### ISSUE TITLE
FBX UV's flipped vertically on import

### ISSUE THREAD

**Issue by Stabberthomas** [armory3d/armorpaint#10]
The UV's of an imported FBX end up flipped vertically. It's not a blocker as I can pre-flip, but it's a turnoff for new users.

**Comment by luboslenco** [comment]
Fixed at https://github.com/armory3d/iron_format/commit/c3fbb9ffaab9fe6921923889e58935ddd3dcc709, will be live in upcoming build. Thanks for report!
