### ISSUE TITLE
Simplify bug report by adding issue template and integrate with bug report tool

### ISSUE THREAD

**Issue by bitinn** [armory3d/armorpaint#100]
This would make bug report and feature requests easier by automating the build number and platforms.

First, setup the issue template:
https://help.github.com/en/articles/creating-issue-templates-for-your-repository

Second, url query to autofill build number:
https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters

Should be pretty easy to do.

**Comment by luboslenco** [comment]
Pressing `Help - Report Bug` button will now auto-fill the build number and platform.
