### ISSUE TITLE
Undo Merging a layer with mask down freezes ArmorPaint

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1000]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-14) - 229498a

**Steps to reproduce:**
Build this situation
![grafik](https://user-images.githubusercontent.com/28649121/121940427-63c61080-cd4e-11eb-9cbf-b07be57f3ce4.png)

- Merge Layer 2 down to Layer 1. This works perfectly
- Undo the operation freezes ArmorPaint

This is similar to #987.
I'd like to link this issue to #792

**Comment by luboslenco** [comment]
Thanks! https://github.com/armory3d/armorpaint/issues/792
