### ISSUE TITLE
Undo mergeing layer down on layer with mask does not restore the mask

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1001]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-14) - 229498a

**Steps to reproduce:**
Build this situation:
![grafik](https://user-images.githubusercontent.com/28649121/121941097-257d2100-cd4f-11eb-8e99-563db3fab3df.png)

- Merge Layer 2 down on Layer 1
- Undo the operation and get 
![grafik](https://user-images.githubusercontent.com/28649121/121941315-65dc9f00-cd4f-11eb-849a-282d25494d58.png)
- The mask is not restored
- Now press redo -> ArmorPaint freezes.
I'd like to link this issue to #792

Finally I'm unsure whether the merge down operation should behave like that or not. I honestly don't know:
Before merge down
![grafik](https://user-images.githubusercontent.com/28649121/121941181-3ded3b80-cd4f-11eb-8b04-6a820b2c8f7b.png)
After merge down
![grafik](https://user-images.githubusercontent.com/28649121/121941235-4d6c8480-cd4f-11eb-87b3-1e8db186263d.png)
Is that correct?

**Comment by luboslenco** [comment]
Thanks! https://github.com/armory3d/armorpaint/issues/792
