### ISSUE TITLE
Angle can be changed for triplanar and project layers in some cases

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1006]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-15) - 238ac27

**Steps to reproduce:**
1. Create a material with a pattern (such that you can see rotations)
2. Create two fill layers.
3. The lower fill layer should be on UV
4. The upper on on tri planar/project
5. Rotate the lower (uv one)
6. Click on the upper on and rotate it

![grafik](https://user-images.githubusercontent.com/28649121/122006973-c30c3b00-cdb7-11eb-997c-ce65060c8174.png)

**Comment by luboslenco** [comment]
Link https://github.com/armory3d/armorpaint/issues/951
