### ISSUE TITLE
Undo merge down layers changes layer object

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1007]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-15) - 238ac27

**Steps to reproduce:**
Build this situation 
![grafik](https://user-images.githubusercontent.com/28649121/122043811-10020880-cddc-11eb-9a05-363a133af43a.png)
Notice that the objects are different.
Now merge it down
Undo the operation. Now the object changed to Shared.
![grafik](https://user-images.githubusercontent.com/28649121/122044989-720f3d80-cddd-11eb-9ad7-a0c746048ef8.png)

Again I'd like to link it to #792

**Comment by luboslenco** [comment]
👍 https://github.com/armory3d/armorpaint/issues/792
