### ISSUE TITLE
Multiple keymaps fails on macOS

### ISSUE THREAD

**Issue by bitinn** [armory3d/armorpaint#101]
Quite a few shortcuts don't work on macOS:

- Many actions involving `ctrl`/`shift`/`tab` appears to fail (nor does `cmd` alternative works), including but not limit to: `file_open`, `file_save`, `file_new`,  `import_assets`, `export_textures`, `cycle_layers`, `toggle_2d_view`, `toggle_node_editor`.
- Middle mouse button doesn't `action_pan`.
- Shift + paint doesn't enable `brush_ruler`.
- cmd + shift + z or ctrl + shift  + z doesn't fire `edit_redo`, but fire `edit_undo` instead.

Things that do work:

- F + drag does change `brush_radius` 
- cmd + z does `edit_undo`
- `view_*` all appears to work by pressing the respective number key.
- `tool_*` all appears to work by pressing the respective letter key.

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/Kode/Kinc/pull/415.

**Comment by luboslenco** [comment]
Some keys still fail, link to https://github.com/armory3d/armorpaint/issues/248.
