### ISSUE TITLE
macOS Big Sur Icon

### ISSUE THREAD

**Issue by Shrinks99** [armory3d/armorpaint#1010]
Sure the icon has rounded corners... but are they round enough? :P

Most applications seem to be adapting their icons for macOS Big Sur so I figured I'd give ArmorPaint a shot as I've done a few of these by now.  I've made 4 versions which range from least-native-looking to most-native-looking, for what it's worth I like option 4.
![Icon-MacOS-512x512@2x](https://user-images.githubusercontent.com/5672810/122106680-3af25980-cde8-11eb-8b89-330c5afb6e8d.jpg)

Here it is in context with some other graphics-related applications

<img width="599" alt="Screen Shot 2021-06-15 at 2 33 02 PM" src="https://user-images.githubusercontent.com/5672810/122106760-4e9dc000-cde8-11eb-8f22-0441fc016daf.png">

Happy to revise and send assets if requested :)

**Comment by luboslenco** [comment]
Please feel welcome to add a macOS specific icon at https://github.com/armory3d/armorpaint/tree/master/Assets/raw/icon, thanks a lot! 🙂
