### ISSUE TITLE
Rights click on element with context menu should also select an element

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1018]
Suppose we have the following situation
![grafik](https://user-images.githubusercontent.com/28649121/122284173-9f4b1100-ceed-11eb-8fab-a013b034a8d2.png)
I selected the first swatch but right-clicked the last one. If I click delete, the last one will be removed (which is correct) but it gives the user a wrong hint because the first one remains selected. Therefore I propose to select the element also by right click to make it more intuitive for users.
The same applies for layers, masks, materials, brushes and so on.

In particular the same applies for nodes as well. If the users right-clicks on a unselected node and no node is selected the context menu is greyed out because no node is selected. If any other node is selected and the user right clicks a unselected node then the selected operation in the context menu will be performed on the selected nodes. This behavior is inconsistent.
Therefore I propose to change that:
1. If the user right clicks a node the current node should be selected and the context menu should perform an operation on this node.
2. If the user presses ctrl to multi-select. The current behavior should remain. 

By doing so the behavior would be consistent with typical file explorers and so on. (Basically every programm that supports multi selection)

**Comment by luboslenco** [comment]
Should work better now.

**Comment by MathemanFlo** [comment]
Yes definitely. It is much more intuitive now. Thank you very much.
