### ISSUE TITLE
macOS retina screen support

### ISSUE THREAD

**Issue by bitinn** [armory3d/armorpaint#102]
Not a top priority and does incur some performance cost, but a nice thing to have.

If implemented, I think there should be 2 toggles, one for viewport and one for UI:

<img width="480" alt="Screen Shot 2019-05-14 at 12 25 16" src="https://user-images.githubusercontent.com/1484279/57670850-b13d9400-7643-11e9-9e64-6d8996e3f2a3.png">

<img width="279" alt="Screen Shot 2019-05-14 at 12 25 24" src="https://user-images.githubusercontent.com/1484279/57670856-b569b180-7643-11e9-9f80-087ea545d522.png">

**Comment by luboslenco** [comment]
All armorpaint builds are now hidpi/retina enabled. The related settings are `UI Scale` (Interface) and `Super Sample` (Viewport).
