### ISSUE TITLE
Trace: TypeError: Cannot read property 'width' of undefined when opening the browser

### ISSUE THREAD

**Issue by jcostello** [armory3d/armorpaint#1021]
**ArmorPaint version:**
0.8 a4b3207

**OS/device including version:**
MXLinux
GT1030

**Issue description:**
When using the browser for materials I get this error and the app freezes
```
Trace: TypeError: Cannot read property 'width' of undefined
    at kha_Image.get_width (<anonymous>:3622:30)
    at <anonymous>:11328:53
    at Array.render (<anonymous>:4376:6)
    at Function.render (<anonymous>:44047:35)
    at renderCallback (<anonymous>:44103:14
```

**Steps to reproduce:**
Open AP
Open the browser
Open the materials folder
I got that error on the console after downloading the materials

**Comment by luboslenco** [comment]
Hello, thanks for report. Please ensure that `wget` command is available / installed in your Linux distribution and that ArmorPaint has permission to write files to disk.
