### ISSUE TITLE
[feature request] Export textures from all visible layers

### ISSUE THREAD

**Issue by bitinn** [armory3d/armorpaint#103]
I am pretty sure people have raised this issue before but couldn't find it here, so:

There should be a way to export texture from all (visible or selected) layers, instead of only export from one layer. The current approach makes ArmorPaint much less useful.

**Comment by luboslenco** [comment]
All visible layers will get exported into a texture by default now. Can by configured with `Export Textures - Layers` combo. If anyone discovers more quirks during export please throw more issues here.

![1b](https://user-images.githubusercontent.com/3685704/58040316-88cb0380-7b35-11e9-8a78-e7429e668685.PNG)
