### ISSUE TITLE
Android Build: Issue with AndroidHtttpRequest.java

### ISSUE THREAD

**Issue by spalius** [armory3d/armorpaint#1032]
ArmorPaint version: master

**OS/device including version:**
Linux, Nokia 6.2, Android 10, Android Studio

**Issue description:**
armorpaint/armorcore/Sources/android/AndroidHttpRequest.java has class, interface, or enum expected errors for lines 3, 6, 7, 8, 9, 10, 11 when trying to run 'app' in Android Studio.

**Comment by luboslenco** [comment]
Hello, please build the desktop version for now. (Still) hoping to make android build process work out of the box as soon as possible.
