### ISSUE TITLE
Blur removes height

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1033]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-25) - a4108bf

**Issue description:**
The blur tool removes the height information (makes it black)

**Steps to reproduce:**
1. Fill a model with a material having a height
2. Try to blur it
Then you get something like this
![grafik](https://user-images.githubusercontent.com/28649121/123420722-32eea280-d5bc-11eb-9fec-62a6bba06b21.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/f32b7909a7f3494401b95b275f12627a38b2fda2.
