### ISSUE TITLE
Clicking the clone tool crashes Krom.app on macOS

### ISSUE THREAD

**Issue by simons-public** [armory3d/armorpaint#1035]
**ArmorPaint version:**

commit 26c04854b857e95d87040bc82110255e553d7c58

**OS/device including version:**

macOS Mojave 10.14.6
iMac (Retina 5K, 27-inch, Late 2015)

**Issue description:**

Clicking on the clone tool crashes Krom.app

**Steps to reproduce:**
- Compile armorpaint for MacOS using steps in README.md
- Run Krom.app from the command line `./Krom.app/Contents/MacOS/Krom`
- Click on the clone tool
- Application crashes with the following output on the terminal:

```
./Krom.app/Contents/MacOS/Krom 
Compilation failed: 

program_source:113:51: error: implicit conversions between vector types ('float3' (vector of 3 'float' values) and 'float2' (vector of 2 'float' values)) are not permitted
vec2 texCoordInp = texelFetch(gbuffer2, ivec2((sp + cloneDeltaLocal) * gbufferSizeLocal), 0).ba;
                                                  ^

Assertion failed: (shader->impl.mtlFunction), function kinc_g5_shader_init, file /dev/armorpaint/armorcore/Kinc/Backends/Graphics5/Metal/Sources/kinc/backend/graphics5/shader.mm, line 51.
Abort trap: 6
```

I tried reverting commit e4914f25b30e4aec970dc591b0fa0ff55598b36d (from the git blame) to see if that made a difference and recompiled. It crashed after clicking the clone tool again with a different error.

```
./Krom.app/Contents/MacOS/Krom 
Compilation failed: 

program_source:114:7: error: cannot initialize a variable of type 'int2' (vector of 2 'int' values) with an rvalue of type 'float2' (vector of 2 'float' values)
ivec2 texpaint_size = textureSize(texpaint_pack_undo, 0).xy;
      ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Assertion failed: (shader->impl.mtlFunction), function kinc_g5_shader_init, file /dev/armorpaint2/armorcore/Kinc/Backends/Graphics5/Metal/Sources/kinc/backend/graphics5/shader.mm, line 51.
Abort trap: 6
```

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/2ce0991fbafceafa440d1c0820f4a7ce1dec748a, thanks for report.
