### ISSUE TITLE
Suggestion for author testing on linux [OpenGL]

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#1037]
I tested the program again, I am a fan and hope to get the software operational. Linux is an important work platform for me and probably for many 3D artists. Currently, there are a lot of bugs that it's hard even for everyone bugs to report, something falls apart, it won't work there, others crash... They suggest that the author should play the software on Linux himself (OpenGL), necessarily with a normal graphics card it may have an impact, I am using Nvidia at the moment (OpenGL). The most important linux systems today are Debian, Ubuntu and possibly Rocky Linux replacing Centos in the future.

Eg. crash Swatches when i click when have loaded tested model, in previev cube work fine
![image](https://user-images.githubusercontent.com/69405892/123814941-62701880-d8f6-11eb-8a63-c931c42152e2.png)

**Comment by luboslenco** [comment]
No plans to give up on Linux, please do not give up on reporting issues as well!
