### ISSUE TITLE
I'm experiencing this issue ("check internet connection to access the cloud") on Win7.

### ISSUE THREAD

**Issue by spamjim** [armory3d/armorpaint#1038]
I'm experiencing this issue ("check internet connection to access the cloud") on Win7. 

ArmorPaint.org - v0.8 (2021-06-16) - e72478b

The cmd.exe window displayed the following error (grabbed with a quick press of the printscreen button):

```

The term 'invoke-WebRequest' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:18
+ Invoke-WebRequest <<<< -Uri 'https://luboslenco.gotlab.io/armorpaint/index/html' -OutFile 'J:\PortableApps\ArmorPaint\.\data\\download.bin'
+ CategoryInfo " ObjectNotFound: (Invoke-WebRequest:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException  
```

The path listed above for download.bin seems odd.

_Originally posted by @spamjim in https://github.com/armory3d/armorpaint/issues/864#issuecomment-871560497_

**Comment by luboslenco** [comment]
Hello, check here https://github.com/armory3d/armorpaint/issues/803. If that does not help and you are unable to use Windows 10 please send me an email for a refund.

**Comment by spamjim** [comment]
Thanks for the instant response! I'm sorry I missed the previous topic. There's no need for a refund. I mostly work in Win10 & Linux (just briefly at a Win7 machine now).   The PowerShell update from https://www.microsoft.com/en-us/download/details.aspx?id=54616 might be a decent temporary resolution to work with this Win7 machine.
