### ISSUE TITLE
[bug] layer "merge down" not working as expected (macOS)

### ISSUE THREAD

**Issue by bitinn** [armory3d/armorpaint#104]
To be honest there are 2 issues here:

- The layer "merge down" doesn't work as I expect, I expected a WYSIWYG result.
- The second issue is undo doesn't work with "merge down" properly, it never restores the original layers (which, to be frank, is memory intensive, but still...)

<img width="366" alt="Screen Shot 2019-05-14 at 12 40 02" src="https://user-images.githubusercontent.com/1484279/57671233-79375080-7645-11e9-86d3-1967abacce0d.png">
<img width="278" alt="Screen Shot 2019-05-14 at 12 40 07" src="https://user-images.githubusercontent.com/1484279/57671239-7f2d3180-7645-11e9-908a-2dad2b863677.png">
<img width="284" alt="Screen Shot 2019-05-14 at 12 40 13" src="https://user-images.githubusercontent.com/1484279/57671243-818f8b80-7645-11e9-903a-d2243ac651aa.png">
<img width="355" alt="Screen Shot 2019-05-14 at 12 40 17" src="https://user-images.githubusercontent.com/1484279/57671248-83594f00-7645-11e9-8a2d-84983d710084.png">

**Comment by SojanJanso** [comment]
This should be separated in two, merge down bug for mac, and feature request to undo layer merges.

**Comment by bitinn** [comment]
I would be happy with just fixing the merge down bug, and perhaps prompt user once about the not able to undo part.

**Comment by luboslenco** [comment]
- Layer merge should give WYSIWYG result now
- Undo for layer operations has been implemented
