### ISSUE TITLE
Armorpaint compilation

### ISSUE THREAD

**Issue by Spirou4D** [armory3d/armorpaint#1040]
Hi,
I compiled your application with Microsoft Visual Studio 16.100.3 2019 with all modules but I had these errors:
https://1drv.ms/u/s!Al4yBRY9NHg-eTdBBYZ7XmMkndQ?e=LBlLZV
Could you help me to this compilation, please.
I'm on Windows 10 64bytes with Node.js and Git like your explain.
My nephew Leo Depoix (leonumeric) explain me for Visual Studio but when I generate the solution, I had these errors!
Thks in advance.

EDIT: I bought you two releases of Armorpaint on Gumroad.

**Comment by luboslenco** [comment]
Hi, thanks for report. You need to build in release mode.

> Build and run for x64 & release

https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-debug-and-release-configurations?view=vs-2019#change-the-build-configuration

See https://github.com/armory3d/armorpaint/issues/719.

**Comment by Spirou4D** [comment]
Ha yes thanks!

Here is my result:
1>   Création de la bibliothèque C:\Users\Patrick\armorpaint\armorcore\build\x64\Release\Krom.lib et de l'objet C:\Users\Patrick\armorpaint\armorcore\build\x64\Release\Krom.exp
1>Génération de code en cours
1>Previous IPDB not found, fall back to full compilation.
1>All 2482 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Fin de la génération du code
1>Krom.vcxproj -> C:\Users\Patrick\armorpaint\armorcore\build\x64\Release\Krom.exe
========== Génération : 1 a réussi, 0 a échoué, 0 à jour, 0 a été ignoré ==========

Is it correct or not?
