### ISSUE TITLE
iOS/Android v8 Build Error

### ISSUE THREAD

**Issue by emmasteimann** [armory3d/armorpaint#1041]
**ArmorPaint version:**

ArmorPaint: 0c9b2efa6415381bf4ed643fe3790378b1e00bcf
ArmorCore: aadda5cf4840563e14532f2c681098617946bf72
Kinc: 9a76ce0
v8_bin: 9a65dcb4f6c0dfe480164b0a16d11ad87c371422

**OS/device including version:**

iPhone X
Samsung Galaxy S20
XCode Version 12.4
macOS 10.15.7
Android Studio 4.0.2

**Issue description:**

When building armporpaint (Krom) for iOS or Android, there is a v8 error:

```
Undefined symbols for architecture arm64:
  "v8::internal::trap_handler::RegisterDefaultTrapHandler()", referenced from:
      v8::internal::trap_handler::EnableTrapHandler(bool) in libv8_monolith.a(handler-outside.o)
  "v8::internal::trap_handler::TryHandleSignal(int, __siginfo*, void*)", referenced from:
      v8::TryHandleWebAssemblyTrapPosix(int, __siginfo*, void*) in libv8_monolith.a(api.o)
      v8::V8::TryHandleSignal(int, void*, void*) in libv8_monolith.a(api.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm struggling to build v8 on my machine to try different versions, nor am I sure which version of v9.0 the v8_bin project is using. But as of filing this bug report v8 is up to 9.2.230.13. So maybe try upgrading and rebuilding. 

**Steps to reproduce:**

Try building for either and you'll see. I've confirmed this with other users as well that they're experiencing the same issue.

**Comment by luboslenco** [comment]
Hi, thanks for report. Building in release mode should resolve that issue. Mobile build process still needs work, sorry - actively working on it.
