### ISSUE TITLE
Max hardness level to 2 and scale radius size to 0.01

### ISSUE THREAD

**Issue by InseminatoreFolle** [armory3d/armorpaint#1044]
The hardness level indicator should go up to the achievable limit of 2 and you should add the possibility to scale the radius of the brush up to 0.01 with the f key.

**Comment by luboslenco** [comment]
Hardness of 1.0 is supposed to be the maximum so that needs to be properly fixed at https://github.com/armory3d/armorpaint/issues/231.

https://github.com/armory3d/armorpaint/commit/d7403ca8af0c95237fd6c1c39f0611b777354828
