### ISSUE TITLE
Packed images that are not a power of two are imported/exported incorrectly

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1045]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-07-05) - 48b64d1

**OS/device including version:**
Win10 DX 11

**Steps to reproduce:**
1. Create a brush/material/... with an image whose size is not a power of two
2. Export it as packed
3. Import it in a new instance of ArmorPaint/restart ArmorPaint

Example:
Initial alpha brush
![grafik](https://user-images.githubusercontent.com/28649121/124428096-87d4aa80-dd6c-11eb-8742-d2c9d2a88c7b.png)
Imported version:
![grafik](https://user-images.githubusercontent.com/28649121/124428124-915e1280-dd6c-11eb-9aa1-125391ff4218.png)

Alpha map whose side is not a power of two
![concrete](https://user-images.githubusercontent.com/28649121/124431761-14816780-dd71-11eb-86cd-8e353681d80b.png)

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/armory3d/armorpaint/issues/1111.
