### ISSUE TITLE
Live Brush Preview breaks masks and fill layers

### ISSUE THREAD

**Issue by Haggets** [armory3d/armorpaint#1046]
*ArmorPaint 0.8-4434112, Windows*

**Issue description:**
When using fill layers and masks with the Live Brush Preview option enabled, it causes masks and fill layers to be unusable, since the selection of fill layers become inaccurate (When selecting say, fill layer 2, it previews fill layer 1), as well as causing masks to be unpaintable no matter what, and completely erasing the contents of a mask after the option is ticked too.

**Steps to reproduce:**
1. Create a fill layer with a mask attached to it, and another right below it (Change colors of both to notice the effect), leaving the default paint layer in the bottom.
2. Paint the mask.
3. Activate the Live Brush Preview in the preferences.

After being ticked, the mask gets completely erased and trying to paint immediately deletes any stroke you do. As for the layers, when previewing the second fill layer, it first seemingly shows the contents of the now deleted mask, or the contents of the first fill layer after deselecting and reselecting, despite it being supposedly hidden by the mask. When selecting the layer mask, it shows the contents of the second fill layer, to then show a combination of both the first and second fill layers when deselecting and reselecting.

Before activation
https://user-images.githubusercontent.com/70298382/124703804-f3c82780-dec0-11eb-9d2a-1bfe24f67b3b.mp4

After activation
https://user-images.githubusercontent.com/70298382/124703816-f9257200-dec0-11eb-904e-676aedd66926.mp4

(Divided in 2 videos since the preference takes a while to activate)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/fc5d87916986818a4075b6bc1d2cd2b3101526a4, thanks for report.
