### ISSUE TITLE
Camera Infinite zoom on mesh

### ISSUE THREAD

**Issue by InseminatoreFolle** [armory3d/armorpaint#1047]
**ArmorPaint version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Sorry I need more info to be helpful.

**Comment by InseminatoreFolle** [comment]
> 
> 
> Sorry I need more info to be helpful.

When I paint the textures in the 2d window (the 2d layer window) and I move the image doing action_pan a bug often happens, the camera in the 3d mesh window when I do action_pan does not do the correct action it does an infinite zoom towards the mesh every time I press the key to do action_pan

**Comment by InseminatoreFolle** [comment]
sometimes the uncontrolled zooming does it even when I press the key for action rotate, I use the keymap blender, I don't know if the bug can also depend on this
