### ISSUE TITLE
How to build with MSYS2

### ISSUE THREAD

**Issue by iwoithe** [armory3d/armorpaint#1049]
Hi there,

Is it possible to build ArmorPaint with MSYS2 on Windows?

Thanks

**Comment by luboslenco** [comment]
Hey! Sorry no experience with that, with ArmorPaint targeting 5 operating systems it's already plenty to keep up. 🙂 It should be doable but you would need to look into https://github.com/Kode/Kinc. The `node Kinc/make -g direct3d11` call is the relevant one.

**Comment by MathemanFlo** [comment]
I think it should be doable. If I was you I would start with the auto generated visual studio solution and use it as an inspiration to build a makefile. ArmorPaint has the advantage that V8 is the only precompiled dependency on windows and all other things are compiled from source. Luckily V8 has a precompiled package for MSYS2. Maybe DirectX is a bit tricky, too. Therefore you might want to try OpenGL (auto-generate the visual studio solution for opengl) in case of issues on this side.

**Comment by iwoithe** [comment]
Thanks for the advice. 🙂

**Comment by iwoithe** [comment]
While I've been playing around with the commands, I've come across this error:

```
C:\path\to\armorpaint\Sources/arm/Translator.hx:5: characters 8-20 : Type not found : arm.sys.File

Haxe compiler error.
```
