### ISSUE TITLE
support channel packing on texture export

### ISSUE THREAD

**Issue by bitinn** [armory3d/armorpaint#105]
Once #103 is supported, the second step would be to support channel packing, which is quite common nowadays:

http://wiki.polycount.com/wiki/ChannelPacking

What Substance Painter does is allow users to define their own export template, which allow users to channel swizzle freely.

ArmorPaint's node graph should be quite perfect for this application: in the same way Substance Designer or other node-based shader authoring tools would work.

(EDIT: to be fair there is already channel packing for UE4 ORM map but I think we could have more options)

**Comment by luboslenco** [comment]
Should be doable now through the new preset editor located at `File - Export Textures... - Presets`.
