### ISSUE TITLE
ArmorPaint crashes in mask mode

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1053]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-07-13) - 014f400

**OS/device including version:**
Win10 x64

**Issue description:**
ArmorPaint crashes if a non shared material is used in conjunction with mask mode

**Steps to reproduce:**
1. Open ArmorPaint and use the default rounded cube
2. Add a black mask to the first layer, the black mask should be selected now
3. Select .Cube instead of Shared for Layer 1 
3. Select mask mode in the mode menu
4. ArmorPaint crashes

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/e5a4f7a222b1a9a5b5e3d0e2253dcd2b8ed3c840, thanks for report!
