### ISSUE TITLE
Materials in material id view have noisy borders

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1054]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-07-13) - 014f400

**OS/device including version:**
Win10 x64

**Issue description:**

1. Create two materials
2. Paint with them such that the two materials have a shared border
3. Switch to material id view and get a result like this

![grafik](https://user-images.githubusercontent.com/28649121/125613209-fa7c257e-6062-4aa8-88d9-a9cc8c1fcb95.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/f6d92f6aec69abbbb19e5160bb01a75b68340295, thanks for report.
