### ISSUE TITLE
Text tool UV scale incorrect

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1055]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-07-13) - 014f400

**OS/device including version:**
Win10 x64

**Issue description:**
1. Select the text tool
2. Change the UV scale
3. Stamp some text and get this result

![grafik](https://user-images.githubusercontent.com/28649121/125619409-2a6d441c-b936-4ed9-b778-d9dd98dff321.png)
The "text-matrix" is what you can see, the single big "text" is what you get.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/e202ca6a2f2bf961e53ab79589d0f2ac7bc65347.
