### ISSUE TITLE
Mode menu has inconsistent behavior

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1057]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-07-16) - e5a4f7a

**OS/device including version:**
Win10 x64

**Issue description:**
The mode menu has various options such as Lit, Occlusion and so on. Sometimes when I choose a mode the menu closes, sometimes not. Unfortunately I have no deterministic steps to reproduce this but I think it has something todo with my mouse movement like not changing the x-coordinate or something like that. 

I think the desired behavior would be: close the menu in any case.

**Comment by luboslenco** [comment]
Sorry not able to reproduce it. :( The menu should close in all cases. Hopefully more people report this and then it may get more obvious how to fix it.

**Comment by MathemanFlo** [comment]
Thank you for investigating this. I can't reproduce it anymore, too.
