### ISSUE TITLE
[feature request] make layer channel toggle easier

### ISSUE THREAD

**Issue by bitinn** [armory3d/armorpaint#106]
I don't want to flood the issues but I think it's worth noting these 2 things:

- The current layer channel toggle menu closes after a single click, that's annoying when you want to toggle multiple channel to off/on.

- The current layer duplication doesn't copy channel settings, it's default to `on` for all channels, so you have to toggle them all again.

<img width="282" alt="Screen Shot 2019-05-14 at 13 18 13" src="https://user-images.githubusercontent.com/1484279/57672503-f5806280-764a-11e9-8751-4b70be04d3f3.png">

**Comment by luboslenco** [comment]
(Don't mind the flood and thanks for taking time to raise those issues, it's gold!)

**Comment by luboslenco** [comment]
Both issues should be resolved now in the latest builds.
