### ISSUE TITLE
Scrolling through combo boxes also zooms if the underlying area is zoomable.

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1062]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-07-19) - 832ee79

**OS/device including version:**
Win10x64

**Issue description:**
Scrolling through combo boxes also zooms if the underlying area is zoomable. Examples are the TexCoordinate/Blending combo box and the viewport, Texture/Layers combo box and the 2d view. By suitable resizing the TextCoordinate/Blending combo box can also zoom the node editor.

**Steps to reproduce:**
1. Open the Blending combo box
2. Scroll to select an item (which is a pretty awsome feature)
3. The viewport zooms as well

**Comment by luboslenco** [comment]
Should be resolved now, thanks for report.
