### ISSUE TITLE
[bug] UV-Scaling not working when using ColorID

### ISSUE THREAD

**Issue by SpicyMemeBoi** [armory3d/armorpaint#107]
When applying a material to a part of a mesh using colorID, any scaled textures using the mapping-node in the material are still scaled but won't tile. They simply stretch. When applying the material to the entire mesh however, the textures tile properly.

**Comment by luboslenco** [comment]
@SpicyMemeBoi many thanks for posting here! This issue should be resolved in the latest builds, please let me know if you get to test it.
