### ISSUE TITLE
Show names hover preview

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1070]
Currently ArmorPaint has
- the feature to hover over a texture or material to preview it.
- The option to show the texture/material/... names below the icon. Most of the time the name is too long to be shown completely, therefore ArmorPaint allows for hovering over the name to show a tooltip with the whole name.

It would be great if the name would also be shown below the preview if the user hovers over the icon to preview the texture/material/... (even if the option to show the names is disabled)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/d581933109916d271e968381169e081ab643d191.

**Comment by MathemanFlo** [comment]
Great! Love it.
