### ISSUE TITLE
Double clicking on a font results in ui glitch

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1072]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-07-28) - 8c84f42

**OS/device including version:**
Win10x64

**Steps to reproduce:**

1. Go to Fonts tab
2. Double click the default font and get
![grafik](https://user-images.githubusercontent.com/28649121/127393884-7efdfeaa-c970-486f-b2de-85c948b9c4ac.png)

Hovering the 2D View button also previews the the font.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/1ae19b32b38d680de4557f06ec9b943d1665ec48.
