### ISSUE TITLE
krom_cache:1065: Uncaught ReferenceError: Krom is not defined

### ISSUE THREAD

**Issue by wilsoft-gt** [armory3d/armorpaint#1076]
**ArmorPaint version:**
v0.8 github

**OS/device including version:**
Ubuntu 20.04.2lts
Linux 5.4.0-80-generic #90-Ubuntu x86_64

**Issue description:**

When I try to compile a release build I always get this error:

###Error 1
`krom_cache:1065: Uncaught ReferenceError: Krom is not defined`
The krom.bin file is generated successfully but when I try to run I get this other error:

###Error 2
`bash: ./krom.bin: cannot execute binary file: Exec format error`

I'm not sure if I'm missing any step during the compilation.

**Steps to reproduce:**

1) Follow the instructions to compile for linux
2) Go to ./build/krom and compile the krom.js with closure
3) Run from base dir: node armorcore/make -g api --snapshot
4) Go to: armorcore/Deployment
5) Run the following command and error 1 will apear: ./Krom ../../build/krom --snapshot 
6) Go to build/krom, give excecution rights to the krom.bin file and then tried to run and got the error 2.

**Comment by luboslenco** [comment]
Hello, the program is still to be run via `Krom` as before.  `krom.bin` file only replaces `krom.js`.
