### ISSUE TITLE
Wrong tooltips

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1077]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-04) - f6d92f6

**OS/device including version:**
Win10x64

**Issue description:**
The 2D-View button in Textures, Fonts and the Restore button in Swatches shows the last tooltip of the items below. 

**Steps to reproduce:**
1. Hover the Restore button in Swatches
2. Get 
![grafik](https://user-images.githubusercontent.com/28649121/128146396-21398283-f421-4347-a0b1-1013bc49c513.png)

I debugged it and found out the issue is the function getHover in line 1554 of Zui.hx. The problem is that in these cases the condition in 1555 is true and therefore the last item (the last color swatch, font, texture) does not update the isHovered member and therefore the wrong tooltip is shown. I do not exactly understand this condition but probably this branch should also update isHovered to false or something like that.

Edit: I forgot to mention I have turned ON asset names. If asset names are turned off hovering the 2D-View button in the Texture tab shows the last texture as tooltips instead of its name.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/zui/commit/9fdc3c755a85c9208e73bb1c23f196f08737bc0f, thanks for report.
