### ISSUE TITLE
Unrolled buttons in bottom bar are too narrow for some locales.

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1078]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-04) - f6d92f6

**Issue description:**
e83ebdb79ce6ed6b742b348076132d0af648ee69 unrolled the menu buttons which is a great improvement. Unfortunately the button's widths are fixed and do not adapt if the text is too long. Clearly the english locale is fine:
![grafik](https://user-images.githubusercontent.com/28649121/128148600-522db14b-e184-4f69-8095-b4a0ee1adc61.png)
But for example the german locale looks ugly now (and so do other)
![grafik](https://user-images.githubusercontent.com/28649121/128148687-45f8d7e8-8aa8-4b82-83fe-a2ecd098930c.png)

**Comment by luboslenco** [comment]
Should be better after https://github.com/armory3d/armorpaint/commit/9e8e31fc5bf6f845742d3dcec90ee8e6de112ee5, will do proper variable size buttons eventually.

**Comment by MathemanFlo** [comment]
Super cools. Thanks!
