### ISSUE TITLE
Improve bake tool

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armorpaint#108]
Bake tool only supports baking voxel-traced AO map. To do:
- ~~AO (ray-traced / DXR build)~~
- ~~Curvature~~
- ~~Cavity (ray-traced / DXR build) - use AO bake + low radius~~
- ~~Height (from high-poly)~~
- ~~Bent Normals (ray-traced / DXR build)~~
- ~~Derivative Normals (from high-poly)~~
- ~~Tangent Normals (from high-poly)~~
- ~~Normals (Object)~~
- ~~Position~~
- ~~Material ID~~
- ~~Object ID~~
- ~~Lightmap (ray-traced / DXR build)~~
- ~~Thickness~~
- ~~Vertex Colors~~

**Comment by cgvirus** [comment]
Hello, What is the workflow for baking normal map from High poly to Low poly? searching for some documentation in the manual. A step by step text or video would be really helpful. 
Thanks.

**Comment by luboslenco** [comment]
Check https://www.youtube.com/watch?v=Gsq20kQ6ddY for current state of affairs. 🙂
