### ISSUE TITLE
when you save the project, the fill layers turn into painting layers

### ISSUE THREAD

**Issue by sanya-2005** [armory3d/armorpaint#1080]
ArmorPaint version: commit: 7bf061a25e2eafd3170fd575bdf47038ab93cf41

**Issue description:**
I saved the project and closed the program. then reopened it, and all the fill layers turned into painting layers
before saving and closing program
![Снимок экрана 2021-08-04 235820](https://user-images.githubusercontent.com/88460753/128255588-03643b2a-6423-4b98-8d4c-c26abe3e9102.png)
after i opened the project
![Снимок экрана 2021-08-04 235916](https://user-images.githubusercontent.com/88460753/128255787-2684fd36-ed1c-4137-906b-fe9d4f813c47.png)

**Comment by MathemanFlo** [comment]
I could not reproduce this on the same version. Maybe there are some hidden steps involved .

**Comment by luboslenco** [comment]
Please reopen the issue if you get to reproduce it again.
