### ISSUE TITLE
the program breaks after right-clicking on the brush

### ISSUE THREAD

**Issue by sanya-2005** [armory3d/armorpaint#1081]
**ArmorPaint version:** commit 7bf061a25e2eafd3170fd575bdf47038ab93cf41

**Issue description:**
I right clicked on the brush in the brushes menu. after which the preview of the clicked brush and the title where you could select the section with materials, brushes and particles disappeared
![Снимок экрана 2021-08-05 002724](https://user-images.githubusercontent.com/88460753/128257266-9349b509-25a4-4066-9360-1c91e5dc9f35.png)

when you clicked anywhere on the screen after that, this popped up and the program hung:
![Снимок экрана 2021-08-05 002135](https://user-images.githubusercontent.com/88460753/128257501-42906ef2-de47-42b6-9a9e-52a598068940.png)

**Comment by MathemanFlo** [comment]
I also could not reproduce this on the same version. Maybe your project has some properties I did not have while testing.

**Comment by sanya-2005** [comment]
hike you are really right. I tried to re-create the project (transfer all meshes and save) and no problems were observed. since this is so, then I will do it all over again, since I haven't gone too far

**Comment by MathemanFlo** [comment]
If this should ever happen again you can always export a layer as textures and import them in another project. Simply create a new material with the exported textures and fill a new layer with UV-Scale 1 then you have the same layer back.

**Comment by luboslenco** [comment]
Please reopen if you get to reproduce it again.
