### ISSUE TITLE
Brush preview only works after changing the brush or save and reload

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1082]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-04) - 7bf061a

**OS/device including version:**
Win10 x64

**Steps to reproduce:**

1. Create a new brush by clicking on the "New" button and get 
![grafik](https://user-images.githubusercontent.com/28649121/128291721-83db5a51-4894-45fa-b1d9-116a53e61319.png)

2. Hover the newly created brush and wait for a preview 
3. Nothing will happen

Now there a two ways to resolve the problem
1. Save and reload the project. The brush icon changes 
![grafik](https://user-images.githubusercontent.com/28649121/128291757-761fab8e-4958-4675-a4b3-8ddd32d439b8.png)
and a preview is available
2. Edit the brush. The icon gets updated immediately and a preview becomes available, too.

**Comment by MathemanFlo** [comment]
I also wanted to mention that there are these thin grey stripes between the icons. 
![grafik](https://user-images.githubusercontent.com/28649121/128462911-a6e818f6-f747-49a7-8880-de32d1b9c554.png)
They go away if the icon is updated but newly created brushes have one on the left side

**Comment by luboslenco** [comment]
Should be resolved via https://github.com/armory3d/armorpaint/commit/8b43e2f7f27e0253970b408280944fab238c751e, thanks for report.
