### ISSUE TITLE
changing the button for hiding masks on the fill layer

### ISSUE THREAD

**Issue by sanya-2005** [armory3d/armorpaint#1083]
I suggest replacing the icon for the button that hides the mask on the fill layer from a minus to an arrow. when the masks are not hidden, it will look up, and when hidden, it will look down. here is an example
![Снимок экрана 2021-08-05 111849](https://user-images.githubusercontent.com/88460753/128317738-8d3b9a38-e3a0-4ae2-8b78-64e38a04c247.png)
![Снимок экрана 2021-08-05 112031](https://user-images.githubusercontent.com/88460753/128317854-f32778e2-6a75-4aee-b7b4-3ad7803aa12e.png)

**Comment by luboslenco** [comment]
👍  linking with https://github.com/armory3d/armorpaint/issues/1069, please feel welcome to post even more suggestions there.

**Comment by Wario-Ametrano** [comment]
hello, it's interesting your idea but it doesn't bring a really useful change an arrow from a plus one doesn't change much as a symbol, but your idea is interesting and so maybe I can propose an my alternative of your idea,I used an arrow like you did but with the name of the mask or the type of level next to it, I also tried to change the order and the look, maybe it can interest you.
![coso](https://user-images.githubusercontent.com/86927539/128353087-2bbb1dff-36b7-4f30-adaa-9ac36ffcad58.gif)

**Comment by Wario-Ametrano** [comment]
This is my idea of how layers and masks could look like, I already wrote this idea in another post but I'm writing it here to get all the ideas on here.Add an arrow with the name of the layer type, below the name of the main layer.I think this way you have more space for the name of the main layer and it is also clearer which layers you are using.
![coso](https://user-images.githubusercontent.com/86927539/128353995-91ba0441-ee42-4e30-a4d4-c85c889a8a3d.gif)
