### ISSUE TITLE
improve work with the Color Ramp node

### ISSUE THREAD

**Issue by sanya-2005** [armory3d/armorpaint#1085]
working with the color ramp node is not convenient. why not make it like it is done in blender, that is, a strip on which the sliders are located?
![Снимок экрана 2021-08-05 190455](https://user-images.githubusercontent.com/88460753/128383262-3a655608-7cfc-4be7-b4e4-b79723642f28.png)
yes, although this feature is small, it will make your work easier and improve the overall impression of ArmorPaint

**Comment by luboslenco** [comment]
Hoping to properly match up all nodes at https://github.com/armory3d/armorpaint/issues/36.

**Comment by soundsbeard** [comment]
i wonder, why this is closed. color ramp node is still unintuitive.

**Comment by rpaladin** [comment]
@soundsbeard this issue was closed in favor of the earlier duplicate issue #36 as Lubos mentioned above. Lubos tends to close 'duplicate' issues to reduce extra spam / wasted time.
