### ISSUE TITLE
Text input controls loose their newly appended text

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1087]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-06) - 8b84e4c

**OS/device including version:**
Win10x64

**Steps to reproduce:**
1. Open ArmorPaint and the Browser
2. Initial situation ![grafik](https://user-images.githubusercontent.com/28649121/128541478-e353930a-b54a-4cca-9aef-928524da8e65.png)
3. Click on the control to start typing. The whole text gets selected (a not so well chosen behavior in my opinion) therefore we can not start typing in case text should be appended ![grafik](https://user-images.githubusercontent.com/28649121/128541505-ecaa3ae2-2ce2-4f8b-ab58-59865c9776c9.png)
4. Press the Right key on the key board to unselect everything. Now text can be appended ![grafik](https://user-images.githubusercontent.com/28649121/128541536-0f960060-2f97-4b62-bbaf-0dbdca997dea.png)
5. Click on the edit control again. The appended text is gone ![grafik](https://user-images.githubusercontent.com/28649121/128541580-64213323-8e21-4964-a250-6599a88b3c76.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/zui/commit/61187f00720a6ae9e3f85b7b043e16b5cc7eb2aa.

**Comment by MathemanFlo** [comment]
Great! The text input control becomes better and better.
