### ISSUE TITLE
I can only build armorpaint with `project.cpp14 = true`

### ISSUE THREAD

**Issue by sprhawk** [armory3d/armorpaint#1088]
**ArmorPaint version:**

 0.8dev or master (b00b9288bc6815f4267a0fab19a9506a83ff4711)

**OS/device including version:**

 Debian 11

**Issue description:** 

for default build, it failed with log:
```
../../v8/include/v8-internal.h:452:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
```

**Steps to reproduce:**

** My Fix: **

I changed `armorcore/kincfile.js`, replace `project.cpp11 = true` with `project.cpp14 = true`, it compiled and run

**Comment by luboslenco** [comment]
C++17 is now set as the default.
