### ISSUE TITLE
Undoing "merge down" freezes armorpaint

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#1089]
ArmorPaint.org - v0.8 (2021-08-09) - b00b928

Windows 10 - Direct3D11
Intel(R) HD Graphics 620  (non-DXR ) 

**Issue description:**
Undoing Merge down current layer with the underlying one freezes Armorpaint.
Merge down by itself, for some weird reason, changes the look of the texture as it was before layer merging.

**Steps to reproduce:**
Merge down current layer with the underlying one.
Undo the operation.
Armorpaint freezes.

**Comment by luboslenco** [comment]
Undo fixes incoming, linking with https://github.com/armory3d/armorpaint/issues/792. Thanks for report!
