### ISSUE TITLE
Changing blending modes in the node editor should auto-update the viewport

### ISSUE THREAD

**Issue by ssnd292** [armory3d/armorpaint#109]
The title should be pretty self explanatory:

Let's say I have a MixRGB node and I blend the node, I'd appreciate it if the viewport would auto-update without me having to fill the material in every time.

I think having that a toggable option is a good idea.

**Comment by luboslenco** [comment]
Linking with issue https://github.com/armory3d/armorpaint/issues/114, will do more work to expose fill layer functionality better.
