### ISSUE TITLE
Combo box shows black border

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1096]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-13) - 8131ede

**Issue description:**
![grafik](https://user-images.githubusercontent.com/28649121/129342912-bf3cb5cf-86f9-4a01-a72b-06c62a080211.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/3b33226369433f57aef9f8836ad0ff13ce0e9ae6, thanks!
