### ISSUE TITLE
Material menu inconsistent with Main menu

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1097]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-13) - 8131ede

**Steps to reproduce:**
Clicking on the caption of an expanded node menu e.g. Converter in the following example does not close the menu. This behavior is inconsistent with the main menu.
![grafik](https://user-images.githubusercontent.com/28649121/129343189-9f632e5d-2dad-49f4-8c9c-96dc5ce46d6a.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/04803f588dfb168599a04c9e2244857b33035047.
