### ISSUE TITLE
Paint layer icons have border on the left

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1099]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-15) - 04803f5

**OS/device including version:**
Win10 x64

**Steps to reproduce:**
I found yet another tiny ui glitch.
1. Open ArmorPaint
2. Look at Layer 1's icon. The left border shows parts of the checker transparency pattern.
![Screenshot 2021-08-15 171945](https://user-images.githubusercontent.com/28649121/129483522-57852e0d-bd16-4641-bd02-66f29f648972.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/fc2156f3a2bb075eb128e69db0404664d388deb1. 👍
