### ISSUE TITLE
Unlit output node

### ISSUE THREAD

**Issue by bitinn** [armory3d/armorpaint#110]
I think ArmorPaint's material node system is very closed to shader graph system in other game engines. So it's ripe for making custom shaders.

The use case here is I would love to match my in-game rendering when I author textures, having an unlit output node will help.

(I imagine many indie games are in the same boat where we use NPR instead of straight PBR.)

**Comment by brunomrsn** [comment]
It would be good for painting diffuse only 3D models for low-end devices. (If I didn't misunderstand)

**Comment by bitinn** [comment]
@brunomrsn correct, or build a custom blinn-phong shading if one wishes.

Since PBR output node is already available, I think an Emission/Diffuse-only node like Blender should be fairly easy to add? This + material node means users can manage how shading is done in ArmorPaint.

**Comment by luboslenco** [comment]
There is a way to customize viewport shading via plugins now. Added a simple celshade example at https://github.com/armory3d/armorpaint/commit/6e03b7ef8d30976568287d95421fb7606e08a25a, more to come.
