### ISSUE TITLE
dark vertical line in preferences setting

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#1103]
ArmorPaint.org - v0.8 (2021-08-12) - c66d753
Win 10 64 bit

Hello Lubos! Purely by chance I noticed one little thing. In the program settings, in the Theme rollout. When I open the drop-down list with a choice of theme, then such a vertical line appears. This is just a trifle. But still...
![image](https://user-images.githubusercontent.com/65244629/130045958-56aa1951-46c6-40fa-9723-4fe1f7afc2dc.png)

**Comment by luboslenco** [comment]
Check https://github.com/armory3d/armorpaint/issues/1096.

**Comment by AlexKiryanov** [comment]
Thanks. I will update the version)
