### ISSUE TITLE
Color picker color selector is bigger than its panel

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1105]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-27) - 1d01f56

**OS/device including version:**
Win10x64

**Issue description:**
The color selector is again higher than the panel. Also the border is slightly incorrect.
![grafik](https://user-images.githubusercontent.com/28649121/131096865-4eb92afd-f8fe-49f2-a24f-ec81e4c2aafb.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/2947dff2f060acf770d9d292e73d29eff02146c1.
