### ISSUE TITLE
Improve color picker widget

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1106]
- [x] ~~The color picker widget used for picking a color for swatches, in the color picker tool, the preferences and probably elsewhere has no preview of the currently picked color.~~
![grafik](https://user-images.githubusercontent.com/28649121/131098464-0f726f67-6a78-484d-a896-0430edc5b5d9.png)
The RGB node has
![grafik](https://user-images.githubusercontent.com/28649121/131098402-213b4619-4ead-4d74-9ac5-6b6a378f8624.png)

- [x] ~~I propose to unify both and show a preview in both cases. Currently it is very hard to pick an exact shade because there is no preview~~. 

- [x] ~~Additionally I propose to not close the picker widget if the color wheel was used. I think this is a reasonable behavior because~~
- ~~It is also not closed if R,G,B or H, S, V is changed~~
- ~~The user doesn't have to reopen the picker for adjustments if the first color choice was not perfect.~~

- [x] ~~As a third proposal I suggest to change the behavior of the HEX value edit.~~

1. [x] ~~Currently if the user clicks on it, the whole content is selected. To unselect it the user typically has at least two choices: 1. click again, 2. press an arrow key. The first option does not work in this case because the picker is immediately closed (swatch color picker). This behavior should be changed in order to be consistent with other places like the color hex value edits in the Theme-editor in the preference dialog.~~
2. [x] ~~In addition it would be nice if the edit would support 6-digit hex codes, i.e. missing alpha. In case the code is 8 digit the behavior should remain, in case the code is 6 digit, two 'f' should be appended at the front.~~
3. [x] ~~In case the user inserts an invalid code, e.g. the code contains an 's'. The color picker changes its value to some 1-digit string. Sometimes it is '0', sometimes something else. I suggest to use a valid color code in this case.~~
4. The hex edit allows for transparent colors, but this ability is not reflected in the tabs for RGB and HSV. Further more it is only supported in preview for swatches but not for the RGB node. I.e. if the users drags a semi-transparent swatch to the node editor, the alpha channel is set to 'ff'. 
![grafik](https://user-images.githubusercontent.com/28649121/131112624-67394cc8-6054-488d-ba50-fa94c906f2bd.png)

**Comment by AlexKiryanov** [comment]
You are welcome! @MathemanFlo (Florian))
if I did so many topics, I think I could forget about some of them too)))

**Comment by paolohuesp** [comment]
I would also like to add something, if a black / white bar can be added to the RGB node to be able to darken or lighten the color as it is in blender.

**Comment by MathemanFlo** [comment]
> 
> 
> I would also like to add something, if a black / white bar can be added to the RGB node to be able to darken or lighten the color as it is in blender.

The HSV tab has a slider for V that does what you suggest. But clearly it is not exactly what you suggest.

**Comment by MathemanFlo** [comment]
I have yet an additional idea. Currently the picker tool does not allow for transferring a color to a RGB node or swatches (proposed in #892). As it is hard to transfer a picked color to a specific rgb node I propose a picker button like in Blender for all color picker widgets in ArmorPaint. 
![grafik](https://user-images.githubusercontent.com/28649121/135243489-a6a8541f-ac9b-40db-a92b-54b28c8c15ca.png)

**Comment by l0ud** [comment]
@MathemanFlo this Eyedropper idea from blender seems to be a particularly useful in my case, when I try to pick colour from opened 2d image. Unfortunately current picker tool doesn't support sampling from 2d textures.

**Comment by MathemanFlo** [comment]
@l0ud I think this is a great idea for several reasons. Would you please create a feature a separate request for your idea? I will then add my ideas and comments there.

**Comment by l0ud** [comment]
@MathemanFlo sorry, I must have missed your response. I created separate feature request as requested.
