### ISSUE TITLE
Changing a swatch color also changes the color picker tool's color.

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1108]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-27) - 1d01f56

**OS/device including version:**
Win10x64

**Issue description:**
1. Change a swatch color.
2. The color picker's color changes accordingly.
![grafik](https://user-images.githubusercontent.com/28649121/131101550-013271db-49be-440d-80d3-12b9eeacfc5d.png)

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/892.
