### ISSUE TITLE
Texture to mask changes button colors

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1109]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-27) - 1d01f56

**OS/device including version:**
Win10 x64

**Steps to reproduce:**
1. Open ArmorPaint
2. Import a texture
3. Right click on it and select "to mask"
4. The buttons become darker and a black mask appears

After importing the texture
![grafik](https://user-images.githubusercontent.com/28649121/131139383-464fb54d-c5e3-4bb7-a8e7-96acca2d9009.png)

After clicking on "to mask"
![grafik](https://user-images.githubusercontent.com/28649121/131140021-c795ba62-b6c5-469e-936d-bda7f7468e77.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/e11cf49f67b8edae1f1b70e06dd291c472c3069d, thanks for report!
