### ISSUE TITLE
[bug] not able to create new brush or new particle brush

### ISSUE THREAD

**Issue by bitinn** [armory3d/armorpaint#111]
When I clicked on the `New` button under Brush or Particles panel, it does nothing.

I assume either an explanation is lacking here or it simply isn't implemented yet?

(Clicking on `Nodes` under Brush panel does show the Brush graph; but `Nodes` under Particles doesn't seem to do anything neither.)

<img width="279" alt="Screen Shot 2019-05-22 at 12 09 56" src="https://user-images.githubusercontent.com/1484279/58146873-a9f13880-7c8a-11e9-9058-3e721e39a3db.png">

Using v0.6 May-20th build on macOS.

**Comment by luboslenco** [comment]
New brush nodes can be created now in latest builds, particle nodes still to go at https://github.com/armory3d/armorpaint/issues/34.
