### ISSUE TITLE
Texture reimport clears image view

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1110]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-27) - 1d01f56

**OS/device including version:**
Win10 x64

**Issue description:**
Reimporting a texture while showing it in the image viewer clears the image viewer instead of showing the reimported image

**Steps to reproduce:**
1. Import texture
2. Open the texture in the image viewer
3. Reimport the texture
4. The image viewer gets cleared and no image is shown until the user presses 2D View again.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/355b0127087a3f58c7cfc7f28e0065bf02c51a37, thanks for report.
