### ISSUE TITLE
Exporting one mesh automatically exports all meshes

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1113]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-27) - 1d01f56

**OS/device including version:**
Win10 x64

**Issue description:**

**Steps to reproduce:**
1. Create a new project with rounded cube
2. Append the following mesh and split it by material
[FassMP.zip](https://github.com/armory3d/armorpaint/files/7067879/FassMP.zip)
3. Now there are three meshes 
![grafik](https://user-images.githubusercontent.com/28649121/131147865-8044e0b5-1323-480c-86cf-620ccdc7671e.png)
4. Export one of them.
5. Load the exported mesh into another software like Meshlab
You can see that 
- ArmorPaint exported all of them
- ArmorPaint exported a mesh that produces warnings (identical vertex indices in the same face), so maybe there is an additional bug in the mesh exporter

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/2679bb72db115790c054a6b69c8fa260883f8d90.

> ArmorPaint exported a mesh that produces warnings (identical vertex indices in the same face), so maybe there is an additional bug in the mesh exporter

The obj format should be valid, but you can further reduce the file size in a mesh editing program.
