### ISSUE TITLE
Flipped normals are flipped back if the mesh is rotated

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1114]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-27) - 1d01f56

**OS/device including version:**
Win10 x64

**Steps to reproduce:**
1. Create a new project with the plane
2. Flip normals
3. Rotate Z
The normals are flipped back.

Further more I'm not sure whether I understand the normals correctly. In my opinion they should indicate the outer side of a face. I.e. flipping a plane should exchange both sides. Clearly ArmorPaint does not do it. What does it actually do?

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/8002eacddc2d9d13108e7bae15ecdb16d1d80893, thanks for report! It basically just flips the pointing direction of vertex normals which are used for calculating the lighting.
