### ISSUE TITLE
Color picker tool 2d position is shown in font view.

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1115]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-08-27) - 1d01f56

**OS/device including version:**
Win10 x64

**Issue description:**
The small circle to indicate the color picker tool's position is not only shown for texture 2d view but also for font view. Unfortunately the mouse cursor is missing, it is next to the "white ball". Clearly this is a small glitch.
![grafik](https://user-images.githubusercontent.com/28649121/131162162-eccb1e65-4269-4b93-9a77-1febe552552a.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/94fc80783b5313f79cb4adaab0f61370796c55db.
