### ISSUE TITLE
[bug]Eraser doesn't work on 2D

### ISSUE THREAD

**Issue by WhiteTiger-21** [armory3d/armorpaint#112]
I can erase painted on 3D view.But can't on 2D excepting layer 1.
The places erased on 3D view are painted on 2D view and exported same to 2D view.
I'd like to export textures by layers.
I'd like you to work alpha on 2D.
Thank you a lot for your work.
![image](https://user-images.githubusercontent.com/12580960/58144975-7cf15580-7c8b-11e9-81c9-c3847a526933.png)

**Comment by luboslenco** [comment]
New builds are up and eraser should behave correctly now. Thank you for reporting this issue!
