### ISSUE TITLE
Decal and text tool in split view produce visual artifact

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1125]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-09-06) - e11cf49

**OS/device including version:**
Win10 x64

**Issue description:**
![grafik](https://user-images.githubusercontent.com/28649121/132311101-e576706f-b370-4c35-b8f4-bd9025ff7889.png)

**Steps to reproduce:**
1. Turn on split view.
2. Select the Decal or the Text tool.
3. Hover the border between the two views. (without stamping)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/464a22bd7d66206215a7ef3931863d873e63cee8.
