### ISSUE TITLE
Brush hardness does not work over painted areas

### ISSUE THREAD

**Issue by NNatsios** [armory3d/armorpaint#1127]
*ArmorPaint 0.8-558a5d7, Windows*

**Issue description:**
Brush hardness does not work over painted areas
Painting over existing colors in paint or mask layer does not take bush hardness into account.

**Steps to reproduce:**

![NN_2021-09-10_1809](https://user-images.githubusercontent.com/46283788/132844184-f955b9cc-007b-4205-bd59-de631549465e.png)

**Comment by MathemanFlo** [comment]
I think this is the same as #595.

**Comment by luboslenco** [comment]
Will fix at https://github.com/armory3d/armorpaint/issues/595, thanks for report.
