### ISSUE TITLE
Compile error on macos

### ISSUE THREAD

**Issue by robw001** [armory3d/armorpaint#113]
I updated armorpaint from Github today, and tried running it with a daily build of Blender (compiled from source) on Macos 10.14.5

I get a bunch of Haxe compile errors when hitting Play, see the attached file. Cleaning and rebuilding does not help.

[aperrors-20190523.txt](https://github.com/armory3d/armorpaint/files/3211332/aperrors-20190523.txt)

**Comment by luboslenco** [comment]
Hello @robw001, updating armory to the latest [git version](https://armory3d.org/manual/#/dev/gitversion?id=armory-updater) should do the trick. You may still experience more kinks on macos as opengl is now deprecated and I still have some work to do before we can switch to the metal backend..

Hope that helps!

**Comment by robw001** [comment]
Hi @luboslenco,

Running into a new problem now: cmft is not playing nice. It is locking (beach ball), then hanging my iMac (2019 model witha  Radeon RX580 Pro). Could that also be from deprecating openGL/CL?

**Comment by robw001** [comment]
Hi @luboslenco,
Did an update on Armory, now running into a new problem: cmft seems to not play nice with my machine. It hangs (beach ball), then locks the machine. Replacing it with a downloaded version from the cmft github page did not help.

I cannot check if this solves the compile errors.

**Comment by luboslenco** [comment]
I am building on 2014 MacBook Pro but unable to trigger this. 😢 I will try to check on another machine, thanks for letting me know. Will also look into decoupling cmft from the armorpaint build process.

**Comment by robw001** [comment]
thanks!
