### ISSUE TITLE
Blur doesn't seem to work

### ISSUE THREAD

**Issue by NLEGITN** [armory3d/armorpaint#1130]
*ArmorPaint 0.8-e11cf49, Windows*

Hello, I am using Armor paint and Blur doesn't seem to work.  Any model I am working on when I blur nothing happens.

I drag a 3d model in and add a new paint layer and choose a color and paint on my object and then I select blur and it does nothing.

**Comment by MathemanFlo** [comment]
Are you sure you blur the same layer you painted? The blur tool does only blur the content of the current layer and is not affected by other layers.

**Comment by luboslenco** [comment]
Assuming this is outdated https://github.com/armory3d/armorpaint/issues/1135.
