### ISSUE TITLE
Odd Camera Drift

### ISSUE THREAD

**Issue by calebn2020** [armory3d/armorpaint#1131]
**ArmorPaint version:Whatever the newest version is not sure I downloaded it yesterday on 9/18/2021**

**OS/device including version:Win10 I have a GTX 950 MSI 2gb graphics card**

**Issue description: Randomly while in armorpaint the camera or model will begin to drift off while using right click rotate and eventually the 3d model itself disappears. This has happened multiple times so far. **

edit: realized that even if i reimport another 3d model after this the model still isnt visible

**Steps to reproduce: I imported a fbx model then after texturing it a bit while holding right click to rotate the object leaves the view and no matter where I turn I cannot see it**

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/1050, thanks for report.
