### ISSUE TITLE
Problems upscaling to noise texture

### ISSUE THREAD

**Issue by paolohuesp** [armory3d/armorpaint#1132]
ArmorPaint 0.8-c0978d1, Windows
![image](https://user-images.githubusercontent.com/87718540/135177983-db2c3faa-d553-4274-8e23-8d642527f64c.png)
![image](https://user-images.githubusercontent.com/87718540/135178309-b1cc3c70-d4b7-45ce-a7c2-19c3c381689f.png)
Issue description: As the scale of the noise texture node increases, parallel lines and other strange things begin to be seen, they are seen from the value 10 but it is not very noticeable, they become more noticeable as it increases with the value of 300 the error ends up being totally evident

Steps to reproduce: Add a noise texture node and increase the scale to high values.

**Comment by MathemanFlo** [comment]
@luboslenco This one can be closed, can't it?
![grafik](https://user-images.githubusercontent.com/28649121/156649899-ee5280de-2cd8-4c8d-9791-1a378dbaf5d4.png)
