### ISSUE TITLE
Cannot overwrite exr files in export textures.

### ISSUE THREAD

**Issue by ronh991** [armory3d/armorpaint#1134]
ArmorPaint version:
7674c63

OS/device including version:
Windows 10 19042.1237 20H2

Issue description:
cannot overwrite exr file texture export.

Steps to reproduce:
create a mesh with one rgb color. set roughness, set metallic. Export as exr 16 bit. - works on initial export.  Make a change and re export. Old files remain.

**Comment by ronh991** [comment]
this is a windows issue I assume. I checked the date modified and it gets changed, so the program does update, however your program does not modify the date created, only the date modified, so windows DATE field in the file explorer shows the date created under default Date field.

**Comment by MathemanFlo** [comment]
I think this is not an issue at all. The creation date is always the date a file was newly created (i.e. a new file name in a direcory was added to the file system). If a file gets overwritten it is not newly created but updated since no new file name is added  to the filesystem.
