### ISSUE TITLE
Smudge Brush

### ISSUE THREAD

**Issue by NLEGITN** [armory3d/armorpaint#1135]
*ArmorPaint 0.8-e11cf49, Windows*

**Feature description:**
I am slowly understanding Armor Paint more and more and one tool that would be nice is a Smudge brush.  The Smooth Brush works very, very slowly but a smudge brush would be really nice.

**Comment by luboslenco** [comment]
Blur tool has a `Directional` option now to perform smudge, quality will improve. Thanks for report!
