### ISSUE TITLE
Strange error when rotating in viewport

### ISSUE THREAD

**Issue by paolohuesp** [armory3d/armorpaint#1136]
*ArmorPaint 0.8-c0978d1, Windows*

Issue description: 
This error occurred to me while I was painting and suddenly when I wanted to rotate, what it does is zoom very quickly while I rotate.
I have tried closing and reopening but it persists with only that file.

Steps to reproduce:
I would not know how to reproduce it, since it happened suddenly.

**Comment by MathemanFlo** [comment]
I think this is similar to or a duplicate of #1131 and #1050.

**Comment by luboslenco** [comment]
Continue at https://github.com/armory3d/armorpaint/issues/1050.
