### ISSUE TITLE
Decal brush

### ISSUE THREAD

**Issue by NLEGITN** [armory3d/armorpaint#1138]
the decal brush is really hard to use.  I select it and try to add a stencil brush to operate the decal brush but I can find the correct YouTube videos and I was thinking if there were simple instructions on the armor paint app on how to do things. That might be nice:). Plus, how do I use the decal brush?  Sometimes I turn it on and all I see is a mask that I can control by holding ctrl, and moving and rotating the mask.

**Comment by MathemanFlo** [comment]
Maybe this is similar or an extension to #928

**Comment by luboslenco** [comment]
Will make it happen at https://github.com/armory3d/armorpaint/issues/928, thanks for suggestion.
