### ISSUE TITLE
Non-destructive material workflow (material update on change)

### ISSUE THREAD

**Issue by jsena42** [armory3d/armorpaint#114]
It would be very useful being able to change the material and see the changes on the model without the need of repainting.

**Comment by luboslenco** [comment]
There is one option - create a fill layer by right-clicking on the layer and select `To Fill Layer` (more [info](https://armorpaint.org/manual/#/?id=layers)). Then the material changes should reflect on the model immediately. Looking into making this more intuitive soon, it's not clearly exposed now.

**Comment by luboslenco** [comment]
It is now possible to create a fill layer by drag-and-dropping the material from materials tab onto viewport or layers tab. Also added `To Fill Layer` option when right-clicking on the material.
