### ISSUE TITLE
Crashes alot

### ISSUE THREAD

**Issue by NLEGITN** [armory3d/armorpaint#1141]
*ArmorPaint 0.8-e11cf49, Windows*

**Feature description:**

I have a few hours to use Armor Paint and I notice it does seem to crash a lot.  The Brushes work great but if you are really quick with your paint strokes it seems to be too much for the program:(

**Comment by luboslenco** [comment]
Thanks for report. Any chance you can file a bug report with steps to reproduce the crash? Please let me know, will fix asap!
