### ISSUE TITLE
Default font does not show a hover preview

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1149]
**ArmorPaint version:**
ArmorPaint.org - v0.9 (2021-10-05) - bd87056
Windows - Direct3D11

**Issue description:**
All newly imported fonts show a preview on hover. The default font does not.

**Steps to reproduce:**
1. Import another font
2. Hover the default one, nothing happens
3. Hover the imported one, a preview is shown

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/f6a760cc8b3d0709dabf61179586607ae77f5014. The small icons get a little jaggy now, will have to fix that too.
