### ISSUE TITLE
[bug]I am able to build armorpaint but it won't open

### ISSUE THREAD

**Issue by ErkBlender** [armory3d/armorpaint#115]
I was able to successfully build armorpaint from source without issues, but the armorpaint window stayed white and closed after a couple seconds.

**Comment by luboslenco** [comment]
Sorry I need more details to be helpful. Which OS? GPU?

**Comment by ErkBlender** [comment]
Windows 10 64bits, gtx 1060 6gb

**Comment by luboslenco** [comment]
Ah, you need to set graphics api to OpenGL on Windows. See [readme](https://github.com/armory3d/armorpaint/blob/master/README.md) for build instructions.

On Windows it's better to compile this [Krom](https://github.com/armory3d/Krom_armorpaint) binary for Direct3D11 support (faster perf) and native file dialogs. See Krom instructions [here](https://github.com/armory3d/Krom_armorpaint#build-instructions).
