### ISSUE TITLE
Zooming font 2d view moves "Abg"-preview

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1150]
**ArmorPaint version:**
ArmorPaint.org - v0.9 (2021-10-05) - bd87056
Windows - Direct3D11

**Issue description:**
Scrolling in 2D view for fonts moves the "Abg" instead of zooming. The movement direction depends on the initial position of the "Abg" preview. Pan to change it.

**Steps to reproduce:**
1. Open the 2d view for a font
2. Scroll the mouse wheel
3. Now pan 
4. Scroll again and notice the change in direction.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/a3991793463883bca5c4fef6f6702c03ae9a4e9d.
