### ISSUE TITLE
Ellipses outside of text edit control

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1153]
**ArmorPaint version:**
ArmorPaint.org - v0.9 (2021-10-05) - bd87056
Windows - Direct3D11

**Issue description:**
The ellipses to indicate longer texts are outside the text edit control. 
![grafik](https://user-images.githubusercontent.com/28649121/136385803-10151bed-8807-4e1a-85c4-5ef2f0002711.png)
Clearly this is more zui related.

**Comment by luboslenco** [comment]
Should be better after https://github.com/armory3d/zui/commit/277b28757954a849b9751f0854afeca27ea7ce7a.
