### ISSUE TITLE
Symmetry is incorrect for decal and text tool

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1155]
**ArmorPaint version:**
ArmorPaint.org - v0.9 (2021-10-05) - bd87056
Windows - Direct3D11

**Issue description:**
The issue becomes clear by this situation
![grafik](https://user-images.githubusercontent.com/28649121/136391767-44d9ad93-e17a-4918-ab91-af7a585c301d.png)
Compare the results by symmetry painting with the ordinary paint tool and the decal/text tool. The decal tool paints four squares instead of two. The two incorrect ones are highlighted.

**Comment by luboslenco** [comment]
Hopefully all good with https://github.com/armory3d/armorpaint/commit/97579ffd1b0dbd66b827b292f5f4b0a39e4e3aff, thanks for report.
