### ISSUE TITLE
Color picker node -Height Channel?

### ISSUE THREAD

**Issue by melvixiodf** [armory3d/armorpaint#1157]
@luboslenco Hi , using the picker node in the material editor, does the color picker node for height/bump map. I noticed it works only for albedo, normal, occlusion, roughness and metallic only
![untitled](https://user-images.githubusercontent.com/54470864/137635163-0a56046d-de0c-4e3d-bedb-dab509384a1c.png)
This is the setup I am using, shouldn't the color picker be able pick the height values along with the other channels?

**Comment by MathemanFlo** [comment]
Picking the height is currently not implemented. The same holds for opacity.

**Comment by melvixiodf** [comment]
yeah, noticed #878 immediately I tried to paint in a new layer. Thanks for the hack solution.

Armor paint has so much potential for height/bump map painting, if these issues are sorted out. 

The blur tool needs a liitle bit of refinement for height map painting. Right now, it works really well but sorts of leaves different sharp vaules in the pixels rather than smoothing them out.

**Comment by MathemanFlo** [comment]
You are welcome. You are right, height maps have lots of potential. Especially stamping details works really well. Just fill a layer's height with 0.5 and then stamp darker patterns to make holes and lighter patterns to make "hills".  Bluring and smooth painting is not so easy. See #274, #231.

**Comment by luboslenco** [comment]
Added at https://github.com/armory3d/armorpaint/commit/dfb9937b089c443f1f717515485ef7d080dd83a0, thanks for report!
