### ISSUE TITLE
Issue with mesh import, regardless of format

### ISSUE THREAD

**Issue by ksantiago1974** [armory3d/armorpaint#1158]
*ArmorPaint 0.8-7a1df6f, Windows*

**Issue description:** I get this every time I import a mesh, whether it's .blend format or .fbx format. Please help.

![APIssue](https://user-images.githubusercontent.com/68402856/138360585-31baacca-52d1-4e9d-9c82-bdbf740d7e22.PNG)

**Steps to reproduce:**

I need a solution

**Comment by luboslenco** [comment]
Hi, this should resolve the issue:

> Black spots appear on the imported mesh:
> Make sure all mesh faces are present on the UV map.
