### ISSUE TITLE
Unable to load uv_unwrap plug-in on iOS 

### ISSUE THREAD

**Issue by aaaronorg** [armory3d/armorpaint#1159]
**ArmorPaint version:**

ArmorPaint.org - v0.8 (2021-10-18) -821c59f
iPlodPrune-FOBC8ABC-04CD-4753-B7F6-99258E22245C - Metal

**OS/device including version:**

iPad Pro 12” 2020 6gb ram

**Issue description:**

Go to: Plugins => Manager => uv_unwrap. Nothing happens, expecting uv unwrap plug-in to load. Checking the console gives the following output (incidentally hitting export on the log does not seem to work either):

```
ReferenceError: WebAssembly is not defined
Failed to load plugin 'uv_unwrap.js'
no native wasm support detected
```

**Comment by robomaxis** [comment]
> I think it’s for all wasm plug-in, even import gltf glb is like this, gltf one gets stuck too

Confirm that. Got same bug on my iPad Pro 2020 12”

**Comment by aguycalled** [comment]
any update on this?

**Comment by robomaxis** [comment]
> any update on this?

Upgraded to iPad Pro 2021(M1), updated app - still not fixed
‘No native wasm support detected’
