### ISSUE TITLE
ArmoryPaint doesn't run and fail with black screen

### ISSUE THREAD

**Issue by rdcklinux** [armory3d/armorpaint#116]
commit bb80421583dc01ac5642278dfc4ecb51c06ca28e (HEAD -> master, origin/master, origin/HEAD)
Author: luboslenco
Date:   Sat May 25 23:34:28 2019 +0200
    Update readme

SO: Linux Ubuntu 18.04
Arch: 64bit
Armory3D version: 0.6 64bit
With commit 5f77c5c30d88fb904f795478907aef1e7fd1f2a2 works.

### First attempt 

1. Open Armory3D
2. update SDK
3. restart Armory3D
4. open armorpaint project file (Assets/blend/scene.blend)
5. click on play button
6. console shows Type not found : arm.App

symptom: The arm directory in Assets/blend/Sources is empty.

### Second attempt

1. I create a symbolic link to Source/arm directory into Assets/blend/Sources (I has removed empty arm directory)
2. Open Armory3D
3. update SDK
4. restart Armory3D
5. open armorpaint project file (Assets/blend/scene.blend)
6. click on play button
7. arm.App works now!
8. but console shows  Could not open file ../Assets/blend/build_scene/debug/krom/World_irradiance.arm
9. the World_irradiance.arm file isn't there.

symptom: Armorpaint window doesn't open.

### Third attempt:

1. Copy Assets/blend/scene.blend to armorypaint root directory (as before)
2. Open Armory3D
3. update SDK
4. restart Armory3D
5. open armorpaint project file (scene.blend)
6. click on play button
7. World_irradiance.arm file was found!!
8. but, now console shows:

Uniform N not found.
Uniform texUnpack not found.
iron.data.ShaderData:46: Shader data "copy_mrt3_pass" not found!
Uncaught exception:
			cc.context = res.getContext(shaderPath[2]);
			^
TypeError: Unable to get property 'getContext' of undefined or null reference
   at Anonymous function (krom.js:17483:4)
   at Anonymous function (krom.js:19354:4)
   at Anonymous function (krom.js:20581:4)
   at iron_data_Data.getSceneRaw (krom.js:19363:3)
   at iron_data_ShaderData.parse (krom.js:20577:2)
   at iron_data_Data.getShader (krom.js:19341:2)
   at iron_RenderPath.prototype.loadShader (krom.js:17482:3)
   at arm_renderpath_RenderPathDeferred.init (krom.js:6077:2)
   at arm_renderpath_RenderPathCreator.get (krom.js:6034:2)
   at Anonymous function (krom.js:14156:6)

symptom: Armorpaint windows shows black screen

**Comment by luboslenco** [comment]
I have updated readme with updated build instructions, ArmorPaint compilation is now self-contained for tighter Krom integration.

**Comment by rdckgames** [comment]
thaks you, I try again!
