### ISSUE TITLE
Crash on obj+udim import

### ISSUE THREAD

**Issue by nequine** [armory3d/armorpaint#1163]
Hello everyone !

*ArmorPaint 0.8-a06962c, Windows*

**Issue description:**
I wanted to try armorpaint on a production like asset. It has 26 udims. 

The asset :
https://www.dropbox.com/s/ks0m1e9u34dx49b/razorcrest.obj?dl=0

**Steps to reproduce:**
Open armorpaint
File > import mesh
select the razorcrest.obj
split by > udim tile
import
and it crashes

**Comment by luboslenco** [comment]
Still much to do on udims but fixed the crash now at https://github.com/armory3d/armorpaint/commit/1348570a14690fa46979689f45e2e763cce7bb02. Many thanks for providing the file!
