### ISSUE TITLE
Allow Deleting Layers/Mats/Brushes/etc With the 'Delete' Keyboard Key

### ISSUE THREAD

**Issue by FoonTheRaccoon** [armory3d/armorpaint#1166]
As the title says. Allow Deleting Layers/Mats/Brushes/etc With the 'Delete' Keyboard Key. It's fine if a confirmation window pops up so long as the default choice is "Yes delete" so you can just hit Del then enter quickly to delete them instead of having to use the right click context menu. Just a way to speed up work.

**Comment by luboslenco** [comment]
Added at https://github.com/armory3d/armorpaint/commit/990490e627814b72b85ddb907120d039cd1ab231, thanks for suggestion.
