### ISSUE TITLE
Keyboard Shortcut: Spacebar to open Menu to add Nodes

### ISSUE THREAD

**Issue by ssnd292** [armory3d/armorpaint#117]
The title says it all. 

Should be working similar to  UE4 and Designer - ie. pressing space open a Search Bar with results displayed underneath. Makes it quicker to get the desired nodes if you know their names.

**Comment by luboslenco** [comment]
Node search is now available in latest builds.

![nodes2](https://user-images.githubusercontent.com/3685704/59045565-97792080-8880-11e9-9f7d-459240dc2792.PNG)
