### ISSUE TITLE
How to avoid overlapping automatic UVs

### ISSUE THREAD

**Issue by honus85** [armory3d/armorpaint#1171]
Hi whenever I import an object which has no UVs, with multiple objects. Upon load and split by object, the UVs seem to be layered on top of each other. Having a look at the code it seems like the UVs are generated per mesh (looped per arm paint object) and not generated via create and pack once all unwrapped?

![FCA28EEC-89AA-4EFD-930C-45186CE8EAF9](https://user-images.githubusercontent.com/34238090/139126065-29c1a8f6-87c5-4465-95cb-2d965fb251ec.jpeg)

**Comment by luboslenco** [comment]
Fix incoming via https://github.com/armory3d/armorpaint/issues/1159.
