### ISSUE TITLE
No Scene Navigation 

### ISSUE THREAD

**Issue by ebutts531** [armory3d/armorpaint#1172]
**ArmorPaint version:**
v0.8 (2021-10-03)-a06962c

**OS/device including version:**
Pop!_OS 21.04 x86_64, linux
5.13.0-7614-generic
AMD Ryzen 7 3800X (16) @ 3.900GH 
NVIDIA GeForce RTX 2080 SUPER  Driver 470.63.01

**Issue description:**
No viewport navigation in default scene on startup. Does not work with Blender keymap as well. 

**Steps to reproduce:**
Launch ArmorPaint. No navigation.

**Comment by Regnsloja** [comment]
Same for me on Linux Mint 19.2 (Cinnamon) with the same version of ArmorPaint.
Can't navigate the viewport at all. Once when I clicked around madly the camera did suddenly pan (a big jump instantly), but I couldn't make it happen again.

I don't have the previous versions, so I don't know if it's unique to this version.

**Comment by luboslenco** [comment]
Should be now resolved via https://github.com/armory3d/armorpaint/issues/1179#issuecomment-984711549, otherwise please let me know. Thanks for report!
