### ISSUE TITLE
Can't export textures

### ISSUE THREAD

**Issue by Bubblehead333** [armory3d/armorpaint#1176]
Can't export textures, follow the video tutorial as shown here: https://www.youtube.com/watch?v=nuzooiT7rJk
ArmorPaint says that texture has been exported...but hasn't. I bought the paid version v0.8, tried re-installing, running in administrator mode, no idea why it isn't working. Can export mesh fine. Can't export the log file either, same issue.

File -> Export Textures...

Export settings below:

![2021_10_31_ArmorPaint](https://user-images.githubusercontent.com/29005853/139581991-604cba5e-b978-42bd-87af-a5d364b9b3e0.jpg)
ArmorPaint.org - v0.8 (2021-10-03) - a06962c
Windows - Direct3D11
Radeon RX 580 Series

Edition	Windows 10 Home
Version	21H1
Installed on	‎18/‎04/‎2021
OS build	19043.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by Bubblehead333** [comment]
Embarrassingly I've gotten it to work, weirdly my anti-virus was blocking the creation of the new files - even after turning it off after seeing a previous thread!

**Comment by luboslenco** [comment]
Happy to hear, thanks for the report!
