### ISSUE TITLE
Severe performance problem with Arch Linux and Nvidia RTX 2080

### ISSUE THREAD

**Issue by lehthanis** [armory3d/armorpaint#1179]
Hi!  I have armorpaint installed on Arch Linux on a laptop with an Nvidia RTX 2080 video card.  When I launch the program it almost immediately causes my GPU usage to spike to ~70% and my system temps immediately start overheating upwards of around 80-90C. The viewport is almost unresponsive.  My framerate in the viewport appears to be about 1 frame every 2-5 seconds. I haven't been able to spend any time looking through settings in the program because it starts overheating and I don't want to burn up my laptop.  Any procedures I should follow in order to either get it working or provide you with the debugging info you need?

**Comment by infinder** [comment]
Did you find what the problem was or/and a solution.? Windows installation here but i think my system temps overheating upwards too. Not that dramatic as you describe but definitely more than i use to expect.

**Comment by lehthanis** [comment]
@infinder I have not found a solution, nor have I revisited because no one seemed interested in the issue either on the archlinux side or the armorpaint side.  The armorpaint discord server pointed me here, and you're the first person to respond to the issue.

**Comment by infinder** [comment]
Lately Armorpaint gains more attention. Users from different OSes and hardware platforms (CPUs, GPUs) start using it, thus more bugs or shortcomings appear and ask for solutions. We have to be patient for @luboslenco to iron out bugs or add new features etc. He is a very good guy..

**Comment by luboslenco** [comment]
Fixed the unresponsive viewport on Linux in the latest 0.9dev builds. It should be related to >60hz displays.

Will take a look at reducing the gpu usage when idle. Thanks for support!
