### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by jonbragado** [armory3d/armorpaint#118]
Hi, how can we help this be translated in spanish?

**Comment by luboslenco** [comment]
Hello @jonbragado, thank you for offering help with the translation! Looking into internationalization for upcoming armorpaint versions, will report back.

**Comment by jonbragado** [comment]
Can you make armourpaint the Mari / Substance of Blender? :P. OpenSource initiatives rules.

**Comment by lucasdlk** [comment]
I could help for the french localization

**Comment by Calinou** [comment]
I'm interested in helping for French localization as well. If I have enough spare time in front of me, I could even look into adding i18n support to ArmorPaint, but I have little experience with Haxe and its i18n libraries.

**Comment by Calinou** [comment]
On my way to adding i18n support… :tada: 

![image](https://user-images.githubusercontent.com/180032/76691175-754ed300-6648-11ea-9962-a7f7f925a377.png)

Localization is handled using JSON files loaded via the [jsoni18n](https://github.com/Nekith/jsoni18n) library. The original English strings are the source strings, which means the library will fall back automatically to English if no translated string is available for the current language (placeholders and pluralization will work as expected).

Some issues:

- The font doesn't include accented characters such as `é`. This means they won't display.

**Comment by luboslenco** [comment]
Wow, thanks for looking into this!

> The font doesn't include accented characters such as é. This means they won't display.

Aha, will fix. We will also need to detect which non-ascii characters the language uses, and then report this to the font atlas generator - so it knows which characters to include in the atlas. Should be easy to automate this.

> I need to add language detection (and overriding) logic, since the library doesn't come with any.

Kinc library which ArmorPaint runs on contains the `kinc_language()` function. On [Windows](https://github.com/Kode/Kinc/blob/master/Backends/System/Windows/Sources/Kore/System.cpp#L968) it just returns "en" right now so it still needs to be implemented. On [macOS](https://github.com/Kode/Kinc/blob/master/Backends/System/macOS/Sources/Kore/System.mm#L229) it's already imlemented. Will expose this function to ArmorPaint.

> We should figure out a way to generate translation files automatically, update existing translations with new strings and remove obsolete strings.

👍👍

> App.i18n.tr() is a bit verbose, as we need to use it for every translatable string. Maybe we can shorten it to just tr() or _() with some kind of global macro?

That would be sweet, I vote towards tr().

Will also take care of the menu-bar align. 😃

**Comment by Calinou** [comment]
@luboslenco I didn't find a way to expose a global macro or method, so I added a `tr()` helper method to App. This way, we can use `App.tr(...)` instead of `App.i18n.tr(...)`, which is still a bit less verbose.

**Comment by sh-dave** [comment]
You can import static fields of a class in haxe.

```haxe
import App.tr;

function foo() {
    trace(tr('some_string_id'));
}
```

**Comment by Calinou** [comment]
I've finished marking all UI strings as translatable :slightly_smiling_face:

**Comment by luboslenco** [comment]
Pull request very much welcome, even if more things are to come / change. 🙂

**Comment by luboslenco** [comment]
It's in!

- I have added `Krom.language()` function (but still needs to be implemented on [Windows](https://github.com/Kode/Kinc/blob/master/Backends/System/Windows/Sources/Kore/System.cpp#L968), just returns "en")
- Fixed menu bar align
- Looking into handling accented characters

**Comment by Calinou** [comment]
@luboslenco I finished the script for extracting/updating translations and replacing localized strings after loading a translation. Now, how can I check whether a file is present so I can avoid crashing if no translation is available for the current language?

**Comment by luboslenco** [comment]
Quick snippet:

```haxe
// List of available language files, ["fr.json", ...]
import arm.sys.File;
var languages = File.readDirectory(Path.data() + Path.sep + "locale"); 
```
```haxe
// Combo for selecting language
var activeLanguage = "fr";
var languageHandle = Id.handle({position: languages.indexOf(activeLanguage)});
ui.combo(languageHandle, languages, tr("Language"), true);

if (languageHandle.changed) {
	// Apply a different language
}
```

Everything else I think you already figured out but always happy to provide more info.

**Comment by 1234EMMM** [comment]
Hello, I found a fr file under "krom\data\locale" path, and found that this file can be changed to Chinese translation, but it seems that there is no Chinese font, so the text cannot be displayed, but is blank, I want to ask if I can make the Chinese translation work (probably because there is no Chinese font file, I feel that I can use the open source font used by BLENDER), if you can, I can also provide Chinese translation, thank you.
PS:This English is machine translated, I hope you can understand
![TIM截图20200414235557](https://user-images.githubusercontent.com/49475772/79246987-7de73300-7eac-11ea-9aff-bd132d5a22e6.png)

------------------------------------------------
你好,我在"krom\data\locale"路径下找到了一个fr,的翻译文件,发现这个文件可以更改为中文的翻译,但是好像没有中文的字体,导致不能显示文本,而是显示为空白的,我想问问能不能使中文翻译有效(可能是因为没有中文的字体文件,我感觉可以使用BLENDER使用的开源字体),如果可以我也可以提供中文的翻译,谢谢您了
PS:这段英文是使用机器翻译的,希望您能看的懂

**Comment by Calinou** [comment]
@1234EMMM Accented characters haven't been added in yet, so not even the French locale will display correctly for now.

**Comment by luboslenco** [comment]
@Calinou French locale should already display properly. Did I miss something? Is something displayed wrong?

@1234EMMM I understand, hope you can translate back. 🙂 Can you contribute your `zh_CN.json` translation file (ideally via pull-request)? I will look into adding support for Chinese font. Thanks for your help!

**Comment by Calinou** [comment]
@luboslenco I can confirm it works as of https://github.com/armory3d/armorpaint/commit/c064b04c332025b8975361dbec4cf9290f589b12, thanks :slightly_smiling_face: 

![2020-04-14_21 17 13](https://user-images.githubusercontent.com/180032/79264806-6f415180-7e95-11ea-9d46-ff935b2cdb51.png)

**Comment by 1234EMMM** [comment]
> @Calinou French locale should already display properly. Did I miss something? Is something displayed wrong?
> 
> @1234EMMM I understand, hope you can translate back. 🙂 Can you contribute your `zh_CN.json` translation file (ideally via pull-request)? I will look into adding support for Chinese font. Thanks for your help!

Hello, I have the Chinese translation file 'zh_CN.json' now, but I don't know where to upload it, because this is probably my first submission. Please ask where the submission portal is, it would be nice to have a Chinese translation, I also found the BLENDER font file: https://github.com/sobotka/blender/tree/master/release/datafiles/fonts
I also tried to use this translation, but the result is the following, all the text disappears.
![QQ截图20200415114409](https://user-images.githubusercontent.com/49475772/79296592-72c4ef00-7f0e-11ea-8d78-facb31769b80.png)
-------------------------------------------
您好,我现在已经处理好中文的翻译文件'zh_CN.json',但是我不知道从那儿上传,因为这大概是我第一次提交.麻烦问一下提交的入口在那里啊,如果能有中文翻译就太好了,我还找到了BLENDER的字体文件:https://github.com/sobotka/blender/tree/master/release/datafiles/fonts
另外我尝试了一下使用这个翻译,但是效果就是下面这样,所有的文字都消失了.

**Comment by 1234EMMM** [comment]
@Calinou @luboslenco 
In addition to the translation problem there is also the name, in BLENDER I know that there is such a problem, that is, can only copy the text to complete the input, can not directly input, I hope Armorpaint will not have such a situation!
---------------------------------------------------------------------------------
另外除了翻译的问题以外还有名称,在BLENDER中我知道有这样的问题,就是只能复制文本完成输入,不可以直接输入,希望Armorpaint不会有这样的情况

**Comment by 1234EMMM** [comment]
I've already uploaded this file, please check the path to see if it's correct
https://github.com/armory3d/armorpaint/commit/9ccf6f16548f09de19158d14def2b6b48d738d8a.

PS:This English is machine translated, I hope you can understand
-------------------------------------------------------
我已经上传了这个文件,麻烦帮忙看一下路径是否正确https://github.com/armory3d/armorpaint/commit/9ccf6f16548f09de19158d14def2b6b48d738d8a

**Comment by Calinou** [comment]
> In addition to the translation problem there is also the name, in BLENDER I know that there is such a problem, that is, can only copy the text to complete the input, can not directly input, I hope Armorpaint will not have such a situation

This requires adding support for IME, which isn't exactly easy or straightforward to do.

**Comment by 1234EMMM** [comment]
> > In addition to the translation problem there is also the name, in BLENDER I know that there is such a problem, that is, can only copy the text to complete the input, can not directly input, I hope Armorpaint will not have such a situation
> 
> This requires adding support for [IME](https://en.wikipedia.org/wiki/Input_method), which isn't >exactly easy or straightforward to do.

This is not good news for a Chinese user like me,:0
I still wish I could type directly, or copy the text.  _(:з」∠)_
![CC69786F26F4D89FDD787EC4C0B32E37](https://user-images.githubusercontent.com/49475772/79311896-ae70b080-7f30-11ea-92b5-f42ae9b8c608.jpg)
---------------------------------------------------

这对于我这种中文用户来说不是一个好消息  ,:0
我还是希望能直接输入,或者是复制文本也可以 _(:з」∠)_
![CC69786F26F4D89FDD787EC4C0B32E37](https://user-images.githubusercontent.com/49475772/79311896-ae70b080-7f30-11ea-92b5-f42ae9b8c608.jpg)
