### ISSUE TITLE
Incorrect layer mask preview on hover

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1181]
**ArmorPaint version:**
ArmorPaint.org - v0.9 (2021-11-04) - 773c272
Windows - Direct3D11

**Steps to reproduce:**
1. Create a black or white mask
2. Paint on it
3. Hover the mask icon to show the preview tooltip. If the mask was a black mask, the preview is black. If the mask was a white mask, the preview is white
![grafik](https://user-images.githubusercontent.com/28649121/140317421-1c104d05-92f3-4e67-8eba-1f4954d8e48a.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/42b7028a0cda4550639d48aad131e0350fd96af5. Thanks for report!
