### ISSUE TITLE
Documentation is nonexistent

### ISSUE THREAD

**Issue by Goury** [armory3d/armorpaint#1187]
Stop adding new features that do not work (because broken or nobody know how to use em) and start writing documentation.    
Current "manual" is but a joke, you can't figure how anything works from it and a slightest deviation for what the author had in his mind results in being stuck to a wall.    
"Howtos" are even worse, nothing is explained at all, it's more of a showcase than anything useful.

**Comment by Granada1** [comment]
> Stop adding new features that do not work (because broken or nobody know how to use em) and start writing documentation.
Current "manual" is but a joke, you can't figure how anything works from it and slightest deviation for what the author had in his mind results in being stuck to a wall.
"Howtos" are even worse, nothing is explained at all, it's more of a showcase than anything useful.

> 
Not very politely put ,but a good point about the documentation

**Comment by infinder** [comment]
Documentation is hard to write and even if you are right to some extend, its better not to burden the programmer with this task.
There are some good video tutorials on the internet about using the program: 
https://www.youtube.com/channel/UCKUVTPjY4nBCJLS6imbPbZA/videos
https://www.youtube.com/playlist?list=PLTZhWSINdiMw1TQ9eya1pDv1SKz7RwfAT
This is how it usually goes with open sourced programs.
Volunteers write tutorials, documentation or/and code to help main programmers.

**Comment by Goury** [comment]
Sorry, but I don't have any polite words for a commercial product that doesn't care to explain how to even use it.

@infinder    
There are none.    
The first link in but an insult where author doesn't care to speak clearly nor actually explain what is going on but does force you to suffer from a background acoustic assault.    
The second one is but a waste of time. It's literally impossible to find any clear answer to any particular question on there.

**Comment by infinder** [comment]
I'm not trying to convince anyone of anything. I believe that armorpaint is very promising
and I love it, even if there is not enough material of how to use it and it has not yet reached version 1.oo.

**Comment by luboslenco** [comment]
Thanks for the criticism, it helps a lot. Will be the main focus of v 1.0, I agree it sucks right now. ArmorPaint should be still considered an 'early' 0.x project with lots of work ahead, but will get there eventually.

I try to put up as many warnings as possible before anyone decides to pay for the pre-built binaries, ie. marking it as a preview and noting "The preview version has many rough edges and the experience may be frustrating." Happy to send a refund to all requests, just send me an email!

**Comment by Goury** [comment]
Please either don't close the issue report or add it to the official roadmap
