### ISSUE TITLE
Unable to build (Windows)

### ISSUE THREAD

**Issue by alisherks** [armory3d/armorpaint#119]
I've got the following error trying to build armorpaint. Did everything as described in the readme.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command "ml64.exe /c /nologo /Zi /Fo"x64\Debug\amd64_Thunks.obj" /W3 /errorReport:prompt  /Ta..\Chakra\lib\Runtime\Language\amd64\amd64_Thunks.asm" exited with code 1.	Krom	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\masm.targets	70	
`

**Comment by luboslenco** [comment]
Is this the full error log? 64bit Windows?

**Comment by alisherks** [comment]
Yes, this is happening on 64bit windows.

Extracted from Krom logs:
```
Assembling ..\Chakra\lib\Runtime\Language\amd64\amd64_Thunks.asm...
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\masm.targets(69,5): error MSB3721: The command "ml64.exe /c /nologo /Zi /Fo"x64\Release\amd64_Thunks.obj" /W3 /errorReport:prompt  /Ta..\Chakra\lib\Runtime\Language\amd64\amd64_Thunks.asm" exited with code 1.
```
Seems like issue is with Krom.

**Comment by luboslenco** [comment]
Yes..but I am unable to reproduce it so far, sorry. If you have the patience you might try compiling ChakraCore directly and see if the issue persist (should result in the same error):
https://github.com/microsoft/ChakraCore

Maybe helpful:
https://www.youtube.com/watch?v=dk9OOP4DmoU
