### ISSUE TITLE
Windows users that can not run armorpaint outside of Visual Studio

### ISSUE THREAD

**Issue by BAROBA-3d** [armory3d/armorpaint#1193]
Hi,
I made this " issue" in the hope to help others and to improve the documentation.

1.Building is quite easy, just switch to Release instead of debug in the little window in the middle of the topbar.
2.If you have build succesfully ( armorpaint should pop up and you can paint in it), but are unable to get it running outside of Visual Studio.Also clicking on the executable (Armorpaint.exe) does nothing.
3.Then do the following:
Find the executable ( usually in <path to Armorpaint>\armorcore\build\x64\Release.
Copy Armorpaint.exe into the folder <path to Armorpaint>\build\krom. There you will find Krom.js and a map called Data.
Now copy Armorpaint.exe, krom.js and the folder Data to any other folder. For example program files and create a new folder and drop it all in that folder. 
Now it all works.

I really hope that it helps other people who are also not programmers.

**Comment by CarmikoCoala** [comment]
It worked for me thanks!_
