### ISSUE TITLE
Building on iOS with Xcode

### ISSUE THREAD

**Issue by omariparris** [armory3d/armorpaint#1194]
**ArmorPaint version:**
0.8 ?

**OS/device including version:**
MacOS 12 Monterey
iPhone XR

**Issue description:**
Im using Xcode to build armorpaint on my iPhone, the app is already installed on my phone but every time I build it stays on a black screen and it makes a breakpoint at these lines of code: Line 715 in krom_lock_vertex_buffer(args)

`		Local<ArrayBuffer> abuffer = ArrayBuffer::New(isolate, vertices, (count - start) * kinc_g4_vertex_buffer_stride(buffer));`

**and in the thread:**
#3	0x0000000100ba8d18 in (anonymous namespace)::krom_lock_vertex_buffer(v8::FunctionCallbackInfo<v8::Value> const&) at /Users/username/Desktop/ARMORPAINT/armorpaint/armorcore/Sources/main.cpp:715

If anyone knows how to properly build this version help would be greatly appreciated

**Comment by luboslenco** [comment]
Appears to be linked with https://github.com/armory3d/armorpaint/issues/1192, will investigate there. Thanks for report.
