### ISSUE TITLE
Installation infos

### ISSUE THREAD

**Issue by Blenderari** [armory3d/armorpaint#1195]
Hi
I've just purchased Armorypaint
I'm a windows 10 user with a rtx 2080 ti as gpu, which version i need to install? ArmorPaint_08_win64 or ArmorPaintDXR_08_win64?
Many thanks
Arian

**Comment by MathemanFlo** [comment]
The DXR Version uses DirectX 12 and raytracing the other one uses DirectX 11 without raytracing. You probably want to use the ArmorPaintDXR_08_win64 version.

**Comment by Blenderari** [comment]
Thank you very much for the reply! Very appreciate!
:)
I'll install it!
Again. many thanks for your time! cheers
