### ISSUE TITLE
Use core profile instead of compatibility profile

### ISSUE THREAD

**Issue by qwertychouskie** [armory3d/armorpaint#12]
The use of the OpenGL compatibility profile makes the program not work on any system that uses Mesa (mainly Intel HD and AMD cards).  Could the program be made to use a core profile?

See also https://github.com/armory3d/armorpaint/issues/11

**Comment by qwertychouskie** [comment]
Not sure where to download, @gerardogc2378 can you test?

**Comment by luboslenco** [comment]
Requesting core-profile seems to work properly https://github.com/Kode/Krom/issues/64#issuecomment-396049097!
