### ISSUE TITLE
Render Bug compiled latest version

### ISSUE THREAD

**Issue by jayanam** [armory3d/armorpaint#120]
Hi, I just compiled the latest build of Armorpaint with VS 2017 on Windows 10. 

I get the following drawing issue, a white triangle is always displayed where the mouse cursor is.

![image](https://user-images.githubusercontent.com/18039584/58784892-b5c2f000-85e4-11e9-990d-8603d2652299.png)

**Comment by luboslenco** [comment]
Hi @jayanam, there is some turbulence in latest git right now as I am finalizing the new 3D brush cursor. Should be all good soon.

In the meantime please disable the `Preferences - Usage - 3D Brush Cursor` option. That will bring back the old 2D cursor. 🙂 

(Will post at https://github.com/armory3d/armorpaint/issues/35 as soon as 3D cursor is ready.)

**Comment by jayanam** [comment]
Alright, great, it works now. Here is a video with your fix included:-)

https://youtu.be/dk9OOP4DmoU

**Comment by luboslenco** [comment]
Thanks! 😍 Almost ready with the 3D cursor, will work out of the box then. Will also tag 0.6 in the [releases](https://github.com/armory3d/armorpaint/releases) eventually, to make building 'less buggy' version easier.

**Comment by jayanam** [comment]
Cooo, thx man
