### ISSUE TITLE
Pressing Delete key in the nodegraph removes Material and not node

### ISSUE THREAD

**Issue by Eisenblute** [armory3d/armorpaint#1207]
**ArmorPaint version:**
v0.9 (2021-12-16) - f6a760c

**OS/device including version:**
Windows 7 x64
NVIDIA GeForce GTX 750

**Issue description:**
If you press keyboard's Delete key in the nodegraph window, program removes Material (or Brush) and not the node.

**Steps to reproduce:**
- Create new Material or Brush clicking New button
- Press TAB to go to the nodegraph
- There choose RGB node and press Delete key on the keyboard.

NB. Pressing Right mouse button -> Delete works fine.

**Comment by MathemanFlo** [comment]
I can reproduce that and I'm pretty sure it is because of https://github.com/armory3d/armorpaint/commit/990490e627814b72b85ddb907120d039cd1ab231

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/fad8c4518221004c44ad43e9d91bbe05ac60e554, thanks a lot!
