### ISSUE TITLE
ProcessUncleanExitError while trying to compile armorpaint

### ISSUE THREAD

**Issue by satyamrajabhar** [armory3d/armorpaint#121]
When i am trying to compile armor paint in visual studio code i m getting a error-  ProcessUncleanExitError.
i m trying to install it since the morning but i am facingf the same error everytime hope someone will help me out with it.
 To fix it i installed Kodestudio in windows but it still is not working i tried of reinstalling the nodejs both of them the 10.0+ version and 12.0+ version.
![error](https://user-images.githubusercontent.com/51327552/58806660-4a087380-8634-11e9-9444-30472371ade3.PNG)

![Error in Kode](https://user-images.githubusercontent.com/51327552/58806911-bf744400-8634-11e9-93ed-82344da5a011.PNG)

**Comment by luboslenco** [comment]
Hello @satyamrajabhar. To compile armorpaint, Visual Studio is required (not Visual Studio Code). Hope that helps!

**Comment by satyamrajabhar** [comment]
Thanks for your reply, i am installing visual studio and i will try compile it again, thank you.
