### ISSUE TITLE
Reexporting imported material increases its size

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1213]
**ArmorPaint version:**
ArmorPaint.org - v0.9 (2021-12-19) - f374b53

1. Build a simple material.
2. Export it packed
3. Close ArmorPaint
4. Open it again and import the material
5. Export it again. It doubles its size.

I built an example to show it.  Packed_1 is the first material. Packed_2 is the same material but the rexported version.
[Example.zip](https://github.com/armory3d/armorpaint/files/7741480/Example.zip)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/eb6c1ea1312e69472f6eef04a5188a3cc9deb62b, thanks for report.
