### ISSUE TITLE
Inconsistency in the preview of the composition

### ISSUE THREAD

**Issue by Forteskun** [armory3d/armorpaint#1215]
I've seen a few tutroials and I tried to figure out what is happening between the layer list and viewport, but I'm literally unable to understand this behaviour so please someone explain to me:

https://user-images.githubusercontent.com/93223122/146688997-f43a0bc3-67ce-49bd-b599-cb35a38b9c0e.mp4

I don't get why selecting one or another layer changes what I see in the viewport. Aren't I supposed to be doing a composition and what I should be seeing is the result of that composition? Or did I miss something?

Also, I would also like to take this opportunity to ask, since I couldn't clarify it with the documentation, what's the difference between Material workspace and Paint workspace? And which I should use to see the results of my layers composition?
Because changing between Paint and Material I've noticed that shows differents results.
In Material workspace still happens this inconsistency.

https://user-images.githubusercontent.com/93223122/146689535-31cc7ecf-76a7-436f-8c8d-7d83e4cd1b5d.mp4

Sorry for the noob question, I'm having trouble getting used to Armor Paint.

**Comment by luboslenco** [comment]
Hello, thanks for report. The material workspace is meant for showing the single currently selected material in the viewport. When painting & working with multiple layers paint workspace should be used, so the layer/material selection will not alter the viewport.
