### ISSUE TITLE
Tooltips are not changed if language changes

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1216]
**ArmorPaint version:**
ArmorPaint.org - v0.9 (2021-12-19) - f374b53

**Issue description:**
If a user changes the language the language of the tooltips does not change.

**Steps to reproduce:**
1. Suppose ArmorPaint uses the english locale.
2. Hover a button on the left toolbar to reveal its tooltip. It is in english.
3. Now change the language to any other locale, e.g. German.
4. Now hover the same button again and see that the tooltip language did not change.
5. Close ArmorPaint and reopen it.
6. The tooltip is now correct.

**Comment by luboslenco** [comment]
Hm that is weird, seems to work as expected here. I tried English and then German. Any idea if something else might influence it?

**Comment by MathemanFlo** [comment]
Sorry Lubos I explained it incorrectly.
1. Set de locale in ArmorPaint
2. Close ArmorPaint
3. Open it again
4. Change locale to en or any other
5. Now the tooltip is still German.
6. Restart ArmorPaint, now it is correct.
So you have to start with a NON English locale and not with the English one.

But please, it is definitely no big issue, ArmorPaint has much more important ones. It is also no new issue, it is probably a bug it has since it got locale support.
