### ISSUE TITLE
Changing height value in materials causes cube to go black

### ISSUE THREAD

**Issue by SojanJanso** [armory3d/armorpaint#122]
Ubuntu 18.04.2 LTS (Gnome 3.28.2)
AMD® Fx-8320e
GeForce GTX 780 (driver 415)

Steps to recreate:
1. Open armor paint (I have v0.6 (2019-05-23) - ae7f30e (linux-OpenGL))
2. Double click on material to access material nodes.
3. Change "Height" value in the "Material Output" node
3.5. Even if the "Height Value is brought back to 0 after change and before next step it will still work
4. Paint on cube, or double click on material again.

Result:
Either action causes the cube to go black, and while painting on the cube, the cube completely disappears. Other visual glitches can also occur in the 3d view.

**Comment by SojanJanso** [comment]
Here are some previews.




![Peek 2019-06-04 12-31](https://user-images.githubusercontent.com/26679320/58896831-d2cef000-86c4-11e9-866f-73af57246f4c.gif)
![Peek 2019-06-04 12-32](https://user-images.githubusercontent.com/26679320/58896834-d2cef000-86c4-11e9-991f-890b2f126f0e.gif)

**Comment by SojanJanso** [comment]
Also, I don't know if it is of any relevance, but these errors shows up in terminal.
```
GL Error 1282 ../../Kore/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.cpp 197

GL Error 1282 ../../Kore/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.cpp 197
```

**Comment by Magi-max** [comment]
Same here, kde neon + nvidia.

**Comment by luboslenco** [comment]
This should no longer happen now in the latest build.

Height paint is still tacky though, will dedicate one of the upcoming updates to it.

**Comment by SojanJanso** [comment]
It no longer happens on my system.
