### ISSUE TITLE
non-English characters are not displayed in the browser

### ISSUE THREAD

**Issue by sanya-2005** [armory3d/armorpaint#1221]
**ArmorPaint version:**
commit f374b531206b82eddca3210e84daa5c24253cf67

**OS/device including version:**
ubuntu 20.04

**Issue description:**
the names of folders and files written in a non-English language will not be displayed in the browser
![Screenshot_20211222_214146](https://user-images.githubusercontent.com/88460753/147140182-d7ac35fe-388a-4a88-aef1-3263b3b31fc0.png)

**Comment by MathemanFlo** [comment]
I can reproduce that. ArmorPaint does definitely not display all characters the Robo font contains.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/zui/commit/c24daaf245919429bae588cda7ab853248eef385, thanks for report.
