### ISSUE TITLE
Usability Adjustments

### ISSUE THREAD

**Issue by RuanLucasGD** [armory3d/armorpaint#1224]
Hi, I've been using Armorpaint for a few days and I have some small tweaking tips that can bring a better experience to users.

1 - Enlarge the sliders in the upper options bar (will help to select smaller values more accurately)

2 - Zoom in on the 2D viewport (Helps paint smaller parts of the UV)

**Comment by MathemanFlo** [comment]
I think 2 is already possible, isn't it? Just zoom in the 2D viewport by scrolling. Please notice that the brush size is independent of the zoom level (which is great because you can zoom out and in while painting). So if you want to paint smaller details zoom in and reduce the brush size.

**Comment by MathemanFlo** [comment]
@luboslenco Maybe this isssue is resolved becau selecting values bacame much easier with https://github.com/armory3d/zui/pull/146
