### ISSUE TITLE
When i try building in release of x64 i am warned that i need v143 build tools, however i already have desktop development tools in visual studio, what do i do?

### ISSUE THREAD

**Issue by bustzee** [armory3d/armorpaint#1225]
**ArmorPaint version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Comment by MathemanFlo** [comment]
Do you use VS 2019 or VS 2022? In case you use the first you should change the platform toolset in your visual studio solution to a toolset you have installed. You can find this option in the general tab in the ArmorPaint solution properties. 

Screenshot, unfortunately German but I'm sure you understand what I mean:
![grafik](https://user-images.githubusercontent.com/28649121/147453475-8ff6f166-f91f-45aa-b8b0-990d1b19dc21.png)

**Comment by luboslenco** [comment]
Should be resolved via VS 2022.
