### ISSUE TITLE
How to visualize height?

### ISSUE THREAD

**Issue by Forteskun** [armory3d/armorpaint#1227]
I'm trying to paint a carved detail, but in viewport I'm unable to see height. Is there some checkbox I forgot to activate to see height? Or it is still not possible?
![Captura de pantalla 2021-12-30 000635](https://user-images.githubusercontent.com/93223122/147709611-5d841942-edaa-454f-b4ab-e6e8a321487f.png)
![Captura de pantalla 2021-12-30 000743](https://user-images.githubusercontent.com/93223122/147709649-c21e9756-284e-4cbb-89e4-eed8ac32a092.png)
(2nd image is height mode)
As you see in the screenshots, there is no trace of visual representation of the height

**Comment by MathemanFlo** [comment]
For me it works (I painted several heights):
![grafik](https://user-images.githubusercontent.com/28649121/147735324-ed4f4d3d-e070-407c-a60a-6a41a5e3e846.png)
Would you please check Edit-> Perferences -> Viewport -> Displacement Strength. Set it to a non-zero value should produce the effect you see in my screenshot.

**Comment by Forteskun** [comment]
All right, I checked your instructions and, although it wasn't required to activate Displacement Strength, you were right.
At first I thought it was just a singular bug in one file (happened to me before) but then I realized that there was 2 issues:
-You cannot paint negative heights (they appear flat)
-If you create a fill layer, then create a black mask, and at last try to paint in the mask the shape you wanted to be craved; the result is that there is no trace of visual representation of height (because it's there)

Here's the layers setup I mention:
![image](https://user-images.githubusercontent.com/93223122/147742049-18e5319a-9dde-4cf7-b1d8-96f4a354e8c8.png)

And here the results: at left the material with black mask added, at right the same material painted in a Paint Layer.
![Captura de pantalla 2021-12-30 110530](https://user-images.githubusercontent.com/93223122/147741961-36cb174d-1085-4e7e-ac1e-d6723f0e2452.png)
![Captura de pantalla 2021-12-30 110557](https://user-images.githubusercontent.com/93223122/147741966-36631b31-37ac-4fbb-a921-6d229ce4a2b3.png)

Have you ever tried to paint negative height? O to paint a black mask over a Fill Layer with height? It worked for you?
If not, we maybe should open a Bug Report / Feature request

**Comment by MathemanFlo** [comment]
The range of height maps is from 0 (minimum Height) to 1 (maximum height). In order to paint "hills" and "valleys" you have to paint a height of 0.5 first and then paint the holes and hills. 
![grafik](https://user-images.githubusercontent.com/28649121/147744189-648e0b64-1eda-46dd-b107-3ac4da1eeb94.png)

The second thing is a bug which I can reproduce. 
1. Fill a layer with height 1.
2. Add a black mask
3. Paint something. 
4. The height is not used.

All in all I agree with you, painting heights is relatively clunky. 

A way to by-pass at least a few issues would be to paint a height texture and then to convert it to a normal map via the Normal Map node.

**Comment by Forteskun** [comment]
Yeah I know that the height range goes from 0 to 1, I guess I am bad used to Substance Painter which allowed me to paint negative height without nedding to set a mid-height layer first.
![image](https://user-images.githubusercontent.com/93223122/147759290-6ce5e379-c073-4d32-8398-a390c1cae2dc.png)

Well, seems like it's just a matter of getting used to it, or maybe wait the height system to be changed in the future.

For now, I think I'm going to report the bug to be known, and close this question.
Thank you for your help, I'll try your workarounds since they sound kinda helpful.
