### ISSUE TITLE
GL Error 1282 PipelineStateImpl.cpp (git version)

### ISSUE THREAD

**Issue by wilsoft-gt** [armory3d/armorpaint#123]
![Captura de pantalla 2019-06-04 10:44:03](https://user-images.githubusercontent.com/27575726/58898167-33573080-86b7-11e9-8f46-19994eeac224.png)

`GL Error 1282 ../../Kore/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.cpp 197`

Ubuntu 18.04
ArmorPaint - v0.6 (2019-06-04) - 3db0b75
Node v8.10.0
clang version 6.0.0-1ubuntu2

I'm not sure if it is needed but:
Nvidia GTX 1060
Nvidia Driver 430.14

**Comment by luboslenco** [comment]
Git version needs some updating for opengl, sorry. Will get that sorted in coming days.

**Comment by luboslenco** [comment]
Fixed now! Please note the updated build step for Linux:
https://github.com/armory3d/armorpaint/commit/a1f61403b88b5ac9e0f689c2dc78337dc3915588

(cleaning the `/build` folder might be needed if already present)
