### ISSUE TITLE
Error when trying to build from source

### ISSUE THREAD

**Issue by itsleviathan0** [armory3d/armorpaint#1232]
I keep getting this error when i try to build from source can anyone please help me out? (i'm using ubuntu 21.04)

Here is the terminal

/home/darik/Desktop/armorpaint/Libraries/iron/Sources/iron/data/Geometry.hx:9: characters 8-28 : Type not found : kha.arrays.ByteArray
/home/darik/Desktop/armorpaint/Libraries/iron/Sources/iron/data/Geometry.hx:31: characters 23-32 : Type not found : ByteArray

Haxe compiler error.

**Comment by todirbg** [comment]
It is not just you, there is an issue with the last commit. Until it is resolved roll back to 1bdd741.
```
git checkout 1bdd741
git submodule update --init --recursive
```
Build it and than switch back to latest to keep the code current
```
git switch -
git submodule update --init --recursive
```

**Comment by itsleviathan0** [comment]
> 

Sorry i don't understand can you explain what i should do step by step please?

**Comment by todirbg** [comment]
Well this is step by step :)
Open terminal in the cloned armorpaint folder and type(copy) the first 2 commands. Then build as usual.

**Comment by itsleviathan0** [comment]
right i wasn't in the right directory but now it works thank you very much!
