### ISSUE TITLE
Empty `changes.md` file in repository root

### ISSUE THREAD

**Issue by Calinou** [armory3d/armorpaint#1235]
There in a empty `changes.md` file in the repository root: https://github.com/armory3d/armorpaint/blob/master/changes.md

It doesn't appear to be referenced anywhere in the codebase. Should it be removed?

**Comment by luboslenco** [comment]
Removed at https://github.com/armory3d/armorpaint/commit/ee743c79ca6bda28a9d04d6a63c79907890ce959.
