### ISSUE TITLE
Reimport mesh results in empty layerstack

### ISSUE THREAD

**Issue by ikonnow** [armory3d/armorpaint#1239]
ArmorPaint 0.9-1bdd741, Windows

**Issue description:**
when reimporting an .obj mesh (multiple materials / objects), the layerstack is completely purged. The materials remain, but all layers and groups are gone, which makes the reimport virtually pointless, so the mesh must be finalized in the workflow before armorpaint is used. For me, reimport is one of the core features! Expected: the layerstack remains - all work done until then is still there. (in Substance Painter, for example, masks even get regenerated on reimport)

**Steps to reproduce:**
a project was created, an .obj with several materials was imported and split by materials. now, during the texturing process, different fill layers and paint layers as well as masks were created. after a few UV errors were noticed in the workflow, the mesh was optimized (only UV / mesh changes to 1 material - no renaming). After the mesh was re-imported via the reimport function, the import popup for the splitting of the mesh appears again, after material splitting was selected again, after clicking ok the layers ar gone.

**Comment by luboslenco** [comment]
Thanks for report. Hm I am probably missing some step to correctly reproduce the issue. Do you get this even in some minimal case? Like importing a simple cube.obj file, creating a paint layer and reimporting the mesh.

**Comment by ikonnow** [comment]
> Thanks for report. Hm I am probably missing some step to correctly reproduce the issue. Do you get this even in some minimal case? Like importing a simple cube.obj file, creating a paint layer and reimporting the mesh.

I did test this with several materials assigned. if necessary, i will provide you with a mesh.

**Comment by ikonnow** [comment]
> Thanks for report. Hm I am probably missing some step to correctly reproduce the issue. Do you get this even in some minimal case? Like importing a simple cube.obj file, creating a paint layer and reimporting the mesh.

after much more testing, i found out that mainfold faces can be the problem (this also leads to faces not being rendered at all) and the temp cached files. The mesh problems are of course due to me, as for the incorrect display of a correct mesh after reimport, I could only find a solution after close open or in doubt after a restart of the PC.
