### ISSUE TITLE
Pen Navigation

### ISSUE THREAD

**Issue by squeige** [armory3d/armorpaint#124]
I am working with a Wacom Intuos 5, Windows 10. One item that is really problematic is I hold F key to resize the drawing brush but it is super sensitive almost to the point where not usable.

A small recommendation as well for navigation, I don`t use the buttons on my pen I usually sculpt and then use ctrl, alt or shift to rotate pan or zoom. Currently I can only rotate while using the pen since we don`t really have a middle mouse button. Maybe have a navigation preset or being able to customize them?

**Comment by squeige** [comment]
In Blender we have an option to emulate 3 button mouse. This would work wonders.

**Comment by luboslenco** [comment]
Should be better in latest builds - fixed brush resizing being super sensitive and keymap is now fully configurable in preferences. Thanks for report!
