### ISSUE TITLE
Do not change slider value on a single click

### ISSUE THREAD

**Issue by ncuxonaT** [armory3d/armorpaint#1244]
When you click on a slider to enter manual editing, its value changes. This is very annoying but also could break UI if you want to edit the "ui scale" value.
![ui_scale](https://user-images.githubusercontent.com/15171368/151233585-09e28fd7-6905-403f-8644-5f9855a2796b.png)

**Comment by MathemanFlo** [comment]
@luboslenco This one can be closed now due to #146 .

**Comment by ncuxonaT** [comment]
Yes, thank you
