### ISSUE TITLE
Import fbx error

### ISSUE THREAD

**Issue by jayanam** [armory3d/armorpaint#125]
Hi,

when I export the simple default cube, unwrapped, from Blender 2.8 and drag it into the latest version of Armorpaint, it looks like this

![image](https://user-images.githubusercontent.com/18039584/58908798-d177e480-8711-11e9-8bb6-f07b11a563a9.png)

Obj with the model works.

**Comment by luboslenco** [comment]
Fixed in the latest builds, thanks for reporting this bug!

**Comment by jayanam** [comment]
> Fixed in the latest builds, thanks for reporting this bug!

Thx for fixing:-)
