### ISSUE TITLE
I cant open the Armorpaint app anymore...

### ISSUE THREAD

**Issue by Todynhoodobem** [armory3d/armorpaint#1256]
I just compiled it, opened and it worked just fine, but after closing it and turning my PC off i cant open the programm anymore, would you guys have a solution? Keep it up with the great work, loved the programm

**Comment by luboslenco** [comment]
Hello, which OS?

**Comment by luboslenco** [comment]
Many thanks for your support. Feel welcome to report any issues you might run into.

**Comment by raduprv** [comment]
I am having the same problem, only that it didn't even work the first time I built it.
I built it from yesterday's code, when I start the exe it closes. No window, no error message, no nothing.

**Comment by MathemanFlo** [comment]
Take a look at #1162. Did you do that?
