### ISSUE TITLE
Problem when building on Windows

### ISSUE THREAD

**Issue by raduprv** [armory3d/armorpaint#1258]
I am trying to compile the latest git version on Windows. I followed the instructions, and when I got to "node Kinc/make -g direct3d11" part, after building the shaders I got the following error:
"Error while reading the registry: ProcessUncleanExitError: QUERY command exited with code 1:

ERROR: The system was unable to find the specified registry key or value.
Could not find a Windows SDK, make sure Visual Studio is installed with C/C++ support."

I have VisualStudio 2022 installed. Any idea what I should do?

**Comment by luboslenco** [comment]
Hello, thanks for report. Selecting `Desktop development with C++` component in the Visual Studio installer should resolve the issue.

https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=msvc-170#step-4---choose-workloads

**Comment by raduprv** [comment]
Thank you, that solved it. I then built it in the Release mode (the debug mode didn't work), but nothing happens when I run the compiled program. I start the exe file and it doesn't do anything. No window, no error, no nothing. Any ideas?

**Comment by MathemanFlo** [comment]
You might want to take a look at https://github.com/armory3d/armorpaint/issues/1162. Does that work for you?

**Comment by raduprv** [comment]
That worked, thank you!
