### ISSUE TITLE
ArmorPaint is not compiling on ubuntu 18.04lts (git version)

### ISSUE THREAD

**Issue by vijaygithub01** [armory3d/armorpaint#126]
I was trying to install ArmorPaint in my ubuntu machine, but i was getting a error each time i was trying to intall it.
As mension in the readm file:
Me installed clang in my Pc, than node and lastly i installed git. i thought there is a problem in the version so i unpgraded all the programs i downloaded but i still am getting this error
![Screenshot from 2019-06-05 11-42-46](https://user-images.githubusercontent.com/51396355/58934305-b051db00-8787-11e9-860e-31a039eb84db.png)

**Comment by vijaygithub01** [comment]
I Have installed git version git version 2.17.1 installed on my machine, nodejs versions git version 2.17.1 and clang version is git version 2.17.1
![versions'](https://user-images.githubusercontent.com/51396355/59005604-ecdf0e80-883b-11e9-90c8-6273ec1e6b00.png)

**Comment by sh-dave** [comment]
Did you do a `--recursive` clone of the repo, and could you show the actual commandline you're trying to run?

**Comment by vijaygithub01** [comment]
There are all the commands i have used:-
![First](https://user-images.githubusercontent.com/51396355/59082211-a78c1100-890f-11e9-8f6f-45ac8df67e4c.png)
![second](https://user-images.githubusercontent.com/51396355/59082216-aa870180-890f-11e9-8b60-d46c2bf66919.png)
![Third](https://user-images.githubusercontent.com/51396355/59082219-ace95b80-890f-11e9-8cf3-8df2c4f834ec.png)

**Comment by sh-dave** [comment]
What does `make --version` output? `make` will be the next thing that will be called to build for the linux target. And seeing a `ENOENT` (basically file not found) might suggest it's missing.

**Comment by luboslenco** [comment]
Fingers crossed, thanks for help @sh-dave. Added `make` mention to the readme. https://github.com/armory3d/armorpaint/commit/d90b1a5ce203932e24101e6884231cdcee1597f4

**Comment by vijaygithub01** [comment]
After installing the gnu make i deleted the armorpaint folder from my home directory, and again started with the command:-
git clone --recursive https://github.com/armory3d/armorpaint
after this i followed all the commands but after:-
node Kore/make -g opengl --compiler clang --compile
this command i got this result
![Compilation failed](https://user-images.githubusercontent.com/51396355/59087902-a533b200-8923-11e9-9cd6-dfc4ff943ab8.png)
![make version](https://user-images.githubusercontent.com/51396355/59087938-c72d3480-8923-11e9-930a-6897c33be55e.png)

**Comment by sh-dave** [comment]
Ok at least it's starting to compile now. Can you attach the log for that as the short snippet only shows warning, no errors. It should be ok to just rerun `node Kore/make -g opengl --compiler clang --compile`.

**Comment by vijaygithub01** [comment]
okay i m going to give it a try.

**Comment by vijaygithub01** [comment]
no i am still getting the same output it says compilation failed
and it says something about fetal error.
the warnings are related to clang will it be helpful if i will reinstall clang
![Warning 1](https://user-images.githubusercontent.com/51396355/59090084-60127e80-8929-11e9-9274-fc1a0d6caa63.png)
![warning 3](https://user-images.githubusercontent.com/51396355/59090087-61dc4200-8929-11e9-83eb-9f7fa003dce3.png)
![warning 2](https://user-images.githubusercontent.com/51396355/59090089-643e9c00-8929-11e9-91dd-d96cd552d0dd.png)

**Comment by sh-dave** [comment]
You're missing the x11 development libraries, try to install `libx11-dev`

**Comment by sh-dave** [comment]
And as you're already missing the x11 ones, you're probably going to need these as well:

- `libasound2-dev`
- `libxi-dev`
- `libxinerama-dev`
- `mesa-common-dev`

**Comment by vijaygithub01** [comment]
okay thanks a-lot. i m, installing libx11 and will install all these too.

**Comment by vijaygithub01** [comment]
i am still facin g a Krom Error 1
![Krom Errro 1](https://user-images.githubusercontent.com/51396355/59091209-7bcb5400-892c-11e9-93fa-29eeaee3ddbf.png)

**Comment by sh-dave** [comment]
Oh, it compiled and it's trying to link now. Install `libgl-dev` as well.

**Comment by luboslenco** [comment]
I have updated readme linking to this page now:
https://github.com/Kode/Kha/wiki/Linux

Once you have all the dependencies you will get the build process to succeed. 🙂

**Comment by vijaygithub01** [comment]
when  i m trying to run build/Krom for executable its not working is there any other command fro executing this file

**Comment by sh-dave** [comment]
Does it log anything when you try to run it?

**Comment by eddybiersack** [comment]
> i am still facin g a Krom Error 1
> ![Krom Errro 1](https://user-images.githubusercontent.com/51396355/59091209-7bcb5400-892c-11e9-93fa-29eeaee3ddbf.png)

i solved the error same as your error by updating the clang version.
