### ISSUE TITLE
Build for Windows 10 Failed

### ISSUE THREAD

**Issue by Mechanical-Games** [armory3d/armorpaint#127]
When building the latest version I get a couple of errors from visual studio. Console of visual studio is below

![image](https://user-images.githubusercontent.com/49130644/59066281-922ecc80-88a6-11e9-9613-fc16e07c3c14.png)

and the error list
![image](https://user-images.githubusercontent.com/49130644/59065256-2ea39f80-88a4-11e9-88a0-1da0ddf0e4c1.png)

and here is the cloning thing in git bash

`
Me MINGW64 ~
$ git clone --recursive https://github.com/armory3d/armorpaint
Cloning into 'armorpaint'...
remote: Enumerating objects: 548, done.
remote: Counting objects: 100% (548/548), done.
remote: Compressing objects: 100% (376/376), done.
remote: Total 3598 (delta 289), reused 389 (delta 146), pack-reused 3050
Receiving objects: 100% (3598/3598), 39.31 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (2129/2129), done.
Checking out files: 100% (198/198), done.
Submodule 'Kha' (https://github.com/armory3d/Kha) registered for path 'Kha'
Submodule 'Krom' (https://github.com/armory3d/Krom_armorpaint) registered for path 'Krom'
Submodule 'Libraries/armory' (https://github.com/armory3d/armory) registered for path 'Libraries/armory'
Submodule 'Libraries/iron' (https://github.com/armory3d/iron) registered for path 'Libraries/iron'
Submodule 'Libraries/iron_format' (https://github.com/armory3d/iron_format) registered for path 'Libraries/iron_format'
Submodule 'Libraries/zui' (https://github.com/armory3d/zui) registered for path 'Libraries/zui'
Cloning into 'C:/Users/Rando/armorpaint/Kha'...
remote: Enumerating objects: 1097, done.
remote: Counting objects: 100% (1097/1097), done.
remote: Compressing objects: 100% (920/920), done.
remote: Total 1097 (delta 231), reused 593 (delta 108), pack-reused 0
Receiving objects: 100% (1097/1097), 977.62 KiB | 783.00 KiB/s, done.
Resolving deltas: 100% (231/231), done.
Cloning into 'C:/Users/Rando/armorpaint/Krom'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (134/134), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 134 (delta 8), reused 111 (delta 7), pack-reused 0
Receiving objects: 100% (134/134), 2.64 MiB | 1.09 MiB/s, done.
Resolving deltas: 100% (8/8), done.
Cloning into 'C:/Users/Rando/armorpaint/Libraries/armory'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 24757 (delta 0), reused 2 (delta 0), pack-reused 24752
Receiving objects: 100% (24757/24757), 59.73 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (18905/18905), done.
Cloning into 'C:/Users/Rando/armorpaint/Libraries/iron'...
remote: Enumerating objects: 258, done.
remote: Counting objects: 100% (258/258), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 7048 (delta 138), reused 194 (delta 101), pack-reused 6790
Receiving objects: 100% (7048/7048), 1.65 MiB | 2.06 MiB/s, done.
Resolving deltas: 100% (4845/4845), done.
Cloning into 'C:/Users/Rando/armorpaint/Libraries/iron_format'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 359 (delta 14), reused 61 (delta 13), pack-reused 295
Receiving objects: 100% (359/359), 119.52 KiB | 7.03 MiB/s, done.
Resolving deltas: 100% (113/113), done.
Cloning into 'C:/Users/Rando/armorpaint/Libraries/zui'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 2506 (delta 12), reused 21 (delta 10), pack-reused 2480
Receiving objects: 100% (2506/2506), 2.14 MiB | 3.33 MiB/s, done.
Resolving deltas: 100% (1500/1500), done.
Submodule path 'Kha': checked out '211cb8821407bbfd4669f60a33fb5411151e9435'
Submodule 'Backends/Kore/khacpp' (https://github.com/armory3d/khacpp.git) registered for path 'Kha/Backends/Kore/khacpp'
Submodule 'Kore' (https://github.com/armory3d/Kore.git) registered for path 'Kha/Kore'
Submodule 'Tools/haxe' (https://github.com/armory3d/haxe_bin.git) registered for path 'Kha/Tools/haxe'
Submodule 'Tools/khamake' (https://github.com/armory3d/khamake.git) registered for path 'Kha/Tools/khamake'
Submodule 'Tools/kravur' (https://github.com/armory3d/kravur_bin.git) registered for path 'Kha/Tools/kravur'
Submodule 'Tools/lame' (https://github.com/armory3d/lame_bin.git) registered for path 'Kha/Tools/lame'
Submodule 'Tools/oggenc' (https://github.com/armory3d/oggenc_bin.git) registered for path 'Kha/Tools/oggenc'
Cloning into 'C:/Users/Rando/armorpaint/Kha/Backends/Kore/khacpp'...
remote: Enumerating objects: 20660, done.
remote: Total 20660 (delta 0), reused 0 (delta 0), pack-reused 20660
Receiving objects: 100% (20660/20660), 28.96 MiB | 1.34 MiB/s, done.
Resolving deltas: 100% (14970/14970), done.
Cloning into 'C:/Users/Rando/armorpaint/Kha/Kore'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 23393 (delta 0), reused 1 (delta 0), pack-reused 23390
Receiving objects: 100% (23393/23393), 13.80 MiB | 1.44 MiB/s, done.
Resolving deltas: 100% (12913/12913), done.
Cloning into 'C:/Users/Rando/armorpaint/Kha/Tools/haxe'...
remote: Enumerating objects: 4235, done.
remote: Counting objects: 100% (4235/4235), done.
remote: Compressing objects: 100% (2736/2736), done.
remote: Total 4235 (delta 2825), reused 2041 (delta 1463), pack-reused 0
Receiving objects: 100% (4235/4235), 47.47 MiB | 1.54 MiB/s, done.
Resolving deltas: 100% (2825/2825), done.
Cloning into 'C:/Users/Rando/armorpaint/Kha/Tools/khamake'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 8646 (delta 71), reused 86 (delta 63), pack-reused 8538
Receiving objects: 100% (8646/8646), 4.83 MiB | 1.96 MiB/s, done.
Resolving deltas: 100% (4980/4980), done.
Cloning into 'C:/Users/Rando/armorpaint/Kha/Tools/kravur'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 6 (delta 0), pack-reused 0
Cloning into 'C:/Users/Rando/armorpaint/Kha/Tools/lame'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 6 (delta 0), pack-reused 0
Cloning into 'C:/Users/Rando/armorpaint/Kha/Tools/oggenc'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 6 (delta 0), pack-reused 0
Submodule path 'Kha/Backends/Kore/khacpp': checked out 'ed25ee54b5a29e4403eccc9a85a1e44ed685bd1a'
Submodule path 'Kha/Kore': checked out '5d5c11ed92c414591300563a7f5fc046ed681a5c'
Submodule 'Tools/koremake' (https://github.com/armory3d/koremake.git) registered for path 'Kha/Kore/Tools/koremake'
Submodule 'Tools/kraffiti' (https://github.com/armory3d/kraffiti_bin.git) registered for path 'Kha/Kore/Tools/kraffiti'
Submodule 'Tools/krafix' (https://github.com/armory3d/krafix_bin.git) registered for path 'Kha/Kore/Tools/krafix'
Cloning into 'C:/Users/Rando/armorpaint/Kha/Kore/Tools/koremake'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 6517 (delta 21), reused 24 (delta 18), pack-reused 6473
Receiving objects: 100% (6517/6517), 4.57 MiB | 2.00 MiB/s, done.
Resolving deltas: 100% (3312/3312), done.
Cloning into 'C:/Users/Rando/armorpaint/Kha/Kore/Tools/kraffiti'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 13 (delta 2), reused 6 (delta 1), pack-reused 0
Cloning into 'C:/Users/Rando/armorpaint/Kha/Kore/Tools/krafix'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 0), reused 6 (delta 0), pack-reused 0
Submodule path 'Kha/Kore/Tools/koremake': checked out '83ab37191aaf301758e4aaaf0507c525fdc277af'
Submodule path 'Kha/Kore/Tools/kraffiti': checked out '1a589c357b7716b6643d318eca937d81902e778a'
Submodule path 'Kha/Kore/Tools/krafix': checked out '5a2dc7d376bf5aef638a6d4561d0d2094ed74a75'
Submodule path 'Kha/Tools/haxe': checked out 'c64dc3336cb8b6a28852a8ebe5d6d540f567ba12'
Submodule path 'Kha/Tools/khamake': checked out 'beb5c43529f188720fabe0ad14428613fd6a9011'
Submodule path 'Kha/Tools/kravur': checked out '224bfe99eebe2fa7d30659ca8f0fc435f312d66d'
Submodule path 'Kha/Tools/lame': checked out '7e10dc2dd39444a97444a6b07635a7786b227bcb'
Submodule path 'Kha/Tools/oggenc': checked out 'dcb7978e77c5154ecfd2c3931c0aae1ce68c5fee'
Submodule path 'Krom': checked out '37e7247dc6e66c77ec0b276007a8c80e1298eca6'
Submodule 'Chakra' (https://github.com/armory3d/ChakraCore.git) registered for path 'Krom/Chakra'
Submodule 'Kore' (https://github.com/armory3d/Kore.git) registered for path 'Krom/Kore'
Cloning into 'C:/Users/Rando/armorpaint/Krom/Chakra'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Total 109641 (delta 1), reused 1 (delta 1), pack-reused 109639
Receiving objects: 100% (109641/109641), 132.70 MiB | 1.83 MiB/s, done.
Resolving deltas: 100% (88236/88236), done.
Cloning into 'C:/Users/Rando/armorpaint/Krom/Kore'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 23393 (delta 0), reused 1 (delta 0), pack-reused 23390
Receiving objects: 100% (23393/23393), 13.80 MiB | 1.36 MiB/s, done.
Resolving deltas: 100% (12913/12913), done.
Submodule path 'Krom/Chakra': checked out '8053ef846b1fd12f52649806355ea33e49e23ab5'
Submodule path 'Krom/Kore': checked out '5d5c11ed92c414591300563a7f5fc046ed681a5c'
Submodule 'Tools/koremake' (https://github.com/armory3d/koremake.git) registered for path 'Krom/Kore/Tools/koremake'
Submodule 'Tools/kraffiti' (https://github.com/armory3d/kraffiti_bin.git) registered for path 'Krom/Kore/Tools/kraffiti'
Submodule 'Tools/krafix' (https://github.com/armory3d/krafix_bin.git) registered for path 'Krom/Kore/Tools/krafix'
Cloning into 'C:/Users/Rando/armorpaint/Krom/Kore/Tools/koremake'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 6517 (delta 21), reused 24 (delta 18), pack-reused 6473 
Receiving objects: 100% (6517/6517), 4.57 MiB | 1.09 MiB/s, done.
Resolving deltas: 100% (3312/3312), done.
Cloning into 'C:/Users/Rando/armorpaint/Krom/Kore/Tools/kraffiti'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 13 (delta 2), reused 6 (delta 1), pack-reused 0
Cloning into 'C:/Users/Rando/armorpaint/Krom/Kore/Tools/krafix'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 0), reused 6 (delta 0), pack-reused 0
Submodule path 'Krom/Kore/Tools/koremake': checked out '83ab37191aaf301758e4aaaf0507c525fdc277af'
Submodule path 'Krom/Kore/Tools/kraffiti': checked out '1a589c357b7716b6643d318eca937d81902e778a'
Submodule path 'Krom/Kore/Tools/krafix': checked out '5a2dc7d376bf5aef638a6d4561d0d2094ed74a75'
Submodule path 'Libraries/armory': checked out 'f4a9cceebe24de6ae4ce52ae646d6b9b74a796f2'
Submodule path 'Libraries/iron': checked out 'a08ebfc89ca5564d8a2b32d24ffbdb0ce9794eff'
Submodule path 'Libraries/iron_format': checked out '99cbb8ca69436b25404e27d2918ccf45e53c976d'
Submodule path 'Libraries/zui': checked out 'ead42481a758061f9340c813e426f195f71f4c3b'

ME MINGW64 ~
$ cd armorpaint

ME MINGW64 ~/armorpaint (master)
$ node Kha/make krom -g direct3d11
Using Kha from C:\Users\Rando\armorpaint\Kha
Creating Kha project.
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 19 (World.hdr).
Exporting asset 2 of 19 (World_irradiance.arm).
Exporting asset 3 of 19 (World_radiance.hdr).
Exporting asset 4 of 19 (World_radiance_0.hdr).
Exporting asset 5 of 19 (World_radiance_1.hdr).
Exporting asset 6 of 19 (World_radiance_2.hdr).
Exporting asset 7 of 19 (World_radiance_3.hdr).
Exporting asset 8 of 19 (World_radiance_4.hdr).
Exporting asset 9 of 19 (World_radiance_5.hdr).
Exporting asset 10 of 19 (World_radiance_6.hdr).
Exporting asset 11 of 19 (World_radiance_7.hdr).
Exporting asset 12 of 19 (World_radiance_8.hdr).
Exporting asset 13 of 19 (World_radiance_9.hdr).
Exporting asset 14 of 19 (config.arm).
Exporting asset 15 of 19 (color_wheel.png).
Exporting asset 16 of 19 (cursor.png).
Exporting asset 17 of 19 (font13.bin).
Exporting asset 18 of 19 (icons2x.png).
Exporting asset 19 of 19 (icons.png).
Exporting asset 1 of 2 (default_brush.json).
Exporting asset 2 of 2 (default_material.json).
Exporting asset 1 of 5 (authors.md).
Exporting asset 2 of 5 (license.md).
Exporting asset 3 of 5 (license_cmft.md).
Exporting asset 4 of 5 (license_cycles-nodes.md).
Exporting asset 5 of 5 (license_lz4-wasm.md).
Exporting asset 1 of 2 (plugin_hello.js).
Exporting asset 2 of 2 (plugin_rotate.js).
Exporting asset 1 of 2 (theme_light.arm).
Exporting asset 2 of 2 (theme_dark.arm).
Exporting asset 1 of 1 (readme.txt).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise256.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (font_default.ttf).
Exporting asset 1 of 1 (cmft.exe).
Compiling shader 1 of 33 (Gizmo_overlay.frag.glsl).
Compiling shader 2 of 33 (Gizmo_overlay.vert.glsl).
Compiling shader 3 of 33 (Material2_mesh.frag.glsl).
Compiling shader 4 of 33 (Material_mesh.frag.glsl).
Compiling shader 5 of 33 (Material_mesh.vert.glsl).
Compiling shader 6 of 33 (armdefault_mesh.vert.glsl).
Compiling shader 7 of 33 (armdefault_mesh.frag.glsl).
Compiling shader 8 of 33 (bloom_pass.frag.glsl).
Compiling shader 9 of 33 (blur_adaptive_pass.frag.glsl).
Compiling shader 10 of 33 (blur_edge_pass.frag.glsl).
Compiling shader 11 of 33 (blur_gaus_pass.frag.glsl).
Compiling shader 12 of 33 (compositor_pass.frag.glsl).
Compiling shader 13 of 33 (compositor_pass.vert.glsl).
Compiling shader 14 of 33 (copy_mrt3_pass.frag.glsl).
Compiling shader 15 of 33 (deferred_light.frag.glsl).
Compiling shader 16 of 33 (deferred_light_VoxelAOvar.frag.glsl).
Compiling shader 17 of 33 (deferred_light_VoxelAOvar.vert.glsl).
Compiling shader 18 of 33 (pass.vert.glsl).
Compiling shader 19 of 33 (pass_copy.frag.glsl).
Compiling shader 20 of 33 (pass_viewray.vert.glsl).
Compiling shader 21 of 33 (pass_viewray2.vert.glsl).
Compiling shader 22 of 33 (smaa_blend_weight.frag.glsl).
Compiling shader 23 of 33 (smaa_edge_detect.frag.glsl).
Compiling shader 24 of 33 (smaa_blend_weight.vert.glsl).
Compiling shader 25 of 33 (smaa_edge_detect.vert.glsl).
Compiling shader 26 of 33 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 27 of 33 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 28 of 33 (ssgi_pass.frag.glsl).
Compiling shader 29 of 33 (ssr_pass.frag.glsl).
Compiling shader 30 of 33 (supersample_resolve.frag.glsl).
Compiling shader 31 of 33 (taa_pass.frag.glsl).
Compiling shader 32 of 33 (world_pass.frag.glsl).
Compiling shader 33 of 33 (world_pass.vert.glsl).
Compiling shader 1 of 4 (Material_voxel.vert.glsl).
Compiling shader 2 of 4 (armdefault_voxel.frag.glsl).
Compiling shader 3 of 4 (armdefault_voxel.geom.glsl).
Compiling shader 4 of 4 (armdefault_voxel.vert.glsl).
Compiling shader 1 of 8 (painter-colored.vert.glsl).
Compiling shader 2 of 8 (painter-image.frag.glsl).
Compiling shader 3 of 8 (painter-image.vert.glsl).
Compiling shader 4 of 8 (painter-colored.frag.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.vert.glsl).
Compiling shader 8 of 8 (painter-video.frag.glsl).
Done.

MEE MINGW64 ~/armorpaint (master)
$ cd Krom

ME MINGW64 ~/armorpaint/Krom ((37e7247...))
$ node Kore/make -g direct3d11
korefile found.
Creating Windows project files.
Compiling shader 1 of 10 (g1.frag).
Compiling shader 2 of 10 (g1.vert).
Compiling shader 3 of 10 (painter-colored.frag).
Compiling shader 4 of 10 (painter-colored.vert).
Compiling shader 5 of 10 (painter-image.frag).
Compiling shader 6 of 10 (painter-image.vert).
Compiling shader 7 of 10 (painter-text.frag).
Compiling shader 8 of 10 (painter-text.vert).
Compiling shader 9 of 10 (painter-video.frag).
Compiling shader 10 of 10 (painter-video.vert).

Me MINGW64 ~/armorpaint/Krom ((37e7247...))
$ 
`

**Comment by luboslenco** [comment]
Something is not playing nice with the Visual Studio setup..:/ Maybe helpful:
- Verify `Desktop development with C++` component is installed
- https://stackoverflow.com/questions/22188919/windows-sdk-registry-variable-not-found
- https://www.youtube.com/watch?v=dk9OOP4DmoU
