### ISSUE TITLE
Import .obj issue on Tab s7

### ISSUE THREAD

**Issue by AmateroL** [armory3d/armorpaint#1273]
Tried to import obj files into Armor Paint v.9 for Android. Via drag and drop or via mesh import. Same result, app shows a pop up message " Importing Mesh" and then freezes.  Even with a small obj. File i get this issue. 

Using a Tab S7 with 8GB RAM with Android 12.  

*ArmorPaint 0.9-f9dab61, Android*

**Issue description:**

**Steps to reproduce:**

**Comment by AMGizzle** [comment]
Having same issue on galaxy s10 cannot import any mesh, .obj .fbx or .glb get error failed to load mesh when drag and dropping mesh. If I switch split to UDMI it crashes.

**Comment by luboslenco** [comment]
Pushed a new update (220215) to resolve file access issues. File picker, Samsung My Files app and drag and drop should work on Android 10, 11, 12. Feel welcome to post more Android issues, thanks for notice!
