### ISSUE TITLE
Clicking two times on hex value in RGB node and using the arrow keys to navigate moves the whole node

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1278]
**ArmorPaint version:**
ArmorPaint.org - v0.9 (2022-02-17) - a044960
Windows - Direct3D11

**Issue description:**
If the user clicks two times on the hex edit in order to unselect the text the node itself is moved.

**Steps to reproduce:**
1. Click on an RGB node
2. Go to the Hex tab
3. Click on the edit two times
4. Press left or right arrow-key

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/zui/commit/c63280cbe0f0cc6cae692ced768a6e86ee289fd2, thanks for report!
