### ISSUE TITLE
Armorpaint is not compiling on Pop!_OS 19.04 (git version)

### ISSUE THREAD

**Issue by Powerbyte7** [armory3d/armorpaint#128]
I am trying to compile Armorpaint on my machine, but the compilation fails. I have looked at issue #126 but I still can't get it to work. Help will be very much appreciated.

[Log](https://drive.google.com/file/d/1PIePA4w8DnC1BeI4sl2N9X8FBEgmJ2A0/view?usp=sharing)

OS: Pop!_OS 19.04

**Comment by luboslenco** [comment]
Hey, I am not sure I see any error / failed message there, is that the full log?

**Comment by Powerbyte7** [comment]
I've ran it with this command: node Kore/make -g opengl --compiler clang --compile > compile-log.txt
But you're right that it doesn't include the full log

**Comment by Powerbyte7** [comment]
[Here is the log from the terminal](https://drive.google.com/file/d/1RB86yq6D4Z_rDi7dsi4jYQn77qwmDe9h/view?usp=sharing)

**Comment by luboslenco** [comment]
Looks like the issue at https://github.com/Kode/Krom/issues/129. Maybe older clang version would do? If you gather any more findings please post at https://github.com/Kode/Krom/issues/129.
