### ISSUE TITLE
Multi-undo on brush not possible?

### ISSUE THREAD

**Issue by l0ud** [armory3d/armorpaint#1291]
It seems I can undo-redo only last action on a brush. If I made 2 mistakes when using brush, I can undo one. Undoing one more is not available, option in menu is grayed out.

This seems so fundamental I'm not sure if this is a bug or a missing feature.

**Comment by l0ud** [comment]
False alarm, it seems like I changed the undo steps count setting to 1 by mistake (though I don't remember doing that). Sorry for the noise.

**Comment by MathemanFlo** [comment]
The default number of undo steps is four. As far as I know there are no issues for undoing paint operations. Though the undo system has several issues you can find in the "meta" bug here: https://github.com/armory3d/armorpaint/issues/792
