### ISSUE TITLE
Separate camera speed for rotation, move and zoom.

### ISSUE THREAD

**Issue by l0ud** [armory3d/armorpaint#1292]
It seems like for me:
- dragging an object with shift is way too fast for me - (seems to take a reference point that is moving an object too far away too easily, it doesn't stick to the cursor like in blender)
- rotating the object is in just right speed
- zooming in and out is too slow.

Unfortunately I cannot correct it as camera speed affects all of those things. I would like to have separate sliders to tune that settings.

**Comment by MathemanFlo** [comment]
I'd like to implement this. @luboslenco Any objections?

**Comment by luboslenco** [comment]
Sounds awesome!

**Comment by MathemanFlo** [comment]
Here we go...
@l0ud Does that suit your needs?
![grafik](https://user-images.githubusercontent.com/28649121/156638960-a6932e4d-2f0c-4d64-b723-d26fc2a4bce3.png)

**Comment by l0ud** [comment]
Thank you, I compiled this change, tested and it's working as expected :)
Of course it's still not 1:1 reproduction of blender "feeling" (it would be ideal) but now I can tune it to a very usable state.

**Comment by MathemanFlo** [comment]
Thank you very much @l0ud . Happy to get other bug reports and feature requests.
