### ISSUE TITLE
Roughness and metallic aren't working

### ISSUE THREAD

**Issue by ErkBlender** [armory3d/armorpaint#13]
![image](https://user-images.githubusercontent.com/17138896/40997343-fa5ff118-690c-11e8-9681-5dc292d9c30d.png)
I'm using armory 0.4
The black spot is what happens when the metallic is at 1, and when I try to paint different roughness values it doesn't change anything. I don't think there's any glossiness at all.

**Comment by luboslenco** [comment]
Ah, I guess it's time to start keeping in-development builds in shape as well. Fix in https://github.com/armory3d/armorpaint/commit/47d2f11024601e96a5c65162e77676775d0b56d3.
