### ISSUE TITLE
Text brush size and flipped (git version)

### ISSUE THREAD

**Issue by AFWSI** [armory3d/armorpaint#130]
The text brush(top in screenshot) is flipped. Also, the text is painted is bigger than the text brush. Would be nice if the sizes matched. Built from Github from a couple days ago.

![ArmorPaint_text](https://user-images.githubusercontent.com/24877571/59102565-18243500-88f2-11e9-8026-8d58d81ee596.jpg)

**Comment by luboslenco** [comment]
Hi @AFWSI, which commit are you on? This should no longer happen in latest git.
(but still using 2D decal/text placement https://github.com/armory3d/armorpaint/issues/35#issuecomment-499548923)

**Comment by AFWSI** [comment]
OK, I just got the latest ```commit e9aab115c365fd2e0292378907422eabeb8a4f40``` and it seems to work now.
