### ISSUE TITLE
Eraser paints black

### ISSUE THREAD

**Issue by AFWSI** [armory3d/armorpaint#131]
Eraser paints black in viewport. Would be nice if it's similar to Substance Painter. Added single color and used eraser in both programs. Built from Github couple days ago.

Mesh with no color in Substance Painter.
![Sustance_eraser_no_color](https://user-images.githubusercontent.com/24877571/59102730-97b20400-88f2-11e9-8547-baead6be30b4.jpg)

Eraser in Substance Painter. Takes color off and reveals just the color of mesh.
![Sustance_eraser](https://user-images.githubusercontent.com/24877571/59102742-a3052f80-88f2-11e9-9ee1-4dd80b9073ed.jpg)

Eraser in ArmorPaint.
![ArmorPaint_eraser](https://user-images.githubusercontent.com/24877571/59102757-af898800-88f2-11e9-8419-313eea268730.jpg)

**Comment by luboslenco** [comment]
What determines the color of mesh? Is it always the 'initial' gray color?

**Comment by luboslenco** [comment]
Eraser clears to the initial mesh color (which is gray by default for now) instead of black in updated builds. 🙂
