### ISSUE TITLE
Blender keymap double use of shortcuts

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#1314]
The Blender keymap has double uses of shortcuts
![grafik](https://user-images.githubusercontent.com/28649121/156833479-76e34238-3bfb-404b-8817-5954cdc932b5.png)

**Comment by luboslenco** [comment]
Hm. maybe better after https://github.com/armory3d/armorpaint/commit/0afaed994fbf93c6bba0d428e12da64df48b0658.

**Comment by MathemanFlo** [comment]
Congratulation for 1000 closed issues
![grafik](https://user-images.githubusercontent.com/28649121/162755793-ec29835d-d9ae-441d-8ea7-e266ed46ad33.png)
