### ISSUE TITLE
Switch to Y-up causes insta-core

### ISSUE THREAD

**Issue by pbowmar** [armory3d/armorpaint#132]
Hi,

When trying to switch to Y-Up (before or after importing model) I get:

krom.bin does not match this Krom versionAbort (core dumped)

v0.06rc

Linux64 (openSuse 15.0)

On Kubuntu 18.10 it does the same thing.

Not sure if it's relevant, but I also see this on both platforms:

Uniform N not found.
Uniform texUnpack not found.
Uniform step not found.
Uniform brushScale not found.
Uniform W not found.
Uniform eye not found.
Uniform aspectRatio not found.
Uniform brushScale not found.

**Comment by luboslenco** [comment]
Should work properly now in latest build. Mesh tools changed a bit, geometry can now be rotated arbitrarily around each axis:
![1a](https://user-images.githubusercontent.com/3685704/59368765-3ac5ac00-8d3f-11e9-953b-bbd12bd91929.PNG)
