### ISSUE TITLE
xdg-explorer not found

### ISSUE THREAD

**Issue by pbowmar** [armory3d/armorpaint#133]
Running anything in Help that opens an URL gives me "xdg-explorer not found" on both Kubuntu and OpenSUSE 15.0

I can't even find something called "xdg-explorer" to install :)

If that's a real thing, maybe fall back to "xdg-open" if it's not found? xdg-open is a standard across all (that I know of) Linux distros.

Cheers,

Peter B

**Comment by luboslenco** [comment]
Hi Peter, switched to the "xdg-open" in latest builds, thanks for suggestion!
