### ISSUE TITLE
Glitch in Environment Map

### ISSUE THREAD

**Issue by ABugNamedBeetle** [armory3d/armorpaint#1332]
**OS/device including version:**
windows 10

**Issue description:**
By moving the Environment angle, the Env map is being dragged instead of drawing. Thus producing a glitch effect.

**Steps to reproduce:**

https://user-images.githubusercontent.com/62416701/158030494-e78addfd-460f-44c3-8c54-35717500ff33.mp4

**Comment by MathemanFlo** [comment]
Unfortunately I could not repoduce the shown issue on any machine that is available to me.... Tested it on Nvidia and Intel graphics cards on windows 10.
Maybe it depends on the envmap file? Could you provide it? Alternatively it could be driver bug. Maybe an update could help?

**Comment by ABugNamedBeetle** [comment]
yup, it is not present in the new build.
