### ISSUE TITLE
Visual Studio Build Error

### ISSUE THREAD

**Issue by metkymetky** [armory3d/armorpaint#1336]
Excuse me, I've found a solution.
I was building a wrong .sln file

***

Hello.
I have a problem building ArmorPaint in Visual Studio.

I use Windows 10 and I've downloaded clean files from the repository. I use VS version 2022.

When I Build Solution, the process starts and goes on till it gives these errors:

Severity Code Description Project File Line Suppression State
Error LNK2001 unresolved external symbol kickstart Kinc C:\temp\armorpaint\armorpaint\armorcore\Kinc\build\windowsunit.obj 1

Severity Code Description Project File Line Suppression State
Error LNK1120 1 unresolved externals Kinc C:\temp\armorpaint\armorpaint\armorcore\Kinc\build\x64\Release\Kinc.exe 1

Compilation fails.

![error 01](https://user-images.githubusercontent.com/98658059/158703050-ed83d9ad-054d-4ec6-8002-f02987e02630.jpg)
![output 01](https://user-images.githubusercontent.com/98658059/158703051-f259652b-687e-4d7e-8c10-975c0e9e45bd.jpg)

I would appreciate some help.

**Comment by luboslenco** [comment]
No prob, glad you have found the solution!
