### ISSUE TITLE
[iOS Xcode Build] xcodeproj corrupted?

### ISSUE THREAD

**Issue by omariparris** [armory3d/armorpaint#1337]
**ArmorPaint version:**
0.9 [latest]

**OS/device including version:**
iPhone XR

**Issue description:**
I'm trying to build the latest version on Xcode but the project file isn't opening anymore. Not sure what's causing this.

This is the error that shows when I try to open it.

So the version I'm currently using the previous version from my last iOS build issue I submitted 
[lz4 deprecated stuff]

![image](https://user-images.githubusercontent.com/68160962/158708539-865da87d-dfbb-4f25-b59e-00add7d5b209.jpeg)

**Comment by luboslenco** [comment]
Appears to be ok now in the latest revision.
