### ISSUE TITLE
Replicating node tree from Blender in ArmorPaint

### ISSUE THREAD

**Issue by Fei1919** [armory3d/armorpaint#1338]
All materials that I try replicating from Blender in ArmorPaint using nodes never work. This one example of a metal material node tree that I tried replicating in ArmorPaint. So is it impossible to do this, or am I doing something wrong?
![Screenshot 2022-03-17 230654](https://user-images.githubusercontent.com/100168620/158902906-f7d3cb36-5491-4e01-b016-545dd8c17a56.png)
![Screenshot 2022-03-17 230821](https://user-images.githubusercontent.com/100168620/158902907-bc737c70-16f8-48d6-91cd-246cd763543e.png)
![Screenshot 2022-03-17 230922](https://user-images.githubusercontent.com/100168620/158902910-f8f97172-2355-4a6f-9410-b454cd58cd48.png)
![Screenshot 2022-03-17 230953](https://user-images.githubusercontent.com/100168620/158902925-c664b0cf-22dc-4030-a367-735e6e29cf86.png)

**Comment by luboslenco** [comment]
Will fix at https://github.com/armory3d/armorpaint/issues/36, sorry its taking so long.
