### ISSUE TITLE
why DX11 workflow different from DX12(DXR)

### ISSUE THREAD

**Issue by ronh991** [armory3d/armorpaint#1339]
DX 11 workflow - apply patch then make

DX12(DXR) workflow - apply make then patch 

does it make a difference?

[a1e9ef4](https://github.com/armory3d/armorpaint/commit/a1e9ef4e6e073228538ece02a510ccd8c0cef309)

**Comment by luboslenco** [comment]
Not in that case but fixed now, thanks for notice!
