### ISSUE TITLE
Wacom Pressure Windows 7

### ISSUE THREAD

**Issue by arcfxnate** [armory3d/armorpaint#1342]
**ArmorPaint version:**
Version .9

**OS/device including version:**
Windows 7 with latest wacom driver from website. 

**Issue description:**
I just purchased A.P. and it ran with no problems except the wacom pen pressure is not working.  I checked my settings and used my wacom in many other softwares like photoshop, but the one thing that might be causing the problem is that this computer is still running windows 7.  If this is the issue, is there any way of fixing the problem?  Thank you in advance for assisting me.

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Hi, thanks for your support! As far as I know Microsoft did not make the "modern" windows ink api which ArmorPaint uses available on Windows 7. Please drop me an [email](https://armorpaint.org/community.html) for a refund if you are only able to run on Windows 7. Sorry for the trouble.

**Comment by arcfxnate** [comment]
> 

No worries, no refund is required.  Happy to support you and hope to use in the future.  I'm stuck on Win7 till I finish this film I'm on.  Peace and best wishes!
