### ISSUE TITLE
Decal not displaying Properley

### ISSUE THREAD

**Issue by arcfxnate** [armory3d/armorpaint#1343]
**ArmorPaint version:**

Version .9

**OS/device including version:**

Windows 7

**Issue description:**

The decal texture displays smaller than the brush size, but when paints it paints at the correct brush size.  I've tried other photos and not luck.
![armor-paint](https://user-images.githubusercontent.com/102152074/159474733-6478d51a-ee6f-4221-9871-fef505f61b14.png)

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Thanks for report. Tested with non-square photos and it appears to be ok in the latest dev builds - if the issue still persists please let me know the steps to reproduce.
