### ISSUE TITLE
[Android] Can't import anything other than sample files

### ISSUE THREAD

**Issue by morkalmarrh** [armory3d/armorpaint#1344]
**ArmorPaint version:**
v0.9 (2022-02-13) 60faac2

**OS/device including version:**
OpenGL on Android Samsung Tab S6 Lite

**Issue description:**
Filetype error. I tried importing by exporting from Blender 3.0:
.obj
.fbx
.dae

I don't even use that one it was a shot in the dark. I tried an actual model I use and then a basic cube. None of it worked.

Doesn't work from Gdrive. Downloading it ro my internal storage, then navigating to my downloads in the file browser inside the app also doesn't work.

I can open files from the Cloud OK. 

I can open image files from the same folder on my internal storage OK also, those show up in the browser without issue.

I don't want to go through the refund process y'know, I want this app to work. Minor bugs are OK but it's... I can't use it at all it's broken.

Note: It says /sdcard/(filepath). I'm using the internal storage. Strangely it does find my files but it's saying it's looking in the sdcard slot.

Also, there's no file management from the projects folder. Please add a way to delete them without emptying the app's data out entirely every time...?

EDIT: Dragging and dropping seems to work, bizarrely, but that requires a rather convoluted setup. 

**Steps to reproduce:**
Try to open literally any file.

**Comment by luboslenco** [comment]
Thanks for report, it should now work properly via the file browser as well in the newly released Android update. Please let me know if you get to test it and sorry it took a while. Working on more updates to make the experience better.
