### ISSUE TITLE
Interface not responsive on Mac version

### ISSUE THREAD

**Issue by bheiland** [armory3d/armorpaint#135]
Single and double clicks to interface unresponsive. Can’t find anything that properly responds to mouse clicks on UI . If I slightly drag while clicking the item might highlight .

**Comment by luboslenco** [comment]
Hi, which macOS version / gpu are you on? Standard build or git version?
I am testing on macOS 10.14.4 (macbook pro 2014) but sadly it appears ok here. 😕

**Comment by bheiland** [comment]
MAC OS Mojave 10.14.5 GPU Nvidia GeForce GT 650M 1 GB  (2012 Macbook Pro)
I was able to make a change that makes blender interface responsive.
In the user preferences I changed  Input/Mouse/Drag Threshold from 0 to 3 and interface now responds properly.
Now that I have the interface responding, I get a crash when Krom tries to run.  I think I am on the standard Build.  

Should I try the GIT version?

**Comment by bheiland** [comment]
I am going to need some instructions on setting up the GIT version .  
I am not exactly sure where to place the files and how to install from the preferences screen.

**Comment by luboslenco** [comment]
Thanks for the info! No need for git build, was just to let me know what should I test with. Any luck using the newly updated macOS ArmorPaint build?

> In the user preferences I changed Input/Mouse/Drag Threshold from 0 to 3 and interface now responds properly.

Hm I think I am not on the same page here - was Blender interface not responsive in the same way as ArmorPaint?

**Comment by bheiland** [comment]
I accidentally reported under armory paint.  This should've  been under Armory 2.80 mac.  My blender interface was not responsive until I made the change.  I can't seem to get Armory to run under blender in a way that allows anything to work properly.  I'll try to make sure I am responding in the correct area.

**Comment by luboslenco** [comment]
Linking with https://github.com/armory3d/armory/issues/1295.
