### ISSUE TITLE
The brush does not change with the pressure of the pen

### ISSUE THREAD

**Issue by Wario-Ametrano** [armory3d/armorpaint#1359]
In the latest version of Armor Paint (0.9dev (6d1660a)) if I use the pen, the radius of the brush and the hardness of the brush no longer change if I press the pen. In previous versions I never had this bug with the same pen

**Comment by luboslenco** [comment]
Hi, thanks for report. Which OS are you on?

**Comment by Wario-Ametrano** [comment]
I use Windows 11, but with blender and other software I have not had this problem, I don't know if it depends on the os

**Comment by Disar** [comment]
Make sure windows ink is enabled. If you're using a Wacom Tablet make sure you enable it under mapping in the wacom settings.

**Comment by luboslenco** [comment]
Please let me know if the issue persists even with windows ink enabled. Some more info [here](https://github.com/armory3d/armorpaint_docs#pen).
