### ISSUE TITLE
Interface blurs up when "3d Cursor" is enabled (linux)

### ISSUE THREAD

**Issue by SojanJanso** [armory3d/armorpaint#136]
Build ff1aea1

When the 3d Cursor is enabled, the interface blurs up. The 3d view does not seem to be affected. While the mouse is moved in an interface section, that section is not bury, but as soon as motion stops, it blurs up again.

![Peek 2019-06-12 14-48](https://user-images.githubusercontent.com/26679320/59378310-098ab300-8d22-11e9-88c9-593eaba628dc.gif)

Ubuntu 18.04.2 LTS (Gnome)
GTX 780 (driver 415)
AMD FX-8320e

**Comment by luboslenco** [comment]
Should be fixed now at https://github.com/armory3d/armorpaint/commit/69ada843fb1a3062d9e56c1655f13c015cb0a13d. For some reason all is ok on my machine, so thanks for letting me know.

(Skips a small ui draw optimization on opengl, will revisit that once transition to vulkan is done.)

**Comment by SojanJanso** [comment]
Yep, it seems to work fine now.

And wooh! Moving to vulkan... that is quite a move !! :open_mouth:

**Comment by SojanJanso** [comment]
Also, for your future reference, between this build and the last, the freez up and lag caused when I would change to a texture size over 2k is also gone...

**Comment by luboslenco** [comment]
Awesome! If any task takes suspiciously long, issue report for that is welcome as well.
