### ISSUE TITLE
more materials

### ISSUE THREAD

**Issue by SlincHD** [armory3d/armorpaint#1361]
i would like to see more materials from ambientcg.com and polyhaven.com it would make my live so much easier, and also some decals. Ambientcg.com dose have some decals wich would be cool to see in the could as well

have a nice day.

**Comment by luboslenco** [comment]
Thanks for the request, more materials now available in the cloud.

It takes a bit to fetch the icons when opening the folder with many materials for the first time on Windows and Linux, will make it asynchronous in upcoming updates.
