### ISSUE TITLE
Dude about the cloud library

### ISSUE THREAD

**Issue by jdevlearning** [armory3d/armorpaint#1362]
You when know say something just go to the browser tab and click to cloud but doesnt exist also what is the path for setup the cloud library, because is empty
![bug](https://user-images.githubusercontent.com/9778566/161674045-f951f239-5a5d-42c9-a652-ce9b8808861e.png)

Dude Im gonna be your lappy dog to help you 
on this project

**Comment by jdevlearning** [comment]
ITs say armorpaint 0.8 compiled version

**Comment by SlincHD** [comment]
it is probably an older version of armirpaint 0.8 you could try to compile the latest 0,8 relise

**Comment by luboslenco** [comment]
Hello, that indeed looks like some ancient ArmorPaint, even older than final 0.8 release. Please update to one of the prebuilt versions or compile the latest one from GitHub.

**Comment by jdevlearning** [comment]
**DUDE IM GONNA BETA TESTER BECAUSE I BELIEVE ON THIS PROJECT JUST SEN COMPILED VERSIONS AND ALSO GIVE YOU IMPROVEMENTS REALLY.**
![bugcloud](https://user-images.githubusercontent.com/9778566/165190889-340ea36a-c5bf-4848-a129-2ef75b66728d.gif)

**Comment by rpaladin** [comment]
Hi, this is a public platform. Please refrain from childish behavior.
Lubos spent a lot of time on his software, ArmorPaint. The least you can do is behave civilly, if not also accept that fees help sustain hard workers.

If you'd like a free, compiled binary, perhaps ask nicely next time and someone might surprise you with such a free gift.
