### ISSUE TITLE
Wont compile

### ISSUE THREAD

**Issue by RecoilUK** [armory3d/armorpaint#1363]
Hi

Trying to compile armorpaint, and kee getting the following error 

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'v8\libraries\win32\release\v8_monolith.lib'	ArmorPaint	C:\armor\armorpaint\build\LINK	1	

This is despite me following the instructions and unpacking the library.

Any help would be appreciated, using Windows Visual Studion Community 2022.

**Comment by luboslenco** [comment]
Hi! Not sure why that would happen if you followed instructions, sorry. All seems to be in order here.

Make sure to run `armorcore\Kinc\make --from armorcore -g direct3d11` after the v8 library has been unpacked, but it's already like that in the instructions so probably not helpful.
