### ISSUE TITLE
"No such file/process" when typing "armorcore\Kinc\make --from armorcore -g direct3d11"

### ISSUE THREAD

**Issue by HoraceDTorace** [armory3d/armorpaint#1366]
I've been trying to compile ArmorPaint for the past day. Successfully cloned from Git but no progress after that. I've unpacked v8_monolith prior to running the command listed above.
![image](https://user-images.githubusercontent.com/103247427/162550386-1e8b1ef0-36ae-4733-b91f-0f01d2366629.png)
When I try typing "armorcore\Kinc\make --from armorcore -g direct3d11" I get the following error every time.
![image](https://user-images.githubusercontent.com/103247427/162550265-3758df62-9ddd-4904-88a0-2430193ff6ea.png)
Strangely, armorcore appears to vary in size by one gigabyte depending on the drive it's in, despite having almost exactly the same number of files, and the same number of steps taken. That one extra file is from my second attempt at extracting v8_monolith in a slightly different directory.
Examples:
![image](https://user-images.githubusercontent.com/103247427/162550512-c6d39a07-3d3b-425e-a868-71f78c98b022.png)
![image](https://user-images.githubusercontent.com/103247427/162550527-b49b1ab8-60c7-478d-b268-e64fd97f10a5.png)
My operating system is "Windows 10 Home 64-bit".
I have node.js, Git, and Visual Studio 2022 already downloaded.

**Comment by MrAdrianPl** [comment]
take a look on that issue its the same as yours and it gives simple solution for compiling [here](https://github.com/armory3d/armorpaint/issues/1326)

**Comment by luboslenco** [comment]
Will report a fix at https://github.com/armory3d/armorpaint/issues/1326.
