### ISSUE TITLE
Linux: layer save issue

### ISSUE THREAD

**Issue by TheImaginaryOne** [armory3d/armorpaint#137]
64bit Arch Linux, armorpaint https://github.com/armory3d/armorpaint/commit/95a150990b7ff507b5432f3868bf60d49559f7d4

Steps to reproduce:
* New project with default cube
* Add 3 new blank layers (no need to paint on them)
* Import sample_colorid.png texture from https://github.com/armory3d/armorpaint_samples into Textures
* Save the project
* Close Armorpaint
* Reopen Armorpaint
* Open the same project. Layer 4 suddenly turns a solid blue (EDIT: in my most recent tests it turned orange)

**Comment by SojanJanso** [comment]
I can't seem to reproduce this on Ubuntu Linux (64bit) and ArmorPaint bfed2ba

**Comment by TheImaginaryOne** [comment]
After re-opening the file, if I click on Layer 4 and click "2D View", this error appears, although the 2D image successfully opens anyway:
```GL Error 1282 ../../Kore/Backends/Graphics4/OpenGL/Sources/Kore/RenderTargetImpl.cpp 166```

I also have screenshots: 
Before I save the file
![screen1](https://user-images.githubusercontent.com/15994818/59832630-75ab8d80-9398-11e9-9869-a67d5cc65eb7.png)
After I open Armorpaint again and open the same file
![screenshot2](https://user-images.githubusercontent.com/15994818/59832637-78a67e00-9398-11e9-97ec-f735ce6a02db.png)

Also note in the second screenshot Layer 4 has changed colour but the cube itself has not.

Not sure if related, but since Krom didn't compile successfully with clang 8 on my computer, I built my own version of clang 7.

**Comment by luboslenco** [comment]
Possibly resolved now but still needs more testing. 🔨
