### ISSUE TITLE
Integration With Blender 

### ISSUE THREAD

**Issue by BlenderTest** [armory3d/armorpaint#1372]
Could there be a way for Amour paint to replace blender Texture paint and integrate fully in Blender via a addon. Currently Blender Texture painting is slow and out of date and I doubt it will be fixed anytime soon, but Amour paint is fast stable enough and it Use blenders nodes but lacks some key brush features so would it be best to fuse them together and make a better  Blender Texture paint system using Amour.

**Comment by luboslenco** [comment]
Moving ArmorPaint code as-is into Blender is not possible, sorry. :( Basically ArmorPaint mimicks Blender nodes but it's coded from scratch. Hence why some nodes still behave oddly / wrong.
