### ISSUE TITLE
Failed to read compressed .blend

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorpaint#138]
[bug.zip](https://github.com/armory3d/armorpaint/files/3294474/bug.zip)
Import this file -> ArmorPaint shows `Error: Failed to read mesh data`.

Windows 8.1 64bit
Geforce GTX 750 Ti
Direct3D11
Armorpaint 0.6 bfed2ba

**Comment by luboslenco** [comment]
Fixed, importer will now read compressed `.blend`s as well. https://github.com/armory3d/iron_format/commit/7f322fcd419ab7fd9574d332b28ef229403503a4
