### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by WilledgeR** [armory3d/armorpaint#1388]
Is there a free way to download the built version?

![Capture](https://user-images.githubusercontent.com/8308025/165169054-4e477fdf-a480-435c-9fe2-88863b81f025.PNG)

**Comment by rpaladin** [comment]
Hi yes. ArmorPaint is free if you compile the public source from this repository.

I give a detailed summary here: https://forums.armory3d.org/t/how-to-update-armorpaint/4415/8

**Comment by luboslenco** [comment]
👍 👍
