### ISSUE TITLE
 hardness not working with clone tool

### ISSUE THREAD

**Issue by Pemo33** [armory3d/armorpaint#1389]
Hello,

there is a way to have the hardness working with clone tool?  
Thanks.

Pascal Mora

**Comment by Pemo33** [comment]
or even on black mask, both are not working for me. Thanks

**Comment by Pemo33** [comment]
![image](https://user-images.githubusercontent.com/10427044/166097265-3493f949-dd23-4486-8519-02334a1b364f.png)

**Comment by luboslenco** [comment]
Added at https://github.com/armory3d/armorpaint/commit/6c7c3e207548c16af375a4d1fb08f66f5477840c, thanks for report.
