### ISSUE TITLE
Crash when checking for updates

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorpaint#139]
`Help` > `Check for updates` crashes ArmoryPaint.

Error inside cmd.exe (German):
```
Invoke-WebRequest : Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden..
In Zeile:1 Zeichen:1
+ Invoke-WebRequest -Uri 'http:luboslenco.gitlab.io/armorpaint/index ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Powershell.Commands.InvokeWebRequestCommand
```

Which roughly translates into:
`The request was cancelled. It was not possible to create a secure SSL/TLS channel.`

Windows 8.1 64bit
Geforce GTX 750 Ti
Direct3D11
Armorpaint 0.6 bfed2ba

**Comment by luboslenco** [comment]
The update check can still fail but should no longer crash now. Will add an actual updater eventually.
