### ISSUE TITLE
Too many issues preventing Armorpaint from launching in Mac OS 12.3.1

### ISSUE THREAD

**Issue by inseyven** [armory3d/armorpaint#1391]
**ArmorPaint version:**
0.9

**OS/device including version:**
Mac OS 12.3.1 Intel CPU + RX 5500 XT

**Issue description:**

![Captura de Pantalla 2022-05-03 a las 1 58 02](https://user-images.githubusercontent.com/25097644/166344479-fef80552-7f82-4bf6-8b32-6ef04a3eca5d.png)

**Steps to reproduce:**
Build and Run with Xcode

**Comment by luboslenco** [comment]
Hi, these should be "only" warnings, which should still let you run the app. If you also get an actual build error please let me know.

**Comment by inseyven** [comment]
Cool and all. But those warnings make Armorpaint never launch in Mac OS.
