### ISSUE TITLE
Textures can not be imported

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#1394]
ArmorPaint.org - v0.9 (2022-05-03) - ca853e4
Windows - Direct3D11
Intel(R) HD Graphics 620

Textures can not be imported either alone or with the corresponding materials. Drag and drop doesn't work also.

![no-textures](https://user-images.githubusercontent.com/72331575/166560800-ef61f7e1-869b-4722-a4cb-7c3c33ae0cf4.jpg)

**Comment by MathemanFlo** [comment]
I can reproduce it. @luboslenco it is because of https://github.com/armory3d/iron/commit/aa24581a218ebb1ff81c6c6e6794c31620b22dfc
If the user tries to load a texture ImportTexture.hx calls Data.getImage and the extension is replaced by ".k".

**Comment by luboslenco** [comment]
Thanks so much for quick report! Reverted at https://github.com/armory3d/iron/commit/a7f6da0c3f9786717ecc0b283f25fea571b205b9.
