### ISSUE TITLE
Compiling error on Fedora

### ISSUE THREAD

**Issue by asdf123445** [armory3d/armorpaint#1398]
I'm trying to compile armor paint on linux and i've encountered an error
![image](https://user-images.githubusercontent.com/105203759/167376960-ed80188d-bb40-4353-985a-8a9063d75e1b.png)

sry for polish commandline

**Comment by luboslenco** [comment]
Hi, can you paste the full log? There should be some more details above the `1 error generated.` line.

**Comment by asdf123445** [comment]
Fedora

**Comment by spalius** [comment]
You need the package `wayland-protocols-devel`

`dnf install wayland-protocols-devel`

**Comment by luboslenco** [comment]
Added a mention at https://github.com/armory3d/armorpaint/wiki/Linux-Dependencies, thanks!
