### ISSUE TITLE
Export to unity

### ISSUE THREAD

**Issue by PasinduAnjana** [armory3d/armorpaint#140]
How to export using armorpaint to unity?
Unity uses a metallic smoothness map.

**Comment by SojanJanso** [comment]
I believe that unity will automatically switch to metallness workflow if you put a texture in the metallic slot of the standard material. For more info I suggest you read https://docs.unity3d.com/Manual/StandardShaderMaterialParameterMetallic.html

**Comment by PasinduAnjana** [comment]
Unity use one map for metallic and roughness. Metallic is in red channel and roughness/smoothness is in alpha channel. We have to combine those two textures to a one texture.

Thanks for your help.

**Comment by PasinduAnjana** [comment]
![Cheat-Sheet](https://user-images.githubusercontent.com/47142024/59652954-ab405300-91ad-11e9-849e-e4d58f533cc0.png)

**Comment by luboslenco** [comment]
@PasinduAnjana I have added a new export template in latest builds - setting `Export Textures - Output` to `Unity 5` should generate the metallic-occlusion-smoothness map.
