### ISSUE TITLE
0.9 version "Neither wayland nor X11 found."

### ISSUE THREAD

**Issue by igorr0driguez** [armory3d/armorpaint#1400]
**ArmorPaint version:** 0.9

**OS/device including version:**

OS: Pop!_OS 22.04 LTS
Proc: Intel i5-9300H
GPU: GeForce GTX 1650

**Issue description:**

When trying to launch ArmorPaint 0.9 from terminal, it doesn't open and shows this message.

**Steps to reproduce:**

Download ArmorPaint 0.9 and try to run using `./ArmorPaint`.

To add, 0.8 worked, the issue only occurs with 0.9.

**Comment by luboslenco** [comment]
Update at https://github.com/armory3d/armory/issues/2487#issuecomment-1130181477.

**Comment by igorr0driguez** [comment]
The workaround works. Thanks!

**Comment by igorr0driguez** [comment]
VKRT version doesn't, though.

Error message is: "Segmentation fault (core dumped)"

**Comment by luboslenco** [comment]
Applied https://github.com/Kode/Kinc/pull/710.

For the VKRT the patch needs updating if I recall correctly - the `git apply armorcore/patch/vulkan_raytrace.diff --directory=armorcore/Kinc` step should throw an error.
