### ISSUE TITLE
Text and icons too small

### ISSUE THREAD

**Issue by martycz185** [armory3d/armorpaint#1401]
*ArmorPaint 0.9-2e3c5ed, Windows*

I have difficulty reading the text and the icons.   Would it be possible to adjust the text and Icon size?
Thanks

**Comment by luboslenco** [comment]
Hi, to adjust the size increase the `Menu` - `Edit` - `Preferences...` - `Interface` - `UI Scale` slider.

https://www.youtube.com/watch?v=PjTP7DCMXUo&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=18
