### ISSUE TITLE
Resolution dosn't scale up

### ISSUE THREAD

**Issue by SlincHD** [armory3d/armorpaint#1402]
Armorpaint 0.9 Githup 18.5.2022

Windows

![image](https://user-images.githubusercontent.com/85231739/169107919-dac77e30-1c4c-41d9-9dec-99cefd0999fa.png)
i scaled the texture resolution down to 128 and than back up to 4k and the texture stayes in the 128 resolution state

**Comment by luboslenco** [comment]
Fill layers will get updated after https://github.com/armory3d/armorpaint/commit/9a7b2a27620a2793edb308edf07ff9bdef8bafdf, thanks for issue report.
