### ISSUE TITLE
armorcore\Kinc\make --from armorcore -g direct3d11 WIN10 Not Working

### ISSUE THREAD

**Issue by cheekystrace** [armory3d/armorpaint#1406]
Hello,

I am trying to compile Armorpaint for Windows 10 but I am encountering some errors. I would greatly appreciate any guidance with regard to the errors I am encountering. To begin, I will explain what steps I performed.  I think that I am getting the Step 3 wrong and that is throwing everything off.

1. I started by recursively cloning the repository using Windows Git
git clone --recursive https://github.com/armory3d/armorpaint

2. I installed Microsoft Visual Studio 2022 and also Visual Studio build tools for windows.

3. As instructed on the main page, I attempted this:
**armorcore\Kinc\make --from armorcore -g direct3d11**

I received the following error:

**C:\Users\tom\armorpaint\armorcore\Kinc>make --from armorcore -g direct3d11
Using Kinc (16e9a6a4) from C:\Users\tom\armorpaint\armorcore\Kinc
kfile not found.
Error**

Is there anyone that can provide more detailed instructions or pointers on how to build this for windows 10 because I cannot get past the step above

**Comment by luboslenco** [comment]
Hi,

Thanks for checking out ArmorPaint. Please open the terminal at `C:\Users\tom\armorpaint` instead of `C:\Users\tom\armorpaint\armorcore\Kinc` and then run `armorcore\Kinc\make --from armorcore -g direct3d11`.

**Comment by cheekystrace** [comment]
Thank you. Can you assist me in fixing the following error? 

The BaseOutputPath/OutputPath property is not set for project 'ArmorPaint.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='x64'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	

ArmorPaint	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	824
