### ISSUE TITLE
Hexe compiler error

### ISSUE THREAD

**Issue by KingDoogan** [armory3d/armorpaint#1409]
After running: armorcore\Kinc\make --from armorcore -g direct3d11

I get an error.

C:\armorpaint\Sources/Main.hx:24: characters 26-43 : Uncaught exception process_run
C:\armorpaint\armorcore\Tools\haxe\std/eval/_std/sys/io/Process.hx:1: character 1 : Called from here
C:\armorpaint\Libraries\armorbase\Sources/arm/sys/BuildMacros.hx:18: characters 14-83 : Called from here
C:\armorpaint\Sources/Main.hx:24: characters 26-43 : Called from here

Haxe compiler error.
Error: kfile did not call resolve, no project created.

I have the latest versions of Haxe, Node.js, Git.

**Comment by jessechunn** [comment]
I have this issue. How was it resolved?

**Comment by KingDoogan** [comment]
> 
I found a pre-compiled version

https://github.com/lmoreloss/armorpaintCompiled
