### ISSUE TITLE
Copy paste not working on Linux

### ISSUE THREAD

**Issue by SojanJanso** [armory3d/armorpaint#141]
Material nodes can not be copied/pasted or duplicated. This is an issue when creating procedural materials, since combinations of nodes such as noise+rgb+mix+ramp have to be constantly rebuilt from scratch, rather than copying an existing one.

**Comment by luboslenco** [comment]
Yo, which build do you run? Latest development + Linux? On Windows `Ctrl + C` / `Ctrl + V` seems to work like usual, will boot to Linux in a bit.

**Comment by SojanJanso** [comment]
I am in linux (Ubuntu 18), latest itch build, 8304763.

**Comment by SojanJanso** [comment]
I tried this on Windows (still build bfed2ba), and ctrl+v/ctrl+v didn't work on nodes there either.

**Comment by luboslenco** [comment]
Which Windows version? Did it work for you in previous builds? It still seems to work here (Windows 10 1903), but maybe I will get lucky once I test on other machines.

**Comment by luboslenco** [comment]
Also, does copying text from text fields work or is it also broken? Thanks for info!

**Comment by SojanJanso** [comment]
I am on Windows build 18362. I didn't know you could copy/past in text fields, but when I tried (I used the string field in the text tool), it wouldn't work either.

**Comment by SojanJanso** [comment]
I re-downloaded itch build and I might have confused build numbers. It works in Windows on bfed2ba itch build, but not more recent builds.

**Comment by luboslenco** [comment]
Fixed the Windows madness, Linux to go.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/Kode/Kinc/pull/448.
