### ISSUE TITLE
glTF files don’t load on iPadOS, results in black screen

### ISSUE THREAD

**Issue by hybridherbst** [armory3d/armorpaint#1415]
**ArmorPaint version:**

iPadOS, v0.9 official 

**OS/device including version:**

iPadOS, 15.6

**Issue description:**

Neither .gltf nor .glb files import at all.
There’s an import dialogue, but after pressing “Import” the screen simply goes black.
This is a huge workflow issue: the entire reason for ArmorPaint on iPadOS for me would be importing models from Nomad and continuing to work on them.
Obj files do import but are missing many features that could be preserved from glTF.

**Steps to reproduce:**

Attached a glb file that doesn’t load: 
[Dateien.zip](https://github.com/armory3d/armorpaint/files/8885476/Dateien.zip)

Related
- #1360

**Comment by luboslenco** [comment]
Should be fixed in the latest iPad update, thanks for report. Looks like there is no uv-map so the built in uv_unwrap plugin can be used - it takes a long time (5-10 minutes) to unwrap though, will try to investigate and speed it up. Please let me know about any further issues.
