### ISSUE TITLE
Can't export anything on Android

### ISSUE THREAD

**Issue by DAVISAO** [armory3d/armorpaint#1416]
**ArmorPaint version:**

I use oficial build 0.9
 I use Android os
**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

In export label, don't show the directory
![Screenshot_2022-06-16-16-36-05-027_org armorpaint](https://user-images.githubusercontent.com/38228354/174155736-852dcdf8-1b09-46da-9969-a3e6a480b144.jpg)

**Comment by DAVISAO** [comment]
![Screenshot_2022-06-22-12-12-41-344_org armorpaint](https://user-images.githubusercontent.com/38228354/175066596-c1d9b5f9-3b64-484c-9c7c-2f59e247699d.jpg)
I can't export nothing as I can't access the directories. I use a Android 10

**Comment by luboslenco** [comment]
Should be resolved in the newly released Android update. It will now export the textures into the pictures folder. Please let me know if you get to test it, thanks for report.
