### ISSUE TITLE
Not Exporting

### ISSUE THREAD

**Issue by GitHub252525** [armory3d/armorpaint#1422]
*ArmorPaint 0.9-60faac2, Android*

**Issue description:**
Can't export anything
My device
 vivo1935 
8gb ram
128Gb storage - 100gb available
**Steps to reproduce:**
You just can't export things like texture,meshes,etc in

**Comment by luboslenco** [comment]
Argh, file access has become very restricted in recent Android versions. Fix incoming at https://github.com/armory3d/armorpaint/issues/1416, thanks for report.
