### ISSUE TITLE
C1083 errors

### ISSUE THREAD

**Issue by JaidynCG** [armory3d/armorpaint#1423]
As far as I can tell, I've done everything correctly up to this point, but I'm getting these errors when I'm trying to build. **I should also mention that I believe I'm supposed to have a build folder inside the armorcore folder, but the only one I have is in the armorpaint folder.**

<img width="960" alt="image" src="https://user-images.githubusercontent.com/66656514/177836239-0ddb9d17-2b92-4f8c-afb4-4cfc8239b87f.png">

**Comment by luboslenco** [comment]
That's weird, what Visual Studio version are you on?

**Comment by JaidynCG** [comment]
I'm on the latest 2022 version. v143

**Comment by luboslenco** [comment]
Sorry I am not sure what if wrong. For some reason your Visual Studio is unable to locate those header files. Please make sure `Desktop development with C++` is checked and installed in Visual Studio Installer and try a fresh ArmorPaint clone.

> I should also mention that I believe I'm supposed to have a build folder inside the armorcore folder, but the only one I have is in the armorpaint folder.

Yes, that is correct in the current version - build folder in armorpaint folder.
