### ISSUE TITLE
Cant Export textures

### ISSUE THREAD

**Issue by lilCoffeeBrain** [armory3d/armorpaint#1425]
*ArmorPaint 0.9-16cf14e, Windows*

**Issue description:**
cannot export any kind of textures

**Steps to reproduce:**

file< export textures < pick the folder < name the png < nothing shows up on the folder

**Comment by luboslenco** [comment]
Hm, seems to work ok here. Which Windows version are you on? What is the export folder path? Could any anti-virus software prevent ArmorPaint from writing the files? Thanks for report.

**Comment by lilCoffeeBrain** [comment]
Currently running win10 - 21h2. I had tried many export paths, including straight to desktop. 

After reading your reply I tested again after disabling the anti-virus, and it seems to do the trick... thank you!  
Is this a known issue? I just got the program recently.

**Comment by luboslenco** [comment]
Happy to hear - thanks for letting me know! No known issue, but I had no other clue what could cause it. Which anti-virus software are you using?

**Comment by lilCoffeeBrain** [comment]
This pc currently is using Avast.
