### ISSUE TITLE
Segmentation Fault at launch

### ISSUE THREAD

**Issue by JohnRudy** [armory3d/armorpaint#1426]
**ArmorPaint version:**
[53b6304](https://github.com/armory3d/armorpaint/commit/53b6304020017699d3c56b0ea2846095c8d88e21)

**OS/device including version:**
Pop!_OS 22.04 LTS x86_64

**Issue description:**
Unable to launch Armorpaint. 
Followed instructions, installed dependencies.
cd `~/armorpaint/armorcore/Deployment`
Tried to launch with `./ArmorPaint ../../build/krom`
Expecting to launch.
Crashes instead with only this in the terminal.   
```
Using OpenGL version 4.6 (forward-compatible).
Uniform N not found.
Segmentation fault
```

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorcore/commit/72a1aa308b3abef61b2e4cb02eac59c8a6a1c8c3, thanks for report!
