### ISSUE TITLE
Invisible Mesh in Viewport

### ISSUE THREAD

**Issue by ppk-gh** [armory3d/armorpaint#1427]
**ArmorPaint version:**
[53b6304](https://github.com/armory3d/armorpaint/commit/53b6304020017699d3c56b0ea2846095c8d88e21)

**OS:**
Linux 5.18.10-arch1-1 
GPU0: AMD Radeon RX5600m
GPU1: AMD Radeon Vega 7
Mesa 22.1.3-1

**Issue description:**
Cube is visible on start-up but upon any interaction with the window, it becomes invisible, same with any imported mesh. Env map in bacground still renders however.

[Terminal Output](https://pastebin.com/QLuu3v5C)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorcore/commit/72a1aa308b3abef61b2e4cb02eac59c8a6a1c8c3, thanks for report!
