### ISSUE TITLE
Armor Paint does not start from my linux terminal

### ISSUE THREAD

**Issue by Frost199** [armory3d/armorpaint#143]
could not load krom.js. aborting.
===========================

Steps from the Readme:

```bash
# Linux
1 node Kha/make krom -g opengl --shaderversion 330
2 cd Krom
3 node Kore/make -g opengl --compiler clang --compile
4 cd Deployment
5 strip Krom
6 ./Krom ../../build/krom
```
line 6 is where i am stucked

**Comment by SojanJanso** [comment]
What linux version are you running? I just built it on Ubuntu 18.04, and it worked (First time I ever build a project from someone else online successfully! :joy: )

Do you have all dependencies? Node.js, all the deps packages, (maybe Java?) etc?

```
~/armorpaint/Krom/Deployment$ ./Krom ../../build/krom
Uniform N not found.
Uniform texUnpack not found.
Uniform step not found.
GL Error 1282 ../../Kore/Backends/Graphics4/OpenGL/Sources/Kore/RenderTargetImpl.cpp 166

Uniform brushScale not found.
Uniform W not found.
Uniform eye not found.
Uniform aspectRatio not found.
Uniform brushScale not found.
```

**Comment by Frost199** [comment]
I am running a debian distro

i have all the deps except fro libgl-dev,
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libgl1-mesa-dev' instead of 'libgl-dev'
libgl1-mesa-dev is already the newest version (18.3.6-2).
0 upgraded, 0 newly installed, 0 to remove and 1096 not upgraded.
```

**Comment by Frost199** [comment]
when i compile, i dont get errors but i get alot of warnings while compiling but no errors. and i have the Krom executable in the Deployments folder but anytime i run ```./Krom ../../build/krom```,  i get 
 the ```could not load krom.js. aborting.``` from my terminal

**Comment by Frost199** [comment]
I now works, i didn't put armor painter in my home folder it was in a sub-folder Running:
```./Krom ../../build/krom``` now works

**Comment by SojanJanso** [comment]
yeah, I was about to comment, I get the same error when I run `./armorpaint/Krom/Deployment/Krom ../../build/krom` instead of taking the time to cd in `./armorpaint/Krom/Deployment` and then running `Krom ../../build/krom`. So there is definitely something it is doing behind the scenes, and assuming it is in a certain file path to begin with.

**Comment by Frost199** [comment]
i figured ```./Krom ../../build/krom``` was  too complicated for me to remember so i created a  bash script to do that for me, but its inside the Deployments folder so if i run ./armorpainter.sh it runs;
bash code:
```
#!/bin/bash
./Krom ../../build/krom
```

then save, and make chage the mode to executable with 
```
chmod +x armorpainter.sh
```

**Comment by SojanJanso** [comment]
Could this be the culprit? I found it in the readme. ```
## Running

[`krom [assetsdir shadersdir [--flags]]`

If no arguments are provided, assets and shaders are loaded from the executable path.](url)
```

**Comment by Frost199** [comment]
i believe that's another thing too with the ```Krom [assetsdir shaderdir [--flags]]```
i am yet to use armor paint fully, i just hope i don't get frustrated with it...lol

**Comment by SojanJanso** [comment]
I found that if you copy the Krom file in ```armorpaint/Krom/Deployment```, and past it beside the ```armorpaint/build/krom```, you can just run it from there, and armorpaint will work fine. You can also use the Krom for linux from https://github.com/armory3d/Krom_bin

**Comment by hrstwn** [comment]
I still get the error but I don't understand. Anyone can help?

```
heru@hrstwn:~/armorpaint/Kromx/Deployment$ ./Krom ../../build/krom
could not load krom.js. aborting.
```

**Comment by cpcbegin** [comment]
I also get the same error in this last step.
I try with Ubuntu Mate 20.04 & Debian 11.

**Comment by BrainBlasted** [comment]
Also have this error on the last step, running from the `armorpaint/armorcore/Deplyment` directory.
