### ISSUE TITLE
Blur does not work for mask

### ISSUE THREAD

**Issue by SlincHD** [armory3d/armorpaint#1433]
armorpaint 0.9
gumroad
win 10

idk what to say els the blur brush dosn't work at all

**Comment by Tyrannosaurus1234** [comment]
Blur works for me on materials, but not masks.

**Comment by luboslenco** [comment]
Pushed a fix for mask blur at https://github.com/armory3d/armorpaint/commit/27b1b58b01aa8b3f14c92a1ec8e51877034a5dac, thanks for report.

If blur still does not work please let me know steps to reproduce, will investigate.
