### ISSUE TITLE
Problem import ngons

### ISSUE THREAD

**Issue by maljos** [armory3d/armorpaint#1438]
OS: Linux Mint 20.04
Blender 3.1.2

The surfaces of the objects with polygons larger than 4 sides are imported discretionary, some are and some are not.

**Comment by corjohnson** [comment]
Hey @maljos I tried to replicate it with a modified default cube in blender, but I didn't get any unexpected results. Do you have screenshots of what you're seeing? Or a sample `.blend` or `.obj` file you can attach to this issue?

**Comment by luboslenco** [comment]
Maybe related to https://github.com/armory3d/armorpaint/issues/1272? Will continue there.
