### ISSUE TITLE
Exported .obj files

### ISSUE THREAD

**Issue by Frost199** [armory3d/armorpaint#144]
.obj exported from armor paint is successfully imported in Blender as i can see from my console, running blender from my terminal, but when imported, i can't see the mesh,  but the object property is in the scene graph  but can be seen in the editor

**Comment by Frost199** [comment]
even with the "bomberman" sample provided by armor paint, if i export this mesh from armor paint and open this mesh in blender, it has the same behavior but blender shows it as a successful import but it doesn't in the scene view just in the scene graph.

**Comment by luboslenco** [comment]
Thanks for opening the issue, can reproduce - fix incoming!

**Comment by Frost199** [comment]
I will be waiting, thanks for the awesome software

**Comment by luboslenco** [comment]
Fixed now in newly updated builds. 🔨
