### ISSUE TITLE
node Kinc/make -g direct3d11 Always returns this error

### ISSUE THREAD

**Issue by MR-QUACK94** [armory3d/armorpaint#1441]
When trying to build armorpaint, I always get this error when running `node Kinc/make -g direct3d11`

> C:\Users\customer\Documents\Armor\2\armorpaint>node armorcore/make -g direct3d11
> 
> C:\Users\customer\Documents\Armor\2\armorpaint>cd armorcore
> 
> C:\Users\customer\Documents\Armor\2\armorpaint\armorcore>node Kinc/make -g direct3d11
> C:\Users\customer\Documents\Armor\2\armorpaint\armorcore\Kinc\make:2
> if [[ "$OSTYPE" == "linux-gnu"* ]]; then
>    ^
> 
> SyntaxError: Unexpected token '['
> ←[90m    at Object.compileFunction (node:vm:360:18)←[39m
> ←[90m    at wrapSafe (node:internal/modules/cjs/loader:1055:15)←[39m
> ←[90m    at Module._compile (node:internal/modules/cjs/loader:1090:27)←[39m
> ←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)←[39m
> ←[90m    at Module.load (node:internal/modules/cjs/loader:1004:32)←[39m
> ←[90m    at Function.Module._load (node:internal/modules/cjs/loader:839:12)←[39m
> ←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
> ←[90m    at node:internal/main/run_main_module:17:47←[39m
> 
> C:\Users\customer\Documents\Armor\2\armorpaint\armorcore>

**Comment by lumsdnb** [comment]
I have the same issue, how did you fix it?
