### ISSUE TITLE
Edge wear creator

### ISSUE THREAD

**Issue by DrasChannel** [armory3d/armorpaint#145]
Edge wear creator to create rusty or dirty edges of object.

**Comment by Hopefullyidontgetbanned** [comment]
mirrors issue with Pointiness Channel in geometry node #501 since pointiness is usually used for edge wear for blender procedural creation

**Comment by luboslenco** [comment]
First edge wear creator is now available at `Browser tab - cloud - materials - procedural - EdgeWear001`. Will be added to the [how-to section](https://armorpaint.org/howto) soon.
