### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by zihadttttttttttt** [armory3d/armorpaint#1452]
**ArmorPaint version:**

**OS/device including version:**

**Issue description:**

This error is showing
'armorcore' is not recognized as an internal or external command,

**Steps to reproduce:**

![Capture](https://user-images.githubusercontent.com/86789765/192088818-53db836a-ad1a-48a7-8461-2ba061f607db.PNG)

**Comment by luboslenco** [comment]
Please make sure the `git clone` command succeeds completely, looks like it was interrupted for some reason (maybe dropped internet connectivity).
