### ISSUE TITLE
Latest MacOS build hangs at launch

### ISSUE THREAD

**Issue by rk-wbz** [armory3d/armorpaint#1453]
**ArmorPaint version:**
0.9 or f7226e5560fdc6f1c814819b08deb02add8c5cbc

**OS/device including version:**
MacOS Monterey 12.6. x64 i9. AMD Radeon Pro 5500M.

**Issue description:**
Building per the readme instructions (and either specifying a path to krom.js in the debug run scheme or launching the app from the finder to get around the "unable to load krom.js" issue) results in the app stuck trying to launch indefinitely. The icon will bounce in the dock, but will never load the app and will require a force quit.
It appears that the main thread gets stuck in kickstart/start_v8, specifically at V8::SetFlagsFromString(). If you bypass that, it will still get stuck at V8::Initialize().
Possibly need to update the V8 library?
The 0.8 build works fine; it's just 0.9 or custom builds that fail to run.

NOTE: this also happens with the prebuilt 0.9 build on gumroad, so it does not appear to be an issue with my build setup specifically.

**Steps to reproduce:**
Build latest per instructions for MacOS or run 0.9 release.

**Comment by thebuza** [comment]
I confirm the bug. I have exactly the same problem, macOS Mojave, Xcode 11.3.1. I took me some time to come to the same result as you have but the app behaves as you described - it's launching and force quit is necessary. 

By the way @rk-wbz how you bypassed the Signing process? I have the free account but when I hit build it builds but cannot run - it says:

Could not launch “ArmorPaint”
Domain: IDEDebugSessionErrorDomain
Code: 3
Failure Reason: internal error

**Comment by luboslenco** [comment]
Should be resolved now, thanks for report.

> specifying a path to krom.js in the debug run scheme

This is still required, will look into it.
