### ISSUE TITLE
Tablet mouse holds everything when doing simple click

### ISSUE THREAD

**Issue by BryantCrisos** [armory3d/armorpaint#1456]
*ArmorPaint 0.9-3cc0388, Windows*

**When ever I click on swatches only once using the tablet it holds instead of simple clicking. Same goes for when selecting materials.**

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/armory3d/armorpaint/issues/853, thanks for report.
