### ISSUE TITLE
strip: 'Krom': No such file

### ISSUE THREAD

**Issue by NicTanghe** [armory3d/armorpaint#1458]
Hello since i ran into the issue [#1449](https://github.com/armory3d/armorpaint/issues/1449) i wanted to compile for linux without vk which also did not compile.

I did clone recursively  so idk why it`s not working.
```
armorcore/Deployment (1e7c4d8)
❯ strip Krom
strip: 'Krom': No such file
```

**Comment by luboslenco** [comment]
Hi, if the issue still persists in the latest commit please post the full build log. Note the command is `strip ArmorPaint` when compiling ArmorPaint.

**Comment by NicTanghe** [comment]
i think clang might not have been installed.
