### ISSUE TITLE
Custom brush types

### ISSUE THREAD

**Issue by Appsepsi** [armory3d/armorpaint#146]
Custom brush types by importing mask map.

**Comment by luboslenco** [comment]
Added a preliminary support for brush masks by placing `Image Texture` in brush nodes and connecting it to the `Opacity` socket.

![brush_mask](https://user-images.githubusercontent.com/3685704/62683401-9f5b5b00-b9be-11e9-8cb7-c67686743693.png)

**Comment by SojanJanso** [comment]
It's important to note that this brush does not work with the default 3d cursor. It only works with the 3d cursor disabled.

**Comment by luboslenco** [comment]
@SojanJanso that sounds like a bug - will check on it in Linux builds!

**Comment by luboslenco** [comment]
Pushed a fix for Linux into 0.7 dev builds. Keeping open to add more options on how the brush mask is sampled.

**Comment by luboslenco** [comment]
Additional options are available via brush nodes. Specific feature requests welcome.
