### ISSUE TITLE
Ability to paint by UV islands

### ISSUE THREAD

**Issue by zsculpt** [armory3d/armorpaint#1464]
Looking to transition from Substance Painter (I bought Armor Paint because I really want to support this project!). The main workflow I use instead of breaking things up into meshes or multiple materials in Blender is just drag selecting the UV islands. Is this a feature you plan on adding?

![paintbyisland](https://user-images.githubusercontent.com/5686852/199844750-269e978e-441e-466d-99ab-9b43e1b2efe7.gif)

**Comment by luboslenco** [comment]
Will implement at https://github.com/armory3d/armorpaint/issues/1405, thanks for support!
