### ISSUE TITLE
Error: kfile did not call resolve, no project created.

### ISSUE THREAD

**Issue by jessechunn** [armory3d/armorpaint#1466]
On Win 10, 64 bit, when running:

armorcore\Kinc\make --from armorcore -g direct3d11
(from location C:\Users\jc\OneDrive\Local\VS Github\armorpaint>)

I get the following error:

**Haxe compiler error.
Error: kfile did not call resolve, no project created.**

Please advise, thank you in advance!

**Comment by luboslenco** [comment]
Hm, all seems well here. Maybe some anti-virus is preventing the build process from creating new files on disk?

**Comment by jessechunn** [comment]
> Hm, all seems well here. Maybe some anti-virus is preventing the build process from creating new files on disk?

Same issue with antivirus turned off. Also tried moving to new directory off the root, running as Administrator. Same issue. Is there anything I can look at or provide to help diagnose this?

**Comment by luboslenco** [comment]
Please check https://github.com/armory3d/armorpaint/issues/129#issuecomment-499854180.

> Is 'git' command accessible from command line? Looks like it fails for not being able to locate it.
