### ISSUE TITLE
Building ArmorPaint on NixOS linux

### ISSUE THREAD

**Issue by the-argus** [armory3d/armorpaint#1467]
I use NixOS and would like to set up a development environment for ArmorPaint. At the moment, I get [this error](http://ix.io/4fgD) while building the project. It provides very little that is helpful to me in order to understand what is going wrong. Here is the devShell environment I'm in, when I invoke the ``armorcore/Kinc/make --from armorcore -g opengl --compiler clang --compile`` command that causes the error:

```nix
{
    devShell.x86_64-linux =
      pkgs.mkShell
      pkgs.mkShell.override {
        stdenv = pkgs.clangStdenv;
      } {
        packages = with pkgs;
          [
            alsaLib
            mesa
            libGLU
            libGL
            linuxHeaders
            libglvnd
            gtk3
            gtk3-x11
            vulkan-loader
            libudev-zero
            libudev0-shim
            wayland
            wayland-protocols
          ]
          ++ (with pkgs.xorg; [
            libXinerama
            libXrandr
            libXi
            libXext
            libXcursor
          ]);
      };
}
```

As you can see, I am using clang and have the required libs (and more!) as far as I can tell.

I am on commit ``7db533dd5869a49c85bcaf403f43e82d7afa97c4`` of armorpaint, and am using commit ``8993cc730d11148ef59e84a8f15f94f688e1bfd1`` of nixpkgs.

**Comment by luboslenco** [comment]
Hi, please ensure that the `/home/argus/Desktop/armorpaint/armorcore/Tools/haxe/haxe-linux64` binary has permission to run.

**Comment by the-argus** [comment]
It seemed to already be executable, but I tried ``chmod +x armorcore/Tools/haxe/haxe-linux64`` just to be sure. No effect. Even running the build as root does not help. ENOENT may be caused by some cloning error? I cloned the repository initially with ``git clone https://github.com/armory3d/armorpaint --recursive --depth 1``. Is there some prerequisite dependency i need to build or install?

**Comment by luboslenco** [comment]
I wish I could be more helpful but I am not sure what is wrong, sorry. The build actions for Linux seem to be working fine, maybe try inspecting those:

https://github.com/armory3d/armorpaint/actions/runs/3393998607/jobs/5642003204
https://github.com/armory3d/armorcore/actions/runs/3429138571/jobs/5714348950
