### ISSUE TITLE
I need help with the armor paint - github version

### ISSUE THREAD

**Issue by Noahthenoob53** [armory3d/armorpaint#147]
Hello! I have a lot of issues with the armor paint github verision. Before I buy it I want to play around with the github version but every time when I try to install and use armor paint it either doesn't start or I get a black screen. I also watch a new tutorial about the installation (https://www.youtube.com/watch?v=dk9OOP4DmoU&t=44s)but I tried it more than 5 times out,  unfortunately it didn't worked. I really hope that someone can help me!

**Comment by SojanJanso** [comment]
Yes the Github repo is not very stable. Do you have java installed? Try [this](https://drive.google.com/open?id=1GSAzHTPxYtHnA7zAf6CJVhiyJkd4g0RT) build I made. I tested it on a friends computer and it worked, so if it doesn't work on your computer we will know we are missing something.

**Comment by luboslenco** [comment]
> Note 1: This repository is aimed at developers and may not be stable 🙂 

There should be no need for java though. Try the build by @SojanJanso, works fine here. Beware: undo system in git version is in the middle of upgrade process, lots of issues there right now..

**Comment by Noahthenoob53** [comment]
What!! Did you really send me the standalone? This works perfectlty!

**Comment by SojanJanso** [comment]
@Noahthenoob53 Just make sure to buy it if you like it :wink:

**Comment by Noahthenoob53** [comment]
I will buy it but the github version doesn't work. I have everything installed. Even the c++ input for the visual community.

**Comment by MoritzBrueckner** [comment]
@Noahthenoob53 did you choose "Release" as the build configuration in Visual Studio or "Debug"? I had the same issue (black screen) and I just forgot to choose "Release". Maybe this helps :)

@SojanJanso I think you mean JavaScript. Yes you need node.js. Java is a completely different language than JavaScript.

**Comment by luboslenco** [comment]
@Noahthenoob53 can you paste the output from Visual Studio after getting a black screen? 

node.js to build, to run Krom on Windows nothing is required apart from VC++ redist thingy. 🙂

**Comment by SojanJanso** [comment]
@MoritzBrueckner yeah, I was under the impression that they shared some libraries for some reason.
@Noahthenoob53 I tried the video tutorial, and It did not work for me. I only got it to work after I followed the steps written in the github read me. And as moritz said, I indeed changed the setting to "release" in visual studio, so that might actually be it.

**Comment by Noahthenoob53** [comment]
@MoritzBrueckner I followed EVERY step from the video. If did it more than 5 times. The purchased version worked for me so I buy it 100 %. It was really cool tho!

**Comment by SojanJanso** [comment]
@Noahthenoob53 If you don't want to have to run visual studio every time, and ore build it to run it (witch takes for EVER on VS), you can copy the Krom file in ```armorpaint/Krom/Deployment```, and past it beside the ```armorpaint/build/krom```, you can just run it from there, and armorpaint will work fine. You can also use the Krom for linux from https://github.com/armory3d/Krom_bin

**Comment by luboslenco** [comment]
Please use the https://github.com/armory3d/Krom_armorpaint as linked in this repository, otherwise you will not get file dialogs to save project / export files and similar odd behavior.. After the first build in Visual Studio you should get it to run instantly, and you will get an error log in the Visual Studio output which is handy when running git version for reporting bugs. 🐛

**Comment by Noahthenoob53** [comment]
Thank you so much guys. I really thought no one would help me! 😁
