### ISSUE TITLE
Android file path Incorrect

### ISSUE THREAD

**Issue by MarioPeper** [armory3d/armorpaint#1470]
On Android a path on a SD card is searched. But the Rom memory is displayed. If no SD card is installed, nothing can be exported.
P.S. would be nice to know where the projects are stored to work between desktop tablet and phone.

**Comment by luboslenco** [comment]
Should be now resolved in the latest Android update, thanks for report!

Projects are stored at `/data/user/0/org.armorpaint/files`.
