### ISSUE TITLE
Stop storing binaries on git - cache binaries elsewhere

### ISSUE THREAD

**Issue by the-argus** [armory3d/armorpaint#1473]
I'm currently trying to build armorpaint on nixOS linux, where libs and the elf interpreter are in different locations from most linux distributions. The binaries stored in this git repository are compiled to be interpreted by ``/lib64/ld-linux-x86-64.so.2``. At the moment I am patching the executables ( an extremely long and tedious process :( ), but this issue is still important: providing source for your build tools increases portability. I understand that having the binaries in version control makes it seem like the build is easier to set up and reproduce, but the reality is that those binaries are still interpreted and dynamically linked. You have not controlled all the state of the build process by putting your binaries in version control.

**Comment by luboslenco** [comment]
If I understand correctly then this is in regards to [Kinc](https://github.com/Kode/Kinc) bundling the binaries used in the build process -  a change like this would need to happen at Kinc repo. If the build process in Kinc changes, then ArmorPaint adopts that. Sorry but it would be too much to manage that by myself.
