### ISSUE TITLE
unstable, crashes ll the time and I cant see the brushes anymore

### ISSUE THREAD

**Issue by philippeflorent** [armory3d/armorpaint#1476]
just installed/compiled the latest version

suddenly it does not show the brushes anymore

![image](https://user-images.githubusercontent.com/118295975/208492937-d040a2a1-4381-4a0b-b168-5e7bf827c5db.png)

and now I cannot click anywhere anymore
this is really unstable

**Comment by luboslenco** [comment]
Hi, please fill in the bug template (knowing armorpaint version + OS is very handy), should be able to fix it promptly then!

Link:
https://github.com/armory3d/armorpaint/issues/new?assignees=&labels=bug&template=bug_report.md&title=
