### ISSUE TITLE
Crash using "UV Island"

### ISSUE THREAD

**Issue by runtime-error-r00** [armory3d/armorpaint#1482]
every time I try to use the fill with the "UV island" function it keeps crash

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorcore/commit/653193cedb1761124bdb58c048128c4ec05a539f, thanks for report.

**Comment by runtime-error-r00** [comment]
I've done what was written and it still crashes every single time I try to use the fill with UV Island function

https://user-images.githubusercontent.com/80646658/210101637-f411a82d-e7a7-4471-a951-f9f1bed64a05.mp4 (hope u can see it ) , video with the crash 

![image](https://user-images.githubusercontent.com/80646658/210101764-d742dd4f-1e4f-48f7-88a4-e22bdeb0caf2.png) (picture with the code updated)
