### ISSUE TITLE
Not Being Able To Launch ArmorPaint After Self Compile

### ISSUE THREAD

**Issue by cornholio11111** [armory3d/armorpaint#1483]
**ArmorPaint version:**
Version - 0.8

**OS/device including version:**
OS: Windows 10.0.19045 Build 19045
CPU: i7 -6700 Intel (3.40GHz)
GPU: NVIDIA GeForce GTX 1080 (Dell, Alienware Aroura R5)
Ram: 16GB DDR4

**Issue description:**
When I try to open ArmorPaint after Self Compiling it doesn't launch at all

**Steps to reproduce:**
just follow the steps on the github page and it should bug out.

Video: https://www.youtube.com/watch?v=arlgnCZZmCw

**Comment by luboslenco** [comment]
Please check the windows instructions in the readme.
