### ISSUE TITLE
Errors when running armorpaint.blend in Blender2.79 and 2.80

### ISSUE THREAD

**Issue by cborelc** [armory3d/armorpaint#15]
Steps taken:
1. Import armorpaint.blend in Blender2.79 (downloaded Armory_04_win64_b27.7z and the 2.8 version)
2. Press "Play" in "Armor Player section of rendering window.

The console shows:
...
Compiling shader 1 of 1 (Material_voxel.frag.glsl) failed:
Shader compiler error.
...
Compiling shader 8 of 8 (painter-video.vert.glsl).
D:\programs\Armory\armsdk\Kha\Sources/kha/internal/ShadersBuilder.hx:84: characters 59-64 : Array<kha.Blob> should be kha.Blob
D:\programs\Armory\armsdk\Kha\Sources/kha/internal/ShadersBuilder.hx:84: characters 59-64 : Array<kha.Blob> should be kha.internal.BytesBlob
D:\programs\Armory\armsdk\Kha\Sources/kha/internal/ShadersBuilder.hx:84: characters 59-64 : For function argument 'source'
D:\programs\Armory\armsdk\Kha\Sources/kha/Shaders.hx:4: lines 4-6 : Defined in this class
D:\programs\armorpaint-master\Sources/arm/UITrait.hx:463: characters 37-66 : Cannot access private field frameG
D:\programs\armorpaint-master\Sources/arm/UITrait.hx:464: characters 37-66 : Cannot access private field frameG
D:\programs\armorpaint-master\Sources/arm/UITrait.hx:301: characters 44-55 : object : iron.object.Object -> mat : iron.data.MaterialData -> link : String -> Null<kha.FastFloat> should be String -> Null<kha.FastFloat>
D:\programs\armorpaint-master\Sources/arm/UITrait.hx:302: characters 43-53 : object : iron.object.Object -> mat : iron.data.MaterialData -> link : String -> iron.math.Vec4 should be String -> iron.math.Vec4
D:\programs\armorpaint-master\Sources/arm/UITrait.hx:303: characters 43-53 : object : iron.object.Object -> mat : iron.data.MaterialData -> link : String -> iron.math.Vec4 should be String -> iron.math.Vec4
D:\programs\armorpaint-master\Sources/arm/UITrait.hx:304: characters 49-56 : object : iron.object.Object -> mat : iron.data.MaterialData -> link : String -> kha.Image should be String -> kha.Image
D:\programs\armorpaint-master\Sources/arm/UITrait.hx:304: characters 49-56 : For function argument 'x'
D:\programs\armorpaint-master\Sources/arm/UITrait.hx:885: characters 7-22 : zui.Zui has no field imageInvertY
D:\programs\armorpaint-master\Sources/arm/UITrait.hx:906: characters 7-22 : zui.Zui has no field imageInvertY

Done.
Finished in 10.702107429504395
Build failed, check console

**Comment by luboslenco** [comment]
Hello,

If you are compiling git version of ArmorPaint then you need to use the git version of Armory, as both projects are developed simultaneously. Do not use b2.8 version though, that can bring another set of issues (untested).
