### ISSUE TITLE
Add Material ID management 

### ISSUE THREAD

**Issue by DarkS474** [armory3d/armorpaint#150]
Although the usual workflow is to use a 3D modeling software to assign Material ID to faces/vertices of an object before painting with another software like ArmorPaint, it could be useful if ArmorPaint had its own easy but still feature rich Material ID management tools to let users add multiple materials to any object without having to rely on any 3D modeling software. It would speed up the workflow to do everything materials/painting related inside ArmorPaint.

**Comment by luboslenco** [comment]
Linking with https://github.com/armory3d/armorpaint/issues/382 and https://github.com/armory3d/armorpaint/issues/381.
