### ISSUE TITLE
Lowest item in Object list can not be hidden or transformed

### ISSUE THREAD

**Issue by Daerst** [armory3d/armorpaint#152]
Armor Paint v0.6 (2019-06-27) - ea12196 on Windows 10

1. Import FBX with multiple objects.
1. Try to hide each individual object (Scene -> Properties -> Visible toggle)
--> The lowest (in my case) object is always visible, even if the checkbox is unchecked.

1. Try to move, rotate, scale each individual object
--> The lowest (in my case) object is does not change at all

**Comment by luboslenco** [comment]
Fixed in new dev build. Note: additional objects are now parented to the first object.
