### ISSUE TITLE
'Object' fill mode always covering the entire geometry, even if parts are separate objects

### ISSUE THREAD

**Issue by Daerst** [armory3d/armorpaint#153]
Armor Paint v0.6 (2019-06-27) - ea12196 on Windows 10

1. Import an FBX with two separate objects (e.g. GunMetal, GunGrip).
1. Fill with the 'Object' mode.
--> Both parts are painted, which makes quickly painting logically separated parts of the mesh really hard.

To be clear: The two parts are both topologically unconnected and in separate objects. They are not joined together as one.

**Comment by luboslenco** [comment]
Fill tool should now respect the filter selection in `Layers` tab. With filter set to specific object, only that object gets filled.
