### ISSUE TITLE
Crash on .arm load

### ISSUE THREAD

**Issue by winterwicht** [armory3d/armorpaint#1534]
*ArmorPaint 0.9-238f9e8, Windows*

**Issue description:**
AP silently crashs on load or load most recent. Its a car model for ACC. 0.8 loads that without a fault. 
FYI - 0.8 starts with a black model btw, have to min/max the window.

**Steps to reproduce:**
load 3d.obj ;)

**Comment by winterwicht** [comment]
yes, shit, i made a mistake. sry, its not the obj, its the .arm what crashes. i have also no clue what i am doing, so it just maybe some dumb stuff i made. But 08 loads. 0.9 not.  I append the arm. 
[lambotest9.zip](https://github.com/armory3d/armortools/files/10948024/lambotest9.zip)

**Comment by luboslenco** [comment]
Should be resolved after https://github.com/armory3d/armortools/commit/5e22373d40f5dc9a1f08f851973a965d414f0cca, thanks for report!
