### ISSUE TITLE
Base / detail normal map blending

### ISSUE THREAD

**Issue by Daerst** [armory3d/armorpaint#154]
My modeling process is as follows:

1. Create a high-poly mesh that is not unwrapped
1. Create a low-poly mesh and unwrap it.
1. Bake normals from high to low.

Now, I'd like to texture this low-poly object in ArmorPaint _while applying this normal map as a base._ The painted normal maps should be blended on top of it. Currently, the painted normal maps are overwriting my base normal map, killing the nice baked high-poly details.

Information on blending normals can be found here:
https://blog.selfshadow.com/publications/blending-in-detail/
The Whiteout and UDN Blending methods are fairly simple and should give adequate results in most cases, so they'd be something to try.

**Comment by Vytek** [comment]
This is a very important feature

**Comment by sirmaxim** [comment]
You can accomplish this with nodes, but it is *very* inconvenient.
https://i.imgur.com/bI3qmny.png

I have built and tested it in armor paint 0.7 and it does work, however it is very time consuming to build. I attempted to export the material to share here, but it crashes on me.

**Comment by therev123** [comment]
We could fix this with an improvement of Fill Layer feature, or looking for to implement an additional Fill Layer feature inheriting from the existing feature. In my view both way have their own plus and flaw. We can already set uvmap texture on 3d object with fil layer, this video prove it(look at 14min 56s): https://www.youtube.com/watch?v=V7jWi8w0v2Q

@luboslenco I said you that I will go back with a solution about my Multi Texture set feature request. There it is. Let me know if you want ro know more about it :).

**Comment by jcostello** [comment]
Any update on this issue? IMO its very important

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/b443977c7424ee48e6687c430910c04a078facb8. It is enabled by default and can be set per layer via `layer context menu - normal blending` option.

![cap](https://user-images.githubusercontent.com/3685704/106286792-53514580-6246-11eb-9c82-48b5d9088417.png)
