### ISSUE TITLE
Issues with Hardness and Opacity

### ISSUE THREAD

**Issue by Daerst** [armory3d/armorpaint#155]
Windows 10 / 0.6rc (9378b62)

Here are some issues regarding the Hardness and Opacity controls. They might be by design, so I'd be happy to hear your thoughts.

When working on a layer with the brush opacity set to 0.3, the opacity won't add up when I paint over a surface multiple times. It'll be 0.3 the first time, and it will not changed afterwards. I'd expect the opacity to build up (i.e. combine 0.3 times the stroke with 0.7 times what's underneath, each time I paint over the area) so it converges towards full opacity of 1.

The hardness value seems to be the absolute width of the blend region, and not proportional to my brush size. Actually, hardness should control the blend between a constant strength and a linear (or other?) falloff towards the edge. The way it is currently, it is very hard to control and painting with a small soft brush is almost impossible to set up.

**Comment by luboslenco** [comment]
Working to improve brushes in the 0.8 release - thanks for all the details, comes in very handy.

(Linking with https://github.com/armory3d/armorpaint/issues/231)
