### ISSUE TITLE
Textures have seams around UV-islands after import into UE4

### ISSUE THREAD

**Issue by SpicyMemeBoi** [armory3d/armorpaint#157]
v0.6 (2019-06-27)
The textures look fine in armorpaint but have small seams around the UV-islands after importing them into UE4.

![Untitled](https://user-images.githubusercontent.com/50810138/60993685-3d6fed00-a34f-11e9-8935-b862a6be7caa.PNG)

**Comment by SojanJanso** [comment]
Yeah, this has been hanging around in one form or another for a while now, see http://forums.armory3d.org/t/pixel-bleed-fix-needed/3218

**Comment by luboslenco** [comment]
There is a way to stretch brush strokes using `Paint Bias` option in preferences (a value above 1 can be entered manually), but in that case UV-islands need a bit of margin. Will try to make it a little smarter soon so there is less need to tinker with that option.

![1](https://user-images.githubusercontent.com/3685704/60994434-cfc4c080-a350-11e9-9860-8d8a905c39cf.PNG)

**Comment by PixelPartner** [comment]
Renaming it to `Paint Bleed` would help. And an on screen explanation even more.

**Comment by adriansnetlis** [comment]
I think extending them indefinitely in the margin-space until they hit other island's extension would be a good solution (in an approach similar to voronoi).

**Comment by dacanizares** [comment]
Yeah, something like this would be great: https://docs.substance3d.com/spdoc/padding-134643719.html

Here is a Gimp plugin to do something similar: https://polycount.com/discussion/114616/uvpadder-filter-for-gimp-2-6

**Comment by SaraDark** [comment]
https://docs.substance3d.com/spdoc/padding-134643719.html it look cool (wow feature)  :+1:

**Comment by luboslenco** [comment]
`Preferences... - Usage - Dilate Radius` option is now available for generating padding when painting. New builds up soon.

**Comment by philippeflorent** [comment]
> `Preferences... - Usage - Dilate Radius` option is now available for generating padding when painting. New builds up soon.

does not work for me, the seems are always there
setting dilate to 0 does not fix anything setting it to higher numbers makes it even worst

would be nice if painting was done beyond the uv seems
