### ISSUE TITLE
Obj import streched polygons

### ISSUE THREAD

**Issue by FirefightGI** [armory3d/armorpaint#158]
*ArmorPaint 0.6-9378b62, Windows*
I just purchased ArmorPaint and I have been getting visual errors with some .obj models seemingly at random that have stretched polygons on import. For example the attached sword image. 
[Sword.zip](https://github.com/armory3d/armorpaint/files/3413289/Sword.zip)

![bug](https://user-images.githubusercontent.com/20493432/61575205-e61ffa00-aa7d-11e9-8ff8-f353604ec862.png)

I have attached a .zip folder containing the model.

**Comment by luboslenco** [comment]
Fixed now in fresh 0.7 development build, many thanks for opening this issue!
