### ISSUE TITLE
Type not found : iron.math.Vec4 (in file InputNode.hx)

### ISSUE THREAD

**Issue by Papergami45** [armory3d/armorpaint#161]
Trying to compile latest Armorpaint git version on Arch Linux. Get this issue.

Sidenote: Had to git clone Kromx seperately, as it wouldn't clone with the --recursive argument ("Direct fetching of that commit failed"). Doubt it's related but thought I would mention.

**Comment by luboslenco** [comment]
Should clone properly again now, which also eliminates the `Type not found : iron.math.Vec4` error. Doing some work on the internals so more errors can pop up using the latest git version, but will get it back in order asap.
