### ISSUE TITLE
Tile Material Output

### ISSUE THREAD

**Issue by FirefightGI** [armory3d/armorpaint#163]
A slider to tile material output would be extremely helpful something similar to UV scale but for each individual material. Maybe just increase the UV scale's maximum value to beyond 2.

**Comment by luboslenco** [comment]
Some improvements in the latest 0.7dev builds:
- Fill layer has individual `UV Scale` control:
![1a](https://user-images.githubusercontent.com/3685704/67132135-ea3bef00-f207-11e9-97f8-ef06baff242f.PNG)
- `UV Scale` brush property has higher range, any value can be entered through keyboard.
- To scale UVs directly in material, `Mapping` node can be used:
![1b](https://user-images.githubusercontent.com/3685704/67132136-ec9e4900-f207-11e9-9ec1-a61fdc0ff4ff.PNG)
