### ISSUE TITLE
Breakpoint Exception when zooming out nodes 

### ISSUE THREAD

**Issue by saumilhack** [armory3d/armorpaint#164]
armorpaint v 0.6 
windows 8.1 64bit 
when i zoom out nodes they always crash and vs tells me that krom.exe has triggered a break point 
Krom.exe has triggered a breakpoint. occurred
int byteLength = format_byte_size(texture->format) * texture->tex_width * texture->tex_height * texture->tex_depth;
		Local<ArrayBuffer> abuffer = ArrayBuffer::New(isolate, tex, byteLength);
		args.GetReturnValue().Set(abuffer);
here it triggers

**Comment by saumilhack** [comment]
https://ibb.co/jZQk1Xh
![Screenshot (38)](https://user-images.githubusercontent.com/22980796/61930523-a2585380-af9b-11e9-8eae-e0d361ad5020.png)

**Comment by saumilhack** [comment]
i think its because i dont have gpu 
because when i checked it exception is showed in gpu areas

**Comment by luboslenco** [comment]
Fixed now in latest builds & latest git, thanks for report!
