### ISSUE TITLE
Metallic material is not working in Linux

### ISSUE THREAD

**Issue by SojanJanso** [armory3d/armorpaint#165]
On latest update 8c39514, and Linux (Ubuntu 18.04)

Metallic slider on material output makes no difference in the 3d window when painting.
![Peek 2019-07-30 08-42](https://user-images.githubusercontent.com/26679320/62130101-439a1f00-b2a6-11e9-9b9e-1a307fa85990.gif)

**Comment by SojanJanso** [comment]
I tried reproducing it in windows, but it still seems to work fine there.

**Comment by luboslenco** [comment]
Any luck with the latest/updated build? Appears to be ok here.

**Comment by SojanJanso** [comment]
Confirmed, it's now working again in build f6677e3

**Comment by luboslenco** [comment]
Wohoo, thanks for testing!
