### ISSUE TITLE
Support symlinking the ArmorPaint binary to a directory

### ISSUE THREAD

**Issue by Calinou** [armory3d/armorpaint#166]
I'd like to add ArmorPaint to `PATH` quickly by symlinking the `ArmorPaint` binary to a directory in my `PATH` such as `$HOME/.local/bin/armorpaint`. However, doing this will cause ArmorPaint to crash on start with the following message:

```text
could not load krom.js. aborting.
```

As a workaround, I can write a launcher script that `cd`s to the ArmorPaint directory then starts it, but it'd be more convenient if I could symlink the binary directly :slightly_smiling_face: This works with many other software (including Blender), as they detect the base directory that corresponds to the resolved symlink.

PS: For those who need it, here's a launcher script for reference:

```bash
#!/bin/sh

# Change the path below depending on where you extracted ArmorPaint
cd "$HOME/.local/opt/armorpaint/"
./ArmorPaint "$@"
```

**Comment by luboslenco** [comment]
Sorry but I was not able to figure this out. If anyone gets to it then PR is welcome, here is where the arguments are passed to ArmorPaint: https://github.com/armory3d/armorcore/blob/master/Sources/main.cpp#L3678.
