### ISSUE TITLE
Add some mask for some effects in distributive

### ISSUE THREAD

**Issue by Lexpartizan** [armory3d/armorpaint#168]
What about add some mask for some effects in distributive.
Like fingerprints, cracks, grunge, scratches, streaks, attritions...

Hard to search for them yourself.
And each artist has long had such a set of texture masks.
In addition, I think they will come in handy when you make node tools for generating all kinds of things, so it will be useful to include them in the distribution.

Well, I’ll ask the question at the same time ...
Are you going to make tools using curvature, world position, etc.
We can bake them in a blender, but I would like to use them in your program.
But you implemented raytrasing feature, this allows us to hope that we will bake in Armor Paint.

I understand, that i want too much, but you must not concede the Substance Painter.  SP allows  to create normal textures for people who do not have artistic abilities. And that's all thanks to his generators, smart masks, etc., when you can stain or age the surface in one click. And, of course, over time we want to see something like this in your program. And even more. Thanks to the node system, i hope that Armor Paint will replace Substance Designer.

**Comment by luboslenco** [comment]
Will make it happen, linking with issue https://github.com/armory3d/armorpaint/issues/177. Curvature baking is also included now. 🙂
