### ISSUE TITLE
Window does not show up on Windows + Krom

### ISSUE THREAD

**Issue by guidomm55** [armory3d/armorpaint#17]
this is the print of console:
https://user-images.githubusercontent.com/25100386/42649186-4f9b4a76-85df-11e8-856e-ff372b7fb0d0.png

**Comment by luboslenco** [comment]
Hm, do other Armory projects work for you fine? Maybe some write access issues?

**Comment by guidomm55** [comment]
no project works

**Comment by chabad360** [comment]
I'm getting a `KeyError: 'copy_mrt3_pass'` when ever I try to compile armorpaint. I havent tried other projects but it seems like a global issue.

**Comment by luboslenco** [comment]
@chabad360  Updating armory to [git version](https://armory3d.org/manual/#/dev/gitversion?id=armory-updater) should fix that error. (It's looking for `copy_mrt3_pass` located at [armsdk/Armory/Shaders](https://github.com/armory3d/armory/tree/master/Shaders)).

@guidomm55 Try to move the folders from desktop to something like `C:\Users\user_name\Documents\test`, maybe that helps with the write access. Running Blender from console or as an admin may also help. If problem persists please open issue at [armory](https://github.com/armory3d/armory).

**Comment by chabad360** [comment]
did that, it compiles. however, it refuses to load on my system (probably because my system is lower-end).

**Comment by luboslenco** [comment]
@chabad360 what do you get - black screen or immediate crash? What is your OS and GPU?

**Comment by chabad360** [comment]
seems like when I open the startup file, krom does the same thing, but browser works fine. on Armorpaint (didn't try this with startup file) nmake gives some syntax errors.

**Comment by luboslenco** [comment]
Perhaps ok now?

**Comment by chabad360** [comment]
Sorry, I haven't been using armory or windows recently, so I can't really tell you...

**Comment by luboslenco** [comment]
No prob at all, thanks for dropping a reply. 🙂
