### ISSUE TITLE
App doesn't show title on opened file on Linux

### ISSUE THREAD

**Issue by OfficialKris** [armory3d/armorpaint#170]
ArmorPaint Version: b0257bb573c15a8dae17d361b17ea5fa091882e7
OS: Elementary OS 5.0

Issue: When you open a saved file the title displays as `"untitled - ArmorPaint."`

Steps to reproduce:

1. Open ArmorPaint
2. Open a saved file
3. Observe incorrect naming

Expected behavior:

It is expected to display the name of the file as well as an asterisk for when an edit has been made but is not saved. Potentially the file path could be worked in.

Current behavior (opened file edited and non-edited, and new file):

![Screenshot from 2019-08-18 21 46 18](https://user-images.githubusercontent.com/37947442/63235093-2d78e200-c206-11e9-9111-bfe1cf6f8928.jpg)

Suggested behavior:

New file:

![Screenshot from 2019-08-18 21 46 18 3](https://user-images.githubusercontent.com/37947442/63235111-3c5f9480-c206-11e9-8f5f-8fee327f94c9.jpg)

Opened file (note: asterisk for edited file):

![Screenshot from 2019-08-18 21 46 18 2](https://user-images.githubusercontent.com/37947442/63235126-4f726480-c206-11e9-8b03-53dfd62c0cb1.jpg)

Inspiration from blender:

New file:

![Screenshot from 2019-08-18 22 08 25](https://user-images.githubusercontent.com/37947442/63235142-5e591700-c206-11e9-85a7-44ed16212245.png)

Opened file:

![Screenshot from 2019-08-18 22 09 55](https://user-images.githubusercontent.com/37947442/63235146-61ec9e00-c206-11e9-9a61-ab978f4b40a7.png)

Edited file:

![Screenshot from 2019-08-18 22 08 49](https://user-images.githubusercontent.com/37947442/63235156-67e27f00-c206-11e9-8156-e2700841600d.png)

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/Kode/Kinc/pull/449.
