### ISSUE TITLE
Particle tool freezes the whole application

### ISSUE THREAD

**Issue by LukeSeers** [armory3d/armorpaint#172]
ArmorPaint Version: latest repo build
OS: Windows 10

Once clicking on the Particle tool, the clicking function stops working. Which kinda freezes the application. The only way I've found a fix is by restarting Armor Paint.

Note: Its only the Particle tool, everything else seems to work fine.

![gif](https://user-images.githubusercontent.com/16389426/64443896-d2326500-d0ca-11e9-9285-290b8322f72c.gif)

**Comment by Granada1** [comment]
I can confirm ,just tested with same results


Windows 10 Pro 64 bit
GeForce RTX™ 2070 GAMING OC 8G 
AMD FX (tm)-9590 Eight-core Processor
31.96 GB RAM
3840 x 2160 ,60 Hz

**Comment by luboslenco** [comment]
Fixed at https://github.com/armory3d/iron/commit/0d69c96ef05624fed0065c730ac22a4e28d43e98 / https://github.com/armory3d/armorpaint/commit/5d27a14f0c39a1af514322b7fa1d7e077022223d, many thanks for report!
