### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by Senn04** [armory3d/armorpaint#173]
I'm trying to build ArmorPaint 0.7 on Windows10 x64 

When trying to build the program using  MS Visual Studio 2017 I get the attached error even when I follow the exact instructions in the README.md 
![Annotation 2019-09-07 192602](https://user-images.githubusercontent.com/42946874/64478221-9b7d4d00-d1a5-11e9-93bc-e7f6115c5adc.jpg)

**Comment by luboslenco** [comment]
Make sure to unpack the v8 lib like mentioned in the readme:
`# Unpack 'V8\Libraries\win32\release\v8_monolith.7z' using 7-Zip (exceeds 100MB)`

Hope that helps!
