### ISSUE TITLE
Interface blurs up when "3d Cursor" is enabled Win 64

### ISSUE THREAD

**Issue by MOAdev** [armory3d/armorpaint#174]
Armorpaint 6.
Windows 10 Home.
Nvidia 1080Ti
24GiB Ram.

The entire interface is blurred until the moves near the text. This only happens with the 3d cursor enabled.

**Comment by luboslenco** [comment]
Fixed in 0.7 dev builds, thanks for report, Link with https://github.com/armory3d/armorpaint/issues/205.
