### ISSUE TITLE
Preferences Don't Get Saved

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armorpaint#176]
*Please specify your ArmorPaint version and OS.*
ArmorPaint 0.7 beta on Linux (5.2.13.arch1-1)

When I set something in preferences (e.g. viewport quality) the preferences do not get saved. Having an option to save current preferences, or even better - per-file preferences - would save a lot of time.

**Comment by luboslenco** [comment]
Should properly auto-save on change now.
(https://github.com/Kode/Kinc/pull/420 https://github.com/Kode/Kinc/pull/424)
