### ISSUE TITLE
Material/Brush/Particle Preset Library

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armorpaint#177]
I think it would be cool if there was a library that you can enable somewhere in the interface that has a set of materials, brushes and particles provided that are likely to be used by many people.

Those can include examples with using procedural nodes as well as some with packed textures. To prevent size increase of the armory executable and it's data those could be only downloaded once the user clicks on "import preset library" or something like that.

Additionally, community library repository could be made where everyone can provide their custom libraries for others to download and use in their projects.

**Comment by luboslenco** [comment]
To access the library `Browser tab - Cloud` button is now available. It is very bare bones and clunky for now, will improve over time. Library items are also visible at https://armorpaint.org/cloud.html.

It will also be possible to add custom libraries, right now there is a `Preferences - Usage - Cloud Server` option which can be pointed to any S3 storage.
