### ISSUE TITLE
Armorpaint freezing on .hdr import

### ISSUE THREAD

**Issue by bmobius** [armory3d/armorpaint#180]
Armorpaint 0.7 on Windows 10

When attempting to import an .hdr image, the application freezes and can only be closed.

**Comment by MoritzBrueckner** [comment]
Same issue here, though Armorpaint crashes and doesn't freeze on my system. The import itself appears to be working (the console prints the import progress and it seems fine) but afterwards Armorpaint crashes.

Also Win 10, using the latest stable version from Gumroad

**Comment by luboslenco** [comment]
Fixed now in new dev builds, thanks for report!
