### ISSUE TITLE
ArmorPaint Still Freezing on .HDR import for EnvMap

### ISSUE THREAD

**Issue by bmobius** [armory3d/armorpaint#181]
ArmorPaint is still freezing on .hdr import for EnvMap. Application freezes and can only be closed out by clicking on the "X".

Windows 10 Pro
CPU: Intel 8 Core i7-5960X 3.00 GHz
GPU: Nvidia GeForce Driver (GTX 980ti)

**Comment by luboslenco** [comment]
Hi, can you share which armorpaint version are you running? (from `Menu - Help - About...` dialog)
Does .hdr file from [armorpaint_samples repository](https://github.com/armory3d/armorpaint_samples/releases) also freeze?

**Comment by bmobius** [comment]
version v0.7 (2019-09-19) 1560f82
Windows direct3D11
NVIDIA GeForce GTX 980 Ti

**Comment by luboslenco** [comment]
Did you test with the one I linked above? Alternatively, can you share the .hdr file that crashes for you?

**Comment by bmobius** [comment]
I completely missed that link. I'm downloading it now. Give me a few minutes to test.

**Comment by bmobius** [comment]
Here is one of the .hdr files I've been attempting to use.

[Panorama.zip](https://github.com/armory3d/armorpaint/files/3644352/Panorama.zip)

**Comment by luboslenco** [comment]
Thanks for testing & sharing the file! Somehow it works on my windows 10 machine, but I will test on two more setups and hopefully get it reproduced.

**Comment by Granada1** [comment]
Freezing for me to using the latest windows dev build

Windows 10 Pro 64 bit
GeForce RTX™ 2070 GAMING OC 8G 
AMD FX (tm)-9590 Eight-core Processor
31.96 GB RAM
3840 x 2160 ,60 Hz

**Comment by milanvanzanten** [comment]
Same problem (tried with the Panorama.hdr given above) on v0.7 (2019-12-16) - 10b7645

Windows 10 x64
GeForce GTX 1070
Intel Core i7-6700K
16 GB RAM

**Comment by luboslenco** [comment]
Anyone able to retest with the latest 0.8 dev (328e67b) builds? Assuming it still freezes, please paste the contents of `stderr.txt` file from your `/ArmorPaint` folder (if present).

**Comment by luboslenco** [comment]
Please reopen if issue persists.

**Comment by JuliusH93** [comment]
Hello,
i too have the crash issue whilst loading an .hdr map inside of armor paint.
Here is the info provided in the about section:

ArmorPaint.org - v0.8 (2020-10-06) - 67538a9
Windows - Direct3D11
IDIA GeForce GTX 1080  

Attached is a zip with the stderr.txt and the .hdr files i tried to load. The sample hdr failed aswell.
[ArmorPaint_0.8.zip](https://github.com/armory3d/armorpaint/files/5404755/ArmorPaint_0.8.zip)

**Comment by luboslenco** [comment]
Investigating at https://github.com/armory3d/armorpaint/issues/628, many thanks for the info!
