### ISSUE TITLE
UV coordinates for base color are broken when scaling/rotating the coordinates

### ISSUE THREAD

**Issue by ReiMari** [armory3d/armorpaint#182]
ArmorPaint: v0.7 (2019-10-03) - 69acf2a
OS: Windows 10 (10.0.17763 Build 17763)

UV coordinates are broken when the UV coordinates are scaled (both when scaled through the UV Scale slider) while using a mapping node in the material.

Base color only:
![BaseColor_Only](https://user-images.githubusercontent.com/7037870/66145889-fa4eae80-e60b-11e9-9a56-a8d5f09108e0.png)

Base color & normal map:
![BaseColor_And_NormalMap](https://user-images.githubusercontent.com/7037870/66145946-118d9c00-e60c-11e9-89d4-204fe16b4d39.png)

Only Y scaling and/or rotating the UV coordinates cause this to happen. X scaling seems to be fine.

A similar thing seems to happen with roughness when only the base color is scaled and plugged in.

The issues are also present in the export, so it's not just a rendering thing.

Edit: normal map UV's are fine when the base color UV's are broken

**Comment by luboslenco** [comment]
Appears to work properly now in latest 0.8 development builds, thanks for report!
