### ISSUE TITLE
Drag and Drop material crash in Armor Paint DXR 0.7 DEV

### ISSUE THREAD

**Issue by Clockmaster** [armory3d/armorpaint#185]
Hi, I'm using Armor Paint DXR 0.7 DEV.
When i drag and drop a material in the viewport, the program crashes, while it works perfectly in previous versions.

My system's specs:
AMD FX-8150, 16 Gb RAM
Windows 10 64 bit Version 10.0.18362 build 18362
NVidia GeForce GTX1070 8 Gb
Graphics Driver version 431.60

Thanks for the attention

**Comment by luboslenco** [comment]
Fixed it latest build, thanks for report!
