### ISSUE TITLE
Exploding geometry with the brush tool

### ISSUE THREAD

**Issue by takeobass** [armory3d/armorpaint#186]
Hi! I just purchased armor paint but I seem to have a major problem with it. Whenever I import an .obj file and try to paint it with a material with textures using a brush, it literally explodes the whole object geometry. Am I doing something wrong? I imported the obj and the folder with material textures just as shown in your youtube video. I have tested 0.6 and 0.7 versions - both the same issue.

EDIT: my system specs:
Intel i7 8700
Gigabyte GTX 1080ti
32GB DDR4 
nvidia studio drivers - version 431.70
windows 10 - most recent update

![explode](https://user-images.githubusercontent.com/33058900/66963645-79b09900-f074-11e9-8000-78f2bce95ff4.png)

**Comment by Granada1** [comment]
Never seen that before, maybe you could provide the file to the Dev for testing

**Comment by takeobass** [comment]
Okay, so a quick investigation revealed I might have the same problem as the guy in this bug report:
https://github.com/armory3d/armorpaint/issues/167
Is this going to be fixed, or already is but I don't know how to use armor paint? When I unplugged the height map from the nodes tab, the geometry explosion happens no more. When I plug it back in, it happens again.

**Comment by takeobass** [comment]
> Never seen that before, maybe you could provide the file to the Dev for testing

I have tested a couple of .obj's, but here is the one from the screenshot (see attachment)
[47-obj.zip](https://github.com/armory3d/armorpaint/files/3736669/47-obj.zip)

**Comment by luboslenco** [comment]
Hello! Right now the height map will displace mesh vertices along normals, but it's not handy in cases. It can be disabled by setting `Viewport tab - Displace` to `0`. Maybe I should set it to `0` by default?

![111](https://user-images.githubusercontent.com/3685704/67306126-c245d780-f4f6-11e9-97e2-842a75f77912.PNG)

**Comment by luboslenco** [comment]
Tried to re-normalize height map displacement strength in latest dev builds, so it should no longer look like an explosion.
