### ISSUE TITLE
Can the blender material node be imported for use?

### ISSUE THREAD

**Issue by karlxuthus** [armory3d/armorpaint#187]
Hi,I just purchased armor paint on the gumroad. I select the amory3d in order to have rendering effects on blender2.8. But something error occur when I have the material node on armory3d for direct use. 
So I think I need the  armor paint. I have the idea of importing the node to the armor paint.Then I complete the model and export the file on the armor paint to the blender2.8.
The model in Aromry3d runs ok.

**Comment by luboslenco** [comment]
Hi!

> But something error occur when I have the material node on armory3d for direct use

Can you show me the error? Do you mean the one reported at https://github.com/armory3d/armory/issues/1440?

**Comment by karlxuthus** [comment]
> Hi!
> 
> > But something error occur when I have the material node on armory3d for direct use
> 
> Can you show me the error? Do you mean the one reported at [armory3d/armory#1440](https://github.com/armory3d/armory/issues/1440)?

Yes, eevee material node may not be supported by armory3d for the time being. So I use armorpanit's object and texture to test something. And I add rotation to the model. When the player runs, the model can be broken.

**Comment by karlxuthus** [comment]
> Hi!
> 
> > But something error occur when I have the material node on armory3d for direct use
> 
> Can you show me the error? Do you mean the one reported at [armory3d/armory#1440](https://github.com/armory3d/armory/issues/1440)?

**Comment by karlxuthus** [comment]
emmmm....I build failed
[3.zip](https://github.com/armory3d/armorpaint/files/3759910/3.zip)

**Comment by luboslenco** [comment]
It seems to work ok for me.:( Do other armory projects work for you? What is the error output in system console?
![1a](https://user-images.githubusercontent.com/3685704/67489867-8df72600-f672-11e9-86a2-af6385ff20ab.PNG)

**Comment by luboslenco** [comment]
Continuing at https://github.com/armory3d/armory/issues/1440.
