### ISSUE TITLE
UI glitching (git version)

### ISSUE THREAD

**Issue by AFWSI** [armory3d/armorpaint#188]
Windows 10 x64
GTX 950M
440.97

ArmorPaint ```commit 04765d66bbcba8989182ba12a535f4d7d66be5cd```

Really bad UI glitching.

![armorpaint_ui](https://user-images.githubusercontent.com/24877571/67485288-531fce80-f62f-11e9-9f89-36b932c65324.jpg)

Hover over the material name and you lose material name and node categories.
![armorpaint_ui_2](https://user-images.githubusercontent.com/24877571/67485313-5d41cd00-f62f-11e9-995b-2cebc18096b7.jpg)

**Comment by luboslenco** [comment]
There is probably some error thrown - can you check the debug output in visual studio?

**Comment by AFWSI** [comment]
See if this helps any.

![armorpaint_debug](https://user-images.githubusercontent.com/24877571/67509207-19af8900-f658-11e9-9265-37f90caae2b4.jpg)
