### ISSUE TITLE
Applying Material

### ISSUE THREAD

**Issue by emilguder** [armory3d/armorpaint#189]
*ArmorPaint 0.7-15ffafb, Windows*

When applying the default material via drag and drop to the default cube ArmorPaint crashes and closes itself.

**Comment by luboslenco** [comment]
Hi, is this on DXR build? Need to fix this in our Direct3D12 backend, but It should work fine in regular non-dxr Direct3D11 builds. (link https://github.com/armory3d/armorpaint/issues/185)

**Comment by emilguder** [comment]
Yes its the DXR and it works fine on the regular one. Thanks for the quick response!

**Comment by luboslenco** [comment]
Thanks for the report, fix incoming at https://github.com/armory3d/armorpaint/issues/185!
