### ISSUE TITLE
Resizing Window on Mac OS does not work correctly

### ISSUE THREAD

**Issue by kenthinson** [armory3d/armorpaint#19]
I paid for the ich.io version to help support the project :)

The release has a bug on Mac OS. If you make the window bigger after launching the App. The GUI does not resize correctly to fit the window. Leaving strange white area around the GUI.

A different issue I tried to build the github code to see if this has already been fixed but the project fails to build on my system. Second screen shot.

![screen shot 2018-07-25 at 4 54 28 am](https://user-images.githubusercontent.com/2245494/43199510-178b9fe0-8fc7-11e8-9ee9-fd347131ff6a.png)
![screen shot 2018-07-25 at 4 58 10 am](https://user-images.githubusercontent.com/2245494/43199589-5c815b94-8fc7-11e8-84ca-60c1437bad83.png)

**Comment by luboslenco** [comment]
Fixed the resizing on macOS, will be live in 0.5 soon. Thanks for the report!
