### ISSUE TITLE
Use materials to define texture sets

### ISSUE THREAD

**Issue by emilguder** [armory3d/armorpaint#190]
I think ArmorPaint would benefit greatly from using materials to define texture sets instead of seperated meshes. This way it would work the same as Unreal and Unity do.

**Comment by luboslenco** [comment]
Do you mean splitting the mesh by material when importing from obj/fbx/..?

**Comment by emilguder** [comment]
Yes so that ArmorPaint creates a different texture set per material

**Comment by luboslenco** [comment]
Added `File - Import Mesh - Split By - Material` option in latest 0.7 dev build. Afterwards new layers can be assigned to specific material.

**Comment by emilguder** [comment]
Nice!
