### ISSUE TITLE
Vector Mapping - display rotation in degrees

### ISSUE THREAD

**Issue by emilguder** [armory3d/armorpaint#191]
*ArmorPaint 0.7-15ffafb, Windows*
When using the Vector Mapping to adjust position, rotation or scaling of an image it just disappears which makes it impossible to adjust anything.

**Comment by luboslenco** [comment]
Can you please paste example node setup to reproduce?

**Comment by emilguder** [comment]
Found the issue, the UV Map Vector did not work correctly. I think this was an issue with my computer, not with the software.

**Comment by emilguder** [comment]
Part of the issue was that the rotation is hard to grasp. I think switching it to degrees woulp help.

**Comment by luboslenco** [comment]
Mapping node displays rotation in degrees now.
