### ISSUE TITLE
Disabling or masking a Height Map does not work properly

### ISSUE THREAD

**Issue by emilguder** [armory3d/armorpaint#192]
*ArmorPaint 0.7-15ffafb, Windows*

When trying to disable or mask the Height Map of a material everthing but the Height Map gets masked.

**Comment by luboslenco** [comment]
Can you please give me steps to reproduce? I tried disabling `Height` in the material context menu and afterwards painting no longer seems to affect height, but I think you mean something different.

**Comment by emilguder** [comment]
Yea sure!
First step: Apply the material to the object
Second Step: Create black mask for the material and see if the height is adjusted,
Third Step: Disable the Height for the applied material and see if anything changes

**Comment by luboslenco** [comment]
Fixed now, normal map masking to go at https://github.com/armory3d/armorpaint/issues/331.
