### ISSUE TITLE
Focus on selected

### ISSUE THREAD

**Issue by emilguder** [armory3d/armorpaint#193]
Maybe add in a focus feature for the 3D and 2D viewport to focus on the selected node or mesh.

**Comment by luboslenco** [comment]
Hi, do you mean focus as in point camera to selected object? Or display/draw only selected object in the viewport?

**Comment by emilguder** [comment]
Yea, I was talkinh about a camera focus on the selected object. Sometimes with bigger meshes its hard to locate and focus on the part youre painting onOn Dec 10, 2019 2:03 PM, Lubos Lenco <notifications@github.com> wrote:Hi, do you mean focus as in point camera to selected object? Or display/draw only selected object in the viewport?

**Comment by luboslenco** [comment]
Linking with https://github.com/armory3d/armorpaint/issues/251.
