### ISSUE TITLE
Texture filtering & materials

### ISSUE THREAD

**Issue by izzymg** [armory3d/armorpaint#194]
Is there any way to completely disable filtering/interpolation on the material output? Even with super sampling turned to x0.25 and texture filtering disabled, it appears the values are still being filtered in the actual painting.
![filtering](https://user-images.githubusercontent.com/30461139/67906625-18dba180-fbda-11e9-908b-4ee161bb08ba.png)

Thanks! Great program.

**Comment by luboslenco** [comment]
Looks like the filtering is still performed when sampling `Image Texture` node. Fix incoming, thanks for report!

**Comment by luboslenco** [comment]
Fixed in latest dev builds. The option is now available under `menu - viewport - filter textures`.
