### ISSUE TITLE
[Bug] GPU rendering distorted screen

### ISSUE THREAD

**Issue by Staazvaind** [armory3d/armorpaint#195]
Version 0.6 and 0.7dev
Win10
Gtx1080 on I7 8086K

3D Cursor on / off no change

Picture:
https://i.imgur.com/d1y0nyW.png

**Comment by luboslenco** [comment]
Hi, any change if you disable `SSAO` option in `Preferences - Viewport`? Your setup looks perfectly normal, which nvidia driver version are you on? Thanks for report.
