### ISSUE TITLE
DPI issues on Surface Book

### ISSUE THREAD

**Issue by mike-kennedy** [armory3d/armorpaint#196]
Hi Everyone,
I found today that ArmorPaint is unusable a Microsoft Surface Book running at 3000 x 2000 pixels.
Tried a lot of the DPI tricks in Windows at the ArmorPaint application level, not system, it's only ArmorPaint that's having issues. I checked off the various HDPI settings but it doesn't seem to change anything in ArmorPaint. Plusthe text is so small I am struggling to even see options.
 
Any suggestions? Even if it's the same steps but maybe I missed something, would be great.
Thanks ahead of time .
Cheers Mike K

![ArmorPaint_DPI_Issue](https://user-images.githubusercontent.com/26829461/67995381-84e0f880-fc20-11e9-87d4-1370e231a4a1.PNG)

**Comment by Granada1** [comment]
Hi ,did you try changing the view scale in Armorpaint

**Comment by luboslenco** [comment]
Please raise the `UI Scale` option in ArmorPaint to `2.0` or higher:
- In 0.6: `Preferences tab - Interface - UI Scale`
- In 0.7dev: `Menu bar - Edit - Preferences - Interface - UI Scale`

If UI is too small to navigate, open `ArmorPaint/data/config.arm` file in text editor and change `"window_scale":1` to `"window_scale":2`.

Looking into auto-setting this option on high-dpi screens for upcoming builds. Sorry for trouble and thanks for bringing attention to this!

**Comment by mike-kennedy** [comment]
That worked thank you, used the config at 2

**Comment by luboslenco** [comment]
ArmorPaint will now auto-set `UI Scale` to `2.0` on high-res screens in latest dev builds.
