### ISSUE TITLE
Mari inspired workflow

### ISSUE THREAD

**Issue by EgertKanep** [armory3d/armorpaint#198]
Mari has amazing nodes based workflow possibilities. I feel like Armorpaint could benefit a lot from a couple of Mari like features.

Paint node in node graph - basically having a paint layer as a node.

Nodes for masks - when you create a mask it could be treated same way like a fill layer and you could use nodes to modify masks. Together with paint node that would open up a whole new world of masking.

Third idea would be node layer. It would be an empty node graph where user could drag n drop a material and start making custom tweaks to it.

Maybe this a too different from the workflow you have in mind, 

All that said I'm super impressed already about the work you have done.

**Comment by luboslenco** [comment]
Amazing post, thanks! Will start rolling these nodes in upcoming builds. 🔨

**Comment by luboslenco** [comment]
Improvements in the recent builds:
- Paint layer can be dragged into node editor 
- Control mask with nodes - select `To Fill Mask` in the mask context menu (https://github.com/armory3d/armorpaint/commit/b2b898709b2b376b92eff6e1946476b0c2b14604)
- Material can be dragged into node editor, for tweaks or mixing multiple materials
