### ISSUE TITLE
Send to LuxCore

### ISSUE THREAD

**Issue by EgertKanep** [armory3d/armorpaint#199]
I just figured what if Armorpaint had a feature like Substance Painter where you could render your scene with Iray, but instead Armorpaint could use open source render engine like LuxCore. Or is this already a planned feature? This would benefit both projects and should be relatively easy to do (says persons who has no idea about coding). But I could try to find a curious developer who would want to tackle this task.

**Comment by Hopefullyidontgetbanned** [comment]
I like this idea, having a non real-time renderer built in or natively integrated would be great for previewing how other programs would render it or people who might not know how to use programs like blender but already have a mesh.
Also having more features that compete with programs with Substance Painter is ultimately good for any Mesh Painter. Armorpaint can likely convert scene data into a Luxcore format. Luxcore also has an API with documentation

**Comment by luboslenco** [comment]
Will focus more on progressing the built-in path tracer for the time being (ie. https://www.youtube.com/watch?v=uQb-LOJdYrE). However if someone decides to develop luxcore plugin please let me know, glad to help with that!
