### ISSUE TITLE
Mouse drag up/down direction reversed?

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armorpaint#20]
in windows 0.4 build, used mouse to drag the object up/down then the object rotated in the opposite direction.
Feel free to close this if it is an expected behavior.

**Comment by MiloHX** [comment]
Hi I have done more test. The dragging direction only makes sense when you are dragging the front of the model. When the model is not front facing to the camera, the rotation direction is very confusing (sometimes reversed)

**Comment by luboslenco** [comment]
Fixed.
