### ISSUE TITLE
Compiled version doesn't start from .exe

### ISSUE THREAD

**Issue by Atulin** [armory3d/armorpaint#200]
Current version, (https://github.com/armory3d/armorpaint/commit/0163f27d05bb10856aaee79206544d4458df4290) running on Win10 1903, compiled with VS 2019.

Release x64 starts up just fine when started from within Visual Stuidio, but trying to open `Krom.exe` directly doesn't work for some reason. Just shows the spinner next to the mouse cursor for a split second and that's that.

**Comment by Roci-dev** [comment]
Hi there, so the instructions don't make it that clear, but there is a folder `armorpaint/build/krom`, I assume you were doing like I was doing and building it to `armorpaint/Kromx/build/x64/Release` Just cut everything in that folder and move it to the `armorpaint/build/krom` folder instead.

**Comment by Atulin** [comment]
Yep, that works perfectly, thanks!
