### ISSUE TITLE
Black Screen when compiling on Linux

### ISSUE THREAD

**Issue by varomix** [armory3d/armorpaint#201]
Hi
trying to build this on POP_OS  is basically Ubuntu 19
I get it to compile but I get a black window, no content

I tried with the latest code on github and the 0.6 tag 19.08
both same results

this is the output
`Xinerama extension is not installed
Trace: TypeError: Cannot read property 'get_frequency' of null
    at Function.kha_Scheduler.start (<anonymous>:6543:36)
    at Function.kha_SystemImpl.init (<anonymous>:37468:16)
    at Function.kha_System.start (<anonymous>:37235:17)
    at Function.Main.start (<anonymous>:103:13)
    at Function.Main.main (<anonymous>:83:7)
    at <anonymous>:45629:6
    at <anonymous>:45630:3
`
The xinerama issues was fixed a while ago, it might be something else
https://github.com/Kode/Kinc/pull/273

thanks

**Comment by luboslenco** [comment]
Looks like Kinc still fails to retrieve primary display on your setup or something. Maybe this helps to get past through it https://github.com/armory3d/Kromx/commit/f5174c3026c1ce13eebb1e4a3647c92159b51f29.

**Comment by varomix** [comment]
Hey Lubos, that was it, the issue is with a dual monitor setup, cause I compiled it on my laptop and that worked, run that build in my workstation and failed
After your modification it works on my workstation as well, you should PR this to the main Kromx repo

thanks for the help

**Comment by luboslenco** [comment]
Great to hear, thanks for testing!

Unfortunately if you examine https://github.com/armory3d/Kromx/commit/f5174c3026c1ce13eebb1e4a3647c92159b51f29 it's more of a 'hack' fix. Kinc fails to retrieve primary display for some reason. I tested on Ubuntu 18.04 + dual monitor setup and it worked, have to investigate with no xinerama.

**Comment by varomix** [comment]
xinerama is horrible for 3D apps, bad performance I never use it, also makes your monitors like one big monitor, I don't think anyone uses Xinerama

**Comment by luboslenco** [comment]
Kinc itself uses Xinerama to retrieve display info.
https://github.com/Kode/Kinc/blob/master/Backends/System/Linux/Sources/Kore/Display_Xinerama.cpp

**Comment by varomix** [comment]
as you can see that is a bad idea, cause Xinerama is not something enabled by default and is not even encouraged anymore

**Comment by luboslenco** [comment]
If it's not enabled by default then I am clueless why it still works on my Ubuntu + dual monitor setup. But will do a proper research soon, thanks for info.
