### ISSUE TITLE
Keymap: unable to assign "/" and "." keys on Linux

### ISSUE THREAD

**Issue by harsan81** [armory3d/armorpaint#202]
Hello. I just recently bought and tried ArmorPaint 0.6 in Linux Ubuntu, and the first thing I tried was to change the keymap as I'm left-handed and it's not very efficient for me to use Ctrl+Z to undo. I tried changing the shortcut to "/" but it's not working. I can't change the redo key to "." too. 

Is there a way for me to change the keymap to punctuation & symbols like "/" and "." or is it just not possible? If I can't change it, then it'll be hard for me to use the software, as I've gotten used to using "/" as Undo in another software like Blender and Krita. 

And if it's not possible for me to change it, can it be added to the next release? It would be very helpful. Thank you.

**Comment by luboslenco** [comment]
Hi, it should be resolved in the upcoming build - will release asap in coming days. Thanks for report!

**Comment by luboslenco** [comment]
Fixed now in latest ArmorPaint 0.7 dev builds.
(link https://github.com/Kode/Kinc/pull/447)
