### ISSUE TITLE
Every import / export operation crashes the editor, Manjaro Linux, compiled from github

### ISSUE THREAD

**Issue by DjoleDzele** [armory3d/armorpaint#207]
As it says in the title, even when run with sudo, the error in terminal is "Segmentation fault".
The other errors that are there as soon as i start the program are:

Uniform N not found.
Uniform texUnpack not found.
Uniform step not found.
Uniform brushScale not found.

**Comment by luboslenco** [comment]
I guess Zenity is missing on your system to open the file browser dialog. Will implement a fallback to the non-system custom file browser for the final 0.7 builds.
Please post further findings at https://github.com/armory3d/armorpaint/issues/179.

**Comment by DjoleDzele** [comment]
I read that answer in one of the previous reports and checked, i dont think it's that,
Zenity --version gives 3.32.0

**Comment by luboslenco** [comment]
Thanks for info! Will have to install another distro and hopefully will be able to reproduce & fix. 🙁

**Comment by DjoleDzele** [comment]
Hope so too, thank you guys for all the awesome work!

**Comment by luboslenco** [comment]
Posted an update at https://github.com/armory3d/armorpaint/issues/179#issuecomment-550532899, maybe that helps at least as a temporary workaround.
