### ISSUE TITLE
GL Error 1280 Segfault Crashes

### ISSUE THREAD

**Issue by cgvirus** [armory3d/armorpaint#208]
Armory paint version 0.6, 0.7 dev and Git self compiled
OS Debian 10 Bullseye/Sid. 
NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1  
GeForce GTX 950

All of the version gives:
`GL Error 1280 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 242`
and sometimes this:
`GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/RenderTargetImpl.c 170`

and crashes with segfault.

Also throws bunch of warning:
```
Uniform N not found.
Uniform texUnpack not found.
Uniform step not found.
Uniform brushScale not found.
Uniform W not found.
Uniform eye not found.
Uniform aspectRatio not found.
Uniform brushScale not found.
Uniform WVP not found.
Uniform inp not found.
Uniform inplast not found.
Uniform aspectRatio not found.
Uniform brushOpacity not found.
Uniform brushScale not found.
Uniform aspectRatio not found.
Uniform brushOpacity not found.
Uniform brushScale not found.
```

To reproduce:
Unfortunately very random. Mostly :

1. while assign a new material
2. Changing paint Layer to Material
3. Changing RGB color, plugging texture node etc.

**Comment by luboslenco** [comment]
Thanks for report, this will come in handy! Linking this issue with https://github.com/armory3d/armorpaint/issues/204 as it is hopefully related. Please feel welcome to post any further findings there as well. Apparently it goes boom during shader/pipeline compilation.
