### ISSUE TITLE
No import in the file menu

### ISSUE THREAD

**Issue by dannysetvisions** [armory3d/armorpaint#209]
I had to read the help files to find out how to import a model into ArmorPaint. I literally fell at the first hurdle. I'm assuming there was a specific reason to omit 'Import' from the File menu but it's a bit of an obstacle. Almost every application I use has an import feature in the file menu. Drag and drop is really good and I like that but not having an import in the menu feels incomplete and would be a reason for someone to use Substance over Armorpaint. 

Any change this could be added to the menu?

**Comment by luboslenco** [comment]
Hi, thanks for feedback! Please check out the 0.7 development builds (`ArmorPaint_07dev`), import and export options have been added to the menu. Hoping to finalize 0.7 asap. 🙂

![1aa](https://user-images.githubusercontent.com/3685704/68371979-424b7e80-0140-11ea-8360-a9796299ee13.PNG)

**Comment by dannysetvisions** [comment]
Awesome!
We're really new to this workflow and are really excited to start using it in production.
________________________________

**Comment by luboslenco** [comment]
Did more refinements in 0.7 dev builds, file menu should now look fairly standard.
