### ISSUE TITLE
Armory paint won't start

### ISSUE THREAD

**Issue by Noahthenoob53** [armory3d/armorpaint#21]
Hello! I really need help! When i try to start (Play) armory paint then it gives me an error

**Comment by luboslenco** [comment]
Hi! What does the error say?

**Comment by Noahthenoob53** [comment]
Traceback (most recent call last):
  File "C:\Users\Noah\Documents\Armory4\armsdk//armory/blender\arm\props_ui.py", line 498, in execute
    make.play(in_viewport=False)
  File "C:\Users\Noah\Documents\Armory4\armsdk//armory/blender\arm\make.py", line 428, in play
    build(is_play=True, in_viewport=in_viewport)
  File "C:\Users\Noah\Documents\Armory4\armsdk//armory/blender\arm\make.py", line 350, in build
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "C:\Users\Noah\Documents\Armory4\armsdk//armory/blender\arm\make.py", line 168, in export_data
    for s in assets.shader_passes_assets[ref]:
KeyError: 'copy_mrt3_pass'

**Comment by luboslenco** [comment]
Compiling git version of ArmorPaint needs [git version of Armory](http://armory3d.org/manual/#/dev/gitversion?id=armory-updater). Once that is done it should compile properly. It's probably safer to play with Armory first before jumping on ArmorPaint development. Hope that helps!

**Comment by Noahthenoob53** [comment]
Hi!! it didn't worked but thank you!! I practice the Armory3d engine all the avaible time. I really want to try armory paint out before pay for it! ( i will buy Armory paint)

ohh and it gave me a other error message:

C:\Users\Noah\Documents\armorpaint-master\Sources/arm/logicnode/ObjectNode.hx:20: characters 29-35 : Type not found : armory.Scene
C:\Users\Noah\Documents\armorpaint-master\Sources/arm/logicnode/ObjectNode.hx:20: characters 29-69 : Void should be armory.object.Object
C:\Users\Noah\Documents\armorpaint-master\Sources/arm/logicnode/ObjectNode.hx:20: characters 29-69 : Void should be iron.object.Object
C:\Users\Noah\Documents\armorpaint-master\Sources/arm/logicnode/InputNode.hx:20: characters 15-21 : Type not found : armory.system.Input
C:\Users\Noah\Documents\armorpaint-master\Sources/arm/logicnode/InputNode.hx:29: characters 13-19 : Type not found : armory.system.Input

Have a nice day!

**Comment by Noahthenoob53** [comment]
OMG!!! it worked thank you so much Lubos >3 Bro!! I will buy Armory paint anyway to help you

have a nice day!!!
