### ISSUE TITLE
ArmorPaint not compiling on Ubuntu 19.04

### ISSUE THREAD

**Issue by charliergi** [armory3d/armorpaint#210]
Hello,
I try to compile ArmorPaint on Ubuntu 19.04 with all the dependencies installed but it doesn't work.
I've tried many ways, with command lines in the README.md, or with Kode Studio.
I've carefully installed all the requirements.
Here are the steps I followed and errors that occured.
First I recursively clone the repo :
```
git clone --recursive https://github.com/armory3d/armorpaint
```
Then I go into the armorpaint folder
```
cd armorpaint
```
Then I execute the commands to compile on linux : 
```
# Linux
node Kromx/make -g opengl
cd Kromx
node Kinc/make -g opengl --compiler clang --compile
cd Deployment
strip Krom
./Krom ../../build/krom
```
But It crash after during the 3rd line,
Here is the log of the crash : 
[log.txt](https://github.com/armory3d/armorpaint/files/3821196/log.txt)
Apparently Krom is missing but I don't understand why...
And when I try to use KodeStudio, is crashes while importing js.lib.Int32Array;
Thanks in advance for your help!

**Comment by luboslenco** [comment]
Hello! Sorry but I have never seen this before - perhaps it's something to do with your node setup?

> FTR: make ✖ ERR  Missing Makefile / Bakefile is the output of an npm package called make. Having it in the PATH confuses node-gyp and breaks the build.

https://stackoverflow.com/questions/46587834/unable-to-install-node-expat-in-linux/55247282#55247282

**Comment by JohnSmith25** [comment]
It is probably related that there is a newer changes to how --recurse flag works, the command `git clone --recursive` seems to pull only 1 layer of submodules and doesn't check for additional submodules, it happened to me before too. The initial should have been `git clone --recurse-submodules` which pulls in all submodules found under `Kromx` directory 

In your case you could just delete the `Kinc` directory found under `armorpaint/Kromx`  and run `git submodule sync | git submodule update --init ---recursive` which should pull in all the submodules recursively.

The output should look something like this (when you removed the kromx folder):
```
user@user:~$ cd ~/programs/armorpaint_test
user@user:~/programs/armorpaint_test$ git submodule sync
Synchronizing submodule url for 'Kromx'
Synchronizing submodule url for 'Libraries/iron'
Synchronizing submodule url for 'Libraries/zui'
user@user:~/programs/armorpaint_test$ git submodule update --init --recursive
Submodule path 'Kromx': checked out '70da8463fac4f77547be8c56c5c8a1189f6658b3'
Submodule path 'Kromx/Kinc': checked out '5d1f9313e64f335b3441a11e485330dd734b1930'
Submodule path 'Kromx/Kinc/Tools/kincmake': checked out 'af525c793361bbd2a0cc13222cd02a66cbe5b84c'
Submodule path 'Kromx/Kinc/Tools/kraffiti': checked out '1a589c357b7716b6643d318eca937d81902e778a'
Submodule path 'Kromx/Kinc/Tools/krafix': checked out '5a2dc7d376bf5aef638a6d4561d0d2094ed74a75'
user@user:~/programs/armorpaint_test
```
Afterwards you should be able to compile and run this program normally with the same instruction found on the readme file.

**Comment by charliergi** [comment]
It works ! Thanks a lot !
I just deteled the module make with npm.

**Comment by luboslenco** [comment]
Great, thanks for reporting back!
