### ISSUE TITLE
TIF / TIFF file format support

### ISSUE THREAD

**Issue by Daerst** [armory3d/armorpaint#211]
ArmorPaint doesn't seem to support TIF / TIFF files currently (0.7 dev - f960268). E.g. textures.com as one of the largest resources on the web uses this file format, so support in ArmorPaint would be highly appreciated.

**Comment by luboslenco** [comment]
Added `import_tiff` plugin in latest dev builds. Once enabled in the plugin manager, `.tif`/`.tiff` images can be imported / dragged in normally. 🙂

**Comment by Daerst** [comment]
Wonderful, thanks!!
