### ISSUE TITLE
 My objects are not imported into the program 

### ISSUE THREAD

**Issue by 3Djao** [armory3d/armorpaint#213]
I've tried all the ways to import an object into the program but it doesn't leave the default square. Could someone help me?

**Comment by luboslenco** [comment]
Hello, which armorpaint version and operating system are you on? Are you able to share the object which fails to import?

**Comment by 3Djao** [comment]
I'm using windows 10 as OS and according with the updater inside de software i'm in the lastest version. would you like to see my program compiled?

**Comment by luboslenco** [comment]
Should be operational in latest 0.7 dev builds. Just drag and drop `.obj` file onto the viewport and press `Import` in the popup. If issue persists please send the info from the `Help - About...` dialog. 🙂 

![1a](https://user-images.githubusercontent.com/3685704/69672863-41e83880-1099-11ea-9a43-cc079bd8ef1c.PNG)
