### ISSUE TITLE
Project Through/Paint Buffer

### ISSUE THREAD

**Issue by RichXJester** [armory3d/armorpaint#215]
It would also be great if there was a project through feature similar to Mari's, I find this being the most used feature when working on productions so i would love to this implemented. in addition to this i think a paint buffer option would be useful too

**Comment by luboslenco** [comment]
With Decal tool selected, it is now possible to hold `ctrl` and then paint to project through the decal. Not sure if it's the exact feature but should offer similar functionality. New video coming soon to the [how to section](https://armorpaint.org/howto.html)!

**Comment by NicTanghe** [comment]
Hello,

It`s unclear to me if the concept of the paint buffer is implemented / understood.

It is very handy and explained over here.

https://www.youtube.com/watch?v=Ut3OpGf0AwY
