### ISSUE TITLE
Advanced RGB options

### ISSUE THREAD

**Issue by RichXJester** [armory3d/armorpaint#216]
it would be really nice to have RGB sliders as well as a hex value code in the RGB settings

**Comment by Hopefullyidontgetbanned** [comment]
HSV support would be nice too

**Comment by luboslenco** [comment]
Added RGB, HSV and Hex input to color wheels. Will be live in updated builds tonight.

![a](https://user-images.githubusercontent.com/3685704/86887275-973cfb80-c0f8-11ea-8ac2-796c19638174.PNG)

![2](https://user-images.githubusercontent.com/3685704/86887495-e71bc280-c0f8-11ea-98f3-71920de603f2.PNG)
