### ISSUE TITLE
Stamp Steam issues.

### ISSUE THREAD

**Issue by Bob3DPaint** [armory3d/armorpaint#217]
ArmorPaint version 7  I think  windows 
Stamps over seam cause issues and separation -  not edge bleeding.
![image](https://user-images.githubusercontent.com/57740537/68826053-4266f380-06d7-11ea-88ad-cf618e30084e.png)

**Comment by luboslenco** [comment]
Hello, thanks for report. It looks like you are running version 0.6, but I guess it will be the same in 0.7 dev build. Do you get this behavior even on the default cube? If not, are you able to share the model file with me for testing?

**Comment by Bob3DPaint** [comment]
Dont have same model but i have one i  just tested in 0.7 
[New folder.zip](https://github.com/armory3d/armorpaint/files/3858062/New.folder.zip)
![image](https://user-images.githubusercontent.com/57740537/69043934-f72e4700-0a2e-11ea-9bd3-d5f270b5e714.png)

**Comment by Bob3DPaint** [comment]
its appers to be only on sharp edges

**Comment by Bob3DPaint** [comment]
Default cube test-show issues occuring to
![image](https://user-images.githubusercontent.com/57740537/69048064-863f5d00-0a37-11ea-930e-ac27b10b40ef.png)

**Comment by luboslenco** [comment]
Ah, I see! Should be resolved soon, once the decal tool will get the warping feature mentioned at https://github.com/armory3d/armorpaint/issues/35. Will post a fix at issue https://github.com/armory3d/armorpaint/issues/35 asap.
