### ISSUE TITLE
About menu not working

### ISSUE THREAD

**Issue by EJ72** [armory3d/armorpaint#218]
Armorpaint 0.7 dev on Windows 10

Selecting the about menu opens a cmd window for a second then exits without showing the version info.

**Comment by luboslenco** [comment]
Hi, which graphics card are you on? ArmorPaint tries to fetch GPU info in the about menu and I suspect something goes wrong there - will throw in some error checking to prevent that, thanks for report.

**Comment by EJ72** [comment]
Hello luboslenco, I am currently using a PNY GTX 780 with 3 GB Vram.

**Comment by EJ72** [comment]
I can confirm that in Armorpaint v0.7 (2019-11-15) - 3487bd1 this bug does not exist.
Compiled at 9:11 AM 11/15/2019

**Comment by luboslenco** [comment]
Ah, was a git version quirk.
