### ISSUE TITLE
Material node menu does not scaled up correctly

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armorpaint#22]
I am working with a 4K monitor and using 2.5x UI scale, the menu cannot show the complete node description
![capture](https://user-images.githubusercontent.com/17811339/44001551-e7f0e034-9e66-11e8-9a61-bfb737aaceac.JPG)
:

**Comment by MiloHX** [comment]
Well It turns out that the whole material editor screen is not scaled up at all when setting the UI scale. Probably need to fix the whole thing together.

**Comment by luboslenco** [comment]
Aha yes, it's running as a separate zui instance and the scale is not passed there, will fix!

**Comment by luboslenco** [comment]
Fixed node menu scale.
