### ISSUE TITLE
Crash when checking for updates

### ISSUE THREAD

**Issue by Praxeos1** [armory3d/armorpaint#220]
ArmorPaint v0.6 (2019-05-13)
Windows Version	10.0.18362 Build 18362

I click "Help/Check for Updates..." A command prompt window opens briefly, then closes. The ArmorPaint window closes. The application does not update.

**Comment by luboslenco** [comment]
Thanks for report, still investigating - linking with issue at https://github.com/armory3d/armorpaint/issues/139.
