### ISSUE TITLE
What version of node and Visual Studio are needed to build armorpaint?

### ISSUE THREAD

**Issue by rajeshja** [armory3d/armorpaint#221]
I'm using Node.js v12.13.0 and VS 2019. 

The below command:

    node Kromx/make -g direct3d11

gives me a bunch of compilation errors:

    armorpaint\Sources/arm/ui/UIMenu.hx:289: characters 16-33 : Uncaught exception process_run
    armorpaint\Kromx\Tools\haxe\std/eval/_std/sys/io/Process.hx:1: character 1 : Called from here
    armorpaint\Sources/arm/util/BuildMacros.hx:12: characters 14-83 : Called from here
    armorpaint\Sources/arm/ui/UIMenu.hx:289: characters 16-33 : Called from here
    armorpaint\Sources/arm/ui/UIMenu.hx:23: lines 23-373 : Defined in this class
    armorpaint\Sources/arm/ui/UIMenu.hx:314: characters 16-33 : Uncaught exception process_run
    armorpaint\Kromx\Tools\haxe\std/eval/_std/sys/io/Process.hx:1: character 1 : Called from here
    armorpaint\Sources/arm/util/BuildMacros.hx:12: characters 14-83 : Called from here
    armorpaint\Sources/arm/ui/UIMenu.hx:314: characters 16-33 : Called from here
    armorpaint\Sources/arm/ui/UIMenu.hx:23: lines 23-373 : Defined in this class

I'm running Windows 10, and am using git from Ubuntu under WSL, just in case that makes any difference.

Is this something that should go into a bug report instead?

**Comment by luboslenco** [comment]
git is called during build process at https://github.com/armory3d/armorpaint/blob/master/Sources/arm/util/BuildMacros.hx#L12, I am guessing it fails to do that on your system?

**Comment by rajeshja** [comment]
Brilliant! It worked, thanks.

**Comment by luboslenco** [comment]
Yay, happy to help!
