### ISSUE TITLE
Modified, deleted and untracked files?

### ISSUE THREAD

**Issue by AFWSI** [armory3d/armorpaint#222]
Any idea why I got modified, deleted and untracked files when I tried to do ```git pull origin master``` yesterday? I ended up having to "checkout" those files to be able update. I still have a untracked file showing ,but it lets me do a ```git pull origin master``` .I never even deleted or modified any of the source files.

**Comment by luboslenco** [comment]
Which files were marked as modified?

**Comment by AFWSI** [comment]
Not sure how I get that after doing a "checkout" on them . It no longer shows when doing ```git status```. The one showing as untracked is this ```Shaders/voxel_hlsl/src/hlslbin.exe```.

**Comment by luboslenco** [comment]
Hm not sure on that either, sorry. I guess cloning from scratch will get rid of that as a last resort.
