### ISSUE TITLE
Some Material Node Love

### ISSUE THREAD

**Issue by bmobius** [armory3d/armorpaint#223]
Man, I love this app so much. Best $20 I've ever spent.

Now that I got that out of the way, may I make some requests?

**Blur Node** - Just a simple Gaussian blur would be nice. Advanced blur options, even better.

**Warp Node** - Directional warp node with an angle slider.

**RGB Node Revised** - Would really love to be able to use standard 0-255 RGB values as well as hex input. This would give ArmorPaint parity with a number of other popular apps that use those values.

**Mapping Node Revised** - Specifically rotation. I'm not sure what rotation algorithm is being used, but it's be great to be able to type in a 0-359 degree value and have the texture rotate accordingly. This would have ArmorPaint using the same artist-friendly conventions that many other popular 3D texturing apps use.

Thanks for all you do and your time!

**Comment by lucasdlk** [comment]
Maybe you should divide this ticket into one feature each ?

**Comment by luboslenco** [comment]
- Opened Warp node ticket at https://github.com/armory3d/armorpaint/issues/454
- Blur node ticker at https://github.com/armory3d/armorpaint/issues/454

> Would really love to be able to use standard 0-255 RGB values as well as hex input

Done now.

> but it's be great to be able to type in a 0-359 degree value

 Done now.

Thanks for the great suggestions!
