### ISSUE TITLE
BakeToTexture 

### ISSUE THREAD

**Issue by Bob3DPaint** [armory3d/armorpaint#224]
bake maps to a texture so I can be manipulated with nodes- for edge wear with musgrave niose

**Comment by luboslenco** [comment]
Hi, can you elaborate with more details? Do you mean something like nodes mentioned at https://github.com/armory3d/armorpaint/issues/198?

> Paint node in node graph - basically having a paint layer as a node.

**Comment by Bob3DPaint** [comment]
instead of baking to layer or mask, bake result appears as a texture in the textures tab allowing for mix in noise in nodes etc

**Comment by Bob3DPaint** [comment]
also, the awesome feature would be inverted masks in layer stack.

**Comment by luboslenco** [comment]
Some improvements in the recent builds:
- Layers can be mixed in nodes as well, same like textures
- Masks can be inverted via context menu now

Will aim to improve the layer management next.
