### ISSUE TITLE
Object disappears when setting the height texture on Linux

### ISSUE THREAD

**Issue by grimm** [armory3d/armorpaint#225]
ArmorPaint version 0.7
Linux Mint 19.2
GPU Nvidia GTX 980 (I also have a RTX 2070 but it is not connected to any monitors and is only used to render on).

To replicate the issue I just start with the default cube.
I open the nodes panel
I drag a 16bit PNG height texture into the node panel
I hook it up to the height pin on the Material Output node.
I try and paint the cube and it disappears.

Thanks,
Jason

**Comment by luboslenco** [comment]
The cube should no longer disappear in latest builds, thanks for report!
