### ISSUE TITLE
FBX Import with multiple meshes - objects reset position to origin

### ISSUE THREAD

**Issue by Uro1** [armory3d/armorpaint#226]
Windows 10 Pro x64, Build 1909.
ArmorPaint 817be55 built from repo today.

When importing FBX files all the contained mesh positions are reset to origin (0,0,0).

I tested with multiple scene's / FBX files, with and without `Parse Transforms` option on importer with same/similar position results in ArmorPaint.

This does not appear to affect OBJ files.

This seems like a regression to #81 ?

Attaching image to show result (and to verify my FBX's are not the issue), rear application is Marmoset Toolbag 3.08, front is ArmorPaint 817be55.
![toolbag_2019-11-28_14-29-51](https://user-images.githubusercontent.com/5954927/69814371-f3977e80-11eb-11ea-9d4e-25ba0cc3aaa7.png)

**Comment by luboslenco** [comment]
Hi @Uro1, are you able to throw me some random .fbx file to reproduce the issue? I attached a simple one which appears to work here (with `Parse Transforms` enabled), but I guess anything more complex fails - will take a look and fix! 🔨 
 
[fbx_file.zip](https://github.com/armory3d/armorpaint/files/3919033/fbx_file.zip)

**Comment by Uro1** [comment]
Hi @luboslenco , I put together this quick scene, exported as both obj & fbx files to compare.

1. 4items-offset-from-point-of-origin(.obj/.fbx) - are the scene objects exported as is.
2. 4items-offset-from-point-of-origin-reset-xform(.obj/.fbx) - are the scene objects with their transforms reset prior to export.

The obj files load fine for both files, the fbx files are reset in both.
With the tansforms reset before export in 2. they load in the correct orientation but still are all reset to point of origin.

I tested all files again in Marmoset Toolbag3 & in the 3D Viewer in Windows 10 and all appear as they do in 3dsMax as you can see from the viewport screenshot.

I hope you fill find these useful, I'm happy to do more test's as required to quash this issue.

![3dsmax_2019-12-04_12-30-18](https://user-images.githubusercontent.com/5954927/70143161-cd158f80-1692-11ea-85d8-ee0ba2402852.png)
[armorpaint-test-models-fbx-obj.zip](https://github.com/armory3d/armorpaint/files/3921802/armorpaint-test-models-fbx-obj.zip)

**Comment by Uro1** [comment]
hey @luboslenco any progress/planned fix for this? 
I tested latest build and still same issue.

**Comment by luboslenco** [comment]
Thanks for the test files, pushed a fix at https://github.com/armory3d/armorpaint/commit/06209c536b0c5121b8139040c82b7214b6510176 - new builds will be up soon.

![img](https://user-images.githubusercontent.com/3685704/104049205-dd2c6680-51e4-11eb-9446-19268527c7ce.PNG)

Note: When exporting from Blender, `Z` up, `Y` forward should produce the correct result. Alternatively the mesh can be rotated in ArmorPaint via `Meshes tab - Tools... - Rotate X / Y / Z`.
