### ISSUE TITLE
Preview the brushes (tools)

### ISSUE THREAD

**Issue by brunomrsn** [armory3d/armorpaint#227]
When I'm painting, I feel the need to see beforehand what is going to be painted on the mesh under the cursor. This is especially important when, for example, I want to rotate the brush. 

What I mean is the default Brush could show what is going to be painted (under it) while moving it through the mesh. Decal and Text kind of work like this (it's ok since they don't change while moving because they are kind of a stamp).

All of these brushes (Brush, Decal and Text) could also preview when I rotate them (by UV Rotate or Mapping node rotation).

PS.: When I say brush I am referring to the left-hand side tools (Brush, Eraser, Fill, Decal and so on).

**Comment by luboslenco** [comment]
New option is now available in latest dev builds at `Preferences... - Usage - Live Brush Preview`. It will display what is going to be painted beforehand. Should work for all tools apart from bake, particles, picker and color-id, in both viewport and 2d view.

It will be enabled by default once it gets more tested. Bug reports welcome!
