### ISSUE TITLE
Haxe compiler error

### ISSUE THREAD

**Issue by station437** [armory3d/armorpaint#229]
Hi, maybe I do something wrong or miss something, but after '**node Kromx/make -g direct3d11**' I get the next error:
```
...
Compiling shader 8 of 8 (painter-video.vert.glsl).
E:\Programs\armorpaint\Sources/arm/ui/UIMenu.hx:303: characters 16-33 : Uncaught exception process_run
E:\Programs\armorpaint\Kromx\Tools\haxe\std/eval/_std/sys/io/Process.hx:1: character 1 : Called from here
E:\Programs\armorpaint\Sources/arm/util/BuildMacros.hx:12: characters 14-83 : Called from here
E:\Programs\armorpaint\Sources/arm/ui/UIMenu.hx:303: characters 16-33 : Called from here
E:\Programs\armorpaint\Sources/arm/ui/UIMenu.hx:23: lines 23-387 : Defined in this class
E:\Programs\armorpaint\Sources/arm/ui/UIMenu.hx:328: characters 16-33 : Uncaught exception process_run
E:\Programs\armorpaint\Kromx\Tools\haxe\std/eval/_std/sys/io/Process.hx:1: character 1 : Called from here
E:\Programs\armorpaint\Sources/arm/util/BuildMacros.hx:12: characters 14-83 : Called from here
E:\Programs\armorpaint\Sources/arm/ui/UIMenu.hx:328: characters 16-33 : Called from here
E:\Programs\armorpaint\Sources/arm/ui/UIMenu.hx:23: lines 23-387 : Defined in this class

Haxe compiler error.

```

ArmorPaint: current git master branch
OS: Windows 10 Home x64

**Comment by station437** [comment]
Sorry, this error under 'Far manager', in console (cmd) everything is allright :(

**Comment by limarest** [comment]
I am getting the same error, what exactly is needed to be installed?

**Comment by station437** [comment]
> 
> 
> I am getting the same error, what exactly is needed to be installed?

As I remember - I had opened a terminal window before installing NodeJS and got this error in this window. I just opened a new terminal window after installing NodeJS and problem was solved.

**Comment by limarest** [comment]
> > I am getting the same error, what exactly is needed to be installed?
> 
> As I remember - I had opened a terminal window before installing NodeJS and got this error in this window. I just opened a new terminal window after installing NodeJS and problem was solved.

That's too bad. I've had node.js installed but it didn't help, I even deleted it and tried latest version and still got the same error.

**Comment by luboslenco** [comment]
Is the `git` command able to run from the command line? Looks like it fails to retrieve git commit id of your cloned armorpaint repository for some reason.

**Comment by AnonFriction** [comment]
> Is the `git` command able to run from the command line? Looks like it fails to retrieve git commit id of your cloned armorpaint repository for some reason.

I've never had any luck with the git command, I just used the desktop app to clone it that way

**Comment by station437** [comment]
> 
> 
> > > I am getting the same error, what exactly is needed to be installed?
> > 
> > 
> > As I remember - I had opened a terminal window before installing NodeJS and got this error in this window. I just opened a new terminal window after installing NodeJS and problem was solved.
> 
> That's too bad. I've had node.js installed but it didn't help, I even deleted it and tried latest version and still got the same error.

Maybe this video will help, there is another command to build: `node Kha/make Krom -g direct3d11`
[https://www.youtube.com/watch?v=dk9OOP4DmoU](url)

**Comment by luboslenco** [comment]
@station437  Noo, that is the old one, please follow the commands in the [readme](https://github.com/armory3d/armorpaint/blob/master/README.md) - always up-to-date. 🙂 

@AnonFriction it should still work when you clone using the desktop app, but [git](https://git-scm.com/downloads) needs to be available/runnable from the command line. Basically git is invoked during the build process to retrieve the version of your cloned repository which is then displayed inside ArmorPaint.

**Comment by lahtis** [comment]
Not working with Ubuntu. Getting  Haxe compiler error.

my log is:
node armorcore/make -g opengl
Using Kha from /home/tuomas/Lataukset/armorlab/armorcore
Creating Kha project.
Exporting asset 1 of 4 (Scene.arm).
Exporting asset 2 of 4 (default_brush.arm).
Exporting asset 3 of 4 (icons.png).
Exporting asset 4 of 4 (icons2x.png).
Exporting asset 1 of 24 (World_irradiance.arm).
Exporting asset 2 of 24 (World_radiance.hdr).
Exporting asset 3 of 24 (World_radiance_0.hdr).
Exporting asset 4 of 24 (World_radiance_1.hdr).
Exporting asset 5 of 24 (World_radiance_2.hdr).
Exporting asset 6 of 24 (World_radiance_3.hdr).
Exporting asset 7 of 24 (World_radiance_4.hdr).
Exporting asset 8 of 24 (World_radiance_5.hdr).
Exporting asset 9 of 24 (World_radiance_6.hdr).
Exporting asset 10 of 24 (World_radiance_7.hdr).
Exporting asset 11 of 24 (World_radiance_8.hdr).
Exporting asset 12 of 24 (black_white_gradient.png).
Exporting asset 13 of 24 (brdf.png).
Exporting asset 14 of 24 (color_wheel.png).
Exporting asset 15 of 24 (cursor.png).
Exporting asset 16 of 24 (font.ttf).
Exporting asset 17 of 24 (font13.bin).
Exporting asset 18 of 24 (font_mono.ttf).
Exporting asset 19 of 24 (ltc_mag.arm).
Exporting asset 20 of 24 (ltc_mat.arm).
Exporting asset 21 of 24 (noise256.png).
Exporting asset 22 of 24 (shader_datas.arm).
Exporting asset 23 of 24 (smaa_area.png).
Exporting asset 24 of 24 (smaa_search.png).
Exporting asset 1 of 1 (font_cjk.ttc).
Exporting asset 1 of 7 (base_color.json).
Exporting asset 2 of 7 (generic.json).
Exporting asset 3 of 7 (minecraft_mer.json).
Exporting asset 4 of 7 (unigine.json).
Exporting asset 5 of 7 (unity.json).
Exporting asset 6 of 7 (unreal.json).
Exporting asset 7 of 7 (xplane.json).
Exporting asset 1 of 1 (default.json).
Exporting asset 1 of 1 (temp.json).
Exporting asset 1 of 3 (license.md).
Exporting asset 2 of 3 (license_onnx.md).
Exporting asset 3 of 3 (license_texsynth.md).
Exporting asset 1 of 5 (autosave.js).
Exporting asset 2 of 5 (hello_node_brush.js).
Exporting asset 3 of 5 (hello_world.js).
Exporting asset 4 of 5 (import_tiff.js).
Exporting asset 5 of 5 (import_txt.js).
Exporting asset 1 of 1 (keepme.txt).
Exporting asset 1 of 5 (photo_to_base.quant.onnx).
Exporting asset 2 of 5 (photo_to_height.quant.onnx).
Exporting asset 3 of 5 (photo_to_normal.quant.onnx).
Exporting asset 4 of 5 (photo_to_occlusion.quant.onnx).
Exporting asset 5 of 5 (photo_to_roughness.quant.onnx).
Exporting asset 1 of 10 (license_fonts.md).
Exporting asset 2 of 10 (license_heapsfbx.md).
Exporting asset 3 of 10 (license_icons.md).
Exporting asset 4 of 10 (license_kinc.md).
Exporting asset 5 of 10 (license_lz4-wasm.md).
Exporting asset 6 of 10 (license_nfd.md).
Exporting asset 7 of 10 (license_stb.md).
Exporting asset 8 of 10 (license_tinydir.md).
Exporting asset 9 of 10 (license_v8.md).
Exporting asset 10 of 10 (license_zlib.md).
Exporting asset 1 of 1 (light.json).
Exporting asset 1 of 1 (readme.txt).
Compiling shader 1 of 7 (Material_mesh.frag.glsl).
Compiling shader 2 of 7 (Material_mesh.vert.glsl).
Compiling shader 3 of 7 (layer_copy.frag.glsl).
Compiling shader 4 of 7 (layer_copy_bgra.frag.glsl).
Compiling shader 5 of 7 (layer_copy_rrrr.frag.glsl).
Compiling shader 6 of 7 (layer_copy_rrrr.vert.glsl).
Compiling shader 7 of 7 (layer_view.vert.glsl).
Compiling shader 1 of 34 (Gizmo_overlay.frag.glsl).
Compiling shader 2 of 34 (Gizmo_overlay.vert.glsl).
Compiling shader 3 of 34 (bloom_pass.frag.glsl).
Compiling shader 4 of 34 (blur_adaptive_pass.frag.glsl).
Compiling shader 5 of 34 (blur_edge_pass.frag.glsl).
Compiling shader 6 of 34 (blur_gaus_pass.frag.glsl).
Compiling shader 7 of 34 (compositor_pass.frag.glsl).
Compiling shader 8 of 34 (compositor_pass.vert.glsl).
Compiling shader 9 of 34 (copy_mrt3_pass.frag.glsl).
Compiling shader 10 of 34 (cursor.frag.glsl).
Compiling shader 11 of 34 (cursor.vert.glsl).
Compiling shader 12 of 34 (deferred_light.frag.glsl).
Compiling shader 13 of 34 (deferred_light_voxel.frag.glsl).
Compiling shader 14 of 34 (deferred_light_voxel.vert.glsl).
Compiling shader 15 of 34 (histogram_pass.frag.glsl).
Compiling shader 16 of 34 (line.frag.glsl).
Compiling shader 17 of 34 (line.vert.glsl).
Compiling shader 18 of 34 (pass.vert.glsl).
Compiling shader 19 of 34 (pass_copy.frag.glsl).
Compiling shader 20 of 34 (pass_viewray.vert.glsl).
Compiling shader 21 of 34 (pass_viewray2.vert.glsl).
Compiling shader 22 of 34 (prefilter_envmap.frag.glsl).
Compiling shader 23 of 34 (smaa_blend_weight.frag.glsl).
Compiling shader 24 of 34 (smaa_blend_weight.vert.glsl).
Compiling shader 25 of 34 (smaa_edge_detect.frag.glsl).
Compiling shader 26 of 34 (smaa_edge_detect.vert.glsl).
Compiling shader 27 of 34 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 28 of 34 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 29 of 34 (ssgi_pass.frag.glsl).
Compiling shader 30 of 34 (ssr_pass.frag.glsl).
Compiling shader 31 of 34 (supersample_resolve.frag.glsl).
Compiling shader 32 of 34 (taa_pass.frag.glsl).
Compiling shader 33 of 34 (world_pass.frag.glsl).
Compiling shader 34 of 34 (world_pass.vert.glsl).
Compiling shader 1 of 3 (armdefault_voxel.frag.glsl).
Compiling shader 2 of 3 (armdefault_voxel.geom.glsl).
Compiling shader 3 of 3 (armdefault_voxel.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:100: characters 79-100 : arm.TConfig has no field camera_rotation_speed
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:101: characters 86-107 : arm.TConfig has no field camera_rotation_speed
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:103: characters 86-107 : arm.TConfig has no field camera_rotation_speed
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:111: characters 53-74 : arm.TConfig has no field camera_rotation_speed
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:113: characters 56-77 : arm.TConfig has no field camera_rotation_speed
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:116: characters 58-79 : arm.TConfig has no field camera_rotation_speed
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:238: characters 91-107 : arm.TConfig has no field camera_pan_speed (Suggestion: camera_speed)
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:239: characters 94-110 : arm.TConfig has no field camera_pan_speed (Suggestion: camera_speed)
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:218: characters 21-38 : arm.TConfig has no field camera_zoom_speed
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:166: characters 90-107 : arm.TConfig has no field camera_zoom_speed

/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:166: characters 121-137 : arm.TConfig has no field camera_pan_speed (Suggestion: camera_speed)
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:175: characters 79-100 : arm.TConfig has no field camera_rotation_speed
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:176: characters 81-102 : arm.TConfig has no field camera_rotation_speed
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:183: characters 13-23 : Class<arm.Context> has no field lightAngle
/home/tuomas/Lataukset/armorlab/Libraries/armorbase/Sources/arm/Camera.hx:183: characters 35-45 : Class<arm.Context> has no field lightAngle

Haxe compiler error.
