### ISSUE TITLE
When adjusting the material nodes smaller, the text doesn't scale down correctly

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armorpaint#23]
See the screen below:
![capture](https://user-images.githubusercontent.com/17811339/44001829-a271cae6-9e6b-11e8-8ece-8ca24983c24d.JPG)

This is not caused by UI scaling. Even if I use 1.0 UI scale, the problem is still there.

**Comment by luboslenco** [comment]
Fixed at https://github.com/armory3d/zui/commit/7103059792241d9ebf4092277b153927ce046e02.
