### ISSUE TITLE
OBJ import issues with Lightwave 3D 10.1/above and Blender 2.80 

### ISSUE THREAD

**Issue by Clockmaster** [armory3d/armorpaint#232]
Hi. I am a registered user of Armorpaint 0.7
I have noticed that when exporting my object from Lightwave 3d .lwo to .obj format , trying to import the .obj file in Armorpaint the object is heavily corrupted, with vertices that goes to near infinite values positions. If I try to import before my obj in Blender 2.8, and re-export it in OBJ format, apparently the object is not corrupted anymore, but when trying to paint on it the UV appear to be completely corrupted, probably by blender import (so not an Armorpaint bug this time). But I cannot export in Armorpaint my .obj objects at all. Recently I managed to obtain correct import in Armorpaint when exporting in FBX2011 binary format from Lightwave 3D, and importing FBX object in Armorpaint.
In this case both the object and UV are correct (only a rotate x command in Armorpaint is needed to correctly orientate the object).
So I suggest both to improve .obj importing and to mantain actual compatibility with .fbx importing, that actually is the only way for a Lightwave 3D user to import correctly in Armor Paint
Many many thanks for the attention

**Comment by luboslenco** [comment]
Hi, are you able to share the troubling .obj file? (attaching .zipped files should work here.) Will fix asap.

There was another .obj importer fix in the most recent 0.7 build released on December 6 (tag-66b788b) - if by any chance you are running an older 0.7 build please try updating as well. Thanks for report!

**Comment by Clockmaster** [comment]
Sure! 
Here my 3D .obj file attached.
I am already using latest update.
Thanks for the support
[BUG REPORT OBJ FILE.zip](https://github.com/armory3d/armorpaint/files/3936495/BUG.REPORT.OBJ.FILE.zip)

**Comment by Vytek** [comment]
I have the same problem with OBJ created with Wings 3D 2.2.4. I have bought last version of ArmorPaint:

![image](https://user-images.githubusercontent.com/2614303/70393881-57415900-19ef-11ea-98be-b3e133e36bc1.png)

Using Viewer there no problem:

![image](https://user-images.githubusercontent.com/2614303/70393815-9e7b1a00-19ee-11ea-9cfa-3d9f8d2de460.png)

![image](https://user-images.githubusercontent.com/2614303/70393856-0893bf00-19ef-11ea-8f2b-6f2d5181354f.png)

With ArmorPaint:

![image](https://user-images.githubusercontent.com/2614303/70393886-763feb00-19ef-11ea-8f77-0bda9db4c017.png)

File used:

[TestWings.zip](https://github.com/armory3d/armorpaint/files/3936673/TestWings.zip)

Please, let me know how to help.
Thank you for your work.

**Comment by luboslenco** [comment]
New 0.7 development builds are up - both models should now import correctly. Thanks a lot for sharing the files!

---

> when trying to paint on it the UV appear to be completely corrupted

Not sure if this is intentional, but on the shared Battle Tank model there are overlapping UVs, which might be difficult for painting:

![1a](https://user-images.githubusercontent.com/3685704/70543352-8e884500-1b6a-11ea-9ba7-91912e142702.PNG)

One possible fix: non-overlapping UVs can be generated directly in ArmorPaint, by enabling `Xatlas` plugin and clicking `Unwrap`:

![1c](https://user-images.githubusercontent.com/3685704/70543785-49184780-1b6b-11ea-9b94-b3facd510285.PNG)

Alternatively, using the `Smart UV Project` unwrap in Blender should also work.

**Comment by Clockmaster** [comment]
Hi! Thanks for the support. The uv problem is generated when opening the obj from blender, is a Blender issue. The obj generated by LightWave has a correct non-overlapping uv. I have managed to do this with Armorpaint: https://www.turbosquid.com/3d-models/3d-cartoon-tank-model-1480653
Thanks a lot for your program😊😊😊

**Comment by luboslenco** [comment]
> The uv problem is generated when opening the obj from blender, is a Blender issue.

Ah, I see.

> I have managed to do this with Armorpaint: https://www.turbosquid.com/3d-models/3d-cartoon-tank-model-1480653

Wohoo, love it. 😍 Please feel welcome to open additional bug / feature-request issues as well!
