### ISSUE TITLE
Segmentation fault when trying to open file on Linux

### ISSUE THREAD

**Issue by StarrKiss** [armory3d/armorpaint#233]
Manjaro KDE, latest version of ArmorPaint. When I try to launch it, it works fine, but gives this message:
Uniform N not found.
Uniform texUnpack not found.
Uniform step not found.
Uniform W not found.
Uniform eye not found.
Uniform aspectRatio not found.
Uniform brushScale not found.
When I try and open a file, I get this:
/home/gstarr/armorpaint.sh: line 5: 26722 Segmentation fault      (core dumped) ./Krom ../../build/krom

**Comment by StarrKiss** [comment]
It is the same thing with every command, by the way

**Comment by luboslenco** [comment]
Hi, thanks for report! Please check here for details: https://github.com/armory3d/armorpaint/issues/179.

To use a built-in file browser as a workaround in ArmorPaint 0.7dev:
> Added a new Edit - Preferences - Native File Browser option. Disabling this option will make ArmorPaint use it's own, primitive file browser and should make it possible to export the painted textures.

For import, drag and drop should also work in the meantime, until I figure out why Zenity has issues on Arch/Manjaro.:/

**Comment by StarrKiss** [comment]
That would probably be helpful to put in the README.md for future readers, just thinking.

**Comment by mscofield0** [comment]
Still an issue on Linux today
