### ISSUE TITLE
Can't paint on fill layer mask

### ISSUE THREAD

**Issue by Nhiqill** [armory3d/armorpaint#234]
*ArmorPaint 0.7-4a16a82, Windows* (Windows 10, built according to directions so using Direct3D)

EDIT: Okay, I was clearly mistaken in my first version of this issue that this was ever possible to do in the first place! I must have thought I was doing something I definitely wasn't!

Is it intentional that masks for fill layers can't be painted on? Brushes will of course refuse to paint if the current layer is a fill layer, but this includes if you're trying to paint on only the mask and not the layer itself.
If this is for the sake of restricting having to re-update the layer (make sense), what about displaying an error message or making the mask unselectable for dopes like me who think this is in error and keep trying anyway?

**Comment by luboslenco** [comment]
Thanks for report, fix incoming!

> EDIT: Okay, I was clearly mistaken in my first version of this issue that this was ever possible to do in the first place! I must have thought I was doing something I definitely wasn't!

It appears to work fine in ArmoPaint 0.6, so it probably worked in one of the builds you tried in the past. 🙂

**Comment by Nhiqill** [comment]
Pulled latest build, confirmed working now for me. Thanks so much for the excellent work!

**Comment by luboslenco** [comment]
Glad to hear!
