### ISSUE TITLE
Mipping edge issue with alpha and normal map decal, working fine with uv map mode

### ISSUE THREAD

**Issue by Bob3DPaint** [armory3d/armorpaint#235]
windows 8.1 v0.7 (2019-11-26) -44cfe07
![image](https://user-images.githubusercontent.com/57740537/70411694-e43aef80-1a8d-11ea-810d-aa566b7da55f.png)

**Comment by Bob3DPaint** [comment]
this might be what causes the seam stamp issues

**Comment by luboslenco** [comment]
Fixed in latest development builds. If issue still pops up please reopen with sample decal texture.
