### ISSUE TITLE
Edge erosion/rust

### ISSUE THREAD

**Issue by Clockmaster** [armory3d/armorpaint#239]
Hi! It would be absolutely wonderful if in the future you can add a tool that generates rust and erosion effects on the edges of the object, like the similar ones in Substance Painter. Think of it!
Goodbye and keep up the good work!!!

**Comment by luboslenco** [comment]
Agreed! Hoping to make it available in final 0.7 builds, linking with issue https://github.com/armory3d/armorpaint/issues/145. 🙂
