### ISSUE TITLE
Update already painted material

### ISSUE THREAD

**Issue by Botoni** [armory3d/armorpaint#242]
Is, or will be posible to get already painted materials to update when the materials node tree is modified?

**Comment by luboslenco** [comment]
Hi, one way to achieve that is to use fill layers (drag and drop material onto viewport). You can also create layer mask and paint where the fill layer should be visible.

![1a](https://user-images.githubusercontent.com/3685704/71326387-87fab580-24fa-11ea-8ef8-c4e2e89c8fdb.PNG)

Afterwards, changing the material node tree will update the already painted surface.

![1b](https://user-images.githubusercontent.com/3685704/71326389-8cbf6980-24fa-11ea-9e72-ac3a53408456.PNG)

**Comment by Botoni** [comment]
I see, only fill layers remain "live". Thanks!

**Comment by luboslenco** [comment]
Glad to help!
