### ISSUE TITLE
Custom decal shape

### ISSUE THREAD

**Issue by LiamBester** [armory3d/armorpaint#243]
Hey, I would like to know how I can create a custom decal shape without having to use the default rectangle and circle shapes, because I would like to know how to import my own shape decal.

**Comment by luboslenco** [comment]
Hi, you should be able to create custom shape by using the Opacity socket of Material Output.

![1a](https://user-images.githubusercontent.com/3685704/71326151-313fac80-24f7-11ea-9c4b-90de30214710.PNG)

**Comment by LiamBester** [comment]
Thank you very much, I'll give it a try.

**Comment by LiamBester** [comment]
Hi, the method you showed me did work, however the texture becomes washed out due to plugging it into the opacity node, i'm not sure if i'm doing something wrong, I'll appreciate any help you can offer thanks.

**Comment by luboslenco** [comment]
Link  to https://github.com/armory3d/armorpaint/issues/247.
