### ISSUE TITLE
Error importing 3d model cut with blender knife tool

### ISSUE THREAD

**Issue by LiamBester** [armory3d/armorpaint#246]
*Please specify your ArmorPaint version and OS.*
Every time I import meshes that I used the blender knife cut tool it always glitches, I would appreciate a fix for this thanks.

**Comment by luboslenco** [comment]
Thanks for report - are you able to share the mesh file? Which ArmorPaint version and OS?

**Comment by LiamBester** [comment]
Im using windows10 and armorpaint version 0.7 
![2020-01-05 23_41_24-Blender](https://user-images.githubusercontent.com/59147091/71786535-1ac84380-3015-11ea-8e35-0ee563de36ab.png)
![2020-01-05 23_42_29-untitled_ - ArmorPaint](https://user-images.githubusercontent.com/59147091/71786540-1ef46100-3015-11ea-8c6f-aeb8aa1a5e10.png)
sometimes the model comes out black and hollow other times it ignores creating the geometry, I'll appreciate any help you can give, thanks.

**Comment by luboslenco** [comment]
Are you able to share the mesh file? That is the fastest way to get it fixed since I will be able to reproduce the issue myself. 🙂 

As a workaround, enable the `Triangulate Faces` option when exporting the `.obj` file to fix the issue.
![Capture](https://user-images.githubusercontent.com/3685704/71786649-e3a26400-300d-11ea-8fcf-6d7df4e4ecba.PNG)

**Comment by LiamBester** [comment]
Thanks Lubos I'll give it a try, Ill recreate a another mesh for you in a moment since I deleted the old one.

**Comment by LiamBester** [comment]
your triangulate face method worked nicely, thanks for the help.

**Comment by luboslenco** [comment]
Glad to hear, thanks for posting!

Will still investigate original issue, maybe related with https://github.com/armory3d/armorpaint/issues/228.
