### ISSUE TITLE
Plugging decal into opacity washes out original colour.

### ISSUE THREAD

**Issue by LiamBester** [armory3d/armorpaint#247]
Hi, the method you showed me did work, however the texture becomes washed out due to plugging it into the opacity node, i'm not sure if i'm doing something wrong, I'll appreciate any help you can offer thanks.

**Comment by luboslenco** [comment]
Hi, are you able to share the texture so I can reproduce the issue? Would love to take a look.

**Comment by LiamBester** [comment]
Hi, I would like to make my decals look like this which I made without using the decal tool
![2020-01-05 23_25_40-untitled_ - ArmorPaint](https://user-images.githubusercontent.com/59147091/71786336-08e5a100-3013-11ea-8edf-54d222f6ec53.png) 
but instead it comes out washed out when i use the decal tool
![2020-01-05 23_22_55-untitled_ - ArmorPaint](https://user-images.githubusercontent.com/59147091/71786346-261a6f80-3013-11ea-8474-79288afde203.png)
This is the original image
![2](https://user-images.githubusercontent.com/59147091/71786358-3df1f380-3013-11ea-83db-1d75604990e1.png)

**Comment by luboslenco** [comment]
Can you try connecting `Image Texture - Alpha` output (instead of `Color`) to the `Opacity` input? Attaching example below:

![decal](https://user-images.githubusercontent.com/3685704/72550852-efa2e700-3893-11ea-917e-5196934a855e.PNG)

(tested on 0.8dev build)

**Comment by LiamBester** [comment]
Thanks, I'll give it a try.

**Comment by luboslenco** [comment]
No prob!
