### ISSUE TITLE
Some keys for navigating not working in MacOS

### ISSUE THREAD

**Issue by eivber** [armory3d/armorpaint#248]
Many key combinations doesn't work in MacOS.
Such as shift+tab, ctrl+tab, alt+any arrow key, ctrl+middle mouse button etc.
Navigation therefore becomes kinda difficult in MacOS ;)

Some info in the running system:
Keyboard: Apple Keyboard anno 2012
Mouse: Logitech MX Master
Mac: iMac Late 2012
OS: MacOS 10.13.6 High Sierra
GPU: Nvidia GeForce GTX 680MX 2048MB
ArmorPaint 0.7

**Comment by luboslenco** [comment]
Pushed some improvements at https://github.com/Kode/Kinc/pull/515. (still unable to get shift+tab but most key combos should be fine now.)
