### ISSUE TITLE
ColorID not working in MacOS

### ISSUE THREAD

**Issue by eivber** [armory3d/armorpaint#249]
I cannot get ColorID to work properly.

I'm trying the following:
1. Import model
2. Try painting on the model a little, -works fine
3. Import ColorID-texture, select a color to work with
4. Trying to paint again, most of the model turns red plus some artifacts, and I can't paint.

Using:
OS: MacOS 10.13.6 High Sierra
GPU: Nvidia GeForce GTX 680MX 2048MB
ArmorPaint 0.7

Screenshots:
![1](https://user-images.githubusercontent.com/25989867/71773497-40dedc80-2f5e-11ea-9631-608c798a7e68.png)
![2](https://user-images.githubusercontent.com/25989867/71773498-40dedc80-2f5e-11ea-9895-554a9cfabaf0.png)
![3](https://user-images.githubusercontent.com/25989867/71773499-40dedc80-2f5e-11ea-98c5-9611320dc483.png)
![4](https://user-images.githubusercontent.com/25989867/71773500-40dedc80-2f5e-11ea-9afe-61b870867090.png)

**Comment by luboslenco** [comment]
Hi, thanks for report. I have pushed updated ArmorPaint 0.7 builds for macOS with a fix just now. Windows and Linux builds should not be affected. Please let me know if you get to test it.

**Comment by eivber** [comment]
Hi,

It worked nicely!

Your response time was insane, from bug report to bug fixed in less than 24 hours.
Thanks a lot!

![5](https://user-images.githubusercontent.com/25989867/71787368-1c930680-3017-11ea-8980-a8abeed0d2c3.png)
