### ISSUE TITLE
I can't drag textures or models in Armory paint

### ISSUE THREAD

**Issue by Noahthenoob53** [armory3d/armorpaint#25]
Hi ! i had a Problem before but now i have a other Problem. When I drag textures or models in Armory paint it doesn't show up

**Comment by SojanJanso** [comment]
In order to help out the developers can you be a little more specific, as in; what version of armor paint are you using, and what operating system are you running?

**Comment by luboslenco** [comment]
Linking to https://github.com/armory3d/armorpaint/issues/7.
