### ISSUE TITLE
Navigation without pen buttons

### ISSUE THREAD

**Issue by nozmajner** [armory3d/armorpaint#250]
It would be nice if viewport navigation would not necesseraly require any of the buttons on the pen, but only holding down a key. 
To me it is more comfortable and faster to use the keyboard for this than using the buttons on the pen. I rarely use those actually, if at all.
Another thing that would be nice is the ability to zoom in and out with keys.

Also I am left handed, so I map the most used features to the numpad for easy access. 
My texture painting setup in blender is like this for example: 
* Hold Numpad 0 for camera rotation
* Hold Numpad Enter for camera pan
* Numpad + and - for zoom

**Comment by luboslenco** [comment]
Should be doable now by configuring `Preferences.. - Keymap`.

> Another thing that would be nice is the ability to zoom in and out with keys.

Added `view_zoom_in` and `view_zoom_out` shortcuts to the keymap.

Thanks for report!

**Comment by nozmajner** [comment]
It handles great! Thank you!
