### ISSUE TITLE
Eraser shortcut switching between Eraser and Brush tools

### ISSUE THREAD

**Issue by nozmajner** [armory3d/armorpaint#252]
In Krita the Eraser is not a separate tool, but a toggle for the Brush tool. One of the most useful aspects of this is that you can toggle between Eraser and Brush with one key. This could potentially free up a key, and could make painting a bit more streamlined and comfortable.

**Comment by luboslenco** [comment]
Thanks for report! A new shortcut slot is now available at `Preferences.. - Keymap - swap_brush_eraser`.
