### ISSUE TITLE
Material browser

### ISSUE THREAD

**Issue by PnkMyo** [armory3d/armorpaint#253]
Hiya ! I was wondering about an option for a (preferably local/offline) material browser ?
Like, you know how there's little previews of the materials for the materials in the actual project ?
Yeah, what if that, but from a local library (that you can provide yourself, if there wouldn't be stuff already included) ?
((Sort of like a sample library to a musician, where they can choose whichever samples fit their current project...))

Unless that feature is already in... ? I dunno, maybe I missed something. (Or maybe it's not possible at the moment ?)

**Comment by luboslenco** [comment]
Thanks for the request! Will make it happen, in progress now for the upcoming ArmorPaint 0.8 release. 🙂 
Linking to https://github.com/armory3d/armorpaint/issues/177.
