### ISSUE TITLE
Panning is capped at 60 FPS on Linux and macOS

### ISSUE THREAD

**Issue by Calinou** [armory3d/armorpaint#254]
**OS:** Fedora 31
**ArmorPaint version:** 0.7

I'm using a 144 Hz monitor. In ArmorPaint, I noticed the brush preview moves smoothly when moving the mouse cursor (it follows the cursor perfectly), but panning seems to be capped at 60 FPS. This also applies to the axis preview in the bottom-right corner. I have a GTX 1080 with the proprietary driver, so it can definitely render more than 60 FPS.

Ideally, ArmorPaint should detect the monitor refresh rate and use that to set the FPS limit (or any other limit that's causing camera panning to run at a slower rate). Alternatively, it could offer a setting to change the FPS limit.

**Comment by luboslenco** [comment]
It should work on Windows now, however on Linux the refresh rate is hard-coded to 60 https://github.com/Kode/Kinc/blob/master/Backends/System/Linux/Sources/Kore/Display.cpp#L58, will have to fix that.

**Comment by luboslenco** [comment]
Fixes at https://github.com/Kode/Kinc/pull/554 and https://github.com/Kode/Kinc/pull/553. (live in latest builds)
