### ISSUE TITLE
Cannot Zoom using pen

### ISSUE THREAD

**Issue by ArieLeo** [armory3d/armorpaint#255]
Action_Zoom while using pen seems not working, i can rotate and pan the view but i cannot zoom the view. Using Mouse it works just fine but when i use alt+right button on pen it rotate the view.
Using Armor Paint build from repo on 13 jan 2020 commit 9e8672e232862822f7c8e789e9087becc73a0d12 [9e8672e]
On Windows with Wacom Bamboo

**Comment by ArieLeo** [comment]
additional information, if i disable the "Use Windows Ink" Setting on the Wacom Preferences i can zoom using the pen, but i lose pen pressure

**Comment by Senmuth** [comment]
I have the same problems with wacom intuos pro and Huion WH1409 tablets. ArmorPaint V 08

**Comment by luboslenco** [comment]
Linking with issue at https://github.com/armory3d/armorpaint/issues/522.
