### ISSUE TITLE
Clone also on UV

### ISSUE THREAD

**Issue by acheljay** [armory3d/armorpaint#258]
Hi, tried to clone directly on UV map but this function don't seam to exist. Could it be great for rectification on 2D (we are working on photogrammetry asset and armorpaint could be really great to correct for example seems on assets)

**Comment by luboslenco** [comment]
Ah, looks like the clone source is not getting set in the 2D view - fix incoming, thanks for report!

**Comment by luboslenco** [comment]
Fixed now in latest 0.8 dev builds.
