### ISSUE TITLE
UV unwrap issues

### ISSUE THREAD

**Issue by acheljay** [armory3d/armorpaint#260]
*Please specify your ArmorPaint version and OS.*
Tried the UV unwrap and it stuck for more than an hour (3% cpu) and does nothing. When trying to make an action, it freeze and I had to kill the soft. The config is a HP z-620 with double octocore xeon, 96Go of ram and working on a nvme disk.

**Comment by luboslenco** [comment]
Thanks for report! Are you able to unwrap the default cube, or does that freeze as well?

**Comment by acheljay** [comment]
Hi, I'll try tomorrow if I can unwrap the cube. It will be great if it unwrapp like zbrush (because using zbrush for our student in our workflow on photogrammetry is really hard).

**Comment by luboslenco** [comment]
Updated `uv_unwrap` plugin at https://github.com/armory3d/armorpaint/commit/880ee49d43df2814cc83856895039df4c9a3950c, should work a bit better. Note: the plugin generates one atlas per mesh as of now.
