### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by Redcroft** [armory3d/armorpaint#261]
Pop_os 19.10, latest git version

I've cloned the repo recursively and have all the build deps installed but unable to compile Armorpaint.

redsith@poseidon:~/.git$ git clone --recursive https://github.com/armory3d/armorpaint
Cloning into 'armorpaint'...
remote: Enumerating objects: 338, done.
remote: Counting objects: 100% (338/338), done.
remote: Compressing objects: 100% (221/221), done.
remote: Total 8735 (delta 168), reused 249 (delta 117), pack-reused 8397
Receiving objects: 100% (8735/8735), 51.02 MiB | 22.30 MiB/s, done.
Resolving deltas: 100% (5704/5704), done.
Submodule 'Kromx' (https://github.com/armory3d/Kromx) registered for path 'Kromx'
Submodule 'Libraries/iron' (https://github.com/armory3d/iron) registered for path 'Libraries/iron'
Submodule 'Libraries/zui' (https://github.com/armory3d/zui) registered for path 'Libraries/zui'
Cloning into '/home/redsith/.git/armorpaint/Kromx'...
remote: Enumerating objects: 59, done.        
remote: Counting objects: 100% (59/59), done.        
remote: Compressing objects: 100% (38/38), done.        
remote: Total 4531 (delta 17), reused 45 (delta 6), pack-reused 4472        
Receiving objects: 100% (4531/4531), 175.53 MiB | 30.13 MiB/s, done.
Resolving deltas: 100% (2617/2617), done.
Cloning into '/home/redsith/.git/armorpaint/Libraries/iron'...
remote: Enumerating objects: 67, done.        
remote: Counting objects: 100% (67/67), done.        
remote: Compressing objects: 100% (33/33), done.        
remote: Total 7554 (delta 35), reused 52 (delta 23), pack-reused 7487        
Receiving objects: 100% (7554/7554), 1.74 MiB | 3.47 MiB/s, done.
Resolving deltas: 100% (5220/5220), done.
Cloning into '/home/redsith/.git/armorpaint/Libraries/zui'...
remote: Enumerating objects: 172, done.        
remote: Counting objects: 100% (172/172), done.        
remote: Compressing objects: 100% (76/76), done.        
remote: Total 3120 (delta 91), reused 131 (delta 62), pack-reused 2948        
Receiving objects: 100% (3120/3120), 2.26 MiB | 4.12 MiB/s, done.
Resolving deltas: 100% (1844/1844), done.
Submodule path 'Kromx': checked out 'b04476c602ec38f7b658ab2b65822da0185bdc03'
Submodule 'Kinc' (https://github.com/armory3d/Kinc) registered for path 'Kromx/Kinc'
Cloning into '/home/redsith/.git/armorpaint/Kromx/Kinc'...
remote: Enumerating objects: 26, done.        
remote: Counting objects: 100% (26/26), done.        
remote: Compressing objects: 100% (20/20), done.        
remote: Total 27466 (delta 9), reused 20 (delta 6), pack-reused 27440        
Receiving objects: 100% (27466/27466), 14.56 MiB | 14.50 MiB/s, done.
Resolving deltas: 100% (15322/15322), done.
Submodule path 'Kromx/Kinc': checked out 'ce90062878847b56be59325e77c50b8099d6e335'
Submodule 'Tools/kincmake' (https://github.com/armory3d/kincmake.git) registered for path 'Kromx/Kinc/Tools/kincmake'
Submodule 'Tools/kraffiti' (https://github.com/armory3d/kraffiti_bin.git) registered for path 'Kromx/Kinc/Tools/kraffiti'
Submodule 'Tools/krafix' (https://github.com/armory3d/krafix_bin.git) registered for path 'Kromx/Kinc/Tools/krafix'
Cloning into '/home/redsith/.git/armorpaint/Kromx/Kinc/Tools/kincmake'...
remote: Enumerating objects: 194, done.        
remote: Counting objects: 100% (194/194), done.        
remote: Compressing objects: 100% (152/152), done.        
remote: Total 6924 (delta 72), reused 125 (delta 35), pack-reused 6730        
Receiving objects: 100% (6924/6924), 4.76 MiB | 6.67 MiB/s, done.
Resolving deltas: 100% (3578/3578), done.
Cloning into '/home/redsith/.git/armorpaint/Kromx/Kinc/Tools/kraffiti'...
remote: Enumerating objects: 13, done.        
remote: Counting objects: 100% (13/13), done.        
remote: Compressing objects: 100% (12/12), done.        
remote: Total 13 (delta 2), reused 7 (delta 1), pack-reused 0        
Cloning into '/home/redsith/.git/armorpaint/Kromx/Kinc/Tools/krafix'...
remote: Enumerating objects: 9, done.        
remote: Counting objects: 100% (9/9), done.        
remote: Compressing objects: 100% (9/9), done.        
remote: Total 9 (delta 0), reused 5 (delta 0), pack-reused 0        
Submodule path 'Kromx/Kinc/Tools/kincmake': checked out '20c826a2203d5de406a5584ed0d3f7af34fecb60'
Submodule path 'Kromx/Kinc/Tools/kraffiti': checked out '1402c08e1628181d0ed6357db78691a37b3a8cdf'
remote: Enumerating objects: 484, done.
remote: Counting objects: 100% (484/484), done.
remote: Compressing objects: 100% (213/213), done.
remote: Total 477 (delta 262), reused 476 (delta 261), pack-reused 0
Receiving objects: 100% (477/477), 67.95 MiB | 25.74 MiB/s, done.
Resolving deltas: 100% (262/262), completed with 1 local object.
From https://github.com/armory3d/krafix_bin
 * branch            5a2dc7d376bf5aef638a6d4561d0d2094ed74a75 -> FETCH_HEAD
Submodule path 'Kromx/Kinc/Tools/krafix': checked out '5a2dc7d376bf5aef638a6d4561d0d2094ed74a75'
Submodule path 'Libraries/iron': checked out '0a56ce95dcef4efae5059d9c9f841bf667717ea1'
Submodule path 'Libraries/zui': checked out '996d307b26c136e8f619717ffd8366aec79e1e2e'
redsith@poseidon:~/.git$ cd armorpaint
redsith@poseidon:~/.git/armorpaint$ node Kromx/make -g opengl
Using Kha from /home/redsith/.git/armorpaint/Kromx
Creating Kha project.
/home/redsith/.git/armorpaint/Kromx/Sources/kha/graphics4/Graphics2.hx:1080: characters 43-61 : Class<kha.Shaders> has no field painter_image_frag
/home/redsith/.git/armorpaint/Kromx/Sources/kha/graphics4/Graphics2.hx:1081: characters 41-59 : Class<kha.Shaders> has no field painter_image_vert
/home/redsith/.git/armorpaint/Kromx/Sources/kha/graphics4/Graphics2.hx:1099: characters 43-63 : Class<kha.Shaders> has no field painter_colored_frag
/home/redsith/.git/armorpaint/Kromx/Sources/kha/graphics4/Graphics2.hx:1100: characters 41-61 : Class<kha.Shaders> has no field painter_colored_vert
/home/redsith/.git/armorpaint/Kromx/Sources/kha/graphics4/Graphics2.hx:1119: characters 43-60 : Class<kha.Shaders> has no field painter_text_frag
/home/redsith/.git/armorpaint/Kromx/Sources/kha/graphics4/Graphics2.hx:1120: characters 41-58 : Class<kha.Shaders> has no field painter_text_vert
/home/redsith/.git/armorpaint/Kromx/Sources/kha/graphics4/Graphics2.hx:744: characters 43-61 : Class<kha.Shaders> has no field painter_video_frag
/home/redsith/.git/armorpaint/Kromx/Sources/kha/graphics4/Graphics2.hx:745: characters 41-59 : Class<kha.Shaders> has no field painter_video_vert

Haxe compiler error.

Not sure what ive done wrong, but i've tried to init submodules and pull again but still complaints about no fields

Thanks

**Comment by luboslenco** [comment]
Thanks for report - nothing wrong on your side. I checked it out now and it appears to be caused by `.` character in path, ie. `~/.git`. If you move it out to a different path with no `.` then it should pass.

(The issue with `.` likely related to https://github.com/Kode/khamake/issues/93)
