### ISSUE TITLE
export textures not opening up

### ISSUE THREAD

**Issue by Calpal3D** [armory3d/armorpaint#262]
using windows 10 and armor paint 8.

I tried to export my textures and when i press export textures there's a lot of flashing. A window tries to pop up but ultimately nothing happens. Any ideas what might be happening?

**Comment by luboslenco** [comment]
Likely related to those path issues - pushed new 0.8 dev builds, please let me know at https://github.com/armory3d/armorpaint/issues/257#issuecomment-575211253.
