### ISSUE TITLE
UI glitches if the UI Scale is set to larger than 1

### ISSUE THREAD

**Issue by Wasabi-Cheetah** [armory3d/armorpaint#263]
*ArmorPaint 0.8-62c9bca, Linux*

**Comment by luboslenco** [comment]
Hm not sure I am seeing it here. Can you please share screenshot? Which graphics card?

**Comment by Wasabi-Cheetah** [comment]
I have an NVidia Geforce 830m. (which btw much props for making a really awesome program that runs on low specs unlike Substance Painter :P)

So the glitch seems to only happen in fullscreen, and in scale 1.2, that's the only scale I'm familiar with that does that glitching/stuttering.

![ArmorPaint UI Glitch](https://user-images.githubusercontent.com/45925149/72671917-cfe00000-3a06-11ea-8b0e-3cfa488bd4c3.gif)

**Comment by luboslenco** [comment]
Fixed in latest 0.8 development builds - it was basically the scrollbar popping in and out in some cases. Thanks for report!

**Comment by Wasabi-Cheetah** [comment]
awesome!!! glad to help :D
