### ISSUE TITLE
DAE File Support

### ISSUE THREAD

**Issue by RadioactiveBullfrog** [armory3d/armorpaint#264]
I would love to see support for DAE files (import and export) in this program.

**Comment by ssnd292** [comment]
A DAE file importer is very much needed since it's one of the file formats the Blender Crew heavily invests time into.

**Comment by luboslenco** [comment]
Decided to focus more on gltf and usd ([blender link](https://docs.blender.org/manual/en/latest/files/import_export/usd.html)) formats for now, sorry. If someone decides to develop a dae plugin I will still be glad to help with that!

**Comment by RadioactiveBullfrog** [comment]
That is frankly a terrible idea. DAE is a long-running industry standard and it is foolish to discount it so flippantly. At least be kind enough to leave the issue open and revisit it in the future as opposed to completely discounting the possibility.

**Comment by ssnd292** [comment]
Phew, closing this ticket with a focus on more blender-related file formats is a decision I dont support. ....

And that comes from someone who uses Blender daily.

**Comment by RadioactiveBullfrog** [comment]
This is not a good decision. Focus on industry standards please.
