### ISSUE TITLE
ArmorPaint to Remember Which Monitor It Was Closed On

### ISSUE THREAD

**Issue by ArgentArts** [armory3d/armorpaint#266]
Hello. Love ArmorPaint and excited to see where you take it! Thank you for creating it!

I would love if ArmorPaint would remember which monitor it was closed on so it would open on that monitor the next time I started it. I use it on a interactive pen display (like a Wacom Cintiq) to paint, which is Monitor 2. Every time I open ArmorPaint it opens on Monitor 1. So, it would be nice if it could recall the monitor it was closed on, and open there. 

Thanks.

**Comment by luboslenco** [comment]
Hi, many thanks for posting! Which operating system are you on?

**Comment by ArgentArts** [comment]
Windows 10 with all updates.

**Comment by luboslenco** [comment]
Oh no, it should already work like that on Windows. If you resize the ArmorPaint window, then close it and re-open, does it remember the window size? (Both size and position should be stored.)

Does the file `ArmorPaint\data\config.arm` exists?

**Comment by ArgentArts** [comment]
config.arm is not in that folder. So, that must be the issue. Does it matter where I placed the ArmorPaint folder? I've been sticking it in C:\Program Files so it's with most of my other installed software. I believe that previous versions of ArmorPaint remembered to be full-screen or not. But this version does not. It always opens on Monitor 1 windowed.

Just to be sure, I tried moving it again to Monitor 2, maximized it, shut it down, and started it again. It opened on Monitor 1 windowed. And, again, no config.arm file.

**Comment by luboslenco** [comment]
Fixed in latest 0.8 development builds, will now remember window position even when placed in `C:\Program Files`. 🙂

**Comment by ArgentArts** [comment]
Works perfectly now! Thanks! :)

**Comment by luboslenco** [comment]
Awesome, thanks for letting me know!
