### ISSUE TITLE
Better materials organization and workflow options from imported Blender object

### ISSUE THREAD

**Issue by Marke747** [armory3d/armorpaint#267]
v0.7, win10, ndivia gtx1080

The ability to select and paint mesh-parts that are organized by materials in Armor Paint (that were assigned in Blender) needs to give users a better range of choices and options to help optimize painting/material assignment in Armor Paint.

To repro: 
In Blender, create 2-3 objects. Create 3-4 different materials. Assign to these materials to random parts across the 3 objects. Choose the 3 objects, then export them as an object (with selected and materials option checked on). Import obj into APaint.  The 3 objects display correctly. 

THE BUG: 
1) Then, look at the top-most right drop down list of available materials. Instead of seeing a list of just 3 materials, (because I only used 3 materials in blender) I see a long list of materials repeated, corresponding to the number of times each material was used in Blender. 
2) Also, if we accept that a list is as designed, then clicking/choosing one of the multiple listings (in the drop down list) does not act like a filter to then display only that selected material-mesh object in the viewport. So what's the purpose of the multiple listing them? 

To fix:
Give the user 2 options to select by-materials to help organize paint work and make that operation faster.
Option 1:  Group and display all mesh parts that have 1 material assigned to them in the viewport. In this way I can, as an example, assign "Steel" to parts of objects in Blender that all have steel material. Then in Armor Paint, I just select Steel from the drop down, and I should see all steel-material assigned parts in the viewport. then I can very quickly paint-bucket "steel material" I create in Armor Paint onto to all those mesh parts in the viewport in 1 quick step.
Option 2:  Group all steel material parts assigned, but subdisplay all mesh objects individually in the drop down that have that material assignment (as it does today)  BUT then if I click one (or multiselect) of those entry/ies, then I should only see that 1 (or as many multi selected) object's in the viewport. This would enable me to paint as an example, some Steel material parts as "metal=1" and some like brushed steel "Metal=.5, Rough=.5". This would be good because then I could do basic steel material assignments to all parts in Blender, instead of assigning shiney steel to some parts and brushed steel to other parts.. that fine tuning of material-level painting should all be done in Armor Paint   
![bug](https://user-images.githubusercontent.com/60196687/72931426-b09ce780-3d12-11ea-801f-9e5c7de57510.PNG)

**Comment by luboslenco** [comment]
Materials are merged into single entry now https://github.com/armory3d/armorpaint/commit/b6f33c7052d503244ca4833722531efccce533ff, thanks for report!
