### ISSUE TITLE
Emissive map feature

### ISSUE THREAD

**Issue by therev123** [armory3d/armorpaint#268]
Hi, it could be awsome to be able to create(or paint) emissives part on our assets and to be able to get an single emissive map at the end of exporting step. Sorry for my bad english.

**Comment by luboslenco** [comment]
Hi, exporting emissive map is now possible by adding it to the exporter preset (`Export Textures... - Presets`):

![1a](https://user-images.githubusercontent.com/3685704/77119606-18339280-6a37-11ea-99a3-38058f52bfa5.PNG)


For improved emission display, enabling `Preferences... - Viewport - Bloom` can help.

**Comment by therev123** [comment]
Thank :)

**Comment by RuanLucasGD** [comment]
@luboslenco I went to test the emission, but the image is always exported as black:

![image](https://user-images.githubusercontent.com/79365912/147369133-75309de2-3f23-4484-b839-eff9f303723d.png)
![image](https://user-images.githubusercontent.com/79365912/147369147-0e7a30fb-412e-4c64-ae8e-93b7087b92d9.png)

[maps.zip](https://github.com/armory3d/armorpaint/files/7775021/maps.zip)
