### ISSUE TITLE
Brush radius incremental increase/decrease option

### ISSUE THREAD

**Issue by harsan81** [armory3d/armorpaint#269]
Hello, is there a hotkey or option to increase/decrease the brush radius incrementally like in 2D painting software? the usual hotkey is [ to increase and ] to decrease. Thank you.

**Comment by luboslenco** [comment]
Hi, I have added [ and ] hotkeys to increase/decrease brush radius in the latest 0.8 development builds. The increment step is fixed at 0.1 for now, will eventually make that configurable as well.

**Comment by harsan81** [comment]
That's great! Thank you very much!
