### ISSUE TITLE
Textures changed when opening a saved project on macOS

### ISSUE THREAD

**Issue by eivber** [armory3d/armorpaint#270]
ArmorPaint 0.7
MacOS 10.13.6

The textures got somewhat messed up.
I started a project and applied a couple of textures to it and saved the project to a file.
Came back to work on it the next day and opened the project file and the textures was all looking strange.
I had one wall with a brick texture, this material also got the files shuffled around a bit,
Base color got replaced by a displacement texture.
Roughness got replaced by a base color for an other texture collection (plaster, not bricks)
Normal Map got replaced by a roughness texture

The model was textured using ColorID, a color was selected and then applied a texture to that area using Fill tool.

Top picture shows messy textures and a material node setup with shuffled texture files.
Bottom picture just shows the colorID.

![messedup](https://user-images.githubusercontent.com/25989867/73110923-814fcb80-3f08-11ea-8f14-2b2efb4cd8e6.png)

![messedup2](https://user-images.githubusercontent.com/25989867/73110559-1c47a600-3f07-11ea-83f5-deb1203070a6.png)

**Comment by luboslenco** [comment]
Thanks for report - any luck using the latest 0.8dev builds?
