### ISSUE TITLE
Freeze after changing keymaps

### ISSUE THREAD

**Issue by Zulfiqarib** [armory3d/armorpaint#271]
Hi , 

 I have tried compiling and running on two different systems. 

 1 ) one on the intel / nvidia only runs in local debugger mode but not with krom.exe

 2)  one on the AMD CPU / GPU doesn't not work even with local debugger mode.  This system is in 
     dual boot mode Windows 10  / Lubuntu. It runs on the AMD CPU / GPU in linux.

  In windows I am using Visual studio 2019 Community.

Help Appreciated. 

Rgds.

Zulfikar

**Comment by luboslenco** [comment]
Hi,
1) You need to copy krom binary to the working directory (notice the `Set Project - Properties - Debugging - Command Arguments to ..\..\build\krom` build step)
2) Can you paste the crash / stack trace from visual studio?

**Comment by Zulfiqarib** [comment]
Hi,

 I have copied the binary too but it doesn't work , and sorry i am not a programmer , how do i get the crash / stack trace ?

**Comment by Zulfiqarib** [comment]
Hi,

 redownloaded the source and ran it again and now the exe is working :). if any issues i will report.

**Comment by Zulfiqarib** [comment]
I have one issue when i run the .exe on the laptop , it completely freezes the system for a few minutes, I am not sure but i think it happened after i changed the keymap to blender , but even after changing it to default it's the same.

**Comment by luboslenco** [comment]
Sorry I am not sure I follow, when does it freeze (since you are able to change keymaps)? I assume the OS is Windows 10? Which ArmorPaint version? What GPU?

**Comment by Zulfiqarib** [comment]
Hi Lubo,

  It freezes when i run krom.exe.

 Yes the OS is windows 10 .

 CPU is an i5 2430m
 
 GPU is GT525m 2GB.

> Sorry I am not sure I follow, when does it freeze (since you are able to change keymaps)? I assume the OS is Windows 10? Which ArmorPaint version? What GPU?

**Comment by luboslenco** [comment]
I guess the best way to see what is going on is to compile directly on the system and check where exactly does it freeze in Visual Studio. If the whole system freezes (which no program should be able to do), then maybe something gpu related?

**Comment by Zulfiqarib** [comment]
> I guess the best way to see what is going on is to compile directly on the system and check where exactly does it freeze in Visual Studio. If the whole system freezes (which no program should be able to do), then maybe something gpu related?

It does not freeze when compiling. It's compiled on this same system.

I will check if there are any issues on the gpu. will also update the drivers. 

Will report.

**Comment by luboslenco** [comment]
Yes but make sure to run it from Visual Studio - do not run the .exe directly. Visual Studio should let you see details on what's wrong.

**Comment by Zulfiqarib** [comment]
Ok will do

**Comment by Zulfiqarib** [comment]
Just tried by running local windows debugger and it made my system go crazy for almost 5 mins. 
 
I had a armor paint profile in the nvidia panel , going to remove that check again.

**Comment by Zulfiqarib** [comment]
Well it still behaves the same, if i run it through VS it literally makes the system become unstable for 5 mins.

 Removed the nvidia profile but still the same.

 It was working fine , don't know what went wrong.

**Comment by Zulfiqarib** [comment]
It's working now.

**Comment by luboslenco** [comment]
Sweet! How did you fix it?

**Comment by Zulfiqarib** [comment]
> Sweet! How did you fix it?

honestly i don't know , but it could be the nvidia profile that i had , also deleted the whole source and downloaded and compiled.

BTW this works for  X-plane PBR ?

**Comment by luboslenco** [comment]
Aha, I see. There is an export preset for x-plane already included, but I learned it's not fully correct yet - still have to look into it.

**Comment by Zulfiqarib** [comment]
> Aha, I see. There is an export preset for x-plane already included, but I learned it's not fully correct yet - still have to look into it.

Cool , would be great if it was corrected.

**Comment by Zulfiqarib** [comment]
Hi Lubo,

 Does the paid version have the correct X-plane PBR ?
