### ISSUE TITLE
ArmorPaint's Future

### ISSUE THREAD

**Issue by therev123** [armory3d/armorpaint#273]
Hi, It could be usefull to know more about what ArmorPaint can do and what it can't. As i saw, ArmorPaint work diffrent way than other popular pbr painting software like Substance Painter. Many people here asking to know how to do some specific thing that SubstancePainter can do. I have no experiences about PBR painting, I have some skill about the PBR concept and what it looking for. Also, It could be a great point to give us more learning and asset ressources web link that can be usefull for ArmorPaint community and also reduce no answer issue, feature purpose and question here. If you have questions, that will be an pleasure for to answer them :) . Have good day!

**Comment by luboslenco** [comment]
Hi,

To learn what features are implemented it's best to quickly search through the manual:
https://armorpaint.org/manual.html

It's also perfectly fine to post a question here or open a feature request when something is missing. I want to encourage increasing the number of tickets / posts, not reducing. 🙂 

Apart from manual there are short clips showing specific functionality now with more to come:
https://armorpaint.org/howto.html

To see which features are likely to be implemented next, see:
https://github.com/armory3d/armorpaint/projects

Hope that helps! 🙂

**Comment by therev123** [comment]
I never saw previously the "How-to" section on the web. Thank you very much for the info :D 
I am satisfy  to paid 20$ for this software. Nice work

**Comment by luboslenco** [comment]
Yay! Many thanks for support - more updates soon. 🔨
