### ISSUE TITLE
Use picker to sample colours for Brush/Palette 

### ISSUE THREAD

**Issue by OtherRealms** [armory3d/armorpaint#275]
Currently the Picker only displays RGB values but really should drive the brush colour. The issue here is  which RGB node would it modify? My feeling is that Armor Paint needs a palette system. Sampled colours go to a global palette and can be added to any material via palette node rather than RGB node. Or perhaps it is an extension of the existing RGB node. Thanks.

**Comment by ArieLeo** [comment]
Having a global palette system and RGB color picker would be very usefull for classic/stylistic texture painting.
Having a global palette and color picker that could work outside of the material node would be an awesome addition

**Comment by luboslenco** [comment]
Thanks for the suggestion - pushed some improvements now.

- Added new `Swatches tab`
- `Picker tool` can be used to pick active swatch color (or double-click the color to edit by hand)
- Swatch colors can be drag and dropped into material node editor
- `Picker material node` can be used to drive the brush color via `Picker tool` / active swatch color

![cap](https://user-images.githubusercontent.com/3685704/106360974-b82a9f80-631b-11eb-8942-ee2a4065d1a2.png)
