### ISSUE TITLE
Clear layer

### ISSUE THREAD

**Issue by OtherRealms** [armory3d/armorpaint#276]
It would be great to have the option to clear/empty all of the passes for a paint layer. Additionally a more advanced approach would be an eraser option to 'clean' the picked sub object or connected mesh

![Erase](https://user-images.githubusercontent.com/58406975/73417498-5d5b1280-436c-11ea-9533-c13adfaab7b5.JPG)
.
Thanks.

**Comment by luboslenco** [comment]
A new `Clear` option is now available for both layer and mask in the context / right-click menu. Sub object option coming at https://github.com/armory3d/armorpaint/issues/381.
