### ISSUE TITLE
Layer blending not as expected

### ISSUE THREAD

**Issue by OtherRealms** [armory3d/armorpaint#278]
V0.8 Windows 2020.01.28
Lets say we want to add skin normal detail to a separate layer to the skin colour. It should be a matter of f making a bump layer by turning off Base Color. However it appears the the pass toggles only affect the visibility of passes when the layer is selected not its contribution to the final render/exported textures. Furthermore disabling Base Color will not reveal the layer beneath making the toggle fairly useless. Cheers.

![layer blendingA](https://user-images.githubusercontent.com/58406975/73419182-46b7ba00-4372-11ea-85dc-b4ee6e3802be.JPG)
![layer blendingB](https://user-images.githubusercontent.com/58406975/73419185-491a1400-4372-11ea-8933-e59990e90e90.JPG)

**Comment by ArieLeo** [comment]
A fix for this issue are merged to master 4 days ago, 
![image](https://user-images.githubusercontent.com/6450517/74083416-b9c1de80-4a9e-11ea-8ee1-000d73234115.png)
