### ISSUE TITLE
Changing size with "F"-Key extremely sensitive (with Pen)

### ISSUE THREAD

**Issue by Braindrain85** [armory3d/armorpaint#279]
Hey there,

I just got ArmorPaint and it seems quite decent so far. However when I hold the F-Key and move my pen for changing my brush size, the cursor first resets to a very small size, then responds not at all (for the first few millimeters) and finally responds extremely sensitive. So it is impossible for me to use this shortcut with a graphics tablet. 
With the mouse the brush size change works buttery smooth. But since I don't use the mouse for drawing, this is not an option.

OS: Windows 10
Tablet: Wacom One Medium
GPU: GTX 1070
ArmorPaint Version: 0.8 (2020-01-28)

**Comment by OtherRealms** [comment]
Issue also mentioned here:
[https://github.com/armory3d/armorpaint/issues/90#issue-430097151]

**Comment by luboslenco** [comment]
Hi, thanks for reporting this. I have pushed some improvements into the latest 0.8dev builds. Scaling brush size with a pen should be smooth now. It will not lock the pointer in place but atleast it should be usable.

**Comment by Braindrain85** [comment]
Thank you for looking into it! 
Now it at least works when I have "Windows Ink" enabled. Unfortunately this brings back the annoying "press and hold"-circles for me. In case anyone has the same problem, I disabled them with this tutorial: http://www.creativewithjaakko.com/2017/07/20/disable-wacom-circle-in-photoshop-cc-windows-10/
