### ISSUE TITLE
Constant crashing 

### ISSUE THREAD

**Issue by DreamsOf3DSpace** [armory3d/armorpaint#280]
Hi, guys, I'm hoping somebody can help me fix this.

I keep getting this just from importing textures
![image](https://user-images.githubusercontent.com/59645217/73599452-7ebe2900-453b-11ea-8eb7-8d329c2af958.png)

Sometimes it doesn't hate the textures so much but then crashes when I plug them in, although it seems to display everything fine until it crashes.
![image](https://user-images.githubusercontent.com/59645217/73599549-b4afdd00-453c-11ea-975c-ca7de9fd7edc.png)

I'm guessing it's more of a hardware problem than a bug but it's so close to working it's frustrating :(
![image](https://user-images.githubusercontent.com/59645217/73599715-5e439e00-453e-11ea-8fda-bc52334ea1a1.png)

A .txt file appeared with errors saying "TypeError: Cannot read property 'hxBytes' of undefined" but I have no idea what this means, I'm just an artist.

Also I'm using the latest "ArmorPaint_08dev_win64" version.

**Comment by luboslenco** [comment]
Hi!
- Which Windows version are you on? Latest 10?
- What graphics card?
- Any difference if you check the "ArmorPaint_07_win64" version?
- Do models import properly?
