### ISSUE TITLE
Udim problem

### ISSUE THREAD

**Issue by Rozwan** [armory3d/armorpaint#282]
I've used armor paint 0.7 and 0.8DXR and udims are like this :

![image](https://user-images.githubusercontent.com/51855978/73606024-4277e080-45ae-11ea-9300-e9c632f586fd.png)

And I imported it with split by udim

**Comment by luboslenco** [comment]
Hello, you need to select which udim tile to paint on, see:
https://www.youtube.com/watch?v=cASoidrJdJc&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=16

Afterwards, during texture export, each udim tile will get exported as a separate texture. Will eventually enable painting across multiple udim tiles. Hope that helps!

**Comment by Rozwan** [comment]
So right now I can't paint across all udims like in blender 2.82 :(

**Comment by luboslenco** [comment]
Sorry not yet - needs some thinking to manage all the udim tiles on the gpu and I do not want to tank the performance. Should be ready in v1.0.

**Comment by J-MG21** [comment]
Is the problem fixed? Because I still have this problem when I bake
