### ISSUE TITLE
File Import not working as intended

### ISSUE THREAD

**Issue by ssnd292** [armory3d/armorpaint#283]
Hey Lubos - I just downloaded the latest 0.8 version - but it seems that the import is broken. When I import any sort of mesh, doesnt matter if obj, fbx or blend - nothing happens. Only way to actually import is by drag-n-drop.

Version is latest ArmorPaint_08dev_win64

**Comment by luboslenco** [comment]
Hey! Sadly it seems to work like usual here. 🙁 Do textures or other asset types import ok for you? Is it just model import acting up?

**Comment by ssnd292** [comment]
Hey Lubos, I attached a video

https://streamable.com/c3dha

Texture import works fine.

**Comment by luboslenco** [comment]
Aha, it looks like the import popup gets immediately canceled, should be able to fix that. 🔨

**Comment by luboslenco** [comment]
Hopefully resolved now in the latest 0.8dev builds.
