### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armorpaint#284]
Hey lubos i dont think this is the right place(sorry) but do you plan to submit armorpaint and armory to epic megagrant?

**Comment by LukeSeers** [comment]
Sadly I doubt that Epic would be interested in ArmorPaint since they just pretty much backed Mixer

**Comment by Xristoskr** [comment]
I dont think this is an issue.Epic fund godot so...

**Comment by luboslenco** [comment]
Thanks for the suggestion, no prob at all to post questions here as well. Applied a while back - not sure what are the chances but will post an update if I hear back. 🙂

**Comment by luboslenco** [comment]
Whoa, did hear back from Epic actually!
https://twitter.com/luboslenco/status/1232325217319563264

**Comment by Xristoskr** [comment]
Wow awesome news

Στις Τρί, 25 Φεβ 2020, 18:46 ο χρήστης Lubos Lenco <notifications@github.com>
έγραψε:
