### ISSUE TITLE
CTD when Opening

### ISSUE THREAD

**Issue by Ulazygit** [armory3d/armorpaint#286]
Windows 10 
i5-7600K, GTX1070
OpenGL version installed by following this tutorial :https://youtu.be/y6h2KOP47ZY
and using opengl instead of d3d.
Compiling was successful.
App opens for 2 seconds, can't click anything, then CTD with no error dialogue

**Comment by luboslenco** [comment]
Hi, on Windows ArmorPaint needs to be compiled with Direct3D11, check here for always up to date instructions:
https://github.com/armory3d/armorpaint/blob/master/README.md

On Linux, OpenGL will be replaced by Vulkan as well.
