### ISSUE TITLE
Armory necessary?

### ISSUE THREAD

**Issue by Ulazygit** [armory3d/armorpaint#287]
Is armory necessary for armorpaint to run successfully if self built? I followed all of the build steps and compiled the programme in d3d. Unfortunately, clicking on the .exe does nothing and the programme doesn't load.
Win10x64

**Comment by Ulazygit** [comment]
Just some extra info:

'Krom.exe' (Win32): Loaded 'E:\Program Files (x86)\armor\armorpaint\Kromx\build\x64\Release\Krom.exe'. Symbols loaded.
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\D3DCompiler_47.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dinput8.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. 
'Krom.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'Krom.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\umpdc.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\DXCore.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dbghelp.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\InputHost.dll'. 
Could not load krom.js, aborting.
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. 
The thread 0x19b0 has exited with code 1 (0x1).
The thread 0x33dc has exited with code 1 (0x1).
The thread 0x1f54 has exited with code 1 (0x1).
The thread 0x2c1c has exited with code 1 (0x1).
The program '[10612] Krom.exe' has exited with code 1 (0x1).

**Comment by luboslenco** [comment]
... if anyone stumbles upon this:

> Could not load krom.js, aborting.

means the working directory has not been set properly:

> Set `Project - Properties - Debugging - Command Arguments` to `..\..\build\krom`
