### ISSUE TITLE
Multi project support

### ISSUE THREAD

**Issue by therev123** [armory3d/armorpaint#289]
Hi! ArmorPaint seem to be not able to run more than one project on the same instance. I don't know if an feature is planed to come soon, but it be an good thing to check this :)

**Comment by luboslenco** [comment]
Hi, can you elaborate? You mean like opening multiple instances of ArmorPaint? Which operating system are you on?

**Comment by therev123** [comment]
I mean that when you working on a saved project and you open an other project, AmorPaint crash. Am i  clear? Sory again for my bad english, i will try to be more clear next time :)

**Comment by luboslenco** [comment]
Let me know if this still happens in latest 0.8 development builds. :) If so then steps and OS to reproduce would be very helpful.
