### ISSUE TITLE
Creating material node from search bar resulting multiple nodes created

### ISSUE THREAD

**Issue by ArieLeo** [armory3d/armorpaint#291]
On v 0.8, When creating a new material nodes from search popup it's not creating only one node but multiple nodes are created instead. This is only happened when using search bar, when creating node from the menu it's works just fine.
See attached gif
![CreateNodeFromSearch](https://user-images.githubusercontent.com/6450517/74084597-99e4e780-4aab-11ea-895c-21964c792feb.gif)

**Comment by luboslenco** [comment]
Please make sure to keep `Preferences - Viewport - VSync` enabled for now (requires program restart to take effect), that will fix those. 🙂
