### ISSUE TITLE
Popup Menu Locking the UI

### ISSUE THREAD

**Issue by ArieLeo** [armory3d/armorpaint#292]
On ArmorPaint v0.8, Windows 10
When there's a popup menu opened, it locked the ui, i cannot click anything unless i press escape key. Usually popup menu should be closed when we click outside the area of the menu.
Locking happened on almost every popup menu, except the create nodes menu on top of the material editor.
I hope the gif are clear enough, not sure how to show mouse click on gif
![PopupMenuLock](https://user-images.githubusercontent.com/6450517/74084709-8a19d300-4aac-11ea-9be8-c13a0de153e7.gif)

**Comment by luboslenco** [comment]
See https://github.com/armory3d/armorpaint/issues/291#issuecomment-583756289.
