### ISSUE TITLE
Normal Map Node

### ISSUE THREAD

**Issue by ArieLeo** [armory3d/armorpaint#293]
Any chance we can get Normal Map node in Armor Paint,
![image](https://user-images.githubusercontent.com/6450517/74084972-44aad500-4aaf-11ea-8a67-ce60652ecdb3.png)

Having this node we can increase/reduce the intensity of the normal map, also having the ability to use different normal map (TangentSpace, ObjectSpace, WorldSpace)

**Comment by unfa** [comment]
Yeah, is there a way to use an externally baked normal map?

**Comment by luboslenco** [comment]
`Normal Map` node is now available thanks to @MathemanFlo! It can be used to alter the normal map strength. Only tangent space maps are implemented for now.
