### ISSUE TITLE
Node editor: Mouse clicks interact with multiple overlapping nodes

### ISSUE THREAD

**Issue by Banbury** [armory3d/armorpaint#296]
Armorpaint version: master ade717c95614e57ea9d207f3369bc8e93334f92a
OS: Windows

In the node editor create several nodes and overlap them (color nodes work well). If you click on the top most node, all the other nodes are changed, too.
Mouse clicks should be caught by the top most node. All other nodes should ignore events, that are already handled.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/zui/commit/044038881cff7cc18dc062879e7719b738cf7fdc. Thanks for report!
