### ISSUE TITLE
Blending preview

### ISSUE THREAD

**Issue by Senmuth** [armory3d/armorpaint#297]
Please add preview of layers blending cause it's awful to open mix menu every time when you tried to find the mix mode what you need.
 And it will be great if you create a bridge with Cinema 4D in feauture.

**Comment by luboslenco** [comment]
When layer blending combo / dropdown is open it can now be changed via arrow up / down keys, which will result in immediate preview. Thanks for report!  https://github.com/armory3d/zui/commit/912570df3ee454570fdaa367b4f17f1bbb21e134 https://github.com/armory3d/armorpaint/commit/dd849fa79eba78ce881a8dfd16b79be29b839dc1
