### ISSUE TITLE
Retopology Feature?

### ISSUE THREAD

**Issue by therev123** [armory3d/armorpaint#298]
Hi! Is there a plan to implement a retopology feature in ArmorPaint? If not, it could be nice to see this feature in the future :)

**Comment by ArieLeo** [comment]
i highly doubt that though, ArmorPaint are well a texture painter/baker app, not a Modeller

**Comment by luboslenco** [comment]
Keeping it all about textures for now to keep focused, want to really get that painting workflow polished. 🙂

**Comment by therev123** [comment]
No problem :)
