### ISSUE TITLE
ArmorPaint Latest Build Will Not Run/Open

### ISSUE THREAD

**Issue by ArgentArts** [armory3d/armorpaint#299]
Hello. I just (today) downloaded an update to ArmorPaint from GumRoad (08dev-win64) and it will not run at all. When I click the EXE file, the cursor cycles for a moment, then nothing. My system is Windows 10 Home, version 1903, OS build 18362.657.

**Comment by bmobius** [comment]
I was just on my way here to open the same issue. I'm getting the exact same result when I try to run the latest ArmorPaint 0.8 build (2-12-2020).

**Comment by luboslenco** [comment]
Hi, many thanks for report. Is there an `stderr.txt` file generated alongside the .exe?

**Comment by bmobius** [comment]
No there is not.

**Comment by luboslenco** [comment]
Hm something to do with the `.exe` itself then. Somehow all seems well here but going to check on another machine. I assume 0.7 build still works ok?

**Comment by bmobius** [comment]
I just discovered that the most recent build works fine in any directory other than C:.

For example, I usually have ArmorPaint installed in C:\Program Files\ArmorPaint. However, the most recent 0.8 version will not run from that location even if I run it "As Administrator".

But I just copied ArmorPaint over to my D: drive and when I ran the .exe, it started right up.

**Comment by ArgentArts** [comment]
That's the exact same for me. I also have ArmorPaint in C:\Program Files\ArmorPaint.  If I copy the folder to my desktop and run the EXE, then ArmorPaint runs perfectly.

**Comment by luboslenco** [comment]
Oh no, that should have already been fixed. Great find, updated builds coming!

**Comment by bmobius** [comment]
Thanks, Lubo! Much love!

**Comment by LiamBester** [comment]
I'm having the same problem, it won't start up at all when i open the software unfortunately.

**Comment by luboslenco** [comment]
@LiamBester did you try the temporary workaround mentioned above? Where is your armorpaint located?

**Comment by luboslenco** [comment]
Updated 0.8 dev builds for Windows - things should be back to normal. 🔨

**Comment by ArgentArts** [comment]
That works for me. Thank you! :)

**Comment by bmobius** [comment]
Thank you, Lubo! The issue is resolved from what I can tell on this new build. ArmorPaint started right up from it's installation on my C: drive. Much love and keep up the great work!

**Comment by therev123** [comment]
Thank you to luboslenco but we must to dont forget everyone behind ArmorPaint :)

**Comment by bmobius** [comment]
I have nothing but love for Lubo and all the developers behind ArmorPaint. The includes everyone working with the AP community!

**Comment by luboslenco** [comment]
😍 👍👍

**Comment by AbdallahFH** [comment]
for some reason I have the same problem here...

**Comment by zzub1** [comment]
i have the same issue,i tried every solution mentioned above but it still won't start,can someone help?
