### ISSUE TITLE
object rotation / mouse movement ratio incorrect in windowed mode [Linux]

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armorpaint#3]
When running the program in non-fullscreen windowed mode on Linux, the object rotation / mouse movement ratio seems not correct, (object rotation is slower than mouse movement, the smaller the screen is, the slower the rotation will be). This is not just ArmorPaint, any game built by Armory also have this problem. (note that I am using 200% scaling mode of Ubuntu 17.10)

/Milo

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/968.
