### ISSUE TITLE
Error Compile v8_monolith.lib

### ISSUE THREAD

**Issue by Toso82** [armory3d/armorpaint#300]
I try to compile ArmorPaint with my Visual Studio 2019 how explain but give this:

Error LNK1104	unbable to open 'v8\libraries\win32\release\v8_monolith.lib'	Krom	D:\githfork\armorpaint\Kromx\build\LINK	1

**Comment by luboslenco** [comment]
..if anyone stumbles upon this then the fix should be:
> Unpack `v8\libraries\win32\release\v8_monolith.7z` using 7-Zip (exceeds 100MB)

**Comment by larinius** [comment]
"v8\libraries\win32\release\v8_monolith.7z" - Unpack and rerun 
"armorcore\Kinc\make --from armorcore -g direct3d11", 
this way project builds ok.
