### ISSUE TITLE
Linux Centos7 AP 0.8

### ISSUE THREAD

**Issue by joshuazt** [armory3d/armorpaint#301]
Hi

Just bought Armor Paint, having issues getting it running on Linux Centos7. My terminal is telling me i am missing a library. 

![Screenshot from 2020-02-18 13-44-51](https://user-images.githubusercontent.com/23189306/74699577-284c2c80-5255-11ea-9c16-8f58919efa66.png)

Would really appreciate some help getting this working. Thanks! :)

**Comment by luboslenco** [comment]
Hi! Did some testing today - you would need Centos8. as glibc version is too old on Centos7. :( Another option is to compile ArmorPaint manually, but the provided clang seems to be old as well, so there may be more issues - happy to assist if I can.

Please drop me an email linked [here](https://armorpaint.org/community.html) for a refund and apologizes for inconvenience.

**Comment by joshuazt** [comment]
> Hi! Did some testing today - you would need Centos8. as glibc version is too old on Centos7. :( Another option is to compile ArmorPaint manually, but the provided clang seems to be old as well, so there may be more issues - happy to assist if I can.
> 
> Please drop me an email linked [here](https://armorpaint.org/community.html) for a refund and apologizes for inconvenience.

Hi Luboslenco, Thanks for the checking this out! :) 

Unfortunately the OS is at the studio I work at and for now upgrading isn't a option. In the near future we maybe, so ill speak to the team and get back to you. 

Thanks again for looking into this.

Josh
