### ISSUE TITLE
Vertex colors

### ISSUE THREAD

**Issue by divineniiquaye** [armory3d/armorpaint#302]
how do i access vertex colors
![image](https://user-images.githubusercontent.com/53147395/74779077-be537780-5294-11ea-85cb-4898bf3ac983.png)

**Comment by divineniiquaye** [comment]
it works in armory3d

**Comment by luboslenco** [comment]
Vertex color data can be imported via .fbx and .blend formats now by enabling `Parse Vertex Colors` option in the import dialog.
