### ISSUE TITLE
Problem Painting Mesh w/ Color ID Map

### ISSUE THREAD

**Issue by SolomonPowell** [armory3d/armorpaint#304]
Windows 10; GTX 1060 3GB; v 0.8 since 2/18/2020

This is the result when I attempt to fill in a plane with a color ID made in blender:

![result2](https://user-images.githubusercontent.com/5898980/74781017-b7197300-526e-11ea-8283-f028d51a6fe6.PNG)

Obviously the border squares with lines and smaller squares are the issue I'm experiencing. Also worth noting that some tools also produce the error, while others do not:
![toolstest](https://user-images.githubusercontent.com/5898980/74782245-14aebf00-5271-11ea-9c53-cc5cb36d81bb.png)

My Vertex Painted Color ID looks like this:
![vertexpaint2](https://user-images.githubusercontent.com/5898980/74781086-dd3f1300-526e-11ea-9de5-b1e84087dc17.PNG)

And my UV Map looks like this:
![uvmap2](https://user-images.githubusercontent.com/5898980/74781119-e9c36b80-526e-11ea-9429-2898e7b50430.PNG)

**Comment by luboslenco** [comment]
Thanks for report, fixed in latest dev builds.
