### ISSUE TITLE
TIF file format support

### ISSUE THREAD

**Issue by martink-unity** [armory3d/armorpaint#305]
TIF / TIFF is a pretty commonly used file format, would be nice to have support for it.

**Comment by luboslenco** [comment]
Hi, you should be able to import TIF images by enabling the `Menu bar - Edit - Preferences... - Plugins - import_tiff` plugin. Once it's enabled, it will stay enabled even for future launches.

Right now plugins are off by default to keep startup times fast, but I want to eventually auto-enable those file import plugins when that file type is imported for the first time. That should make it less obscure. 🙂

**Comment by martink-unity** [comment]
ah nice , thank you :)
