### ISSUE TITLE
live link plugin for unity is broken

### ISSUE THREAD

**Issue by 1abinitio1** [armory3d/armorpaint#306]
**Please specify your ArmorPaint version and OS.**
0.8,windows

the unity live-link plugin, seems to be broken.
looked through the unreal one and found that

the command line arguments for the unreal version are:
"saved_mesh.obj" "path to unreal engine project"

while unitys ones are:
saved_mesh.obj

(unity is missing the "" and the second part)

armor paint should probably be able to accept just a file for command line arguments and work
(not engine specific, and the rest to be handled by a plugin engine side)

**Comment by luboslenco** [comment]
Investigating together with https://github.com/armory3d/armorpaint_unity/issues/2.
