### ISSUE TITLE
Can it be build in visual code studio osx?

### ISSUE THREAD

**Issue by schroef** [armory3d/armorpaint#309]
I was wondering if this also can be build with Visual Code Studio  on OSX?

**Comment by luboslenco** [comment]
Sorry not sure on this one, I recommend to follow the readme for now (which appears to be problematic on it's own on macOS, investigating at https://github.com/armory3d/armorpaint/issues/308 ). 🙂 

With that said, Xcode installation will be still required for compilation. Maybe there is a way to import Xcode project into Visual Studio Code?
