### ISSUE TITLE
crash when resizing window

### ISSUE THREAD

**Issue by kenthinson** [armory3d/armorpaint#31]
Getting a crash with armor paint when trying to resize the window on mac osx.

GL Error 1281 /Users/lubos/Downloads/Krom/Kore/Backends/Graphics4/OpenGL/Sources/Kore/VertexBufferImpl.cpp 207

2018-09-06 19:36:59.395 Krom[1544:26153] -[BasicOpenGLView resize:]: unrecognized selector sent to instance 0x7fd51c52b4b0
2018-09-06 19:36:59.400 Krom[1544:26153] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[BasicOpenGLView resize:]: unrecognized selector sent to instance 0x7fd51c52b4b0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff389712db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5fb18c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff38a09db4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff388e7820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff388e71e8 _CF_forwarding_prep_0 + 120
	5   Krom                                0x000000010c5a3529 Krom + 7120169
	6   CoreFoundation                      0x00007fff38900edc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	7   CoreFoundation                      0x00007fff38900daa _CFXRegistrationPost + 458
	8   CoreFoundation                      0x00007fff38900ae1 ___CFXNotificationPost_block_invoke + 225
	9   CoreFoundation                      0x00007fff388be880 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1664
	10  CoreFoundation                      0x00007fff388bd9b7 _CFXNotificationPost + 599
	11  Foundation                          0x00007fff3a9cd8c7 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	12  AppKit                              0x00007fff35f484db -[NSWindow _setFrameCommon:display:stashSize:] + 3813
	13  AppKit                              0x00007fff35f475e9 -[NSWindow _setFrame:display:allowImplicitAnimation:stashSize:] + 222
	14  AppKit                              0x00007fff35f47504 -[NSWindow setFrame:display:] + 67
	15  AppKit                              0x00007fff3698a3e9 -[NSWindow(NSWindowResizing) _resizeSetFrame:withEvent:] + 124
	16  AppKit                              0x00007fff361b237f -[NSWindow(NSWindowResizing) _resizeWithEvent:] + 3060
	17  AppKit                              0x00007fff366f0422 -[NSTitledFrame attemptResizeWithEvent:] + 177
	18  AppKit                              0x00007fff360bc3dd -[NSThemeFrame handleMouseDown:] + 297
	19  AppKit                              0x00007fff360bc603 -[NSThemeFrame mouseDown:] + 30
	20  AppKit                              0x00007fff367bdd6d -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5891
	21  AppKit                              0x00007fff367ba9c4 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2359
	22  AppKit                              0x00007fff367b9c70 -[NSWindow(NSEventRouting) sendEvent:] + 497
	23  AppKit                              0x00007fff3661b236 -[NSApplication(NSEvent) sendEvent:] + 2462
	24  Krom                                0x000000010c5a28ed Krom + 7117037
	25  Krom                                0x000000010c5a4802 Krom + 7124994
	26  Krom                                0x000000010c5a27ac Krom + 7116716
	27  Krom                                0x000000010c5a4826 Krom + 7125030
	28  Krom                                0x000000010bedd77e Krom + 18302
	29  Krom                                0x000000010c5a3428 Krom + 7119912
	30  Foundation                          0x00007fff3a9f55a0 -[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:modes:] + 1123
	31  Foundation                          0x00007fff3a9f50bf -[NSObject(NSThreadPerformAdditions) performSelectorOnMainThread:withObject:waitUntilDone:] + 131
	32  Krom                                0x000000010c5a318e Krom + 7119246
	33  libdyld.dylib                       0x00007fff60732015 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by luboslenco** [comment]
Fixed at https://github.com/Kode/Kore/commit/ae45ba56da98f044e131bc95a339b97525df1fff by Robert, I updated the `Armory_05_mac` build on itch.io.

I also got that `GL Error 1281`, will fix.:)
