### ISSUE TITLE
How to Build using MsBuild Commandline tool . 

### ISSUE THREAD

**Issue by yudhir** [armory3d/armorpaint#310]
I am getting error .

```
MSBUILD : error MSB1009: Project file does not exist.
Switch: G:\GAMES\Armour_Paint\armorpaint\Kromx\build\Krom.sln

```
when executing " `msbuild G:\GAMES\Armour_Paint\armorpaint\Kromx\build\Krom.sln /t:build /p:'Configuration=Release;Platform=x64' `"

**Comment by luboslenco** [comment]
Sorry not sure on this one, there is too many platforms and setups to keep up so I recommend to follow the readme for now.

If you just want to compile from the command line, run:
`node Kinc/make --compile`

If that works out you could then check [kincmake](https://github.com/Kode/kincmake) sources to see how the `--compile` argument is handled.

Hope that helps!
