### ISSUE TITLE
Take brush hardness / opacity into account when painting mask

### ISSUE THREAD

**Issue by skywalger88** [armory3d/armorpaint#312]
Hello,
I am using v 0.8 from Gumroad

When painting a fill layer mask, the brush setting like hardness and opacity doesn't react. Changing radius works but result radius is bigger then the preview brush radius still.

I am also unable to set anywhere whether to paint black or white into the mask. Or I dunno how to do it.

Or are these things just missing features?

Thanks

**Comment by luboslenco** [comment]
Hello, thanks for report. Opacity and radius issues should be fixed, hardness is not yet working. The color which gets painted onto mask is taken from the active material base color slot.

**Comment by AlexKiryanov** [comment]
Good day! I noticed the same problem! Program version v 0.8 2020-07-08 26094a7

**Comment by dasparadoxon** [comment]
I have the strange problem under windows with 15adaf6 (2020-09-07) that when I use a custom brush that it sometimes uses the brush correctly (opacity) on the mask and sometimes not.

**Comment by sacrish** [comment]
Is there any plan on when this will be fixed? Currently it seems brush alpha does not work at all on masks, making it very difficult to paint height transition with masks.

**Comment by MathemanFlo** [comment]
Having this feature would be really great to paint softer masks.

**Comment by luboslenco** [comment]
All masks should now take hardness into account after https://github.com/armory3d/armorpaint/commit/c849ec4763946705112d2f7e72c4b33883e6197f.

**Comment by AlexKiryanov** [comment]
Good day!! Thank you Lubos very much !!

ср, 23 июн. 2021 г. в 14:11, Lubos Lenco ***@***.***>:
