### ISSUE TITLE
HueSatVal node doesn't work on Vornoi and Noise textures nodes

### ISSUE THREAD

**Issue by skywalger88** [armory3d/armorpaint#313]
Hello,

in Material node editor, when I plug procedural textures like Noise or Vornoi into HueSatVal, the HueSatVal doesn't seem to do anything. It goes the same with Blur node.

**Comment by luboslenco** [comment]
Fixed in latest development builds.

Blur (Image) node will only work with images used for color input but will fix that as well. 🙂
