### ISSUE TITLE
Getting latest builds

### ISSUE THREAD

**Issue by divineniiquaye** [armory3d/armorpaint#314]
How do i get armory paint without having to buy it over and over again
![image](https://user-images.githubusercontent.com/53147395/75446491-6e914200-595f-11ea-83a2-79e82ed092aa.png)

**Comment by divineniiquaye** [comment]
And Congrats on ur Fund Grant, armorpaint is going epiccccccccc we huuuu

**Comment by luboslenco** [comment]
Hi, looks like you are able to download the latest builds based on the attached screenshot? Can you provide more details?

ArmorPaint is available in your [GumRoad library](https://gumroad.com/library) forever, and you can also use the original email sent by GumRoad. You can also check updating section in the [manual](https://armorpaint.org/manual).

**Comment by divineniiquaye** [comment]
@luboslenco Am making a commercial game i wanna use armorpaint so it will be in armorpaints showreel,
i just downloaded it and its the same no vertex bake option and access to vertex colors from nodes
![image](https://user-images.githubusercontent.com/53147395/75448666-8c60a600-5963-11ea-9c25-fb99db9dc7d0.png)

**Comment by luboslenco** [comment]
Sorry there are no vertex colors yet - I will post asap once the feature is implemented at your existing ticket here https://github.com/armory3d/armorpaint/issues/302. 🙂

**Comment by divineniiquaye** [comment]
Ok super cooooooooooooool
