### ISSUE TITLE
Decals and Text applied through mesh

### ISSUE THREAD

**Issue by BioQuake** [armory3d/armorpaint#315]
Working on Windows 10, with Armorpaint v0.8

When applying decals to a model, they appear not only on the side applied to, but also on the other side of the model.
![1](https://user-images.githubusercontent.com/22009334/75633226-73762000-5c03-11ea-8e0d-f49dbe57babc.PNG)
![2](https://user-images.githubusercontent.com/22009334/75633227-740eb680-5c03-11ea-8fcb-ea8501a69ae1.PNG)

**Comment by luboslenco** [comment]
Appears to start occurring as soon as height channel is used/painted in a project, looking for a fix.

**Comment by luboslenco** [comment]
Fixed in latest development builds.
