### ISSUE TITLE
Paint trembling issues

### ISSUE THREAD

**Issue by grihan74** [armory3d/armorpaint#316]
Hi there,
With the current state of cloning brush, it's almost impossible to clone with precision, as every time you pass the brush over the same area you get a different and distorted result.
Can this be improved?
Thanks in advance,
Alberto Moreno

**Comment by luboslenco** [comment]
Marking as a bug, will fix - thanks for report.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/e4914f25b30e4aec970dc591b0fa0ff55598b36d.
