### ISSUE TITLE
OBJ import bug?

### ISSUE THREAD

**Issue by dangerfx** [armory3d/armorpaint#317]
left AP, right Max
obj exported via unreal
![Capture](https://user-images.githubusercontent.com/51142488/75747051-cfb27e80-5d80-11ea-95bd-ec5aab7a668b.JPG)
![Capture1](https://user-images.githubusercontent.com/51142488/75747140-08eaee80-5d81-11ea-9774-c9411632421b.JPG)

**Comment by luboslenco** [comment]
Hi, are you able to share the obj file? I assume it's the same if you export to fbx?
