### ISSUE TITLE
Alpha Channel not baked into textures

### ISSUE THREAD

**Issue by JanLoehr** [armory3d/armorpaint#318]
Hey,
I am trying to export maps for Unity Mixed Reality Toolkit (HoloLens). I want to pack some channels into one texture.

MRTK needs this setup:
![image](https://user-images.githubusercontent.com/11177594/75783628-27d98880-5d61-11ea-9b1e-7cd32810ee09.png)

But the alpha channel (smoothness) is never baked out. It's just empty (1) in the result.

OS: Windows 10
ArmorPoint: 0.8 (2020-02-12) 646b516

Best, Jan

**Comment by luboslenco** [comment]
Thanks for report, fix incoming!

**Comment by luboslenco** [comment]
Fixed now in latest development builds.
