### ISSUE TITLE
type missing armory.math.Vec4

### ISSUE THREAD

**Issue by kenthinson** [armory3d/armorpaint#32]
Getting the following error when trying to compile the project using the latest git version on armory and armorpaint.

/Users/kent/Developer/armorpaint/Sources/arm/logicnode/InputNode.hx:5: characters 7-23 : Type not found : armory.math.Vec4

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/1612c7f234ff2b9174e08fcf02938e17d88df79a.
