### ISSUE TITLE
Hybrid Baker

### ISSUE THREAD

**Issue by therev123** [armory3d/armorpaint#320]
Hi everyone, I would like to purpose something about the baker tools. I think the baker need some core improvement. Some of theirs feature are limited to RTX hardware. Here we have an open source PBR painting software, i think ArmorPaint could bring something that make it different of theirs competitor. I think that armorpaint baking tool need a hybrid implementation(opencl support) for the future, or cpu compute support for every baking feature.  That was my purpose, I don't have a rtx graphic card in my desktop because I hate Nvidia and i think that I'm not alone here in this situation.
Thank for reading, I hope there will be some people vote or comment my post :)
Sorry for my very bad english :(

**Comment by luboslenco** [comment]
Hello! It is possible to implement additional raytracing APIs into ArmorPaint in the future, but I have to be careful on how to spend the development resources. Right now DirectX Raytracing (DXR) is the simplest-to-implement and most-performant way to perform raytracing for a project like ArmorPaint.

If I drop DXR, ArmorPaint will lose access to hardware accelerated raytracing and will most likely run slower in the end compared to programs which do use it.

Most importantly, **DXR is not proprietary to Nvidia** - it's a raytracing API built into DirectX. It's just that only Nvidia provides an implementation on desktop cards as of now via RTX. However, DXR is now confirmed to be available on the new Xbox - which is actually powered by AMD architecture and has nothing to do with Nvidia. It's easy to guess what comes next. 🙂

**Comment by therev123** [comment]
We must keep DXR implementation. That wasn't my intention to purpose to drop it from ArmorPaint. :)
