### ISSUE TITLE
Disabled channels on layers appear in export

### ISSUE THREAD

**Issue by JanLoehr** [armory3d/armorpaint#321]
Heyhey,

As in the first screenshot, I setup a layer for importing an externally generated Occlusion Map. It displays perfectly fine in the viewport.

![image](https://user-images.githubusercontent.com/11177594/76329123-71d7e680-62ec-11ea-95a5-5fe17d911979.png)

But exporting this results in the occlusion color and normal (which aren't filled) overlaying in the base and normal maps.

![image](https://user-images.githubusercontent.com/11177594/76329252-9df36780-62ec-11ea-964c-75a623ba2df2.png)

Best, Jan

OS: Windows 10
Version: 0.8(2020-03-03) - c506d7a

**Comment by luboslenco** [comment]
Also fixed in latest development builds.
