### ISSUE TITLE
Base map blending feature

### ISSUE THREAD

**Issue by therev123** [armory3d/armorpaint#322]
Is there any plan for an 3d model base map(normal, AO, curvature) blending feature?

**Comment by luboslenco** [comment]
If I understand correctly then it should be possible to enable blending via Layers tab.

**Comment by therev123** [comment]
Look at 3min 30s in this video: https://www.youtube.com/watch?v=kRtXIj6ENT4
This is what i talking about base map blending feature

**Comment by therev123** [comment]
This feature was also purpose in this issue: #154 . The good therm is: Texture set. I think this feature should be take in consideration and be implemented soon as possible. When it will be implemented, I think that it will be more easier to implement many request feature like edge wear and other will comming soon. Add this feature ro the "to do" list, and if you want to make this more effecient, "multi texture set" should be take in consideration instead. 
I bought this addon this week: https://blendermarket.com/products/DECALmachine
It could be awesome to be able to do this with armor paint in the future(look at 28m 10s): https://www.youtube.com/watch?v=YCUV8pS7MXQ&t=47s
But for now take multi-texture set in consideration to the "to do" list.
