### ISSUE TITLE
Stencil Support

### ISSUE THREAD

**Issue by ArieLeo** [armory3d/armorpaint#323]
Can we get stencil masking and painting support on armor paint? Similar to blender stencil mask with on screen display for stencil transform (Rotate, Scale, Move, Strength)
https://www.youtube.com/watch?v=ktFY3pcU1lo

**Comment by luboslenco** [comment]
Basic stencil map support is now available in latest development builds. It can be enabled by plugging an image into `Stencil` socket in `Brush Output` node.

Stencil transform can be enabled by holding `ctrl` (or remapped in keymap). Rotation is not yet implemented.

![1a](https://user-images.githubusercontent.com/3685704/77121278-1d92dc00-6a3b-11ea-83ee-3828f4bbfdc3.PNG)

**Comment by therev123** [comment]
Nice :D

**Comment by ArieLeo** [comment]
Awesome!!!
