### ISSUE TITLE
Windows Build File Won't Run

### ISSUE THREAD

**Issue by rafallegatus** [armory3d/armorpaint#324]
Hi, I'm having a hard time building the program in my Windows 7. The krom.exe won't open and when I debug it, it always give me this prompt.

Could not load krom.js, aborting.
The program '[6000] Krom.exe' has exited with code 1 (0x1).

I hope someone can help me. I have installed node, java, and VC without any trouble.

**Comment by luboslenco** [comment]
Hello, please check https://github.com/armory3d/armorpaint/issues/256 for solution. If issue persists feel welcome to post in the linked issue as well.

**Comment by rafallegatus** [comment]
Hi, I have tried that as well, I indicated that in the Debugging part but it still doesn't work.
