### ISSUE TITLE
Windows Build File Still Won't Run

### ISSUE THREAD

**Issue by rafallegatus** [armory3d/armorpaint#325]
Hi, after following the solution in [#256](https://github.com/armory3d/armorpaint/issues/256)

I'm still getting this prompt when I debug the output build;

Could not load krom.js, aborting.
The program '[7424] Krom.exe' has exited with code 1 (0x1).

**Comment by rafallegatus** [comment]
Debugger output:

'Krom.exe' (Win32): Loaded 'C:\Projects\armorpaint\build\krom\Krom.exe'. Symbols loaded.
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\lpk.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\usp10.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\D3DCompiler_47.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dinput8.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dbghelp.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\apphelp.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\AppPatch\AppPatch64\AcLayers.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\winspool.drv'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\mpr.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\AppPatch\AppPatch64\AcXtrnal.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\AppPatch\AppPatch64\AcGenral.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\sspicli.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\sfc.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\sfc_os.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\userenv.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-core-synch-l1-2-0.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\igd10umd64.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\XInput9_1_0.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\hid.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\Wldap32.dll'. 
The thread 0x22dc has exited with code 0 (0x0).
Krom.exe has triggered a breakpoint.

**Comment by rafallegatus** [comment]
Here is the build folder  [build.zip](https://drive.google.com/open?id=1trebFtKkv5ek2tbxOPY9NcInhOtwwE3K) , could someone figure out what is wrong with the build file? I have been redoing everything from scratch like recloning the repo.

**Comment by rafallegatus** [comment]
Hi, I have tested the build file in a laptop with Windows 10. It seems to be working. So this does mean my Windows 7 didn't meet the requirements to run the program?

**Comment by luboslenco** [comment]
> Here is the build folder build.zip , could someone figure out what is wrong with the build file?

I have checked out the project and the command arguments seem to be set to:
`..\..\build`

Notice the [instructions](https://github.com/armory3d/armorpaint/blob/master/README.md) mention a different path:
`..\..\build\krom`

Also, make sure to not actually include the ` character in the path. Hope that helps!

**Comment by rafallegatus** [comment]
I have tried doing that as well. But the build file seems to work only in my Windows 10 computer. The only thing that I assume that stopping the Krom.exe to run from my Windows 7 laptop is the version of opengl. Does your programs requires an opengl 3.5 installed just like Blender 2.8?

**Comment by rafallegatus** [comment]
I can use your program(the build file) in my Windows 10 laptop only, that would do for now. Not sure what causing it to abort it in my Windows 7 laptop. Thing is I can't use Blender 2.8 either in my Windows 7 computer without hacking or tricking it to identify my as Opengl 3.5. There must be dependencies that my Windows 7 laptop doesn't meet. My videocard must be pretty old too in my Windows 7 machine.
