### ISSUE TITLE
Lock the cursor when panning or rotating viewport

### ISSUE THREAD

**Issue by mchome** [armory3d/armorpaint#326]
Just like blender, you will not move the cursor out of viewport if you are panning or rotating viewport.

**Comment by Calinou** [comment]
To be more accurate, this feature is about confining the cursor to the viewport when panning. When the cursor reaches one edge of the viewport, it will wrap to the opposite edge so you can keep panning forever.

**Comment by luboslenco** [comment]
Thanks for the request! `Preferences - Interface - Wrap Mouse` option has been added. https://github.com/armory3d/armorpaint/commit/7e519f70237d1dccc904bd5b06b57efe09c22ab1 https://github.com/armory3d/armorbase/commit/cee270e04280a165ef9d9e602141b7a96dd5d5a9
