### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by nvcken** [armory3d/armorpaint#328]
By following to build android apk from the instruction
```
node Kromx/make android -g opengl --shaderversion 300
cd Kromx
node Kinc/make android -g opengl --noshaders
```
Then open Android Studio from `~/armorpaint/Kromx/build/Krom` -> Build -> Make Project, getting this error
```
~/armorpaint/Kromx/Sources/main.cpp:2716: error: undefined reference to 'v8::MicrotasksScope::~MicrotasksScope()'
```

**Comment by luboslenco** [comment]
Notice the comment in instructions:
> Manual tweaking is required for now:
> https://github.com/armory3d/Kromx/blob/master/kincfile.js#L68

I recommend building for desktop until the android / ios build process gets smoother.

**Comment by rataman098** [comment]
Two years and it hasn't got smoother it seems
