### ISSUE TITLE
Add some way to hide meshes.

### ISSUE THREAD

**Issue by ca3games** [armory3d/armorpaint#330]
Hi, I just tried armor paint, It's a pretty nice tool to paint textures.
However the only thing lacking is some form of being able to hide a mesh so you can paint on a mesh under it.

Similar to how meshes with diferent materials on Substance Painter has some kind of texture layer system where you only paint in that mesh layer and can hide and unhide such mesh layer and paint on the other meshes without painting on the mesh on top.

Could be useful to paint meshes that are under another mesh, like the head under the hair mesh or some part of the body under the cloth mesh or an accesory that is hidden under another mesh.

**Comment by luboslenco** [comment]
Hello, thanks for opening an issue. There is a way to select a specific mesh to paint on:
https://www.youtube.com/watch?v=9LJY2y6JyKg&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=19

**Comment by ca3games** [comment]
> 
> 
> Hello, thanks for opening an issue. There is a way to select a specific mesh to paint on:
> https://www.youtube.com/watch?v=9LJY2y6JyKg&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=19

Thanks, didn't saw that option, maybe make it more visible for newer user.
Maybe I should close this issue.
