### ISSUE TITLE
Normal Map not affected by Masks

### ISSUE THREAD

**Issue by JanLoehr** [armory3d/armorpaint#331]
Got this setup:

![image](https://user-images.githubusercontent.com/11177594/77144754-fd890a00-6a86-11ea-8a60-7d3e7c9072b0.png)

The exported normal map is filled only with the noisy grain of the upmost layer (the screens). The wood normal is lost though it renders correctly.

![ApplicationFrameHost_j5uePPi3dO](https://user-images.githubusercontent.com/11177594/77144925-6cfef980-6a87-11ea-8064-ae115afe0390.png)

Windows 10
ArmorPaint v0.8 (2020-03-19) - cc565e

**Comment by luboslenco** [comment]
Awesome, thanks for report.

**Comment by luboslenco** [comment]
Still needs more testing but it should work better now in latest builds.

**Comment by JanLoehr** [comment]
I'll test 😉
