### ISSUE TITLE
Channels of layers not applied after reopen project

### ISSUE THREAD

**Issue by JanLoehr** [armory3d/armorpaint#332]
I've added an externally baked occlusion map for the whole asset. So only that channel is applied.

![image](https://user-images.githubusercontent.com/11177594/77145105-ec8cc880-6a87-11ea-92e9-fab7f556ee18.png)

Every time I open the project I have to click through the channels again, selecting which one should be active.

![image](https://user-images.githubusercontent.com/11177594/77145441-daf7f080-6a88-11ea-8118-83d6f6f778a7.png)

Windows 10
ArmorPaint v0.8 (2020-03-19) - cc565e

**Comment by JanLoehr** [comment]
Adding to that. Clicking through the layers seams to apply the Base Color channel. The height channel stays active (got no Heightmaps in there, so I disabled) 🤔

**Comment by luboslenco** [comment]
Should be resolved in updated dev builds. 🔨
