### ISSUE TITLE
SVG/Vector Image Import

### ISSUE THREAD

**Issue by Hopefullyidontgetbanned** [armory3d/armorpaint#335]
It would be ideal for Armorpaint to have support for vector image formats (ex. SVG) for high resolution procedural texturing.  This is a feature that is available in substance painter and it would be nice for it to be in Armorpaint.

**Comment by Calinou** [comment]
Unfortunately, the state of open source SVG libraries is kind of bleak. If you want to stick to permissively-licensed options, there's the unmaintained [nanosvg](https://github.com/memononen/nanosvg) which works well on simple SVGs but breaks on most complex vectors. There are other libraries like librsvg which are more complete, but that one is LGPL-licensed to my knowledge.

**Comment by Hopefullyidontgetbanned** [comment]
unfortunately that is true with most vector formats however if basic svg support is possible then that would be ideal. for example pattern generation is what i mostly see svg support as useful for making texturing easier. ex cloth pattern to make procedural cloth textures

**Comment by Hopefullyidontgetbanned** [comment]
fixed in 5bb60a6cd76c9b0b04a217734f52a629da7d5463
