### ISSUE TITLE
Preference Setting for Pen Pressure Sensitivity and Speed Settings for Pan Orbit Zoom

### ISSUE THREAD

**Issue by benji004266** [armory3d/armorpaint#336]
I find it very helpful to be able to adjust pen pressure per software because adjusting it via the OS Settings would require constant readjusting when switching between them.

Also, when close to an object, panning can be way too fast. And, while I personally can live without it, it would be cool if you could POZ via touch input (kinda like in 3D-Coat).

And thanks A LOT for making ArmorPaint :-)

**Comment by luboslenco** [comment]
Added `Preferences - Pen - Sensitivity` option in latest 0.8 dev builds. 🙂

**Comment by luboslenco** [comment]
Also added `Camera Speed` option in the preferences, will continue to improve the navigation in upcoming updates.
