### ISSUE TITLE
Multi Texture Set

### ISSUE THREAD

**Issue by therev123** [armory3d/armorpaint#337]
I think this feature should be take in consideration and be implemented soon as possible. When it will be implemented, I think that will be more easier to implement many request feature like edge wear and other one will comming soon. I hope this feature request will stay open until the feature will be implemented. Sorry for my bad attitude, i don't want to offense anyone here but I think i'm not first one here to purpose this feature, see feature request #154    

This is a very important feature!!!

Thank for reading :)

**Comment by luboslenco** [comment]
Can you provide a feature description? Is it not already possible via [layers](https://www.youtube.com/watch?v=ocIPd6sgQBs&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=22) to have multiple texture sets?

**Comment by therev123** [comment]
Look at 3min 20s: https://www.youtube.com/watch?v=kRtXIj6ENT4&t=236s
I think it's clear. This feature could be very usefull in the future. We could use those imported map to make many thing. At this time, quixel mixer only suport one base layer. I think we could implement the same concept, 1 textures set = 1 base-layer, in each base layer we could assign: Base Color map, Metalness map , roughness map, displacement map, normals map, ao map, curvature map and ID map. If we need an extra base layer elsewhere than at the beginning of layer stack, no problem just create an other base layer map, place it where you want it in the layer stack, assign it your maps, and that it we have an multi-texture set(or multi base layer). During the time i writing, Armor Paint is a node base pbr painting software. May be we could implement an extra node in the node editor for this feature, or may be do the same thing than Quixel Mixer. 

This is an other very good exemple, Blender DECAL MACHINE addon and Substance Painter: https://www.youtube.com/watch?v=YCUV8pS7MXQ&t=1691s

Let me know if you need more information :)

**Comment by luboslenco** [comment]
Sorry I am still unsure what to do to reslove this, in armorpaint each layer has base / metal / rough / ... slots, can be assigned to different object and stacked on top. There is a way to place layer nodes into the material and mix multiple layers via nodes, then use that to create a fill layer. I understand lots of features are still missing and quality of life improvements are needed. 🙂

**Comment by therev123** [comment]
> in armorpaint each layer has base / metal / rough / ... slots, can be assigned to different object and stacked on top. There is a way to place layer nodes into the material and mix multiple layers via nodes, then use that to create a fill layer.

I will looking for a possible way to bring this in armorpaint source code. I think this feature is the next step in ArmorPaint development. I don't promise you the code solution, I'll put my idea on paper and post it here where it's finish. If someone want to share some tips and tricks about the source code you welcome :)

**Comment by luboslenco** [comment]
Continuing at https://github.com/armory3d/armorpaint/issues/154.
