### ISSUE TITLE
Texture groups

### ISSUE THREAD

**Issue by ca3games** [armory3d/armorpaint#339]
Something that would be a nice life improvement would be to have some kind of organization or group structure in the texture tab, similar to a layer system, where you can group all the textures of the same material in the same layer or some group you can add some label name to it.

That would  make it easier to organize the textures in the texture tab.

**Comment by therev123** [comment]
It look like an asset management feature.

**Comment by cgvirus** [comment]
It looks like there is a group feature, but I can only put one layer in a group. Does anyone know how this group should be used?

**Comment by luboslenco** [comment]
Hoping to further improve the Browser tab so the existing folder structure on disk can be used for better organization. Will also eventually add search functionality to all tabs which list assets.

Grouping multiple layers into one group should no longer be an issue.
