### ISSUE TITLE
New empty layer hides inferior layer - Linux / OpenGL

### ISSUE THREAD

**Issue by ca3games** [armory3d/armorpaint#340]
*Please specify your ArmorPaint version and OS.*
Armor paint -v0.8 (2020-03-23) - a7fdc07
Linux OpenGL

Here's a video of the bug.
https://www.youtube.com/watch?v=PcRUHmo9ML8
When I create a new empty layer, for some reason it hides an inferior layer, like if It were a mask.

**Comment by therev123** [comment]
Same problem here. In my case the problem apear when I change the layer resolution, I am unable to paint on the 3d object.

**Comment by luboslenco** [comment]
@therev123 *Please specify your ArmorPaint version and OS.*

**Comment by therev123** [comment]
Compiled version

**Comment by luboslenco** [comment]
Please paste the info from `Menu bar - Help - About...` dialog in ArmorPaint, which shows the exact version and OS. 🙂

**Comment by therev123** [comment]
It seem to be fixed with the last commits

**Comment by luboslenco** [comment]
Oki.. original issue still stands so this is unrelated to it.

**Comment by hrkrx** [comment]
I have the exactly same Issue with
ArmorPaint.org - v0.8 (2020-04-21) - 4b64d8b
Linux - OpenGL

**Comment by luboslenco** [comment]
Added Vulkan builds for Linux which should not spot this issue. OpenGL builds are still recommended but eventually Vulkan will become the default once battle tested enough.
