### ISSUE TITLE
iPad Pro Apple Pencil = no pressure sensitive?

### ISSUE THREAD

**Issue by enzyme69** [armory3d/armorpaint#341]
<img width="400" alt="Screen Shot 2020-03-24 at 12 04 23 pm" src="https://user-images.githubusercontent.com/3952687/77377578-9bead780-6dc7-11ea-826d-48688bc5db82.png">

*Please specify your ArmorPaint version and OS.*
Armor Paint 0.8 dev
MacOS Catalina

I am testing Armor Paint with iPad Pro + Apple Pencil, somewhat performance is excellent, but Apple Pencil pressure does not register to the app, it seems..

**Comment by luboslenco** [comment]
Any luck using the newly updated 08dev builds?

**Comment by luboslenco** [comment]
Fixed. 🙂 https://twitter.com/jimmygunawanapp/status/1243476521055965186
