### ISSUE TITLE
RGB node problem

### ISSUE THREAD

**Issue by therev123** [armory3d/armorpaint#342]
*Please specify your ArmorPaint version and OS.*
Build form latest source code, Windows 10

I don't know if it could be a bug but when I change saturation value from RGB node, it don't keep its cursor position RGB circle selection.

**Comment by therev123** [comment]
And i think all RGB based node, for example: color ramp, seem to be affected by this problem.

**Comment by luboslenco** [comment]
Will fix as part of https://github.com/armory3d/armorpaint/issues/216. Thanks for report!

**Comment by therev123** [comment]
It is still there!
