### ISSUE TITLE
iOS error: could not load krom.js

### ISSUE THREAD

**Issue by ChristianHohlfeld** [armory3d/armorpaint#343]
Latest Xcode runtime issue on IOS (yeah, I know, it's still wip).
After successfully compiling the app on ios (main.cpp line 3305):
-> Could not load krom.js, aborting.

Did I miss something or is the file missing inside the app package bundle on ios?
Any help appreciated. Thank you.

**Comment by luboslenco** [comment]
Hello Christian, thanks for checking out ArmorPaint. Yes, I believe the file is missing in the bundle. Please give me 1-2 more weeks and I will refine the build process & update the instructions. :)
