### ISSUE TITLE
Bump/Displacement/Normal Map Nodes

### ISSUE THREAD

**Issue by ndedakaduki** [armory3d/armorpaint#344]
Is it possible to get control over height maps/displacement and also normal maps so as to be able to control the intensity of the map instead of using it at full value. Also to allow the use of both height maps and normal maps on the same material. However I'm not sure if true displacement is something that shall be implimented into ArmorPaint, and if not then I believe normal and bump map nodes would be more than enough.

Something like these:

![ArmorPaint](https://user-images.githubusercontent.com/24776459/77644025-713c8280-6f71-11ea-9eb7-677b1c8af6fe.png)

EDIT: There was a slight mistake on my part, I have noticed that the bump node has option to influence the strength.

**Comment by luboslenco** [comment]
Thanks for report, will make it happen. Joining together with issue at https://github.com/armory3d/armorpaint/issues/293.
