### ISSUE TITLE
CPU/GPU usage spike on minimize

### ISSUE THREAD

**Issue by kazeshini5** [armory3d/armorpaint#345]
*ArmorPaint 0.8-2050d27, Windows*

Extreme usage spikes when minimized

![CPU-GPU Usage Spike](https://user-images.githubusercontent.com/62077668/77739163-e02de000-7032-11ea-8e2a-da196c3685e1.gif)

**Comment by luboslenco** [comment]
Should be resolved in updated 0.8 dev builds, let me know if you get to test it.
