### ISSUE TITLE
I like stamp, but I want multiple stamp

### ISSUE THREAD

**Issue by enzyme69** [armory3d/armorpaint#346]
I love Armor Paint stamp, it is simple to setup via node. But I would like to be able to multi-stamp.

Let say I have bunch of cutout flower shapes, and I want to randomly stamp those flowers while brushing. It would be cool to be able to do this.

I found that also stamp + drag stroke _kills_ the alpha channel. 

<img width="1209" alt="Screen Shot 2020-03-29 at 1 00 41 pm" src="https://user-images.githubusercontent.com/3952687/77838194-578f7b00-71bd-11ea-9635-bf666d9b4ab1.png">

Is there an option to make gap between stamp?

**Comment by enzyme69** [comment]
<img width="1680" alt="Screen Shot 2020-03-29 at 12 55 44 pm" src="https://user-images.githubusercontent.com/3952687/77838132-a25cc300-71bc-11ea-9971-adf5c8dd7ec6.png">

Here is an example showing the issue where stamp works, but stamp and drag gives weird result.

Also I got this when I took snapshots while performing stamp, so it has another bug...

**Comment by luboslenco** [comment]
> Also I got this when I took snapshots while performing stamp, so it has another bug...

@enzyme69 can you let me know how to reproduce it?

**Comment by enzyme69** [comment]
@luboslenco While painting stroke brush, take screenshot (mac) and you can see the brush painting started to bleed into interface.

**Comment by enzyme69** [comment]
I tried it just now, but only get some glitches on texture. But I remember was switching back and forth between Blender and Armort Paint and accidentally take screenshot while brushing. I will record it if I could reproduce exactly. But it's something to do with screenshoting while brushing strokes.

**Comment by enzyme69** [comment]
I was also using Sidecar and iPad Pro Apple Pencil brush I think ...maybe that's also causing this glitch. After I painted the UI, I can no longer go back to 3D view to paint the cube.

**Comment by luboslenco** [comment]
Pushed some improvements, new builds up soon.
- No longer kills alpha
- To change decal image, randomly select image via material nodes, like https://blender.stackexchange.com/questions/93700/node-editor-pick-random-image-texture-from-set
- To make gap - increase `lazy radius` and `lazy step` in brush nodes (brush jitter, directional brush videos at [howto](https://armorpaint.org/howto.html))
