### ISSUE TITLE
Crash while switching to 16k export resolution

### ISSUE THREAD

**Issue by qwinci** [armory3d/armorpaint#348]
*ArmorPaint 0.8-e61e71b, Windows*
Armorpaint crashes while switching to 16k export resolution and all data will be lost.

**Comment by luboslenco** [comment]
Which GPU are you on?

**Comment by august0815** [comment]
Yes , after selecting  8K or 16k resolution armorpaint crashes.
System Linux Mint 19.3, GPU Nvidia GeForce GTX1060 6 GB

**Comment by luboslenco** [comment]
Thanks for info. Can you check gpu mem usage? Does it go past the system resources?

**Comment by august0815** [comment]
Yes you are right, I have 16 GB Ram and even if I close all to save memory, armorypaint consumes all of my memory, ): .
But It is OK for now. I am testing on low res.
Than you

**Comment by luboslenco** [comment]
Changing texture resolution should only consume gpu memory. unless it's already full which appears to be the case here. Will investigate and report back with a fix. 🙂

**Comment by august0815** [comment]
I have two videos, link  youtube
https://youtu.be/rN7KIOhKNjE
Armorpaint ist crashing, selecting exportoption 16 k , befor I hit  'export-button' ???
Maybe the error is: wrong/bad the mesh?
https://youtu.be/uA02o22AUYA
simple box from armorpaint and simple texture , this is working

**Comment by august0815** [comment]
It is better but still bug.
I have updated to your latest commit.It works better now.Total Ram usage about 14 GB.
But after a long time (that takes to process) there is about 10 GB used Ram. I think Ram is not freed after texture save is finished.
https://youtu.be/3Tv3szCFEZs
see last terminal message :
ArmorPaint: ../../Libraries/nfd/simple_exec.h:72: int runCommandArray(char **, int *, int *, int, char *const *): Assertion `__release_assert_tmp__' failed.
Abgebrochen (Speicherabzug geschrieben)

**Comment by luboslenco** [comment]
Switching to 16K on a 6GB card should no longer crash, but it's still hungry, better to go with 8K for cards with <=6GB video memory for now.

**Comment by mojoyup** [comment]
How do I reset when I cant open the program now after switching to 16k? It auto crashes
