### ISSUE TITLE
ArmorPaint does not export emission map

### ISSUE THREAD

**Issue by Hopefullyidontgetbanned** [armory3d/armorpaint#349]
*Please specify your ArmorPaint version and OS.*
Windows 10 Pro
ArmorPaint-MasterBranch-1268-b355159-3/31/2020
![Screenshot (1330)](https://user-images.githubusercontent.com/45346421/78096246-f965c200-738d-11ea-8899-37cf670cee2e.png)
![Screenshot (1331)](https://user-images.githubusercontent.com/45346421/78096258-fff43980-738d-11ea-9783-5baaf4ee209f.png)
![Screenshot (1332)_LI](https://user-images.githubusercontent.com/45346421/78096274-04b8ed80-738e-11ea-8717-05d19301d35f.jpg)
this does not change even if i change the preset

**Comment by luboslenco** [comment]
Those screenshots look like some ancient ArmorPaint version. This is how export textures dialog should look.

![Capture](https://user-images.githubusercontent.com/3685704/78105587-d10faf00-73f1-11ea-9e3c-ced50fb89706.PNG)

**Comment by Hopefullyidontgetbanned** [comment]
strange let me recompile it completely without existing builds

**Comment by luboslenco** [comment]
Please follow the instructions from [readme](https://github.com/armory3d/armorpaint/blob/master/README.md), these always point to the latest builds.
