### ISSUE TITLE
Brush warps to object

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armorpaint#35]
Link to [forum post](http://forums.armory3d.org/t/feature-request-brush-warps-to-object/2070).

**Comment by SojanJanso** [comment]
Mentioned on forum in post http://forums.armory3d.org/t/armorpaint-qol-improvement-suggestions/2572

1. Brush Improvements (third bullet point)

**Comment by luboslenco** [comment]
In-progress. 🖌 

![warp](https://user-images.githubusercontent.com/3685704/58041822-5d4a1800-7b39-11e9-8f42-f8b8795f1b3d.gif)

**Comment by luboslenco** [comment]
Latest builds have brush warp enabled by default. May still need some improvements. Old cursor can be accessed by un-checking `Preferences - Usage - 3D Cursor` property.

Decal and text tool will get the warping in upcoming builds.

**Comment by luboslenco** [comment]
Handle decal warping via https://github.com/armory3d/armorpaint/issues/432.
