### ISSUE TITLE
Remember file browser working directory on Linux

### ISSUE THREAD

**Issue by august0815** [armory3d/armorpaint#350]
Hello,
the work flow interrupts by clicking every time thru the path, where to save , import or export  data .
an working directory would be nice.

**Comment by luboslenco** [comment]
Hi, can you provide more details? How to implement the working directory? Right now ArmorPaint will open a system file browser where your folder bookmarks etc. should be displayed. 

For importing drag and dropping assets is recommended, or creating bookmarks in the `Browser` tab found in the status bar.

Or do you mean skipping the file browser completely? Once the textures are exported for the first time you can then auto-re-export using `ctrl+e` (found as `file_export_textures` operator in keymap), maybe this can be improved?

**Comment by august0815** [comment]
https://youtu.be/EaxQc8SViK8

See on video what I mean.Every time 5 clicks is to much. It is bad organized, but hey testing :)

**Comment by luboslenco** [comment]
Thanks, I see. The file browser on both Windows and macOS remembers the last location, I am not sure why this is not the case on Linux.

**Comment by august0815** [comment]
Okay , I see. But it works on linux too. eg. Geany 1.32 ( C program)
https://youtu.be/D9gotXua4Bo
Opens and save to position of the current text.
But I am not an C -expert

**Comment by luboslenco** [comment]
Yes I can see that as well. The problem is ArmorPaint uses a single library to open file browser on all operating systems, this means we need a special code for Linux. (but it was inevitable anyway https://github.com/armory3d/armorpaint/issues/179)

**Comment by august0815** [comment]
Thank you. It is very hard to make it behave everywhere the same way.

**Comment by august0815** [comment]
https://youtu.be/kB-sJZ7-eTE
The starting point is used in linux too; but with shell script , :(

**Comment by PiloeGAO** [comment]
@august0815 , the blender live-link addon was updated 2 days ago.
If you still experience issues/troubles with the Blender Addon, please report it here: https://github.com/PiloeGAO/Blender-ArmorPaintLiveLink/issues

**Comment by august0815** [comment]
Blender-ArmorPaintLiveLink is now working fine. Thank you.

So, sync with blender works, but if I export an textured 'Cube' armorpaint is opening only temp.obj not *.mtl ?

**Comment by PiloeGAO** [comment]
Armorpaint don't support *.mtl files.

**Comment by luboslenco** [comment]
Using the standard file browser on linux via gtk now.
