### ISSUE TITLE
MMB drag does not work for MAC

### ISSUE THREAD

**Issue by Mujushin** [armory3d/armorpaint#355]
MAC OS High Sierra 10.13.6

Repro Steps
Open ArmorPaint
MMB drag in the 3D view port

Track movement does not activate. Scroll wheel actions still work as normal. MMB drag can be used in other programs such as Maya LT

**Comment by Tezeroth** [comment]
I am also having this problem, and i'm on Catalina 10.15.3

**Comment by luboslenco** [comment]
Fix at https://github.com/Kode/Kinc/pull/515.
