### ISSUE TITLE
Node is removed and other nodes cannot be added after deleting one on macOS

### ISSUE THREAD

**Issue by Mujushin** [armory3d/armorpaint#356]
ArmorPaint 0.7
MAC OSX High Sierra 10.13.6

Repro steps:
Create a new material
Expand node view
Add image texture to the node view
Delete default RGB node
Select Image node

Outcome:
image node disappears from UI after attempting to select it

This has been confirmed to happen with any kind of node after a node of any type is deleted from the view.

**Comment by luboslenco** [comment]
Hm unable to reproduce this, can you please give it a shot using the latest 0.8dev builds instead? Is the issue still present? Thanks for report.

**Comment by Mujushin** [comment]
Have tested this with the 0.8 dev build and the same thing happens. Can confirm this is specific only to MAC, the defect does not happen on Windows.

**Comment by luboslenco** [comment]
Thanks, I have tested on macOS as well but still unable to reproduce. :( The only difference I see is that I tested on Catalina, not sure if that is relevant in this case though.

**Comment by luboslenco** [comment]
Unable to reproduce, sorry. :( Tested on macOS Catalina 10.15.5.
