### ISSUE TITLE
Creating a Live Link plugin for Godot

### ISSUE THREAD

**Issue by Calinou** [armory3d/armorpaint#357]
Just curious, what would it take to create a Live Link plugin for Godot? In other words, what does a plugin need to do to support Live Link functionality?

Not that it's urgent by any measure, but it would be nice to have a page in the manual that documents how to create a Live Link plugin in an abstract, engine-agnostic manner. In the meantime, I'll try to look at the [Unreal](https://github.com/armory3d/armorpaint_unreal) and [Unity](https://github.com/armory3d/armorpaint_unity) plugin sources.

**Comment by luboslenco** [comment]
Hi, would be indeed awesome to have a page in the manual for that. I am hoping to start putting together development docs here on the wiki soon.

There is a new command line interface contributed by Leo at https://github.com/armory3d/armorpaint/pull/347. And another two plugins with sources:
https://github.com/PiloeGAO/Blender-ArmorPaintLiveLink
https://github.com/PiloeGAO/Maya-ArmorPaintLiveLink

**Comment by PiloeGAO** [comment]
Hi Calinou,
I currently work most of my time on the Blender Live-Link Addon.
The Maya plugin is the next thing I will refactor.
I planned to work on Houdini and Godot in future.
