### ISSUE TITLE
Different clarity of the brush stroke when drawing in the viewport and 2D View

### ISSUE THREAD

**Issue by manfromtown** [armory3d/armorpaint#358]
Hi! When I draw on an object in the viewport, the brushstroke is clear, and when I draw in "2D View", it is blurred. The brush strokes are drawn with the mouse. The hardness of the brush is set to the same. Is this how it should be or is it a bug? I'm a beginner at this, so I'm asking.
![Image 1](https://user-images.githubusercontent.com/61837858/78703086-4a3b6480-7912-11ea-9807-77a1354f376d.png)

**Comment by manfromtown** [comment]
When I set the brush hardness on the toolbar and in the Brush Output node to 10, the clarity of the brush strokes is leveled.
![Image 6](https://user-images.githubusercontent.com/61837858/79638387-a2cdf580-818d-11ea-95ba-0530c08a6b0a.png)

**Comment by luboslenco** [comment]
Thanks for report - linking together with similar issue at https://github.com/armory3d/armorpaint/issues/487.
