### ISSUE TITLE
v8_monolith.lib path incorrect in generated VS project

### ISSUE THREAD

**Issue by dbechrd** [armory3d/armorpaint#359]
I followed the instructions in the readme exactly to generate the VS project on a fresh Windows 10 machine. Everything worked as expected, except that v8_monolith.lib relative path is incorrect by default in the Linker Input settings.

The instructions I followed:
```
# Windows
node Kromx/make -g direct3d11
cd Kromx
# Unpack `v8\libraries\win32\release\v8_monolith.7z` using 7-Zip (exceeds 100MB)
node Kinc/make -g direct3d11
# Open generated Visual Studio project
# Set `Project - Properties - Debugging - Command Arguments` to `..\..\build\krom`
# Build for x64 & release
```

The error I got:
![image](https://user-images.githubusercontent.com/707367/78703876-d40e1200-78bf-11ea-8e71-04c2f9ae3949.png)

The way I fixed it:
![image](https://user-images.githubusercontent.com/707367/78703894-db352000-78bf-11ea-9ced-e7472222dea6.png)

I changed:
`v8/libraries/win32/release/v8_monolith.lib`
to:
`../v8/libraries/win32/release/v8_monolith.lib`

Potentially related issues:
https://github.com/armory3d/armorpaint/issues/173
https://github.com/armory3d/armorpaint/issues/300

**Comment by luboslenco** [comment]
The order of instructions needs to be followed. Make sure to do:

> Unpack `v8\libraries\win32\release\v8_monolith.7z` using 7-Zip (exceeds 100MB)`

before doing:

> node Kinc/make -g direct3d11

Afterwards the path to library should be properly resolved.

**Comment by dbechrd** [comment]
@luboslenco The instructions don't say _where_ to unpack the v8_monolith.lib file to. The way I use 7-zip via context menu, I always unpack things as directories to not make a mess of the dir I'm unpacking into, so when I unpacked it, it went to `release\v8_monolith\v8_monolith.lib`, then I ran `node Kinc/make`, then opened VS and saw the error, and moved the lib up one directory.

If `node Kinc/make` depends on the lib being in a particular place, it should verify that when it runs and print a message if it doesn't find it, rather than silently failing and generating a VS project with an incorrect lib path. Also, the instructions should be updated to be more specific about exactly where to unpack to the lib to since it's ambiguous. Both of those things would help!

**Comment by luboslenco** [comment]
I have updated the readme to make it more obvious that no additional directories should be created. https://github.com/armory3d/armorpaint/commit/cc4c3f4688fb95699e91ec244fc68589bd648e41

> If node Kinc/make depends on the lib being in a particular place, it should verify that when it runs and print a message if it doesn't find it

I believe the build tool does not verify this because the library can be also placed anywhere in the linker search folders.
