### ISSUE TITLE
Increasing the UI Scale shifts folder names in the Browser

### ISSUE THREAD

**Issue by manfromtown** [armory3d/armorpaint#360]
Hi! When "UI Scale" is set to 1.2 in "Preferences", folder names are shifted in "Browser". It is possible to fix?
![Image 4](https://user-images.githubusercontent.com/61837858/78758825-65948700-7987-11ea-827f-55ebd417f355.png)

**Comment by luboslenco** [comment]
Yes it is possible, pushed a fix at https://github.com/armory3d/armorpaint/commit/118a515060a049e1521f47e06964299fa940579c. Will be live in upcoming builds, thanks for report!
