### ISSUE TITLE
Import Envmap broken if imported to ArmorPaint install on protected drive/path.

### ISSUE THREAD

**Issue by bmobius** [armory3d/armorpaint#362]
ArmorPaint v0.8 (2020-03-31) - b355159
Windows 10
Direct3D11
NVIDIA GTX 980ti

Whenever I attempt to import an .hdr envmap into ArmorPaint while the program is installed in a protected location (i.e. drive C:) the image will not update the environment in the viewport. This happens with both drag-and-drop as well as Texture>Import.

If I use ArmorPaint in a non-protected install location, the .hdr envmap imports as it should with no issues.

**Comment by bmobius** [comment]
ArmorPaint v0.8 (2020-05-10) - 8ce6c17
Windows 10
Direct3D11
NVIDIA GeForce GTX 980 Ti

Environment Map (EnvMap) import still broken as of the most recent ArmorPaint 0.8 build. If ArmorPaint is installed on a protected drive/path (such as C:), the image imports but does not update in the viewport. Any further attempts to import another .hdr EnvMap (after the first attempt) cause the application to crash to desktop.

**Comment by luboslenco** [comment]
Should be resolved now.
