### ISSUE TITLE
Armor paint cannot export textures in linux

### ISSUE THREAD

**Issue by Jayanth-L** [armory3d/armorpaint#364]
Master branch of Armor paint, Arch linux
Kernel: 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64 GNU/Linux
Desktop environment: KDE and Gnome
on both DE this bug occurs.

`Uniform N not found.
Uniform texUnpack not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/RenderTargetImpl.c 174

Uniform brushScale not found.
Segmentation fault (core dumped)
`
Any solutions guys ?

**Comment by luboslenco** [comment]
Hello, is this related to https://github.com/armory3d/armorpaint/issues/179?

**Comment by Jayanth-L** [comment]
> Hello, is this related to #179?

Yes exactly,
Thank you for pointint out the issue,
just disabled Native file browser in the preferences
Now it works with the built in explorer :)
Can i close this issue ?

**Comment by luboslenco** [comment]
Yes please close this one, but the one at https://github.com/armory3d/armorpaint/issues/179 still needs to be resolved. :( Built-in explorer is only meant as a workaround but should at least allow to export the textures..

**Comment by Jayanth-L** [comment]
> Yes please close this one, but the one at #179 still needs to be resolved. :( Built-in explorer is only meant as a workaround but should at least allow to export the textures..

But the native explorer disable doesn't look persistent
Every time i start i have to manually disable that!

Any solution for this ?

**Comment by luboslenco** [comment]
The solution is to investigate why the browser fails on Arch like mentioned at https://github.com/armory3d/armorpaint/issues/179. 🙂

But if you just want to make it persistent modify it here https://github.com/armory3d/armorpaint/blob/master/Sources/arm/Context.hx#L107.
