### ISSUE TITLE
Real armorpaint features need

### ISSUE THREAD

**Issue by therev123** [armory3d/armorpaint#365]
Hi everyone, today is the last time I'll request(or purpose) new feature about ArmorPaint devlopment. I'll not explain the reasons why i decide to do this, by the way everyone here will don't care about it.  So, this is my last purposes:

1) Be able to make custom node (no fucking(Sorry) scripting!!!!), be able to edit them and re-use them in an other project by importing ArmorPaint project;

2) Implement a "Master fill layer" layer to fix #154 feature request;

3) Be able to set a default working(default asset) path in preference, like substance painter shell;

4) Documentation and how-to are a little bit minimalist;

To get more detail about them, like and ask. 
Sorry for my bad english :)

**Comment by luboslenco** [comment]
Please no strong language here, this tracker is supposed to be accessible to everyone. When the issues already exist (ie https://github.com/armory3d/armorpaint/issues/154) there is no need to open another one.
