### ISSUE TITLE
New version:  crashs inserting Voronoi Texture

### ISSUE THREAD

**Issue by august0815** [armory3d/armorpaint#366]
*Please specify your ArmorPaint version and OS.*
Latest version latest commits, Linux mint 19.3
Scene simple Cube, Material new, delate rgb ant want to insert voronoi texture , crash.
output ->
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 212
se
Speicherzugriffsfehler (Speicherabzug geschrieben) (memory)

Segmentation fault (core dumped)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/0fcfa61bdd0f508a1f0d9766e8afe4ceac445e08, many thanks for opening the issue!
