### ISSUE TITLE
Color Picker for OS X crashes Application sometimes

### ISSUE THREAD

**Issue by Blix409** [armory3d/armorpaint#371]
I've noticed once I've worked on a small project, selecting the Color Picker crashes the application.

**Comment by luboslenco** [comment]
Please let me know your ArmorPaint version, thanks.

**Comment by Blix409** [comment]
It’s the latest .8 I believe. I downloaded it yesterday. 

Thanks! 

DAMION HILL
Owner & Operator at E-Mix Online

(585) 690-7707
damion@e-mixonline.com
https://e-mixonline.com

Social Media Links
www.facebook.com/emixonline
www.twitter.com/EMixOnline
www.linkedin.com/in/damionhill

_______________
Unless otherwise agreed expressly in writing this email is to be treated as confidential and the information in it may not be used or disclosed except for the purpose for which it has been sent. Please notify E-Mix Online at salesinfo@e-mixonline.com, if you have received this email by mistake and delete this email from your system.
_______________

**Comment by luboslenco** [comment]
I assume it's 0fcfa61 then, it should be displayed in the `Menu bar - Help - About...` popup.

Can you let me know steps to reproduce the crash? Which color picker should I select? Is selecting it once enough? Does it always crash? Thanks.

**Comment by Blix409** [comment]
Hello! 

I wanted to thank you for such a fantastic application you’ve made. I do however have a question or more so a request... I have a ton of pieces of a model I exported from Blender into ArmorPaint. Within a specific layer you have the option to only show a certain piece of the model rather than display the entire mesh. I have a lot of items in the model. I’m not able to access the entire list. I cannot scroll further down the list. Is there something I’m missing? 

I’m using a Mac 

Thanks

DAMION HILL
Owner & Operator at E-Mix Online

(585) 690-7707
damion@e-mixonline.com
https://e-mixonline.com

Social Media Links
www.facebook.com/emixonline
www.twitter.com/EMixOnline
www.linkedin.com/in/damionhill

_______________
Unless otherwise agreed expressly in writing this email is to be treated as confidential and the information in it may not be used or disclosed except for the purpose for which it has been sent. Please notify E-Mix Online at salesinfo@e-mixonline.com, if you have received this email by mistake and delete this email from your system.
_______________

**Comment by luboslenco** [comment]
Hello, which ArmorPaint version are you using? (available via the `Menu - Help - About...` dialog)
