### ISSUE TITLE
Texture don't wrap when UV's exceed 0-1

### ISSUE THREAD

**Issue by Stromberg90** [armory3d/armorpaint#373]
Using Master branch with visual studio 2019 on windows 10 x64.

Can't paint or fill whatever is outside of the 0-1 uv spaces.

UV's
![](https://i.imgur.com/cONg954.png)
ArmorPaint
![](https://i.imgur.com/K9JKZO6.png)
Substance Painter(What I expect)
![](https://i.imgur.com/LiMoE0R.png)

Link to the obj file.
[Shotgun_Final](https://www.dropbox.com/s/qbugdk0dxz8fbli/Shotgun_Final.obj?dl=0)

**Comment by PiloeGAO** [comment]
Hi @Stromberg90, you need to import your asset with the "UDIM Tile" option to have access to the second UV space.

![image](https://user-images.githubusercontent.com/43547972/79641650-24775080-8199-11ea-87fd-f0937d6b1c2c.png)

![image](https://user-images.githubusercontent.com/43547972/79641692-630d0b00-8199-11ea-9f33-e33e44f4232a.png)

**Comment by Stromberg90** [comment]
This does work, in it's current state I think this should be the default.

Now I haven't used UDIM's, but from what I understand and reading about it, the point is it gives you a texture per UV tile,
while what this does is wrapping which usually is the default behavior.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/1225719ec19f5ba2a9cb8093704a11254400616f, thanks for report!
