### ISSUE TITLE
GL Error 1282 on latest 0.8 ArmorPaint!

### ISSUE THREAD

**Issue by edisan27** [armory3d/armorpaint#376]
- I'm using latest : ArmorPaint.org - v0.8 (2020-04-19) - c635f4f
- Linux - OpenGL - On Linux Mint 18.2

I'm keep getting this error everytime i launch ArmorPaint (Krom) here is my Terminal info when ArmorPaint is running:

> Uniform N not found.
> Uniform texUnpack not found.
> GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/RenderTargetImpl.c 174
> 
> Uniform brushScale not found.
> Uniform brushScale not found.
> Uniform brushScale not found.

The "Uniform brushScale not found" only appear everytime i'm add a new material or layer.
Also I have very slow performance on ArmorPaint like when rotating the view and have a glitchy texture when adding new material but it gone when i updating the view (rotate/pan view).
I also can run Blender 2.82 without having lag issue.

Here is my OpenGL version:

> OpenGL vendor string: X.Org
> OpenGL renderer string: AMD MULLINS (DRM 2.46.0 / 4.8.0-53-generic, LLVM 6.0.0)
> OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.5
> OpenGL core profile shading language version string: 4.50
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 3.0 Mesa 18.0.5
> OpenGL shading language version string: 1.30
> OpenGL context flags: (none)
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.0.5
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
> OpenGL ES profile extensions:

Edit : i have Radeon R5 Video Card

**Comment by luboslenco** [comment]
Thanks for report. `Uniform brushScale not found.` should not cause any harm, it means the shader compiler optimized some variables away.

To get better performance on older video cards,
try switching the `Edit - Preferences... - Viewport - Renderer` option to `Mobile`. Also make sure to disable SSAO (see [manual](https://github.com/armory3d/armorpaint_docs#viewport-1)).
