### ISSUE TITLE
Preview distortion when zooming in on an object in Live Brush Preview mode

### ISSUE THREAD

**Issue by manfromtown** [armory3d/armorpaint#377]
*ArmorPaint v0.8-005f5c6, Windows 10*
![Image 2](https://user-images.githubusercontent.com/61837858/79688410-d0cb3c80-8256-11ea-929b-a467a8c41fec.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/d05b285fcd88d8c7cd312cdecd61d577891154bf. Thanks for report.
