### ISSUE TITLE
Fill mode(UV Shell)

### ISSUE THREAD

**Issue by Stromberg90** [armory3d/armorpaint#382]
Being able to fill the current uv shell, would be really handy, it's my second most used fill mode in substance painter(after submesh).

Like here I filled the face of the text green and the edges blue, which currently I have to do using the face fill.
![](https://i.imgur.com/UlebmGa.png)

**Comment by luboslenco** [comment]
Added at https://github.com/armory3d/armorpaint/commit/c66d753f4e5ea6695179d81f58347cf70965f46a, thanks for the request.
