### ISSUE TITLE
Blender live link update

### ISSUE THREAD

**Issue by divineniiquaye** [armory3d/armorpaint#383]
Hi, pls pls update the blender live link for Armorpaint

**Comment by PiloeGAO** [comment]
Hi @divineniiquaye,
What do you mean about updating? Implementing new features?
If you experience any issues or need specific features for the Blender Live Link, please post a new issue here: [PiloeGAO/Blender-ArmorPaintLiveLink](https://github.com/PiloeGAO/Blender-ArmorPaintLiveLink/issues)

**Comment by divineniiquaye** [comment]
Oh ok :/
