### ISSUE TITLE
Add option to rotate EnvMap

### ISSUE THREAD

**Issue by ni-code** [armory3d/armorpaint#385]
Add an option to rotate the Environment Map, This wold help to better see the effect of the roughness values as the EnvMap is rotated.

**Comment by Calinou** [comment]
I suppose this could be implemented by adding a keyboard modifier that should be held down while rotating the camera. When held down, only the envmap would rotate, not the camera.

**Comment by luboslenco** [comment]
New `rotate_envmap` action is now available at `Preferences - Keymap`. I have mapped it to `ctrl+middle` for consistency with `rotate_light` action which is mapped to `shift+middle` for some reason. We can remap it to right click if desired.
