### ISSUE TITLE
Import OBJ/Split into materials Bug

### ISSUE THREAD

**Issue by Clockmaster** [armory3d/armorpaint#387]
*ArmorPaint Version 0.8 Dev Win64, Windows 10 64bit, version 1909*
Please note that when importing an obj with materials, in the Layer section, if you press the "shared" button, it appears a list of the first material in the obj duplicated an enormous amount of entries. That duplicated material entries fill up the "shared" drop down menu, so it is impossible to work on material from number 2 to last one, since the drop down menu has no handlers, hence it is impossible to scroll it down and see if the first material duplication ends after a certain amount.
Please fix it, since I cannot work with multimaterial OBJs with this issue. Tried both OBJs created with Lightwave 3d 10.1, and with Blender 2.83: same issue with both. 
Thank You very much and keep ut the excellent work

**Comment by Clockmaster** [comment]
Here a test obj, with .mtl file and texture. Attached also the .arm project.
[testcube BUG REPORT.zip](https://github.com/armory3d/armorpaint/files/4585794/testcube.BUG.REPORT.zip)
Thanks alot again

**Comment by Clockmaster** [comment]
and finally a screenshot
![TESTCUBE IMPORT OBJ BUG](https://user-images.githubusercontent.com/19892866/81160128-00ce4b80-8f8a-11ea-9d95-a55c864bbbc2.png)

**Comment by luboslenco** [comment]
Resolved now in latest 0.8 dev builds, thanks for great report!

**Comment by Clockmaster** [comment]
Many Many Thanks! IT WORKS!
