### ISSUE TITLE
Crash while opening ArmorPaint

### ISSUE THREAD

**Issue by ArseniyMyasnik** [armory3d/armorpaint#388]
Hi, when I'm trying to open ArmorPaint I get white screen for 1 second and then an error "The program stopped working" appears. I believe you can help me to solve this problem.
Latest version of ArmorPaint.
PC- Windows 7, 64 bit

**Comment by luboslenco** [comment]
@ArseniyMyasnik please send me your email to lubos at armory3d.org ([link](https://armorpaint.org/community)) so I can send you a refund. Microsoft ended support for Windows 7 so I no longer do the testing there, sorry. :(

**Comment by luboslenco** [comment]
Ah, you are building your own copy - in that case please launch directly from Visual Studio and see if you can get a stack trace for the crash.
