### ISSUE TITLE
Could not locate texture message on project open

### ISSUE THREAD

**Issue by BarendVanAarde** [armory3d/armorpaint#389]
So here is the setup. I have an existing project with a texture imported. If the last character of the texture name is beyond character 1083 in a directory dump then when I open the project it says it cannot find the texture.

For instance I have a directory with say 69 text files with name 01AAAAAAAAAA.txt to 69AAAAAAAAAA.txt and then a image file which has been added to existing project named test.jpg. 
![image](https://user-images.githubusercontent.com/65036054/81431407-5f015700-9161-11ea-9746-1e4ab7e2c013.png)

Then when I open the project it says it cannot locate the texture.
![image](https://user-images.githubusercontent.com/65036054/81431506-82c49d00-9161-11ea-981c-dfd996c8076e.png)

If I delete one of the files before test.jpg.
![image](https://user-images.githubusercontent.com/65036054/81431592-ac7dc400-9161-11ea-8af7-6db429965d1d.png)

Then when I open the project it finds test.jpg.
![image](https://user-images.githubusercontent.com/65036054/81431669-d0410a00-9161-11ea-8921-dad46c8272ec.png)

I'm using ArmorPaint v0.8 (2020-05-08) - 203e607 which I built from source on a Windows 10 PRO desktop.

**Comment by luboslenco** [comment]
Fixed now via https://github.com/armory3d/armorpaint/commit/d9dbd6368da05ec232a444ed9e3b30ff5a285722 and https://github.com/armory3d/armorcore/commit/8ab4d4188709dbbff33ee287f16c58ae2d50eb1e. Thanks for report.
