### ISSUE TITLE
SSS node does not work

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#390]
*Please specify your ArmorPaint version and OS.*
Win 64 release v 0.8 (2020.05.12)
Hello everyone! The first picture is where there should be a clearance.
Second, I use this card and nothing happens. Maybe I'm doing something wrong?
![1](https://user-images.githubusercontent.com/65244629/81721674-ebc15300-9488-11ea-80e6-b7228f2a1a41.jpg)
![2](https://user-images.githubusercontent.com/65244629/81721678-ecf28000-9488-11ea-94c9-e46b7cbc1d72.jpg)

**Comment by Hopefullyidontgetbanned** [comment]
yep, i never got that node to work.

**Comment by luboslenco** [comment]
Link together with https://github.com/armory3d/armorpaint/issues/36.
