### ISSUE TITLE
Baking curvature map

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#392]
Win 64 v 0.8 2020.05.12
When you bake the curvature texture, along with the ribs along the entire model there are such triangles. In general, I understand what is happening. Due to the triangulation, many faces become and he considers their curves. Reducing the radius in the settings gets better, t triangles disappear. but the lines of curvature become very small.
![4](https://user-images.githubusercontent.com/65244629/81723011-e2d18100-948a-11ea-901e-5ead607663fc.jpg)

**Comment by luboslenco** [comment]
Thanks for report! The offset parameter for curvature bake can be set to negative values now, which should help to mitigate this. Otherwise the bake would have to be done on a more subdivided geometry for now.
https://github.com/armory3d/armorpaint/commit/bae348916933dd000957fdbb8d361d054bd51202

**Comment by AlexKiryanov** [comment]
Good afternoon, Lyubos! I haven't read you for a long time! Thanks for making this better! I meant it! I will look a little later when I update the version. It's great that there is now a way to mitigate this without resorting to a high poly model.
