### ISSUE TITLE
macOS Catalina Red-Green Gradient

### ISSUE THREAD

**Issue by nevrax** [armory3d/armorpaint#394]
ArmorPaint 0.7
Git Tag 20.01
Xcode 11.4.1 (11E503a)
OS macOS Catalina 10.15.4
CPU Intel i7
GPU Iris 1536 MB

> GL Error 1282 ~/armorpaint/Kromx/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

<img width="800" alt="Screen Shot 2020-05-13 at 11 44 59 PM" src="https://user-images.githubusercontent.com/684589/81863776-65823b00-9574-11ea-81b7-3352e197f534.png">

<img width="801" alt="Screen Shot 2020-05-13 at 11 45 12 PM" src="https://user-images.githubusercontent.com/684589/81863773-64e9a480-9574-11ea-8790-e1560b08ed3e.png">

<img width="800" alt="Screen Shot 2020-05-13 at 11 45 24 PM" src="https://user-images.githubusercontent.com/684589/81863771-63b87780-9574-11ea-88c4-e31af69be1cd.png">

<img width="801" alt="Screen Shot 2020-05-13 at 11 45 33 PM" src="https://user-images.githubusercontent.com/684589/81863760-61561d80-9574-11ea-98f0-ef8430340cd8.png">

**Comment by oparaskos** [comment]
I also had this error on MacOS Catalina, in the console output I can see GLSL Compile ERROR and GLSL Linker error for many of the shaders, which may be related.

**Comment by oparaskos** [comment]
I notice the instructions are updated for macos to metal instead of opengl

Now I don't get the red green gradient but instead it crashes on launch.

Update log with following these instructions:
```
Krom[35410:328780] Metal GPU Frame Capture Enabled
Krom[35410:328780] Metal API Validation Enabled
validateFunctionArguments:3577: failed assertion `Fragment Function(deferred_light_frag_main): missing sampler binding at index 4 for gbufferDSmplr[0].'
(lldb) 
```

**Comment by luboslenco** [comment]
A bit more time needed, sorry. Will post an update.

**Comment by luboslenco** [comment]
Metal builds should no longer crash. Still wip, will improve over time.
