### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by arun54321** [armory3d/armorpaint#395]
***Armor paint** version: 0.8-git package from AUR. **OS:** Arch linux*

When I click open/save/import from file menu, the app crashes.

```
$armorpaint                                                                                                                     
Uniform N not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/RenderTargetImpl.c 174

Uniform brushScale not found.
/usr/bin/armorpaint: line 3: 136118 Segmentation fault      (core dumped) /usr/lib/armorpaint/Krom /usr/share/armorpaint/krom
```

**Comment by luboslenco** [comment]
Hi, see existing issue at https://github.com/armory3d/armorpaint/issues/179. Any help on fixing this welcome, ArmorPaint uses https://github.com/mlabbe/nativefiledialog + zenity to open the file dialog.
