### ISSUE TITLE
Blender Material Import MixRGB Node Types Imported Wrong

### ISSUE THREAD

**Issue by oparaskos** [armory3d/armorpaint#396]
*ArmorPaint 0.8-e7e8c41, Windows*
Blender 2.80 RC 3

To reproduce import materials from the following file:

[Blender Node Import Test.zip](https://github.com/armory3d/armorpaint/files/4629881/Blender.Node.Import.Test.zip)

Note that in the blender file the names of the nodes have been set to the names of the MixRGB type.

ArmorPaint erroneously imports the types as such in this table.

|| Blender MixRGB Type || Imported Type in ArmorPaint Editor ||
| Mix                               | Mix |
| Darken                          | Add |
| Multiply                         | Multiply |
| Burn                             | Difference |
| Lighten                          | Overlay |
| Screen                            | Lighten |
| Dodge                            | Linear Light |
| Add                                | Darken |
| Overlay                           | Soft Light |
| Soft Light                        | Color |
| Difference                       | Dodge |
| Subtract                          | Burn |
| Divide                             | Screen |
| Hue                                | Subtract |
| Saturation                      | Divide |
| Color                              | Saturation |
| Value                              | Hue |

**Comment by luboslenco** [comment]
Thanks so much for reporting these, helps a ton! Linking this issue with https://github.com/armory3d/armorpaint/issues/36.
