### ISSUE TITLE
Blender Material Import Reroute Nodes are not imported

### ISSUE THREAD

**Issue by oparaskos** [armory3d/armorpaint#397]
*ArmorPaint 0.8-e7e8c41, Windows*
Blender 2.80 RC 3

In blender node editor reroute nodes are a convenience feature that allow you to tidy up the graph
https://docs.blender.org/manual/en/latest/interface/controls/nodes/reroute.html

When importing materials from blender which use reroute nodes the connections are missed.

See the following test file:
[Blender Node Import Test.zip](https://github.com/armory3d/armorpaint/files/4629963/Blender.Node.Import.Test.zip)

![Capture 2](https://user-images.githubusercontent.com/8076088/81965408-ed695300-960f-11ea-9951-dd120ca5b0a9.PNG)
![Capture 1](https://user-images.githubusercontent.com/8076088/81965412-ee9a8000-960f-11ea-8a4d-68591427785a.PNG)

Better handling of this blender feature on import could be as simple as connecting nodes directly where reroute nodes are used.

**Comment by luboslenco** [comment]
Linking this issue with https://github.com/armory3d/armorpaint/issues/36.
