### ISSUE TITLE
Blender Material Import Group Nodes result in very strange dragging behaviour

### ISSUE THREAD

**Issue by oparaskos** [armory3d/armorpaint#398]
*ArmorPaint 0.8-e7e8c41, Windows*
Blender 2.80 RC 3

Importing materials with grouped nodes results in missing connections and nodes in the node editor in armorpaint.

On top of this if you try to drag any of the nodes that it does import it results in some very unusual behaviour where other nodes drag around in the background at different speeds to the one you're currently attempting to drag.

Repro:
Import materials from the following blend file, open the imported material in the node editor and move some nodes around.

[Blender Node Import Test.2.zip](https://github.com/armory3d/armorpaint/files/4630004/Blender.Node.Import.Test.2.zip)

**Comment by luboslenco** [comment]
Linking this issue with https://github.com/armory3d/armorpaint/issues/36.
