### ISSUE TITLE
Assimp Format library support

### ISSUE THREAD

**Issue by DMJC** [armory3d/armorpaint#399]
Add support for importing formats supported with https://github.com/assimp/assimp 
Reduces the need for conversion tools to import files. Assimp has a Javascript port.

e.g:
3D
3DS
3MF
AC
AC3D
ACC
AMJ
ASE
ASK
B3D
BLEND
BVH
CMS
COB
DAE/Collada
DXF
ENFF
FBX
glTF 1.0 + GLB
glTF 2.0: At the moment for glTF2.0 the following extensions are supported:
KHR_lights_punctual ( 5.0 )
KHR_materials_pbrSpecularGlossiness ( 5.0 )
KHR_materials_unlit ( 5.0 )
KHR_texture_transform ( 5.1 under test )
HMB
IFC-STEP
IRR / IRRMESH
LWO
LWS
LXO
M3D
MD2
MD3
MD5
MDC
MDL
MESH / MESH.XML
MOT
MS3D
NDO
NFF
OBJ
OFF
OGEX
PLY
PMX
PRJ
Q3O
Q3S
RAW
SCN
SIB
SMD
STP
STL
TER
UC
VTA
X
X3D
XGL
ZGL

**Comment by luboslenco** [comment]
Sorry but assimp is too big for armorpaint. I still want to bring in more formats over time but via small libraries, similar to how gltf plugin is done. It's powered by cgltf library and the resulting armorpaint plugin weights just ~80kb.

https://github.com/armory3d/armorpaint_plugins/tree/master/io_gltf
https://github.com/armory3d/armorpaint/blob/master/Assets/plugins/import_gltf.wasm

Judging from madview3d (which may not be completely representative), the assimp dll is 7.6mb. On my machine importing 320mb obj file takes 10.8sec in madview3d, compared to 6.7sec in armorpaint.
