### ISSUE TITLE
(Linux) Value sliders can be deleted by backspace, however it cannot be set with numbers

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armorpaint#4]
[Ubuntu 17.10] For any value sliders, if I click the value, the cursor will appear and I can use backspace to delete the value:
![screenshot from 2018-02-28 08-54-31](https://user-images.githubusercontent.com/17811339/36763973-5701dbc4-1c65-11e8-93b0-626f42dd268a.png)
But then there is no response when I use any number keys. 
Hitting enter will result NaN:
![screenshot from 2018-02-28 08-58-40](https://user-images.githubusercontent.com/17811339/36764025-a2301f48-1c65-11e8-8bd6-75a2bbaf4cb8.png)

/Milo

**Comment by MLHX** [comment]
After testing in Windows, I found this bug is Linux only.

**Comment by SojanJanso** [comment]
yes, same is happening to me here. Ubuntu gnome 17.10

**Comment by luboslenco** [comment]
Appears to work now in armorpaint 0.4.
