### ISSUE TITLE
libc.so.6 missing ? 

### ISSUE THREAD

**Issue by MoMe36** [armory3d/armorpaint#40]
Hello, 

When running ```./ArmorPaint```, I get the following error: 

```bash
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found
```

EDIT: I already ran ```sudo apt-get install libc6```

Any fix ? Thanks !

**Comment by SojanJanso** [comment]
I get the same error on linux (ubuntu 18.04), I think the supported version of glibc is the libc6 package, which ends at glibc_2.27 or something.

**Comment by luboslenco** [comment]
Hi,

Any luck if you re-download the linux build now?

**Comment by SojanJanso** [comment]
Yup, the error is gone here, it seems to be starting up just fine now!

**Comment by MoMe36** [comment]
Same here. Now working perfectly !
