### ISSUE TITLE
Not a MDK project

### ISSUE THREAD

**Issue by ZeroUpshaw** [armory3d/armorpaint#400]
I cloned the project... untill then everything went well, I followed the other instructions to the letter, when I then open the solutions as instructed I get a bunch of error messages and the notice that Krom is not an MDK project. I tried this multiple times (starting at cloning the repo) with the same result.
When trying to load the solution in Visual Studio I get the following output:

Output from MDK Dev Console:
Initializing MDK
A solution is already loaded on start
Analyzing project...
Krom not an MDK project.
Krom contains invalid data.
Krom: This is not an MDK project.

Output from Solution:
E:\Documents\armorpaint\Kromx\build\Krom.vcxproj : warning  : The build tools for v142 cannot be found. Install v142 to build using the v142 build tools.

E:\Documents\armorpaint\Kromx\build\Krom.vcxproj : warning  : Platform 'Win32' referenced in the project file 'Krom' cannot be found.

E:\Documents\armorpaint\Kromx\build\Krom.vcxproj : warning  : Platform 'x64' referenced in the project file 'Krom' cannot be found.

error : Designtime build failed for project 'E:\Documents\armorpaint\Kromx\build\Krom.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'E:\Documents\armorpaint\Kromx\build\Krom.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'E:\Documents\armorpaint\Kromx\build\Krom.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'E:\Documents\armorpaint\Kromx\build\Krom.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'E:\Documents\armorpaint\Kromx\build\Krom.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'E:\Documents\armorpaint\Kromx\build\Krom.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'E:\Documents\armorpaint\Kromx\build\Krom.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'E:\Documents\armorpaint\Kromx\build\Krom.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'E:\Documents\armorpaint\Kromx\build\Krom.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'E:\Documents\armorpaint\Kromx\build\Krom.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.

**Comment by luboslenco** [comment]
What is mdk dev console? It looks like your Visual Studio is not set up to compile c/c++ code, hence the `warning : The build tools for v142 cannot be found. Install v142 to build using the v142 build tools.` message.

**Comment by ZeroUpshaw** [comment]
Thank you so much,
you are right, it wasn't installed. Could have sworn I had it. Thanks for the help luboslenco.

**Comment by luboslenco** [comment]
No prob!
