### ISSUE TITLE
Mesh getting distorted badly on OBJ import

### ISSUE THREAD

**Issue by EatThePath** [armory3d/armorpaint#401]
*ArmorPaint 0.8-7adcfb7, Windows*
I am trying to import a mesh from Wings3D into Armorpaint via .obj as an intermediate step. I'm getting weird distortions of the mesh once into ArmorPaint, and have isolated a segment of the mesh where this is particularly easy to spot. 

![image](https://user-images.githubusercontent.com/4766365/82157836-6acbd800-9849-11ea-88e7-016370fee43f.png)

I've imported objs from Wings into many different programs in the past without problem, so I doubt the issue is with the exporter. I've hunted for settings, known issues, or best practices that might avoid this and come up blank, so here we are.

Included here are the .obj and .arm files for this section of mesh.

[BrokeBits.zip](https://github.com/armory3d/armorpaint/files/4640860/BrokeBits.zip)

**Comment by luboslenco** [comment]
Should be resolved now, please let me know if you get to test it. Thanks for report!
