### ISSUE TITLE
Weird materials 2d Window and Nodes movement behavior

### ISSUE THREAD

**Issue by Marke747** [armory3d/armorpaint#402]
Using 0.8 on Win10.  Been using v.7, so not altogether a newbie.

If I hit Tab to open the materials window, and then grab **one** node and try to move it, yes it moves, but so does everything/every other node/canvas background move also! 

I want to be able to move ONLY that node that is selected. (just like in v.7)

I tried changing the camera settings, but there seems to be no effect on this all-node-move behavior.

How do I make the node background and unselected nodes stay/stick in place if I want to move one (or a couple of selected) node/s around?   Is this some sort of new feature or a v0.8 bug that others can replicate?

Aside from being very unnatural, this behavior is stopping me from using the value sliders in any node - if I grab it to change that nodes values then the whole darn node/canvas/everything moves too!

Have I inadvertently pressed some combination of keys to make this happen?

**Comment by Marke747** [comment]
Just noticed that #401 also mentioned this deeper in the bug report. So yes, I see this/confirm that this is an issue.

**Comment by Marke747** [comment]
Impossible to now connect an added node -- trying to make the connection ust moves the whole canvas.

**Comment by Marke747** [comment]
Basically this version is unuseable (v0.8 (2020-05-100) - 8ce6c17
Win - direct3d11
gtx1080

**Comment by luboslenco** [comment]
I tested with the latest builds now (2020-05-29) and all seems well.
