### ISSUE TITLE
Program doesn't open when built

### ISSUE THREAD

**Issue by kgkatzonis** [armory3d/armorpaint#403]
Hello! I have built the executable but nothing happens when I try to open it.

**Comment by kgkatzonis** [comment]
Ok, So, I've copied krom.js into the release folder and now it runs but only as a background process.

**Comment by kgkatzonis** [comment]
I managed to get it working by copying the data folder and krom.js folder into the build folder along with Krom.exe

**Comment by luboslenco** [comment]
Yo! For future reference - that's what the build step

> Set `Project - Properties - Debugging - Command Arguments` to `..\..\build\krom`

is meant to do when running from Visual Studio.
