### ISSUE TITLE
Abort on MBP with Intel Iris graphics

### ISSUE THREAD

**Issue by virtualritz** [armory3d/armorpaint#404]
I'm building master on macOS 10.15 on a 2014 MacBookPro11,1:

```
Chipset Model:	Intel Iris
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x0a2e
  Revision ID:	0x0009
  Metal:	Supported, feature set macOS GPUFamily1 v4
  Displays:
BenQ EL2870U:
  Resolution:	3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition)
  UI Looks like:	3840 x 2160 @ 30 Hz
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Display Serial Number:	88K02466SL0 
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	Thunderbolt/DisplayPort
```

Amorpaint refuses to start:
```
$ ~/Library/Developer/Xcode/DerivedData/Krom-fqoepsfyctyjpfdyhovvzzrjmcwp/Build/Products/Debug/Krom.app/Contents/MacOS/Krom
2020-05-19 15:31:24.103 Krom[82896:6341670] fragment shader color output does not have enough components for the pixel format (MTLPixelFormatBGRA8Unorm)
Assertion failed: (pipeline->impl._pipeline && !errors), function kinc_g5_pipeline_compile, file /Users/moritz/code/armorpaint/Kromx/Kinc/Backends/Graphics5/Metal/Sources/Kore/PipelineState5Impl.mm, line 162.
[1]    82896 abort
```

As I'm running stuff like Substance Painter (and games written in Haxe, e.g. Dead Cells) w/o issues on this laptop I wonder if this is a limitation on the side of Amorpaint that could be lifted somehow?

**Comment by luboslenco** [comment]
I am transitioning ArmorPaint from OpenGL to Metal and need to iron a few more issues, sorry. Will post at https://github.com/armory3d/armorpaint/issues/394 asap.

**Comment by virtualritz** [comment]
Awesome!!! I donate some $$ as soon as this runs, promised.

**Comment by virtualritz** [comment]
Also: how hard would it be for someone like me who doesn't know the codebase to hook up a third party offline renderer with Amorpaint? I have about 25 years of C/C++ experience, mostly with computer graphics stuff but I never touched Haxe.

I would have to wrap a single C header for Haxe on the API side so I don't think this is an issue. I am more talking app architecture.

**Comment by Calinou** [comment]
> I have about 25 years of C/C++ experience, mostly with computer graphics stuff but I never touched Haxe.

Haxe should be quite easy to learn, especially if you have experience with C++. I managed to [add internationalization support](https://github.com/armory3d/armorpaint/pull/329) without any prior Haxe experience.

**Comment by luboslenco** [comment]
Maybe taking the approach like https://github.com/PiloeGAO/Blender-ArmorPaintLiveLink would do? Or using it directly to render with Cycles?

The textures and mesh can be exported from ArmorPaint by passing arguments via terminal / command line, and then feeding that to another software should be straightforward.

**Comment by virtualritz** [comment]
I just built master and the issue persists. Although I do get to see the UI for a second now before it crashes.
