### ISSUE TITLE
Symmetry error

### ISSUE THREAD

**Issue by jjdp0** [armory3d/armorpaint#405]
_Armor Paint v 0.8, Windows 10 x64_

Symmetry on the other side is unfinished compared to the painted side.

**Comment by jjdp0** [comment]
![bug](https://user-images.githubusercontent.com/65613096/82391406-343fba00-9a0f-11ea-81f7-12eab0ee7237.png)
 
Model owned by Frontier, modified by me.

**Comment by luboslenco** [comment]
Should be better now in latest builds, thanks for report.
