### ISSUE TITLE
Normal map painting.

### ISSUE THREAD

**Issue by Appsepsi** [armory3d/armorpaint#408]
Option to create normal map patterns. Inspired by feature in substance designer.
![t](https://user-images.githubusercontent.com/52209860/82660067-f9fe3480-9c29-11ea-9d55-7cba4717b2eb.PNG)
![t2](https://user-images.githubusercontent.com/52209860/82660075-fc608e80-9c29-11ea-9abe-04c7a8ccc88c.PNG)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armorpaint/issues/244.
