### ISSUE TITLE
Drag and drop 

### ISSUE THREAD

**Issue by Granada1** [armory3d/armorpaint#41]
Drag and drop not working for me tested model in APaint 4 and it’s ok but not working in 5,I can link you the model tomorrow when I’m on my comp again

Windows 10 Pro 64 bit
GeForce GTX 1050 Ti
AMD FX (tm)-9590 Eight-core Processor
31.96 GB RAM
1920x1080,60 Hz

**Comment by luboslenco** [comment]
Looking forward to the model file, will fix it asap.

**Comment by Granada1** [comment]
Sorry busy day
https://we.tl/t-RSREwOhIbN
Feel free to use the model for Apaint i made it for testing

**Comment by luboslenco** [comment]
Thanks for the file! It seems to work for me on Windows 10.:( Maybe it's issue with drag and drop itself not working? Do other files work ok on your system?

Some tested files if needed:
https://github.com/armory3d/armorpaint_samples/releases

![123](https://user-images.githubusercontent.com/3685704/48301142-3a370f80-e4e9-11e8-8565-86b782b13440.jpg)

**Comment by Granada1** [comment]
Deleted original downloaded again ,pleased to say everything working as expected.something must have got corrupted along the line ,sorry for mucking you about

**Comment by Granada1** [comment]
Solved
