### ISSUE TITLE
Normal /height map blending

### ISSUE THREAD

**Issue by DrasChannel** [armory3d/armorpaint#410]
Blending between two materials based on normal map or height map.
![image_34787](https://user-images.githubusercontent.com/52209860/82661555-8c9fd300-9c2c-11ea-80a3-892bb298b160.jpg)

**Comment by luboslenco** [comment]
Pushed one more fix at https://github.com/armory3d/armorpaint/commit/6ba903ced62cb7ccf9633267032a310af81ecb45 - it's possible to mix materials via material nodes now, and also use node groups to make it more convenient via single node.

![cap](https://user-images.githubusercontent.com/3685704/106170654-f21b6a80-6190-11eb-993a-b369402de283.png)
