### ISSUE TITLE
Drag and drop layer into layer group

### ISSUE THREAD

**Issue by cgvirus** [armory3d/armorpaint#413]
Hello, Currently I can put only one layer in a group by right click>to Group. 
How to send some other layers into that group folder?
Thanks.

**Comment by bmobius** [comment]
If you right-click on any layer, you can use "Move Up" or "Move Down" to change that layer's position in the Layer Stack. If you do that to any layer directly above or below a group (folder), it will move that layer into that group.

**Comment by cgvirus** [comment]
Thanks! Now I get it.

**Comment by bmobius** [comment]
Great! There's a lot of little things like this within Armor Paint that aren't readily explained by the developer. It took me a bit to figure out how to just rename Layers, lol. I love this app like crazy, but it still has a ways to go.

**Comment by cgvirus** [comment]
What I have realized: This is a great piece of software but the UI needs some sanding to make it user friendly. I want to see this app grow. I will list some UI bugs soon. Thanks for your help.

**Comment by luboslenco** [comment]
Eventually it's supposed to work by simply drag and dropping layer into the group as well, reopening to keep me reminded. :)

**Comment by luboslenco** [comment]
Both layers and groups can now be drag and dropped. Layers can be dropped into groups.
