### ISSUE TITLE
build to windows using azure devOps

### ISSUE THREAD

**Issue by Xephobia** [armory3d/armorpaint#414]
Hello, i'm trying to build to windows, everything is sucessful but when i try too launc krom.exe, it don't do anything. I have figured out later that i need to set `Project - Properties - Debugging - Command Arguments to ..\..\build\krom` in visual studio but i have no ideo how to do it with visual studio build task.

**Comment by luboslenco** [comment]
Hi, the `set Project - Properties - Debugging - Command Arguments to ..\..\build\krom` should be an equivalent to launching via command line manually as `.\Krom.exe ..\..\build\krom`.
