### ISSUE TITLE
Ability to name layers

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#416]
Good evening! I beg! You are welcome! You can add a function to give names to the layers and materials that are created

**Comment by bmobius** [comment]
You can already name layers and materials to whatever you like. Here's how it's done:

1. Create a new Layer or Material
2. Double Left-Click on your new material or layer. This will open up either the 2D view (for Layers) or Node View (for Materials).
3. In the bottom right-hand corner of either the 2D View or Node View is the name of the Layer or Material
4. Left-Click on that name and it will highlight, letting you change it to whatever you like!

These steps also work for Groups as well. Just Double Left-Click on the Group folder icon and you will see the Group name in your 2D View.

Here's a screen shot from ArmorPaint showning renamed Layers and Groups
![Grouping](https://user-images.githubusercontent.com/55331550/82950922-1a482f00-9f5b-11ea-860e-d3e71264a30a.jpg)

**Comment by luboslenco** [comment]
Will add an option to rename directly in the tab soon-ish to make it easier. 🔨

**Comment by AlexKiryanov** [comment]
Thank you so much! bmobius
Thank you so much! luboslenco
Yes, it’s better to do it directly in layers, as in all photo editors.
Just intuitively, I did not immediately understand what to call layers in the lower right corner.
And the materials, for example, are so signed imnea and there you can rename them
![Untitled-2](https://user-images.githubusercontent.com/65244629/83001657-b8e49680-a014-11ea-8013-dae6e3bd5fa8.jpg)

**Comment by luboslenco** [comment]
Awesome! Working on the material names as well - there is an experimental option at `Preferences - Interface - Show Asset Names`. Will enable it by default in the future.

![asset_names](https://user-images.githubusercontent.com/3685704/83003979-5b9a1680-a00f-11ea-91aa-5235d83897d4.jpg)

**Comment by AlexKiryanov** [comment]
Super! Thank!
