### ISSUE TITLE
Fail building: depth_attachment_bits is not a member of kinc_g4_pipeline

### ISSUE THREAD

**Issue by Xephobia** [armory3d/armorpaint#417]
I got those error wich prevented me for building
```
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(1183,35): error C2039: 'depth_attachment_bits': is not a member of 'kinc_g4_pipeline' [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(1184,37): error C2039: 'stencil_attachment_bits': is not a member of 'kinc_g4_pipeline' [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
```
i use node Kinc/make -g direct3d11 --compile with a forked version of this repo, i use github actions for this, check the run : https://github.com/Xephobia/armorpaint/runs/712431080

**Comment by luboslenco** [comment]
Aware & working on it, in the meantime you can get around it by either using the most recent [Kinc](https://github.com/Kode/Kinc) or switching to the https://github.com/armory3d/armorpaint/commit/c916f99636be6b50ffc5804f1fbe4c9570b3cfc6. Updated the title since it's dead on [linux](https://github.com/armory3d/Kromx/actions) and macos as well. 💀

**Comment by luboslenco** [comment]
It's back!

**Comment by Noahthenoob53** [comment]
Thank you, got directed here. It works now!

**Comment by luboslenco** [comment]
Can you paste the output from visual studio?

**Comment by Noahthenoob53** [comment]
There is no really an output. It says 1 successful, no other errors but soon as I go to the 64x folder where the exe file is located and try to start, nothing at all happens. Im really not trying to annoy you in any way I can just buy the programm but for some people who wants to try it for free might be dissapointed or confused!

**Comment by luboslenco** [comment]
DId you follow the step below from the [readme](https://github.com/armory3d/armorpaint/blob/master/README.md)? In Visual Studio:
> Set `Project - Properties - Debugging - Command Arguments` to `..\..\build\krom`

You should be able to run it straight from the Visual Studio.

**Comment by Noahthenoob53** [comment]
Yeah I did it but still nothing happens. 4 weeks ago I did every step and it worked. It launched immediately from visual studio and from the exe file. Maybe I could be wrong again, I tried it like 5 times before and after you fixed it with the g4_pipeline

**Comment by Xephobia** [comment]
i openned an issue with that and he answered me : https://github.com/armory3d/armorpaint/issues/414

you can just do .\Krom.exe wherethekromjsfolderislocated in powershell
