### ISSUE TITLE
Emissive text glitch

### ISSUE THREAD

**Issue by DrasChannel** [armory3d/armorpaint#419]
Hi, when I paint text with emissive material, it creates an emissive square around it.
Material attributes are specified in image below.

Armorpaint v 0.8
Windows

![1](https://user-images.githubusercontent.com/52209860/83036065-80f04a00-a03a-11ea-8326-bae2db347293.PNG)

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/70640a9ec3b27f724872a8bd386eb17e04383d15, will be live in upcoming builds. Thanks for report!
