### ISSUE TITLE
Compiling with master armsdk - crash while starting

### ISSUE THREAD

**Issue by DiegoBM** [armory3d/armorpaint#42]
The latest master version of armorpaint crashes on Windows 10. At least on my Microsoft Surface Book.
I'm building with Blender 2.79 with the current version of "master" for the armsdk (and all its sub-modules). Everything builds ok, but when it's time to run I can see the Krom window for a few seconds (completely blank) and after that it will disappear. This would be my console output:

...
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Finished in 9.391501665115356
Uniform brushScale not found.

Building with C++ will yield similar results (without the brushScale message), I can simply see the window for a couple of seconds for it to immediately disappear.

Note: I can build and run properly with the built-in sdk a previous version of armorpaint (from one month ago to be precise) so it's not like I never managed to run it.
Note2: Using blender 2.8 will yield same output for all cycles, eevee and armory engines selected

**Comment by DiegoBM** [comment]
According to the source comments seems to be a known issue. Closing

**Comment by DiegoBM** [comment]
It has nothing to do with that Uniform "brushScale", since that same message appears on the previous version that I can build and run properly. The master version simply crashes with no message, reason, or leaving any kind of log file/data behind when you try to run it, after displaying 2 seconds of an empty window. Any feedback would be appreciated

P.S.: Menus look incredibly small on the Surface Book

**Comment by DiegoBM** [comment]
Nothing? Just a title change?

**Comment by luboslenco** [comment]
Please let me know if you get to test it using the latest Armory 0.6beta build. I have updated the [readme](https://github.com/armory3d/armorpaint/blob/master/README.md), on Windows the graphics api needs to be set to opengl (but soon it will work using direct3d11 as well).

To combat tiny menus raising the `Preferences - Interface - UI Scale` slider should help.

**Comment by DiegoBM** [comment]
Thank you @luboslenco for the update. I actually tried a couple of days ago with the 0.6 beta and it worked flawlessly! Great job! I haven't tried on the Surface Book again since the graphics card is less capable than my desktop one, but I'll try to give it a go as well to the UI scale setting. Thank you again for your hard work :)

**Comment by DiegoBM** [comment]
I have just tried on the Surface Book and compiled successfully with zero effort but menus still look really small. I understand that 

> To combat tiny menus raising the Preferences - Interface - UI Scale slider should help.
I understand that by preferences you mean Blender preferences, the resolution Scale setting. In any case blender menus all look ok in size, is armorpaint's internal menus the ones that look small. I haved tried anyways increasing the resolution scale but that didn't affect armorpaint's menus, only blender's

**Comment by luboslenco** [comment]
Yay, great it worked!

Sorry, I should have clarified about the UI Scale - ArmorPaint has it built-in so you can tweak it at run-time. The image below should show it the best. Some scaling issues may still be there but at least the basics should work.

![1](https://user-images.githubusercontent.com/3685704/51902726-f30b3d00-23ba-11e9-9ebf-d5b98370351c.PNG)

**Comment by DiegoBM** [comment]
Doh! Silly me! You are correct, you UI scale setting fixes it properly. It now looks good! Thanks for the hint!
