### ISSUE TITLE
Cant install armorpaint (Error in visual studio)

### ISSUE THREAD

**Issue by Noahthenoob53** [armory3d/armorpaint#420]
Everytime when I try to download armorpaint it gives me this error in visual studio:
Armorpaint\armorpaint\Kromx\Sources\main.cpp(1183,35): error C2039
Armorpaint\armorpaint\Kromx\Kinc\Sources\kinc\graphics4\pipeline.h(57):
Armorpaint\armorpaint\Kromx\Sources\main.cpp(1184,37): error C2039
Armorpaint\armorpaint\Kromx\Kinc\Sources\kinc\graphics4\pipeline.h(57)

**Comment by luboslenco** [comment]
Check my comment here https://github.com/armory3d/armorpaint/issues/417.
