### ISSUE TITLE
Ability to set color by numbers

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#421]
Hello everyone! Maybe this will seem stupid. But you can add a function to set the color with numbers. According to the RGB or like that #ffffff Or can it be done somehow already?

**Comment by luboslenco** [comment]
Will make it happen, linking with https://github.com/armory3d/armorpaint/issues/216. Thanks for request!

**Comment by arun54321** [comment]
Please add eyedropper tool too to pick colors.

**Comment by luboslenco** [comment]
@arun54321 will do, thanks for suggestion! Right now the Picker tool can display the picked color values but it's not very useful yet. Will post progress at https://github.com/armory3d/armorpaint/issues/275.
