### ISSUE TITLE
How to save program settings?

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#422]
I want to in the program settings panel, set the parameters I need. After closing the program, I reopen it, and the settings are standard

**Comment by Calinou** [comment]
Which OS and ArmorPaint version are you using? On Windows, make sure to place the ArmorPaint installation folder in a writable location (i.e. **not** Program Files).

**Comment by AlexKiryanov** [comment]
Hello! And I just put her there!)))  Thanks a lot! I'll try!

**Comment by luboslenco** [comment]
Just to note:
- Settings get auto-saved when preferences window gets closed
- I pushed some fixes so all of the individual settings should get saved now
- Settings should also get saved when ArmorPaint is located at `Program Files` nowadays (will be saved into user folder). If not please throw me a bug report.

**Comment by AlexKiryanov** [comment]
Good afternoon! Lubos!
Checked! Yes, it is now saved even if in the  Program Files
Thank you so much!

чт, 11 июн. 2020 г. в 12:30, Lubos Lenco <notifications@github.com>:
