### ISSUE TITLE
ArmorPaint cannot correctly import EnvMap!

### ISSUE THREAD

**Issue by bmobius** [armory3d/armorpaint#425]
*Please specify your ArmorPaint version and OS.*
ArmorPaint Version: V0.8 (2020-05-29) - e5733c5
Windows 10 Pro Version 1909 / Build 18363.836
Direct3D11
Nvidia GeForce GTX 980 Ti

Like the title says, if I have ArmorPaint installed on my C: drive which is where I also have Windows 10, I cannot correctly import an .hdr EnvMap.

1. Attempted EnvMap import via Viewport > Import Envmap...
2. EnvMap will show up as a texture in the Texture tab.
3. Viewport fails to update with imported EnvMap.
4. A second attempt to import any .hdr causes ArmorPaint to crash to desktop.

This issue does not present itself if the install location for ArmorPaint is a non-system, non-protected location. I've tested this by installing ArmorPaint on a different drive and the entire application works as intended.

No changes to permissions for the .exe seem to work. Application is being run as an Administrator. Exceptions have been added to my firewall and my anti-virus for the ArmorPaint EXE.

**Comment by luboslenco** [comment]
Please no duplicates, will fix at https://github.com/armory3d/armorpaint/issues/362, thanks!

**Comment by bmobius** [comment]
Understood. I appreciate everything you do and I cannot thank you enough!

**Comment by luboslenco** [comment]
Sorry it's taking so long, happy for every reported issue. 🔨

**Comment by bmobius** [comment]
You have officially fixed the EnvMap import issue on a protected install path! Thank you! But I did notice that if I pan the EnvMap (ctrl + middle-click) it causes the EnvMap to stretch and distort.
![EnvMap Distortion](https://user-images.githubusercontent.com/55331550/86517369-3f8f4f00-bddd-11ea-8ef0-45422c22910f.jpg)

**Comment by luboslenco** [comment]
Should be now resolved as well, thanks for letting me know!

**Comment by bmobius** [comment]
Lubo, it works like a dream now! LIKE A DREAM! Thank you so much for that AND for expanding the color wheel!

**Comment by luboslenco** [comment]
Happy to hear! 😍😍
