### ISSUE TITLE
compilation does not works with direct3d 12

### ISSUE THREAD

**Issue by Xephobia** [armory3d/armorpaint#426]
see run : https://github.com/Xephobia/armorpaint/runs/724525732?check_suite_focus=true

**Comment by Xephobia** [comment]
`##[error]Process completed with exit code 1.
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2480,36): error C2065: 'pipeline': undeclared identifier [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2480,4): error C3861: 'kinc_raytrace_pipeline_destroy': identifier not found [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2499,32): error C2065: 'pipeline': undeclared identifier [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2499,3): error C3861: 'kinc_raytrace_pipeline_init': identifier not found [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2501,46): error C2065: 'accel': undeclared identifier [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2501,3): error C3861: 'kinc_raytrace_acceleration_structure_init': identifier not found [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2546,3): error C3861: 'kinc_raytrace_set_textures': identifier not found [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2566,45): error C2065: 'accel': undeclared identifier [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2566,3): error C3861: 'kinc_raytrace_set_acceleration_structure': identifier not found [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2567,31): error C2065: 'pipeline': undeclared identifier [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2567,3): error C3861: 'kinc_raytrace_set_pipeline': identifier not found [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2568,3): error C3861: 'kinc_raytrace_set_target': identifier not found [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
##[error]     1>D:\a\armorpaint\armorpaint\Kromx\Sources\main.cpp(2569,3): error C3861: 'kinc_raytrace_dispatch_rays': identifier not found [D:\a\armorpaint\armorpaint\Kromx\build\Krom.vcxproj]
Build time: 0m 52s
Compilation failed.
##[error]Process completed with exit code 1.`

**Comment by luboslenco** [comment]
Updated the instructions with:

> git apply patch/d3d12_raytrace.diff --directory=Kinc

With the patch applied d3d12 compilation should succeed. I plan to open a Kinc PR which will make this step redundant but it's not ready yet.
