### ISSUE TITLE
crash when switching to mobile render path on direct3d 11

### ISSUE THREAD

**Issue by Xephobia** [armory3d/armorpaint#427]
*Please specify your ArmorPaint version and OS.*
latest armory commits, windows 10 and AMD Ryzen 5 2500U with radeon mobile GFX (Vega 8) Ram : 8GO (6,90 GO usuable)

**Comment by luboslenco** [comment]
Can you paste the output from Visual Studio?

**Comment by Xephobia** [comment]
The problem is that i used Github actions because my pc does not have enough space for vs. Does visualstudio stores his log in a file?

**Comment by Xephobia** [comment]
ho i know, i can just set the verbosity level in msbuild! Also what are Krom.tlog folder, it is a log folder from Krom.exe?

**Comment by luboslenco** [comment]
No idea, sorry, but fixed the issue at https://github.com/armory3d/armorpaint/commit/a3eb850e8b4ce7190b41a84c405075f8cdd0cda8. Thanks for report.
