### ISSUE TITLE
Opacity parametr in the material not working properly

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#429]
Win 64 v 0.8 2020.05.12
Good afternoon! For several days now, I’ve been trying to make glass material! But unsuccessfully! Faced a problem. The transparency parameter in the material does not work correctly. If you lower this parameter, the material goes black. Is this the way it should be, or am I not understanding something?
![Untitled-1](https://user-images.githubusercontent.com/65244629/83496485-d5c01480-a4c1-11ea-9a87-ebf91744d5d3.jpg)

**Comment by luboslenco** [comment]
Yo! Sorry, still working on the trasparency - will post at https://github.com/armory3d/armorpaint/issues/265 asap.
