### ISSUE TITLE
0.8 mac installation "scrambled UVs"

### ISSUE THREAD

**Issue by jamiedixxon** [armory3d/armorpaint#434]
Just purchased and downloaded... Mac OSX Catalina 10.15.4 / armorpaint 0.8dev (e5733c5)

Loading a mesh with unwrapped UV displays a scattered result. Painting on the mesh jumps and fills in randomly. Is the screen space to UV mapping having an issue?

Here's the result in armorpaint, the uv's and the exported map:

![Screen Shot 2020-06-03 at 2 52 30 PM](https://user-images.githubusercontent.com/50497503/83693096-2d39af80-a5aa-11ea-81b2-c1a0f5830bf3.png)

<img width="554" alt="Screen Shot 2020-06-03 at 2 53 57 PM" src="https://user-images.githubusercontent.com/50497503/83693106-3a569e80-a5aa-11ea-83c0-01b3a6e6d585.png">

![Untitled_base](https://user-images.githubusercontent.com/50497503/83693119-417dac80-a5aa-11ea-9133-621f59d73c76.png)

**Comment by jamiedixxon** [comment]
solved - there were a couple of polys that had overlapping UVs (duh!)

**Comment by luboslenco** [comment]
Glad to hear!
