### ISSUE TITLE
can't launch git version from linux

### ISSUE THREAD

**Issue by Xephobia** [armory3d/armorpaint#435]
**ArmorPaint version:**
latest git

**OS/device including version:**
Lubuntu in virtualbox on windows

**Issue description:**
building happend corectly but when i try to launch, got a bunch of errors like those : ` GL Error 1281 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 242` 

`GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp 309`

**Comment by luboslenco** [comment]
You are most likely running some ancient opengl version in virtualbox, I believe `opengl 3.3` is the minimum for opengl backend.

**Comment by Xephobia** [comment]
do you know how to update openGL in virtual box?

**Comment by luboslenco** [comment]
I do not think it's possible in virtualbox. :( Happy to be proved wrong though.

**Comment by darkbox** [comment]
Having same issue on real hardware running nvidia-440 drivers (Ubuntu 20.04 LTS).

> GL Error 1281 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 164
> GL Error 1281 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 171
> GL Error 1281 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 171
> GL Error 1281 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 171
> GLSL linker error: 
> GL Error 1281 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392
> Uniform projectionMatrix not found.
> GL Error 1281 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410
> Segmentation fault (core dumped)

glxinfo:
> glxinfo | grep version
> server glx version string: 1.4
> client glx version string: 1.4
> GLX version: 1.4
> OpenGL core profile version string: 4.6.0 NVIDIA 440.64
> OpenGL core profile shading language version string: 4.60 NVIDIA
> OpenGL version string: 4.6.0 NVIDIA 440.64
> OpenGL shading language version string: 4.60 NVIDIA
> OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 440.64
>OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

PS: lastest git
