### ISSUE TITLE
Name materials and layers bug

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#436]
Win 64 v 0.8 2020.06.03 45d1379

Good afternoon! I name materials and layers. Keep checking. After closing the program, I launch Armorpoint again. I open the project and the names are all erased.
![1](https://user-images.githubusercontent.com/65244629/83887639-63fdfa00-a751-11ea-8a91-f262505fda6c.jpg)
![2](https://user-images.githubusercontent.com/65244629/83887644-64969080-a751-11ea-9260-7a92cac034da.jpg)

**Comment by AlexKiryanov** [comment]
Bug fixed!
Thank you Lubos!

**Comment by luboslenco** [comment]
Yay!
