### ISSUE TITLE
menu in layers window always visible

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#438]
Good afternoon! You can make the menu in the window with layers always visible even when you turn the layers down. Because when there are a lot of layers, you leaf them down, and then you need to go back up to select an object, for example, or a new layer.
![1](https://user-images.githubusercontent.com/65244629/83891596-189a1a80-a756-11ea-8660-bd34681ee29a.jpg)

**Comment by luboslenco** [comment]
Fixed via https://github.com/armory3d/armorpaint/commit/4a013da48bbccf4b2e92283114841d8f9a0d377b and https://github.com/armory3d/zui/commit/66336a9ca1412087683ac43ff896c23d77ab246d, tab headers are not going anywhere now. Thanks for report!

![cap](https://user-images.githubusercontent.com/3685704/87029687-c4fd6f80-c1e0-11ea-8512-fad94ad72c46.PNG)

**Comment by AlexKiryanov** [comment]
Thank you so much! This is really very convenient when you do not have to
scroll a bunch of layers up and down.)))

чт, 9 июл. 2020 г. в 13:37, Lubos Lenco <notifications@github.com>:
