### ISSUE TITLE
baking Ambient Occlusion bug

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#439]
Win 64 v 0.8 2020.06.03 45d1379

Good afternoon! When I bake a map of AO, I observe these circles.
![1](https://user-images.githubusercontent.com/65244629/83892380-42077600-a757-11ea-8130-b9d4eeb2de1b.jpg)
![2](https://user-images.githubusercontent.com/65244629/83892388-4338a300-a757-11ea-9a31-38456e25c7b0.jpg)

**Comment by luboslenco** [comment]
The reason is that non-DXR builds fall back to voxels for baking AO. If you use `ArmorPaintDXR` builds instead, you will get ray-traced AO baking. The current requirements for DXR builds can be seen [here](https://github.com/armory3d/armorpaint/blob/master/Assets/readme/readme_dxr.txt).

**Comment by AlexKiryanov** [comment]
Thank you so much!

**Comment by luboslenco** [comment]
No prob, thanks for reporting issues!

**Comment by AlexKiryanov** [comment]
You are welcome!))

пн, 8 июн. 2020 г. в 18:50, Lubos Lenco <notifications@github.com>:
