### ISSUE TITLE
Remember window size on Linux / macOS

### ISSUE THREAD

**Issue by Xephobia** [armory3d/armorpaint#440]
It would be cool if you launch the windows maximized by default because when the windows spawn, it's in the top and we need to move it and resize it

**Comment by AlexKiryanov** [comment]
Hello! I solved this problem like this)
![Untitled-1](https://user-images.githubusercontent.com/65244629/83915949-f23ba580-a77c-11ea-86b1-943631fc6ad5.jpg)

**Comment by Xephobia** [comment]
ok ok that's fun for windows

**but for linux?**

**Comment by R-J-Dawson** [comment]
> _AlexKiryanov_
> Hello! I solved this problem like this)

Thanks! Works a treat with the desktop shortcut, unfortunately it doesn't work with KeyPirinha or the ArmorPaint Blender Link addon.

**Comment by AlexKiryanov** [comment]
You are welcome!
Yes, we are waiting for corrections

**Comment by Calinou** [comment]
@Xephobia Which desktop environment/window manager are you using? Several window managers (like KWin) expose a way to force a window the maximized at startup. Try clicking the icon in the top-left corner of the window then choose **Special Application Settings...**.

**Comment by luboslenco** [comment]
On Windows ArmorPaint should remember the window size / position from previous run (if it does not for someone please open a bug report). On Linux / macOS it is yet to be implemented.

Another temporary workaround might be to open `ArmorPaint/data/config.arm` file in text editor and set `window_w`, `window_h`, `window_x`, `window_y` to desired values.

**Comment by AlexKiryanov** [comment]
Checked. No, it does not work. Windows does not remember the size and position of the last session armorpaint.

**Comment by Xephobia** [comment]
while you fix the error, can you make an option to launch armorpaint in fullscreen? not in maximized windowed mode

**Comment by Calinou** [comment]
@Xephobia I think a fullscreen toggle would be sufficient, no? I don't know if it makes sense to provide a fullscreen option.

Maybe ArmorPaint could remember its fullscreen status when you close it, but I don't think adding a dedicated option makes sense.

**Comment by AlexKiryanov** [comment]
I managed to set up just like this ...
The expand to full window mode does not work for some reason.
But the window size in pixels of the program understands and makes the correct location.
![1](https://user-images.githubusercontent.com/65244629/84578861-a9fe3200-add1-11ea-9691-6c9092ff1fef.png)
![2](https://user-images.githubusercontent.com/65244629/84578862-aa96c880-add1-11ea-867a-675671cf29af.png)

**Comment by luboslenco** [comment]
Both Windows and Linux builds should remember the window size now, macos still wip.

**Comment by AlexKiryanov** [comment]
Yes confirm! this works correctly!

**Comment by luboslenco** [comment]
Also on macos now.
