### ISSUE TITLE
add more algorithms in Voronoi node

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#441]
I have one question, there is a Voronoi node in ArmorPaint.
Is it possible to add to it all the algorithms as in the 3D blender? I mean:
minkowski, manhattan, chebychev
Or at least the first
Thank!

**Comment by jcostello** [comment]
Also more scale

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/36, working to sync all material nodes 1:1.

**Comment by AlexKiryanov** [comment]
Good evening! it's good news that work on the node system is underway.
thank you very much for your work!

чт, 14 янв. 2021 г., 21:39 Lubos Lenco <notifications@github.com>:
