### ISSUE TITLE
Auto-update / overwrite imported textures functionality.

### ISSUE THREAD

**Issue by R-J-Dawson** [armory3d/armorpaint#442]
Hi there Lubos,

I wondered if it would be possible to include auto-update / overwrite functionality to textures that have been imported. For example; when I've imported a decal texture of a poster into ArmorPaint, the source file to that poster texture cannot be altered in photoshop and overwritten. I have to save a new file and import the new file into ArmorPaint instead.

Kind regards and keep up the great work!
-R

**Comment by luboslenco** [comment]
Thanks for the feature request! Did some improvements in latest builds:
- Texture source file can be overwritten now
- Added `File - Reimport Textures` operator which reloads all textures
- Added `Textures tab - Right click on texture - Reimport` operator which reloads selected texture

**Comment by R-J-Dawson** [comment]
> Thanks for the feature request! Did some improvements in latest builds:
>     * Texture source file can be overwritten now
>     * Added `File - Reimport Textures` operator which reloads all textures
>     * Added `Textures tab - Right click on texture - Reimport` operator which reloads selected texture

Wow, sounds perfect. Thank you Lubos!

**Comment by luboslenco** [comment]
Happy to hear!
