### ISSUE TITLE
armorpaint does not support Asian languages

### ISSUE THREAD

**Issue by zxq2233** [armory3d/armorpaint#443]
Hello, I am from Japan.
I have compiled armorpaint for success.
I have created a new language for armorpaint and it does not seem to display Asian characters correctly. Is there a solution?
![QQ截图20200607071040](https://user-images.githubusercontent.com/14195738/83956231-41253000-a88e-11ea-8986-9ff6aa4571e3.png)

**Comment by zxq2233** [comment]
@1234EMMM

**Comment by Calinou** [comment]
Translations for CJK languages should probably be disabled until ArmorPaint is able to display the required characters. (We can disable them by renaming the translation files so they won't match.)

**Comment by luboslenco** [comment]
@zxq2233 @1234EMMM I have pushed some fixes, characters should display now. There are some alignment issues which I will look into fixing. 🙂

![cjk](https://user-images.githubusercontent.com/3685704/84376661-c8054000-abe1-11ea-8c56-29fd25c3ea1c.jpg)

**Comment by 1234EMMM** [comment]
Thank you very much.
