### ISSUE TITLE
Smooth node connections

### ISSUE THREAD

**Issue by Appsepsi** [armory3d/armorpaint#444]
Hi, I think it would be better to have option to switch between straight and smooth connections between nodes. Smooth connections are better in more complex materials. I prefer it because it looks more clean ,organized and it is easier to orientate in the graph. I is used in programs like unreal engine, cinema 4D or substance designer.
![external-content duckduckgo](https://user-images.githubusercontent.com/52209860/84364278-2c1f0880-abd0-11ea-85ea-b2b0cf8fb408.png)

**Comment by luboslenco** [comment]
Hi. There is a 'buried' option for this (contributed at https://github.com/armory3d/zui/commit/02ed787d8edcf7a784020d21cb17ec193ed4e94f). Go to `Edit - Preferences... - Theme` and click `New` to create a new theme (this way theme changes get saved permanently). Afterwards, change the `LINK_STYLE` property of the theme to `1`.

Please keep the issue open, will rework this option to make it clearer.

<img width="979" alt="smooth" src="https://user-images.githubusercontent.com/3685704/84364905-01817f80-abd1-11ea-91a7-367ff0e95470.png">

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/eb94d498b51ee07f936358e7f89dac3736957aed. Will now display combo with `Straight` and `Curved` options.
