### ISSUE TITLE
Linux file manager error

### ISSUE THREAD

**Issue by RastaManKing** [armory3d/armorpaint#445]
Im running armourpaint in archlinux and every time i try to access a file (open, import, save, export..) the program crashes. if i go to preferences and disable native file manager option it works fine (open, import, save, export..) but settings are not saved witch is my problem, every time i start the program again i have to go to settings and uncheck the native file manager option...

**Comment by luboslenco** [comment]
Continuing at https://github.com/armory3d/armorpaint/issues/179 to keep it all in single issue.
