### ISSUE TITLE
Odd Camera Drift

### ISSUE THREAD

**Issue by R-J-Dawson** [armory3d/armorpaint#450]
Hey there,

When making changes to layers in ArmorPaint (in this specific instance, I'd merged down) I've had the viewport start behaving strangely. When right-clicking to rotate the camera, the camera will start to zoom in/out. Oddly, the more % the zoom is at, the faster the camera continues to zoom.

This can also cause the object to rotate wildly.
On one occasion, I've even had the camera move whilst painting in 2D view.
You can see in the link below. I both change the zoom (with the mouse wheel) and right-click to orbit, yet the camera always zooms.

[https://gfycat.com/idioticadoredborderterrier](url)

**NOTE: pressing NUM_0 fixes the issue.**

-R

**Comment by luboslenco** [comment]
Hi, any idea if I can reproduce it with some exact list of steps? I think the 2D view messes up the matrices in some cases but unable to reproduce it so far.

**Comment by R-J-Dawson** [comment]
> Hi, any idea if I can reproduce it with some exact list of steps? I think the 2D view messes up the matrices in some cases but unable to reproduce it so far.

Hi there, I've tried to recreate it and it's very inconsitent, I can't find a 100% way to recreate it. It seems to be a bug when zooming in/out and panning in 2D view. Suddenly the model in the 3D viewport will just rotate on it's side slightly. It's at this point that right-clicking in the 3D viewport will cause the camera to drift.. If you zoom in with the scroll wheel, the camera will drift forwards at a speed equivelant to the amount of zoom. Vice versa for zooming out (holding right click will drift out; the more zoomed out with the scroll wheel, the faster the reverse drift).

Apologies for not having a more concrete answer. If I can find a reliable way to reproduce the drift, I'll update you.

**Comment by luboslenco** [comment]
If anyone still gets this after https://github.com/armory3d/armorpaint/commit/a7bfba7b2ac287ea2e77d003939ad1e2dbe24c21 please let me know.
