### ISSUE TITLE
Simple Bake button instead of drag and hold

### ISSUE THREAD

**Issue by FraserHutchison** [armory3d/armorpaint#451]
I found the process of dragging/holding to bake a little confusing at first. Instead of this I think it would be great to maybe instead have a button that simply says **_start bake_**. A _**bake time**_ input could also be added in the same area to get around having to hold the button to state when you want the bake to end.

Keep up the great work!

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/7e2239bbd79085f609b32abc43763a9c4f19e094, thanks for report!
