### ISSUE TITLE
Blur node

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#454]
Good evening! As I understand it, the blob node only works with external images? Is there any way to work with maps created in armorpaint?

**Comment by Hopefullyidontgetbanned** [comment]
Here is a twitter thread i found that explains why it might not be possible, in regards to blender/but i assume the same applies to armorpaint

**Comment by AlexKiryanov** [comment]
Yes, it’s like that. very sorry
Thank you for finding this.

**Comment by unfa** [comment]
Fun fact - the Blender Voronoi Node has been rewritten and it now has a blur option, which works like a charm.

It doesn't change the fact that it's probably a clever trick in the Node algorithm, and can't be used for anything else.

**Comment by AlexKiryanov** [comment]
Good day! Is this in version 2.9? I just have 2.83 and I was very surprised after reading this message, because yesterday I used this node myself and I definitely remember that I did not see such a function.))))
For some reason, I also think so that this is most likely a trick, but it's still great.
Thanks for the news.

**Comment by unfa** [comment]
@AlexKiryanov Ah, it't note exactly blur, but it's smooth transitions between cell edges:

Looks fabulous though:

![image](https://user-images.githubusercontent.com/491704/89037454-ca149100-d33e-11ea-8b39-4cab9a84ee59.png)

**Comment by AlexKiryanov** [comment]
Yes, like gradient))

пт, 31 июл. 2020 г., 16:02 unfa <notifications@github.com>:

**Comment by luboslenco** [comment]
General `Blur` node has been added. One thing to keep in mind for now is that it converts the input into a texture (which is afterwards blurred), so mapping the output is similar to the `Image Texture` node.

**Comment by AlexKiryanov** [comment]
Thank you very much Lubos!

вт, 29 сент. 2020 г. в 13:22, Lubos Lenco <notifications@github.com>:
