### ISSUE TITLE
Color Ramp node bug

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#455]
Win 64
0.8 (2020.06.14)
I don’t know why, but for some reason such a bunch produces a bug.
We save the file with such material, everything works. Close the program, open and edit the material is not possible, black color and all. Without the Color Rump node, everything is saved and everything works, but not with it. Even if you just connect the gradient node and the Color Rump nodes
![1](https://user-images.githubusercontent.com/65244629/84700035-3720c280-af5b-11ea-81e3-bc2868e914bc.jpg)
![2](https://user-images.githubusercontent.com/65244629/84700040-3851ef80-af5b-11ea-8acf-52052fd14c0a.jpg)
![3](https://user-images.githubusercontent.com/65244629/84700043-3851ef80-af5b-11ea-9941-851ae64764da.jpg)

**Comment by luboslenco** [comment]
Nice! It should work now using the latest git version.

**Comment by AlexKiryanov** [comment]
Thank you very much

чт, 2 июл. 2020 г., 20:17 Lubos Lenco <notifications@github.com>:

**Comment by AlexKiryanov** [comment]
Checked! everything is working! Thanks again!
