### ISSUE TITLE
2 layers in one material do not work together

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#456]
Win 64
0.8 (2020.06.14)

good evening! Suppose I have 2 layers. One with a white circle. The second with a white rectangle.
I insert both layers into the material. One suppose in the color channel. The other is in the height channel.
In fact, we should get: either a white circle with an extruded rectangle, or a white rectangle with an extruded circle. But in the end it turns out that either a white circle is extruded or a white rectangle is extruded.
![1](https://user-images.githubusercontent.com/65244629/84702851-f2e3f100-af5f-11ea-8fa3-48aac9537406.jpg)
![2](https://user-images.githubusercontent.com/65244629/84702854-f4151e00-af5f-11ea-8504-8ba4f60687a0.jpg)
![3](https://user-images.githubusercontent.com/65244629/84702855-f4adb480-af5f-11ea-84c8-f13d6470d643.jpg)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/0b48062748bc4375d3e45df073352f34df9df8c8, thanks for report!

**Comment by AlexKiryanov** [comment]
Good afternoon, Lubos! glad to read you! Thank you so much! you are welcome)

ср, 24 июн. 2020 г., 20:16 Lubos Lenco <notifications@github.com>:
