### ISSUE TITLE
Browser Material Preview Strangeness (Red/Blue colour channel swap?)

### ISSUE THREAD

**Issue by oparaskos** [armory3d/armorpaint#458]
*ArmorPaint 0.8-5bccf1c, macOS*

I created some very basic materials to try out the browser and found some strangeness;

The basic materials are all a colour node piped into colour á la the default material

I created a blue material; the preview in the materials panel correctly shows it as blue exported the material, and found it in the browser and the material incorrectly shows as red.

I did the same for blue and green; Blue shows as red, and green as green

Here are the materials in the browser panel:
![Screenshot 2020-06-16 at 15 43 02](https://user-images.githubusercontent.com/8076088/84789771-7f39f680-afe8-11ea-868a-5081b4a9fe1f.png)

Here is the blue material after double clicking it from the browser panel to import it.

![Screenshot 2020-06-16 at 15 43 15](https://user-images.githubusercontent.com/8076088/84789791-882ac800-afe8-11ea-8fbe-513d72755207.png)

**Comment by oparaskos** [comment]
Obviously, this isnt high impact or urgency; I just wanted to note the strange behaviour for your awareness.

This is with Mac OSX Catalina, prebuilt v08 from gumroad.

**Comment by luboslenco** [comment]
Great catch, thanks for report! Should be resolved now via https://github.com/armory3d/armorpaint/commit/2493446549113f048f92dde8823b5705acd3416c, will be live in upcoming update.
