### ISSUE TITLE
Fill Layers to support opacity

### ISSUE THREAD

**Issue by oparaskos** [armory3d/armorpaint#460]
To enable more non-destructive editing I'd like it if Fill layers could stack, at the moment if a fill layer's opacity is 0 the generated texture shows that as base-color=black rather than opacity-map=black. 

This would enable composition/layering of transparent tiling materials, whilst preserving live-editing of UV Scale of those layers, and enable users to change from a low to a high resolution without any loss of detail.

**Here's an example of the current behaviour (Taken from v08 from GumRoad/Mac OSX Catalina)**
in this example a checker pattern controls opacity of a fill layer.
Underneath the fill layer is a fill layer of a solid red material
![Screenshot 2020-06-18 at 09 43 01](https://user-images.githubusercontent.com/8076088/84998736-21bcbb80-b148-11ea-8b6e-99b436d1c396.png)

![Screenshot 2020-06-18 at 09 36 37](https://user-images.githubusercontent.com/8076088/84998334-99d6b180-b147-11ea-9ea9-81ac213c2e3a.png)

[SimpleChecker.arm.zip](https://github.com/armory3d/armorpaint/files/4797380/SimpleChecker.arm.zip)

**What I'd like:**
I'd like the opacity map of the top checker layer to allow the red layer underneath to show through

![Screenshot 2020-06-18 at 09 39 02](https://user-images.githubusercontent.com/8076088/84998479-cd194080-b147-11ea-9e97-fb661cc917d1.png)
![Screenshot 2020-06-18 at 09 37 04](https://user-images.githubusercontent.com/8076088/84998492-cee30400-b147-11ea-8b28-cde759c977a8.png)

**Comment by luboslenco** [comment]
Fixed now in latest builds, thanks for report.

![b](https://user-images.githubusercontent.com/3685704/91167417-38493b00-e6d4-11ea-9f0e-fed0e0c57777.PNG)
