### ISSUE TITLE
Actualizacion

### ISSUE THREAD

**Issue by vonvivant** [armory3d/armorpaint#461]
**ArmorPaint version:**

**OS/device including version:**

**Issue description:**

en el sitio pricinpal del proyecto dice:
Armor paint se puede actualizar utilizando: Flibrary. con un link a https://gumroad.com/#login?next=%2Flibrary

Actualmente Flibrary en gumroad no existe

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Hi, please drop me an email with your email and I will investigate. If you do not have Gumroad account yet, then once you sign up with your original email ArmorPaint will be auto-added to your library.
