### ISSUE TITLE
Blurry texture from Scaling

### ISSUE THREAD

**Issue by christophsbl** [armory3d/armorpaint#465]
*ArmorPaint 0.8-5bccf1c, Windows*

when using a mapping node with big scaling (like 20 by 20) it happened to me that the resulting material (or the texture) was just a blurry mess compared to something I got in blender.
the normal (1 by 1) scaling is pretty comparable though.

**Comment by luboslenco** [comment]
Please let me know if this is still happening at https://github.com/armory3d/armorpaint/issues/471.
