### ISSUE TITLE
Bug at opening

### ISSUE THREAD

**Issue by julienduroure** [armory3d/armorpaint#47]
Using: 
- linux mint 19 (based on Ubuntu 18.10)
- geforce GTX 860M
- ArmorPaint 0.5

Steps:
- Open Armarpaint
- do not rotate, not zoom
- click to paint : a stroke is paint, instead of painting only a point

See this gif :
![bug_at_open](https://user-images.githubusercontent.com/1696020/48970752-60dc6680-f010-11e8-99ad-c604993913c6.gif)

**Comment by luboslenco** [comment]
Should be fixed in the new 0.6 dev build. 🙂
