### ISSUE TITLE
Weird stretching when using mapping node to scale a texture

### ISSUE THREAD

**Issue by Dummywumfk** [armory3d/armorpaint#471]
I'm using the mapping node paired with a UV map node to scale a texture to how I want it. The problem is that I when I set the scale value in the mapping node to anything >1, the texture scales down, but does not tile itself, so I'm left with the edge of the texture being drawn out forever into infinity. The part that confuses me is that I've gotten textures to tile before, using the same exact workflow.
Here's the result I get most of the time:
![bandicam 2020-06-21 22-34-29-870](https://user-images.githubusercontent.com/67255138/85252181-17ccde00-b410-11ea-9559-e08201c7fb79.jpg)

**Comment by luboslenco** [comment]
Hi, thanks for report. Does this still happen in latest 0.8 dev builds? It seems to work for me but if you can show me steps to reproduce I should be able to fix it.

**Comment by christophsbl** [comment]
hey, you told me to report if my problem is still happening in the latest 08dev_build (Im using the one I can download from your gumroad, is that the latest?) and my scaling problem is still appearing.

**Comment by Ebbombe** [comment]
I tried use the same process on a default cube and it works perfectly scaling up to 10 the texture, i tested on my project and it works, but if I choose a color id, and paint on the selected color id with the bucket tool the texture looks stretched.
![111](https://user-images.githubusercontent.com/51931587/91872593-4ec53880-ec78-11ea-9215-13fd88597ab0.png)
![222](https://user-images.githubusercontent.com/51931587/91872598-508efc00-ec78-11ea-891a-ee7884978f19.png)

**Comment by luboslenco** [comment]
@Ebbombe super cool, that helps a lot! Thanks for the info.

**Comment by luboslenco** [comment]
Let me know if this still occurs, I tested using the setup displayed below and it appears to be ok.

![pic](https://user-images.githubusercontent.com/3685704/104064825-e62a3180-51fe-11eb-9a45-0e3624d50e4e.PNG)
