### ISSUE TITLE
severely lacking customization options for procedural nodes

### ISSUE THREAD

**Issue by tieguaili3d** [armory3d/armorpaint#472]
procedural nodes in armorpaint lack any useful options for creating materials when compared to the equivalent node in blender, the color2 field for the armorpaint brick texture doesn't actually have any effect on the output.

![image](https://user-images.githubusercontent.com/53412281/85313959-b14bcc80-b4b0-11ea-979e-13e83c18fb07.png)
![image](https://user-images.githubusercontent.com/53412281/85314034-ca547d80-b4b0-11ea-9cb6-2a23631395c4.png)

**Comment by luboslenco** [comment]
Working on it, will post more updates at https://github.com/armory3d/armorpaint/issues/36. Thanks for report!
