### ISSUE TITLE
can't reopen saved project file with non-English mesh name

### ISSUE THREAD

**Issue by epth** [armory3d/armorpaint#474]
**ArmorPaint version:**

0.8dev_win64

**OS/device including version:**

nvidia 1060 6G,non-DXR

**Issue description:**

can't reopen saved project file

**Steps to reproduce:**

1,importing a mesh from .obj file,obj file mesh name contains Chinese
2,save project file
3,reopen failed

**Comment by luboslenco** [comment]
Thanks for report! Pushed a fix at https://github.com/armory3d/iron/commit/8a82fa09a813daee8e6c4af563a5dbbb3a22061d, will be live in upcoming update.

**Comment by epth** [comment]
> 
> 
> Thanks for report! Pushed a fix at [armory3d/iron@8a82fa0](https://github.com/armory3d/iron/commit/8a82fa09a813daee8e6c4af563a5dbbb3a22061d), will be live in upcoming update.

Thank you very much!
