### ISSUE TITLE
Freshel. Only works for the current camera position.. Can this be called a bug?

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#477]
Win 64
0.8 (2020.06.14)
Good day! I do not know if this can be described as a bug.
But when I work with the node Freshel or Laer Weigth, it only works for the current camera position. And it’s worth turning the camera then we get the effect as when baking.
It feels like the Fresh function is projected onto the model once.
![1](https://user-images.githubusercontent.com/65244629/85700696-4e8f4680-b6e5-11ea-9bd0-4ba3195061a7.jpg)
![2](https://user-images.githubusercontent.com/65244629/85700701-4f27dd00-b6e5-11ea-85b5-5f2b8a937e15.jpg)
![3](https://user-images.githubusercontent.com/65244629/85700706-4fc07380-b6e5-11ea-8a1f-77be7aa5b663.jpg)
![4](https://user-images.githubusercontent.com/65244629/85700711-4fc07380-b6e5-11ea-95dd-bc7d8281c0f9.jpg)

Thank you! |  
-- | --

**Comment by luboslenco** [comment]
Hi, the fresnel node depends on view, it's mostly included for compatibility with cycles nodes for now. Will maybe get more useful in the future.
