### ISSUE TITLE
Base color socket always applies srgb-to-linear conversion

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#478]
Win 64 0.8 (2020.06.14)
Good day! I do not know if this is normal, I compare the result with the result in Blender 3D. I select the coordinate system of the object. Assign it to the dcanal of color, for clarity. It seems to me that the center of intersection should be in the center of the object, but for some reason it is offset.

![1](https://user-images.githubusercontent.com/65244629/85855478-06445700-b7bf-11ea-8f0e-7c6ed18a6d70.jpg)
![2](https://user-images.githubusercontent.com/65244629/85855481-07758400-b7bf-11ea-9b1e-02c00c452870.jpg)

**Comment by luboslenco** [comment]
I think in lit mode it depends on lighting, tone mapping and compositor - with increased light strength it should show up similarly.  I also improved the base color view mode, which will skip the tone mapping step now to give better view.

<img width="800" alt="Screenshot 2021-08-05 103914" src="https://user-images.githubusercontent.com/3685704/128332821-c1ffcd5d-3dcf-4732-82ac-a5fedcd093fe.png">

**Comment by AlexKiryanov** [comment]
Hello Lubos! Glad to read you! Thanks for this!

чт, 5 авг. 2021 г. в 13:13, Lubos Lenco ***@***.***>:
