### ISSUE TITLE
Nodes go beyond the screen, then they lose their position

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#479]
Win 64 0.8 (2020.06.14)
I drag a bunch of nodes. If the nodes go beyond the screen, then they lose their position
In the video I show it.
https://drive.google.com/file/d/1A3AW366u9oqxcETLG5NAHXHXAk0hl8LE/view?usp=sharing

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/zui/commit/6f4cb2922036ba4d3d933a0c88545157822f3c8b, thanks for report!

**Comment by AlexKiryanov** [comment]
Good day! You are welcome!
Thank you for the fix!

вт, 30 июн. 2020 г. в 09:36, Lubos Lenco <notifications@github.com>:
