### ISSUE TITLE
Stroke offset after zooming

### ISSUE THREAD

**Issue by julienduroure** [armory3d/armorpaint#48]
Using:
* linux mint 19 (based on Ubuntu 18.10)
* geforce GTX 860M
* ArmorPaint 0.5

Steps:
* Open Armarpain
* Do not rotate, not zoom
* Add a stroke: everything is OK
* zoom
* Add a stroke: there is an offset

Don't hesitate to contact me if you need more information

See gif:
![offset](https://user-images.githubusercontent.com/1696020/48970787-ccbecf00-f010-11e8-9393-9e53cfaeeace.gif)

**Comment by SojanJanso** [comment]
I can second this on:
Ubuntu 18.04.1 LTS,
GTX 780
AMD FX 8320E

It seems to happen often when the brush and area painted are smaller, or when there is an angle to the face being painted. Here are some other examples on the cube.
![peek 2018-11-24 12-13](https://user-images.githubusercontent.com/26679320/48971059-0a0c6800-efe3-11e8-84a0-a6fecbbc5ab8.gif)
![peek 2018-11-24 12-14](https://user-images.githubusercontent.com/26679320/48971061-0d9fef00-efe3-11e8-889f-5b0e9af9d7f3.gif)

**Comment by herb64** [comment]
Same here - just bought the software one hour ago: Windows 10, Fujitsu Laptop with NVidia Quadro 3000M. The offset is also dependent on rotation, as I observed.

**Comment by luboslenco** [comment]
Pushed a fix now, should be finally all good in upcoming 0.6 release. Thanks for detailed posts!

**Comment by luboslenco** [comment]
Hopefully good now in the new 0.6 dev build.

**Comment by herb64** [comment]
The problem seems to be solved with 0.6 dev release. I'll do some more testing. Thank you

**Comment by luboslenco** [comment]
Looks ok now, thanks to all for testing!
