### ISSUE TITLE
Group node

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#482]
Good day! Is it possible to add the function of combining several nodes into one node with the necessary inputs and outputs?

**Comment by Hopefullyidontgetbanned** [comment]
This would be very useful for large node groups but also would make things like smart materials possible

**Comment by AlexKiryanov** [comment]
good day! like these?

чт, 23 июл. 2020 г., 03:59 Hope <notifications@github.com>:

**Comment by AlexKiryanov** [comment]
Like this?
![3](https://user-images.githubusercontent.com/65244629/88261979-fc374a80-cccf-11ea-99f0-3661d6f3dff6.jpg)
![2](https://user-images.githubusercontent.com/65244629/88261982-fd687780-cccf-11ea-878a-bc4c1cd82797.jpg)
![1](https://user-images.githubusercontent.com/65244629/88261986-fe010e00-cccf-11ea-85f1-97eb754b3c5c.jpg)

**Comment by Hopefullyidontgetbanned** [comment]
yes for example this i made a smart skin material in blender with easy to read parameters
![Screenshot (1075)](https://user-images.githubusercontent.com/45346421/88292652-c46bdb00-ccae-11ea-873e-53085cf26440.png)

**Comment by luboslenco** [comment]
Added at https://github.com/armory3d/armorpaint/commit/a0eb67389b11e06a50f9117fa17f63bfc2b854f9, testing & fixes in coming days.

**Comment by AlexKiryanov** [comment]
Good day! Great, I've already tried it) Thank you very much!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пт, 8 янв. 2021 г. в 02:11, Lubos Lenco <notifications@github.com>:
