### ISSUE TITLE
Direct3d12 builds fine in Windows 10 with Visual Studio 2019 but doesn't start. Am I missing something?

### ISSUE THREAD

**Issue by tomoprime** [armory3d/armorpaint#483]
When I run Krom.exe nothing happens. Testing on a RTX 2080 MaxQ with latest NVIDIA driver 451.48.

Do I need to rename files to AmorPaint? Thanks.

**Comment by tomoprime** [comment]
Note I had to manually copy Krom.exe, from my Release folder to the base armorpaint\build\krom to get things to work. You may want to update the readme for post step clean up.

**Comment by luboslenco** [comment]
Hi, make sure to follow the step from the instructions:

> Set `Project - Properties - Debugging - Command Arguments` to `..\..\build\krom`

The instructions are set up so ArmorPaint runs directly from VisualStudio where it's easy to inspect and report crashes, no need to copy Krom.exe.
