### ISSUE TITLE
Baking vertex color map bug

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#485]
Win 64
0.8 (2020.06.14)

Good evening! I noticed this error. If you bake the vertex color map on the first gray layer, then everything works correctly. But if you do the same procedure on a new layer, then the program produces a strange result and after even the first result is strange.

Video https://drive.google.com/file/d/1YSeAE0lsChNPuI_5ZIC7pB5QSvNDJxCS/view?usp=sharing
file https://drive.google.com/file/d/1wsJrmvZaUjxrNqfY86Wway2ay0fh741c/view?usp=sharing
Thank you so much!

**Comment by luboslenco** [comment]
Fixed now at https://github.com/armory3d/armorpaint/commit/3e2e07c22147b5a13103a510ddc57f4d542c36b6, thanks again!

**Comment by AlexKiryanov** [comment]
Good day! You are welcome! Thank you!

чт, 2 июл. 2020 г. в 15:30, Lubos Lenco <notifications@github.com>:
