### ISSUE TITLE
Breaking imported model into layers in ArmorPaint

### ISSUE THREAD

**Issue by SunDevilArizona** [armory3d/armorpaint#486]
Inside of ArmorPaint is there a way to select individual or groups of faces so they can be placed in a separate layers and textures individually?

**Comment by AlexKiryanov** [comment]
Hello! Alternatively, paint over certain polygons first, then use this as a mask. https://www.youtube.com/watch?v=PEPxpw62o_g&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=20

**Comment by luboslenco** [comment]
Feel welcome to post more questions!
