### ISSUE TITLE
2D View with wrong brush sizing

### ISSUE THREAD

**Issue by SVNMLR** [armory3d/armorpaint#487]
*ArmorPaint 0.8-a3449b8, Windows*
![Brush Size](https://user-images.githubusercontent.com/44621949/86452965-58d0c680-bd1d-11ea-8151-5a1d58db890b.jpg)

Brush Size in 2D View is independent from zoom.

**Comment by luboslenco** [comment]
Can you please throw in steps to reproduce? Just zooming the camera in and then painting in 2d view does not seem to cause it for me.

**Comment by cYpH3r2oo3** [comment]
- Open Armorpaint
- Activate 2D View
- All Brush settings Standard (nothing changed from start)
- Paint 1 Dot on 3D Model
- Zoom with Mousewheel in 2D View

In the 2D View the Brushsize ist not changing dependig on zoomlevel in 3D it does.
![image](https://user-images.githubusercontent.com/44621949/86459136-a30a7580-bd26-11ea-963e-e26ab67514ab.png)

![image](https://user-images.githubusercontent.com/44621949/86459168-b289be80-bd26-11ea-84a6-5025d7126e74.png)

![image](https://user-images.githubusercontent.com/44621949/86459195-be758080-bd26-11ea-9421-7711699b4f97.png)

**Comment by cYpH3r2oo3** [comment]
The Falloff is different, too. The Big one is painted in 2D View and the small one in 3D (no brushseetings changed in between)



![image](https://user-images.githubusercontent.com/44621949/86459525-3348ba80-bd27-11ea-8153-c9689d5bf1e4.png)

**Comment by luboslenco** [comment]
Should be better after https://github.com/armory3d/armorpaint/commit/3f0de820466c22048b62e15964f7383fe06d1756, thanks for report.
