### ISSUE TITLE
Image is reflected when I use the UV coordinates as input

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#491]
win 10 64 bit
v 0.8 2020-07-03 a3449b8
Good evening! I accidentally noticed a strange thing. I created a model, made a UV. Bake some cards according to UV. If I use just a texture then it will fit correctly on the model. But if I connect the UV node, the texture is somehow strange reflected ...
![1](https://user-images.githubusercontent.com/65244629/86831872-223dd780-c0a0-11ea-918f-d27c63b3294f.jpg)
![2](https://user-images.githubusercontent.com/65244629/86831876-22d66e00-c0a0-11ea-96b7-4eb04db4b818.jpg)
Thank you so much!

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/482214b8e21680938993e19949f5baab422dd645, thanks once again!

**Comment by AlexKiryanov** [comment]
Thank you so much!

ср, 8 июл. 2020 г. в 10:50, Lubos Lenco <notifications@github.com>:
