### ISSUE TITLE
Pen pressure not working on linux (archlinux)

### ISSUE THREAD

**Issue by valentegamedev** [armory3d/armorpaint#493]
I'm not getting pen pressure on Armorpaint running Archlinux. However, I can get it working in Blender, Krita and Gimp. Am I missing something?

Thanks.

**Comment by luboslenco** [comment]
Hi, thanks for report. I tested on Ubuntu 18.04.4 + Wacom Intuos S  and unfortunately it seems to work ok there. Can you let me know which pen / tablet  hardware are you on?
