### ISSUE TITLE
Default non-rounded cube has several duplicated vertices and edges

### ISSUE THREAD

**Issue by treacherousfiend** [armory3d/armorpaint#497]
**ArmorPaint version:**
v0.8 e3be018 DX11

**OS/device including version:**
Windows 10 Home Version 1909
Nvidia GTX 1070
Driver 451.48

**Issue description:**
Default cube (non-rounded) has 24 unnecessary vertices, which could (and seemingly is) causing issues with height maps
All the vertices in the model have 2 copies, the edges are duped as well. 
Side-effects of this issue include height-maps causing faces of the model to disconnect (possibly intentional), which is shown in the attached image

**Steps to reproduce:**
1. Open new project with mesh "Cube" scale 1:1
2. Export mesh
3. Open in model viewer/editor (Blender 2.83 used for my testing)

Image taken in ArmorPaint using default material with height of 1, that is not an outline, it is empty space
![image](https://user-images.githubusercontent.com/46549454/87239377-061e9b00-c3fe-11ea-88ed-d5e54389f2a9.png)

**Comment by treacherousfiend** [comment]
I would submit a pull request to fix myself, but i'm not sure how to export a model into .arm or .json

**Comment by luboslenco** [comment]
Hi, thanks for report. .arm format stores vertices in indexed format suitable for straight gpu consumption, which is the reason for duplicated vertices along the hard edges. See section GPU: Optimizing model geometry at  https://docs.unity3d.com/560/Documentation/Manual/OptimizingGraphicsPerformance.html for more details.

> Note that the actual number of vertices that graphics hardware has to process is usually not the same as the number reported by a 3D application. Modeling applications usually display the number of distinct corner points that make up a model (known as the geometric vertex count). For a graphics card, however, some geometric vertices need to be split into two or more logical vertices for rendering purposes. A vertex must be split if it has multiple normals, UV coordinates or vertex colors. Consequently, the vertex count in Unity is usually higher than the count given by the 3D application.
