### ISSUE TITLE
import behavior is strange

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armorpaint#5]
In both Windows and Linux, when try to import file (obj / fbx), armorpaint "open up" the file instead of import it:
![issue_02](https://user-images.githubusercontent.com/17811339/36773916-e5d76f5e-1c96-11e8-9cd4-2deba47e8683.jpg)

If I open the file until nothing to open, try to click OK, in windows it will crash (in Linux nothing happens):
![issue_03](https://user-images.githubusercontent.com/17811339/36773951-08434220-1c97-11e8-9517-3fdd339172bf.jpg)

Only when I step back one folder level, the file can be loaded:
![issue_04](https://user-images.githubusercontent.com/17811339/36774239-2351b5b4-1c98-11e8-9830-a6b5df40d5b5.jpg)

Also in windows whenever I try to navigate to a folder, a command line window will open then close immediately, is this normal?
![issue_01](https://user-images.githubusercontent.com/17811339/36774271-4d3930f0-1c98-11e8-8ec8-be8b9fd50e16.jpg)

/Milo

**Comment by Deygus** [comment]
Yeah I am having an issue with Importing as well even in the latest version...

**Comment by luboslenco** [comment]
Fixed the weird file browser behavior.
