### ISSUE TITLE
Pointiness channel in geometry node not working

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#501]
Win 10 64bit
v0.8 (2020-07-11) - e3be018
Good day!
When using the Pointiness channel in a geometry node, it produces no results. Black and that's it. Attached printscreen.
For comparison, what it looks like in a blender.
Thank you so much!
![1](https://user-images.githubusercontent.com/65244629/87873405-2afcaa80-c9ca-11ea-934c-89393fa5dbf5.jpg)
![2](https://user-images.githubusercontent.com/65244629/87873407-2c2dd780-c9ca-11ea-8faf-93269386b287.jpg)

**Comment by Hopefullyidontgetbanned** [comment]
i believe this is exclusive to Path Tracing Builds but i think it doesn't work on that either

**Comment by AlexKiryanov** [comment]
Hello! Thank you for your attention. I think the same way.

**Comment by Hopefullyidontgetbanned** [comment]
mostly because pointiness is usually exclusive to path tracing such as luxcore/cycles
https://docs.blender.org/manual/en/latest/render/shader_nodes/input/geometry.html
it should be possible considering it's calculated through curvature which armorpaint supports baking of

**Comment by AlexKiryanov** [comment]
Unfortunately this does not work even on RT build.

**Comment by Hopefullyidontgetbanned** [comment]
![Screenshot (1069)](https://user-images.githubusercontent.com/45346421/88188748-1d733a80-cbed-11ea-874e-db01473a5700.png) Pointiness in Cycles
![Screenshot (1068)](https://user-images.githubusercontent.com/45346421/88188755-1fd59480-cbed-11ea-87ed-f58aef981345.png)
Curvature in Armorpaint

**Comment by AlexKiryanov** [comment]
Yes!!!! This is the ability to make it without baking.

**Comment by luboslenco** [comment]
Link together with https://github.com/armory3d/armorpaint/issues/36.
