### ISSUE TITLE
the mixing overlay mode does not react to the factor value in the Mix node

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#502]
![1](https://user-images.githubusercontent.com/65244629/87886421-68425600-ca25-11ea-887c-c1bb1f78113c.jpg)
![2](https://user-images.githubusercontent.com/65244629/87886423-69738300-ca25-11ea-9dca-45b63ba38d57.jpg)

win 10 64 bit
v0.8 (2020-07-11) - e3be018
When using a blend node with overlay mode, the factor does not affect blending. channels are always mixed 100 percent.

**Comment by luboslenco** [comment]
Thanks for report, does the issue persist in latest builds?

**Comment by AlexKiryanov** [comment]
Good day, Lubos! In ma version v0.8 (2020-08-07) - 7aa59a6 YES. But I noticed that you made a fix for this error by the headers on the github.) I'll update the version today and check it out! However, I'm sure that most likely everything is fine! I will definitely write.) Question: have you dealt with the texture shift in a custom node yet?

**Comment by AlexKiryanov** [comment]
Everything is working! Thank you so much!
