### ISSUE TITLE
Cel Shading

### ISSUE THREAD

**Issue by HeavyHandedHarlot** [armory3d/armorpaint#504]
Hello!

I'm working on an unreal game with cel shaded characters and idk I might get this program eventually anyway but I was wondering whether this program would be suitable for texturing cel shaded character models/NPR models or is this more for photorealistic texturing?

Thank you and kind regards!

**Comment by luboslenco** [comment]
Hi, thanks for checking out ArmorPaint! Right now the painting is focused on the PBR workflow, but you can discard the un-needed channels. NPR viewport features coming at https://github.com/armory3d/armorpaint/issues/110.
