### ISSUE TITLE
0.8 crashes when calls the linux file system browser

### ISSUE THREAD

**Issue by alexfreyre** [armory3d/armorpaint#506]
**ArmorPaint version:**

0.8-dev / master

**OS/device including version:**

Archlinux x64
Mesa Intel(R) HD Graphics 520 (SKL GT2)
Nvidia driver: 450 / card:  940MX

**Issue description:**

when armorpaint starts it shows:
Uniform N not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/RenderTargetImpl.c 174

Uniform brushScale not found.
Uniform inp not found.
Uniform inplast not found.
Uniform brushScale not found.
Uniform inp not found.
Uniform inplast not found.
Uniform brushScale not found.
Uniform inp not found.
Uniform inplast not found.
Uniform brushScale not found.
Uniform brushScale not found.
Uniform brushScale not found.

when I try to use any feature (import or export) that call the linux file system browser it crashes:
/usr/bin/armorpaint: line 3:  3927 Segmentation fault      (core dumped) /usr/lib/armorpaint/Krom /usr/share/armorpaint/krom

**Steps to reproduce:**

Open the editor, paint, save and it crash

**Comment by luboslenco** [comment]
Ah, this is an issue which only seem to happen on arch/manjaro, but so far I believe no one was able to pin point why, since it works fine for example on Ubuntu. Linking to existing issue at https://github.com/armory3d/armorpaint/issues/179 + there is a workaround described.

**Comment by unfa** [comment]
I have the same issue.
