### ISSUE TITLE
Linking v8_monolith.lib gives error LNK2038

### ISSUE THREAD

**Issue by bmalex88** [armory3d/armorpaint#507]
**ArmorPaint version:**
108078dd516f21c0a0dda0d57462901d2b4bf0cd

**OS/device including version:**
PC / Windows 10

**Issue description:**
I follow every step, the Visual Studio is generated, I add `..\..\build\krom` to the command arguments but when I build the solution and after compiling all into objects, I get these linking errors

```
1>v8_monolith.lib(default-platform.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
1>v8_monolith.lib(default-platform.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in main.obj
1>v8_monolith.lib(api.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
1>v8_monolith.lib(api.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in main.obj
1>v8_monolith.lib(v8threads.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
```
and many more like these. At the end I see this:

`LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
`
**Steps to reproduce:**
Just follow the instructions from the repository's README. Have Visual Studio 2019 CE installed

**Comment by luboslenco** [comment]
... if anyone stumbles upon this, make sure to build for `x64 & release` mode.
