### ISSUE TITLE
decals scaling

### ISSUE THREAD

**Issue by Ulazygit** [armory3d/armorpaint#508]
For decals to be in original aspect ratio by default so they are not warped. This is for (stick-on) Windows and doors etc...

**Comment by AlexKiryanov** [comment]
Your texture should be square. If you need to draw a rectangular shape then you must create a square texture with this rectangular shape. Then the ratio will be correct.

**Comment by luboslenco** [comment]
Non-square decals should be kept in the original aspect ratio by default now. https://github.com/armory3d/armorpaint/commit/614930a9a53bb92f6bc50faba7f57fe71761af35

**Comment by AlexKiryanov** [comment]
good day!. great news! Thank! have a good weekend

пт, 11 сент. 2020 г. в 15:38, Lubos Lenco <notifications@github.com>:
