### ISSUE TITLE
The problem with a lot of layers with information about materials

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#509]
win 10 64 bit
v0.8 (2020-07-11) - e3be018
I don't know how to name this problem exactly.
If many layers are used in the scene (maps with baked textures or materials transferred to a layer for painting) and when mixing these layers in a new material, strange things happen.
I solve this problem by exporting masks, textures to an external file. I delete the layers and then blend with the loaded images.
It was the same with curvature maps.
after 6-8 layers it becomes impossible to mix layers in the material.
At first I thought it was because there are a lot of objects in the scene. But even with one object, the same situation occurs. I will send all files if needed.
![1](https://user-images.githubusercontent.com/65244629/88537262-e9957c00-d015-11ea-9eec-ac260bba144b.jpg)
![2](https://user-images.githubusercontent.com/65244629/88537265-eac6a900-d015-11ea-8355-a9b0224c3cda.jpg)
![3](https://user-images.githubusercontent.com/65244629/88537266-eac6a900-d015-11ea-9a3c-68574a535b01.jpg)

**Comment by Ulazygit** [comment]
+1. I am experiencing this too

**Comment by luboslenco** [comment]
Should be resolved now via https://github.com/armory3d/armorpaint/commit/35016a57309c035a7efa668670d6676c22e1072c, thanks for report.

**Comment by AlexKiryanov** [comment]
Thank you very much Lubos! You've done a lot of fixes! Forgive me, but, can
I ask, I wrote a message about a custom node, for some reason I can't make
it work with itself, although I do everything like you do in the examples.
Can you see what's wrong there? From the point of view of syntax,
everything is correct, the node itself works, but not with itself. As if
the array that you created for this does not produce anything.

пт, 25 сент. 2020 г. в 17:01, Lubos Lenco <notifications@github.com>:

**Comment by luboslenco** [comment]
👍 Will do, working on every issue asap!
