### ISSUE TITLE
Opacity doesn't work for stickers (yet)

### ISSUE THREAD

**Issue by Hoxolotl** [armory3d/armorpaint#51]
![armorypaint5awin10_opacity](https://user-images.githubusercontent.com/13289244/51033667-6ed84d80-15a4-11e9-85e4-dec595c7b189.JPG)

Sadly the opacity isn't working for stickers (yet). I connected to the alpha of a .png (didn' t work), then tried to use a white-black height map connected to the opacity. But so far I haven't been able to get the material opacity to react to anything on its input node.

Either I' m doing this wrong, or the opacity in the material node isn't taking its inputs.

P.s.: all the other stuff really meshes well with my workflow, keep up the awesome work: I can has a happy!

**Comment by luboslenco** [comment]
Thanks for opening this! Will fix this asap for the upcoming build, should be easy. :)

**Comment by luboslenco** [comment]
This exact material setup should (hopefully!) work properly in the latest dev builds. The sticker has a dedicated place in the toolshelf now:

![tool_decal](https://user-images.githubusercontent.com/3685704/54047246-d989bc00-41d6-11e9-8ad6-637a2bfa4a9d.png)
