### ISSUE TITLE
Multiple meshes and wireframe mode

### ISSUE THREAD

**Issue by Ulazygit** [armory3d/armorpaint#511]
*ArmorPaint 0.8-108078d, Windows*

Two meshes and using colorid to differentiate between the materials on each object. Viewport mode to wireframe. Shows weird result (my wireframe does not look like this). Also, painting by face does not paint the individual face, but paints the whole colorid material.
![bug](https://user-images.githubusercontent.com/60723284/88603409-bf22dd80-d06c-11ea-96dd-fd6ff50df940.JPG)

**Comment by luboslenco** [comment]
Both issues should be resolved via https://github.com/armory3d/armorpaint/commit/a453f4f8909b2f8bf573f9b3b9808e7b3a9f684a and https://github.com/armory3d/armorpaint/commit/b9fa68a3ace8e6492fe888f916146dadecac7655.
