### ISSUE TITLE
Painting Issue (ArmorPaint)

### ISSUE THREAD

**Issue by Josephz51** [armory3d/armorpaint#512]
*ArmorPaint 0.8-e3be018, Windows*

When painting in one area it paints on another at the same time. (Symmetry is disabled.)

**Comment by luboslenco** [comment]
Hi. does this help? [faq/Mesh gets painted on multiple places at once](https://github.com/armory3d/armorpaint_docs/blob/master/faq.md#mesh-gets-painted-on-multiple-places-at-once)
