### ISSUE TITLE
Text tool improvement

### ISSUE THREAD

**Issue by edap** [armory3d/armorpaint#514]
I have bought armorpaint because of its possibility to rotate and scale text, but the text is pretty limited. Some features that in my opinion could help:

- Copy and paste in the input text field. At the moment is not possible
- A dropped custom font should be available also if I close the file and I open it again
- A better way to rotate the font. At the moment, to rotate the font you have to move the mouse to the top and change the angle. It would be nice to have a shortcut, or maybe rotate the font using the mousewheel. So that I can place perfectly the font at the desired rotation while watching at it.
- I would be nice if the text would be visible when opening the file again after saving it
- When changing fonts, from the default one to the custom one, the new selected fonts is not visible.

**Comment by luboslenco** [comment]
Hi, thanks for report. I pushed some improvements into the freshly updated builds.

> Copy and paste in the input text field. At the moment is not possible

Which OS are you on?

> A dropped custom font should be available also if I close the file and I open it again

List of imported fonts is now saved inside a project file.

> A better way to rotate the font

To rotate the font / decal / brush, try holding alt+f (can be configured in keymap preferences) and move the mouse. Opacity and radius can also be controlled.

> I would be nice if the text would be visible when opening the file again after saving it

Can you give me more details on this?

> When changing fonts, from the default one to the custom one, the new selected fonts is not visible

Should be resolved now, but please let me know if you get to test it.

**Comment by edap** [comment]
> Hi, thanks for report. I pushed some improvements into the freshly updated builds.
> 
> > Copy and paste in the input text field. At the moment is not possible
> 
> Which OS are you on?
Ubuntu
> 
> > A dropped custom font should be available also if I close the file and I open it again
> 
> List of imported fonts is now saved inside a project file.

Cool! thanks
> 
> > A better way to rotate the font
> 
> To rotate the font / decal / brush, try holding alt+f (can be configured in keymap preferences) and move the mouse. Opacity and radius can also be controlled.
> 
> > I would be nice if the text would be visible when opening the file again after saving it
> 
> Can you give me more details on this?

It is the same as question 2, so, it should be fixed.
> 
> > When changing fonts, from the default one to the custom one, the new selected fonts is not visible
> 
> Should be resolved now, but please let me know if you get to test it.

I will test as soon as I am back to my desktop computer and let you know. Many thanks for your efforts.

**Comment by edap** [comment]
Hello, the fonts is now saved in the project. Switching from old fonts to new fonts works. ALT + F for rotating also works.
thanks for the fast fixes ;)
