### ISSUE TITLE
Cant apply d3d12_wrap_sampler.diff for DXR version

### ISSUE THREAD

**Issue by ChrisMGeo** [armory3d/armorpaint#517]
**ArmorPaint version:**
v0.8 (2020-07-31) - add971a20202e147b691a2e1b3b17df82a04d881

**OS/device including version:**
Win10 64bit

**Issue description:**
I'm trying to build ArmorPaint with the wip DXR to try out Path Tracing. However when following the instructions in the homepage, specifically this command:
`git apply patch/d3d12_wrap_sampler.diff --directory=Kinc`
When trying to run this command I get the following error:
```
error: patch failed: Kinc/Backends/Graphics5/Direct3D12/Sources/Kore/Texture5Impl.cpp:142
error: Kinc/Backends/Graphics5/Direct3D12/Sources/Kore/Texture5Impl.cpp: patch does not apply
```

**Steps to reproduce:**

1. Clone the repo and `cd` to it.
2. Use the following commands:
```
node Kromx/make -g direct3d12
cd Kromx
git apply patch/window_handling.diff --directory=Kinc
git apply patch/d3d12_raytrace.diff --directory=Kinc
git apply patch/d3d12_wrap_sampler.diff --directory=Kinc
```
3. You'll fortunately (or unfortunately) see the above error.

**Comment by luboslenco** [comment]
It should be resolved now, many thanks for reporting the issue! https://github.com/armory3d/Kromx/commit/c9b7147cd7e813090efdb9fa465111fb9f12eb09
