### ISSUE TITLE
Bridge with other software as a suite to create materials

### ISSUE THREAD

**Issue by alexfreyre** [armory3d/armorpaint#518]
It is known that Substance has the best closed-source suite for create materials and Quixel mixer has an interesting aproach considering the use of its material library on its own cloud, which certainly saves a lot of time and effort . So I want to propose an idea to our community in front of that kind of suites.

- Armorpaint is the best open source software to paint textures...
- Material Maker (made with Godot Engine) is a very interesting FOSS like the closed Substance Designer, and it is becoming pretty mature.
- Texture Haven is a site that host a free and open repository with textures and materials.

So, 
why not join forces, save time and make something like a suite of software which can communicate each other?

my proposal/ideas:
1. maybe some kind of workflow can be possible consider input/output from Material Maker to Armorpaint, like Substance does between Painter and Designer.
2. maybe Texture Haven could be the online repository for Armorpaint and MM like Quixel Mixer does, that could save a lot of time in Armorpaint, just imagine not import textures only pick from an online library and Texture Haven is free and accessible!

I know that Material Maker and Armorpaint are different in its core, but both are good (Armorpaint has a better UI and performance) and both are at least for me the best open source alternative to Substance suite. 

Will be really great to have a FOSS suite to paint and create materials/shaders which currently don't exist and the users have to use several software very isolated and different.

(sorry for english mistakes, I am spanish speaker)

**Comment by AlexKiryanov** [comment]
Good day, alexfreyre! The idea is great! I saw your tweets yesterday. But if in the future armor paint makes a richer node system (and I really hope so), and library (see on the site, "Opening soon!"), then this will not be necessary.  But again, the idea is not bad) It would not be bad if MM had a plugin that would export the created material to the material for ArmorPaint in one file. Of course, you can always export to textures and assemble them into armor. 
And more.... there is certainly a possibility that they will look a little differently, since I use different rendering engines.
And more about substance
There is no node system in the substance painter, so they have a designer and a bridge for them.

**Comment by alexfreyre** [comment]
Thanks for your answer! If the case will be as you say, so will be amazing
to have the nodes, shaders and workflow which exists in MM and Substance
Designer for procedural material creation, but with all kind of nodes and
shaders or more!

On the other hand in game engines there is an use for textures to create
"static materials" but coded shaders gives the possibility of dynamic
material creation. For that reason please don't forget that a great feature
is to expose the shader code to reuse in the engines. That kind of workflow
saves a lot of time and effort because a very complex code can be created
with nodes instead of the complexity and time that implies to code the
shader itself which certainly would be very extended interns of functions
and lines of code.

Also there are some shader langs glsl, hlsh which vulkan itself include and
most game engines uses but in our FOSS community exist Godot and it have
its own and simplified shader language.

So as a conclusion, great the idea to create something like Substance
Designer within ArmorPaint moreover the feature of expose the shader at
least for me it is extremely important because of the need of create
dynamic materials!

Thanks in advance for consider these ideas and congratulations and thanks
for create ArmorPaint it is a great great great open source software!

 (I can't negate that I really miss the online library that Quixel mixer
has, and ArmorPaint needs that)

**Comment by luboslenco** [comment]
Thanks for the post. Some bridge plugins exist (https://github.com/armory3d/armorpaint_docs#live-link), will be super cool to grow that list further. Contributions on this front are very welcome. The library is taking a while but still coming at https://armorpaint.org/library.html. Creating a plugin to access another library should also be doable, but need to proceed step by step.
