### ISSUE TITLE
Scaling textures and smoothness/roughness choice

### ISSUE THREAD

**Issue by Ulazygit** [armory3d/armorpaint#520]
1. Make it possible to independently scale x and y coordinates of an image texture when painting. Currently can only do uniform scaling.
![request](https://user-images.githubusercontent.com/60723284/89725679-cc937c80-da09-11ea-9acd-d565225a5ef0.JPG)

2. Make it possible to use smoothness instead of roughness via a drop-down menu on the material output nodes so user doesn't have to continuously use inversion nodes. This should also speed up workflows for people who have combinations of smoothness and roughness maps.

**Comment by luboslenco** [comment]
1. The independent scale is possible but it needs to be done via the mapping node.
2. It's tied to the roughness workflow for now, sorry. Will try to look into a quick image node invert feature, maybe a checkbox on the image node. During the export, smoothness map can still be exported if needed.
