### ISSUE TITLE
DXR- Painting on some materials make the whole thing invisible and ticking on Path Tracing causes program to freeze

### ISSUE THREAD

**Issue by ChrisMGeo** [armory3d/armorpaint#521]
**ArmorPaint version:**

v0.8 (2020-07-31) - b0f4ad5c70e5fd1d8d6e4c0c060d3ae1d7f8662a

**OS/device including version:**
Win10 64bit

**Issue description:**
When I'm trying to use some some materials which used to work before, the whole thing becomes invisible.
When ticking on Path Tracing the program 'freezes'. The check seems to flicker on and off, and I can't do anything about it. It doesn't really freeze the application it just gets stuck there.

**Steps to reproduce:**
Try checking on Modes->Path Tracing

**Comment by luboslenco** [comment]
Hello,

> When I'm trying to use some some materials which used to work before, the whole thing becomes invisible.

Can you elaborate on this? Which materials?

> When ticking on Path Tracing the program 'freezes'.

What graphics card are you on?

**Comment by ChrisMGeo** [comment]
I'm sorry for the lack of elaboration but I previously made some materials with a previous version of Armorpaint. But that is no longer the problem, now the problem has become that randomly the model in question just disappears. For example I was trying out the node editor, and minimized my window to half width to only see node editor, and put it back to full width, the whole model disappeared. I also think the path tracing doesn't work because my graphics card is a gtx1660 so it may not support path tracing.

**Comment by luboslenco** [comment]
Hi, does the issue persists in the latest build? It should work on gtx1660 as well, the only difference being performance.
