### ISSUE TITLE
Can't Rotate With Right Mouse Button on Wacom Pen - update docs

### ISSUE THREAD

**Issue by davidmorning** [armory3d/armorpaint#522]
**ArmorPaint version:**
ArmorPaint 0.8 64-bit

**OS/device including version:**
Windows 10 Pro

**Issue description:**
I loaded up ArmorPaint to try it out, and found I had no pressure sensitivity. When I looked up how to resolve this, I saw advice that I should turn on Windows Ink, which I did. I found that this resolved the pressure sensitivity, but when I tried to rotate the object a circle would appear and the object wouldn't rotate. 

Testing it in other programs indicated that the right click still worked despite the circle appearing, and in Blender the circle didn't even appear and I was able to move objects with the right mouse button on the tablet pen just fine. I've checked the pen and touch settings, the right click and hold effect is disabled, and I've made the registry edit some people recommend to force press and hold to be disabled. I've also updated to the most recent Wacom drivers (version 6.3.40-2 on an Intuos Pro PTH-660)

**Comment by AlexKiryanov** [comment]
![Untitled-1](https://user-images.githubusercontent.com/65244629/89734545-60defd00-da65-11ea-8192-898f257be0ec.jpg)
Good day! This will help! Try assigning a modifier to the right mouse button. And specify the alt + left mouse button in it.
It works for me.

**Comment by davidmorning** [comment]
That sort of seems to have worked, although there's still noticeable lag before the rotation kicks in. Still, it does work, so means I can start using the program, thanks! Still think the original issue is something that should be reviewed by the devs though, so going to leave the report open for now

**Comment by AlexKiryanov** [comment]
Honestly, I don't have any lag? Try to use only Alt in the modifier, but then you will need to rotate by pressing the stylus on the tablet.
https://drive.google.com/file/d/1iWYw8-TbfDrquSccLDfwfOTA92p5wcsg/view?usp=sharing

**Comment by AlexKiryanov** [comment]
I will add that the right pen button does not work, most likely due to the fact that in the hotkey settings, this is the alt + left mouse button. And the fact that you can rotate the camera with the right mouse button is probably an additional option, something like this)))

**Comment by davidmorning** [comment]
OK, testing it using alt-left mouse button it actually works just fine and I don't see any lag. I'm possibly even more confused about the right click button now though, if I use alt+right click on my mouse it zooms, which I see is what's in the keymap configuration, but if I do the same on the tablet it seems to treat it as if I was pressing alt+left click and won't zoom. Maybe that's why there's a half second delay before it starts rotating (which is what I meant by the lag), there's a conflict between the zoom and rotate shortcuts when using the tablet?

**Comment by AlexKiryanov** [comment]
Good day! Yes there is, but I think it's out of habit. I also have a mini keyboard with 9 buttons. I reconfigured it to fit my needs and use the pen only for drawing.  By the way, for the sake of interest, I tried to configure the buttons on the tablet, and right-clicking there works the same way as right-clicking.

**Comment by Draise14** [comment]
Yes, can confirm, wacom default right click will do a press and hold gimmick, but if you make it a modifier to Rclick, this will fix it and it will work with Armour Paint.

**Comment by luboslenco** [comment]
[Added a note](https://github.com/armory3d/armorpaint_docs#pen) to docs to hopefully make it more straightforward, thanks for all the info.

**Comment by AlexKiryanov** [comment]
Good evening! thank you)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/104099635-e2cc8f80-526a-11eb-9955-0e0a62be0f51.png)

Unfortunately for older wacom tablet, like the Bamboo CTL series, you can not assign modifier pen maps per application, and it only goes to global... so switching between software breaks a lot of workflows and chaning the defaults is not good. 

Could the pen tablet controls be customizable and not global to the tablet settings?

**Comment by Disar** [comment]
I know this thread is closed, but the issue persists.
I've mapped my upper button to " right click ", but it acts like left click.
Trying to zoom in with alt+click. Build from commit ` Copy all layer props when duplicating` `2e1be30c470e39615cc94c968c716b8bd982b299`
