### ISSUE TITLE
 ERROR but how can I fix it

### ISSUE THREAD

**Issue by Skiddybison5924** [armory3d/armorpaint#524]
my command  was : node Kromx/make -g direct3d11
 the Output was : internal/modules/cjs/loader.js:968
throw err;
^

Error: Cannot find module 'C:\tmp\armor\Kromx\make'
�[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)�[39m
�[90m at Function.Module._load (internal/modules/cjs/loader.js:841:27)�[39m
�[90m at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)�[39m
�[90m at internal/main/run_main_module.js:17:47�[39m {
code: �[32m'MODULE_NOT_FOUND'�[39m,
requireStack: []
}
i hope u can help me

**Comment by luboslenco** [comment]
Hello, it sounds like https://github.com/armory3d/armorpaint/issues/519 - did you use recursive git clone?

**Comment by Skiddybison5924** [comment]
yes i did but i forgot `cd armorpaint`  :-)

**Comment by Skiddybison5924** [comment]
maybe i have more questions  later :-)
