### ISSUE TITLE
 ERROR patch does not apply for (git apply patch/window_handling.diff --directory=Kinc)

### ISSUE THREAD

**Issue by LordVeggie** [armory3d/armorpaint#525]
G:\ArmorPaint\armorpaint\Kromx>git apply patch/window_handling.diff --directory=Kinc
error: patch failed: Kinc/Backends/System/Windows/Sources/Kore/System.cpp:245
error: Kinc/Backends/System/Windows/Sources/Kore/System.cpp: patch does not apply
error: patch failed: Kinc/Backends/System/Windows/Sources/Kore/Window.c:196
error: Kinc/Backends/System/Windows/Sources/Kore/Window.c: patch does not apply

Anyone know how to fix this, please.

**Comment by luboslenco** [comment]
I tried building from scratch on another Windows machine and unfortunately all seems well here. What is your git version? Are you able to figure out the encoding of `patch/window_handling.diff` file on your machine?

**Comment by AFWSI** [comment]
@luboslenco  
Do we need to create a new "build" folder every time we build? The first time it didn't give this patch error ,but the second time it does.

**Comment by Vyounesky** [comment]
Hello , I get the same ERROR too.

OS: Windows 10
git version 2.34.1.windows.1
Node.js version : v16.13.1
Chocolatey v0.11.3
