### ISSUE TITLE
I was building the .exe programm and the came `Could not load krom.js, aborting.` and then `The programm "[21348] Krom.exe "  ended with code 1 (0x1).`

### ISSUE THREAD

**Issue by Skiddybison5924** [armory3d/armorpaint#527]
I was building the .exe programm and the came `Could not load krom.js, aborting.` and then `The programm "[21348] Krom.exe " 
ended with code 1 (0x1).` how can I fix it

**Comment by luboslenco** [comment]
Hello, please check https://github.com/armory3d/armorpaint/issues/256.
