### ISSUE TITLE
Height maps separating mesh faces for no apparent reason

### ISSUE THREAD

**Issue by CodeLineNull** [armory3d/armorpaint#528]
**ArmorPaint version:**
V0.8

**OS/device including version:**

Windows 10 Nvidia GTX

**Issue description:**

When using linear height maps and plugging in either the color or alpha channel into the material height in the materials node editor, mesh faces separate from each other leaving the mesh broken up.

**Steps to reproduce:**

Use a height map (must be grayscale) image texture and plug color into the height of the material whilst set to linear or srgb (Linear makes the faces seperate evenly, srgb makes the faces separate randomly).

![2020-08-10 (1)](https://user-images.githubusercontent.com/69477826/89814579-3d868180-db3b-11ea-81bd-7b62391ef4a1.png)
![2020-08-10](https://user-images.githubusercontent.com/69477826/89814597-437c6280-db3b-11ea-9654-91d05782cce0.png)

**Comment by luboslenco** [comment]
The height socket will displace the faces along the normal, it can be disabled at `Edit - Preferences... - Viewport - Displacement Strength`. Maybe I should set it to 0 by default. Or do you mean the height displacement is not applied as expected?

![disp](https://user-images.githubusercontent.com/3685704/90236080-8fbcf080-de22-11ea-8685-a40f049230df.png)
