### ISSUE TITLE
UI number input suggestions

### ISSUE THREAD

**Issue by cgvirus** [armory3d/armorpaint#529]
Various UI parameter annoyances:
- The given parameters get destroyed whenever clicking into sliders.
- Going beyond 1 and then If changes is needed the number pops back to arbitrary numbers again due to touching slider.
- Numlock doesn't work in Linux to input numbers

Please see the demo in zip video. The same effect is also applied in any slider be it in layer or editors.

Suggestion:
- using slider like this, vertical mouse pressed or middle mouse scroll or up/down arrow key will change the value
![file-4ZqlPiTUtr](https://user-images.githubusercontent.com/22106885/89831246-54e75e00-db7f-11ea-8993-2b4e910e7e9a.png)

OR

- Separating number box column from the slider column
- Using Natron like number slider. middle mouse scroll, up/down arrow will increase or decrease the value in the num box as well.

Reason:
- Material creation is a number sensitive workflow. Slight floating point changes can change the whole look. 
- Value 1 is often not enough in UV or procedural material. 

OS: Debian 10

[demo.zip](https://github.com/armory3d/armorpaint/files/5053318/demo.zip)

**Comment by Calinou** [comment]
> Numlock doesn't work in Linux to input numbers

This should be reported in a separate issue since it's a bug.

**Comment by MathemanFlo** [comment]
I think this suggestion could be linked to #1069.

**Comment by luboslenco** [comment]
https://github.com/armory3d/armorpaint/issues/1069 👍
