### ISSUE TITLE
crash on non-relative path

### ISSUE THREAD

**Issue by Hoxolotl** [armory3d/armorpaint#53]
on my windows pc the textures are in the D:/resources/textures/texture.png, Armory in in D:/Resources/tools/armorypaint
I save a Library.arm in the D:/Resources/tools/armorypaint/library.arm folder with all my nicely made materials
Then make a backup copy on a USB disk of the complete folder structure
Then when I run armorypaint on my linux laptop from the folder (linux root-ish) Applications/armorypaint, and open the library.arm in usbdrive\Resources\tools\armorypaint\library.arm Armory looks for the texture.png... and well, see the screenshot :)
( the texture would be in usbdrive\resources\textures\texture.png
![woopsies](https://user-images.githubusercontent.com/13289244/51203301-00c3bb80-1901-11e9-9319-fc57916f6dc4.png)

I apologise for the bug reports, I'll keep them coming when I see them, I know it's alpha software, never mind lil'ol me if it was already on the todo list ;)
Also, this is a ¨nice to have bug" Not a "it breaks armorypaint for me" bug.

**Comment by luboslenco** [comment]
(Feel welcome to throw all the bugs here, it's super helpful to develop ArmorPaint faster! 😎 )

**Comment by luboslenco** [comment]
Will need more testing but a fix attempt is included in the new dev build!

**Comment by luboslenco** [comment]
Hopefully good now.
