### ISSUE TITLE
Bake ID material map not working

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#530]
v0.8 (2020-08-07) - 7aa59a6
Win 10 64 bit
Good day! I specially for the test install a 30-day version of 3ds max. To check the baking ID material map. Specify ID material to polygons. Exported the model to .obj. And when baking the ID material, it gives me this result. Object ID is the same story.
![1](https://user-images.githubusercontent.com/65244629/89988570-6a947a80-dc88-11ea-83ae-69c54f60ae01.jpg)
![2](https://user-images.githubusercontent.com/65244629/89988574-6bc5a780-dc88-11ea-8299-cd1b1fe37b8f.jpg)
![3](https://user-images.githubusercontent.com/65244629/89988575-6bc5a780-dc88-11ea-972b-6bcafd5f8035.jpg)
![4](https://user-images.githubusercontent.com/65244629/89988577-6c5e3e00-dc88-11ea-9d42-0cc03e9f636d.jpg)
Maybe, of course, because I installed the old version of 3ds max?

**Comment by luboslenco** [comment]
Hello, the material id bake turns the painted materials into a color map. The object id bake turns the mesh parts into a color map. Hoping the pictures below are helpful.

![1](https://user-images.githubusercontent.com/3685704/91342182-f2c36580-e7da-11ea-96b1-9294d000296d.PNG)

![2](https://user-images.githubusercontent.com/3685704/91342194-f5be5600-e7da-11ea-836b-4320f34c7a0b.PNG)

![3](https://user-images.githubusercontent.com/3685704/91342376-3b7b1e80-e7db-11ea-9290-2b6603b233ec.PNG)

**Comment by AlexKiryanov** [comment]
Good day! And I thought that when baking these map, it takes information from the object (like vertex color). In 3ds max, there is this data(id mat and id object), so I thought so. Now I understand what you meant by this tool. 
Baking an object id map, yes, it works for a multi-object model, that's right! I just thought that he would take data from 3ds max
But now it is not clear. In my opinion, the importance of baking this map (id material) is in preparing the areas that I will paint in the future, and not after that ...
Of course, I understand that there is a function for breaking the model into parts from materials when you import it into the program. This is similar to the id material map.
