### ISSUE TITLE
How to Pivot camera about selected face

### ISSUE THREAD

**Issue by Ulazygit** [armory3d/armorpaint#532]
In blender, you select a face, then press . and all viewport movements are fixed to this face. How to do this in armor?

**Comment by AlexKiryanov** [comment]
Good day! Not how. You can't choose a polygon here. And all the manipulations with the camera in the picture.
![test2](https://user-images.githubusercontent.com/65244629/90227513-5f268800-de1d-11ea-819e-bb6431e39c0e.jpg)

**Comment by luboslenco** [comment]
Will make it happen eventually, linking with https://github.com/armory3d/armorpaint/issues/251.
