### ISSUE TITLE
Armorpaint not exporting textures.

### ISSUE THREAD

**Issue by kdh20001** [armory3d/armorpaint#533]
Hi, i apologize if this has already been answered, but i found nothing on the topic. I manually installed the free version of Armorpaint to texture my video game models from blender and use them in unity3D. when I try to export my finished texture it says export completed in the console, but no textures can be found in the folder I chose. I have already saved the project before trying to export. any help would be appreciated and I can answer any further questions if needed.
thank you!!

**Comment by AlexKiryanov** [comment]
Good day! Maybe a strange question, but can you send the source, I will try to export textures? Honestly, I've never had such problems.

**Comment by CodeLineNull** [comment]
I have also had this problem. Whenever, I try to export textures by selected layer, it allows me to export to a location, but then freezes and doesn't let me click, drag or do anything. If I maximise the window, everything goes black and I am forced to close it and restart.

**Comment by AlexKiryanov** [comment]
What version of the program do you have and what operating system? And you can send the source code, which does not export for you, will I try to do it on my own?

**Comment by luboslenco** [comment]
Is there a `stderr.txt` file generated alongside the ArmorPaint binary (`ArmorPaint.exe`)?

> I manually installed the free version of Armorpaint

If that means compiling the git version, do you get any error output in Visual Studio / Xcode / terminal? 

> Whenever, I try to export textures by selected layer

Does exporting visible layers work?

**Comment by CodeLineNull** [comment]
Exporting visible layers sometimes works better, but it combines all the layers into one texture, which messes with the textures if the model consists of multiple objects. OS is Windows 10 and using version 0.8

**Comment by AlexKiryanov** [comment]
In this situation
1.Select the texture object you want to export (so that he is only one in the viewport) and export as visible
2. Or hide all layers related to other objects and export as visible

**Comment by kdh20001** [comment]
I apologize I was asleep, 

[LowRes.zip](https://github.com/armory3d/armorpaint/files/5075932/LowRes.zip)

I also tried to export the Console Logs but they would not export just like the textures!! it seems I cannot export anything I can only save my work as an .arm file

**Comment by kdh20001** [comment]
> I have also had this problem. Whenever, I try to export textures by selected layer, it allows me to export to a location, but then freezes and doesn't let me click, drag or do anything. If I maximise the window, everything goes black and I am forced to close it and restart.

This same thing just happened to me! when I attempt to export from File \ Export Textures... nothing happens. the application freezes up for a bit then unfreezes and the terminal says 'textures exported' but no textures can be found in the folder. 

then if I try to do it by left clicking the layer and choosing export it makes everything freeze and when i maximize all but the model display window turn black.

**Comment by AlexKiryanov** [comment]
I'm really intrigued! To be honest) I downloaded the file from the archive there is nothing there. more precisely, only one arm file without textures.
kdh20001  can you send your file?

**Comment by luboslenco** [comment]
> Is there a stderr.txt file generated alongside the ArmorPaint binary (ArmorPaint.exe)?

**Comment by kdh20001** [comment]
[stderr.txt](https://github.com/armory3d/armorpaint/files/5076304/stderr.txt)

yes here is the stderr file. i am having trouble with my saves right now... i am trying to save a low resolution version of my armorpaint file but its not working so far. ill keep trying but it seems like it losses some of its properties, textures, and data when i zip it...

maybe this one will work..? i might reinstall the whole application honestly.
[LowResolution1.zip](https://github.com/armory3d/armorpaint/files/5076316/LowResolution1.zip)

**Comment by kdh20001** [comment]
no. that zip file did not work. it does not save the mesh data. its just a cube with my texture on it...

**Comment by kdh20001** [comment]
i've been simply trying to save the project in armorpaint then zip it using 7zip because Github does not support .arm files.. is this the correct way to share armorpaint projects? i'm sorry i am very new to this application.

**Comment by luboslenco** [comment]
Thanks for the stderr file. However the error seems to indicate you were importing a .tiff file and access to the file has been denied, so I am a bit lost now.

Could there be any third party software restricting file access for ArmorPaint on your system?

Can you clarify your OS and what does `manually installed the free version of Armorpaint` mean? Is it the git version compiled from source? If so then you should get an error output when running from Visual Studio (assuming Windows).

**Comment by kdh20001** [comment]
I am running windows 10 and I meant that I built the binarys myself following this youtube video. 
https://www.youtube.com/watch?v=y6h2KOP47ZY
and yes i used the source from Git. 

Maybe I should reinstall using another video? I am not familiar with all of the programs used to install armorpaint. If all else fails I will just buy the Armorpaint app because I am meddling in things I do not understand and also after using it even though I am unable to export my textures I am very impressed with the painting and I enjoy the simplistic UI.

**Comment by kdh20001** [comment]
I AM A MORON!
My Antivirus was blocking some Krom and visual studio processes! I simply disabled my antivirus for Armorpaint and everything works great now. This is beyond embarrassing. thank you all for your time and support!

**Comment by kdh20001** [comment]
Should I delete this thread or should I leave it for any potential newcomers who might have forgot to set their antivirus preferences to allow Armorpaint to run correctly?

**Comment by luboslenco** [comment]
Glad to hear it's working now! Thanks again for reporting the issue, will come super handy the next time something like this happens. Also thanks to the @AlexKiryanov for the help on the issue tracker!

**Comment by AlexKiryanov** [comment]
You are welcome Lubos)

вс, 16 авг. 2020 г. в 01:17, Lubos Lenco <notifications@github.com>:
