### ISSUE TITLE
Massive mesh import issue

### ISSUE THREAD

**Issue by francis33** [armory3d/armorpaint#534]
Hello,

I'm a new user of ArmorPaint (last version)
Most of the time, I can't manage to import correctly .OBJ format meshes.

It seems to be always the same issue : 

1) At the start, the import seems to be correct. I can rotate the object, view it, light it, ...
2) When i make the mesh appears, the mesh seems to be totaly disorganized.
3) when i try to color the object, all the faces are colored at the same time, without any respect of their location.

I attached several screen captures : 

1) I made a sphere (.OBJ file) 
2) I import it in Meshlab software, to control it. The mesh seems OK. I can color each face individually (attached picture 1)
3) I import the same file in Armorpaint. All seems OK (picture 2)
4) If i inspect the mesh, it looks totaly disorganized. The mesh seems so dense that the sphere appears nearly black (picture 3)
5) I started to paint the sphere with red color. At the first strocke of brush, the majority of the faces simultaneously turned red (picture 4). As if "millions" of faces were linked and that painting one face leads to paint all the faces.

I noticed the same phenomenon on different .OBJ files, coming from different modeling softwares, each time with a variying degree of disorganization of the mesh.

![Picture 1](https://user-images.githubusercontent.com/53442186/90267578-0e7f5100-de56-11ea-89f8-44d4b68fa631.jpg)
![Picture 2](https://user-images.githubusercontent.com/53442186/90267589-1212d800-de56-11ea-895a-e61a5844ebe0.jpg)
![Picture 3](https://user-images.githubusercontent.com/53442186/90267593-13dc9b80-de56-11ea-82d4-b4dfdef83154.jpg)
![Picture 4](https://user-images.githubusercontent.com/53442186/90267609-19d27c80-de56-11ea-83f4-5cff21aab22e.jpg)

Is it a bug ? Is something missing in my files ? How can I correct it ?

Thanks for this software
Francis

**Comment by luboslenco** [comment]
Hello,

Thanks for report! How does your UV map look like? Does every face occupy unique space on the UV map? If possible you can also attach zipped obj file and I will investigate.

**Comment by francis33** [comment]
Thanks for a so quick answer !

Concerning all the files i tested, there were no UV map, only the .OBJ file without any specific texture ("naked" objects).

I attached 3 zipped exemple files : 

1. "cycle.obj" : once imported, the mesh seems very neat. The painting process works nearly correctly. Once again, some faces seem linked, painting a specific part of the object lead to paint synchronously another part of the object.

2. "wagon.obj" : once imported, the mesh seem very messy. The painting process is nearly out of control
 
3. "sphereref.obj" : the imported mesh seem so dense and so messy that the painting process is out of control and quite slow

If my files are wrong, your help will be precious.
If it a bug and I can contribute to the development of armorpaint, it' a pleasure.

Best.
Francis

[Cycle.zip](https://github.com/armory3d/armorpaint/files/5075884/Cycle.zip)
[wagon.zip](https://github.com/armory3d/armorpaint/files/5075885/wagon.zip)
[Sphereref.zip](https://github.com/armory3d/armorpaint/files/5075887/Sphereref.zip)

**Comment by luboslenco** [comment]
Thanks for the files. The .obj meshes need to have a UV map with non-overlapping faces, otherwise there is no way to apply the (painted) textures onto them properly. (for example you can generate one in blender via [smart uv project](https://docs.blender.org/manual/en/latest/modeling/meshes/editing/uv.html?highlight=smart#smart-uv-project))

**Comment by francis33** [comment]
Thanks you once again !

I'm a newbie in 3D texturing but I learn quite quickly.

Last question : when you generate the UV map, is this map included in the .OBJ file during the export process ?
Or is it an additional file ? And if so, what is the "usual" file format ?

I must improve .. :-)

Tanks for your dedication
Francis

**Comment by luboslenco** [comment]
Yes, the UV map will be stored directly in the .OBJ file, alongside vertex positions and normals. Please feel welcome to post additional questions.
