### ISSUE TITLE
Text overlaps or overflows in the Japanese menu

### ISSUE THREAD

**Issue by shiena** [armory3d/armorpaint#535]
**ArmorPaint version:**
v0.8 (2020-08-15) - 014a8a9

**OS/device including version:**
Windows - Direct3D11

**Issue description:**
The translated Japanese text has a lot of characters, so the menu text overlaps or overflows.

**Steps to reproduce:**

File Menu
![image](https://user-images.githubusercontent.com/1295639/90309896-6fc32500-df27-11ea-8dbf-718e014371e2.png)

Bake Menu
![image](https://user-images.githubusercontent.com/1295639/90309907-8f5a4d80-df27-11ea-9e8d-d0e5616d7abc.png)

**Comment by luboslenco** [comment]
Would a bit smaller font size still be legible, or do we need to increase the width of those menus instead?

**Comment by shiena** [comment]
I changed the font size to 13 and most menu text was able to avoid overlap. But the text size of the menu and menu items do not match.

![image](https://user-images.githubusercontent.com/1295639/93021877-63161780-f620-11ea-8fa3-0f84f8a960cb.png)

**Comment by luboslenco** [comment]
Increased the width at https://github.com/armory3d/armorpaint/commit/25ce14855312e494f5f949b9e383896d6a143b1b. Will eventually calculate the width as needed but this should at least resolve the overlaps for now.
