### ISSUE TITLE
Crash on Texture Import Ubuntu 20.04

### ISSUE THREAD

**Issue by baseballCameron** [armory3d/armorpaint#536]
-->
*ArmorPaint version:*
I am using the current stable build from gum road.

*OS/device including version:*
I am using Ubuntu 20.04 with an Intel® Core™ i7-2600K CPU @ 3.40GHz × 8 along with an AMD Radeon RX 560 graphics card with the latest driver (I have tried amdgpu-install and amdgpu-pro-install with the same results)

*Issue description:*
I have imported my .blend model and ready to starting texturing/painting the model. When I try File>Import Texture, or drag and drop the texture folder the moment I import the textures the whole program crashes without warning.

*Steps to reproduce:*
[Armorpaint bug report-2020-08-16_09.29.59.zip](https://github.com/armory3d/armorpaint/files/5080710/Armorpaint.bug.report-2020-08-16_09.29.59.zip)

**Comment by HRAFNYX** [comment]
Same on Manjaro Linux

_ArmorPaint version:_
ArmorPaint_08dev_linux64

_OS/device including version:_
Manjaro 20.0.3 KDE on two devices

It crashes with a message in Konsole:
free(): invalid pointer

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/armory3d/armorpaint/issues/545, thanks for report!
