### ISSUE TITLE
Adding Nodes via spacebar search menu results in duplicates

### ISSUE THREAD

**Issue by webredraptors** [armory3d/armorpaint#538]
**Software Version:** ArmorPaint.org - v0.8 (2020-08-06) - 7aa59a6
**OS:** Windows - Direct3D11
**Hardware:** NVIDIA GeForce GTX 1060 3GB

Adding multiple nodes of same type by pressing 'Enter' on keyboard results in duplicate nodes created. To reproduce: open a new project, open the node editor, and start adding nodes by pressing spacebar and searching for a particular node. Press 'Enter' to add the node and repeat the process until a duplicate occurs. It generally happens every other node for me. It appears to happen only when adding the same type of node repeatedly.

**Comment by luboslenco** [comment]
Thanks for report. Any chance you have higher than 60hz monitor?

**Comment by webredraptors** [comment]
> Thanks for report. Any chance you have higher than 60hz monitor?

I do in fact. It's a 144hz variable refresh rate monitor.

**Comment by luboslenco** [comment]
Resolved now in the latest builds.
