### ISSUE TITLE
How to preview noise/(etc...) textures?

### ISSUE THREAD

**Issue by Ulazygit** [armory3d/armorpaint#539]
Sorry if this is a stupid question. How do I preview a noise/generated texture? This is because I want to use them for mixing etc.

**Comment by AlexKiryanov** [comment]
Hello! And again I)  I just plug the noise texture output factor into the material's diffuse channel. I have not found another method.  Maybe a dumb answer but sorry)

**Comment by luboslenco** [comment]
Added a node preview feature in the latest builds, will add more options to it along the way.

![Untitled-1](https://user-images.githubusercontent.com/3685704/91867189-a4e3ad00-ec73-11ea-852b-0993857c991f.png)
