### ISSUE TITLE
Edge highlight for material

### ISSUE THREAD

**Issue by tobyplowy** [armory3d/armorpaint#541]
How do I make my material have a highlight on the corners of my material?
The idea is to make the material do all the work so i can just bucket fill the whole mesh and have it do all the work for ma after the setup. I want the material to get the highlight in the areas that are marked red. 
![image](https://user-images.githubusercontent.com/16853304/90681609-f64b6f80-e263-11ea-8cc5-ec2b05946b38.png)
I did find the geometry node that has a spottiness value but was unable to figure out how to hook it into the material output. 
Also related question how do I make materials appear only in crevices? (For things like rust)

**Comment by AlexKiryanov** [comment]
https://www.youtube.com/watch?v=k3P3CX-aK94&list=PLQFW7x3qFlrDBVFyx7LR4Ig0gZm8ab3u7
Hello! Here is a good channel with lessons on armor paint

**Comment by luboslenco** [comment]
Linking with issue at https://github.com/armory3d/armorpaint/issues/145.
