### ISSUE TITLE
Is there any way to blend texture seams? 

### ISSUE THREAD

**Issue by tobyplowy** [armory3d/armorpaint#542]
Tile is fairly self explanatory. I get these seams on my model for the UVs and was hoping that this program would be able to texture blend across these as if they weren't there as 3Dcoat and substance does. Any way to make the program do it like a setting or something? Below is the issue I'm having. 
![image](https://user-images.githubusercontent.com/16853304/90682087-bfc22480-e264-11ea-9764-17f0c515686b.png)

**Comment by daniloulf** [comment]
Did you try the clone tool? https://youtu.be/fbwsNprwPUQ

**Comment by tobyplowy** [comment]
I meant automatically.

**Comment by luboslenco** [comment]
Increasing the `Preferences... - Usage - Paint Bleed` value should help it go further. Hoping to also enable the new dilate technique soon.
