### ISSUE TITLE
Krom(incompatible)

### ISSUE THREAD

**Issue by linxy1122** [armory3d/armorpaint#543]
Hello just realize that the file was incompatible , which version is the code running?
![Capture](https://user-images.githubusercontent.com/69972320/90774063-77206f00-e329-11ea-8ce8-74a5d5d628d0.PNG)

**Comment by Korokoukousei** [comment]
Unfortunately I am facing the same issue no idea how to solve it. I think we must use visual studio 2017. Im not a coder so bear with my terminology.

**Comment by luboslenco** [comment]
Visual Studio 2019 is recommended, please make sure to install components for compiling c++ code during the Visual Studio install process.

**Comment by Lite5h4dow** [comment]
hi, im having this issue and i have the C++ build tools installed
