### ISSUE TITLE
User keymap doesn't work correctly

### ISSUE THREAD

**Issue by Eisenblute** [armory3d/armorpaint#544]
**ArmorPaint version:**

v.0.8 (2020-08-19)

**OS/device including version:**

Windows 7 x64, GForce GTX 750

**Issue description:**

When you've edited keymap, two commands works with problem.
Pressing a key activate and change parameter but after releasing your cursor will be freezed.

**Steps to reproduce:**

- Change keys for "brush_angle" and "brush_opacity" to your own (no matter if you export keymap or not).
- Hold a key to activate/change parameter then release it and you can't move the cursor.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/a0b49ab1ffa61df416ebf5f53cf10ed4b6bdffb3, thanks for report!
