### ISSUE TITLE
"Not enough memory on Image C Buffer." (outofmem than Segmentation Fault)

### ISSUE THREAD

**Issue by PWAckerman** [armory3d/armorpaint#545]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2020-08-06) - 7aa59a6
(Linux, OpenGL)
Obtained from Itch.io

**OS/device including version:**
Linux 5.2.20-1-MANJARO running KDE Plasma, GeForce RTX 2060 SUPER (8GB)

**Issue description:**
Can run program successfully. Upon running, the following is logged in the terminal:
```
Uniform N not found.
Uniform W not found.
Uniform eye not found.
Uniform aspectRatio not found.
Uniform brushScale not found.
```
Default cube mesh loads. Most standard tools work: Can project text and decals onto the surface. Can paint on and erase from the surface. Can adjust base colors through node interface as well as surface qualities (roughness, metallicness, etc.). Can use default texture nodes as input to the material output (brick, grid, noise, etc.). Can navigate history. Can use particle brushes. Can't seem to use clone tool, but may just be limitations of how the tool actually works. I can import and paint other meshes besides the default (some meshes have issues, but thats probably the mesh's fault). If I try to import a custom font, the program goes into a looping error, where the following is continuously printed to the terminal:
```
Trace: TypeError: Cannot read property 'get_length' of null
    at Function.kha_graphics2_truetype_StbTruetype.stbtt__run_charstring (<anonymous>:1:922994)
    at Function.kha_graphics2_truetype_StbTruetype.stbtt__GetGlyphInfoT2 (<anonymous>:1:925852)
    at Function.kha_graphics2_truetype_StbTruetype.stbtt_GetGlyphBox (<anonymous>:1:911853)
    at Function.kha_graphics2_truetype_StbTruetype.stbtt_GetGlyphBitmapBoxSubpixel (<anonymous>:1:927523)
    at Function.kha_graphics2_truetype_StbTruetype.stbtt_GetGlyphBitmapBox (<anonymous>:1:927810)
    at Function.kha_graphics2_truetype_StbTruetype.stbtt_BakeFontBitmap (<anonymous>:1:937914)
    at kha_Kravur._get (<anonymous>:1:864808)
    at kha_Kravur.width (<anonymous>:1:865319)
    at Function.arm_util_RenderUtil.makeFontPreview (<anonymous>:1:188696)
    at l (<anonymous>:1:400752)
```
This freezes most of the GUI and toolbars, but the viewport for the model can still be orbited. The program is essentially unusable at that point.

If i try to import textures to create a more complex material (arguably the whole point of the program), the texture does not appear. The program still continues to function, though the texture is unusable. This appears in the terminal:
```
Not enough memory on Image C Buffer.
outofmem
```
Upon trying to import another texture, this appears in the terminal, and the program crashes:
```
Not enough memory on Image C Buffer.
Segmentation fault
```

None of these textures are very large. They are 4k JPEGs, the largest texture being 15MB.
ArmorPaint never exceeds more than 385MB of GPU RAM according to `nvtop`.

**Steps to reproduce:**
1. Open ArmorPaint -> Import Font -> Program becomes unusable, unresponsive interface
2. Open ArmorPaint -> Import Texture -> (outofmem) -> Import Texture -> Crash

(Note that this is really two different bugs)

**Comment by luboslenco** [comment]
Should be now resolved in freshly updated builds, many thanks for the report.
