### ISSUE TITLE
Importing mesh into ArmorPaint

### ISSUE THREAD

**Issue by Korokoukousei** [armory3d/armorpaint#546]
Im trying to import this mesh into armorpaint -
https://drive.google.com/file/d/1HBpFpenh7snoo3FJqGLR48q8s89KPcxr/view?usp=sharing
This is the .blend file - 
https://drive.google.com/drive/folders/1sK76TydXYLjILHt_ieC-JwcL2GcKm6W9?usp=sharing

When I import the fbx file it has some missing polygons. When i try to import mesh from the .blend file It smooths polygons. I have applied the mirror modifier in blender to create mesh instead of having half a mesh and a hologram. But armorpaint doesnt recognize that and mirrors whatever i paint.

The .fbx file is getting imported back into blender and even into paint3D properly. I recently purchased armorpaint and cannot import rigs into it. Some help will be appreciated.

**Comment by Korokoukousei** [comment]
Thanks a lot! I'm a beginner at blender, I have learned a lot from this.

**Comment by AlexKiryanov** [comment]
You are welcome!) Don't forget to close the post.
