### ISSUE TITLE
Panning bug

### ISSUE THREAD

**Issue by Ulazygit** [armory3d/armorpaint#547]
*ArmorPaint 0.8-108078d, Windows*

Camera mode is orbit.

Holding right mouse (to pan) also causes the viewport to zoom in

**Comment by luboslenco** [comment]
How to reproduce? Any changes to the keymap?

**Comment by Ulazygit** [comment]
No idea. Changed view by pressing 1 on the numpad.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/450.
