### ISSUE TITLE
Plugins crash app

### ISSUE THREAD

**Issue by webredraptors** [armory3d/armorpaint#55]
Any attempt to enable plugins in config.arm results in an immediate crash when launching ArmorPaint. 

Affected Versions:
0.5 'cef5075' - Windows x64 Standalone
0.4 - Windows x64 Standalone

Also, the "plugins" array is not present in config.arm for v0.5. Any attempt to add it also results in a crash.

**Comment by luboslenco** [comment]
Appears ok now using the latest build, please let me know if you get to re-test it.
