### ISSUE TITLE
Segmentation fault upon opening any file open dialog

### ISSUE THREAD

**Issue by abusetech** [armory3d/armorpaint#550]
ArmorPaint version: c832cfd4e2e0cdfabc1e664692b92c1bb80223b0

OS/device including version:

R5 1600X, RX480, amdgpu drivers

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

Issue description:

Armorpaint crashes when performing any action that opens a file open dialog.

`
Thread 1 "Krom" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x5c173f60) at malloc.c:3103
3103    malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0x5c173f60) at malloc.c:3103
#1  0x0000555555608225 in ZenityCommon.constprop.0 ()
#2  0x0000555555608478 in NFD_OpenDialog ()
#3  0x0000555555614327 in (anonymous namespace)::krom_open_dialog(v8::FunctionCallbackInfo<v8::Value> const&) ()
#4  0x0000555555c561be in v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) ()
#5  0x0000555555c556c8 in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) ()
#6  0x0000555555c54dae in v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) ()
#7  0x0000555555b88c79 in Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit ()
#8  0x0000555555b06e64 in Builtins_InterpreterEntryTrampoline ()
`

Steps to reproduce:

Click File -> Open

**Comment by luboslenco** [comment]
Linux is trying to put me into a grave, I just tested on Ubuntu 18.04.4 and it works fine here. Please see https://github.com/armory3d/armorpaint/issues/179 for temporary solution - enabling the built-in file browser. For import drag and drop should work as an alternative. Will try switching to gtk from zenity to fix it.
