### ISSUE TITLE
Non-square stencil / stencil color

### ISSUE THREAD

**Issue by Zoro-xu** [armory3d/armorpaint#553]
I tried to modify the source code so that the stencil feature could draw color information like Blender, not just for masks, but I found that large images could not be drawn at a 1:1 scale.

![Stencil Bug](https://user-images.githubusercontent.com/70063979/91633760-7b314880-ea1d-11ea-932f-67b68174ebb2.gif)

The size of the image is 1920 x 1080.
What am I supposed to do?

**Comment by dasparadoxon** [comment]
( only stencils with same width and heigth are working at the moment. I noticed that too. )

**Comment by Zoro-xu** [comment]
I've solved this problem, but I hope to be able to add this feature to the next version of the AP, which will be useful.

**Comment by Zoro-xu** [comment]
I've solved this problem, but I hope to be able to add this feature to the next version of the ArmorPaint, which will be useful.
Thanks.

**Comment by luboslenco** [comment]
Fixed support for non-square stencils. Thanks for report.

For color - I will have to think about the solution, because brush nodes are not supposed to touch material values (like base color). Will try to improve the decal tool for this purpose.
