### ISSUE TITLE
Pink / missing textures on project open

### ISSUE THREAD

**Issue by Ulazygit** [armory3d/armorpaint#555]
![bug](https://user-images.githubusercontent.com/60723284/91671824-d482a000-eb21-11ea-86cd-c938f13c4fa7.JPG)
*ArmorPaint 0.8-108078d, Windows*

Closing and reopening a project causes materials to 'dissappear' becayse the texture maps can no longer be loaded. Even when trying to reimport the image textures, they still appear pink. Reimporting option also causes a CTD. Annoying as it means I cant open a saved project correctly.

**Comment by luboslenco** [comment]
Sorry but I am unable to reproduce, any details which would help?

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/389.
