### ISSUE TITLE
Not able to load blend materials

### ISSUE THREAD

**Issue by mkbreuer** [armory3d/armorpaint#556]
**ArmorPaint version:**  v0.8 / 2020-07-100-0e3be018

**OS/device including version:** Win 10

**Issue description:** Armorpaint does not know Principle BSDF Node

**Steps to reproduce:** try to load materials from blend 2.79 and 2.8x

**Comment by luboslenco** [comment]
Hm, the Principled BSDF node should get converted into the Material Output node in ArmorPaint. Will investigate at existing issue https://github.com/armory3d/armorpaint/issues/36, thanks for report.
