### ISSUE TITLE
Texture not repeating via mapping node

### ISSUE THREAD

**Issue by Ebbombe** [armory3d/armorpaint#557]
Hi, when I create a new material importing textures I want to scale the images over the 1 limit, I tried to put 2 (even tried 10 to test) on scale and it should repeat the texture tile itself, my setup is correct (i am almost sure of it).
I should open gimp, repeat the image tile, save the image and reimport in ArmorPaint to achieve the result i want. 
I don't know if this is a bug or it's intended to not go above the 1 value scaling so maybe it should be a request feature.

**Comment by luboslenco** [comment]
Hi, thanks for report. Can you provide more details? Which OS? Which ArmorPaint version? Where did you put 2 on the scale - in the node editor?

**Comment by Ebbombe** [comment]
I pulled the repo on Github yesterday morning, Windows 10, I am using color id map to populate the texture, in the image attached you can see that the wall's texture is way too much little because the original texture tile has not appropriate dimensions, i want to be able to upscale the image procedurally without using gimp.

![555](https://user-images.githubusercontent.com/51931587/91867047-76fe6880-ec73-11ea-8c4a-ad506673375d.png)

**Comment by luboslenco** [comment]
Direct3D11 or Direct3D12? It seems to work like usual for me (repeats the texture), anything which could help me to reproduce the issue? Does it happen on the default cube as well for you?

**Comment by luboslenco** [comment]
Found the similar issue - please let me know the details at https://github.com/armory3d/armorpaint/issues/471.
