### ISSUE TITLE
Seg fault when clicking import

### ISSUE THREAD

**Issue by lewis2e** [armory3d/armorpaint#560]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2020-09-03) - b2b8987

**OS/device including version:**
Linux - OpenGL
Arch
Intel integrated graphics

**Issue description:**
Clicking the import button under either Materials or Brushes just causes an instant crash:
/usr/bin/armorpaint: line 3: 251891 Segmentation fault      (core dumped) /usr/lib/armorpaint/Krom /usr/share/armorpaint/krom

Same result when choosing import options from the file menu. And on export. I guess basically anything trying to trigger a file selection dialogue.

Coredump attached

**Steps to reproduce:**
Open application and click import button
[coredump.zip](https://github.com/armory3d/armorpaint/files/5170579/coredump.zip)

**Comment by luboslenco** [comment]
Thanks for report - details and temporary fix at https://github.com/armory3d/armorpaint/issues/179.
