### ISSUE TITLE
Freeze after clear layer group

### ISSUE THREAD

**Issue by shiena** [armory3d/armorpaint#561]
**ArmorPaint version:**

v0.8 (2020-09-04) - b2b8987

**OS/device including version:**

Windows10
non-DXR
NVIDIA GeForce GTX 1080 Ti

**Issue description:**

**Steps to reproduce:**

1. Launch armorpaint
1. Run To Group from the Layer 1 pop-up menu
1. Select a new group on layer tab
1. Run Clear from the group pop-up menu  
![image](https://user-images.githubusercontent.com/1295639/92158009-3c105680-ee66-11ea-9efe-006bcdfb7e39.png)

**stderr.txt**

```
TypeError: Cannot read property 'get_g4' of null
    at arm_data_LayerSlot.clearLayer (<anonymous>:11795:17)
    at clear2 (<anonymous>:25796:10)
    at Array.iron_App.render (<anonymous>:2512:4)
    at Function.kha_System.render (<anonymous>:37342:34)
    at kha_SystemImpl.renderCallback (<anonymous>:37400:13)
```

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/aceb8c1291016be8789061ea95438dca13b7b955, thanks for report!
