### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by 9Matte** [armory3d/armorpaint#562]
**ArmorPaint version:**
v0.8

**OS/device including version:**
Windows 7
GTX 750TI

**Issue description:**
I followed all the steps in the compile guide for Windows, but when I click build (after setting release, all project settings...), it give me these errors. I tried remove everything and reinstall everything, but nothing changed.

I build with Visual studio 2015.
I also tried Visual studio 2019, but it give me more and more errors, like he can't find dtdlib.h or other libraries and i don't know why becouse I have c/c++ extension installed
![Error](https://user-images.githubusercontent.com/67808167/92218877-100ec880-ee9a-11ea-90df-9ba44572759c.PNG)

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Sorry but I have never seen those, not sure what is wrong. The regular builds are done on Windows 10 and Visual Studio 2019, so I would start with these first and see if that works before trying to compile on Windows 7 and Visual Studio 2015.

**Comment by 9Matte** [comment]
ok thanks.
I tried on my laptop with Windows 10 and Visual studio 2017 and it worked. Maybe I suggest add Windows 10 as requirement, maybe that's the problem
________________________________
Da: Lubos Lenco <notifications@github.com>
Inviato: venerdì 4 settembre 2020 10:47
A: armory3d/armorpaint <armorpaint@noreply.github.com>
Cc: 9Matte <matteo-0199@hotmail.it>; Author <author@noreply.github.com>
Oggetto: Re: [armory3d/armorpaint] Error while compiling (#562)


Closed #562<https://github.com/armory3d/armorpaint/issues/562>.
