### ISSUE TITLE
Color ID artifacts

### ISSUE THREAD

**Issue by VooqadAfterburner** [armory3d/armorpaint#564]
**ArmorPaint version:**

![image](https://user-images.githubusercontent.com/70160112/92258164-51b96680-eece-11ea-8d00-986c9f0b9496.png)
nvidia drivers:  452.06

**OS/device including version:**

![image](https://user-images.githubusercontent.com/70160112/92260435-cd67e300-eecf-11ea-9e21-c3cf8c4ba616.png)

**Issue description:**

I'm seeing the artefacts displayed below when using a colour ID and either filling or painting.

If I clear the selected ID materials can be painted without issue.

Exported textures display the same artefacts.

![image](https://user-images.githubusercontent.com/70160112/92258131-42d2b400-eece-11ea-9e21-777d7683da7c.png)

I've rebuilt the model, UV's, colour ID; none of it helped.

This only started happening after I switched to the latest version of ArmorPaint; wasn't happening in the previous version.

**Steps to reproduce:**

**Comment by VooqadAfterburner** [comment]
![image](https://user-images.githubusercontent.com/70160112/92514870-8f89f800-f20a-11ea-8928-72ca8d50ad7c.png)

**Comment by luboslenco** [comment]
Can I have a look at the example files which are causing the trouble so I can reproduce the issue?

**Comment by VooqadAfterburner** [comment]
[containment_unit.zip](https://github.com/armory3d/armorpaint/files/5190607/containment_unit.zip)

**Comment by luboslenco** [comment]
Thanks! If I adjust the color id map contrast I can see the artifacts on the map itself. Is the map baked in ArmorPaint?

![cID2](https://user-images.githubusercontent.com/3685704/92640579-c977fe80-f2dd-11ea-8135-4a3a6ca5d190.png)

**Comment by VooqadAfterburner** [comment]
Actually no, it was baked in Maya.
Any idea what could be causing them?
They're not visible at any point during the Maya workflow, and I've rebuilt that model and the UV's a number of times......?


9 Sep 2020, 19:51 by notifications@github.com:

**Comment by luboslenco** [comment]
Sorry, no experience with baking the maps in Maya, not sure why it exports a map like this.

**Comment by VooqadAfterburner** [comment]
Guess I'll start baking the maps in AP then.  :)

I ramped up the contrast using GIMP; can't see these artefacts.  What are you using?

Thanks for your help!
Tom.


10 Sep 2020, 14:29 by notifications@github.com:

**Comment by luboslenco** [comment]
IIRC I also played with brightness, but you just zoom in on the original picture with no edits. 🙂 

![Capture](https://user-images.githubusercontent.com/3685704/92754208-e74f6d00-f38a-11ea-8d77-9ded4d2b137a.PNG)

**Comment by VooqadAfterburner** [comment]
This is weird man.  All I see is a big red box, nothing else.


10 Sep 2020, 16:29 by notifications@github.com:

**Comment by VooqadAfterburner** [comment]
800% zoom did it.
What the?!


10 Sep 2020, 16:29 by notifications@github.com:

**Comment by VooqadAfterburner** [comment]
*** Mental note.  View thread, not just emails. ***
