### ISSUE TITLE
Black spots everywhere on my .obj model.

### ISSUE THREAD

**Issue by mufabil45** [armory3d/armorpaint#565]
**ArmorPaint version:**

![image](https://user-images.githubusercontent.com/37070857/92299421-41f85b80-ef7c-11ea-8be5-509df4883486.png)

**Issue description:**
The models doesn't work properly. Its cluttered with bunch of black spots and It cant be painted.  
Here the error gif image
https://postimg.cc/rKqtZc6J

**Steps to reproduce:**
I just imported the model from game SimplePlane. 
Here the file to reproduce the error. I tried many import the option but it's just doesn't work
[USF - 45_model.zip](https://github.com/armory3d/armorpaint/files/5177623/USF.-.45_model.zip)

**Comment by luboslenco** [comment]
Hi, your model needs to be UV unwrapped - the UV map tells how the texture should be mapped onto the model.

- [Unwrap in Blender](https://docs.blender.org/manual/en/2.83/modeling/meshes/editing/uv.html#smart-uv-project) (or any other 3D modelling/unwrapping software)
- [Unwrap in ArmorPaint via uv_unwrap plugin](https://www.youtube.com/watch?v=4asEjcYG8Eg&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=24)

I have attached a mesh unwrapped via the `Smart UV Project` tool in Blender.

[USF - 45_export_new.zip](https://github.com/armory3d/armorpaint/files/5177653/USF.-.45_export_new.zip)

**Comment by mufabil45** [comment]
Thx man, I highly appreciate it. Thought some tooltip of this issue might help others.
