### ISSUE TITLE
Importing crashes

### ISSUE THREAD

**Issue by mfiano** [armory3d/armorpaint#566]
**ArmorPaint version:**
d596bef

**OS/device including version:**
Arch Linux, NVIDIA GTX 1070, nvidia 450.66

**Issue description:**
Clicking on any of the Import menu items under File crashes with a segmentation fault.
```
/usr/bin/armorpaint: line 3: 55987 Segmentation fault      (core dumped) /usr/lib/armorpaint/Krom /usr/share/armorpaint/krom
```

**Steps to reproduce:**
Select any Import menu item

**Comment by luboslenco** [comment]
Please check here for a temporary fix https://github.com/armory3d/armorpaint/issues/179, proper fix hopefully soon.
