### ISSUE TITLE
Masking brush creating weird outline

### ISSUE THREAD

**Issue by agnira** [armory3d/armorpaint#568]
**ArmorPaint version:** v0.8 (2020-08-31)

**OS/device including version:** Ubuntu 20.04, GeForce GTX 1050

**Issue description:**
![image](https://user-images.githubusercontent.com/67183228/92709562-3abcbd80-f381-11ea-849e-3b9b801780c2.png)
the brushes creating some outline, which makes masking not going well

**Steps to reproduce:**
I'm just drawing as usual, and this only happens inside the layer mask. on the paint layer everything is going well.

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/armory3d/armorpaint/issues/312.
