### ISSUE TITLE
Windows Defender thinks ArmorPaint.exe is a virus

### ISSUE THREAD

**Issue by tbrosman** [armory3d/armorpaint#569]
**ArmorPaint version:**

ArmorPaint_08dev_win64

**OS/device including version:**

Windows 10 Version 1909 (OS Build 18363.1016)
Windows Defender updated on 2020.9.9

**Issue description:**

I unzipped ArmorPaint and Windows Defender popped up. Here's what it says:

![image](https://user-images.githubusercontent.com/3754050/92764518-573d0380-f349-11ea-9b16-818f5ecc1f93.png)

Likely a hash collision. You submit false-positives here: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by luboslenco** [comment]
Thanks for opening the issue. I did a Windows update and suddenly got `ArmorPaint.exe` wiped from my machine. I updated the `ArmorPaint_08dev_win64` builds now to the latest git revision, and all seems well so far. I have submitted the troubling `ArmorPaint.exe` binary, hopefully that helps. If anyone still encounters this please let me know.
