### ISSUE TITLE
Accidentally Purchased Wrong Version of ArmorPaint

### ISSUE THREAD

**Issue by k1aatu34** [armory3d/armorpaint#570]
Hello Armory dev,

I was trying to find where to purchase ArmorPaint on your website and I accidentally purchased the itch.io version which was 19 euros. When I checked out the manual, it said that the version of ArmorPaint available on Gumroad gets consistent updates without having to redownload the software, which would be ideal for me. The Gumroad version is also only 16 Euros. Is there any way you could give me a refund through PayPal for the itch.io version, so that I can go ahead and buy the Gumroad version? I would much rather have my software connected to an automatic update pipeline like Steam and Gumroad have.

Thanks,

Evan E.

Discord: k1aatu34#0748
Paypal: erelms84@gmail.com

**Comment by Granada1** [comment]
You still get the same updates 👍

**Comment by luboslenco** [comment]
Hello, many thanks for support! Like @Granada1 says both are the same versions, updated at the same time. 🙂 Gumroad adds a tax on top so it should also be the same. I have sent you a gumroad key as well, so you can pick your favorite.

The "check for updates" function can say if newer version is available, but auto-download is not yet finished. I think itchio app should actually be able to auto-update it though, similar to Steam. Let me know if there are any issues.
