### ISSUE TITLE
Missing Blender Keymap

### ISSUE THREAD

**Issue by cliffnhansen42** [armory3d/armorpaint#571]
The Armourpaint manual refers to a Default and a Blender keymap. I'd like to turn it to the Blender keymap, but only the default appears in the preset dropdown in preferences. One of the reasons why I'm excited about ArmourPaint is its connection with Blender and thus its familiarity to me, so I'd prefer to get started using that keymap. Do I need to import it from somewhere? (I'm a brand new user, just purchased and installed it yesterday.)

Here's what I see:
![keymap](https://user-images.githubusercontent.com/34868005/92938731-cfff9680-f401-11ea-9dfa-7e2b72f6e707.JPG)
![armourpaint](https://user-images.githubusercontent.com/34868005/92938948-06d5ac80-f402-11ea-99f1-bd7f25338974.JPG)

**Comment by luboslenco** [comment]
Hi, many thanks for your support!

I have planned to make this available via the upcoming [library](https://armorpaint.org/library) feature, but as usual it's taking a bit longer than expected.

The Blender keymap has camera controls set to mimic Blender:

```
	"action_rotate": "middle",	
	"action_pan": "shift+middle",	
	"action_zoom": "ctrl+middle",
```

Attached zipped keymap json file  below, it can be imported into ArmorPaint via `Preferences.. - Keymap - Import` button. Further changes to the keymap welcome!

[blender.zip](https://github.com/armory3d/armorpaint/files/5252508/blender.zip)
