### ISSUE TITLE
Tab menus disappear on minimize

### ISSUE THREAD

**Issue by azucay** [armory3d/armorpaint#573]
*ArmorPaint 0.8-3dbb7cf, Windows*

**Issue description:**
After minimizing the main window and reopening it, the tab menus on the right are positioned on top of each other. 
![image](https://user-images.githubusercontent.com/6418910/93180835-0148d100-f738-11ea-8d94-ce774dbecd7a.png)
You have to manually drag them down again to be able to use them.

**Steps to reproduce:**
Happens everytime after minimizing the window.

**Comment by luboslenco** [comment]
Fixed now, thanks for report!
