### ISSUE TITLE
The layout is automatically hidden

### ISSUE THREAD

**Issue by solorzanob90** [armory3d/armorpaint#574]
*ArmorPaint 0.8-3dbb7cf, Windows*

**Issue description: 
![Sin título](https://user-images.githubusercontent.com/12124537/93246984-357dbb00-f753-11ea-9fe4-b8d149542b1c.png)

Working with the software, every time I minimize it to look at other things, the tools that appear there marked in the image disappear, and I have to reset the layout every time this happens

**Steps to reproduce: Only when I minimize the window for a short time without using the soft

**Comment by luboslenco** [comment]
Thanks for report, fix coming soon. Link to https://github.com/armory3d/armorpaint/issues/573.
