### ISSUE TITLE
Cant build on macos

### ISSUE THREAD

**Issue by plufz** [armory3d/armorpaint#575]
Hi!

I'm having trouble building the project for macos. Not sure if I'm doing something wrong or if there is a bug. I've added the library path v8/libraries/macos/release to the search path for both debug and release. Tried both relative and absolute path, both recursive and non-recursive. But I still get:
ld: library not found for -lv8_monolith

Any ideas on why?

**Comment by ianlikestrains** [comment]
I actually had this happen on Windows 10 as well. I tried again and I got a bunch of "mismatches" when I tried to build it. Don't have any clue how to fix it though...

**Comment by luboslenco** [comment]
Hey! If the file `libv8_monolith.a` at `armorpaint/armorcore/v8/libraries/macos/release` really exists then my only guess is to double check on the library search path being set in Xcode. When I create macOS builds I set it as absolute path.

---

There was another comment which seemingly disappeared now about "mismatches": make sure to set build to release.

**Comment by plufz** [comment]
Thank you for the reply. I've dragged and drop the path from Finder to make sure it is correct. And that way you get an absolute path. No other ideas? Can you build it for macos yourself?

**Comment by luboslenco** [comment]
Yes, I update the binaries on gumroad & itchio for all operating systems including macOS ~ every week.

There are multiple search path fields in xcode, do you add the path to the library search path field? What is the Xcode and macOS version?
