### ISSUE TITLE
Weird AO Baking

### ISSUE THREAD

**Issue by vijayxd** [armory3d/armorpaint#577]
*ArmorPaint 0.8-6f8e112, Windows*

**AO Baking**

AO Baking producing unwanded black shadows

**Comment by vijayxd** [comment]
Just purchased this software to bake aomaps instantly but it's giving weird results

**Comment by luboslenco** [comment]
Hey, thanks for opening the issue & support. Use the `ArmorPaintDXR_08dev` version, which has a ray-traced AO baking. Here is more info about the DXR (DirectX Raytracing) version:
https://github.com/armory3d/armorpaint/blob/master/Assets/readme/readme_dxr.txt

The non-dxr version is using voxels which are less accurate. If you do not have a hardware capable of DXR as of now and only got the software to do the baking please [drop me an email](https://armorpaint.org/community.html) and I can send a refund. 🙂
