### ISSUE TITLE
After using alt+tab I can't paint

### ISSUE THREAD

**Issue by jcostello** [armory3d/armorpaint#579]
**ArmorPaint version:**
0.8 commit 1a27f5896404c9188090bae944823493aaf3ed93

**OS/device including version:**
Ubuntu 20.04
GT 1030

**Issue description:**
After using alt+tab I can't paint. Left and Right click changes behaviour

**Steps to reproduce:**
I start armor paint
Paint on the defaut layer (with right click)
use alt+tab to go to some other window and go back
Now left click rotates the camera even if I have the paint brush selected. Right click zooms in and out

![Peek 2020-09-20 11-04](https://user-images.githubusercontent.com/1168582/93713282-2753e400-fb31-11ea-960f-6cdb25da5545.gif)

**Comment by jcostello** [comment]
Pressing alt againt seems to fix the issue. But is not an expected behavior

**Comment by luboslenco** [comment]
Fix incoming via https://github.com/Kode/Kinc/pull/557, thanks for report.

**Comment by luboslenco** [comment]
It's in!
