### ISSUE TITLE
Resizing the window makes the mesh lose its shaders?

### ISSUE THREAD

**Issue by DiegoBM** [armory3d/armorpaint#58]
When launching armorpaint it all seems to work ok
![screenshot](https://user-images.githubusercontent.com/1613216/51903252-12569a00-23bc-11e9-9150-d4f14963026c.png)

But after maximizing the window (in Windows 10), the cube goes black making it impossible to paint.
![screenshot 2](https://user-images.githubusercontent.com/1613216/51903229-0074f700-23bc-11e9-9404-95b637fa0f55.png)

Also if you try to rotate you'll see the mesh breaking in a strange manner.
![screenshot 3](https://user-images.githubusercontent.com/1613216/51903241-07036e80-23bc-11e9-9853-43d36c98c412.png)

**Comment by luboslenco** [comment]
Hmm, does it also go black if you just very slightly resize the window? (instead of full maximize) Running at 3000x2000 display resolution?:)

**Comment by DiegoBM** [comment]
Yes, it also happens if I slightly increase the size of the windows. I am running at 3000x2000 resolution on the surface book. I have just tested in my desktop at 1920x1080 and this does not happen

**Comment by luboslenco** [comment]
Hey, any improvements in the latest build?

**Comment by DiegoBM** [comment]
Hey @luboslenco, sorry I've not been using my surface lately. I just tested the very latest version of armorpaint with the latest git sdk and it doesn't seem to present the problem anymore. Good job, and nice new version, it looks really professional!
