### ISSUE TITLE
Fedora 32 - need gtk3-devel package and change path to glib headers

### ISSUE THREAD

**Issue by metal3d** [armory3d/armorpaint#580]
**ArmorPaint version:**

master (a3fbe6476d212a6b3c0edfa60def41efff37241b)

**OS/device including version:**
Linux Fedora 32

**Issue description:**
Compilation fails but can be easily fixed

**Steps to reproduce:**
Follow instruction from README file to have a failed build.

Fixes:
- https://github.com/Kode/Kha/wiki/Linux => add gtk3-devel for fedora package to install
- at https://github.com/armory3d/armorcore/blob/5f7e6dcfcd89c7ba1c2b3bece1d4e24bd05754f4/kincfile.js#L114 => add

```
project.addIncludeDir("/usr/lib64/glib-2.0/include");
```

Then `node Kinc/make -g opengl --compiler clang --compile` should work.

**Comment by luboslenco** [comment]
Many thanks for opening this. I have added the include at https://github.com/armory3d/armorcore/commit/8b81099af95fabb48f58dc3d693876b31bafbfe5 and listed the gtk3 at https://github.com/armory3d/armorpaint/wiki/Linux-Dependencies now (edits welcome).

**Comment by metal3d** [comment]
OK, I didn't know I can edit the page.
One other note, we can change this page to install every packages in one line, instead of several `dnf` or `apt` commands.

**Comment by luboslenco** [comment]
@metal3d ArmorPaint page is at https://github.com/armory3d/armorpaint/wiki/Linux-Dependencies. (Since gtk3-devel is not needed for Kha itself. it's only required for ArmorPaint to open the file browser dialog.)
