### ISSUE TITLE
Weird error painting over seems

### ISSUE THREAD

**Issue by jcostello** [armory3d/armorpaint#581]
**ArmorPaint version:**
0.8 commit d405aee0168b8cc00931e0753d1c8258c38d3ed3

**OS/device including version:**
Ubuntu 20.04
GT1030

**Issue description:**
When paiting over seems a glitch happen. Look attachment

**Steps to reproduce:**
Open ArmorPaint
Import 2 materials
Create 2 fill layers
Create a black mask on the top layer
Paint mask over seems

![glitch](https://user-images.githubusercontent.com/1168582/93820623-d11b9980-fc33-11ea-9f4d-80114d95863d.gif)

Sorry for the quality. I have to compress it a lot to upload

**Comment by luboslenco** [comment]
It's because the material contains a height map which in turn displaces vertices in a normal direction. You can turn it off at `Preferences.. - Usage - Displacement Strength`.

**Comment by jcostello** [comment]
Seems that materials with  height maps create problems. If I apply a  material with height map map and remove it, I see the same issue until I unplug and plug again the normal map. Also some time when I apply the material with height map and delete the bottom layer then I see them bumps. Seems all related in this case

**Comment by MathemanFlo** [comment]
> 
> 
> Seems that materials with height maps create problems. If I apply a material with height map map and remove it, I see the same issue until I unplug and plug again the normal map. Also some time when I apply the material with height map and delete the bottom layer then I see them bumps. Seems all related in this case

I can confirm that behavior. Adding/removing height maps sometimes produces strange artifacts. For instance parts of the texture painted somewhere else shine through the texture having a height map.
