### ISSUE TITLE
Hang When Exporting Texture

### ISSUE THREAD

**Issue by Niknokinater** [armory3d/armorpaint#582]
*ArmorPaint 0.8-e35de33, Windows 10 64-bit Build 1903*

Upon exporting a texture painted on the model (so far of two instances, this happens 100% on the third layer export), the export dialogue will become half covered by the model viewport and Armor Paint will cease to function. Closing the program normally via the X still works as expected, however.

**Comment by luboslenco** [comment]
Hi, it seems you are using a version from July 1 https://github.com/armory3d/armorpaint/commit/e35de3390e29b2b9b15399c9eff98c6af2dc29f9. Does this still happen on the latest builds?

> this happens 100% on the third layer export

Can you give me exact steps to reproduce? Should I export third layer only? Should I export layers three times? How should my layer stack look like? Can you share the `stderr.txt` file generated alongside your `ArmorPaint.exe` binary (or Visual Studio output if building by hand)?

**Comment by Niknokinater** [comment]
I could have sworn I was up to date, despite the update check saying otherwise (are previous builds on the list overwritten ? I'm under the impression that **ArmorPaint_08dev_win64** is the latest)

I'll look to reproduce tomorrow- from memory though, I create 3+ layers, set each to a piece of a model's mesh (usually initially separated by material), then once finished, export them linearly. Twice now, the failure occurs on the export of the third layer. I did manage to eventually circumvent by setting the layer to "Shared", and hiding all of the others- that seemed to work.

As for the file, it should be included in this reply here. Thanks for the response, friend !
[stderr.txt](https://github.com/armory3d/armorpaint/files/5259751/stderr.txt)

**Comment by luboslenco** [comment]
Nice, I was able to reproduce the issue thanks to you! If you download the latest **ArmorPaint_08dev_win64** build (updated today) it will be fixed.
