### ISSUE TITLE
Confirmation popup window on closing app

### ISSUE THREAD

**Issue by adanub** [armory3d/armorpaint#583]
Pretty important UX issue, could lead to losing unsaved work due to misclick (e.g. hitting close instead of minimise/maximise), especially since its the standard in practically any competing software.

**Comment by luboslenco** [comment]
It's implemented on Windows as of now so I am assuming you are on other platform. Linux and macOS implementation planned.

**Comment by adanub** [comment]
I am on Windows 10, and there is no confirmation when closing the app, regardless of whether or not there are unsaved changes. I cloned and built it 8 hours ago, was it added more recently?

**Comment by luboslenco** [comment]
Did you do the `git apply patch/window_handling.diff --directory=Kinc` step from the instructions during build?

**Comment by adanub** [comment]
Not sure, I'll give it a try

**Comment by adanub** [comment]
That fixed it, thank you!
