### ISSUE TITLE
Toggle visibility of individual objects in a mesh

### ISSUE THREAD

**Issue by adanub** [armory3d/armorpaint#584]
I don't think this feature is available yet, looking at the existing issues, documentation and using armorpaint. At the moment I'm trying to paint a stylised hair mesh, but I cannot reach certain areas to paint as they are covered by another object. Being able to toggle the visibility of certain objects in the scene would resolve this problem.

**Comment by luboslenco** [comment]
Hi, please check the "Set Object Mask" video from the [how to](https://armorpaint.org/howto) section to select a specific mesh to paint on:
https://www.youtube.com/watch?v=9LJY2y6JyKg&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=19
