### ISSUE TITLE
Negative brush radius

### ISSUE THREAD

**Issue by adanub** [armory3d/armorpaint#585]
**ArmorPaint version:**
commit 9394e8c9862ee92fbe1798eab728201ec63636fc (latest at time of this post)

**Issue description:**
Using the [ or ] key shortcuts to adjust brush/eraser/blur/etc. width can go below 0

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/42713438/94153042-a2195800-febf-11ea-8bdf-0be1c5b5c0c3.png)

**Comment by luboslenco** [comment]
Nice, pushed a fix at https://github.com/armory3d/armorpaint/commit/955aac0cc7afbca39f403cc0e378f465ec800aaa.
