### ISSUE TITLE
UX: Don't paint/apply effects when unfocused

### ISSUE THREAD

**Issue by adanub** [armory3d/armorpaint#586]
If you're trying to focus back into the application from another monitor/window by clicking on it, can accidentally apply effects on the clicked location. Like Substance Painter, it should avoid applying things unless it is currently in focus.

**Comment by luboslenco** [comment]
Fixed via https://github.com/armory3d/armorpaint/commit/28af0f312a47f5bf1874976cb288c526138614e0. Thanks for suggestion.
