### ISSUE TITLE
Link layer to single material

### ISSUE THREAD

**Issue by adanub** [armory3d/armorpaint#587]
Ability to link a layer to override anything painted inside it to a chosen material. Would greatly improve workflow when separating layers per colour/material like I currently am, as it would prevent painting a material on the wrong layer.

**Comment by adanub** [comment]
My bad, can already do this with masks!

**Comment by adanub** [comment]
Reopening issue, it seems with masks the opacity can only be either 100% or 0, which makes it unusable for painting with a brush as hardness is ignored. Blur tool also simply erases the mask.

**Comment by luboslenco** [comment]
Both layers and mask can do it, please check here https://armorpaint.org/howto.html.

**Comment by adanub** [comment]
> Both layers and masks can do it, please check here https://armorpaint.org/howto.html.

Masking does not allow any alpha blending as I said, it rounds off the opacity of anything I paint to 0 or 1. Stencil doesn't work either, as it has nothing to do with the currently selected layer. What I am looking for is an effect similar to a "colour overlay" effect like in photoshop, where it overrides all colour in a particular layer to the same one, regardless of what material you try to apply with the brush. In this case, it would override your brush to paint the material linked to the layer, regardless of what material is currently selected. Mask _would_ work here, if it didn't have binary values for the mask when painting it.
