### ISSUE TITLE
Brush gets very pixelated

### ISSUE THREAD

**Issue by adanub** [armory3d/armorpaint#588]
**ArmorPaint version:**
Commit 955aac0cc7afbca39f403cc0e378f465ec800aaa

**OS/device including version:**
Windows 10

**Issue description:**
Left: Brush when camera zoomed in close to model
Right: Brush at roughly the same size, with camera zoomed out
![image](https://user-images.githubusercontent.com/42713438/94238576-efdfa000-ff53-11ea-9a73-cba5c1497b6d.png)
Brush seems blurrier and lower-quality in general compared to Quixel Mixer and Substance Painter. I tried importing the same .obj file into both other programs and they had no issues.

**Steps to reproduce:**
Compare brush quality at different camera zoom levels to the model

**Comment by luboslenco** [comment]
Linking with issue at https://github.com/armory3d/armorpaint/issues/231.
