### ISSUE TITLE
Seamless PBR map export?

### ISSUE THREAD

**Issue by unfa** [armory3d/armorpaint#589]
I wonder if ArmorPaint's node texture creation could be used to generate seamlessly repeating PBR maps for texturing game levels.

As I understand it's strictly meant for texturing models (like Substance Painter), but could it also expand a bit do at least the minimum of what Substance Designer does - procedurally generating and exporting seamless maps for texturing large areas that should use non-repeating textures?

What do you think?

**Comment by luboslenco** [comment]
Yes, not quite there but coming. 🙂 

- There will be a dedicated material workspace for that.
![2a](https://user-images.githubusercontent.com/3685704/94336943-0a168e00-ffe7-11ea-97fd-b85d39bcd90f.PNG)

- Any material can be baked into textures.
![2b](https://user-images.githubusercontent.com/3685704/94336955-20244e80-ffe7-11ea-8bbc-f6167fa91745.PNG)
![2c](https://user-images.githubusercontent.com/3685704/94336959-25819900-ffe7-11ea-9651-2f07485a85dc.PNG)

- Will try to provide several algorithms to make texture seamless, including the texture synthesis.
https://twitter.com/luboslenco/status/1173942414966439938

- Will add some tools to extract the pbr textures from photos.
