### ISSUE TITLE
Blank images when exporting

### ISSUE THREAD

**Issue by adanub** [armory3d/armorpaint#590]
**ArmorPaint version:**
Commit 955aac0

**OS/device including version:**
Windows 10

**Issue description:**
Trying to export select layers results in blank images if it is not currently in the "Mix" blend mode (eg. Color, Multiply, Darken)

**Steps to reproduce:**
See issue description
![image](https://user-images.githubusercontent.com/42713438/94265482-f2ee8680-ff7b-11ea-9790-673ff47a6d2d.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/bc5de4f6122402f0af0110ee5694fa32ddc0c672, thanks for report.
