### ISSUE TITLE
The screen collapses when the window is resized

### ISSUE THREAD

**Issue by shiena** [armory3d/armorpaint#592]
**ArmorPaint version:**

ArmorPaint.org - v0.8 (2020-09-26) - 5620243

**OS/device including version:**

Windows - Direct3D11
NVIDIA GeForce GTX 1080 Ti  

**Issue description:**

The screen collapses when the window is resized.

**Steps to reproduce:**

- When started  
  ![image](https://user-images.githubusercontent.com/1295639/94339565-c5feaa00-0035-11eb-9fa2-340e0197a33d.png)
- When the window size is increased  
  ![image](https://user-images.githubusercontent.com/1295639/94339569-cb5bf480-0035-11eb-817f-5cfcc9542c87.png)
- When the window size is reduced  
  ![image](https://user-images.githubusercontent.com/1295639/94339571-d020a880-0035-11eb-8fbe-723b1db753d1.png)

**Comment by luboslenco** [comment]
Hm all seems well here. Did it work correctly for you before? Is this default ArmorPaint config? Any errors in Visual Studio console?

**Comment by shiena** [comment]
This is the default setting that was started after a clean build. There are no build errors.
When I reverted to the old commit, it was correct up to 61a303d, and the screen collapsed from e035689.

**Comment by luboslenco** [comment]
Great info, will investigate, thanks for letting me know.

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/Kode/Kinc/pull/559.

**Comment by luboslenco** [comment]
It's in!
