### ISSUE TITLE
How to debug ArmorPaint - Haxe

### ISSUE THREAD

**Issue by wojtekpil** [armory3d/armorpaint#593]
Hi, so I was having a difficult time trying to debug ArmorPaint. As far as I understand this application consists of many libraries of which main ones are written in C/C++ (armorcore) and Haxe. So after few minutes I was able to easily debug C/C++ part with simple gdb setup. Second part is more tricky. I work on Linux and I found out that ArmorPaint is a Kha project (I am not a Haxe developer I am not 100% sure). Later I found that Armory is using Kode Studio to integrate debugging functionality so I installed standalone version and tried to load ArmorPaint there. Sadly without much of success. I am not sure how to configure Kode Studio to correctly work with ArmorPaint. What are basics steps to achieve working debugger for Haxe part of ArmorPaint? I want to help fix some bugs  that I encounter but it's hard for not Haxe/Kha developer. A simple step by step instructions even in README would be greatly appreciated.

**Comment by lidorY** [comment]
I'm struggling with the same issue.. If you've found a solution will be glad to hear it!
 
My current workaround is print debug lol..

If you're running the Krom build(armorcore) from MSVC, it reroutes the Krom.js log prints to the output console in the IDE.
You can add a log directly in the generted "...armorpaint/build/Krom/Krom.js" file, or in the Haxe source code files.
Haxe - `haxe.Log.trace(...);`
JS - `haxe_Log.trace(...);`

In both cases you'll need to re-run Krom for the effects to take.
If you're adding lines directly to the Haxe source code, re run `node armorcore/make.js -g direct3d11` (or equivalent) command.

**Comment by luboslenco** [comment]
There is still no way to debug the JS code directly, sorry. The JS stacktraces will get thrown into stdout but no stepping through the code or placing the breakpoints for the JS part yet. Once I finish the [WebGPU backend](https://github.com/Kode/Kinc/tree/master/Backends/Graphics5/WebGPU/Sources/Kore) in Kinc, it will be possible to debug via chrome dev tools and similar, so hopefully it's not too far off.
