### ISSUE TITLE
Its having some issue i cant understand what to do please reply

### ISSUE THREAD

**Issue by SHASWATSINGH3101** [armory3d/armorpaint#596]
**ArmorPaint version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

![Screenshot 2020-09-28 201646](https://user-images.githubusercontent.com/70532135/94448067-1efe4780-01c8-11eb-86fd-869801badb22.png)
![Screenshot 2020-09-28 201646](https://user-images.githubusercontent.com/70532135/94448088-26255580-01c8-11eb-82d2-ad1526851c0b.png)
![Screenshot 2020-09-28 201646](https://user-images.githubusercontent.com/70532135/94448185-3d644300-01c8-11eb-9f17-2a63c0b62491.png)

**Comment by luboslenco** [comment]
Apologizes but filling in the following fields is really needed, otherwise I am unable to reproduce the issue and give advice.

```
ArmorPaint version:

OS/device including version:

Issue description:

Steps to reproduce:
```

Without knowing any details, make sure the mesh is properly uv unwrapped.
