### ISSUE TITLE
Brush size comes error when I press win+space

### ISSUE THREAD

**Issue by edmondwu1022** [armory3d/armorpaint#599]
Hi there,

I used the latest version of ArmorPaint which is (0.8dev) and update on 22/09/2020 , and it's running on Windows os.

I found out, if I press the Win + space , the brush size will runs to negative value and it's running infinity.

I uploaded the video about this issue, hope it helps.
[https://youtu.be/UxmIA_jbRkw](url)

**Comment by lidorY** [comment]
The video seems to be private and inaccessible.
Should this keys comibnation make the brush size smaller? If so, then the desired behavior is that it should decrease by some amount and stop after the keys are released?
It happens to me too.  Tho never gets to a negative value, stops around 0.01.

**Comment by edmondwu1022** [comment]
> The video seems to be private and inaccessible.

oops, sorry about that, I changed the status and it should work now, please give a try.

**Comment by lidorY** [comment]
Seems like it got fixed in commit: 4787503526559308d092c537a4237803234bb3e3

The error was that Iron was interpreting Win key as '[',  which changes the brush size.
This issue can be closed :)

**Comment by luboslenco** [comment]
Yup all should be well now. 🙂
