### ISSUE TITLE
UV Unwrap cracks while painting and with PBR texture export

### ISSUE THREAD

**Issue by benjyu** [armory3d/armorpaint#6]
<img width="492" alt="screen shot 2018-03-06 at 8 36 12 pm" src="https://user-images.githubusercontent.com/3675917/37068718-0fc8428e-217e-11e8-85fa-ad92f5d1e71f.png">

There are visible cracks at where uv unwrap separates the mesh surface when painting in armor paint, and it becomes more visible in the exported pbr materials when uploaded to sketchfab. See the image above taken from sketchfab. I've only tested this on Windows.

**Comment by SojanJanso** [comment]
Same here on Linux (Ubuntu gnome 17.10), although I found that turning the biased setting up to max helps to reduce these lines. It does not remove them completely in all places, and they can be hard to spot. I'm guessing some kind of spill feature would be necessary to fix these?

**Comment by luboslenco** [comment]
Should be alleviated now by default. If cracks are still visible turning `Tools - Draw - Bias` above 1.0 will fight that.
