### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by PasinduAnjana** [armory3d/armorpaint#60]
I downloaded the latest version of armory and armorpaint from github.
When I open the .blend file and pressing "play" it reports an error. 
![screenshot 1](https://user-images.githubusercontent.com/47142024/51907406-b6f0d000-23ec-11e9-8dcb-f4b7fc09a3d8.png)

**Comment by luboslenco** [comment]
Hello,

Is your Armory engine copy working fine in other scenes? Are you able to run other projects?

**Comment by PasinduAnjana** [comment]
Yes, they are working.
![screenshot 2](https://user-images.githubusercontent.com/47142024/51913597-dee82f80-23fc-11e9-917b-476a9277beb1.png)

**Comment by luboslenco** [comment]
Maybe something wrong with the armorpaint clone then? Did you clone the latest one using
`git clone https://github.com/armory3d/armorpaint`? Or perhaps write permission issues?

**Comment by PasinduAnjana** [comment]
I am using latest one. When I press run it tells "compiling" and then tells "Build failed.Check console"

**Comment by luboslenco** [comment]
Hm so is that popup error gone? Can you paste the console output here to see the error message? On Windows you can press `Window - Toggle System Console` in Blender to bring it up.

**Comment by PasinduAnjana** [comment]
Read prefs: C:\Users\Pasindu\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Users\Pasindu\Desktop\Armory\2.80\python
Rock generator settings file found:
C:\Users\Pasindu\Desktop\Armory\2.80\scripts\addons_contrib\add_mesh_rocks\add_mesh_rocks.xml
Rock Generator: Numpy found.
Armory: Proxy objects synchronized
WARN (bpy.rna): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\python\intern\bpy_rna.c:1419 pyrna_enum_to_py: current value '0' matches no enum in 'Area', '(null)', 'type'
WARN (bpy.rna): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\python\intern\bpy_rna.c:1419 pyrna_enum_to_py: current value '0' matches no enum in 'Area', '(null)', 'type'
WARN (bpy.rna): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\python\intern\bpy_rna.c:1419 pyrna_enum_to_py: current value '0' matches no enum in 'Area', '(null)', 'type'
Read blend: C:\Users\Pasindu\Desktop\New folder\armorpaint\armorpaint.blend

Armory v0.6 ($Id: ebccb44905d7131d996bc0d21e7836e6d91df402 $)
OS: win, Target: krom, GAPI: opengl, Blender: 2.80 (sub 41)
Exporting Scene
Scene exported in 0.046164751052856445
Exported modules: ['ui', 'format']
Shader flags: ['_Irr', '_EnvTex', '_Rad', '_EnvStr', '_Deferred', '_ShadowMap', '_Spot', '_SinglePoint', '_Brdf', '_SMAA', '_Veloc', '_SSAO', '_gbuffer2', '_SMSizeUniform', '_CGrainStatic']
Running:  ['C:/Users/Pasindu/Desktop/Armory/armsdk//nodejs/node.exe', 'C:/Users/Pasindu/Desktop/Armory/armsdk//Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--parallelAssetConversion', '4', '--to', 'build_armorpaint/debug']
Using project from C:\Users\Pasindu\Desktop\New folder\armorpaint
Using Kha from C:\Users\Pasindu\Desktop\Armory\armsdk\Kha
Creating Kha project.
Warning: No haxelib.json and no Sources directory found in library paint.
Exporting asset 1 of 17 (Scene.arm).
Exporting asset 2 of 17 (cay_irradiance.arm).
Exporting asset 3 of 17 (cay_radiance_1.hdr).
Exporting asset 4 of 17 (cay_radiance_2.hdr).
Exporting asset 5 of 17 (cay_radiance_0.hdr).
Exporting asset 6 of 17 (cay_radiance.hdr).
Exporting asset 7 of 17 (cay_radiance_4.hdr).
Exporting asset 8 of 17 (cay_radiance_3.hdr).
Exporting asset 9 of 17 (cay_radiance_6.hdr).
Exporting asset 10 of 17 (cay_radiance_5.hdr).
Exporting asset 11 of 17 (cay_radiance_7.hdr).
Exporting asset 12 of 17 (cay_radiance_8.hdr).
Exporting asset 13 of 17 (cay_radiance_9.hdr).
Exporting asset 14 of 17 (mesh_Cube.arm).
Exporting asset 15 of 17 (mesh_Plane.arm).
Exporting asset 16 of 17 (mesh_Cylinder.arm).
Exporting asset 17 of 17 (mesh_Sphere.arm).
Exporting asset 1 of 2 (Material_data.arm).
Exporting asset 2 of 2 (shader_datas.arm).
Exporting asset 1 of 1 (cay.hdr).
Exporting asset 1 of 1 (brush_bake.png).
Exporting asset 1 of 1 (brush_colorid.png).
Exporting asset 1 of 1 (brush_draw.png).
Exporting asset 1 of 1 (brush_erase.png).
Exporting asset 1 of 1 (brush_fill.png).
Exporting asset 1 of 1 (cmft-linux64).
Exporting asset 1 of 1 (cmft-osx).
Exporting asset 1 of 1 (cmft.exe).
Exporting asset 1 of 1 (license_cmft.md).
Exporting asset 1 of 1 (color_wheel.png).
Exporting asset 1 of 1 (config.arm).
Exporting asset 1 of 1 (cursor.png).
Exporting asset 1 of 1 (default_brush.json).
Exporting asset 1 of 1 (default_logic.json).
Exporting asset 1 of 1 (default_material.json).
Exporting asset 1 of 1 (drag.png).
Exporting asset 1 of 1 (empty.jpg).
Exporting asset 1 of 1 (license.md).
Exporting asset 1 of 1 (logic_nodes.json).
Exporting asset 1 of 1 (noise64.png).
Exporting asset 1 of 1 (plugin_hello.js).
Exporting asset 1 of 1 (plugin_rotate.js).
Exporting asset 1 of 1 (readme.txt).
Exporting asset 1 of 1 (theme.arm).
Exporting asset 1 of 1 (theme_light.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise256.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (font_default.ttf).
Compiling shader 1 of 30 (Material_mesh.frag.glsl).
Compiling shader 2 of 30 (Material_mesh.vert.glsl).
Compiling shader 3 of 30 (Material_shadowmap.frag.glsl).
Compiling shader 4 of 30 (Material_shadowmap.vert.glsl).
Compiling shader 5 of 30 (Material_voxel.frag.glsl).
Compiling shader 6 of 30 (Material_voxel.geom.glsl).
Compiling shader 7 of 30 (Material_voxel.vert.glsl).
Compiling shader 8 of 30 (blur_adaptive_pass.frag.glsl).
Compiling shader 9 of 30 (blur_edge_pass.frag.glsl).
Compiling shader 10 of 30 (compositor_pass.frag.glsl).
Compiling shader 11 of 30 (compositor_pass.vert.glsl).
Compiling shader 12 of 30 (copy_mrt3_pass.frag.glsl).
Compiling shader 13 of 30 (copy_mrt4_pass.frag.glsl).
Compiling shader 14 of 30 (deferred_light.frag.glsl).
Compiling shader 15 of 30 (max_luminance_pass.frag.glsl).
Compiling shader 16 of 30 (pass.vert.glsl).
Compiling shader 17 of 30 (pass_copy.frag.glsl).
Compiling shader 18 of 30 (pass_viewray.vert.glsl).
Compiling shader 19 of 30 (pass_viewray2.vert.glsl).
Compiling shader 20 of 30 (smaa_blend_weight.frag.glsl).
Compiling shader 21 of 30 (smaa_blend_weight.vert.glsl).
Compiling shader 22 of 30 (smaa_edge_detect.frag.glsl).
Compiling shader 23 of 30 (smaa_edge_detect.vert.glsl).
Compiling shader 24 of 30 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 25 of 30 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 26 of 30 (ssao_pass.frag.glsl).
Compiling shader 27 of 30 (ssr_pass.frag.glsl).
Compiling shader 28 of 30 (taa_pass.frag.glsl).
Compiling shader 29 of 30 (world_pass.vert.glsl).
Compiling shader 30 of 30 (world_pass.frag.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
C:\Users\Pasindu\Desktop\New folder\armorpaint\Sources/arm/UITrait.hx:2629: characters 39-55 : Uncaught exception process_run
C:\Users\Pasindu\Desktop\New folder\armorpaint\Sources/arm/Macro.hx:12: characters 14-83 : Called from here
For function argument 'text'
C:\Users\Pasindu\Desktop\New folder\armorpaint\Sources/arm/UITrait.hx:19: lines 19-3681 : Defined in this class

Haxe compiler error.
Finished in 19.555054903030396
Build failed, check console

**Comment by PasinduAnjana** [comment]
Please, tell me how to do that step by step.

**Comment by luboslenco** [comment]
If you need a tutorial on git this may help:
[git - the simple guide](http://rogerdudler.github.io/git-guide/)

**Comment by PasinduAnjana** [comment]
I use that code in git and it downloaded files. What I have to do now?

**Comment by DiegoBM** [comment]
You seem to have an extra slash in your sdk path. Try using the bundled SDK. I have just cloned armorpaint right now and it works perfectly fine using the bundled sdk that comes with Armory 0.6 beta.

**Comment by luboslenco** [comment]
With files cloned using git, do the same thing you did before - open the .blend file, hit play and it will work. 🙂 Please also keep in mind git version is in development and you may experience various quirks there.
