### ISSUE TITLE
Build failure on Windows.

### ISSUE THREAD

**Issue by sharaths21312** [armory3d/armorpaint#602]
**ArmorPaint version:** None

**OS/device including version:**
Windows 10 2004 build 19041.508

**Issue description:**
Failes to build, cites a missing file, which turns out to not exist.

**Steps to reproduce:**
Attempt building with the method given in README.md
![image](https://user-images.githubusercontent.com/62636355/94989033-3b66ff00-058f-11eb-80e6-f7cb77a686a8.png)
![image](https://user-images.githubusercontent.com/62636355/94989105-eaa3d600-058f-11eb-89f3-5edf91a5b740.png)

**Comment by luboslenco** [comment]
Please try cloning again and make sure it finished cloning into your machine without error (maybe a connection error caused interrupt).

You can see the submodule you are missing linked here:
https://github.com/armory3d/Kinc/tree/master/Tools

Looking at the automated build action, ArmorPaint should compile properly on Windows: https://github.com/armory3d/armorpaint/actions?query=workflow%3A%22Windows+%28Direct3D+11%29%22.
