### ISSUE TITLE
As of build eec87c9, Armorpaint doesn't export height texture. Instead it exports a black metal texture.

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#603]

**Comment by luboslenco** [comment]
Hello, to export the height texture add a height slot to the export preset:
![1a](https://user-images.githubusercontent.com/3685704/95009140-f343ed00-061f-11eb-9e59-57810d692cad.PNG)

https://github.com/armory3d/armorpaint_docs#export-textures
