### ISSUE TITLE
Vignette setting is not taken into account

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#605]
if i drag and drop an HDRI in the viewport and then set it off from the viewport menu, vignette setting is not taken into account -- armorpaint version 0.8 1d81667

**Comment by luboslenco** [comment]
Hello, which OS are you on? Are you able to include a screenshot to better explain the problem? Do you mean that vignette effect is no longer visible?

**Comment by infinder** [comment]
![before](https://user-images.githubusercontent.com/72331575/95227301-a0785a00-0806-11eb-82bc-1d30ddbffea2.jpg)
![after](https://user-images.githubusercontent.com/72331575/95227319-a66e3b00-0806-11eb-91b5-92cb454b1740.jpg)

**Comment by luboslenco** [comment]
Ah, got confused with specific mention of vignette. Pushed a fix at https://github.com/armory3d/armorpaint/commit/95ff36c589a99103bf424545c2cc4edbf1d15c62, thanks for report.
