### ISSUE TITLE
Zoom by pen button do not work in 2d view and node editor

### ISSUE THREAD

**Issue by xzay3d** [armory3d/armorpaint#606]
*ArmorPaint 0.8-dc0c2d4, Windows*

**Issue description:**
I changed keymap to blender like navigation. Zoom - Ctrl+Middle. I use pen. It work in 3d view. But no working in 2d and node editor. 

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/2bcf933aa8bd9e414710735687a036a372e86d41, thanks for report.
