### ISSUE TITLE
menu items that exceed screens down limit can't be selected

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#609]
It looks like there is no way to access menu items that exceed screens down limit.
win10x64 intel hd 620 graphics
![b1](https://user-images.githubusercontent.com/72331575/95951369-f9478400-0dfe-11eb-82e4-c92631dec341.jpg)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/6cbeccf6557e2bb7fe7bde57738656d2a2502049.
