### ISSUE TITLE
Merge Down doesn't respect overlay blending mode

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#611]
Merge down doesn't respect overlay blending mode. Merge outcomes as if the two merged layers were in mix mode.
ArmorPaint 0.8-544a12f, Windows 10 intel HD 620

![before_merge](https://user-images.githubusercontent.com/72331575/95978943-8f8da100-0e23-11eb-89b8-2853312dcd93.jpg)

![after-merge](https://user-images.githubusercontent.com/72331575/95979055-b8ae3180-0e23-11eb-9369-3c2b4316ebf7.jpg)

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/55509c6e025fb6e20e786bcdb117ed1710fdde53, thanks for report!
