### ISSUE TITLE
Environment texture import problem

### ISSUE THREAD

**Issue by Eisenblute** [armory3d/armorpaint#612]
**ArmorPaint version:** v.0.8 (2020-10-09) - 4169f3a

**OS/device including version:** Windows 7 x64, GeForce GTX 750

**Issue description:**

ArmorPaint freezes when you try to import .hdr file over main menu

**Steps to reproduce:**

- In the main menu go to Viewport -> Import Envmap...
- Choose any .hdr file and click Open - ArmorPaint will freeze.

NOTE: If you drag and drop .hdr file right in the viewport, it's imported as it should. Any file you import this way is shown in the Texture panel, but if you try to change envmap and drag it from Texture panel to viewport - nothing will happen.

**Comment by luboslenco** [comment]
Nice, fixed now at https://github.com/armory3d/armorpaint/commit/f208f1ec6c96da7281dd2aaf0d018e7dd9d1b56c.
