### ISSUE TITLE
Draging the mouse in the viewport affects items in 2d view or node editor

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#613]
Holding right or middle mousse button pressed in the vieport and draging to the right, it translates items in 2d view or node editor if they are open and vice versa.

ArmorPaint 0.8dev, Windows10 X64

![armorpaint-bug](https://user-images.githubusercontent.com/72331575/96143681-fe462980-0f0b-11eb-9cf5-257d777da2fe.gif)

**Comment by luboslenco** [comment]
Fix incoming via https://github.com/armory3d/armorpaint/issues/326.
