### ISSUE TITLE
Default envmap is blured.

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#614]
Default envmap is blured despite the fact that menu>viewport>blur Envmap is unchecked..
Armorpaint 0.8dev

![blured-env](https://user-images.githubusercontent.com/72331575/96173952-475ca480-0f31-11eb-90da-ac4a4cbc1c95.jpg)

**Comment by luboslenco** [comment]
Hello, it's on purpose as of now to favor program size and startup speed. Will eventually add an option to replace the default envmap in the config. Right now you can drag and drop any `.hdr` map into the viewport to replace it and it will get saved in your project file as well.
