### ISSUE TITLE
The possibility of selecting the part of mesh for painting as in the blender mask selecting

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#617]
The possibility of selecting the part of mesh for painting as in the blender mask selecting the selection of mesh elements, sometimes it is so that the mesh is connected and not have separated elements

**Comment by luboslenco** [comment]
Hi, please check the "Set Object Mask" video from the [how to](https://armorpaint.org/howto) section to select a specific mesh to paint on:
https://www.youtube.com/watch?v=9LJY2y6JyKg&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=19
