### ISSUE TITLE
Fix config save when running from read-only location on Linux

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#619]
Saved default configuration options, at this moment i must always change configuration options and plugins when i run ArmourPaint. Cool idea is option when i can save config as default.

**Comment by AlexKiryanov** [comment]
good evening! The program automatically saves the settings when you make changes. And the next time you start the program, they remain the same as you did the last time. Well, at least everything works for me)

**Comment by SaraDark** [comment]
Generally yes, but if application is run by user that do not have access to write same directory as app runs, it will not save.
Application should try save in /home/###/.config/AppArmor directory that would allow current user save setting even when application is run inside folder that the user dont have persmission to write.

ArmorPaint.org - v0.8 (2020-10-06) - 67538a9 - Linux -

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/070ee1c088d14d736e8331c22c3394b3b56c95dd.

**Comment by AlexKiryanov** [comment]
Good evening, Lubos! thank you very much)

чт, 11 февр. 2021 г., 20:37 Lubos Lenco <notifications@github.com>:
