### ISSUE TITLE
Allow recreating UV Map (Issue with FBX)

### ISSUE THREAD

**Issue by lunarcloud** [armory3d/armorpaint#62]
[Demon.zip](https://github.com/armory3d/armorpaint/files/2820093/Demon.zip)

Trying some FBX files from fusion 360, painting is overlapped (odd UV Map).

If I manage to navigate blender enough to accidentally activate the "UV Mapping -> Smart UV Project" and re-export it, then armorpaint can work with the FBX correctly.

**Comment by luboslenco** [comment]
Added `Xatlas` plugin in latest dev builds - makes it possible to unwrap directly in armorpaint.

![1a](https://user-images.githubusercontent.com/3685704/69178702-63ca4400-0b0a-11ea-87de-2f0c9c354da0.PNG)

**Comment by Granada1** [comment]
Unwrapped my model ok but exported model with no uv map

**Comment by luboslenco** [comment]
Thanks for testing! Pushed a fix, export will be resolved in next build.

**Comment by Granada1** [comment]
Great thanks
