### ISSUE TITLE
Normal Map and Height Map in material do crash mesh

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#620]
Normal Map and Height Map in material do crash mesh.

![1](https://user-images.githubusercontent.com/69405892/96282552-2d779c00-0fdb-11eb-86da-5b5ada58211a.png)
![2](https://user-images.githubusercontent.com/69405892/96282556-2ea8c900-0fdb-11eb-9cf1-fdb10ef853d3.png)
![3](https://user-images.githubusercontent.com/69405892/96282559-2ea8c900-0fdb-11eb-8389-1c503f001442.png)

**Comment by AlexKiryanov** [comment]
good evening eot nfp! Set the displacement Strenght to 0 in the settings.
![prew](https://user-images.githubusercontent.com/65244629/96295332-61ac8600-0ff6-11eb-9321-04da6f9e4ba4.jpg)

**Comment by SaraDark** [comment]
thanks!

there was recent commit:

https://github.com/armory3d/armorpaint/commit/2c62614831c4e3a141a4e2324ba984ea0792a55e

is this intended that broken feature should be enabled by default?

**Comment by luboslenco** [comment]
@SaraDark can you include your ArmorPaint version? The commit does what @AlexKiryanov suggests by default.

**Comment by SaraDark** [comment]
@luboslenco 
earlier comment was mistake and was edited, its opposite, it was fixed to use default, we have 10 days old version here (ArmorPaint.org - v0.8 (2020-10-06) - 67538a9).

thanks for a fix.

**Comment by luboslenco** [comment]
Happy to hear!
