### ISSUE TITLE
Material Fill - TexCoord type / UV Scale

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#621]
1) New project -> simple cube
2) Drag n Drop material into model
3) it fill model with material UV Based

![image](https://user-images.githubusercontent.com/69405892/96297449-28254c00-0ff1-11eb-8a38-686a875dc1bf.png)

4) Change UV Scale from 1 to 0.2  (same with any other than 0.2 but different than 1)
!! See this looking upper face of Cube only

![image](https://user-images.githubusercontent.com/69405892/96297514-3f643980-0ff1-11eb-9b49-0947c2a2fc0c.png)

**Comment by AlexKiryanov** [comment]
![prew](https://user-images.githubusercontent.com/65244629/96297980-61ae8500-0ffa-11eb-80ad-62cfafcf7999.jpg)
go to the material editor and use the UV and Mapping node

**Comment by luboslenco** [comment]
It's a bug, the UV slider should work like expected.

**Comment by AlexKiryanov** [comment]
yes, I just checked, the slider really does not work.

**Comment by luboslenco** [comment]
Fixed now at https://github.com/armory3d/armorpaint/commit/be4da16ecc270b2accfa8af7d3685e588ee34e98, thanks for report.

**Comment by SaraDark** [comment]
Cool thx :) When compiled linux version ArmorPaint_08dev_linux64.zip is are availab?

**Comment by luboslenco** [comment]
Available now. 🙂

**Comment by SaraDark** [comment]
thx :) :+1:
