### ISSUE TITLE
Crash on Mode -> Normal

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#623]
**ArmorPaint version:**
6cebb3c

**OS/device including version:**
Win 10 2004 x64

**Issue description:**
Armorpaint crashes if I paint a model partially and select Mode -> Normal

**Steps to reproduce:**
1. Load a model with multiple Objects (e.g. split by material)
2. Create a material with a normal. Can be a pbr material but a RGB Node as normal source is sufficient
3. Change Layer 1 from Shared to an object.
4. Fill the part of the mesh.
5. Click Mode -> Normals and get an armorpaint crash. 
See my screenshot for an example situation just before performing step 5.

I believe Armorpaint has a problem with partially missing normals because if a load mesh and do not paint at all I can savely switch. the same holds for completely painted models.

![crash on normal](https://user-images.githubusercontent.com/28649121/96495248-e2ae8c00-1247-11eb-9352-bb7693514cd2.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/7b6e265ede258bfd63b60014d18b4bdba0e51ae1, many thanks for report!
