### ISSUE TITLE
Crash on Mode -> Object id

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#626]
**ArmorPaint version:**
be4da16

**Issue description:**
Armorpaint crashes if Mode is Object id and a layer is changed from Shared to another object. 

**Steps to reproduce:**
The crash is vry similar to the one in #623.
1. Load Mesh and split by material (or something else)
2. Select Mode -> Object id
3. Change the object to paint in a Layer
4. Armorpaint crashes.

**Comment by luboslenco** [comment]
Nice! Should no longer crash now. https://github.com/armory3d/armorpaint/commit/d5bf6c9098ba5513276ccfa80ebd18b714642dd3
