### ISSUE TITLE
Camera rotate mode destroys mesh

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#627]
**ArmorPaint version:**
be4da16

**Issue description:**
The camera rotate mode does not work if a layer is not on shared but on a subobject.

**Steps to reproduce:**
1. Load mesh with multiple objects
2. Select an object different from shared in a layer
3. Select rotate mode for camera.
4. Do rotate using the mouse
5. Get funny results
![armorpaint](https://user-images.githubusercontent.com/28649121/96616149-82c8eb80-1302-11eb-89a3-399d15a2dc73.jpg)

**Comment by luboslenco** [comment]
Fixed via https://github.com/armory3d/armorpaint/commit/0f550c4b7c4dbb04029582ba4d08fe4f605d2cc7, many thanks for report!
