### ISSUE TITLE
Random crash on import envmap

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#628]
**ArmorPaint version:**
be4da16

**OS/device including version:**
Windows - Direct3D11, IA GeForce GT 710  

**Issue description:**
Armorpaint crashes sometimes while loading an envmap

**Steps to reproduce:**
Unfortunately I do not have a deterministic way to reproduce this issue. 
1. Open Armorpaint
2. Load envmap
Sometimes (In 3 out of 4 cases) I get a crash. If it loads the env map properly then everything is fine and all related features work. In case loading an envmap worked it almost certainly crashes on loading another one (or the same one again).

To be honest this is very strange and i believe this issue is somewhat new as I would remember if this "feature" occured in the past. I have no idea about the internal but as it is non deterministic it looks like a multithreading or timing issue or something like that.
If you need further information or a crash dump (I don't know if there are helpful ones) please feel free to ask me.

**Comment by luboslenco** [comment]
How do you load the envmap? Drag and drop, or using the file browser? Is there a difference?

**Comment by MathemanFlo** [comment]
Wow, thank you for the quick reply. To be honest I didn't even know I can do it via drag and drop...
Now I tried it both ways 1. View -> Import Envmap and 2. via drag and drop and both times I get crashes most of the time and sometimes it works and I can not really see a difference.

**Comment by luboslenco** [comment]
Any luck with the latest builds?

**Comment by MathemanFlo** [comment]
First of all thank you so much for all the other fixes, all of them work perfectly. I really appreciate your hard and excellent work. Unfortunately commit "More envmap import fixes" does not fix the problem completely. I still face crashes in some cases if I try to load the envmap via menu but the probability decreased enourmously to only roughly 10%. Loading via drag and drop didn't produce any crash so far and I tried it about 30 times. I do not know whether this helps you but I can share the crash dump with you.
[kinc.dmp.zip](https://github.com/armory3d/armorpaint/files/5418172/kinc.dmp.zip)
If you have further ideas to test please feel free to ask.

**Comment by MathemanFlo** [comment]
I think I found the problem. Loading an envmap sometimes crashes the NVIDIA display driver. So I guess it is probably a bug in the driver and not a bug in ArmorPaint, especially if others are not able to reproduce this on other hardware. Thank you for your patience.

**Comment by luboslenco** [comment]
Thanks for info - will keep an eye on it!
