### ISSUE TITLE
Straight line drawing problem

### ISSUE THREAD

**Issue by Eisenblute** [armory3d/armorpaint#629]
**ArmorPaint version:** v0.8 (2020-10-20) - 6cebb3c

**OS/device including version:** Windows 7 x64, GeForce 750 GTX

**Issue description:**

You can draw correct straight line only if you drag mouse very slowly.
If you move a little fast, line's edges is broken.
If you click mouse button and then hold SHIFT (to project line) and start clicking somewhere else, line will be project not precisely.

**Steps to reproduce:** start drawing with holding SHIFT. See screenshot below.

![Снимок](https://user-images.githubusercontent.com/61283606/96724328-6091a500-13b8-11eb-96d6-4d74e180437b.PNG)

**Comment by luboslenco** [comment]
Thanks for report, investigating a fix together with https://github.com/armory3d/armorpaint/issues/219.
