### ISSUE TITLE
Armorpaint crashes when opening/saving/importing a file

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorpaint#63]
When I click on any button inside Armorpaint that opens a file or does something similar like importing (every io-like functionality), it crashes with an "Armorpaint has stopped working" windows error message.

Drag & Drop on the other side works perfectly fine.

**Armorpaint 0.5** on **Windows 8.1 64bit**

**Comment by MoritzBrueckner** [comment]
@luboslenco Any news on this?

**Comment by luboslenco** [comment]
My only guess so far is permission issues (trouble writing a directory listing file internally).:( But will finally get a hold of Windows 8.1 machine next week, hopefully I will be able to reproduce and fix!

**Comment by MoritzBrueckner** [comment]
If you want me to test something on my machine don't hesitate to ask :)

**Comment by luboslenco** [comment]
Pushed some changes, any luck using the new dev build? :)

**Comment by MoritzBrueckner** [comment]
Thank you! Unfortunately I can't build the git version because of https://github.com/armory3d/armory/issues/1144, can you make a build for me?

**Comment by luboslenco** [comment]
Sorry I should have clarified - new build is now available on gumroad and itch. (please drop me an email if download key is needed.)

**Comment by MoritzBrueckner** [comment]
Thank you very much, it works now!

A very little improvement would be to not show the cmd window that gets opened for a very short time during import/export operations like shown in the following gif. I'm not sure if this is possible and the bug is fixed so I close this issue :)

![github_armory_cmd_at_open](https://user-images.githubusercontent.com/17685000/53592042-bab37600-3b95-11e9-8bc3-5a438fd767d8.gif)

**Comment by luboslenco** [comment]
Yay, very happy to hear that!

The cmd window does not appear to pop up on Windows 10 for me, maybe Windows 8.1 is handling something differently there - will check it out, thanks a lot for mentioning that.

**Comment by MoritzBrueckner** [comment]
It actually opens every time you access a folder so yes this would be great :)
