### ISSUE TITLE
Preferences -> Usage -> Paint Bleed change not remember after restart (eg. changed 1 to 5)

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#630]
Preferences -> Usage -> Paint Bleed change not remember after restart (eg. changed 1 to 5)
ArmorPaint.org - v0.8 (2020-10-21) - 3e93019

**Comment by luboslenco** [comment]
Will finally rework how the bleed works soon, linking with issue at https://github.com/armory3d/armorpaint/issues/157.
