### ISSUE TITLE
Fix loading Greek language characters when using (el) localization

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#634]
Many problems with the choice of the Greek language in the preferences (el). The picture shows what exactly I see first, when I choose Greek.

![start](https://user-images.githubusercontent.com/72331575/96899183-47145a00-1499-11eb-81c7-dd10002f633f.jpg)

In order for the Greek words to start appearing normally, I have to select the text tool and enter all the letters of the Greek keyboard in the text field. Even so, the problems do not end there. The picture shows the situation I described.

![τεχτ2](https://user-images.githubusercontent.com/72331575/96899357-7c20ac80-1499-11eb-82e8-82572cb44779.jpg)

![τεχτ3](https://user-images.githubusercontent.com/72331575/96899496-a70b0080-1499-11eb-810c-979cbad360a3.jpg)

There is not an appropriate enlargement of the menu everywhere to fit all the words in the options. This is evident in the menu options where I have to drag the mouse to set the value. The text tool itself and the text input field also have many problems that I will describe to the extent that I understand exactly what is happening.

**Comment by luboslenco** [comment]
The characters will need to be loaded at https://github.com/armory3d/armorpaint/blob/master/Sources/arm/Translator.hx, I will take care of it in coming days.

**Comment by infinder** [comment]
Then we will have to wait and see if any problems will continue to exist afterwards. The truth is that other languages do not seem to have a persistent problem right now. Thank you very much for your actions and help.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/7d3140710533d6754e2b3099ff8349c2d7e90600. There may still be overlap issues - will take care of it at https://github.com/armory3d/armorpaint/issues/535. Thanks again for the translation!

![el](https://user-images.githubusercontent.com/3685704/97019811-0f68e900-1551-11eb-90cd-64a4248c47b0.PNG)
