### ISSUE TITLE
Shared UVs and multiple objects

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#636]
My setup is as follows:
1. I created two identical objects with shared UVs in Blender.
2. I imported the obj file in ArmorPaint and split by objects.
3. Now I can paint both objects by creating two layers and assigning them to the two objects. Even though they share UVs (and paint the same region on the texture) they look differently if assign different materials. 

I don't know whether this is a bug or not but I think it is a - in my humble opinion - counter intuitive design decsion because by exporting the textures and loading the mesh with textures in some game engine or even in armorpaint again the two objects will look identical (namely they will have the material of the upper layer).

This is a big issue for me as I typically have multiple objects and some of them have shared UVs. It becomes especially weird if the objects and the shared UV maps do not corrspond directly, i.e. if two objects only share parts of their UVs. Is this a bug and if not how should I change my workflow to achive my goals?
Thank you very much
Flo

**Comment by luboslenco** [comment]
Added new `Atlases` tab to the texture export popup, which can be used to tell ArmorPaint which objects do share UV maps. Very basic for now but should work.

**Comment by MathemanFlo** [comment]
Wow you are simply amazing. I will try it immediately and give feedback.
