### ISSUE TITLE
Moving in Render tab destroys mesh

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#637]
**ArmorPaint version:**
4277db8

**Issue description:**
I can destroy meshes similar to #627 in the Render tab.

**Steps to reproduce:**
1. Load mesh with multiple objects/split by material
2. Create layers and assign them to different objects
3. Select one Layer
2. Go to the render tab
3. Move by dragging the red/green/blue arrows and move an objects partially
4. Select a different layer on the right side and drag again. The moving object did not change.
5. Go to the Paint tab, select a different layer
6. Go back to the render tab
7. Drag again and now the other object is moving

Expected behavior: Always move the whole object no matter which layer is selected.

**Comment by luboslenco** [comment]
Keeping the render workspace 'freestyle' for now, basically you can will be able to manipulate the scene objects however you like..but it's still a little down the road and clunky for now.

![t](https://user-images.githubusercontent.com/3685704/96978192-61dce200-151e-11eb-9281-bca39f65ba90.PNG)

**Comment by MathemanFlo** [comment]
Aaaaah, thank you very much for the information. 
Changing the position using the view in the outline tab seems to be intuitive but changing the position by selecting layers is somewhat strange but understandable. 

But I have one suggestion: There could be some button to reset all changes and to restore the mesh.
By the way I found a new bug:
1. Load mesh with multiple objects
2. Go to Render tab, click on Outliner.
3. Reposition some part.
4. Now as I want to reset all my shifts I reload the mesh

then I get this result
![armorpaint](https://user-images.githubusercontent.com/28649121/96983530-71f5c100-1520-11eb-84f5-95b4403541e3.jpg)
and even worse a part of the mesh gets scaled and place on some strange position
![armorpaint2](https://user-images.githubusercontent.com/28649121/96983640-7fab4680-1520-11eb-9ec0-6d746b5a4d6d.jpg)

Now by retunring back to paint tab all Layers disappear
![armorpaint3](https://user-images.githubusercontent.com/28649121/96984108-a9646d80-1520-11eb-9688-bfbc0bcb4e4a.jpg)
Now by clicking reimport mesh again ArmorPaint crashes

In order to simplify the steps to reproduce I append the mesh
[Tower2.zip](https://github.com/armory3d/armorpaint/files/5428522/Tower2.zip)
