### ISSUE TITLE
Crash on some cyclic shader graphs

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#638]
**ArmorPaint version:**
a7613d7

**Issue description:**
Some cyclic shader graphs do crash ArmorPaint others do not

**Steps to reproduce:**
The crash happened in a non so obvious situation but I tried to boil it down to a minimal example:
This one works perfectly:
![armorpaint](https://user-images.githubusercontent.com/28649121/96966786-c132f600-150e-11eb-8caf-a81588956885.jpg)

The very same setup for blur crashes ArmorPaint if one closes the loop
![armorpaint2](https://user-images.githubusercontent.com/28649121/96966851-dad43d80-150e-11eb-9e79-d203d5335d73.jpg)

Funnily this does not happen for all Nodes. I could reproduce it for:
- Warp

It works for
- BrightContrast
- Gamma
- Invert
- Mix RGB together with a working Color node
- Bump
- Mapping
- Normal
- Vector Curves
- Sep/Combine HSV/XYZ
- (Vector) Math

**Comment by luboslenco** [comment]
👍 Fix at https://github.com/armory3d/armorpaint/commit/078088a6df659988cc42a6329e7108e58952d5d9.
