### ISSUE TITLE
Wrong texture if Color Ramp is involved

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#639]
**ArmorPaint version:**
a7613d7

**Issue description:**
I get strange artifacts if I add a Color Ramp
![armorpaint](https://user-images.githubusercontent.com/28649121/96971424-5cc76500-1515-11eb-84f6-972d5699c9d3.jpg)

**Steps to reproduce:**
Again I gad a more complex situation but I could boil it down to:
1. Build a simple RGB -> Blur -> Mat. Output shader graph
2. Fill your object 
3. Add a useless color ramp
4. Fill it again and get strange results.

**Comment by luboslenco** [comment]
👍 Should be resolved via https://github.com/armory3d/armorpaint/commit/faefb60b8795cebdd5ffe2ac09fccae42496bfe9.
