### ISSUE TITLE
Strange material behavior on switch to Material, Bake and Render tabs

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#640]
**ArmorPaint version:**
a7613d7

**Issue description:**
There are several related issues concerning materials and the Paint, Material, Bake and Render tab.

**Steps to reproduce:**
Material tab:
1. Create two materials
2. Load any mesh or use the default cube
3. Click on one material
4. Go to Material tab
5. Now the selected material is painted on the whole object (I don't know whether this is intended or not)
![armorpaint](https://user-images.githubusercontent.com/28649121/96976489-36f18e80-151c-11eb-8b2f-6f3f1d752c72.jpg)

6. Now I click on the second material and it gets painted on some places I do not understand
![armorpaint2](https://user-images.githubusercontent.com/28649121/96976494-39ec7f00-151c-11eb-84bd-ec815bddfca4.jpg)

By going back to Paint tab and selecting the other material the whole situation is inverted.

Material tab second strange behavior:
1. Same situation as above, go to Material tab
2. Drag and drop a material to the Layes view, then a new one is created and the object is completely painted.
3. Go back to Paint tab
4. The layer is still there but completely black and the object is not painted.

Bake tab:
Here everything seems to be fine. Drag and drop a material onto a layer works as expected.

Render tab:
1. Only one material is shown which is white. I can change its shader graph but nothing happens.
2. I can also Import using the import material button in the materials tab on the right. The textures get loaded, but the Render Tab does not show the materials on the right side. Now if I switch back to the paint tab all materials are there and the shader graphs are correct but the round material preview on the right remains white, even though the materials works perfectly. The round preview gets updated correctly be reconnecting the base color (or something else)
3. The the material button on the right is enabled but nothing happens

Finally I have got one question:
What is the exact purpose of the Material tab? Is it to live preview materials as the object get updated on any change in the selected material?

**Comment by MathemanFlo** [comment]
Due to your quick fixes the situation got much better in Render tab now. Mist notably no crashes so far. Thank you so much for that.
But I think I found some strange behaviors again:
In the render tab I can create now multiple materials (I gave still no idea wht's the point of this...) in the following way:
1. Use my tower example with multiple objects in it
2. Go to Render tab
3. One material (white) is there and no other material (Is this intended?) 
4. I still think it is a bug that a selection for objects to move can be made by layers BUT must be done in paint mode. So if I want to move the wall I have to go back to paint tab, select the layer and then switch back. Now, no matter which layer is selected I can always shift the wall. Hence one has to remember which layer was selected in paint mode...
5. But back to materials. Now in render tab I can not create materials by default, but I have to go to the Outliner section on the right, click on some object and then I can create new materials and also edit their shader graphs.
6. Now switch back to paint tab and switch to Render tab again

Now all materials in are non-clickable (the blue frame is missing or on its last position) and on double click "Material 2" shader graph is shown and can be edited. As a result the whole object is painted and this remains if I switch back to paint tab. 

To be honest I'm currently not so sure whether I understand the intention behind the render tab. What's the exact purpose?  Is it to move/rotate/scale objects, the camera ans the light? Further more why is the Properties and Outliner tab not shown in Paint tab. It would be very useful to hide some parts of the mesh in case of complicated meshes. This would be a nice enhancement of the drop  down menu in layers tab on the right where I can hide all but one element but not disable one/some and show all others. To be concrete I'd really like to have a drop down with checkboxes so hide/unhide some elements in Layers tab on the right.

**Comment by luboslenco** [comment]
> 6. Now I click on the second material and it gets painted on some places I do not understand

Pushed a fix at https://github.com/armory3d/armorpaint/commit/b323387012f8b81bd6f5c5962e7c1f8cba881d9b.

> Material tab second strange behavior:

Pushed a fix at https://github.com/armory3d/armorpaint/commit/1aebaa748b42c6a2def151ef17ddab8de054aec4.

> Render tab:

Please disregard this one for now, it's my fault for exposing stuff too early. If I will not manage to finish the render workspace in time for the 0.8 release I will hide it to prevent confusion.

> What is the exact purpose of the Material tab? Is it to live preview materials as the object get updated on any change in the selected material?

Yes. Will add docs about it to the manual once final 0.8 is here.

Many thanks for the report!
