### ISSUE TITLE
Reimporting mesh in Render view crashes ArmorPaint

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#641]
Unfortunately I do not have the permission to reopen an issue but I commented some additional issues in #637
Sorry for doing it the wrong way.

**Comment by luboslenco** [comment]
No prob at all, happy for every report. 
- Fixed the reimport crash
- Reimporting the mesh will also restore the transform now
- Fixed the disappearing tab

https://github.com/armory3d/armorpaint/commit/78c49d368561ebd308332c21161c84154e983b18 https://github.com/armory3d/zui/commit/48557961f456f0d519f3e9776ece0d23496d7d26
