### ISSUE TITLE
Outliner -> Import not working correctly

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#643]
**ArmorPaint version:**
b323387

I hope you are not upset by all my issues but I scheduled some time today to report as much issues as I can find to stabilize ArmorPaint because I'm a experienced "ordinary" mathematician/developer for computer vision, signal processing and so on and I started to learn game development on my own. As I'm not artistically talented at all ArmorPaint is just the best software imaginable because the results I can achieve are way beyond my expectations.  So thank you for your patience and for your wonderful software. It is so intuitive and a dream for every developer who tries to produce non shitty 3D art.

**Issue description:**
Outline -> Import does not really work.

**Steps to reproduce:**
1. Load a mesh the ordinary way.
2. Go to render -> Outliner and import the very same mesh/or any other
![armorpaint](https://user-images.githubusercontent.com/28649121/97011218-ad0aeb00-1546-11eb-8c10-8939b4caae07.jpg)
As you can see the roof is imported way to big and the rest is missing. Further more and this does not only happen in this case but always:
The Outliner -> Scence tree has Dach (German word for roof) as a root object for the model and all other objects are children. this is not quite right. It should be called Bakery. 
the second import creates a bakery node (the one at the end) but places all its children again as children of Dach (i.e. the first file).

**Comment by luboslenco** [comment]
Super happy for every opened issue, it helps to improve ArmorPaint a ton! 🙂

**Comment by MathemanFlo** [comment]
Yes ArmorPaint improves rather quickly and I'm sure I'll be able to use it in a stable manner in productive work in a very short time.
I've also an ammendment to this issue. I can produce a crash via

1. Load a mesh via File menu
2. Go to Render tab and open open another mesh via Outliner -> New
3. Click File Import mesh and import the first one again (still in render mode, otherwise ArmorPaint does not crash)
4. Immediately after that click reimport Mesh in File menu and ArmorPaint crashes

I think one of the reasons could be that in Render tab File Import mesh does not remove the old one. For instance this screenshot shows my tower and the default cube.
![armorpaint](https://user-images.githubusercontent.com/28649121/97071056-bd21d980-15dd-11eb-8c81-c91b14d8ae9a.jpg)

**Comment by luboslenco** [comment]
I have made the render tab invisible via 4e8ab6e - please ignore it for now.
