### ISSUE TITLE
Split view behaves strange

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#645]
**ArmorPaint version:**
7d31407

**Issue description:**
The split view behaves strange in some cases

**Steps to reproduce:**
_Rotation issue_
1. Open any mesh or the default cube
2. Open split view in menu Viewport
3. Rotate a mesh by mouse. Rotations always sync between the two views but shifts don't. In my opinion rotations in one view should not change the rotation in the other view. Rotations in Camera menu only affect the left view.

_Render tab and split view_
If split view is enabled, the red, green, blue arrows can not be used to shift the mesh or parts of it.

_Resize flickering_
Not exactly a bug but the left of the two view is not immediately updated on resize. 
1. Open split view
2. Change the width of the right panel (Layers, History, Plugins) or the shader graph editor. Then the redraw on resize is not smooth.

**Comment by luboslenco** [comment]
Should be a bit less strange now with latest fixes.
