### ISSUE TITLE
Crash on cyclic brush shader graph

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#646]
**ArmorPaint version:**
7d31407

**Issue description:**
Some cyclic Brush shader graphs kill ArmorPaint

**Steps to reproduce:**
1. Create a value-value node cycle, it does not crash yet.
![armorpaint](https://user-images.githubusercontent.com/28649121/97043434-c45fcd80-1572-11eb-85bd-09ba017a5253.jpg)
2. Now connect the cycle to the brush output 

Similar results can be produced by a Input-Input to brush output cycle, a random-random to brush output, a separate vector-vector to brush output, and so on.
I did not test all possibilities but I think it only crashes on connect to brush output

**Comment by luboslenco** [comment]
👍 Pushed a fix at https://github.com/armory3d/armorpaint/commit/784de44ad99981fac753738c899a071a52dcd820.
