### ISSUE TITLE
Mac Decal Image Crash

### ISSUE THREAD

**Issue by KBATL** [armory3d/armorpaint#647]
**ArmorPaint version:**
Most Recent Mac Build

**Issue description:**
Using the Decal feature with an image texture crashes AmorPaint

**Steps to reproduce:**
Add image and connect Material Output for new material. Select Decal tool on left.

**Comment by luboslenco** [comment]
Pushed fixes at https://github.com/armory3d/armorpaint/commit/4d5e2ffed7292da93a396de79b2cb8928d7090fe and https://github.com/armory3d/armorpaint/commit/9ee816d4cc6016584b53cc9ae3960483f112d956, updated builds incoming. Thanks for report!
