### ISSUE TITLE
Particle tool crash

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#648]
**ArmorPaint version:**
d96d095

**Issue description:**
ArmorPaint crashes if the particle tool is selected and a new project is created

**Steps to reproduce:**
1. Open ArmorPaint with default cube
2. Select the particle tool
3. Create a new project. ArmorPaint crashes (this time the process really crashes and no dmp is written)

Expected behavior: The new project is created and the tool remains selected (as this is the behavior for all other tools)
I couldn't find any other tool having this issue.

**Comment by infinder** [comment]
confirmed..

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/1cd7d29d918d0aa5c894f5f51a6b4d1865a4f17a.
