### ISSUE TITLE
Modes do not get updated in Render tab

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#649]
**ArmorPaint version:**
d96d095

**Issue description:**
Switching the Mode (Lit, Base color, Roughness, ...) does not work in Render mode

**Steps to reproduce:**
1. Select any Mode in the menu, e.g. Object ID
2. Go to Render mode, then this Mode is shown
3. Change the mode -> nothing happens
4. Go back to painting tab -> Mode gets updated
5. Go back to Render tab and it is set.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/63535933b7cbad7e239c1c3254919c3388bbc6e2.
