### ISSUE TITLE
Reimport Mesh imports wrong mesh

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#650]
**ArmorPaint version:**
d96d095

**Issue description:**
Reimporting the mesh after creating a new project imports the old one

**Steps to reproduce:**
1. Load a mesh
2. Create a new Project e.g. the default rounded cube
3. Reimport the mesh in file menu

Result: the old mesh is reloaded.
the issue does not happen for reimport textures

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/fccce510a8755dfa277f9a861cf68b3950d0f324.
