### ISSUE TITLE
Text display on the cursor turns into a ghost image

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#651]
Prepare 2-3 simple materials with different colors. Select the text tool and paint the cube once. Now choose a different material. The text display on the cursor turns into a ghost image ..

![text_bug](https://user-images.githubusercontent.com/72331575/97071146-e85cf680-15e6-11eb-93b1-bb0aeb8dee64.jpg)

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/dcf2a011664d3e4f7e3af3435fca6364abd343c3.
