### ISSUE TITLE
Meshes import (right sidebar on the bottom) behaves inconsistently

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#652]
**Issue description:**
Importing a mesh via Meshes -> Import (in the right side bar on the bottom, where you can also find Textures and Fonts) does replace the current mesh in Paint tab.
In Render tab the same appends a new mesh.

**Steps to reproduce:**
1. Do the steps described above.
2. Notice another weird behavior: If you go to Paint tab and Reimport the mesh, then all but the last one are removed but remain in the sidebar view in Outliner:
![armorpaint](https://user-images.githubusercontent.com/28649121/97071304-c449e700-15df-11eb-87d5-b67d3ce6dc24.jpg)

By the way I also think that the Meshes view on the bottom does not work with multiple meshes at all.
 
Finally I have one question/remark on UX:
Is it really necessary and useful to have the ability to import meshes via
- File menu
- Outline in Render tab
- Meshes in the side bar.
- Drag & Drop

and have different behaviors while calling all of them Import? I think this is really confusing
Just an idea: Call the ones which add a mesh simply "Add Mesh" or unify the behavior to always add a mesh (which would be consistent with importing textures, brushes and fonts). 

Is the Meshes side bar and the Outliner side bar really needed? It seems to me rather duplicated (besides the fact that there is the possibility to modify the Camera and the Light). I'd really like to have one view in all tabs (paint, render,...) where I can: Add meshes, toggle visbility of objects, have access to the Tools (Flip normals, ...) and can access more advanced information (like the Properties panel). Everything else is confusing.

**Comment by luboslenco** [comment]
I have made the render tab invisible via https://github.com/armory3d/armorpaint/commit/4e8ab6ecc63fc69f548fc3b36ab645f0e45dd18d - please ignore it for now. All of the other mesh import methods should work exactly the same.
