### ISSUE TITLE
Some texture sources produce wrong results

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#653]
**ArmorPaint version:**
d96d095

**Issue description:**
Most texture nodes besides Image Texture do create weird artifacts when using the ordinary brush tool. The issue does not happen if fill tool is used.

**Steps to reproduce:**
1. Create brick texture or magic texture or any other if these texture sources. 
2. Paint small circles using the brush tool
![armorpaint](https://user-images.githubusercontent.com/28649121/97077984-b187e000-15e8-11eb-94fc-6bc8aadde11f.jpg)

the same happens on a mask layer besides the weird outlines where the base color shines through which was already described in #568.

**Comment by luboslenco** [comment]
Fix coming together with https://github.com/armory3d/armorpaint/issues/316.
