### ISSUE TITLE
Unity texture export preset is slightly incorrect

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#655]
**Issue description:**
The unity texture export is slightly incorrect because the "mos" texture has smoothness in A channel and not in B channel.
Also the height texture is missing

**Solution**
Replace unity.json  with
```
{
	"textures": [
		{ "name": "base", "channels": ["base_r", "base_g", "base_b", "1.0"] },
		{ "name": "nor", "channels": ["nor_r", "nor_g", "nor_b", "1.0"] },
		{ "name": "mos", "channels": ["metal", "occ", "1.0", "smooth"] },
		{ "name": "height", "channels": ["0.0", "height", "0.0", "1.0"] }
	]
}
```

For reference look at:
![armorpaint](https://user-images.githubusercontent.com/47142024/59652954-ab405300-91ad-11e9-849e-e4d58f533cc0.png)

**Comment by luboslenco** [comment]
👍 👍 https://github.com/armory3d/armorpaint/commit/b5c1c78becfb1ce2f161db005cd0675d228d7d12
