### ISSUE TITLE
Brush with stencil don't work as it should

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#656]
ArmorPaint.org - v0.8 (2020-10-25) - 921e31d
Windows10 - Direct3D11
Intel(R) HD Graphics 620 

Brush with stencil don't work as it should

1. Create a new brush
2. use an image texture node as stencil.

Stencil doesn't appears in the viewport

![bug1](https://user-images.githubusercontent.com/72331575/97099508-688c6600-1692-11eb-8894-601fca3d98cb.jpg)

It used to work just fine before

![bug2](https://user-images.githubusercontent.com/72331575/97099518-91146000-1692-11eb-89ca-e06bc9ea551b.jpg)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/7c09a08a61cc22b86d91d967b3d0af747b857791, thanks for report.
