### ISSUE TITLE
Windows build with vulkan support?

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#657]
Could there be a windows build with vulkan support? 
I work on a laptop with Intel (R) HD Graphics 620 and I have read it could support vulkan on windows10.
just asking..

**Comment by luboslenco** [comment]
On Windows with integrated graphics, Direct3D11 build is the fastest one as of now. The benefit of D3D12 / Vulkan is the access to raytracing, but that is not supported on integrated cards.
