### ISSUE TITLE
Weird rotation

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#661]
ArmorPaint.org - v0.8 (2020-10-25) - df2f55d
Windows10 - Direct3D11
Intel(R) HD Graphics 620

It's only me or navigation in the viewport has become weird and slow. Rotation continues for a while after you stop dragging the mouse. if you open the nodes window camera movements become normal. If you close the node view weird camera movements come back.

**Comment by infinder** [comment]
No, everything works as it should now! maybe something on my laptop..

**Comment by infinder** [comment]
The problem seems to be with a low battery level or just using the Laptop battery and not direct power.

**Comment by luboslenco** [comment]
Sounds like the GPU is unable to keep up - turnig off `Preferences... - Viewport - SSAO` should help.
