### ISSUE TITLE
Black Spots on imported obj model

### ISSUE THREAD

**Issue by FrankCastleOG** [armory3d/armorpaint#662]
Hi there,
i just purchased armorpaint (for mac) and so far i find it an amazing addition to my workflow with blender.... 

But when i import an obj object or blend file i get strange black spots on the model that seem not to be affected by me  painting on them.... 

FYI: After the purchase there have been 2 files for mac to download and i just got both, because i did not know which one's the right one.... One zip file was called ArmorPaint_07_mac_unsigned (does not work) the other one ArmorPaint_08dev_mac (works but with the black spot issue). 
The imported mashes are uv-unwrapped.

Does anybody else know about that problem and how to solve it???
.... Google search did not really help....
Please excuse if this topic already exist, but i could not find it....

Greets and THX in advance

**Comment by luboslenco** [comment]
Hello, thanks for reporting the issue. Is the model UV unwrapped correctly? Are the model normals correct? I can take a look at the obj file and investigate if you are able to share it.

`ArmorPaint_07_mac_unsigned ` = version 0.7. `ArmorPaint_08dev_mac` = development version 0.8. I assume you are on a mac where you are restricted to running notarized software only.

**Comment by FrankCastleOG** [comment]
Hi there,

Thanks for the answer.
FYI: i'm also the guy that asked about the specs/iMac(late2013) ... i just gave it a shot and it seems to work fine... It just looks a bit low-res... Can't update due to a music software i have to use, which is not supported by newer OS versions.... but anyway

I'm pretty sure you will laugh at the "quality of my model, because i am a total noob in the 3d World .... Normals should be fine and the model is uv-unwrapped (i hope correctly)....  it would be great if you can have a look for the bug (that most likely i created.... i guess)

in case you can't see the black spots - they are mostly on the hands and feet of the model.

here's a wetransfer link

https://we.tl/t-i78TMy28XM

Thanks in advance, and i want to let you know, that i'm already a fan of armorpaint

greets,

Benjamin D. Graci

-----Original Message-----

**Comment by luboslenco** [comment]
Happy to hear from you! Thanks for sharing the file.

> It just looks a bit low-res

Try setting the `Preferences... - Viewport - Super Sample` option to `1.0x` if it's at `0.5x`. It will make the viewport more gpu hungry though. If it ends up not fast enough you might also experiment with setting `Renderer` option from `Full` to `Mobile`, so you can keep the viewport sharp while trading some render quality.

> in case you can't see the black spots - they are mostly on the hands and feet of the model.

It's a super cool model! When checking the UV map for the hands and feet, it looks like those parts are not unwrapped to big enough area:

![a](https://user-images.githubusercontent.com/3685704/97550962-a65ef680-19d2-11eb-933e-cbb144f37852.PNG)

I did a quick unwrap using the [Smart UV Project](https://docs.blender.org/manual/en/latest/modeling/meshes/editing/uv.html#smart-uv-project) operator in Blender:

![b](https://user-images.githubusercontent.com/3685704/97551547-664c4380-19d3-11eb-9cee-a17617a43b85.PNG)

And afterwards you should get no more black spots and the painting should work well. 🙂 

![c](https://user-images.githubusercontent.com/3685704/97551606-79f7aa00-19d3-11eb-8d5e-373e49028efa.PNG)

**Comment by FrankCastleOG** [comment]
HEy... thx for the quick help....

I will try the settings that you recommended directly in my next session....

Glad that you like my model. Funny thing is, that i tried "proper" uv-unwrapping for the first time (and obviously failed XD ). Before that i always went the smart-uv protect way.

And THX again... that's what i call customer service

Greets from paraguay

-----Original Message-----
