### ISSUE TITLE
Weird UV - Material combination

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#665]
Sorry for asking basically the same question again but I'm still unsure whether I got it completely:
Suppose you have the following simple mesh. It's just a cube but with a weird combination of UV and materials. Always two opposite sides do share the same UV but belong to different materials. 
[Cube.zip](https://github.com/armory3d/armorpaint/files/5448163/Cube.zip)
Now I can easily do the following:
![armorpaint](https://user-images.githubusercontent.com/28649121/97363677-3ef65900-18a3-11eb-9d38-2d62159350c2.jpg)
Create two Layers - one for each material - and paint them differently. Then ArmorPaint shows a painted mesh which does not exist in reality and by exporting I do get - depending on the Layer order - a red or green texture. 
I could be totaly mistaken but I would expect ArmorPaint to produce what I get in reality.
I remember running into issues once where I mistakenly created overlapping UVs. In ArmorPaint I couldn't see that due to a similar situation as above and after exporting my painted mesh to unity I realized I made a mistake in the beginning.
Is it an unavoidable consequence of the way how ArmorPaint is implemented internally?

**Comment by luboslenco** [comment]
Hello, if you set the overlapping UV maps onto the separate atlases:

![a](https://user-images.githubusercontent.com/3685704/97367893-335a6080-18aa-11eb-8754-031b95a4a34a.PNG)

You should get one texture set per atlas: 

![b](https://user-images.githubusercontent.com/3685704/97367902-37867e00-18aa-11eb-8d8e-3e7f152eef05.PNG)

**Comment by MathemanFlo** [comment]
Thank you for your nice example. That is exactly what I'd expect with multiple textures (I feature I didn't know I need before having it. Now I can texture multiple meshes simultaneously. That's truly awsome and a massive improvement in my workflow). 
But non the less I wouldn't expect ArmorPaint to look like that in my screenshot above (which only involves one atlas not two of them). I would expect either a green or a red cube and not a mixed one. I still think this is a bug. Why is it none?
