### ISSUE TITLE
 Pressing f to change the brush size, freezes the viewport

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#668]
It used to work before. I realize I can do the same thing with ] for increase the size and [ for decrease..

**Comment by MathemanFlo** [comment]
I can confirm that. The mouse cursor gets stuck exactly at the middle of the screen where it is hidden but can be revealed by Alt-Tabbing to a different window.
I also realized that the [ ] does not work for my german keyboard layout where [ is AltGr+8 and ] is AltGr+9. It definitely works for the english one though.

**Comment by luboslenco** [comment]
Which ArmorPaint version? a22ec67? Windows?

**Comment by infinder** [comment]
a22ec67,  Windows10

**Comment by luboslenco** [comment]
Hm, seems to work ok here, a22ec67 & Windows10. :(

**Comment by infinder** [comment]
It happens immediately after i press f..Νot once did it work properly .. I think it has been happening for at least two editions, but I'm not sure..

**Comment by luboslenco** [comment]
- Do you spot any errors in the Visual Studio output console after pressing f?
- Do you press and hold the f? Does mouse get released after pressing f again?

**Comment by infinder** [comment]
I didn't hold f pressed.. Now it works. At any right, it souldn't be freezed when I just press and release f..

**Comment by infinder** [comment]
Debug output from VS..
[debug output.txt](https://github.com/armory3d/armorpaint/files/5454898/debug.output.txt)

**Comment by luboslenco** [comment]
👍 Should no longer lock after https://github.com/armory3d/armorpaint/commit/18f487cce5c8fe2fda4c57a878d93ddeab58ad86.
