### ISSUE TITLE
Weird behavior when pressing tab in other languages than english

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#671]
Selecting any other interface language than English and pressing tab, toggles the node editor but also cycles paint, material and bake modes. Selecting English again does not solve the problem unless you reopen the program.

ArmorPaint.org - v0.8 (2020-10-30) - 8f6a140
Windows - Direct3D11

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/zui/commit/59ff212916385e6f8569e76a9c4f54afb4948e08, thanks for report. Make sure to update submodules as well.

The cause of a bug should be opening any popup window via a shortcut (ie. `ctrl+k` for preferences). If there is indeed something wrong with the language swap please let me know.
