### ISSUE TITLE
How does Developing ArmorPaint on Windows?

### ISSUE THREAD

**Issue by Yue-Liu-j** [armory3d/armorpaint#673]
How does Developing ArmorPaint on Windows make an IDE work? Such as: code completion, code tracing, looking for references, etc...
Previously using the VsCode editor, you can implement these functions after installing the Kha and Haxe plugins. But I can't do it these days. What should I do?

**Comment by Calinou** [comment]
> Previously using the VsCode editor, you can implement these functions after installing the Kha and Haxe plugins. But I can't do it these days. What should I do?

What happens when you try to install the Haxe and Kha extensions? Do you get any error messages?

**Comment by Yue-Liu-j** [comment]
I received two new errors.
<img width="338" alt="VsCode Error" src="https://user-images.githubusercontent.com/72639242/99607323-8907d000-2a46-11eb-9b39-3292a1ec55e9.png">
