### ISSUE TITLE
Does not show layer texture when edited layer is active

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#674]
Does not show layer texture when edited layer is active

![image](https://user-images.githubusercontent.com/69405892/97923384-2c29cb80-1d5e-11eb-9871-7e28ee865afb.png)

![image](https://user-images.githubusercontent.com/69405892/97923400-38158d80-1d5e-11eb-8e38-4119c2309abc.png)

I use latest downloadable build ArmorPaint. - LINUX (OpenGL)

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/675.
