### ISSUE TITLE
Crash the second time I open ArmorPaint or load a file after opening another project - Linux

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#676]
Crash the second time I open ArmorPaint or load a file after opening another project.
![image](https://user-images.githubusercontent.com/69405892/97927394-2e435880-1d65-11eb-9719-973235871d3a.png)

When ArmorPaint closes and reopens after crash, it works fine.
![image](https://user-images.githubusercontent.com/69405892/97927592-9134ef80-1d65-11eb-921b-37cf19513541.png)

I use latest downloadable build ArmorPaint. - LINUX (OpenGL)

**Comment by luboslenco** [comment]
Thanks for report. Can you give me the exact steps to reproduce? Is this with armorpaint running from read-only location https://github.com/armory3d/armorpaint/issues/619? (trying to figure out the setup so I can reproduce)

**Comment by SaraDark** [comment]
ArmorPaint runs with read / write user permissions
Centos 8.2 (4.18.0-193.14.2.el8_2.x86_64) OpenGL with Nvidia drivers.
Run normally, the shortcut that calls the command: / opt / ArmorPaint / ArmorPaint
exacly like by run on terminal / opt / ArmorPaint / ArmorPaint

**Comment by SaraDark** [comment]
It look like fix :), ArmorPaint.org - v0.8 (2020-11-16) - a8f04d0

**Comment by luboslenco** [comment]
Awesome!
