### ISSUE TITLE
Improving "Add help button to mesh import box"

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#678]
I saw you added a button to https://github.com/armory3d/armorpaint_docs/blob/master/faq.md some minutes ago.
The first time I used ArmorPaint I had serious issues to import my meshes due to the problem of non-triangulated, non-convex fbx files. Luckily I found your helpful comment in #228 which prevented me from giving up ArmorPaint on my first try. I think it would be worth to add this helpful remark and maybe also some other limitations of the importer.

**Comment by luboslenco** [comment]
Added note on  non-convex polygons, thanks for notice!
