### ISSUE TITLE
Armorpaint directX 12 DRX crush when add opacity material

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#679]
ArmorPaint.org - v0.8 (2020-11-04) - c3a001c
Win 10 64 bit  GTX 1070(v. driver 26.21.14.4166)

Good afternoon Lubos!
Yesterday I updated the Windows DXR version. It's very interesting to see the transparency implementation. I decided to try it, maybe it will appear in this version (I thought)) I reduce the transparency of the standard material and assign it to a regular cube. And the program crashes.
![prew](https://user-images.githubusercontent.com/65244629/98227252-21428700-1f68-11eb-9bcc-6292011b5454.jpg)
Thanks and have a nice day)

**Comment by MathemanFlo** [comment]
Just in case it is of interest I can not reproduce it in the D11 07e3397 Build on Win 10 64bit. So it seems to be related to DirectX 12 raytracing.

**Comment by luboslenco** [comment]
Many thanks for report, fix at https://github.com/armory3d/armorpaint/commit/5db49b90917fd864693b74a16734b7fa7b7ab359. Documentation update on transparency in path-traced mode still coming.

**Comment by AlexKiryanov** [comment]
thanks for the answer Lubos)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

чт, 5 нояб. 2020 г. в 14:06, Lubos Lenco <notifications@github.com>:
