### ISSUE TITLE
Krom stops working when minimizing or switching to desktop on Windows

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorpaint#68]
Steps to reproduce on **Windows 8.1 64bit**:

- Open **Armorpaint 0.6 dev build** for win64
- Minimize or switch to desktop with Windows key + D

Error: "Krom has stopped working"

**Comment by luboslenco** [comment]
Awesome, thanks for catching that - switched to Direct3D11 on Windows and slipped this, fix incoming. 🙂

**Comment by luboslenco** [comment]
Fixed now and also updated windows build.

**Comment by MoritzBrueckner** [comment]
Thank you :)
