### ISSUE TITLE
Transparency bug in Material tab

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#680]
**ArmorPaint version:**
07e3397

1. Fill an empty layer with this material
![1 step](https://user-images.githubusercontent.com/28649121/98233912-f05e5400-1f5f-11eb-9823-756cb0c21094.png)

2. Go to material tab, unplug the opacity voronoi texture and pull the slider down
![2 step](https://user-images.githubusercontent.com/28649121/98233979-0e2bb900-1f60-11eb-9d6c-62977623d088.png)

3. Go back to paint tab and paint with the material. The opacity is not applied. (But it will be applied if I click on the opacity slider again)
![3  step](https://user-images.githubusercontent.com/28649121/98234104-3e735780-1f60-11eb-9f92-875b8c6ed0b8.png)

The same does not happen for other maps like metalic or roughness.

In addition I have got a question I'd like to ask:
Whenever I paint a base color and say a normal map using a material, then both to not interfere with each other on a texture level, but in case of opacity this does not hold true. Initially I would have expected to get a completely green base color and some pattern in the opacity channel. 
![question](https://user-images.githubusercontent.com/28649121/98234722-1e906380-1f61-11eb-8c81-c3805bf55c2d.png)
I think this becomes really strange in case I just paint opacity and no base color because I would not expect something greyish at all. Please also notice the "stacked" paint strokes (I mean you can see I painted multiple times on similar positions). These are only in the base color, the opacity is not affected at all because I didn't change it.
![question2](https://user-images.githubusercontent.com/28649121/98235163-be4df180-1f61-11eb-9ca5-6c4e1aca84a5.png)

**Comment by luboslenco** [comment]
Should be resolved via https://github.com/armory3d/armorpaint/commit/aedcf718a08677372ae88814e38e875287d06d74, thanks for report. More opacity fixes to come as the behavior is still confusing.
