### ISSUE TITLE
how to compile for Android without errors?

### ISSUE THREAD

**Issue by MarcioVitor** [armory3d/armorpaint#681]
I can't compile for Android, even making the requested manual Tweaks, Android Studio always returns an error in which it cannot find v8Monolith.I would like to know if someone does not have a CMAKE file ready for me to compile. note: I can compile normally for Windows

**Comment by luboslenco** [comment]
Hello, please use the desktop builds for now. Hoping to make android build process work out of the box without the manual tweaks as soon as possible.
