### ISSUE TITLE
ArmorPaint freezes on any mode change

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#682]
**ArmorPaint version:**
9b0e2f7

**OS/device including version:**
Win64

**Issue description:**
ArmorPaint freezes on any mode change.

**Steps to reproduce:**
1. Open ArmorPaint
2. Change Mode in Mode menu
![1 step](https://user-images.githubusercontent.com/28649121/98345521-1134b100-2015-11eb-838f-baae62419776.png)

**Comment by luboslenco** [comment]
👍 👍 fix at https://github.com/armory3d/armorpaint/commit/ac9a398b8e20aeab97cf120d1b5f1a10fac5a207..
