### ISSUE TITLE
Open containing directory

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#684]
It would be nice to be able to right click on a texture and have to possibility to open the directory containing this texture in the native file explorer (preferred because I have file previews there unlike in ArmorPaint's internal browser) and/or in the browser on the bottom. This way it would be very handy to locate a texture and add additional textures from a directory very quickly.
![1 step](https://user-images.githubusercontent.com/28649121/98359626-d0df2e00-2028-11eb-971a-8f467bb311b8.png)

**Comment by MathemanFlo** [comment]
Thank you very much for implementing it in e7daffb. It works perfect and is really appreciated.

**Comment by luboslenco** [comment]
Happy to hear! 🙂 Thanks for another great suggestion.
