### ISSUE TITLE
Bundled fabric_ball model has overlapping UVs

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#685]
The bundled fabric_ball asset has overlapping UVs. I think this should not be the case as it is very unintuitive for users who want to try ArmorPaint.
![1 step](https://user-images.githubusercontent.com/28649121/98361193-64196300-202b-11eb-8353-95b13bed7027.png)
![2 step](https://user-images.githubusercontent.com/28649121/98361297-91661100-202b-11eb-96db-7f46e3b57486.png)

**Comment by luboslenco** [comment]
Removed the `fabric_ball` for now but `shader_ball` is still present as a mesh for quick testing.
