### ISSUE TITLE
Linux compile error (fatal error: 'gtk/gtk.h' file not found)

### ISSUE THREAD

**Issue by LordVeggie** [armory3d/armorpaint#686]
lordveggie@pop-os:~/Documents/GitHub/armorpaint/armorcore$ node Kinc/make -g opengl --compiler clang --compile
kincfile found.
Creating Linux project files.
Compiling shader 1 of 10 (g1.frag).
Compiling shader 2 of 10 (g1.vert).
Compiling shader 3 of 10 (painter-colored.frag).
Compiling shader 4 of 10 (painter-colored.vert).
Compiling shader 5 of 10 (painter-image.frag).
Compiling shader 6 of 10 (painter-image.vert).
Compiling shader 7 of 10 (painter-text.frag).
Compiling shader 8 of 10 (painter-text.vert).
Compiling shader 9 of 10 (painter-video.frag).
Compiling shader 10 of 10 (painter-video.vert).
Compiling...
clang  -O2 -I./ -I../../v8/include -I../../Libraries/nfd/include -I../../../../../../../../usr/include/gtk-3.0 -I../../../../../../../../usr/include/glib-2.0 -I../../../../../../../../usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../../../../../../../usr/include/pango-1.0 -I../../../../../../../../usr/include/cairo -I../../../../../../../../usr/include/gdk-pixbuf-2.0 -I../../../../../../../../usr/include/atk-1.0 -I../../../../../../../../usr/lib64/glib-2.0/include -I../../../../../../../../usr/lib/glib-2.0/include -I../../../../../../../../usr/include/harfbuzz -I../../Libraries/tinydir/include -I../../Libraries/zlib -I../../Libraries/texsynth -I../../Kinc/Sources -I../../Kinc/Backends/System/Linux/Sources -I../../Kinc/Backends/System/POSIX/Sources -I../../Kinc/Backends/Graphics4/OpenGL/Sources -I../../Kinc/Backends/Graphics5/G5onG4/Sources  -DKINC_IMAGE_STANDARD_MALLOC -DWITH_NFD -DWITH_TINYDIR -DWITH_ZLIB -DWITH_TEXSYNTH -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_LINUX -DKORE_OPENGL -DKORE_POSIX -DKORE_G4 -DKORE_G5 -DKORE_G5ONG4  -std=c99  -c ../../Libraries/nfd/nfd_gtk.c -o nfd_gtk.o
clang  -O2 -I./ -I../../v8/include -I../../Libraries/nfd/include -I../../../../../../../../usr/include/gtk-3.0 -I../../../../../../../../usr/include/glib-2.0 -I../../../../../../../../usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../../../../../../../usr/include/pango-1.0 -I../../../../../../../../usr/include/cairo -I../../../../../../../../usr/include/gdk-pixbuf-2.0 -I../../../../../../../../usr/include/atk-1.0 -I../../../../../../../../usr/lib64/glib-2.0/include -I../../../../../../../../usr/lib/glib-2.0/include -I../../../../../../../../usr/include/harfbuzz -I../../Libraries/tinydir/include -I../../Libraries/zlib -I../../Libraries/texsynth -I../../Kinc/Sources -I../../Kinc/Backends/System/Linux/Sources -I../../Kinc/Backends/System/POSIX/Sources -I../../Kinc/Backends/Graphics4/OpenGL/Sources -I../../Kinc/Backends/Graphics5/G5onG4/Sources  -DKINC_IMAGE_STANDARD_MALLOC -DWITH_NFD -DWITH_TINYDIR -DWITH_ZLIB -DWITH_TEXSYNTH -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_LINUX -DKORE_OPENGL -DKORE_POSIX -DKORE_G4 -DKORE_G5 -DKORE_G5ONG4  -std=c99  -c ../../Libraries/zlib/inflate.c -o inflate.o
../../Libraries/nfd/nfd_gtk.c:10:10: fatal error: 'gtk/gtk.h' file not found
#include <gtk/gtk.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [makefile:14: nfd_gtk.o] Error 1
make: *** Waiting for unfinished jobs....
Build time: 0m 0s
Compilation failed.

it looks like some of the Linux files are missing or not added yet how can i fix this??

**Comment by luboslenco** [comment]
Hello, make sure to install linux dependencies linked in the readme: https://github.com/armory3d/armorpaint/wiki/Linux-Dependencies.

**Comment by LordVeggie** [comment]
sorry to bother but i did re run all the terminal comands of the
dependencies and still get the same error when i cd in to armorcore and run
the command node Kinic/make -g opengl --compiler clang --compile and it
still does not find gtk.h i also checked the git repo and it is also not
there any idea how to fix this? thank you for your time
