### ISSUE TITLE
Option to zoom horizontally or both vertical and horizontal at the same time

### ISSUE THREAD

**Issue by williamtan1080** [armory3d/armorpaint#687]
Currently, the mouse zoom is set vertically only.
I would like to request an option to toggle between zooming horizontally, vertically or both at once like (like in maya)
This would be a nice option to help retain some of the muscle memory from other programs and I hope it's not too hard to implement.

Many Thanks.

**Comment by luboslenco** [comment]
Added a new `Preferences... - Interface - Direction to Zoom` option at https://github.com/armory3d/armorpaint/commit/f3c267122b25ab89d21340f7ba82aba51fdb5c47. New builds up soon. Thanks for report!
