### ISSUE TITLE
Can we create a discord server or sub-reddit?

### ISSUE THREAD

**Issue by jcostello** [armory3d/armorpaint#689]
It would be great to have a place to comunicate between ArmorPaint users in order to share experiences and improve comunication to colaborate better. What do you think?

**Comment by luboslenco** [comment]
Yes please feel free to create those. I am trying to maximize time for development / managing the issues / docs / support so help on that is very welcome.

**Comment by MoritzBrueckner** [comment]
Hi, there is already a discord server for Armory3D and Armorpaint: https://discordapp.com/invite/axq6qWV. Feel free to join :)

**Comment by jcostello** [comment]
@MoritzBrueckner thanks, im join right now
