### ISSUE TITLE
Krom crashes when importing a blend with a path object in it

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorpaint#69]
I accidentally had a path object inside a blend file I was importing and got the error "Krom stopped working".

Windows 8.1 64bit with latest Armorpaint 0.6 dev build.

Example file: http://pasteall.org/blend/index.php?id=51298

**Comment by luboslenco** [comment]
Fixed via https://github.com/armory3d/iron_format/commit/accb41277ede9547f9a78af18bc197deacd5379f and https://github.com/armory3d/armorpaint/commit/38e4a5080b344f35d01851e36a4575c868b5fb84, thanks!
