### ISSUE TITLE
Minor redraw bug on split view

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#690]
**ArmorPaint version:**
51fe06e

**OS/device including version:**
Win64

**Issue description:**
The second view has some very tiny redraw issues when closing menus or dialogs.

**Steps to reproduce:**
1. Open split view
2. Open a menu such that it overlaps with the second view and close it again

![armorpaint](https://user-images.githubusercontent.com/28649121/98725049-efc92180-2394-11eb-9be7-2dadbbbd1e30.jpg)

The same happens for dialogs overlapping the second view as well.
I just noticed it but I think this is very low priority. Thanks to your other split view fixes the feature is great and very appreciated.

**Comment by luboslenco** [comment]
Pushed another fix at https://github.com/armory3d/armorpaint/commit/ac1a8bf91790fcf60724038041d38419d6c57824, thanks for report!
