### ISSUE TITLE
Non deselectable shader node connection

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#691]
In some situation the connection line between two shader nodes can not be deselected anymore.

Steps to reproduce
1. Stack two nodes such that the input/output plugs overlap. You do not have to connect them.
![armorpaint](https://user-images.githubusercontent.com/28649121/98726577-fce71000-2396-11eb-9bfe-42a43ae81f75.jpg)
2. Now click left mouse button down on the stacked plugs and pull the mouse.
3. The "add a new node" menu appears. Either select one or click right mouse button to close it.
4. Now you have a mouse following line which you can not get rid of (at the end of the line in the screenshot would be the mouse cursor which is hidden in the screenshot). I didn't find any way to get rid of this line because it can not be plugged anywhere, creating a new material does not help as well. 
![armorpaint](https://user-images.githubusercontent.com/28649121/98726874-5ea77a00-2397-11eb-8544-6a600e70c436.jpg)

I had this issue already multiple times and never was able to figure out how I achieved it. Maybe there are others as well.

**Comment by luboslenco** [comment]
Should be resolved via https://github.com/armory3d/zui/commit/92bbe44f185a9c66243d686938364502987fda80, thanks for report!
