### ISSUE TITLE
Add translation to Brazilian Portuguese

### ISSUE THREAD

**Issue by MarcioVitor** [armory3d/armorpaint#692]
I created a translation file for the Portuguese language, and I would like it to be added.
[pt_br.zip](https://github.com/armory3d/armorpaint/files/5533130/pt_br.zip)

**Comment by luboslenco** [comment]
It's added now, thanks for contributing! https://github.com/armory3d/armorpaint/commit/90308055c9798757ad526b221ee4b5c0e8588006
