### ISSUE TITLE
Armor Paint does not start on Android 10 build

### ISSUE THREAD

**Issue by MarcioVitor** [armory3d/armorpaint#693]
**ArmorPaint version:**

c75fc324d85104b85a36a52c87d06ed95a9f83ae

**OS/device including version:**

Operating System: Android 10
GPU: Qualcomm Adreno 610 
Backend: OpenGL

**Issue description:**

It displays a black screen and then closes on its own.

**Steps to reproduce:**

Just compile for the Android platform, and open the app on a device running Android 10

Edit: link to download faulty android binary: https://drive.google.com/file/d/1FgbmRdzAA1ANlwzSeDfYkVwxbM6rMtne/view?usp=sharing

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/703.

**Comment by DAVISAO** [comment]
> **ArmorPaint version:**
> 
> [c75fc32](https://github.com/armory3d/armorpaint/commit/c75fc324d85104b85a36a52c87d06ed95a9f83ae)
> 
> **OS/device including version:**
> 
> Operating System: Android 10 GPU: Qualcomm Adreno 610 Backend: OpenGL
> 
> **Issue description:**
> 
> It displays a black screen and then closes on its own.
> 
> **Steps to reproduce:**
> 
> Just compile for the Android platform, and open the app on a device running Android 10
> 
> Edit: link to download faulty android binary: https://drive.google.com/file/d/1FgbmRdzAA1ANlwzSeDfYkVwxbM6rMtne/view?usp=sharing

Hey, send a email for me,
daviarr068@gmail.com
