### ISSUE TITLE
Linux will Vulkan be without ray tracing?

### ISSUE THREAD

**Issue by Madaraz1024** [armory3d/armorpaint#697]
The problem I have is the RX 5500XT ArmorPaintVK video card they do not start only the RTX video card is sadness I need Vulkan better than OpenGL
![image](https://user-images.githubusercontent.com/17591539/99148633-e17f4c00-2699-11eb-8612-689c149738c9.png)

there are other game engines without RTX ray tracing looking cool name SDFGI not necessarily RTX graphics card all both ray tracing works https://godotengine.org/article/godot-40-gets-sdf-based-real-time-global-illumination 

Thanks :)

**Comment by luboslenco** [comment]
Hello, thanks for report. The AMD RX 6000-series cards now also do support ray-tracing so it's no longer just RTX cards from nvidia. I will get a hold of RX 6000-series card asap and ensure it runs properly. ArmorPaint needs hardware accelerated ray-tracing to get the maximum possible performance + needs to shoot "raw" rays against the geometry to perform baking.

PS: OpenGL builds are still recommended on Linux, more work is needed to optimize Vulkan builds.

**Comment by ruchitinfushion** [comment]
Update:
https://www.khronos.org/blog/vulkan-ray-tracing-final-specification-release

https://www.khronos.org/blog/vulkan-ray-tracing-best-practices-for-hybrid-rendering
