### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'v8\libraries\win32\release\v8_monolith.lib'

### ISSUE THREAD

**Issue by Ceebox** [armory3d/armorpaint#699]
**ArmorPaint version:**
Latest from master branch

**OS/device including version:**
Windows 10
R7 2700
GTX 1060
All latest drivers
Using VS 2017

**Issue description:**
Does not compile, with error: LINK : fatal error LNK1181: cannot open input file 'v8\libraries\win32\release\v8_monolith.lib'

**Steps to reproduce:**
Compile on VS2017

---------------------
It is extracted from the zip.

**Comment by luboslenco** [comment]
Make sure to unpack via "Extract Here" so no additional folders are created. Also make sure it was unpacked before calling "node Kinc/make" like in the instructions. The Windows build action appears to have no issues, looking at it might provide more insight:
https://github.com/armory3d/armorpaint/actions

**Comment by Ceebox** [comment]
I have done this.

**Comment by AFWSI** [comment]
@luboslenco 

I'm running into the same issue. Never had a issue, until the build structure changed.
