### ISSUE TITLE
Drag and drop not working on Linux

### ISSUE THREAD

**Issue by SojanJanso** [armory3d/armorpaint#7]
Dragging and dropping meshes and images in the node editor or in the 3d environment, as well as in the import section doesn't work on Linux Ubuntu gnome (Ubuntu 17.10) on ver  _02a and 0.3
Linux Ubuntu gnome (Ubuntu 18.04) on ver _02a, 0.3, and 0.4

Once the image is dragged in the editor, simply nothing happens.
![peek 2018-03-21 17-00](https://user-images.githubusercontent.com/26679320/37737181-69f755f4-2d29-11e8-837d-b03df66e75d0.gif)

**Comment by www2000** [comment]
I can confirm this under Ubuntu 17.10 (i use beta _03)

**Comment by luboslenco** [comment]
Fix at https://github.com/Kode/Kore/pull/325, live in upcoming build.
