### ISSUE TITLE
Obj Export produces unconnected mesh

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#700]
**ArmorPaint version:**
a8f04d0

**Issue description:**
Exporting a mesh as obj produces a unconnected mesh because each triangle gets its own (non shared) vertices. 

**Steps to reproduce:**
[Example mesh.zip](https://github.com/armory3d/armorpaint/files/5551793/Example.mesh.zip)
1. Load any (connected) mesh, e.g. the initial_cube.obj in the attached zip file
2. Export mesh as obj (in case of the cube get exported_cube.obj in the attached zip)
3. By looking at the obj file in an text editor one can see that the mesh contains 36 vertices (the cube has 12 triangles and each triangle gets its own vertices) instead of 8 shared vertices.
4. By looking again at the obj file in a text editor line 122 (the last lne) contains lots of NULL-characters. They shouldn't be there as well.

I know it is not the primary focus of ArmorPaint to deal with the mesh data itself and I also won't need the feature. If ArmorPaint forgets the adjacency i.e. the mesh topology then this is probably not really feasible. I realized the problem when I exported the fabric_ball to blender where I had to repair the mesh first in order to investigate the UV problem more in detail. 

Finally one question out of curiosity: The height data of a texture/layer disturbs the vertices and sometimes produces gaps between them. Is this related to the non shared vertices?

**Comment by luboslenco** [comment]
All should be well now, thanks for report! Not sure on the height data, need to revisit that soon.
