### ISSUE TITLE
Magic first layer

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#701]
ArmorPaint.org - v0.8 (2020-11-04) - c3a001c
Win 10 64bit

Hello Lubos! I decided to re-create this report, because the topic in which I mentioned this is already closed.
So that's it.
There are several functions that only work correctly on layer 1. Namely:

1. The displacement in the viewport are displayed correctly on the first layer, but when you transfer the same layer to the second, the displacement disappears. (But for me it doesn't really matter. But still)
![1](https://user-images.githubusercontent.com/65244629/99377598-73c06380-28d7-11eb-8a02-b3effae90cbd.jpg)
![2](https://user-images.githubusercontent.com/65244629/99377606-758a2700-28d7-11eb-854c-a750a42a3e9e.jpg)

2.Displaying the normal mode works correctly only for the first layer (more precisely, it always shows the normal map of only the first layer)
![3](https://user-images.githubusercontent.com/65244629/99379031-31982180-28d9-11eb-834b-6763d4902fc8.jpg)
![4](https://user-images.githubusercontent.com/65244629/99379034-32c94e80-28d9-11eb-97ad-21bad534ba09.jpg)
![5](https://user-images.githubusercontent.com/65244629/99379038-3361e500-28d9-11eb-853c-ffc1dbeed4fe.jpg)
![6](https://user-images.githubusercontent.com/65244629/99379041-3361e500-28d9-11eb-9352-285c8c35ca0b.jpg)

3. If we use a transparency channel in the material. and using the stamp tool we apply the material. Then the transparency map for the normal map works only on the first layer. On the second layer, the normal map is not clipped to the transparency map.
![7](https://user-images.githubusercontent.com/65244629/99380111-92742980-28da-11eb-85a2-5fd3394ed0c2.jpg)
![8](https://user-images.githubusercontent.com/65244629/99380117-93a55680-28da-11eb-90fc-06fe2145ba00.jpg)
![9](https://user-images.githubusercontent.com/65244629/99380120-943ded00-28da-11eb-984c-4622f374cec5.jpg)

Somehow like this)
Thank you so much! And good day)

**Comment by luboslenco** [comment]
Will investigate, thanks!

**Comment by AlexKiryanov** [comment]
Not on anything)

**Comment by luboslenco** [comment]
Should be resolved now, thanks for report. There is a new layer system under the hood now, some issues may pop up - will be doing more testing and push new builds soon.

**Comment by AlexKiryanov** [comment]
Good afternoon! Yes, it's cool! To be honest, we came up with something here)  I will write to you soon Feature request.
After discussing this idea with people)
