### ISSUE TITLE
v8_monolith missing symbol

### ISSUE THREAD

**Issue by adaxiik** [armory3d/armorpaint#702]
Cant build krom.exe in visual studio
![image](https://user-images.githubusercontent.com/50113451/99415285-ef320d00-28f7-11eb-906a-a4c52079caf6.png)

error LNK2001: Unresolvable external symbol __tls_guard  etc..

Edit: I tried build older version and everything runs fine

**Comment by luboslenco** [comment]
Hello, thanks for report. Updating your Visual Studio should resolve the issue.
https://developercommunity.visualstudio.com/content/problem/1010557/-dyn-tls-on-demand-init-and-tls-guard-related-weir.html
