### ISSUE TITLE
There is a code error in the v8-internal.h file

### ISSUE THREAD

**Issue by MarcioVitor** [armory3d/armorpaint#703]
In Android Studio when compiling the project, it will inform that the field "std :: remove_cv_t <T>" does not exist

![image](https://user-images.githubusercontent.com/13188882/99442689-7bdccb00-28f8-11eb-9079-33e5ffce73ac.png)

However it can be solved by changing the part of the field to remove_cv

this "_t" should be removed in the android builds of armor paint

after doing this, the project compiled normally, I don't know if it is a compatibility error of the ".o" libraries of v8monolith android, but after doing this it solves everything

**Comment by luboslenco** [comment]
Thanks for letting me know. Found out the `-std=c++11` flag in `app/build.gradle` file has to be set to `-std=c++14` instead - that will get rid of the compile error. Once I am done implementing Android file picker I will finally automate this.

https://github.com/armory3d/armorcore/blob/master/kincfile.js#L87
