### ISSUE TITLE
EXR Export is broken

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#704]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2020-11-16) - e7daffb

**OS/device including version:**
Win64

**Issue description:**
The exr export produces either black images or some with strange pink artifacts

**Steps to reproduce:**
Export a 16 oder 32 bit exr texture and view the result in gimp/blender/...
We (@AlexKiryanov and me ) discovered this by a deeper investigation of #503. It seems to me that the handling of high bit depths is broken on some places.

**Comment by AlexKiryanov** [comment]
Thank you very much for a good experiment. I just looked at your report) I will write you the answer to your question.)
one head is good and 2 is better)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/657060583770fde294b4baf9ab87c79d80aca3c9, thanks for report!
