### ISSUE TITLE
Support dropping multiple files

### ISSUE THREAD

**Issue by tomcb1** [armory3d/armorpaint#71]
_Title edited (06-03-19). Old title was "Dragging and droping files into ArmorPaint 0.5 and 0.6dev causes a crash on Linux"_

Pretty much what the title said and I am not sure if this is a linux specific bug as I currently do not have a windows install to test on. 

Low quality gif here: ![untitled 2](https://user-images.githubusercontent.com/3697663/53653813-2227ff00-3c44-11e9-9652-b7a600be5b24.gif)

Info about my system:
`OS: Manjaro Linux x86_64`
`Kernel: 4.14.102-1-MANJARO`
`CPU: AMD FX-8320`
`GPU: NVIDIA GeForce GTX 1070`
`DE: KDE Plasma 5.15.1`

EDIT: Intrestingly drag and drop does work without flaw if I run the windows build through WINE

**Comment by luboslenco** [comment]
Hm, just tested on my Manjaro + xfce setup and it seems to work there. Maybe related to KDE? Will investigate, thanks for reporting it!

**Comment by tomcb1** [comment]
I found why I could not drag and drop files. I was trying to move file from a folder called "PBR assets". When I changed the name of this folder to "PBRassets" it worked without flaw meaning linux native ArmorPaint could not handle spaces in file paths while the windows version running on wine could.

For example the when the file path had a space:
`Could not open file /home/tomjb/Documents/PBR%20assets/[4K]Metal07/Metal07_col.jpg.`
The space would show up as a `%` sign. Hope this helps!

**Comment by SojanJanso** [comment]
I can confirm the same thing happens on Ubuntu 18.04.2 LTS.
For example when dragging textures in the node editor, it worked fine, unless the file, or one of the folders in it's path contained a space.

**Comment by luboslenco** [comment]
This was super helpful, thanks. Pushed a fix and uploaded new dev builds, please let me know if you get to re-test it.

**Comment by tomcb1** [comment]
I've retested this with the new 06dev build from gumroad and drag and drop functionality seems to be working fine with filepaths that include a space. Though I have also found that dragging and dropping multiple files will cause ArmourPaint 06dev to crash.

Here is the console output:
```Uniform N not found.
Uniform brushScale not found.
Uniform W not found.
Uniform eye not found.
Could not open file /home/tomjb/Documents/PBR assets/4KMetal07/Metal07_disp.jpg
file:///home/tomjb/Documents/PBR assets/4KMetal07/Metal07_met.jpg.
Could not open file /home/tomjb/Documents/PBR assets/4KMetal07/Metal07_disp.jpg
file:///home/tomjb/Documents/PBR assets/4KMetal07/Metal07_met.jpg.
```

**Comment by SojanJanso** [comment]
I can confirm it is also working for me in Ubuntu on the latest itch.io build.

**Comment by Daerst** [comment]
On Windows 10 / latest 0.6rc (9378b62), dropping multiple textures doesn't crash, but it doesn't work either. None of the textures shows up in the textures view.

**Comment by luboslenco** [comment]
Multiple files can be drag and dropped now at once.
