### ISSUE TITLE
Concept. New Mask system interface

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#710]
Good evening, Lubos! We have a proposal for a new interface for working with the mask system. Look please! In my video, I explain how the new approach to layer masks works.
https://youtu.be/4p0XrL5jaMw
I hope you appreciate our idea.
Thanks!

**Comment by jcostello** [comment]
@luboslenco I hope the proposal make sense and can help you with your current work on the mask layer. Also I think this could be a good place to discuse it so you can have a clear picture of what the people expects and what could be useful in terms of usability. What do you think?

**Comment by Rizzlord** [comment]
i think it is very well thought throu, would be awesome to see it in AP, but i dont know how much work it would be to implement it, but still very nice idea, would become very handy at texturing our models.

**Comment by jcostello** [comment]
@luboslenco any input on this one?

**Comment by luboslenco** [comment]
Will start working on it asap. 🔨

**Comment by jcostello** [comment]
@luboslenco Nice, I hope we helped with this on something. With @AlexKiryanov we discussed a lot how this could be useful for the users and he put a lot of work on the video to visually explain what we talked.
If you need help in any way, count with us. User input is really important to achieve the best product so count with us if you need :muscle:

**Comment by jcostello** [comment]
@luboslenco since you are working on this, talk to @AlexKiryanov or me if you want to have early feedback or try to see the best useful way to implement this for the users. We will love to contribute to it

**Comment by luboslenco** [comment]
Continuing to polish the new mask system in all the opened issues, big thanks for proposing this!

**Comment by AlexKiryanov** [comment]
I won't get tired of saying thank you! ))  thank you)

ср, 23 июн. 2021 г. в 14:13, Lubos Lenco ***@***.***>:

**Comment by jcostello** [comment]
Thank you @luboslenco and @AlexKiryanov. Great work
