### ISSUE TITLE
Particle brush upgrade

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#712]
Particle brush upgrade, add:
- Flow option
- Gravity direction
- Gravity strength
- Drips like https://youtu.be/bdvb8r5WC0g?t=10
- Spawn Speed
- Spawn Spread
- Spawn Rate Factor
- Add simulated physical orbs such as;
      https://youtu.be/g0MWFkl1d94?t=145
      https://youtu.be/6HMGx4NPL7U?t=124
      https://youtu.be/iSV116EyhwA?t=150

More options Particle brush like in Substance,

The current particle options are fun, but require more usability

**Comment by luboslenco** [comment]
Linking together with https://github.com/armory3d/armorpaint/issues/34.
