### ISSUE TITLE
Keep layers/textures when re-importing mesh

### ISSUE THREAD

**Issue by adanub** [armory3d/armorpaint#717]
Hi, currently when I re-import a mesh, it deletes all layers. I can of course work around this by exporting all of my texture layers before re-importing the mesh, then import the textures afterwards and apply them individually to newly created layers, but this is a pretty terrible workflow. There should be an option (preferably on by default, for a non-destructive approach) when importing a model to keep existing layers, as sometimes I need to make slight modifications to the mesh, while keeping the same uv unwrapping.

**Comment by luboslenco** [comment]
Hello, thanks for report. To just reimport the mesh, press `Menu bar - File - Reimport Mesh` (shortcut `ctrl + r`).
