### ISSUE TITLE
Spanish translation minimal error

### ISSUE THREAD

**Issue by Abash-esp** [armory3d/armorpaint#718]
Sorry for my error.
In the file: Assets/locale/es.json. on line: 308

change: "Axis": "Aje",
to: "Axis": "Eje",

**Comment by MathemanFlo** [comment]
If you change that, you could also add ... in  "Bake Material...": "Bakear Material", in line 332

**Comment by Abash-esp** [comment]
The ideal translation for "Bake" is "hornear", but in all the programs that I use, bake or bakear is used.
In this context, "bakear Material" would be fine.

would I really have to say "Bake to Texture"?  (Bake a Textura) or is it something else?

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/c7de8f59aee5ff29cbf9c32339f7933179da976c.
