### ISSUE TITLE
issues with v8_monolith.lib when  compiling 

### ISSUE THREAD

**Issue by Ulf3000** [armory3d/armorpaint#719]
Hello , im trying to compile on win10 64 with visual studio2019

everything goes fine till v8_monolith.lib is loaded:

it then throws about a thousand mismatch errors :

`v8_monolith.lib(default-platform.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj`

and fails with:

```
1>X:\C++ projects\armorpaint\armorcore\build\x64\Debug\Krom.exe : fatal error LNK1319: 1108 mismatches detected
1>Done building project "Krom.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

please help

**Comment by luboslenco** [comment]
Hello, thanks for report. Please build for the release mode like mentioned in the readme.

**Comment by Ladmen** [comment]
Hi, I had similar issue at first. I didn't set realease by mistake, but when i did it finally the banch of other problems appeared Ważność	Kod	Opis	Projekt	Plik	Wiersz	Stan pominięcia
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_1	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(objects.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_2	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(objects.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(heap-space.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(escape-analysis.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(load-elimination.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(zone-stats.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(runtime-test.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(sweeper.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(process-heap.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(graph.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(register-allocator.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(lazy-compile-dispatcher.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(materialized-object-store.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(marking-visitor.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(stats-collector.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(heap.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(isolate.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(log.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(sweeper.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_count_trivial_1	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(factory.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_find_trivial_4	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(wasm-objects.obj)	1	
Błąd	LNK2001	nierozpoznany symbol zewnętrzny __std_count_trivial_8	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\v8_monolith.lib(loop-analysis.obj)	1	
Błąd	LNK1120	liczba nierozpoznanych elementów zewnętrznych: 6	Armory	I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\build\x64\Release\Armory.exe	1	
Also I noticed the communicat : make --from ..\armorcore -g direct3d11
Using Kinc (cc564857) from I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore\Kinc
kfile found.
Creating Windows project files.
Using Kha from I:\5.INNE_PROGRAMY\ArmorPaint\armortools\armorcore
Neither Kha directory nor project file (khafile.js) found.
Compiling shader 1 of 2 (g1.frag).
Compiling shader 2 of 2 (g1.vert).
Done.
Can any of you tell me what I did wrong ? as can't find it in issue section
