### ISSUE TITLE
Armor Paint exe built by Visual Studio is not opening.

### ISSUE THREAD

**Issue by Mine-Ranger** [armory3d/armorpaint#720]
**ArmorPaint version:**
Master Branch cloned on 5 December 2020.

**OS/device including version:**

Using Windows 10 pro (up to date)
on Ryzen 5 3500 with rx 570 and 8 GB RAM

**Issue description:**

I followed all the steps written on Armor Paint's github page using dx 11
and I am using Visual Studio 2019 along with c++ development for desktop and windows 10 development.
The exe is generated by build solution and setting mode to release.
There are no errors but the exe does not run and not even open a window.
![ap](https://user-images.githubusercontent.com/75626127/101367986-a05f0e00-38cc-11eb-83e6-7b788526838d.png)

**Steps to reproduce:**

Follow the steps on the homepage with visual studio along with c++ development for desktop and windows 10 development.

**Comment by Abash-esp** [comment]
Copy the executable to armorpaint / build / krom and run it again.

**Comment by luboslenco** [comment]
Please run the git version directly from Visual Studio when possible so when you get a crash it's easy to report it. (Notice the step "Set `Project - Properties - Debugging - Command Arguments` to `..\..\build\krom`").
