### ISSUE TITLE
Can’t compile iOS version on xcode

### ISSUE THREAD

**Issue by gooeygreenmuffins** [armory3d/armorpaint#723]
**ArmorPaint version:**

Latest master branch

**OS/device including version:**

I’m using MacOS Catalina, with the latest xcode to build for an iOS target.

**Issue description:**

I followed directions, tried to build in xcode, and got an error “KINC_FUNC not defined”

**Steps to reproduce:**

Steps are in issue description.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorcore/commit/b4f98406c5053f9fd507faaeda87feb355026123, thanks for report!
