### ISSUE TITLE
Renaming a layer paints on it

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#724]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2020-12-14) - d884048 but the issue is not new

1. Double click on a material
2. Double click on a layer
3. Now as both are open the layer-name edit field is over the layer.
4. If any drawing related tool is selected: By selecting the edit field to rename the layer I unintentionally paint the object.

![armorpaint](https://user-images.githubusercontent.com/28649121/102123906-dc075400-3e47-11eb-9c2c-9f36bbbbed4d.jpg)

Finally one usability remark: I only found out by chance that I can rename layers in this view. Intuitively I would have expected this functionality on double click (obviously not applicable here) or on right click in the context menu. Maybe it would improve the usability to add a rename entry in the context menu.  It could either turn the Layer name into a edit field (similar to renaming objects in Blender) or open texture view and set the focus on the layer edit field?

**Comment by MathemanFlo** [comment]
Thank you for the nice double click layer rename feature. It is great. 
Merry Christmas 🎄 and thank you for your awsome work.
I wish you all the best

**Comment by infinder** [comment]
Right click menu initiates only if the cursor is exactly above layer name. Maybe a drop-dawn menu, like the blending one, is better. Otherwise a larger area for right clicking it would be more easy and efficient.
Merry Christmas and thank you for all your hard work

**Comment by luboslenco** [comment]
All should be well now, thanks for excellent feedback!

Want to tackle the last two issues for 0.8 release, updated the roadmap at https://github.com/armory3d/armorpaint/projects/4. I will do some "release candidate" before the final release so there is time to update translations. 🙂
