### ISSUE TITLE
Crash on Mode -> Material id

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#726]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2020-12-18) - 6936312

**OS/device including version:**
Win 10 x64

**Issue description:**
ArmorPaint crashes on Mode -> Material id

**Steps to reproduce:**
1. open ArmorPaint (the default cube is shown)
2. Clock Mode -> Material id

**Comment by luboslenco** [comment]
The immortal bug! Fix at https://github.com/armory3d/armorpaint/commit/20b775e5b0a3d1e09ff6fd069c97bb6583750909.

**Comment by MathemanFlo** [comment]
Now it works again and the bug died once again :-)

Am Fr., 18. Dez. 2020 um 11:50 Uhr schrieb Lubos Lenco <
notifications@github.com>:
