### ISSUE TITLE
Slightly incorrect handling of infinity values in material preview

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#727]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2020-12-18) - 20b775e

**OS/device including version:**
Win 10 x64

**Issue description:**
If the shader graph produces infinity values the material preview gets completely black but the material actually isn't completely black

**Steps to reproduce:**
Build the following situation:
![armorpaint](https://user-images.githubusercontent.com/28649121/102607702-ffbce980-4128-11eb-91f3-142fb6ce4207.jpg)
I think the color handling is correct but the preview of the material is not. A non zero value divided by 0 results in a white color and zero/zero results in black. I think this is okay. Of course this example is artificial but dividing two image textures is not completely stupid.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/e3188f4ef9b9e432439ef7f89284e44ebd78544b, thanks for report.
