### ISSUE TITLE
Shorten recent projects file names

### ISSUE THREAD

**Issue by adanub** [armory3d/armorpaint#728]
Hello, currently the "Recent Projects" menu shows the full path of the files, which means it often doesn't fit inside the window and I can't tell the files apart. Could this instead only show the file's name without the path, like most other applications? The path should be shown separately, like in a hover tooltip.

![image](https://user-images.githubusercontent.com/42713438/102678834-0c137600-41ff-11eb-8c94-0e8d763a28e7.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/f8c98587784ac3e7bd503d27b5a6aa595ebef8e8, thanks for report!
