### ISSUE TITLE
Please explain in some detail the Normal Bake workflow

### ISSUE THREAD

**Issue by ABS2021** [armory3d/armorpaint#729]
Please explain how the Normal Bake from a high poly mesh to a low poly one is supposed to work right now, from a user perspective.
I can not find any clear information on what has to be selected in the bake option, what has to be selected in the display option, where is the baked normal expected to appear and how to apply it/use it?
( or frankly any information on the bake at all, outside a couple of bad third-party videos) 

Please just explain this in text in a few simple, clear steps.
Thank you!

**Comment by luboslenco** [comment]
Hi, thanks for posting! There is a cool third-party video by Alexander at https://www.youtube.com/watch?v=Gsq20kQ6ddY.

Right now there are some issues to resolve which are reported at https://github.com/armory3d/armorpaint/issues/437. Once I address this I will make the interface less clunky and add a new video clip to the [how to](https://armorpaint.org/howto) section. To make it less clunky I started to move baking features into a separate workspace in the latest builds.

![bake](https://user-images.githubusercontent.com/3685704/102686881-f85e1480-41ea-11eb-9331-51e53457ecdf.png)


Sorry it's taking a while, working to make it better in the upcoming builds as soon as possible.

**Comment by ABS2021** [comment]
Thank you for the quick answer and looking forward to the improved version!
