### ISSUE TITLE
Request fur brush

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armorpaint#73]
It would be great to have a fur brush may be based on shell technique with physics enable that can be exported to armory :) may be in a far future :)

**Comment by adamearle** [comment]
Since its using blender it should be possible. 

What would be interesting is using hair to paint with and how few hairs you could get away with or set your own limit of hairs?

**Comment by luboslenco** [comment]
Putting priority onto core texture painting features for now. 🙂 I think some small scale beard/fur/hair should be doable with brush mask + normal/height map.
