### ISSUE TITLE
error displaying normal maps mode in the viewport.

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#730]
v0.8 (2020-12-20) - 20b775e
win 10 64 bit

Hello Lyubos! I noticed another problem with the display of the normal map in the viewport.
Here, take a look. There are many layers. But the point is that if one of the layers has a transparent background. Layer of gold. When it is turned on, only its normals are displayed. If you turn off the background, normal maps of other layers appear.
Roughly speaking. the viewport, mixing normal maps of all layers, ignores the alpha channel of the layer.
![1](https://user-images.githubusercontent.com/65244629/102761325-d0f07e80-4387-11eb-929e-4b626258fc60.jpg)
![2](https://user-images.githubusercontent.com/65244629/102761328-d221ab80-4387-11eb-973a-0515077a144e.jpg)
Thank you. Have a nice day)

**Comment by luboslenco** [comment]
Pushed some improvements at https://github.com/armory3d/armorpaint/commit/f476ffe08e06b94a2078dec7c84468120f950544, will need more testing but this issue should be resolved now.
