### ISSUE TITLE
Viewport on Mac keeps flickering  - Apple M1

### ISSUE THREAD

**Issue by ghost** [armory3d/armorpaint#731]
**ArmorPaint version:**

-ArmorPaint_08dev_mac.zip

**OS/device including version:**

-macOS Big Sur 11.1 
-Apple M1 chip Mac Mini 2020

**Issue description:**

-The viewport keeps flickering and I physically cannot look at it for very long.

https://user-images.githubusercontent.com/71099713/102933189-cd382700-446f-11eb-9b63-92f4e90f3481.mov

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Hello, thanks for report. I have tested on macOS 11.2.3 + mac mini m1 and it seems to work fine now. If the issue still persists for you please let me know.
