### ISSUE TITLE
Add support for retro/pixel art textures.

### ISSUE THREAD

**Issue by ca3games** [armory3d/armorpaint#732]
Hi, I just want to know if is possible to paint in a pixel art style in armor paint.

**Comment by luboslenco** [comment]
Hi, thanks for posting here. Please check the docs at https://armorpaint.org/manual to see currently available options. There is a way to configure viewport, lower the texture resolution, show texels and disable filtering. There is no pixel-precise pain tool (pencil) yet, but will eventually implement that as well.

![pixelart](https://user-images.githubusercontent.com/3685704/103079149-a135b680-45d3-11eb-952c-02790b8d1e60.jpg)
