### ISSUE TITLE
How to update ?

### ISSUE THREAD

**Issue by francis33** [armory3d/armorpaint#733]
Hi,

I bought the 0.7 version of the software at the end of the summer.
I would like to update with the new release (Windows 10 user).

How to do it ? It's not verry clear for me.

Happy christmas and thanks again for the soft !
Francis

**Comment by luboslenco** [comment]
Hello,

You can access the downloads at your [gumroad library](https://gumroad.com/library). If you did not register on Gumroad, then ArmorPaint will be auto-added to your library after you register with your email address.

You can also use the original email sent from Gumroad. If you let me know your email address (you can mail me [directly](https://armorpaint.org/community)) I can also resend it to you.

Many thanks for your support!
