### ISSUE TITLE
Weird Texture behavior

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#735]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2020-12-29) - e3188f4

**OS/device including version:**
Win64

**Issue description:**
ArmorPaint contains various textures (magic, voronoi, brick and so on). I realized that they behave differently and I don't know whether this is intentional or not. If it is maybe it would be helpful to add some notes to the manual.

**Steps to reproduce:**
Cube with rounded edges
![ap_brick](https://user-images.githubusercontent.com/28649121/103273313-4b8c5000-49bf-11eb-883a-edba74312d82.jpg)
![ap_magic](https://user-images.githubusercontent.com/28649121/103273318-4deeaa00-49bf-11eb-9506-8fab99e01e85.jpg)
![ap_checker](https://user-images.githubusercontent.com/28649121/103273321-50510400-49bf-11eb-80df-f114635a66f6.jpg)

Ordinary cube
![ap_cube_brick](https://user-images.githubusercontent.com/28649121/103273629-116f7e00-49c0-11eb-972c-47cf5da7aa3c.jpg)

**Comment by luboslenco** [comment]
Not intentional. 🙂 Linking together with https://github.com/armory3d/armorpaint/issues/36, want to make Cycles nodes 100% compatible.
