### ISSUE TITLE
Menu font is small when language is CJK and custom theme is set

### ISSUE THREAD

**Issue by shiena** [armory3d/armorpaint#736]
**ArmorPaint version:**

ArmorPaint.org - v0.8 (2020-12-29) - e3188f4

**OS/device including version:**

- Windows - Direct3D11
- NVIDIA GeForce GTX 1080 Ti  

**Issue description:**

Menu font is small when language is CJK and custom theme is set

**Steps to reproduce:**

1. Switch language to ja or zh_cn in preference
2. Switch theme to light in preference
3. Restart ArmorPaint

**default theme**
<img src="https://user-images.githubusercontent.com/1295639/103278735-8f0eaa80-4a0f-11eb-8ec7-9d4dfc326dad.png" width="30%">

**custome theme**
<img src="https://user-images.githubusercontent.com/1295639/103278767-a188e400-4a0f-11eb-9473-d1bc75d199eb.png" width="30%">

**Comment by luboslenco** [comment]
Should be fixed via https://github.com/armory3d/armorpaint/commit/e23b83b34230243e53d58423654ae03733c5c5cd, thanks.
