### ISSUE TITLE
Tooltip text height is low when language is CJK

### ISSUE THREAD

**Issue by shiena** [armory3d/armorpaint#738]
**ArmorPaint version:**

ArmorPaint.org - v0.8 (2020-12-30) - 194c734

**OS/device including version:**

- Windows - Direct3D11
- NVIDIA GeForce GTX 1080 Ti  

**Issue description:**

Tooltip text height is low when language is CJK

**Steps to reproduce:**

1. Switch language to ja or zh_cn in preference
2. Restart ArmorPaint
3. Hover the cursor over the toolbar icon

**Japanese**
![image](https://user-images.githubusercontent.com/1295639/103355987-0e28df00-4af3-11eb-833d-23bba5a6718f.png)

**Chinese**
![image](https://user-images.githubusercontent.com/1295639/103355997-14b75680-4af3-11eb-92f8-cc9e0f0a8901.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/zui/commit/5036a71cffadec23497d708409601c45dd9d643d.
