### ISSUE TITLE
Picker can't select a material if it has an emission value other than zero.

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#739]
Make some materials with different colors. Set one of them to have an emission value other than 0. Paint some areas with these materials and then try to pick each one of them with the picker tool. You can't select the one with the emission value.
ArmorPaint.org - v0.8 (2020-12-30) - 194c734
Windows10 - Direct3D11
Intel(R) HD Graphics 620

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/9da4f074def1ee01580758f8f076612cfd092ce5, thanks for report.
