### ISSUE TITLE
Cryengine integration

### ISSUE THREAD

**Issue by ArchonGnosis** [armory3d/armorpaint#740]
*ArmorPaint 0.8-7a1df6f, Windows*

Integration for a smoother workflow with Cryengine would be well received. Substance Painter has full integration with Cryengine. A Crytec staff member indicated that ArmorPaint devs had expressed interest in doing so. Hopeful anticipation all round.

**Comment by luboslenco** [comment]
Hello, thanks for the request! I am planning to do a Cryengine plugin eventually but right now it's too much for me to handle - I am hoping someone beats me to it, for example similar to how the Maya and Blender plugins are done. Help is welcome!

https://github.com/PiloeGAO/Maya-ArmorPaintLiveLink
https://github.com/PiloeGAO/Blender-ArmorPaintLiveLink
