### ISSUE TITLE
LNK2001 v8_monolith.lib error

### ISSUE THREAD

**Issue by AFWSI** [armory3d/armorpaint#741]
Getting a LNK2001 error. I've unzipped the v8_monolith.lib, so not sure what's causing this.

![v8_error](https://user-images.githubusercontent.com/24877571/103384127-dd2cb800-4aba-11eb-99d5-1c4770dbaf87.jpg)

**Comment by luboslenco** [comment]
See https://github.com/armory3d/armorpaint/issues/702.
