### ISSUE TITLE
Filtering multiple objects to be visible

### ISSUE THREAD

**Issue by adanub** [armory3d/armorpaint#742]
Hello, is it possible to filter out objects so that more than 1 (but not all) objects are visible?
![image](https://user-images.githubusercontent.com/42713438/103405507-84891800-4bab-11eb-89e5-7ad2b4796fd1.png)
This doesn't seem to be the case as far as I can tell - could this be implemented perhaps with checkboxes next to each object to toggle visibility?

On a similar note, the same thing being implemented for layer sharing between objects would be very useful!
![image](https://user-images.githubusercontent.com/42713438/103405634-d893fc80-4bab-11eb-8ba0-25eb7ec33abe.png)
Screenshots above aren't the best example as I have 2 objects in this case, but with more than 2 objects this would improve the workflow for texturing (at least for me, personally) a lot.

**Comment by luboslenco** [comment]
Hello, thanks for the request! Pushed some improvements.

Individual meshes can now be made visible / invisible in the `Meshes tab`.

![vis](https://user-images.githubusercontent.com/3685704/104635937-e5801800-56a2-11eb-8cc1-6d8bc3e6cb4c.PNG)

Meshes can be grouped into atlases at `File - Export textures... - Atlases tab`.

![1a](https://user-images.githubusercontent.com/3685704/104635985-f7fa5180-56a2-11eb-964e-506432f4a71a.PNG)

Afterwards, filter can be set to desired atlas, showing all the meshes which belong to the atlas.

![1b](https://user-images.githubusercontent.com/3685704/104635995-fa5cab80-56a2-11eb-947e-41cec868df72.PNG)

Layer object mask can be set to desired atlas, sharing the layer across all the meshes which belong to the atlas.

![1c](https://user-images.githubusercontent.com/3685704/104636003-fd579c00-56a2-11eb-93d0-a47687e15eca.PNG)
