### ISSUE TITLE
"Brick Texture" node "Color 2" input unusable?

### ISSUE THREAD

**Issue by mikesmullin** [armory3d/armorpaint#743]
**ArmorPaint version:**
`v0.8 (2020-12-31)` `ed9b206`

**OS/device including version:**
GeForce RTX 2080 Ti
Latest Studio drivers

**Issue description:**
I am surprised this has not been reported yet.
I saw it in this [YouTube video](https://youtu.be/Z4OyWeGbHPg?t=588)
I checked in the Github Issues history and could find no reference to it.
I compiled latest `master` branch on Windows and was able to reproduce the bug.

**Steps to reproduce:**
See image 
![image](https://user-images.githubusercontent.com/106222/103432149-433b3d00-4b98-11eb-91ac-e2a66cddbef1.png)

**What I was expecting:**
That setting the second color would cause some bricks to appear in the chosen color, for an alternating pattern, similar to what you get in Blender for the same node.

**Comment by mikesmullin** [comment]
We can see the input parameter `vec3 c2` is in scope but simply not used.

https://github.com/armory3d/armorpaint/blob/ed9b2066a3079b23e107d71edca16ee58a2a1531/Libraries/shaderlib/Sources/arm/shader/ShaderFunctions.hx#L160-L166

**Comment by mikesmullin** [comment]
A couple examples from Blender:

Cycles
https://github.com/blender/blender/blob/master/intern/cycles/kernel/shaders/node_brick_texture.osl#L82
https://github.com/blender/blender/blob/master/intern/cycles/kernel/svm/svm_brick.h#L101

Evee?
https://github.com/blender/blender/blob/master/source/blender/nodes/texture/nodes/node_texture_bricks.c#L80

**Comment by luboslenco** [comment]
https://github.com/armory3d/armorpaint/pull/744
