### ISSUE TITLE
Pen preassure is not working on linux.

### ISSUE THREAD

**Issue by yosoyfreeman** [armory3d/armorpaint#745]
**ArmorPaint version:**
0.8 official non ray traced build.

**OS/device including version:**
Linux (Pop OS)

**Issue description:**
There is no recognition of the pen pressure even with the options activated.

**Steps to reproduce:**
Open Armor paint, use the pen.

**Comment by luboslenco** [comment]
Hello, thanks for letting me know. Unfortunately the pressure seems to be fine on my Wacom Intuos S + Ubuntu - I will get ahold of more tablet hardware, investigate and hopefully bring a fix soon. Which hardware are you on? I have also sent you a refund, sorry for trouble. Continuing at similar issue at https://github.com/armory3d/armorpaint/issues/707.

**Comment by yosoyfreeman** [comment]
HI! i really apreciate you honesty, but i found a fix the last night! the
problem now is that i live in spain, so i paied extra taxed, around 23
euros in total (25 bucks) but i got a refund of 16 dollars. Can you restore
my purcharse so i have no to pay that taxes again? i viewed all your
tutorials and i really liking the tool! hope it can be fixed cause i have
no much money and that taxes are big for me. Thanks for your help!

**Comment by yosoyfreeman** [comment]
this is the exact price i paied
[image: imagen.png]

**Comment by yosoyfreeman** [comment]
Okay, i has been researching and looks like i lost the taxes. gumroad can
only refund the value of the pay you get and i dont want to make you lost
money. So i wil be saving some money and i will be purcharsing as soon i
can. Please, respond to this emails if you read them so i know is safe to
purchase again without make you think it was an error on the refund or
something and you refund it again xD

have a nice day!

**Comment by edap** [comment]
I can confirm that the problem happens only with non-wacom tablets. I have a Wacom Intuos M and the pen prossure is working, but it is not working on an XP-Pen Artist tablet.
