### ISSUE TITLE
Automatically enable plugin on associated file import

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#749]
I wonder whether it would be a good idea to automatically enable the tiff-plugin (or at least to auto enable it on first tiff file load) or to include tiff support as core feature. I think an ordinary user would never expect to be able to import png, jpg, bmp but not tif and it seems to me counter inituitive to look into Plugins to enable the support.  I totally understand it for all other formats like stl as it is relatively uncommon for texture painting (due to its lack of uv map support)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/43562d6079d3c209266f7d4cf7635133cd9c0201, thanks for suggestion.
