### ISSUE TITLE
Error When running Armory Paint on Linux

### ISSUE THREAD

**Issue by Adeelasd** [armory3d/armorpaint#75]
I am getting this error
Uniform N not found.
Uniform brushScale not found.
Uncaught exception:
	sphere.visible = true;
	^
TypeError: Unable to set property 'visible' of undefined or null reference
   at arm_util_RenderUtil.makeMaterialPreview (krom.js:9366:2)
   at Anonymous function (krom.js:6798:4)
   at iron_App.render (krom.js:14706:4)
   at kha_System.render (krom.js:41748:3)
   at kha_SystemImpl.renderCallback (krom.js:41874:2)

**Comment by luboslenco** [comment]
Hello @Adeelasd, which ArmorPaint version are you on?

**Comment by Adeelasd** [comment]
the latest one downloaded a few hours ago

**Comment by luboslenco** [comment]
Unable to reproduce here so far.:( Do you get that error immediately on startup?

**Comment by Adeelasd** [comment]
no after compiling it
![screenshot_20190308_221738](https://user-images.githubusercontent.com/38320190/54044161-14e4b480-41f0-11e9-978a-5e601c78f250.png)

**Comment by Adeelasd** [comment]
Complete Log:
Armory v0.7 ($Id: f618d47c6cfb765b981cc21677d775fc25786df8 $)
OS: linux, Target: krom, GAPI: opengl, Blender: 2.80 (sub 44)
Exporting Scene
Scene exported in 0.009796857833862305
Exported modules: ['ui', 'format']
Shader flags: ['_Irr', '_EnvTex', '_Rad', '_EnvStr', '_Deferred', '_LTC', '_SinglePoint', '_Brdf', '_SMAA', '_Veloc', '_SSAO', '_gbuffer2', '_CGrainStatic']
Running:  ['/home/adeel/armorpaint/Armory/armsdk//nodejs/node-linux64', '/home/adeel/armorpaint/Armory/armsdk//Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--parallelAssetConversion', '4', '--to', 'build_armorpaint/debug']
Using project from /home/adeel/armorpaint
Using Kha from /home/adeel/armorpaint/Armory/armsdk/Kha
Creating Kha project.
Warning: No haxelib.json and no Sources directory found in library paint.
Exporting asset 1 of 22 (Scene.arm).
Exporting asset 2 of 22 (cay_irradiance.arm).
Exporting asset 3 of 22 (cay_radiance.hdr).
Exporting asset 4 of 22 (cay_radiance_0.hdr).
Exporting asset 5 of 22 (cay_radiance_1.hdr).
Exporting asset 6 of 22 (cay_radiance_2.hdr).
Exporting asset 7 of 22 (cay_radiance_3.hdr).
Exporting asset 8 of 22 (cay_radiance_4.hdr).
Exporting asset 9 of 22 (cay_radiance_5.hdr).
Exporting asset 10 of 22 (cay_radiance_6.hdr).
Exporting asset 11 of 22 (cay_radiance_7.hdr).
Exporting asset 12 of 22 (cay_radiance_8.hdr).
Exporting asset 13 of 22 (cay_radiance_9.hdr).
Exporting asset 14 of 22 (mesh_Cube.007.arm).
Exporting asset 15 of 22 (mesh_Cube.009.arm).
Exporting asset 16 of 22 (mesh_Cube.010.arm).
Exporting asset 17 of 22 (mesh_Cube.012.arm).
Exporting asset 18 of 22 (mesh_Cube.arm).
Exporting asset 19 of 22 (mesh_Cylinder.001.arm).
Exporting asset 20 of 22 (mesh_Cylinder.arm).
Exporting asset 21 of 22 (mesh_Plane.arm).
Exporting asset 22 of 22 (mesh_Sphere.arm).
Exporting asset 1 of 5 (Gizmo_data.arm).
Exporting asset 2 of 5 (Material2_data.arm).
Exporting asset 3 of 5 (Material_data.arm).
Exporting asset 4 of 5 (armdefault_data.arm).
Exporting asset 5 of 5 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise256.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (cay.hdr).
Exporting asset 1 of 1 (authors.md).
Exporting asset 1 of 1 (cmft-linux64).
Exporting asset 1 of 1 (cmft-osx).
Exporting asset 1 of 1 (cmft.exe).
Exporting asset 1 of 1 (license_cmft.md).
Exporting asset 1 of 1 (color_wheel.png).
Exporting asset 1 of 1 (config.arm).
Exporting asset 1 of 1 (cursor.png).
Exporting asset 1 of 1 (default_brush.json).
Exporting asset 1 of 1 (default_logic.json).
Exporting asset 1 of 1 (default_material.json).
Exporting asset 1 of 1 (drag.png).
Exporting asset 1 of 1 (empty.jpg).
Exporting asset 1 of 1 (tool_bake.png).
Exporting asset 1 of 1 (tool_colorid.png).
Exporting asset 1 of 1 (tool_decal.png).
Exporting asset 1 of 1 (tool_draw.png).
Exporting asset 1 of 1 (tool_eraser.png).
Exporting asset 1 of 1 (tool_fill.png).
Exporting asset 1 of 1 (tool_gizmo.png).
Exporting asset 1 of 1 (tool_particle.png).
Exporting asset 1 of 1 (tool_shape.png).
Exporting asset 1 of 1 (tool_text.png).
Exporting asset 1 of 1 (license.md).
Exporting asset 1 of 1 (logic_nodes.json).
Exporting asset 1 of 1 (noise64.png).
Exporting asset 1 of 1 (plugin_hello.js).
Exporting asset 1 of 1 (plugin_rotate.js).
Exporting asset 1 of 1 (readme.txt).
Exporting asset 1 of 1 (theme_dark.arm).
Exporting asset 1 of 1 (theme_light.arm).
Exporting asset 1 of 1 (font_default.ttf).
Compiling shader 1 of 35 (Gizmo_overlay.frag.glsl).
Compiling shader 2 of 35 (Gizmo_overlay.vert.glsl).
Compiling shader 3 of 35 (Material2_mesh.frag.glsl).
Compiling shader 4 of 35 (Material_mesh.frag.glsl).
Compiling shader 5 of 35 (Material_mesh.vert.glsl).
Compiling shader 6 of 35 (armdefault_mesh.frag.glsl).
Compiling shader 7 of 35 (armdefault_mesh.vert.glsl).
Compiling shader 8 of 35 (armdefault_voxel.frag.glsl).
Compiling shader 9 of 35 (armdefault_voxel.geom.glsl).
Compiling shader 10 of 35 (armdefault_voxel.vert.glsl).
Compiling shader 11 of 35 (bloom_pass.frag.glsl).
Compiling shader 12 of 35 (blur_adaptive_pass.frag.glsl).
Compiling shader 13 of 35 (blur_edge_pass.frag.glsl).
Compiling shader 14 of 35 (blur_gaus_pass.frag.glsl).
Compiling shader 15 of 35 (compositor_pass.frag.glsl).
Compiling shader 16 of 35 (compositor_pass.vert.glsl).
Compiling shader 17 of 35 (copy_mrt3_pass.frag.glsl).
Compiling shader 18 of 35 (copy_mrt4_pass.frag.glsl).
Compiling shader 19 of 35 (deferred_light.frag.glsl).
Compiling shader 20 of 35 (pass.vert.glsl).
Compiling shader 21 of 35 (pass_copy.frag.glsl).
Compiling shader 22 of 35 (pass_viewray.vert.glsl).
Compiling shader 23 of 35 (pass_viewray2.vert.glsl).
Compiling shader 24 of 35 (smaa_blend_weight.frag.glsl).
Compiling shader 25 of 35 (smaa_blend_weight.vert.glsl).
Compiling shader 26 of 35 (smaa_edge_detect.frag.glsl).
Compiling shader 27 of 35 (smaa_edge_detect.vert.glsl).
Compiling shader 28 of 35 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 29 of 35 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 30 of 35 (ssgi_pass.frag.glsl).
Compiling shader 31 of 35 (ssr_pass.frag.glsl).
Compiling shader 32 of 35 (supersample_resolve.frag.glsl).
Compiling shader 33 of 35 (taa_pass.frag.glsl).
Compiling shader 34 of 35 (world_pass.frag.glsl).
Compiling shader 35 of 35 (world_pass.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Finished in 4.957830429077148
Uniform N not found.
Uniform brushScale not found.
Uncaught exception:
	sphere.visible = true;
	^
TypeError: Unable to set property 'visible' of undefined or null reference
   at arm_util_RenderUtil.makeMaterialPreview (krom.js:9366:2)
   at Anonymous function (krom.js:6798:4)
   at iron_App.render (krom.js:14706:4)
   at kha_System.render (krom.js:41748:3)
   at kha_SystemImpl.renderCallback (krom.js:41874:2)

GL Error 1282 ../../Kore/Backends/Graphics4/OpenGL/Sources/Kore/RenderTargetImpl.cpp 166

Uniform brushScale not found.
Uncaught exception:
	sphere.visible = true;
	^
TypeError: Unable to set property 'visible' of undefined or null reference
   at arm_util_RenderUtil.makeMaterialPreview (krom.js:9366:2)
   at Anonymous function (krom.js:6798:4)
   at iron_App.render (krom.js:14706:4)
   at kha_System.render (krom.js:41748:3)
   at kha_SystemImpl.renderCallback (krom.js:41874:2)

Uniform brushScale not found.
Uncaught exception:
	sphere.visible = true;

**Comment by luboslenco** [comment]
It looks like the .blend file is somehow wrong in your git clone, but I am not sure why. Or something goes wrong when exporting the `.Sphere` object, but so far it passes ok here. Will post if I discover more details.

**Comment by luboslenco** [comment]
Compiled fresh Linux build on Friday but did not manage to reproduce this issue, hopefully it's ok now.
