### ISSUE TITLE
Curvature map is nor working in custom models imported from blender. 

### ISSUE THREAD

**Issue by yosoyfreeman** [armory3d/armorpaint#751]
**ArmorPaint version:**
0.8 non ray tracing.

**OS/device including version:**
POP-os LInux (Ubuntu)

**Issue description:**
curvature is not detected when importing models from blender 2.91 to armor paint 0.8

**Steps to reproduce:**
Open blender, export the default cube to obj. Import in armor paint, try to bake curvature. All is black.
(I tested too with a smoothed cube and some random objects)

I tried all the possible combinations on exporting, but i cant make it works. All the other bakes works fine. 

Maybe there are some conditions neccesary to work that i cant find on the documentation? Nice day!

**Comment by luboslenco** [comment]
Many thanks for report, will investigate, linking together with https://github.com/armory3d/armorpaint/issues/696.
