### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by masi1515** [armory3d/armorpaint#756]
Hello, I have some errors :( any help? 

..
1>pipeline.c
1>mouse.c
1>http.c
1>   Creating library C:\temp\armorpaint\armorcore\build\x64\Release\Krom.lib and object C:\temp\armorpaint\armorcore\build\x64\Release\Krom.exp
1>v8_monolith.lib(runtime-test.obj) : error LNK2001: unresolved external symbol __dyn_tls_on_demand_init
1>v8_monolith.lib(runtime-wasm.obj) : error LNK2001: unresolved external symbol __dyn_tls_on_demand_init
1>v8_monolith.lib(execution.obj) : error LNK2001: unresolved external symbol __dyn_tls_on_demand_init
1>v8_monolith.lib(isolate.obj) : error LNK2001: unresolved external symbol __dyn_tls_on_demand_init
1>v8_monolith.lib(handler-outside.obj) : error LNK2001: unresolved external symbol __dyn_tls_on_demand_init
1>v8_monolith.lib(handler-inside-win.obj) : error LNK2001: unresolved external symbol __dyn_tls_on_demand_init
1>v8_monolith.lib(runtime-test.obj) : error LNK2001: unresolved external symbol __tls_guard
1>v8_monolith.lib(runtime-wasm.obj) : error LNK2001: unresolved external symbol __tls_guard
1>v8_monolith.lib(execution.obj) : error LNK2001: unresolved external symbol __tls_guard
1>v8_monolith.lib(isolate.obj) : error LNK2001: unresolved external symbol __tls_guard
1>v8_monolith.lib(handler-outside.obj) : error LNK2001: unresolved external symbol __tls_guard
1>v8_monolith.lib(handler-inside-win.obj) : error LNK2001: unresolved external symbol __tls_guard
1>C:\temp\armorpaint\armorcore\build\x64\Release\Krom.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "Krom.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by luboslenco** [comment]
See https://github.com/armory3d/armorpaint/issues/702.

**Comment by masi1515** [comment]
> See #702.

thanks. it works
