### ISSUE TITLE
Importing files on Android doesnt seem to work

### ISSUE THREAD

**Issue by brian-uplevel** [armory3d/armorpaint#757]
**ArmorPaint version:**

ArmorPaint_08dev_android64.zip

**OS/device including version:**

Samsung Galaxy Note 9

**Issue description:**

I enabled storage settings for the app, but the file explorer doesn't allow me to import or export anything. I can't access my SD card to look for directories or files. 

**Steps to reproduce:**

Open armor paint app. Select import mesh. No files or directories appear in browser.

**Comment by jigenMal** [comment]
Same issue on a Galaxy Tab S7+ with Android 10. Enabled memory permission but I can see only a "sdcard" folder. Any attempt to export (meshes, brushes, console log...) says OK but does nothing. Looking for saved file names or "armorpaint" on the device shows no result.

**Comment by luboslenco** [comment]
I have updated the `ArmorPaint_08dev_android64.zip` builds.
- ArmorPaint will ask for storage permission upon startup (no need to manually enable storage permission in the settings)
- Fixed listing the files in Browser tab
- Importing files will summon the native android file picker

Thanks for report!
