### ISSUE TITLE
Node editor font is small in CJK language

### ISSUE THREAD

**Issue by shiena** [armory3d/armorpaint#758]
**ArmorPaint version:**

ArmorPaint.org - v0.8 (2021-01-08) - a0eb673

**OS/device including version:**

Windows - Direct3D11
NVIDIA GeForce GTX 1080 Ti  

**Issue description:**

Node editor font is small in CJK language

**Steps to reproduce:**

1. Switch language to ja or zh_cn in preference
1. Open Material Node Editor or Brush Node Editor

<img src="https://user-images.githubusercontent.com/1295639/103968953-37f39d00-51a8-11eb-8047-43acd2726d32.png" width=50%>

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/5d64c2991c3e207bc01f3f29858c468ef7683ccb.
