### ISSUE TITLE
4K texture gets pixelated? (Following Video tutorial)

### ISSUE THREAD

**Issue by SimonClider** [armory3d/armorpaint#764]
https://www.youtube.com/watch?v=mkcFpaudl8U
I was following this Video Tutorial with the latest version(0.8) I followed everything(except doing the UV smart unwrapping since the 3d Model provided already had it's UV unwrapped and for some reason when I do the UV smart unwrapping it unwrapps weirdly)
for some reason when I import the texture it appears pixelated?
I first used 1K but it came out pixelated so I did it again but using the 4K texture but still have same problem.
Textures I used are 4k PNG
https://cc0textures.com/view?id=Metal021
https://cc0textures.com/view?id=Metal037
![image](https://user-images.githubusercontent.com/77374256/104407443-98c80000-552f-11eb-801f-c5cc80bb4486.png)

Is this a Bug or is there an option where I can change the Texture size manually? Thank you.

**Comment by luboslenco** [comment]
Hello, thanks for report. Yes, the layer resolution can be changed in the `Layers tab` - setting it to 4K should help.

![res](https://user-images.githubusercontent.com/3685704/104425794-634c0280-5581-11eb-948f-a6d41576aeb5.PNG)

**Comment by SimonClider** [comment]
![image](https://user-images.githubusercontent.com/77374256/104525446-2ce8a480-55ce-11eb-987c-1915383af61d.png)
I change the texture resolution to 4k yet It still appears to be Pixelated?

**Comment by luboslenco** [comment]
Looks like it's a bit better compared to the original image, but I assume the resolution is still too low. When I look at the layer preview in your screenshot the painted part appears to be tiny, is the UV map evenly distributed? Do you get better results if you skip the height map?

> And when I chagne the Color to 32Bit, the Whole Program just crashes

Sorry I need more details to be helpful. How much gpu memory do you have? What ArmorPaint version are you using? Does 2K + 32Bit work?

**Comment by SimonClider** [comment]
I guess it was the Height  map that makes it look pixelated, using 4K texture with 4K size res looks better without Height map 
![image](https://user-images.githubusercontent.com/77374256/104794240-580cf880-5774-11eb-885b-d92d85f4015e.png)
as long as I don't zoom in too much it looks okay ish other than UV sceme(likely cause I didn't do proper UVing)

My Graphic Card is
![image](https://user-images.githubusercontent.com/77374256/104794288-a4583880-5774-11eb-83e6-a316810c08c3.png)
I believe this is 8GB memory
CPU:Ryzen 1700   Ram:32gb

![image](https://user-images.githubusercontent.com/77374256/104794374-3bbd8b80-5775-11eb-922c-19197bca5d5d.png)
2K res +32bit seems to work but program is slightly studdering?(from time to time)

When changed to 4k res + 32bit, it crashed first time
2nd attempt it froze for 3 minutes or so but it works, but program struggles and frame dropps to like 2-3 fps ish

4k Res + 16bit seems to work but shows same result of 2K + 32bit frame drop from time to time

**Comment by luboslenco** [comment]
👍👍 Looking into it, thanks for additional info.

**Comment by philippeflorent** [comment]
same here, downloaded pbr high res textures from cc0texture.com applying as is, and it appears pixelated
![image](https://user-images.githubusercontent.com/118295975/208489173-9bbe32b7-9b70-412a-8468-077da84cc2c9.png)
