### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by artnorab** [armory3d/armorpaint#765]
Please let ArmorPaint be the first alternative to expensive/intrusive software for Blender artists who want to do hand painted style texture : add an actual color picker based on base color. 

**EDIT:** Well, I guess I was wrong when I thought I was buying "3D texture painting" software.  I watched videos to make sure that the necessary tools were present and I thought it was OK but now I see that some important tools are missing : no configurable shortcuts for pen (e.g. emulate mouse in blender), no "drag shortcuts" for brush size, no color picker. These three missing functions alone make actual texture painting impossible.

I should have been more careful before buying so that's too bad for me. However, the software is excellent for this price even if I don't need it as is.

**Comment by luboslenco** [comment]
Hello, thanks for report. Working on further color picker improvements at https://github.com/armory3d/armorpaint/issues/275. To scale the brush by dragging hold the `f` key. The key can be remapped at `Edit - Preferences... - Keymap`, it's tagged as `brush_radius` (and related shortcuts are `brush_opacity`, `brush_angle`).

> I should have been more careful before buying so that's too bad for me. However, the software is excellent for this price even if I don't need it as is.

Please email me with the email you used, it's perfectly valid to get a refund. 👍

**Comment by artnorab** [comment]
Thank you for the answer.

The shortcut works great (I thought I just had to press it once like in Blender). I will not ask for a refund. I rarely get the chance to support independent developers because I have a limited budget so I'm happy to contribute to this project. I will wait for the implementation of the color picker to get started on the software :)

**Comment by Granada1** [comment]
At the price it is I was happy to pay at the start and wait for feature updates 😀
