### ISSUE TITLE
4K texture gets pixelated?(even after change the Resolution and changing Color from 8bit to 32bit crashes the app)

### ISSUE THREAD

**Issue by SimonClider** [armory3d/armorpaint#766]
This is follow up of https://github.com/armory3d/armorpaint/issues/764
I left comment but haven't got any response(Im assuming because it was closed)
![image](https://user-images.githubusercontent.com/77374256/104679575-f9844380-56bb-11eb-8f5f-44e6a6870b32.png)
I change the texture resolution to 4k yet It still appears to be Pixelated?
And when I chagne the Color to 32Bit, the Whole Program just crashes

**Comment by luboslenco** [comment]
https://github.com/armory3d/armorpaint/issues/764#issuecomment-760718481
