### ISSUE TITLE
Cant launch new version via visual studio 2019

### ISSUE THREAD

**Issue by masi1515** [armory3d/armorpaint#768]
Everything was successful but when I click Local Windows Debugger to launch AP, this appears in the output log of VS19. See below.

'Krom.exe' (Win32): Loaded 'C:\temp\armorpaint\armorcore\build\x64\Release\Krom.exe'. Symbols loaded.
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Program Files\AVAST Software\Avast\aswhook.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\D3DCompiler_47.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dinput8.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dbghelp.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\InputHost.dll'. 
Could not load krom.js, aborting.
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
The thread 0x3598 has exited with code 1 (0x1).
The program '[18912] Krom.exe' has exited with code 1 (0x1).

**Comment by luboslenco** [comment]
See https://github.com/armory3d/armorpaint/issues/256#issuecomment-574209774.

**Comment by masi1515** [comment]
solved
