### ISSUE TITLE
Crazy Bugs on linux - Many layers

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#770]
Crazy Bugs on linux - Many layers, like on screans:

![image](https://user-images.githubusercontent.com/69405892/104939241-7828fb80-59b0-11eb-9f98-9829f22d5c6c.png)
![image](https://user-images.githubusercontent.com/69405892/104939283-86771780-59b0-11eb-926f-470dbcfe7c31.png)
![image](https://user-images.githubusercontent.com/69405892/104939329-92fb7000-59b0-11eb-963d-1c34c6a2d64b.png)

Layers incorrect painted (correct selected elements),
Layers is transparently when not should be transparentetc.
Crazy OMG

ArmorPaint.org - v0.8 (2021-01-15) - 30aff91

**Comment by luboslenco** [comment]
I really need the steps to reproduce the issue so I can fix it, sorry. Please also post the test files whenever possible and I am happy to investigate, thanks.
