### ISSUE TITLE
.blend file import wrong normals

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#771]
Added tested files:
[testModel.blend.zip](https://github.com/armory3d/armorpaint/files/5831446/testModel.blend.zip)
i cannot attach arm test model beacouse Github allow 10MB, file with zipped have ~80MB
external source 30 days available: https://easyupload.io/deizfo

Like on screans:
![image](https://user-images.githubusercontent.com/69405892/104941385-4a918180-59b3-11eb-98d2-48a46c84d866.png)
![image](https://user-images.githubusercontent.com/69405892/104941466-67c65000-59b3-11eb-8f51-8ba6024ca93b.png)
![image](https://user-images.githubusercontent.com/69405892/104941642-9e03cf80-59b3-11eb-909f-9e7de09e28b0.png)
![image](https://user-images.githubusercontent.com/69405892/104941706-b1af3600-59b3-11eb-89da-a9d9eba4e905.png)
![image](https://user-images.githubusercontent.com/69405892/104941739-bc69cb00-59b3-11eb-8b5e-33943292212e.png)

Layers incorrect painted (correct selected elements),
Layers is transparently when not should be transparentetc.
Crazy OMG

ArmorPaint.org - v0.8 (2021-01-15) - 30aff91

**Comment by luboslenco** [comment]
Thanks! Pushed some fixes at https://github.com/armory3d/armorpaint/commit/8de0ef8c69e25e701e7a7e25759132f2fc56c888 https://github.com/armory3d/armorpaint/commit/c917e78e4ddb77f58bc3b8d4e025ca907579005b https://github.com/armory3d/armorpaint/commit/f2194f508fb7c4208d850e6458b894a3e7aa6c73, new builds up soon.
