### ISSUE TITLE
Build fails on Windows VR version

### ISSUE THREAD

**Issue by shiena** [armory3d/armorpaint#772]
**ArmorPaint version:**

f25b8857edef77fbce37f6f658f4dec76c9e7d36

**OS/device including version:**

Windows - Direct3D11
NVIDIA GeForce GTX 1080 Ti

**Issue description:**

Build fails on Windows VR version

**Steps to reproduce:**

1. node armorcore\make -g direct3d11 --vr oculus
2. pushd armorcore
3. git apply patch/window_handling.diff --directory=Kinc
4. node Kinc\make -g direct3d11 --vr oculus
5. popd
6. msbuild armorcore\build\Krom.sln -property:Configuration=Release -verbosity:diag

```
"C:\Users\shiena\dev\armorpaint\armorcore\build\Krom.sln" (既定のターゲット) (1) ->
"C:\Users\shiena\dev\armorpaint\armorcore\build\Krom.vcxproj" (既定のターゲット) (2) ->
(Link ターゲット) ->
  VrInterface_Oculus.obj : error LNK2001: 外部シンボル "void __cdecl Kore::log(enum Kore::LogLevel,char const *,...)" (?log@Kore@@YAXW4LogLevel@1@PEBDZZ) は未解決です [C:\Users\shiena\dev\armorpaint\armorcore\build\Krom.vcxproj]
  C:\Users\shiena\dev\armorpaint\armorcore\build\x64\Release\Krom.exe : fatal error LNK1120: 1 件の未解決の外部参照 [C:\Users\shiena\dev\armorpaint\armorcore\build\Krom.vcxproj]
```

**Comment by luboslenco** [comment]
Fix at https://github.com/Kode/Kinc/pull/595, thanks for report.
