### ISSUE TITLE
Build instructions for Linux seem outdated

### ISSUE THREAD

**Issue by prokoudine** [armory3d/armorpaint#775]
The suggested command `./Krom ../../build/krom` for Linux seems outdated, there is simply no such path when you run it from `Deployment` as suggested.

Now, I _can_ run `./Krom ../build/Krom` but:

`Could not load krom.js, aborting.`

There is simply no such file in all of ArmorPaint's source code tree, all git submodules included:

```
~/s/3/armorpaint (master)> find . -name *js
./khafile.js
./Libraries/zui/examples/FileBrowser/khafile.js
./Libraries/zui/examples/MultipleWindows/khafile.js
./Libraries/zui/examples/ColorWheel/khafile.js
./Libraries/zui/examples/Elements/khafile.js
./Libraries/zui/examples/Scaling/khafile.js
./Libraries/zui/examples/Nodes/khafile.js
./Libraries/zui/examples/Canvas/khafile.js
```

**Comment by luboslenco** [comment]
Hello, thanks for report. The `krom.js` file is generated by the `node armorcore/make -g opengl` command mentioned in the instructions, it is not part of a git repository. Let me know if the issue persists.
