### ISSUE TITLE
Path error when importing brushes with image texture - Linux

### ISSUE THREAD

**Issue by spellmell** [armory3d/armorpaint#776]
![armorpaint_import_brush_img_route_error](https://user-images.githubusercontent.com/77791463/105364532-07662700-5bdc-11eb-8f3d-7ef2ce6beb10.png)
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-01-20) - 30aff91
Linux - OpenGL

**OS/device including version:**
Fedora 32

**Issue description:**
Importing previously exported .arm brushes, produces a path error when looking for the mask of the image texture node.

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/82cd250c09a1fd2783292973874cfb369263726c, thanks for report!

**Comment by spellmell** [comment]
![path_error_persist_in_import_brush_with_image_texture_node](https://user-images.githubusercontent.com/77791463/105624306-8d15ec80-5dff-11eb-9c17-e94c6d594eb3.png)
I updated the installation with:
git pull origin master
git submodule update --init --recursive
but the problem persisted.
then I completely removed the previous installation
i re-downloaded by git everything completely and re-compiled
and the problem still persists...
ArmorPaint.org - v0.8 (2021-01-24) - 1fa27a9
is it possible that the error is that the path to the png mask is not the same as the path to the saved .arm brush?
i have the png masks files in: /mnt/trabajo/ArmorPaint/Brushes/png
and the saved brush in:  /mnt/trabajo/ArmorPaint/Brushes/pinceles_ok.
It would be interesting to have an default folder where to have saved brushes and materials to automatically imported when starting the program, or a configuration file where to set the paths.

**Comment by spellmell** [comment]
![path_error_persist_in_import_brush_with_image_texture_node_02](https://user-images.githubusercontent.com/77791463/105624643-32ca5b00-5e02-11eb-9fcd-4527b3f7998e.png)
the brush only work if i delete failed pinked mask and re import png brush mask images

**Comment by spellmell** [comment]
Hi again... I'm "thinking" about this... is it not a possibility to package the png image mask into the .arm exported brush file, as an asset, in a similar way how blender automatically pack external data into .blend files? ... maybe this can be more useful, for sharing the exported brushes without need also add png files or subdirectories whit other people. is only an idea. thank you for your work, I really appreciate this.

**Comment by luboslenco** [comment]
Thanks for letting me know. Did you re-export the `apb_ink_35.arm` file using the latest build? (it needs to be re-created, sorry)

> It would be interesting to have an default folder where to have saved brushes and materials to automatically imported when starting the program

Will eventually make it possible to over-write the default project.

> is it not a possibility to package the png image mask into the .arm exported brush file, as an asset

Yes, coming soon. 🙂

**Comment by spellmell** [comment]
![re_exported_imported_brush_working](https://user-images.githubusercontent.com/77791463/105637389-1521e380-5e4c-11eb-9fda-820cb1b4b4db.png)
yes, re-exporting and importing now works fine. I hadn't thought of that little detail, lol. sorry. seems solved. thank you!

**Comment by luboslenco** [comment]
Yay, happy to hear. Looks cool! I have also exposed the `Pack Assets` option now at https://github.com/armory3d/armorpaint/commit/be7346c2b43a1c561b9abbc153a21b687ebcfeeb when exporting materials and brushes, but still needs a bit more work - looks like non power-of-two textures get packed wrong.

**Comment by spellmell** [comment]
> Yay, happy to hear. Looks cool! I have also exposed the `Pack Assets` option now at [be7346c](https://github.com/armory3d/armorpaint/commit/be7346c2b43a1c561b9abbc153a21b687ebcfeeb) when exporting materials and brushes, but still needs a bit more work - looks like non power-of-two textures get packed wrong.

sounds good, I'll try update again for try it. thx
