### ISSUE TITLE
Not shows all layers - Linux

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#777]
Not shows all layers
This behaves weird, it should generally show everything except "hidden", there are no hidden layers in the screenshot so it should show everything.

ArmorPaint.org - v0.8 (2021-01-19) - f25b885
Linux - OpenGL

does not show everything:
![image](https://user-images.githubusercontent.com/69405892/105386328-8ecf8c80-5c14-11eb-9d1c-0169a9cc8f37.png)
![image](https://user-images.githubusercontent.com/69405892/105386380-9e4ed580-5c14-11eb-91a0-e47da2262897.png)
![image](https://user-images.githubusercontent.com/69405892/105386445-aeff4b80-5c14-11eb-8559-8393f7239317.png)

**Comment by luboslenco** [comment]
- Can you post non-cropped screenshot so I can see the layer setup better?
- Do you get the same result when using just plain-color materials with no textures?
- The normals still look messed up in your screenshot. I am assuming you are using the test file provided at https://github.com/armory3d/armorpaint/issues/771? It should look like this in the latest ArmorPaint build.

![Capture](https://user-images.githubusercontent.com/3685704/105401314-5a64cc00-5c26-11eb-93d7-7d3964d48b11.PNG)

**Comment by SaraDark** [comment]
Yes i used  the test file provided at #771.
Previous screans is from test .arm file, now i add import clear blend test file and add tested textures again:

![Zrzut ekranu z 2021-01-21 21-34-19](https://user-images.githubusercontent.com/69405892/105409685-1d520700-5c31-11eb-8dba-1710e0e8808f.png)
![image](https://user-images.githubusercontent.com/69405892/105409787-41ade380-5c31-11eb-80fe-ffb821e87ee2.png)
![image](https://user-images.githubusercontent.com/69405892/105409822-50949600-5c31-11eb-920b-2568364f8045.png)
![image](https://user-images.githubusercontent.com/69405892/105409874-630ecf80-5c31-11eb-8c60-500435ce4444.png)
![image](https://user-images.githubusercontent.com/69405892/105409914-702bbe80-5c31-11eb-942e-6ddfa9a0738a.png)
![image](https://user-images.githubusercontent.com/69405892/105410004-9a7d7c00-5c31-11eb-985e-b71a686f02a4.png)

**Comment by luboslenco** [comment]
Thanks! Fix at https://github.com/armory3d/armorpaint/commit/7ae6dcbc133dae8bb5482ac29fbbd1b719db952f.
