### ISSUE TITLE
Compiling and debugging issues

### ISSUE THREAD

**Issue by brunomrsn** [armory3d/armorpaint#78]
First of all, I bought and used the ArmorPaint version 0.5 and it has stunning performance, it is easy to use, in a nutshell, I think it a promising replacement for Blender texturing.

Regarding the compiling issues (master branch), I managed to compile as the image shows:

![Screenshot (2)](https://user-images.githubusercontent.com/7876349/54162737-5c0fb700-4435-11e9-98bf-81929896d60d.png)

But, as you can see, the assets/icons don't show up.

I'm interested in debugging the code, but:

1) I tried to open the Kode Studio from Armory (the "Kode Studio" button underneath "Armory Project"), but it opens the project folder instead:

![Screenshot (8)_LI](https://user-images.githubusercontent.com/7876349/54163493-f96bea80-4437-11e9-9026-fbbcf4f38b96.jpg)

2) I also tried to debug without using Armory, just opening the Windows Store Kode Studio version and setting up the "launch.json" file as following:

![Screenshot (9)](https://user-images.githubusercontent.com/7876349/54163899-54eaa800-4439-11e9-80fe-64c12a304fed.png)

But when I run the "Kha: Krom" debugger I have a geometry shader syntax error:

![Screenshot (11)_LI](https://user-images.githubusercontent.com/7876349/54163986-ae52d700-4439-11e9-87b7-04a14e31ceb3.jpg)

Obs.: 
1) There are no console errors running in Armory engine, only when I try debugging in Kode Studio.
2) I can successfully debug the code using the "trace" function when running in Armory engine.

Could you help me?

**Comment by brunomrsn** [comment]
I had just noted that when I check the "Bundled SDK" in the "Add-ons", the "Kode Studio" button works as expected, but when I uncheck that and pass the SDK path, it stops working.

**Comment by brunomrsn** [comment]
Regarding the compiling issue, I think that's due to the absence of "-g opengl" argument. But even so I can't debug. When I try running "Krom.exe build_armorpaint/krom build_armorpaint/krom-resources" ArmorPaint window opens, but its content doesn't show up and it closes when a move the mouse over the window.

**Comment by luboslenco** [comment]
Hey @brunomrsn, sorry about the trouble and thanks for checking out ArmorPaint.
- The 'assets/icons don't show up' issue should be resolved now if you update Armory, it was a bug in git version. (https://github.com/armory3d/zui/commit/d86170256c343ffeafece19c88f5c527fa055c43)
- With ArmorPaint 0.6 I am adding D3D11 support, so debugging on Windows + KodeStudio hopefully resolved soon. The latest available 0.6dev_win64 builds are already D3D11 powered.
- I opened a new ticket to add debug instructions into the readme. https://github.com/armory3d/armorpaint/issues/79

**Comment by brunomrsn** [comment]
Thank you.

I tested it out and now the icons are ok:

![Screenshot (11)](https://user-images.githubusercontent.com/7876349/54209568-c586d880-44bc-11e9-82ea-cec3892b3c44.png)

**Comment by brunomrsn** [comment]
Is there any code-related stuff you'd like voluntary help to deliver next release?

**Comment by luboslenco** [comment]
Awesome, happy to see the icons working! I am also hoping --watch argument will get working again eventually.
