### ISSUE TITLE
Masks don't work with fill layers

### ISSUE THREAD

**Issue by TushieSushi** [armory3d/armorpaint#780]
![image](https://user-images.githubusercontent.com/66031501/105618786-8d0bf180-5deb-11eb-9772-4432da2b3fb8.png)

Steps to reproduce:
Create two layers and add a black mask to the top one, then bake any kind of map into it (in my case curvature)

My workaround:
Convert the masked layer as a paint layer then fill the entire layer again

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/fa37c878f981611c524a58c79dbb02d62da5b357, thanks for report!
