### ISSUE TITLE
Dragging and dropping a folder with PBR Materials doesn't properly create the material

### ISSUE THREAD

**Issue by TushieSushi** [armory3d/armorpaint#781]
**ArmorPaint version:**
v0.8 21/01/19
GTX 1050Ti, Windows 10

**Issue description:**

If you try and import a folder with a PBR material, armor paint will create a new material without importing/assigning the textures to it

**Steps to reproduce:**
Open a new project, drag and drop a folder containing PBR materials, a material will be created but without textures being imported or set up.
![image](https://user-images.githubusercontent.com/66031501/105630127-7a270a80-5e47-11eb-9ead-b31d39921ac7.png)

**Comment by luboslenco** [comment]
What does the folder contents look like?

**Comment by TushieSushi** [comment]
> What does the folder contents look like?

![image](https://user-images.githubusercontent.com/66031501/105630388-333a1480-5e49-11eb-93a8-9d96d86cb9e7.png)

**Comment by luboslenco** [comment]
Thanks! Was because of `_2k` extension but pushed a fix at https://github.com/armory3d/armorpaint/commit/f24557491fc56aa140d398fe541fb185b64350b9.
