### ISSUE TITLE
Import triangulator not working properly

### ISSUE THREAD

**Issue by TushieSushi** [armory3d/armorpaint#782]
**ArmorPaint version:**
v0.8 (21/01/19)

**OS/device including version:**
Windows 10, GTX 1050Ti

**Issue description:**
When I import a mesh without triangulating it first, some artifacts are visible

**Steps to reproduce:**
Importing a non-triangulated mesh creates some artifacts
![image](https://user-images.githubusercontent.com/66031501/105630204-16e9a800-5e48-11eb-9209-038fa1d52e64.png)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armorpaint/issues/228.
