### ISSUE TITLE
Material normal map artifacts

### ISSUE THREAD

**Issue by TushieSushi** [armory3d/armorpaint#783]
**ArmorPaint version:**
v0.8 (21/01/19)

**OS/device including version:**
GTX 1050Ti, Windows 10

**Issue description:**
When assigning a material with a normal map to an object, shadow artifacts show up

**Steps to reproduce:**
Import a mesh, then create a new material and assign a normal map to it, the mesh will now look weird
![image](https://user-images.githubusercontent.com/66031501/105630295-a1320c00-5e48-11eb-943b-39ec8bf0f9b1.png)

**Comment by luboslenco** [comment]
`Material Output` node in ArmorPaint takes normal map (`Image Texture`) directly as an input. Separate `Normal Map` node is coming via https://github.com/armory3d/armorpaint/issues/293.
