### ISSUE TITLE
Imported model with boolean topology have problems - Linux

### ISSUE THREAD

**Issue by spellmell** [armory3d/armorpaint#785]
I didn't do any tests beyond this.
A person asked me for help because he had problems to importing a similar model in substance painter. I was able to do it... and I thought to try with armorpaint, but when I imported the mesh, the object did not respect the topology of the hole created with a boolean modifier in blender.
![wrong_import_mesh_with_booleans_02](https://user-images.githubusercontent.com/77791463/105660126-1c2b0f00-5ea9-11eb-86c7-8bf267f8ffe6.png)
The hole in the mesh say him can't join to the party tonight
![wrong_import_mesh_with_booleans_01](https://user-images.githubusercontent.com/77791463/105660133-20efc300-5ea9-11eb-894a-3dfece860bb2.png)

ArmorPaint.org - v0.8 (2021-01-24) - be7346c
Linux - OpenGL
Fedora 32

https://drive.google.com/drive/folders/1JbL4ZW6Zb1osoJ0V_znFOn4lcLQp4KLo?usp=sharing

**Comment by luboslenco** [comment]
Hello, thanks for report. When exporting the `.obj` file enable the `Triangulate Faces` option. (hoping to fix soon at https://github.com/armory3d/armorpaint/issues/228)

**Comment by luboslenco** [comment]
Should work out of the box with https://github.com/armory3d/armorpaint/commit/6ff8fc7f1b3158f0e8050146752d2db4ece2c0dd. 🔨 

![cap](https://user-images.githubusercontent.com/3685704/106027276-07c65c80-60cb-11eb-909e-016bf0580e01.png)

**Comment by spellmell** [comment]
work fine, thx.

**Comment by spellmell** [comment]
![materials_Screenshot_20210127_182249](https://user-images.githubusercontent.com/77791463/106056487-802e1d00-60cd-11eb-921b-3a73f7a74f24.png)
![udims_Screenshot_20210127_182149](https://user-images.githubusercontent.com/77791463/106056499-845a3a80-60cd-11eb-8610-e2add2fd4acd.png)
I'm doing some small tests, and it seems that it still lacks a little magic touch for meshes with multimaterials, or udims....
https://drive.google.com/drive/folders/19Vvhu5thj7Gk0eS9iDAONgWj3CI9E9fR?usp=sharing

**Comment by luboslenco** [comment]
Thanks, that helps a lot! Pushed a fix for material split at https://github.com/armory3d/armorpaint/commit/a2458db31c56661a8ba713ac75c6157234ef812f. The udims issue seem to be related to `Material` tab (should fix itself if you switch to `Paint` tab), not to triangulation - will investigate.

**Comment by spellmell** [comment]
in neither of the variants did I use triangulation, but now it works correctly in both cases. 
ArmorPaint.org - v0.8 (2021-01-27) - a2458db
![multimats_ok_Screenshot_20210127_220621](https://user-images.githubusercontent.com/77791463/106077911-35be9780-60f1-11eb-89a5-21a4a67fd6ff.png)
![udims_ok_Screenshot_20210127_220621](https://user-images.githubusercontent.com/77791463/106077935-40792c80-60f1-11eb-9141-f0545d7d8425.png)

**Comment by luboslenco** [comment]
Yes, no need to triangulate on your own anymore because ArmorPaint now does it internally. 👍
