### ISSUE TITLE
Painting multiple texture channels simultaneously

### ISSUE THREAD

**Issue by Blenderwizard62** [armory3d/armorpaint#786]
I don't have armor paint yet, but am looking at buying it.
I currently use blender and am looking for a program that can paint the albedo or color, and Normal map at the same time, if you can please tell me if you can do this in armor paint as I tried Mari and cant do it there. As I understand you can do this in 3DCoat, I am new to github so if the developer reads this and this feature is currently not included, please add it. Thanks in advance.

**Comment by luboslenco** [comment]
Hello, thanks for checking out ArmorPaint! Yes, you can paint multiple channels at once - you can check out https://armorpaint.org/howto.html and https://armorpaint.org/manual.html to see what features are available and what is still missing. 🙂
