### ISSUE TITLE
Paint over all model objects instead of the selected element / object - Linux

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#788]
When I use manual painting, I paint over all model objects instead of the selected element / object
![image](https://user-images.githubusercontent.com/69405892/106094430-4e02d680-6132-11eb-91b3-b1105f155b3b.png)
![image](https://user-images.githubusercontent.com/69405892/106093201-201c9280-6130-11eb-86aa-5fc59cc2666f.png)
![image](https://user-images.githubusercontent.com/69405892/106093286-44786f00-6130-11eb-89ef-f409adbead37.png)
![image](https://user-images.githubusercontent.com/69405892/106093321-5528e500-6130-11eb-888b-843c38a19bbc.png)

ArmorPaint.org - v0.8 (2021-01-27) - 9696e42
Linux - OpenGL

**Comment by luboslenco** [comment]
Hello, you have to assign the layer to the object you wish to paint on.

![106094430-4e02d680-6132-11eb-91b3-b1105f155b3b](https://user-images.githubusercontent.com/3685704/106108744-fae84e00-6148-11eb-8178-b59eaf7f4065.png)
