### ISSUE TITLE
Cannot see all painted layers with selected layers - Linux

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#790]
Cannot see all painted layers with selected layers, e.g. on screens:
![image](https://user-images.githubusercontent.com/69405892/106202001-931e1b80-61b9-11eb-80b2-87ed275ad946.png)
![image](https://user-images.githubusercontent.com/69405892/106202011-9addc000-61b9-11eb-9f8b-4665c298375c.png)

[testFile2.arm.zip](https://github.com/armory3d/armorpaint/files/5890136/testFile2.arm.zip)
[testModel2.blend.zip](https://github.com/armory3d/armorpaint/files/5890137/testModel2.blend.zip)

ArmorPaint.org - v0.8 (2021-01-27) - 9696e42
Linux - OpenGL

**Comment by luboslenco** [comment]
Sorry but I am still not able to reproduce it, it works like expected here. :( If the issue persists in latest builds maybe try to record a video, so I can follow the steps exactly. Thanks for the help.
