### ISSUE TITLE
Can not drag layer after the last group

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#791]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-01-30) - 77d0ef2

**OS/device including version:**
Win64

**Issue description:**
Can not drag layer after the last group

**Steps to reproduce:**
Create several groups and layers.
Then it is always possible to drag and drop layers to different positions except in the case that the last element is a group. If the last element is a layer then everything can be dragged and dropped after it.
Situation:
![ap1](https://user-images.githubusercontent.com/28649121/106356752-4d209f00-6302-11eb-9ca3-f2a5ed506c0f.jpg)
Change order
![ap2](https://user-images.githubusercontent.com/28649121/106356760-57429d80-6302-11eb-920f-01b8fb275267.jpg)
By dragging to the top the blue line appears
![ap4](https://user-images.githubusercontent.com/28649121/106356775-6cb7c780-6302-11eb-8253-c831d3fe7d7b.jpg)
By dragging ito to the bottom the blue line never shows up
![ap3](https://user-images.githubusercontent.com/28649121/106356769-61fd3280-6302-11eb-90b9-d7c7a6841d7d.jpg)

Finally one usability question/idea: Currently groups can not be nested - which is perfectly fine for me - but if I drag a group into another group I get this drag and drop blue line. Maybe it should not show up in this case?

**Comment by luboslenco** [comment]
Both issues should be resolved now via https://github.com/armory3d/armorpaint/commit/78d2de076f05417b110e32e53e8eb77334cde257, thanks for report! Will eventually add group nesting, once the basics work. 🙂

**Comment by MathemanFlo** [comment]
Awsome. Thank you very much for the quick fix. 

> Will eventually add group nesting, once the basics work. 🙂

Good idea but no need to hurry. I highly appreciate your tremendous amount of work.
