### ISSUE TITLE
Problem with huion graphics tablets

### ISSUE THREAD

**Issue by evin279** [armory3d/armorpaint#793]
ArmorPaint version: v0.8 (2021-01-27) - 9696e42

OS/device including version:
Windows 10 64bit, GTX 1080

Issue description:
Huion tablets does not apply any pressure sensitivity. It works like a mouse unless I activate windows ink.
But there are lags and other strange behavior then.

I can’t work properly with it.

My tablet is the HUION Kamvas Pro 22 (2019) and is works with all my other software.

**Comment by luboslenco** [comment]
Hello, thanks for report. ArmorPaint is using the Windows Ink on Windows, so it needs to be enabled.
There is a huion support page regarding the Windows Ink issue mentioning lags which might be helpful?
https://support.huion.com/en/support/discussions/topics/44001012773

If the issue persists please drop me an email so I can send you a refund, sorry about the trouble.

**Comment by evin279** [comment]
Don't worry, I won't ask for a refund, I want to support the project.

If I find a solution, I will post on the forum, thanks for answering me.
