### ISSUE TITLE
Parameter names in a group node not save

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#794]
ArmorPaint.org - v0.8 (2021-01-24) - 1fa27a9
Win 10 64 bit

Hello Lubos! How are you? Thanks to my subscriber, we found a new bug. It is associated with the names of the parameters in the node group.
I created a new group in the material. Let's assume the simplest option. At the input, the UV (UV coordinates) and values (size) at the output color (Color). Gave names to group parameters. If, in a new material, add this group, the names of the group parameters are not saved. But if you copy this node from the material in which it was created to the new material, then everything is fine.
Video attached https://drive.google.com/file/d/1Htc3W2PA1Zt9qX2ygdXvs8CDxT8uxHZY/view?usp=sharing

**Comment by luboslenco** [comment]
Great catch, thanks! Pushed a fix at https://github.com/armory3d/armorpaint/commit/f5e9473d61bc5aeb1b7cc76e1f351b581c28cff5.

**Comment by AlexKiryanov** [comment]
Nothing, Lubos) thanks to my subscriber for finding it and for you that
they fixed it so quickly, I just wrote a report about it))

вс, 31 янв. 2021 г., 19:21 Lubos Lenco <notifications@github.com>:
