### ISSUE TITLE
Fill Layer Mask issue

### ISSUE THREAD

**Issue by melvixiodf** [armory3d/armorpaint#795]
Noticed if you have a fill layer with height say 0.6 and you paint a mask for it. If you create a new fill layer on top and fill the new layer's mask with black. The height of the lower fill layer is now at 0. It's no longer displayed in the viewport.

Another issue is when using a texture in the brush nodes opacity and I set the color of the brush to white in the material being used to paint the mask for the fill layer, the vaules are not consistent, they are all over the place but if the color of the brush material is set to black, it works correctly.
Maybe an accumulate option for the brushes while painting.

**Comment by luboslenco** [comment]
It should work now after https://github.com/armory3d/armorpaint/commit/6c78d780c55025c074594557fae9924fa2f7435d and https://github.com/armory3d/armorpaint/commit/63bfbeb15b1d3bb341a9435e89b851cc693d4896, thanks for report!

**Comment by melvixiodf** [comment]
Thanks for the fixes.
