### ISSUE TITLE
Scatter Brush

### ISSUE THREAD

**Issue by melvixiodf** [armory3d/armorpaint#796]
Been trying out armor paint in the last two weeks. Must say I am impressed with it and how well it runs even on low end cpus.

I am wondering if we can get a scatter brush, sort of like Blender's texture jitter brush(when you increase the jitter vaule in Blender, you can increase the spacing between jitter with the spacing in Blender as well) that scatters the brush points over a large area with a few strokes. It would be great for decals as well for scattering leaves, twigs materials over large areas.

Hopeful this can pls be considered and thanks for all the work you have put in so far. Many kudos to you for all the hardwork

**Comment by luboslenco** [comment]
Hello, thanks for the issue reports, it helps a lot! I think it should be doable via brush nodes, please check the Brush Jitter video at https://armorpaint.org/howto.html. Hoping to provide some prebuilt brushes via https://github.com/armory3d/armorpaint/issues/177 soon, so it's easier to get started.

**Comment by melvixiodf** [comment]
Thanks for the info. I have used the jitter brush created in your vid before making this feature request.
Here is what I am trying to say:
![viewport](https://user-images.githubusercontent.com/54470864/106490722-65391f80-64b6-11eb-96f6-a0fb708398f3.gif)
 In Blender, I can use a very tiny brush and control the jitter amount. In armor paint, this isn't possible. If I decrease the brush point, I can't control the jitter amount. I can only randomise the rotation, size and control the spacing.

I tried the particle brush but it doesn't work currently so I am assuming it still work in progress. No way to control the jitter amount for the paint brush nodes thats why I wanted to make a feature request.

**Comment by luboslenco** [comment]
Thanks for the excellent explanation! Not bothering at all, it really helps to see which features I should focus on next. Adding link to https://github.com/armory3d/armorpaint/issues/34 so I take it into account and make it possible, hopefully more progress there soon.
