### ISSUE TITLE
errors while updating armorpaint sources and building

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#798]
ArmorPaint.org - v0.8 (2021-01-31) – c609245
Windows10 - Direct3D11
Intel(R) HD Graphics 620  

While trying to update sources and build I'm getting the following errors:
----------------------------------------------------------------------------------------------------
...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 45 (delta 33), reused 44 (delta 32), pack-reused 0
Unpacking objects: 100% (45/45), 4.18 KiB | 24.00 KiB/s, done.
From https://github.com/armory3d/armorpaint
 * branch            master     -> FETCH_HEAD
   1f9d4c7..c609245  master     -> origin/master
Updating 1f9d4c7..c609245
Fast-forward
 .../shaderlib/Sources/arm/shader/NodesMaterial.hx      | 10 +++++-----
 Sources/arm/App.hx                                     |  2 +-
 Sources/arm/Context.hx                                 |  4 ++--
 Sources/arm/Enums.hx                                   | 13 +++++++------
 Sources/arm/Project.hx                                 |  2 +-
 Sources/arm/ProjectFormat.hx                           |  4 ++--
 Sources/arm/data/LayerSlot.hx                          | 17 +++++++++++++----
 Sources/arm/node/MakeMesh.hx                           |  3 +++
 Sources/arm/render/RenderPathPaint.hx                  |  3 ++-
 Sources/arm/ui/TabLayers.hx                            | 18 ++++++++++++------
 Sources/arm/ui/TabSwatches.hx                          |  6 +++++-
 Sources/arm/ui/UIMenu.hx                               |  3 ++-
 Sources/arm/ui/UINodes.hx                              |  4 ++--
 13 files changed, 57 insertions(+), 32 deletions(-)
error: Your local changes to the following files would be overwritten by checkout:
        Backends/System/Windows/Sources/Kore/System.cpp
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout '0378408eabeec9c7a2a2ab93c16cae4862fd6948' in submodule path 'armorcore/Kinc'
Failed to recurse into submodule path 'armorcore'
do you want to continue with building armorpaint sources[Y/N]?y
.
.
some lines later

error: patch failed: Kinc/Backends/System/Windows/Sources/Kore/System.cpp:245
error: Kinc/Backends/System/Windows/Sources/Kore/System.cpp: patch does not apply
error: patch failed: Kinc/Backends/System/Windows/Sources/Kore/Window.c:196
error: Kinc/Backends/System/Windows/Sources/Kore/Window.c: patch does not apply
kincfile found.
Creating Windows project files.
Compiling shader 1 of 10 (g1.frag).

![εικόνα](https://user-images.githubusercontent.com/72331575/106393824-d66acb00-6401-11eb-8e34-5f28846bb0e2.png)

Also, trying to extract_locales.py el, the json file doen't contains previous Greek translation. Only an English template!
What am I doing wrong?

**Comment by luboslenco** [comment]
I think it's because of the Kinc submodule in armorcore being updated recently - cloning form scratch should resolve the issue, apologizes for trouble.

> Also, trying to extract_locales.py el, the json file doen't contains previous Greek translation. Only an English template!
What am I doing wrong?

Looks like it should already do that https://github.com/armory3d/armorpaint/blob/master/Assets/locale/tools/extract_locales.py#L87, will look into it asap.
