### ISSUE TITLE
Dilate radius not applied to mask

### ISSUE THREAD

**Issue by todirbg** [armory3d/armorpaint#799]
**ArmorPaint version:**
v0.8-c609254

**OS/device including version:**
Windows 10/DX11/Nvidia GTX1050

**Issue description:**
When using fill layer with mask painted in the 3D viewport the dilate radius setting is not applied to the mask. As a result after apply or on export seams are visible.

**Steps to reproduce:**
Open new cube, create some color material and add it as fill layer. Add black mask to the layer. Use the fill tool or the brush to paint the cube white in the 3D viewport. Apply the mask. Activate UV map and zoom in the 2D viewpor to see the result.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/e0596152fb2ab18d08a6aa56a93b578e6d30f16e, many thanks for report!

**Comment by todirbg** [comment]
Thank you :)
