### ISSUE TITLE
Projection of brush does not scale properly with screen resolution

### ISSUE THREAD

**Issue by SojanJanso** [armory3d/armorpaint#80]
On Ubuntu 18.04.2 LTS (gnome), the resolution of the screen affects the projection size of the brush, and causes it to miss-align with the brush cursor size.

If the resolution is greater than FHD, the projection is larger than the brush circle, and if the resolution is less than FHD, the projection is smaller than the circle. Here are screenshots at 800x450, 1280x720 (HD), 1920x1080 (FHD), and 3840x2160 (4K) respectively.

![800x450](https://user-images.githubusercontent.com/26679320/54213052-282aa500-44ba-11e9-9af1-0d703f84956b.png)
![1280x720](https://user-images.githubusercontent.com/26679320/54213091-3678c100-44ba-11e9-8e93-8abf8b17f8f4.png)
![1920x1080](https://user-images.githubusercontent.com/26679320/54213113-42648300-44ba-11e9-88f5-44357a034cfe.png)
![3840x2160](https://user-images.githubusercontent.com/26679320/54213147-514b3580-44ba-11e9-8999-fde0f1d8d225.png)

**Comment by luboslenco** [comment]
Thanks for opening this, it should be resolved now in the new dev build.

**Comment by SojanJanso** [comment]
Yup, it's now working as expected.

**Comment by luboslenco** [comment]
Sweet!
