### ISSUE TITLE
Copy and paste Mask

### ISSUE THREAD

**Issue by melvixiodf** [armory3d/armorpaint#800]
Wanted to make a feature request for copying and pasting mask.

Right click the mask, Can copy and paste pls be added to the list here so we can copy and paste between paint and fill layer masks.
![screenshot](https://user-images.githubusercontent.com/54470864/106658842-22527700-659e-11eb-9a8f-043a1c8911a4.jpg)

Thanks.

**Comment by luboslenco** [comment]
Masks can be duplicated and moved now after https://github.com/armory3d/armorpaint/commit/b2102d8e3970a035561990a84f1272f04afdcfa3. Thanks for suggestion!
