### ISSUE TITLE
Armor paint lagging

### ISSUE THREAD

**Issue by Blenderwizard62** [armory3d/armorpaint#801]
I recently purchased armor paint, and I am experiencing some lagging when painting a higher poly model. My hardware is: Operating System:Microsoft Windows 10 64 bit
CPU Model: AMD Ryzen 5 2600 Six-Core Processor            
Ram:15.9 GB
Graphics Card: NVIDIA GeForce GT 710 
OpenGL:4.6.0 NVIDIA 461.09
I know my card is really out dated, so if this is the problem just tell me.
Thank you for your time!

**Comment by luboslenco** [comment]
Hello, thanks for posting. Yes, for ArmorPaint graphics card is the most important part. You can tweak some settings in the preferences - for example set Viewport - Renderer to Mobile, Usage - Dilate to Delayed. If it still lags please send me an email for a refund.

**Comment by Blenderwizard62** [comment]
Thanks for your time, really appreciate it!!
