### ISSUE TITLE
Bump node does not handle mixed textures

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#802]
ArmorPaint.org - v0.8 (2021-02-03) - 988af9a
Win 10 64 bit

Hello Lubos! I know you said that the work on this node is not finished yet. So please don't take this as a call to action. I am writing this so as not to get lost.
I tested the fixed Bump node. Found one error.
![4](https://user-images.githubusercontent.com/65244629/106748387-3b0e6b80-6636-11eb-847d-63416733d5ed.jpg)
![3](https://user-images.githubusercontent.com/65244629/106748390-3c3f9880-6636-11eb-9ecb-ab26ab60db1b.jpg)
![2](https://user-images.githubusercontent.com/65244629/106748392-3c3f9880-6636-11eb-83dd-92c6faac165f.jpg)
![1](https://user-images.githubusercontent.com/65244629/106748396-3c3f9880-6636-11eb-994a-8407d96f170c.jpg)

Node for some reason does not process mixed textures. What procedural what ordinary images.
Let's say we take 2h texture. If we use one texture, then the node gives the correct result, but as soon as we mix 2 textures, then the node uses the first texture in the calculations.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/e0649a3434f1483f60cefa8b22509f4d15893475, many thanks for reporting the issue. Please let me know if it works better / worse. 🙂 Still need to improve the quality but the bump node should work in all cases now.

**Comment by AlexKiryanov** [comment]
Good afternoon Lubos! again! Yes, of course, I'll check.) And I'll write to
you)

ср, 3 февр. 2021 г. в 17:01, Lubos Lenco <notifications@github.com>:
