### ISSUE TITLE
Unable to check for updates (dd849fa)

### ISSUE THREAD

**Issue by AlexeySergeich** [armory3d/armorpaint#803]
*ArmorPaint 0.8-dd849fa, Windows 7 (DirectX11)

*

**Issue description:**
Hello, I found the problem in my compiled build. When I try to update ArmorPaint, cmd showing me the next error (sorry for Russia language). And I can't to update programm, or connect to cloud library

![Безымянный](https://user-images.githubusercontent.com/78400738/107004505-70829880-679f-11eb-8046-55d37414fcc7.png)
That's problem in my Net provider or what? Compiling build according instruction step-by-step
![Безымянный2](https://user-images.githubusercontent.com/78400738/107004581-8f812a80-679f-11eb-8197-62ea6373445e.png)

**Comment by luboslenco** [comment]
Hello, thanks a lot for the report. It looks like `Invoke-WebRequest` is not available on Windows 7. I have found one potential solution [here](https://stackoverflow.com/a/53035736). Unfortunately since Microsoft has ended support for Windows 7 it's only a matter of time for more issues to arise eventually, sorry.

**Comment by MathemanFlo** [comment]
I'm unable to reproduce this on ArmorPaint.org - v0.8 (2021-02-05) - dd849fa on win10 x64
I have the impression that the reporter's windows 7 has not powershell 3.0 or later which is required for Invoke-WebRequest.
To find it out whether I'm right or not @AlexeySergeich:
Would you open the powershell via Windows-Key+R: type in powershell and press enter
A blue powershell window opens where you could type in '$PSVersionTable' and press enter. Make a screenshot of the result.

**Comment by AlexeySergeich** [comment]
> I'm unable to reproduce this on ArmorPaint.org - v0.8 (2021-02-05) - [dd849fa](https://github.com/armory3d/armorpaint/commit/dd849fa79eba78ce881a8dfd16b79be29b839dc1) on win10 x64
> I have the impression that the reporter's windows 7 has not powershell 3.0 or later which is required for Invoke-WebRequest.
> To find it out whether I'm right or not @AlexeySergeich:
> Would you open the powershell via Windows-Key+R: type in powershell and press enter
> A blue powershell window opens where you could type in '$PSVersionTable' and press enter. Make a screenshot of the result.
> 
> Seems to me I was too slow :-D
> Maybe a solution for @AlexeySergeich: Install https://www.microsoft.com/en-in/download/details.aspx?id=34595 and then it should work again.

that powershell update helped me in some cases. Now I can connect to cloud library, but still can't check for updates 
![Снимок](https://user-images.githubusercontent.com/78400738/107074247-845ae880-67f9-11eb-9497-dcdfe867decb.PNG)
"The request was aborted: Could not create SSL/TLS secure channel."
