### ISSUE TITLE
Viewport unresponsive

### ISSUE THREAD

**Issue by fopor** [armory3d/armorpaint#804]
**ArmorPaint version:**

Hash: 0bfd12acb0312c653316a524612b13866bbdfdd9

**OS/device including version:**

GPU: RTX 2070S
Arch, kernel 5.10.11-arch1-1

**Issue description:**

Viewport is unreponsive, rest of the UI works fine.
It is impossible to move the camera or use brushes over the mesh.

Screen record of the bug:
https://gph.is/g/4bGpqOG

**Steps to reproduce:**

Happens everytime, as soon as the program starts.

**Comment by luboslenco** [comment]
Seems to work here like usual. :( Is there any error output when you launch ArmorPaint from terminal? If this is not the first time you are running ArmorPaint, did it work before? Same for clean build?

**Comment by fopor** [comment]
Thanks for the quick response!

Terminal output:
```
armorpaint     
Uniform N not found.
Uniform W not found.
Uniform eye not found.
Uniform aspectRatio not found.
Uniform brushScale not found.
```
It is my first time using it, so I have not tested it before, I can try to checkout to an older commit...

**Comment by fopor** [comment]
Hey, just updated Arch and it started working...
I do not know what did the trick, but it is now working.

I am very happy to be able to use Armorpaint :]

**Comment by senjacob** [comment]
@luboslenco I just want to tell the same happens to me in latest Ubuntu 21.04, (lowlatency kernel from Ubuntu installer) and nVidia proprietary stable driver for GTX 1050. 
I compiled from source (latest clone). These are the unique entries from console.
3D viewport is not responding to any of the Left/Mid/Right clicks. Sometimes after opening menu, the menu is not closing evenif I click anywhere.

Unlike @fopor, my OS is up to date. So I thought I should report it. Thanks!

```
Uniform N not found.
Uniform W not found.
Uniform eye not found.
Uniform aspectRatio not found.
Uniform brushScale not found.
Uniform WVP not found.
Uniform inp not found.
Uniform inplast not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/kinc/backend/graphics4/OpenGL.cpp 752
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/kinc/backend/graphics4/rendertarget.c 173
```

**Comment by senjacob** [comment]
Update: 
I re-cloned the repo, built again, had same issue. When used file>open and close the dialog, viewport got responsive. My machine was getting a bit heated up also.

However, after I reset my nVidia X Server settings (Prime Profile: Nvidia(Performance Mode), PowerMizer: Auto) and restarted, the application worked flawlessly.
