### ISSUE TITLE
Stuttering on Linux

### ISSUE THREAD

**Issue by Somamint** [armory3d/armorpaint#806]
**ArmorPaint version: **

Newest Version 0.8

**OS/device including version:**

OS:POPOS!  8-Core 10th Gen Intel i7-10875H CPU
NVIDIA GeForce RTX 2060
Nvidia Driver: 460.39
Up to 64GB memory 

**Issue description:**
Sometimes i start ArmorPaint and to move the cube or any other model cause stuttering and can't really use ArmorPaint then. This can happen many times before one restart of the game will remove all stutterings.

**Comment by Somamint** [comment]
Really not sure what going on here. I use this programm on a laptop.  I figured out if i use Version 0.7 the stuttering will disappear. But if i start Version 0.8 it will stutter. If i remove now the charging cable, Version 0.8 works not perfect but i can use it.

**Comment by Somamint** [comment]
Hello i will answer here, I have not find the issue, the only thing i can tell is, that after while the stuttering got less.

**Comment by Somamint** [comment]
Just wanna tell you, the newest Version of ArmorPaint has even worse performance now and this Version it not usable. Hope that helps to find the problem :)

**Comment by luboslenco** [comment]
Sorry but I was not able to reproduce the issue so far. There has been a similar report at https://github.com/armory3d/armorpaint/issues/804 which claims the OS update fixed it, so maybe OS / graphics driver update could help.

The fact that it works on the integrated gpu and not the dedicated one is odd - ArmorPaint only asks the graphics driver via opengl to complete a task - it has no special code for integrated / dedicated gpus, that should be handled by OS / graphics driver.

If you got the gumroad builds please send me an email for a refund. I will do my best to look for a solution but do not yet know the fix. Apologizes for trouble.

**Comment by Somamint** [comment]
I won't refund, because the program is so good. I will try some driver updates. Etc. but the thing is i bought Armor Paint 2 updates before and it worked perfect only the last 2 updates are stuttering. So if you maybe could offer the version 2 updated before i could keep using your program :)

**Comment by Somamint** [comment]
Hey i just want to tell you. After i updated my OS. Stuttering is gone and also Mask Decals is working!
