### ISSUE TITLE
It is not compiling the haxe's files in their latest versions 

### ISSUE THREAD

**Issue by MarcioVitor** [armory3d/armorpaint#809]
![s](https://user-images.githubusercontent.com/13188882/107515484-d5683500-6b89-11eb-98a1-9a3b5b72c7f7.png)
**ArmorPaint version:**
[a814499](https://github.com/armory3d/armorpaint/commit/a81449990499f25b92335a7e72be2fa392d1f769)

**OS/device including version:**
Windows 10-(2004), I3-4th Gen & 8GB RAM

**Issue description:**
haxe compiler error in the last versions that were committed 

**Steps to reproduce:**
run this code in the directory: node armorcore/make android -g opengl --shaderversion 300

**Comment by luboslenco** [comment]
Based on your screenshot it fails at https://github.com/armory3d/armorpaint/blob/master/Sources/arm/util/BuildMacros.hx#L12, which means git command is not accessible from your command line. When installing git, make sure the option to make git available in command line is enabled.

Check https://github.com/armory3d/armorpaint/issues/129.
