### ISSUE TITLE
Decal Mask not working

### ISSUE THREAD

**Issue by Somamint** [armory3d/armorpaint#810]
**ArmorPaint version: **

Newest Version 0.8

OS/device including version:

OS:POPOS! 8-Core 10th Gen Intel i7-10875H CPU
NVIDIA GeForce RTX 2060
Nvidia Driver: 460.39
Up to 64GB memory

Hello i try to do the same steps as in the tutorial:
https://www.youtube.com/watch?v=c3ooO5i9DKs&feature=emb_title\

First Pictures shows nothing will shop up, once i move in the 2D View the mask sticker will appear.

But nothing will show up in the main window. I only get the picture i want to paint in the 2D view.
![armorpaint](https://user-images.githubusercontent.com/48291814/107615067-cfd32380-6c4b-11eb-81c4-fae4e6f113c7.png)

**Comment by luboslenco** [comment]
Hm all seems well here. I am afraid it has something to do with your issue at https://github.com/armory3d/armorpaint/issues/806, still trying to reproduce it myself, sorry it's taking a while. Will report back at https://github.com/armory3d/armorpaint/issues/806. Or if you already got past the stuttering issue, please let me know.
