### ISSUE TITLE
Memory problem when using high number of Layers in ArmorPaint

### ISSUE THREAD

**Issue by nickwillett** [armory3d/armorpaint#812]
**ArmorPaint version:**
v0.8 (2021-01-03),

**OS/device including version:**
Windows 10, GTX1070

**Issue description:**
When working with a complex model with multilple parts and materials, adding new layers works without any problem until there comes a point where the model no longer displays properly on the screen (inverted normals etc).  Also when that happens, RAM usage begins to climb until all available memory is taken and the software suddenly crashes and closes.

**Steps to reproduce:**
![off](https://user-images.githubusercontent.com/78960700/107765746-46dee980-6d2a-11eb-9d6c-1bdefaef40cb.jpg)
![on](https://user-images.githubusercontent.com/78960700/107765760-49d9da00-6d2a-11eb-88af-896cb20a6864.jpg)

**Comment by luboslenco** [comment]
Hello, thanks for report. Any chance to test it in the latest build (0.8dev 54fb27a / February 11, 2021)? Is it the same?

**Comment by nickwillett** [comment]
I've just compiled the latest version and that seems to have fixed the problem.  Thanks for your help!

**Comment by luboslenco** [comment]
Happy to hear! 😊
