### ISSUE TITLE
Swatches Feature has usability issues

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#813]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-02-12) - ca0fac6

**OS/device including version:**
Win64

**Issue description:**
The new Swatches feature has several usability issues

**Steps to reproduce:**
1. The color picker's height is too small
![Screenshot 2021-02-12 180741](https://user-images.githubusercontent.com/28649121/107799044-38f68c00-6d5d-11eb-93f7-4c8fcad9ea3e.jpg)
2. By double clicking onto a color the R channel is automatically selected and changes if I move the mouse. While it is a nice idea to avoid a click for changing the first channel I think it is confusing.
3. By adding further colors the color picker eventually isn't shown completely. I think it should be positioned such that it is always shown completely
![Screenshot 2021-02-12 181325](https://user-images.githubusercontent.com/28649121/107799684-08632200-6d5e-11eb-9750-99cad8f032cd.jpg)

Besides these small things the feature is absolutely awsome and very useful.

**Comment by luboslenco** [comment]
Great to hear it's useful! I pushed a fix at https://github.com/armory3d/armorpaint/commit/c5756140f227eb9507d8fd55dfbafe752a5d3674, but I am not sure it fixes "The color picker's height is too small" issue. It seems to be correct here no matter which ui scale I set. Are you using the `Preferences.. - Interface - UI Scale` option?

**Comment by MathemanFlo** [comment]
Great! Meanwhile I tried it and no I do not use any UI scaling, neither OS nor ArmorPaint. The picker's positioning is great! It's very intuitive. 
Maybe one additional idea: If there are too many colors to show, there could be a scroll bar.

**Comment by luboslenco** [comment]
All should be well after https://github.com/armory3d/armorpaint/commit/28efd74617a6c45deb957f16beafde96fa2a825e https://github.com/armory3d/armorpaint/commit/f996f76dc22d31afa200d24f6fde58bc685d77e1, thanks for letting me know!

**Comment by MathemanFlo** [comment]
Awsome! Thank you for your quick fixes. I highly appreciate that. Now the feature is just perfect. I also like the little tooltips with the color code on hovering over the colors. 
And I'm sorry, I think I found yet another issue: The import button does not seem to work properly. 
Steps to reproduce:

1. Create some new colors.
2. Save the arm file
3. Reopen ArmorPaint or open a new project.
4. Click on Swatches->import and select the previously saved arm file. 
5. Now the filer picker dilog opens once again and if I select the file again the ordinary import is done.

**Comment by luboslenco** [comment]
Another fix at https://github.com/armory3d/armorpaint/commit/3265095a553a9ffc56f900649bfb15d790a2d28f, thanks for patience!

**Comment by MathemanFlo** [comment]
Works for me now. Thank you for your quick fixes. It's great to work together with you.
