### ISSUE TITLE
Import shortcut is incorrect

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#815]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-02-12) - 3265095

**Issue description:**
There are several buttons where the tooltip contains Ctrl+i, but the connected action is the wrong one. Examples are the textures tab, the meshes tab, the font tab and the swatches tab. All of them are labeled with Ctrl+i but this is only partly true. It works for textures for sure. For meshes the behavior is a bit different. In meshes tab I can either replace or add another one. The Ctrl+i dialog replaces it. Ctrl+i does not support fonts or colors for swatches, even though both import buttons have the label. The file menu shows Ctrl+i for import texture, but clicking on import texture gives me a different file picker (different file types) than pressing Ctrl+i. 

Also clicking on import in textures tab and selecting a hdr image sets it as background image. I don't know whether this is intended or not. At least in theory one could use hdr files for textures, too.

**Comment by luboslenco** [comment]
Should be resolved now, thanks for taking time to report this.

- Removed wrong `ctrl+i` labels
- `Import Texture` will no longer set `.hdr` file as envmap
- `Import Envmap` button is now located in the `File` menu
- There is still one inconsistency, `ctrl+i` shortcut sets the filter so you can import both texture and mesh asset (for convenience), while in the menu it's listed for texture import

**Comment by MathemanFlo** [comment]
Great! Thank you so much. I really like the idea of placing the import envmap in the File menu. It's more consistent. I also think it's very convenient to import meshes and texture at the same time.
