### ISSUE TITLE
Give the picker the ability to add a swatch

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#816]
I wonder whether it would be a useful feature to add a button to add the basis color to the swatches.

**Comment by luboslenco** [comment]
The picker picks the color of the currently active swatch item. Still need to add swatches functionality to the manual. Can also change it the other way around if it ends up confusing, add via a button like you suggested.

**Comment by MathemanFlo** [comment]
Thank you for your clarification. I didn't realize that. I'm also unsure whether I would expect the picker to change my swatches. For example suppose one has a color scheme defined via swatches and one of them is selected because it was used some seconds ago and then the picker overwrites this color, maybe even unnoticed.
