### ISSUE TITLE
Context menu for Nodes

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#817]
I think it would be nice to have a context menu for nodes. Maybe the following items would be great:
- duplicate
- remove
- copy
- cut

If multiple nodes are selected, all nodes should be affected. 
The editor background itself could have a context menu to paste copied or cut nodes.

Background: I only found out by chance that all these functionalities are actually present by shortcuts but not by UI. Others might be unaware of them, too.

Additionally multiselect could be extended by not only allowing for dragging a rectangle but by pressing Ctrl and selecting them node by node.

By the way the node group feature is awsome and very intuitive.

Finally a question: Is it intentional, that the node system does not allow undo and redo?

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/064585a6f6f069f946987f7fbcebc27c7904e141 + fixed ctrl selection.

**Comment by MathemanFlo** [comment]
I found yet another issue:
1. Use any material
2. Right click on Material Output
3. Now left click on a free spece in RGB node (or any other node) i.e. not the color wheel or a control. For instance on the RGB caption above the red line. Alternatively click on a blank space (i.e. not ON a node)
4. On the first click the context menu disappears.
5. On any subsequent click nothing happens except when you move the mouse a bit. In this case the RGB node is selected and gets a white border as expected.

The very same happens for clicking right instead of left mouse button.

**Comment by MathemanFlo** [comment]
I found a simpler way to reproduce it:

1. Right click on a Material Output
2. Right click on a RGB node (or any other node), the other context menu closes
3. Now right click again without moving the mouse cursor between step 2 and 3. The node won't get selected and the context menu won't open

**Comment by luboslenco** [comment]
Should be resolved via https://github.com/armory3d/armorpaint/commit/41a3831cc347a86a67eca9df5eb47df1334a6d49.
