### ISSUE TITLE
Translations in enum-type buttons in nodes not applied

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#818]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-02-13) - 3265095

**Issue description:**
Translations are not applied in enum-type buttons in nodes. As far as I can see there are only a few
- Gradient texture
- Math
- Vector math
- image texture
- ...

**Steps to reproduce:**
Consider my latest pull request for the german translation and check math or vector math.

**Comment by luboslenco** [comment]
Fixed now, thanks!
