### ISSUE TITLE
DirectX 12 Glitch in viewport

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#820]
ArmorPaint.org - v0.8 (2021-02-14) - 743f6d3
Win 10 64bit 
GTX 1070 

Hello Lubos! How are you?Forgive me for writing on a holiday) By the way, happy holidays)
A little story.
I wanted to bake the AO map and so today I collected the latest version of dx12. I loaded the model into the program (split by material). And in the Lit mode, flickering and disappearing geometry appear. Video on the link. https://drive.google.com/file/d/1GKKYlo-O9VpwdwAW-A6_gokby9R1hQg9/view?usp=sharing (if you do not break the model into materials but load it as an object, then the glitch disappears)
in Path Traced mode, everything is fine, but rendering is very slow. While this is understandable, it's like real-time rendering.
I'll write a goodbye in the next report)

**Comment by luboslenco** [comment]
Fixed via https://github.com/Kode/Kinc/pull/600, thanks for another great bug report! :)

**Comment by AlexKiryanov** [comment]
good evening! you are welcome! Thanks for the correction!)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 1 мар. 2021 г. в 21:56, Lubos Lenco <notifications@github.com>:
