### ISSUE TITLE
ArmorPaint Dx12 Crush program in baking maps more than 2K

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#821]
ArmorPaint.org - v0.8 (2021-02-14) - 743f6d3
Win 10 64bit
GTX 1070
Hi again!)
Now let's move on to baking textures.
I tried baking the AO map on the bear model. If I set the texture resolution to more than 2K the program crashes.
Well that's it for today! Have a nice weekend!

**Comment by luboslenco** [comment]
Thanks for report! Hm it seems to work fine on RTX2080, however the reports of GTX 10 series not working well with ray-tracing features seem common - hence also the path-tracing viewport being too slow for you.

I have updated the readme at https://github.com/armory3d/armorpaint/commit/394ff2199a696c0934e9ce77fcf98f518513e9fd to only mention RTX series as supported. GTX 10 series will continue to work (at least for 2K baking) but I am not sure I can make it work better, sorry.
