### ISSUE TITLE
Asset icon not visible when i use height map in material

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#823]
ArmorPaint.org - v0.8 (2021-02-14) - 743f6d3
Win 10 64 bit

Good night Lubos!
I noticed this error a long time ago, but to be honest, it is not critical at all. So little thing.
But I decided to write about it anyway.
When I use the texture for the Height channel in the material. The material icon becomes a solid gray color.
Here you can see on the print screens.
without
![image](https://user-images.githubusercontent.com/65244629/107994805-6ad25180-6fee-11eb-9cb8-de77782b7b49.png)
and with 
![image](https://user-images.githubusercontent.com/65244629/107994839-7d4c8b00-6fee-11eb-89df-52c0f53f804d.png)
Thank you so much! And I didn't say thank you for the previous answer. Thank you, I now understand everything)

**Comment by MathemanFlo** [comment]
Good morning,
I can reproduce that and would like to add another detail:
Works;
![Screenshot 2021-02-16 075907](https://user-images.githubusercontent.com/28649121/108028938-e6eb8a00-702c-11eb-8811-40a420f319c7.png)
Does not work and it's no issue of Invert but Brightness/Contrast/MixRGB and so on do not work as well
![Screenshot 2021-02-16 075853](https://user-images.githubusercontent.com/28649121/108028933-e4893000-702c-11eb-9ebd-4a1c35abf30c.png)
Works:
![Screenshot 2021-02-16 080215](https://user-images.githubusercontent.com/28649121/108029168-4e093e80-702d-11eb-9743-49e4180569f9.png)
Does not work:
![Screenshot 2021-02-16 080205](https://user-images.githubusercontent.com/28649121/108029169-4e093e80-702d-11eb-9f8a-61aaf3247657.png)

![Screenshot 2021-02-16 080144](https://user-images.githubusercontent.com/28649121/108029170-4ea1d500-702d-11eb-9138-e52fb6de031b.png)

**Comment by AlexKiryanov** [comment]
MathemanFlo good morning! Why do you put a normal map in the height channel? Does it seem wrong to me? This channel should work with black and white cards. But not with normal maps. There is a normal channel for this
But of course I may not understand something. In any case, thanks for your message.)

**Comment by MathemanFlo** [comment]
Of course you are completely right it does not make any sense at all, but it used to work in this case, too (because in the past it did not really matter which "type" you plug in). I just wanted to use a different example than you did (I tried all in Colors and vector menu) and Bump was one of them where it made a difference to plug in something in Normal or not. My intention was to show it is not a bug in Brightness/Contrast or in any color node but the bug is somewhere different. I should have been more clear on this issue. Thank you for pointing it out, maybe it helps.

**Comment by AlexKiryanov** [comment]
Ahhh, but I didn't understand! Thank you!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вт, 16 февр. 2021 г. в 10:14, MathemanFlo <notifications@github.com>:

**Comment by luboslenco** [comment]
Should work better after https://github.com/armory3d/armorpaint/commit/a8d73de922be5a4dfc1c25f7588dc84631a312de, many thanks for report!
