### ISSUE TITLE
tif extension not in filter list of file picker dialog

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#825]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-02-16) - b2757fc

**Issue description:**
I refer to #749 and 43562d6 you created an auto enable feature for plugins. I checked out the ArmorPaint repository some minutes ago and realized that the tif extension is not in the filter of the filer picker dialog (only jpg, png, ... are). If I force ArmorPaint to load a tif it does indeed automatically enable the tif plugin and add the two missing extensions (tif, tiff). I think you should add tif and tiff to the default list of texture extensions and probably also some other extensions, too. Otherwise - imho - the auto enable feature is nice to have but somewhat useless.

**Steps to reproduce:**
1. Fresh ArmorPaint without ever having used tiff
2. Browse textures, tiff extension is missing
3. Either enable plugin by hand or force ArmorPaint to import a tiff -> extension is added and texture is loaded.

**Comment by luboslenco** [comment]
If you drag and drop the image into ArmorPaint (that way one can also have image node auto-generated in the canvas) it will get auto-enabled, but to show up in the filters list the plugin has to be enabled already. :(

If the "unable to import tiff" issues keep popping up I will proceed to hack it into the filter list somehow. The reason it's not enabled by default is to retain the fast startup speed.

**Comment by MathemanFlo** [comment]
Sorry, I'm unsure whether I understand you incorrectly or whether I explained it the wrong way.
Initial situation: no tif-extension there, tiff-plugin not loaded
![Screenshot 2021-02-16 095915](https://user-images.githubusercontent.com/28649121/108040614-d1329080-703d-11eb-8f00-5a9ffa740ea9.png)
Now I enforce ArmorPaint to load a tif via:
![Screenshot 2021-02-16 100006](https://user-images.githubusercontent.com/28649121/108040687-e9a2ab00-703d-11eb-8710-23d000e2e61f.png)
Now I can select the tif file and it loads happily (because the plugin is auto-enabled).
My conclusion: Adding .tif and .tiff to the filter and selecting it is equivalent to forcing ArmorPaint to load a tif file. Right? Thus I thought it would be a good idea to do so.
