### ISSUE TITLE
Soft Erase appear mixed black

### ISSUE THREAD

**Issue by ZAQraven** [armory3d/armorpaint#828]
ArmorPaint.org - v0.8 (2021-02-19)
Win 10 64bit

Issue description:
Soft erase appear mixed black instead of mixed transparent

Steps to reproduce:
1. Create a new layer.
2. Lowering the hardness then draw.
3. Erase (with lowering hardness).
![Bug](https://user-images.githubusercontent.com/79313756/108500846-f4ca3500-72e2-11eb-9ecc-73c5c4abbb2e.png)

**Comment by luboslenco** [comment]
Fix incoming together with https://github.com/armory3d/armorpaint/issues/670, thanks for report!
