### ISSUE TITLE
Reimport mesh not working

### ISSUE THREAD

**Issue by Texumin** [armory3d/armorpaint#829]
**ArmorPaint version:**
ArmorPaint_08dev_win64

**OS/device including version:**
Windows 10 Home 20H2

**Issue description:**
Using "Reimport mesh" yields an invisible/non existent mesh. The only material slot left to select for the layers is one named after the imported mesh. Applying the layers to this will freeze the program.
The file I am trying to reimport is located in the original location and is unchanged. Unfortunately reimport will not work with a changed model (UV update) either.

**Steps to reproduce:**
![Screenshot_10](https://user-images.githubusercontent.com/79343332/108577440-60cb8e00-7321-11eb-8301-cf5bb3e1ae77.png)
My project opened and so far intact.

![Screenshot_11](https://user-images.githubusercontent.com/79343332/108577452-6f19aa00-7321-11eb-8602-6540e3dca5a8.png)
My project after hitting "Reimport Mesh".

![Screenshot_12](https://user-images.githubusercontent.com/79343332/108578432-ef8cda80-7322-11eb-87a4-4eca8f03ba56.png)

After setting Layer 32 to "Shared". The UI is unresponsive.

EDIT: Attached correct image 3.

**Comment by luboslenco** [comment]
Hi, pushed a fix at https://github.com/armory3d/armorpaint/commit/6109a3ae240c55e7ecdea9a9c10779f71eb3d175 - thanks for report! Desired `split by` type can now be selected when reimporting the mesh.  New builds up soon.
