### ISSUE TITLE
Adjust transparency for individual layers

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armorpaint#83]
([origin](https://twitter.com/k44devStudio/status/1108774764288581632))

**Comment by Granada1** [comment]
That sounds cool 😎

**Comment by luboslenco** [comment]
Added a per-layer opacity slider!

![1a](https://user-images.githubusercontent.com/3685704/56294493-6c4d3d00-612b-11e9-90ec-c98f618c12d2.PNG)

**Comment by Calpal3D** [comment]
Expanding on this topic, is it possible to make adjustments to layers? For example, change the hue or saturation of a layer's diffuse base colour?
