### ISSUE TITLE
mesh is weird and transparent in weird parts

### ISSUE THREAD

**Issue by Maithesnail** [armory3d/armorpaint#830]
Im not able to import my mesh withouth weird transparency/loss of tris. I dont know what is wron. I fixed the cape before and it just persist.

![model1](https://user-images.githubusercontent.com/79380216/108607973-6af69680-73cc-11eb-9fde-c060d0c446cf.PNG)
![model2](https://user-images.githubusercontent.com/79380216/108607975-6c27c380-73cc-11eb-94ad-7e161f6f1f6e.PNG)
![modelblend1](https://user-images.githubusercontent.com/79380216/108607977-6c27c380-73cc-11eb-80f2-b93bb65ac137.PNG)
![modelblend2](https://user-images.githubusercontent.com/79380216/108607979-6cc05a00-73cc-11eb-9ccf-df4d8ed4dd6d.PNG)

**Comment by MathemanFlo** [comment]
Just a wild guess: Are there triangles with flipped normals? ArmorPaint has a view option: Viewport -> Cull backfaces to show/hide back faces. If this resolves the problem then it is a problem with your mesh.

**Comment by luboslenco** [comment]
Hello, also check here for details https://github.com/armory3d/armorpaint/issues/807.
