### ISSUE TITLE
Export a material without merging layers

### ISSUE THREAD

**Issue by na2axl** [armory3d/armorpaint#831]
*ArmorPaint 0.8-54fb27a, Windows*

Hi @luboslenco, and thank you for this promising tool. I've just bought the software on Gumroad and I'm really happy with it 😃.

While using it I've seen that the layers system allow a lot of customizations and a better workflow, things we lose when we merge them at the time to export the material (the one built from the set of layers). So I wanted to know if there is a possiblity to export a material without merging those layers. I think like that it will let the users to manage their layers as they want without forcing them to merge something, and also will provide an iteration workflow (for example in my case, I want to paint a model using a lot of layers, bake the material, preview in the game engine, if it's not OK, return to ArmorPaint, edit/remove/add layers, bake the material, preview in the game engine, etc..., until I'm satisfied with the result).

**Comment by AlexKiryanov** [comment]
Good day! You can export material without merging layers.

**Comment by na2axl** [comment]
@AlexKiryanov this is a good news! Sorry but I'm not able to figure how to do this? Can you share the details please ? Thanks.

**Comment by AlexKiryanov** [comment]
https://youtu.be/nuzooiT7rJk like this
or that https://youtu.be/J48b4CfLiEk

**Comment by na2axl** [comment]
@AlexKiryanov thanks for your videos. I've found how to do it.
