### ISSUE TITLE
Problem importing texts from SVG format and image reimport problem.

### ISSUE THREAD

**Issue by Almisuifre** [armory3d/armorpaint#832]
*ArmorPaint 0.8-54fb27a, Windows*

**Issue description:**
Hello,
I encounter 2 problems with the version of armorque I use.

Case N ° 1: I use the * .SVG format to keep the maximum quality. I have looked at my files with Gimp, as well as other software, the text displays fine. But in Armor, no.
[ArmorSVG-Bug.zip](https://github.com/armory3d/armorpaint/files/6017376/ArmorSVG-Bug.zip)

Case N ° 2: When I reload an image, (right click> reimport), the application crashes directly without loading anything.

**Steps to reproduce : Case N ° 1**
1 / Create an image in Canvas
2 / Export in * .SVG format
3 / Open Armor
4 / Drag / Drop from the texture library
5 / Notice that the text is missing.

**Steps to reproduce: Case N ° 2**
1 / Right click on a texture
2 / Choose reimport
3 / Crash

I am sending you files for study.

Thanks for your feedback.

**Comment by luboslenco** [comment]
Hello, many thanks for report!

> Case N ° 1: I use the * .SVG format to keep the maximum quality. I have looked at my files with Gimp, as well as other software, the text displays fine. But in Armor, no.

Hm, it looks like that [nanosvg](https://github.com/memononen/nanosvg) library which ArmorPaint uses does not support the text yet, sorry. But ArmorPaint has to rasterize the .svg file, so importing a .png should yield the same result.

> Case N ° 2: When I reload an image, (right click> reimport), the application crashes directly without loading anything.

Pushed a fix at https://github.com/armory3d/armorpaint/commit/075191eccc812b0cb62aed95135c67e3c383412e.

**Comment by Almisuifre** [comment]
Thanks @luboslenco for watching.

It's a shame for the library. Okay, there is a way to hijack.

I'm still looking for the right relationship between my textures to avoid too pixelated. It is not won the first time. We do what we can. I will resume my work with images and not, svg.

Thanks for the fix on the reimport. I trust the software will continue to advance.
