### ISSUE TITLE
Could not load krom.js, aborting: Windows 10, Visual Studio 2019

### ISSUE THREAD

**Issue by SpannerLM** [armory3d/armorpaint#834]
Command argument ..\..build\krom is set in "Project - Properties - Debugging".
Compiled latest source to Releasex64 in VS 2019 with no issue.
Upon trying to launch, I get this:

'Krom.exe' (Win32): Loaded 'D:\armorpaint\armorcore\build\x64\Release\Krom.exe'. Symbols loaded.
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\D3DCompiler_47.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dinput8.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'Krom.exe' (Win32): Unloaded 'C:\Windows\System32\msvcrt.dll'
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\winhttp.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\dbghelp.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\InputHost.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. 
Could not load krom.js, aborting.
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'Krom.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'Krom.exe' (Win32): Unloaded 'C:\Windows\System32\kernel.appcore.dll'
The thread 0x2164 has exited with code 1 (0x1).
The thread 0xe84 has exited with code 1 (0x1).
The thread 0x2d9c has exited with code 1 (0x1).
The thread 0x2ef8 has exited with code 1 (0x1).
The program '[11472] Krom.exe' has exited with code 1 (0x1).

Any ideas?

**Comment by luboslenco** [comment]
Hello, the argument should be `..\..\build\krom`, not `....build\krom`.
