### ISSUE TITLE
Failed to build project from source

### ISSUE THREAD

**Issue by ryadhiprasetya** [armory3d/armorpaint#835]
i'm trying to build armor paint from source and get this error while building on vs 2019

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj	Krom	C:\Users\ryadhi\Work\ap_build\armorpaint\armorcore\build\v8_monolith.lib(default-platform.obj)	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in main.obj	Krom	C:\Users\ryadhi\Work\ap_build\armorpaint\armorcore\build\v8_monolith.lib(default-platform.obj)	1	

Severity	Code	Description	Project	File	Line	Suppression State
Warning	LNK4098	defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library	Krom	C:\Users\ryadhi\Work\ap_build\armorpaint\armorcore\build\LINK	1

**Comment by luboslenco** [comment]
See https://github.com/armory3d/armorpaint/issues/719.
