### ISSUE TITLE
Problem with baking normal map in blender file

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#837]
ArmorPaint.org - v0.8 (2021-02-23) - 9da4f07
Win 10 64bit

Hello Lubos! Another error popped up by accident. One ArmorPaint user helped me with this. Here's a part of the young model.
If I import the model as a blender file. Then a strange thing happens when baking normal maps. If this file is exported to fbh, then the problem disappears. Only those problems remain that I mentioned in my report #437 

file attached
blend file
![image](https://user-images.githubusercontent.com/65244629/109177900-5a159e80-7799-11eb-9e7b-ba39695e54b1.png)
fbx file
![image](https://user-images.githubusercontent.com/65244629/109177980-6d286e80-7799-11eb-8f1d-8ba6e12b99f1.png)
[test.zip](https://github.com/armory3d/armorpaint/files/6044076/test.zip)

Thank you so much! and have a good evening!

**Comment by luboslenco** [comment]
Fix coming together with https://github.com/armory3d/armorpaint/issues/437.
