### ISSUE TITLE
Extracted el.json file doesn't contains Greek translation.

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#838]
Trying to extract_locales.py el, the json file dosen't contains previous Greek translation. Only an English template.

ArmorPaint.org - v0.8 (2021-02-26) - 381f7d0
Windows 10 - Direct3D 11
Intel(R) HD Graphics 620

**Comment by MathemanFlo** [comment]
I tried this as well for the German and Greek locale and I can not reproduce it on ArmorPaint.org - v0.8 (2021-02-26) - 381f7d0 Win10.

**Comment by infinder** [comment]
Thank you MathemanFlo..
Well, It looks like I am totally wrong!
While i am in armorpaint folder, I execute this command from cmd: python ./Assets/locale/tools/extract_locales.py el
What am I doing wrong?

**Comment by MathemanFlo** [comment]
I don't know, but I do the following in cmd:
![Screenshot 2021-02-26 175151](https://user-images.githubusercontent.com/28649121/109329809-55b1ba00-785b-11eb-98a5-2d5d1aef2322.jpg)
Maybe checkout ArmorPaint repository again and retry?

**Comment by infinder** [comment]
You are right. Thank you for your help.
