### ISSUE TITLE
Cavity masking

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armorpaint#84]
([origin](https://twitter.com/nezumiblog/status/1108780939688198145))

**Comment by Magi-max** [comment]
Good suggestion, it is already possible to create procedural masks with nodes, but edge detection seems doesn't work in eevee. https://www.youtube.com/watch?v=KSOMqOmnwEY

**Comment by luboslenco** [comment]
Sadly the origin tweet got deleted and I did not include a copy here. There are some possibilities now:
- Using curvature bake for edge masking ([video](https://youtu.be/qNHeNetQNvE?t=156))
- Using low-radius AO baking to bake cavity map in ArmorPaintDXR build
