### ISSUE TITLE
Tiled textures

### ISSUE THREAD

**Issue by Blenderwizard62** [armory3d/armorpaint#842]
I recently purchesed armor paint and was wondering if It was possible to paint a texture as tiled but not based on the uv map. If you have used blenders painting tool then you will know that you can add a texture map and then tile it but not have it based off the uv map. If armor paint can do this  say so, thank you for your time. also your program is great!

**Comment by AlexKiryanov** [comment]
Hi! I read the question and it became interesting to me. And what kind of texture tiling method is not based on the UV? Or I misunderstood the question. My English is bad.  Can you post a link to the video, what do you mean?

**Comment by Blenderwizard62** [comment]
https://user-images.githubusercontent.com/78112342/110175110-d8d89000-7dc6-11eb-9a4c-dbab1d33d30b.mp4

I think I posted a demo video if it dosn't work please say so.

As you can see in the first clip the seems are very visable, in the second clip you can see the texture is painted on the UV map but not showing the seems. In the end I demo the to maps and the differences, between the two of them. As you can see it still paints based on the uv maps but dosn't show the seems.

**Comment by Blenderwizard62** [comment]
Did my response post?

**Comment by AlexKiryanov** [comment]
Hey! Sorry! Dropped out of my head. If I understood correctly what you need, then here it is. Switch texture coordinates mode to projection and draw. https://drive.google.com/file/d/12CHT0sxqmf2OJhmfytir6Sxyrip6ensT/view?usp=sharing

**Comment by Blenderwizard62** [comment]
Thank you so much! That is a great help, also I whanted to tell you that I found drawing tablets don't work to well. I'd love to help with development, but I can't code so if I can help in any other way let me know!

**Comment by luboslenco** [comment]
More tablet drawing improvements still on the radar. :) Thanks for posting!
