### ISSUE TITLE
Painted Clone Places brocken after reload the file.

### ISSUE THREAD

**Issue by Somamint** [armory3d/armorpaint#845]
**ArmorPaint version:**

**OS/device including version:**

**Issue description:**

I used the clone tool to get rid of seams. Which worked perfect. But after reload the file it looks like this.

https://i.postimg.cc/Px2S8S8D/Bildschirmfoto-von-2021-03-09-00-32-46.png

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Hello, sorry but I need the steps to reproduce and ideally os / armorpaint version info to be helpful. (ie. whether reloading the file means saving and loading .arm file or reimporting the mesh file iself.)

**Comment by Somamint** [comment]
Hello i'm using POP!OS 20.10

Armorpaint v. 0.8 
And it happend when i loading the arm file.
