### ISSUE TITLE
Navigate in Blender mode and quickly center the camera on the object to be painted.

### ISSUE THREAD

**Issue by Almisuifre** [armory3d/armorpaint#846]
Hi
I am using the Blender navigation interface.
I didn't notice that we could focus on a particular object in a complex scene. I am using UDIMs to separate my objects.
*ArmorPaint 0.8-fc7ae2d, Windows*

**Feature description:**
Would it be possible to add the following command line:
1 / Select the UDIM
2 / Press the "." Key or "delete" from the numeric keypad.
3 / This will place the camera and the pivot on the selected object in order to paint it.

or :
1 / Select All
2 / Press the "." Key or "delete" from the numeric keypad.
3 / This will place the camera and the pivot on the whole of the selected scene in order to paint it.

Exemple in pdf file :  [Feature Request 1.pdf](https://github.com/armory3d/armorpaint/files/6136459/Feature.Request.1.pdf)

It is also possible to adapt this solution for normal mode.

Thank you

**Comment by luboslenco** [comment]
Hi, many thanks for report! Feature coming together with https://github.com/armory3d/armorpaint/issues/251.

**Comment by Almisuifre** [comment]
Thank you very much :)
