### ISSUE TITLE
Clamp option not working

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#848]
Win 10 64 bit
ArmorPaint.org - v0.8 (2021-03-14) - 8b02721

Hello!)
Haven't written for a long time ...
Honestly, I often encountered this problem, but did not attach any importance to it. But ... now I ran into it again.
When mixing different procedural textures, the minimum and maximum values are not between 0 and 1. This seems normal to me. Therefore, there is a Clamp function that allows you to cut off all values that are not in this interval. But that's the trouble.
Look at this please.
Here is the procedural noise that I got from mixing several noise textures.
![image](https://user-images.githubusercontent.com/65244629/111873340-eaae5b80-89a0-11eb-8096-04f57700c1d6.png)
If I use this result to create a normal map via a bump node, I end up with this result.
As you can see, where the color is black, there should have been no irregularities. But they are. Even if I use the checkmark Clamp
![image](https://user-images.githubusercontent.com/65244629/111873420-45e04e00-89a1-11eb-9adc-1e8e6bfcee2f.png)
And this is the result with the clamp node that I just made to check this error.
As you can see, where there is a black field, there is no relief.
![image](https://user-images.githubusercontent.com/65244629/111873506-9f487d00-89a1-11eb-8762-20bb1ff56854.png)
Or maybe I'm doing something wrong?

P.S. This error does not apply to the Bump node. He's wonderful! This applies to mathematical operations in nodes.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/cb6dd45c5696cd6915d690251bf6471273974832, thanks for report! Happy to hear about the Bump node.🙂

**Comment by AlexKiryanov** [comment]
good news) thanks for fixing it.

вс, 28 мар. 2021 г., 18:54 Lubos Lenco ***@***.***>:
