### ISSUE TITLE
[Request] Disable Painting Only On Visible Faces

### ISSUE THREAD

**Issue by TakUser** [armory3d/armorpaint#849]
An issue I've had with ArmorPaint as PBR texture painting software for a while now is the aliasing artifacts that appear when you're trying to paint a mesh with part of its surface facing away from the camera.  In something like Substance Painter when you have a large brush and you're painting the edges of what's visible, the brush correctly wraps around 
surfaces and doesn't produce any visible aliasing artifacts.

**Comment by luboslenco** [comment]
Hello, thanks for report! It should be doable by disabling `Depth Reject` and `Angle Reject` options in `Preferences - Usage`. I have also pushed a fix so these options will get saved in the config now https://github.com/armory3d/armorpaint/commit/a3771087c033fff2224d61af70f88dc5f1c5c2a9.
