### ISSUE TITLE
Armor paint don't work again

### ISSUE THREAD

**Issue by Noahthenoob53** [armory3d/armorpaint#85]
Hello sry for annoying but i wanted to try armor paint the git version out and I have some problems. I followed every step but armor paint don't start in blender. It gives me an error:

D:\Armory engine\Armory\armsdk\Kha\Tools\haxe\std/haxe/io/Input.hx:189: characters 37-42 : Uncaught exception Eof
C:\Users\Noah\Desktop\armorpaint-master\Sources/arm/Macro.hx:13: characters 27-49 : Called from here

C:\Users\Noah\Desktop\armorpaint-master\Sources/arm/App.hx:10: lines 10-580 : Defined in this class

Haxe compiler error.
Finished in 20.667096376419067
Build failed, check console

I really hope that someone can help me!!

Have a good day!

**Comment by luboslenco** [comment]
Hello,

You need to clone the repository using `git clone https://github.com/armory3d/armorpaint` like specified in the instructions. (And I need to edit the readme to double-emphasize that.)

**Comment by Noahthenoob53** [comment]
Hey lubos!
I tried it out and I really need help with the manual cloning.

https://github.com/armory3d/armsdk

I don't know where i have to put the link.

**Comment by vitlav** [comment]
I just clone --recursive https://github.com/armory3d/armortools.git and got the same old error when build ArmorPaint:
```
cd armorpaint
../armorcore/Kinc/make --from ../armorcore -g opengl --compiler clang --compile
...
Compiling shader 2 of 3 (voxel_pos.geom.glsl).
Compiling shader 3 of 3 (voxel_pos.vert.glsl).
/tmp/armortools-0.9/armorcore/Tools/haxe/std/haxe/io/Input.hx:189: characters 37-42 : Uncaught exception Eof
/tmp/armortools-0.9/base/Sources/arm/sys/BuildMacros.hx:19: characters 27-49 : Called from here
/tmp/armortools-0.9/base/Sources/MainBase.hx:20: characters 26-43 : Called from here

Haxe compiler error.
Error: kfile did not call resolve, no project created.
error: Bad exit status from /tmp/.private/lav/rpm-tmp.91485 (%build)

```

**Comment by Pro-pra** [comment]
Yes, i also have error: Uncaught exception Eof
