### ISSUE TITLE
Viewport is not updating if you draw on canvas or veiwport

### ISSUE THREAD

**Issue by Benc73** [armory3d/armorpaint#850]
If I try to paint something for a roughness map it is not updating the changes in the 3D Viewport.
I made i Video where you can see the problem!

https://user-images.githubusercontent.com/81378668/112508569-f67a9300-8d8f-11eb-92b2-8c172a079df9.mp4

*ArmorPaint 0.7-10c63f2, Windows*

**Comment by luboslenco** [comment]
Hi, thanks for report. Please use the latest 0.8dev version, should work better. :)
