### ISSUE TITLE
Color space option for exported textures

### ISSUE THREAD

**Issue by sacrish** [armory3d/armorpaint#851]
The exported base color map is linear by default, and cannot seem to be changed. Although this is not a huge problem, it would be nice if there are color space options for exporting.

**Comment by luboslenco** [comment]
Added `Color Space` option in `Export Textures... - Presets tab`, thanks for suggestion! https://github.com/armory3d/armorpaint/commit/0a3cd8777ecd39c9f93a2715f858ca60894ddd12
