### ISSUE TITLE
Shader node?

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#852]
Hello Lubos! Again!
What is this node? More precisely from the name it is clear that the shader.
Is this a glsl shader? Can I use a standard code - an example how can I use it? 
How do I set up a sampler? How to get texture resolution.

**Comment by luboslenco** [comment]
Hi! Yes, it can be used to inject glsl shader code. I recommend writing [custom material node](https://github.com/armory3d/armorpaint/blob/master/Assets/plugins/hello_node.js) instead, as the shader node does not support adding inputs yet.

**Comment by AlexKiryanov** [comment]
Hello) thanks for the answer. well. but I remember that in a custom node I cannot use a sampler 2d to control the uv coordinates. or is there already such a possibility? if possible, you can send me an example.

**Comment by AlexKiryanov** [comment]
Hello Lyubos! The question is, how can I set such a function? I mean, if such operators? (I mean void)
void pR(inout vec2 p, float a)
{
    float sa = sin(a);
    float ca = cos(a);
    p *= mat2(ca, sa, -sa, ca);
}

as example frag.add_function("vec3 void pR(inout vec2 p, float a) { float sa = sin(a); float ca = cos(a); p *= mat2(ca, sa, -sa, ca); }");
