### ISSUE TITLE
Single click on UI buttons with tablet pen behaves as dragging

### ISSUE THREAD

**Issue by sacrish** [armory3d/armorpaint#853]
**ArmorPaint version:**

0.8 (2021-03-11)

**OS/device including version:** 

Windows 10
Wacom Intuos Pro tablet

**Issue description:**

When I use the pen to click a button, for example a layer icon, I end up dragging that layer instead. Apparently to perform a "real" single click, I have to actually double click with the pen (e.g. toggle layer visibility). 

Painting on object is without issue. So I think this behavior only happens with UI buttons.

Not sure if this is intentional. If so, I wish there could be an option to turn this feature off.

**Comment by ABugNamedBeetle** [comment]
can we add the support for WinTab

**Comment by ABugNamedBeetle** [comment]
can you pls point out the code responsible for getting the pen coordinate and pen pressure.

**Comment by luboslenco** [comment]
Fixed in latest 0.9dev builds. If you spot more issues please let me know.
