### ISSUE TITLE
 Impossible to pick a color after several uses  ID color tool.

### ISSUE THREAD

**Issue by AgasferLukich** [armory3d/armorpaint#854]
*ArmorPaint 0.8-fc7ae2d, Windows*

**Issue description:**
 Impossible to pick a color after several uses  ID color tool.
 Аfter reloading the project, you can select a color, but only once. Then you need to reload the project again.
However, after 4-5 reloads of the project, the color selection became completely impossible.
When using the ID tool, nothing happens and the "clear" function does not change the situation.

**Steps to reproduce:**
It is necessary to use the tool several times after loading color ID  map  and use  materials on several parts with Different color ID.

**Comment by luboslenco** [comment]
Hello, many thanks for report! Does reloading the project mean saving it into `.arm` file and then opening it instantly via `File - Open...` menu?
