### ISSUE TITLE
Admod for Armory, to become professional

### ISSUE THREAD

**Issue by blenderrendertester** [armory3d/armorpaint#855]
This is one the the main reasons why more people don't use armory as a full time game dev tool.... You can't monetize your project.
I have been looking into this for the past few weeks and have found a few maybe possible ways of doing this but they all involved library injection or adding Admod SDK to android studio.

What I'm trying to say is that if we can't monetize our games for android then people are going to choose other game engines that can...

So if the is one thing I would ask, it's that you can integrate an Admod support for armory.
If you could do this, I will be able to get more people to join this incredible community. And I will continue to organize more game jams and youtube tutorials.... But if I can't get any advertising revenue in return the I too will have to switch to a different game engine 🥺🙏🙏🙏

**Comment by luboslenco** [comment]
Hello, please use the https://github.com/armory3d/armory repository for armory engine related issues. Related: https://github.com/laxa88/wyn-kha-lib/tree/master/wyn_admob.
