### ISSUE TITLE
Rotation matrix in custome node

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#856]
Lubos, good evening! Can you answer my question regarding rotation matrices. I don't know why, but the code doesn't work with them.

// Node shader
arm.MaterialParser.customNodes.set(nodeType, function(node, socket) {
let frag = arm.MaterialParser.frag;
let Base = arm.MaterialParser.parse_vector_input(node.inputs[0]);

frag.add_function("vec2 pR(vec2 p, float a){\
float sa = sin(a);\
float ca = cos(a);\
p *= mat2(ca, sa,-sa, ca);\
return p;}");

frag.write(`
vec2 uv = ${Base};
vec2 col = pR(uv, 30.);
`);
return `vec3(col,0.)`;
});

although everything works without a matrix. Do I have to set it like a function? Yes?
The glsl code is working, I checked it.
Please, it is very difficult for me to understand this ... without your help.

**Comment by AlexKiryanov** [comment]
Hello Lubos! Can you answer me?

**Comment by luboslenco** [comment]
Hi! Ah, the matrix multiplication needs to be done like this:

`p = mul(mat2(ca, sa,-sa, ca), p);`

That way the shader gets correctly translated to HLSL. I have added a note here: https://github.com/armory3d/armorpaint/wiki/Plugins, thanks for mentioning this.

**Comment by AlexKiryanov** [comment]
Good day! Thank you very much!)
