### ISSUE TITLE
UI bug in Distract free mode

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#857]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-01) - 1b7e131

**OS/device including version:**
Win64

**Issue description:**
The distract free mode (f11) has UI issues if the Shader node editor (or layer view) is opened.

**Steps to reproduce:**
1. Open the shader editor
2. Press F11
3. The Shader editor as well as the right side bar stays (in contrast to the situation where the Shader editor is closed and I press F11)
4. The Shader Editor is usable, the right sidebar's UI is disabled? (which makes sense if it would be hidden, too) And not repainted. E.g. if I open the search for a shader node search bar it covers parts of the right sidebar and if I close it parts of it remains.
5. Also if I click on the "gap" between the Shader editor and the main view to change their sizes I can not stop resizing.

![ap](https://user-images.githubusercontent.com/28649121/113257550-0e3fa300-92cb-11eb-8a9e-ef83e4ab1055.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/5f087ce57ef76e5f8c64b7b34d36fae35beaef69, thanks!
