### ISSUE TITLE
UI malfunction after creating new texture export preset

### ISSUE THREAD

**Issue by sacrish** [armory3d/armorpaint#859]
**ArmorPaint version:**

1b7e131 - Cleanup

**OS/device including version:**

Windows 10

**Issue description:**

After creating a new texture export preset, the program window breaks. UI elements get misplaced, and cannot be interacted with.

![Screenshot 2021-04-01 170418](https://user-images.githubusercontent.com/8361680/113271396-10c2ec80-930d-11eb-869d-8a623f1258a9.png)

The issue doesn't happen with the 2021-3-11 build I got from Gumroad. I'm not sure if it's related with how I built the program on my own.

**Steps to reproduce:**

1. Export textures
2. Switch to preset tab
3. Click 'New' and 'OK'
4. Issue happens

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/a806bd940d0189cb20a5521a1f7784ef32e82d19, many thanks for report!
