### ISSUE TITLE
Build error in armory type missing armory.math.Vec4

### ISSUE THREAD

**Issue by Hellzbellz123** [armory3d/armorpaint#86]
Previous issue is slightly different 
armorpaint 8.07/8.011
latest itchio armory build
will try github directly

C:\Users\Smith\Desktop\Portable Nerd Tools\Armory\Projects\armorpaint-18.07\Sources/arm/logicnode/BrushOutputNode.hx:5: characters 8-24 : Type not found : armory.math.Vec4
Build failed, check console

**Comment by luboslenco** [comment]
`armorpaint-18.07` - something is wrong here, that sounds like ancient v0.4 version. Please follow the instructions here:
https://github.com/armory3d/armorpaint/blob/master/README.md

**Comment by Hellzbellz123** [comment]
im retarded, i updated the SDK wrong cause i suck with git. i updated it the way it said and it worked 
thanks for the help <3

**Comment by luboslenco** [comment]
Yay, glad it worked! 🙂
