### ISSUE TITLE
arma\armorpaint\armorpaint\armorcore\Sources\AndroidFileDialog.cpp:7:10: fatal error: 'Kore/Android.h' file not found

### ISSUE THREAD

**Issue by dkostarnov** [armory3d/armorpaint#860]
arma\armorpaint\armorpaint\armorcore\Sources\AndroidFileDialog.cpp:7:10: fatal error: 'Kore/Android.h' file not found - why? 
I installed NDK
![image](https://user-images.githubusercontent.com/73770663/113284707-11528780-92fb-11eb-9d8a-dcdfc497e77e.png)

**Comment by luboslenco** [comment]
Thanks for report. I have fixed the compile error at https://github.com/armory3d/armorcore/commit/80171d9b030ce20895e20e165887799d1adba09b, but still recommend the desktop builds until the Android build process gets properly managed.
