### ISSUE TITLE
Decal Tool

### ISSUE THREAD

**Issue by DangerDraper** [armory3d/armorpaint#865]
*ArmorPaint 0.8-95aca19, Windows*

Decal not visible when live painting on model but will display on model when painting painting Decal straight to 2D Map.  Same happens for Masking.

Experiencing the same in DXR 0.8

Here's the decal
![Tattoo_Anchor](https://user-images.githubusercontent.com/29082783/114814301-41b81c80-9df7-11eb-9d30-9c84b6cddae1.png)

And both apps

https://user-images.githubusercontent.com/29082783/114814735-2699dc80-9df8-11eb-9758-492a4a5ab20b.mp4

**Comment by AlexKiryanov** [comment]
![image](https://user-images.githubusercontent.com/65244629/114836450-571f4d80-9ddb-11eb-91b7-747a889e89a2.png)
strange but I don't have such a problem

**Comment by MathemanFlo** [comment]
I also can not reproduce it on ArmorPaint.org - v0.8 (2021-04-15) - a8673d9 Windows Dx11 non DXR

**Comment by DangerDraper** [comment]
Only started after DL'ing 0.8 update today. Initially thought I hadn't checked a setting but fired up 0.7 and it was the same.
I'd been using 0.7 15mins before with no issues. Thought it may have been my rig but been fault finding for hrs and everything is checking out.
Honestly don't know where else to turn

**Comment by luboslenco** [comment]
Should be resolved via https://github.com/armory3d/armorpaint/commit/d21dc8efecc0a0e73f15c2dbcb70e9791bce00ee, thanks for report. The issue was only present with 'Live Brush Preview' option enabled.

**Comment by DangerDraper** [comment]
Thanks Lubo! Keep up the good work
