### ISSUE TITLE
Materials change on texture reimport

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#867]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-18) - 4597bee

**OS/device including version:**
Win 10 x64

1. Create some pbr material like 
![ap1](https://user-images.githubusercontent.com/28649121/115142402-e5950880-a041-11eb-846b-b1d452463197.jpg)
2. Now reimport e.g. the base color texture, as the file itself didn't change nothing should happen
3. ArmorPaint reimports the file but also changes the image texture nodes
![ap2](https://user-images.githubusercontent.com/28649121/115142449-15dca700-a042-11eb-980b-dcf69efa2257.jpg)

And this is extremly annoying if one frequently reloads some textures.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/27281c51c755f54c2f5bb3b792e622545ee63d5b, thanks for report!
