### ISSUE TITLE
Wrong handling of long names and lists

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#869]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-18) - 4597bee

**OS/device including version:**
Win10x64

**Issue description:**
Having long names and lists in ArmorPaint is a real pain and sometimes incorrect

**Steps to reproduce:**
1. Textures with long file names get truncated by ... but not only for display purposes but the name gets actually truncated.
![ap3](https://user-images.githubusercontent.com/28649121/115143495-f9dc0400-a047-11eb-9aa1-c043e1db1072.jpg)
2. Long names are truncated and I'm unable determine the actual name. So it would be nice if the drop down would scale accordingly or some tooltip would show up on hovering to reveal the whole name.
![ap2](https://user-images.githubusercontent.com/28649121/115143530-3445a100-a048-11eb-9cc3-83f8279f2e42.jpg)

3. For instance the math node has a very long list of operations which is nice but depending on the node's positions the drop down menu is too big. Maybe one could make it multi-columned like Blender or simply scrollable. The image node dropdown would also benefit from this. 
![ap1](https://user-images.githubusercontent.com/28649121/115142866-46254500-a044-11eb-9b6e-e9df6d6761ac.jpg)

**Comment by luboslenco** [comment]
Should work a bit better  now in the latest version, thanks!
