### ISSUE TITLE
Reset position in texture view

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#870]
I frequently zoom in and out and drag the texture. By doing this it occasionally happens that I "loose" my texture. This frequently happens when I bake. While baking bigger models ArmorPaint becomes a bit unresponsive so dragging and zooming the texture frequently results into something like this:
![Screenshot 2021-04-19 092403](https://user-images.githubusercontent.com/28649121/115197299-1f711800-a0f1-11eb-91b3-3e2ca9940e30.png)
and I can not find the texture anymore. 
So I propse two things

1. Limit dragging as there is no point in "going away from the texture". Then I can not loose it anymore. This is probably the more elegant solution.
2. OR include a reset button as proposed above similar to reset camera.

**Comment by luboslenco** [comment]
Great suggestion! Fix at https://github.com/armory3d/armorpaint/commit/cf8e18864a3aa2d6e63411b38d4d1f0fa7b796a1.

**Comment by MathemanFlo** [comment]
Hey wow! Thanks for the quick implementation. This is exactly how it should be. I really like it.
Except there is one clunky situation.
1. Pull the texture to the bottom
![ap1](https://user-images.githubusercontent.com/28649121/115537949-a661f400-a29b-11eb-912b-348d4db0ce67.png)
2. Open the shader graph
![ap2](https://user-images.githubusercontent.com/28649121/115537947-a5c95d80-a29b-11eb-9a9f-e237a2eadb2a.png)
3. Now the texture is hidden as expected but I can not pull it into the visible area because panning is blocked as the "texture's y-coordinate" is too big.
