### ISSUE TITLE
Building instructions unclear

### ISSUE THREAD

**Issue by Gpinchon** [armory3d/armorpaint#871]
In the building instructions it says :
> Open generated Visual Studio project
> Set `Project - Properties - Debugging - Command Arguments` to `..\..\build\krom`
> Build and run for x64 & release

Which one ? Is it Krom.sln in ./build/ ?

**Comment by MathemanFlo** [comment]
![Screenshot 2021-04-19 124109](https://user-images.githubusercontent.com/28649121/115223959-a8497d00-a10c-11eb-92db-42e89ddf45eb.png)

**Comment by Gpinchon** [comment]
It would not cost anything to add this precision into the readme, I was a bit lost at first 😅

**Comment by luboslenco** [comment]
Updated at https://github.com/armory3d/armorpaint/commit/ab2e0bb6f43fc58cd99ec08dc336d715301939cf.
