### ISSUE TITLE
Non-deselectable shader node connections

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#873]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-15) - a8673d9

**OS/device including version:**
Win10 DX11

**Issue description:**
In some situations the shader node editor gives me non-deselectable connections

**Steps to reproduce:**
1. Build something like. Just the two nodes. 
![ap2](https://user-images.githubusercontent.com/28649121/115411906-2b91ce00-a1f4-11eb-9af8-2e21eb5ced4c.png)

2. In this case select the Tangent node such that there is a white border
3. double click (!) on some output plugs of the Geometry node.
4. Sometimes but not always you get a non-deselectable connection without any meaningful origin. You can even produce more of them like in the following example by clicking on other plugs. 
![ap1](https://user-images.githubusercontent.com/28649121/115412558-b2df4180-a1f4-11eb-839c-58c620aceefd.png)

**Comment by AlexKiryanov** [comment]
Yes, I agree, and it happens. But to be honest, I don't always get such a result. Seldom. Therefore, I do not focus on this)
I have this when I copy and paste a bunch of nodes.

**Comment by MathemanFlo** [comment]
Yes exactly this is how I produced it the first time and I got it from time to time but I never found out how to reproduce it. Clearly this is a very low priority glitch and there are a few more important bugs than this. But I report everything I encounter because the software is so great. (And I think this is worth mentioning it: I could not crash ArmorPaint for some time even though I really tried and it also didn't destroy my work. So I think it's already very stable)

**Comment by luboslenco** [comment]
Fixed via https://github.com/armory3d/armorpaint/commit/2be697f3fe6f998a7fd6b40370e3cd2baaf69392, great catch! If it still occurs in some instance please let me know.

**Comment by AlexKiryanov** [comment]
Thank you so much Lubos!)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

ср, 21 апр. 2021 г. в 11:55, Lubos Lenco ***@***.***>:
