### ISSUE TITLE
Multiple textures for multiple materials

### ISSUE THREAD

**Issue by skyace65** [armory3d/armorpaint#874]
This is kinda similar to #272 and #537 but I don't think those do exactly what I need, so apologies if this gets marked as a duplicate.

I need what substance painter does if you have a mesh with multiple materials. They're treated separately (you can't paint over one when painting over the other) and generate their own textures on export. These should probably be implemented as options since not everyone would use multiple materials that way.

Thank you for the great program! I'm glad there's an alternative to Substance Painter out there now.

**Comment by luboslenco** [comment]
Hi, thanks for posting! There is a way to assign layers to objects:
https://www.youtube.com/watch?v=ocIPd6sgQBs&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=22

And then when exporting textures, switching the `Layers` combo from `Visible` to `Per Object` should generate separate texture sets per object. Or do you have something else in mind?

**Comment by skyace65** [comment]
That's actually exactly what I need, thank you! I'll close this issue
