### ISSUE TITLE
UI freeze if pasting material nodes in brush shader graph

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#876]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-21) - 277ab01

**OS/device including version:**
Win10 x64 

**Steps to reproduce:**
1. Copy some nodes e.g. RGB node from a material shader graph
2. Open the shader graph of a brush
3. Paste it there
4. ArmorPaint UI freezes
5. The opposite case does not happen, so copying brush nodes to material nodes is possible, ArmorPaint does not freeze but some of them clearly make no sense. There is no point in having a brush "input" node in material

**Comment by AlexKiryanov** [comment]
Hey! Because there is no such node (RGB) in the brush editor, check out the list.
![image](https://user-images.githubusercontent.com/65244629/115680379-2e0f3780-a35c-11eb-9caa-22a99241de9c.png)

**Comment by MathemanFlo** [comment]
yes you are right, but I think one should not be able to paste them there at all.

**Comment by AlexKiryanov** [comment]
I support)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/95cf44107416d9049b3ebfb6fc6b2a0fa50fcb1b, thanks for report.
