### ISSUE TITLE
Modify brush position does not work

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#879]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-22) - 5d7766f

**OS/device including version:**
Win10 x64

**Steps to reproduce:**
I wanted to add a small offset to the brush position but that did not work. Then I realized even the simplest cases do not work e.g.
![ap1](https://user-images.githubusercontent.com/28649121/115693522-4b460500-a360-11eb-9570-5e847cae0937.png)
or
![ap1](https://user-images.githubusercontent.com/28649121/115693714-79c3e000-a360-11eb-83bf-952bfe3b51c0.png)

**Comment by luboslenco** [comment]
Should work after https://github.com/armory3d/armorpaint/commit/5bdd21338c10d8a46ca97aaa08c8747f4ec05555. 👍

**Comment by MathemanFlo** [comment]
Awsome! Thank's a lot. I'll play with the brush nodes in the afternoon.
