### ISSUE TITLE
Cant Build in Visual Studio 2019

### ISSUE THREAD

**Issue by MasSufBD** [armory3d/armorpaint#881]
I install it on my another PC and i got this problem.

![Screenshot (1)](https://user-images.githubusercontent.com/81719876/115711002-33d93d00-a39d-11eb-8980-7d200a4025d9.png)

**Comment by luboslenco** [comment]
Make sure the Visual Studio components are properly installed, so you are able to compile c++ projects. Notice the log - "some build tools may not be found".
