### ISSUE TITLE
Node Group related issues

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#882]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-22) - 5d7766f

**OS/device including version:**
Win10 x64

Node groups are a really amazing feature. By using them I found a few minor issues:

**First issue:**

1. Create a new node group and do a few random things like
![ap1](https://user-images.githubusercontent.com/28649121/115711629-0b891880-a374-11eb-82b1-7f23996c8b29.png)
2. Now redo everything (Ctrl+z) and get 
![ap2](https://user-images.githubusercontent.com/28649121/115711720-2a87aa80-a374-11eb-9e08-d02aeb87c369.png)

This is obviously not correct there should be no close button. Now if I press on the "nodes"-button in Group 1 node, the UI freezes.

**Second issue**

1. Create a new node group
2. Click on the nodes button
3. Press Ctrl+z
4. Now ArmorPaint goes back to the material shader graph view. (As expected)
5. Now open the group menu (the menu to select existing group nodes and to create new ones). The group node is now called "Material 1" or something similar.
6. By repeating the procedure you can create as many "Material 1" groups as you desire. Again the UI can be freezed as described in issue 1.

**Third issue**

1. Create two node groups and put some random nodes in them. To demonstrate a second issue suppose in the end it looks like this
 ![ap1](https://user-images.githubusercontent.com/28649121/115713758-a71b8880-a376-11eb-8f40-45a21dc5c999.png)
2. Give the second group the name of the first one
3. Now the second group's nodes are lost and replaced by the first ones.
4. But if you plug out the renamed node from the MixRGB node and plug in again, the UI freezes.

Motivated by this I tried whether the same name for materials or layers is a problem -> no, not at all.

**Comment by AlexKiryanov** [comment]
![image](https://user-images.githubusercontent.com/65244629/115849849-f5d82980-a42d-11eb-8a7e-6627f82c645b.png)
Hey! This is how it works fine!

**Comment by MathemanFlo** [comment]
I think the first issue here should be linked to #792

**Comment by luboslenco** [comment]
https://github.com/armory3d/armorpaint/issues/792
