### ISSUE TITLE
ArmorPaint crashes if texture reimport fails

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#885]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-23) - 05d9991

**OS/device including version:**
Win10 x64

**Issue description:**
ArmorPaint crashes if it can not reimport texture

**Steps to reproduce:**
There are two variants of the bug
1. Import some texture
2. Save the project and close ArmorPaint
3. Rename, move ore delete the texture
4. Open ArmorPaint and the previous project.
5. The unavailable texture is pink now.
6. Right click on it and try to reimport it -> ArmorPaint crashes

Desired behavior: ArmorPaint does not crash and the best thing to happen would be that the file picker opens with the initial file name as the preselected file name. This would allow for an easy relocation of moved textures. Currently it is not possible to move arm files/textures without breaking the whole project (without deleting all textures and importing them again).

The second variant does not lead to a crash
1. Import some texture
2. Rename, remove, move the texture
3. Reimport
4. ArmorPaint does not crash but the whole UI breaks

**Comment by luboslenco** [comment]
Should no longer crash after https://github.com/armory3d/armorpaint/commit/e33485053254ea159a64be506bf73489f51695f2. The file picker will also get opened now, unfortunately no pre-selected file name yet - however the original file name will be visible in the textures tab context menu, which stays visible while the file picker is open.
