### ISSUE TITLE
v8 monolith.lib

### ISSUE THREAD

**Issue by NothingOle** [armory3d/armorpaint#886]
Hello,
I tried to build armorpaint via the git clone command and done all the installation.
If I try to build it now I get this error: LNK1181 Eingabedatei "v8\libraries\win32\release\v8_monolith.lib" kann nicht geöffnet werden.

Windows 10
Visual Studio Community 2019 16.9.4

**Comment by luboslenco** [comment]
Hello, make sure to unpack the lib, from the instructions:
> Unpack `v8\libraries\win32\release\v8_monolith.7z` using 7-Zip - Extract Here (exceeds 100MB)
