### ISSUE TITLE
Lock UI while baking

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#887]
For bigger models, baking is no instant operation but takes a few seconds. While baking ArmorPaint's UI is not completely responsive. That's why clicking at the wrong place while baking can actually destroy the baked image. Especially when rebaking on a layer that already has the same map type it is often unclear whether baking has completed or not.  
Therefore it would be nice to lock the UI while baking and get a small notification when baking has completed. Eg. a dialog blocks the UI while baking and disappears automatically when finished.

**Comment by AlexKiryanov** [comment]
I support it, it's a good idea. Maybe some kind of progress bar. Or yes a dialog box when finished. Or just the "In Progress" dialog box and then bam change the "Finish" dialog box

**Comment by luboslenco** [comment]
Baking in non-dxr build should be instant now (or at least not allow ui input while baking), was a bug.

**Comment by AlexKiryanov** [comment]
Thanks you Lubos)
