### ISSUE TITLE
UDIM support

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armorpaint#89]

**Comment by luboslenco** [comment]
Preliminary UDIM support can be enabled by checking `UDIM import` option before importing the mesh.

![1d](https://user-images.githubusercontent.com/3685704/56296379-ac61ef00-612e-11e9-8efd-bb475294d5b3.PNG)

**Comment by xtvjxk123456** [comment]
but udim export seem not work like other app(zb,mari)

**Comment by luboslenco** [comment]
@xtvjxk123456 can you paste the mesh file you have trouble with? UDIM is still preliminary like stated above - I will take a look and fix it, thanks.

**Comment by luboslenco** [comment]
Please provide a test file if issue persists in latest 0.7 dev builds. When importing, make sure to select `Split By - UDIM Tile` in the import dialog.

Test file:
https://github.com/armory3d/armorpaint_samples/blob/master/sample_udim.obj
