### ISSUE TITLE
Baking does not update layer icon

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#893]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-27) - e334850

**OS/device including version:**
Win10 x64

**Issue description:**
Baking (e.g. AO) does not update the layer icon.

**Steps to reproduce:**
1. Bake something that bakes to base color on an arbitrary layer.
2. Wait until baking is finished
3. The layer icon is not updated.

![ap1](https://user-images.githubusercontent.com/28649121/116244501-44f0c800-a768-11eb-8540-8cd7837b47d4.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/541998a3dd0b04858da1f0dd572c4f0b2e61f807, thanks for report.
