### ISSUE TITLE
Material tab not working

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#898]
Until now I never really used the Material tab (The one between Paint and Bake). As I understand it, it is there to show a certain material in action. 

1. Why is there a material picker? At least for me it does not do anything. Is it broken or is this intentional?
2. If I view a material M via material tab on a already painted object I see that the color is the base color of M and none of the painted layers. For all other textures I can see that they are not hidden in material tab but only the ones which are on the currently active layer. Eg. suppose we have three layers. I select the middle one, then its normal map is completely hidden but the one from the top and from the bottom is not. 
To make it clearer consider these two images. The normal map is on the 2nd layer and it disappears if I select the 2nd one but stays if I select the first or third one.
![ap1](https://user-images.githubusercontent.com/28649121/116562092-2c68e500-a903-11eb-9db1-170cd602c16b.png)
![ap2](https://user-images.githubusercontent.com/28649121/116562111-2f63d580-a903-11eb-953e-8e59fa18abc0.png)

Why is it done like that?

**Comment by luboslenco** [comment]
Pushed fixes at https://github.com/armory3d/armorpaint/commit/238fa49b40dd4a30d52e55d31faaee3e323a0eef and https://github.com/armory3d/armorpaint/commit/95caa2f560e7e87eba47f7fed5f5c1a396384f41. Only selected material should be taken into account now.

**Comment by MathemanFlo** [comment]
Thank you very much! You are very hard-working today!
