### ISSUE TITLE
Undeselectable node connection

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#899]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-29) - bd2d395

**OS/device including version:**
Win10 x64

**Issue description:**
I found yet another undeselectable node connection. But I really think is is hardly a issue in practise. So I consider this low priority

**Steps to reproduce:**
1. Drag a connection out of an arbitrary socket. 
2. Keep the left mouse button pressed such that the connection does not disappear until you left the node editor on the right side
3. Now you can savely release the left mouse button without cancelling the connection.
4. Duplicate the current material. 
5. Now both materials have a unconnected connection. While the initial one can be plugged into a suitable socket, the other one from the duplicated connection can not.

You see this is really artifical.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/2b6546bab9ee435bc956a1683a3e63506a644d18.
