### ISSUE TITLE
Plugs with two connections by pasting

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#900]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-04-29) - bd2d395

**OS/device including version:**
Win10 x64

**Issue description:**
When copying a shader graph with Material output to another material. The old connections remain.

**Steps to reproduce:**
1. Create a material like this and select both nodes:
![ap2](https://user-images.githubusercontent.com/28649121/116659088-52d56180-a991-11eb-8d0c-8e87e8ba91b6.jpg)
2. Now press Ctrl+C or Ctrl+X to copy or cut
3. Create a new material and paste the copied things. Now you get: 
![ap1](https://user-images.githubusercontent.com/28649121/116659205-84e6c380-a991-11eb-8c93-8b39a163969a.jpg) and the old base color is the one be active. Both can be deselected, so it is just a small, low priority glitch.

Maybe this behavior is also somehow intentional as you can paste and then selectively choose which connections to keep or not.

**Comment by luboslenco** [comment]
Nice! Fix at https://github.com/armory3d/zui/commit/496078bc84afd37cb3822b7919a0d5c7a3131887.
