### ISSUE TITLE
Question about plugins

### ISSUE THREAD

**Issue by MrAdrianPl** [armory3d/armorpaint#901]
Hi I've written a small plugin and I've come into a problem where I have to split the output into two since one of the maps multiplies onto the other. Is there any way to check whether any input is applied to node? I've tried various ways to check is the input value different from the default one but I couldn't make it work properly.

**Comment by AlexKiryanov** [comment]
Good afternoon, Lyubos! I subscribe to the question. Can you tell us if it is possible to check if something is included in the input channel. I tried to use the same comparison method as @MrAdrianPl did, but it didn’t lead to any results.
Thank you so much
