### ISSUE TITLE
complement to cloud access error

### ISSUE THREAD

**Issue by babylone2019** [armory3d/armorpaint#907]
When i try to access cloud asset i got the check your internet connection to acces the coud

i am using v0.8 (2021-05-01)

**windows 10:**
<i7 2600k, 16go ram, rtx2070 -->

**Issue description:**
during the error connection armor paint create a new directory c:\program when the cloud error message appear
This may come from an error in your path while registering the error log file

**Steps to reproduce:**
open an file explorer on c: , delete the program directory (be sure that 's it isempty), on armor paint click on cloud or try to drag and drop an hdri.
You will have the progrm repertory back again

**Comment by luboslenco** [comment]
Thanks for the great info, that helps a lot! Fix incoming at https://github.com/armory3d/armorpaint/issues/864.
