### ISSUE TITLE
Linux Stable latest says update is available

### ISSUE THREAD

**Issue by bhibb** [armory3d/armorpaint#908]
**ArmorPaint version:**

AmorPaint.org - v0.7 (2020-01-03) - 10c63f2

**OS/device including version:**

Linux
Solus 4.2
Budgie

**Issue description:**

When I select "Help -> Check For Updates" I get a message that an update is available, but this appears to be the latest stable version for Linux.

**Steps to reproduce:**

Open the Linux stable version, navigate to "Help", then "Check For Updates" and view the popup dialog which states the user should go to armorpaint.org to download the update.

![image](https://user-images.githubusercontent.com/33728168/117172479-616daf80-adbb-11eb-95f4-6423bf7ff2d5.png)

**Comment by luboslenco** [comment]
Hello, please use the latest 0.8dev build, it's in much better shape compared to 0.7.

**Comment by bhibb** [comment]
That's great advice I'll give it a try! Thank you!

**Comment by bhibb** [comment]
And just like that, the issue I mentioned doesn't exist here! Ha, should I just close this issue, or is it still relevant because it affects the "stable" appimage?
