### ISSUE TITLE
Blur node only respects uv texture coordinates

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#909]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-05) - fad55df

**OS/device including version:**
Win10 x64

**Issue description:**
Blur node only respects uv texture coordinates.

**Steps to reproduce:**
1. Build something like this. Instead of a image texture node you can also use a checker texture or something else:
![ap1](https://user-images.githubusercontent.com/28649121/117194650-a35f1b80-ade4-11eb-821c-fc0fc96a87bb.jpg)
2. Fill a layer with the material. 
3. Now skip the blur node and connect the texture directly with the material output. Fill again and see a completely different result.
4. Now repeat with UV coordinates instead of generated. Now it works as expected. You can repeat the game with all other coordinates, too and get the same result.

**Comment by luboslenco** [comment]
Link together with https://github.com/armory3d/armorpaint/issues/374.
