### ISSUE TITLE
Crashes When Deleting Materials on Linux

### ISSUE THREAD

**Issue by SojanJanso** [armory3d/armorpaint#91]
On Linux (ubuntu) armor paint crashes when I delete a material.
Steps to recreate:
1. Open Armor paint.
2. Create a new material
3. Right click on material in material window under layers
4. Click Delete

ArmorPaint -v0.6(2019-03-29) - git 8304763
Linux - OpenGL

**Comment by SojanJanso** [comment]
Confirmed, no longer crashes.

**Comment by luboslenco** [comment]
Yay, happy to hear!
