### ISSUE TITLE
Color Ramp UI glitch

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#913]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-06) - df25817

**OS/device including version:**
Win10 x64

**Issue description:**
The color ramp has a funny UI glitch if an invalid index is entered.

**Steps to reproduce:**
1. Create a Color Ramp node
2. Type in the index 1 (which is not valid because the current max index is 0) and press enter
3. Now you get something like this
![ap1](https://user-images.githubusercontent.com/28649121/117342735-d87e7300-aea3-11eb-97ee-12031c69857d.jpg)

4. Now the UI is not responsive anymore. By scrolling out a tiny bit and pressing right mouse button on a free space the UI becomes responsive again but the nodes fly away in high speed (you should try it, it looks really funny ). 
5. Also the toolbar is gone now.
![ap1](https://user-images.githubusercontent.com/28649121/117343377-838f2c80-aea4-11eb-8ab8-6ed47eb9afa5.jpg)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorbase/commit/3a0ceda2604e5642f3a52f25cdf9f894b23ec582. 👍
