### ISSUE TITLE
Plugin nodes change their color

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#917]
Plugin nodes change there color if restored from a saved project.

**Steps to reproduce:**
1. Enable the hello node plugin. 
2. Add a node to a material. The node's color is red (like the material node, ...)
2. Save the project
3. Close Armorpaint
4. Load the project
5. Now the hello node got orange.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/3d9b58b0a890c687fade23d46d4010a907a003e2.
