### ISSUE TITLE
Node STRING values are not restored

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#918]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-08) - 205197b

**OS/device including version:**
Win10 x64

**Issue description:**
The value of node buttons of type STRING are not restored on project load

**Steps to reproduce:**
1. Pull some node with STRING value in a material, e.g. Attribute or Shader node.
2. Write some content in the edit control.
3. Save the project
4. Reload it.
5. The text is gone BUT it is persisted to file as one can see in a hex editor. So restoring is the issue, not saving.

Background: I use the STRING button for some of my custom nodes.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/zui/commit/a9fbc03e98b66721c47b647c25019f8d761e71cb, thanks for report!

**Comment by MathemanFlo** [comment]
Thank you so much. Now I can really use my Math expression node.
