### ISSUE TITLE
Seamless painting in 2D view

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#919]
It would be a great feature if ArmorPaint would not only support a tiled view in 2D but would also allow for seamless painting. I.e. painting does not stop at the texture border but is extended seamlessly. 
![ap1](https://user-images.githubusercontent.com/28649121/117543805-ac3b3180-b01e-11eb-99a7-b6b294f63b02.jpg)

**Comment by luboslenco** [comment]
Sounds great! Fixed at https://github.com/armory3d/armorpaint/commit/40ebed705cd7141441e3bf29b440bb2788cda99a.
