### ISSUE TITLE
Support to zoom when Orthographic

### ISSUE THREAD

**Issue by WhiteTiger-21** [armory3d/armorpaint#92]
I can zoom objects when perspective by mouse scroll or FoV.
But can't zoom when orthographic,faces are disappeared behave like the view cam is moving on track of depth of view.

**Comment by luboslenco** [comment]
Fixed in new development builds, thanks!
https://github.com/armory3d/armorpaint/commit/e97ba08c00ebc18dc933d21c3b73ce51e00ad250
