### ISSUE TITLE
Layer mask preview is red

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#920]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-08) - 205197b

**OS/device including version:**
Win10 x64

**Issue description:**
Layer mask previews are red instead of greyscale

**Steps to reproduce:**
![ap1](https://user-images.githubusercontent.com/28649121/117548391-0c3cd280-b035-11eb-8e82-2136208b8c59.jpg)

@luboslenco Sorry for flooding your repositories with bug reports, discussions, feature requests and pull requests.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/2ffe9c7e2ec2c609a5d49e086b0c716174a4d179, thanks again. Love the flooding!

**Comment by MathemanFlo** [comment]
You're welcome. Armorpaint is already pretty stable. It's already relatively hard to spot bugs.
