### ISSUE TITLE
Add margin while exporting and baking texture.

### ISSUE THREAD

**Issue by ZAQraven** [armory3d/armorpaint#921]
Hi there.

It will be good if adding margin when we exporting texture and baking the texture. Because there is some issue that some models have strip lines when the model is a far range.

Before give margin
![report1](https://user-images.githubusercontent.com/79313756/117605063-12d86080-b181-11eb-9f27-0b3061bdd512.PNG)

After give margin
![report2](https://user-images.githubusercontent.com/79313756/117605121-313e5c00-b181-11eb-8521-271108d43683.PNG)

**Comment by MathemanFlo** [comment]
Hi,
you are right, this is a very important feature to avoid seams and strips. You might want to consider the option Dilate radius in the Usage section in the preferences dialog you find in the Edit menu. This option allows you to adjust the "texture bleed" while texturing and baking. Does it fulfill your purpose?

**Comment by ZAQraven** [comment]
> Hi,
> you are right, this is a very important feature to avoid seams and strips. You might want to consider the option Dilate radius in the Usage section in the preferences dialog you find in the Edit menu. This option allows you to adjust the "texture bleed" while texturing and baking. Does it fulfill your purpose?

Still does nothing.

**Comment by MathemanFlo** [comment]
For me this works in ArmorPaint.org - v0.8 (2021-05-10) - fde16d8
If the dilate radius is positive I get a nice bleed if I paint the model. It works for the paint tool, the fill tool and for baking. Clearly it does only affect new paintings and not existing ones.
![ap1](https://user-images.githubusercontent.com/28649121/117626244-2f6f9b00-b177-11eb-8cb0-90236a79b9fb.png)

**Comment by luboslenco** [comment]
Hello, yes, it only affects the new paintings. You can also icrease `Dilate Radius` above 16 if needed by entering the value on keyboard.
