### ISSUE TITLE
.PNG images are unable to load in Blender.

### ISSUE THREAD

**Issue by ZAQraven** [armory3d/armorpaint#923]
Hi there.
I just have updated the current repositories of ArmorPaint.
The .png textures are unable to load in Blender.

**Comment by MathemanFlo** [comment]
I can reproduce this. It is definitely no Blender issues as gimp and other applications are affected as well. Even ArmorPaint if I try to import the exports again.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorcore/commit/40a6883c0843e3375b60a4a13ca60940e1b8c73f, thanks for report!
