### ISSUE TITLE
Ctrl+tab performs two actions

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#924]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-10) - fde16d8

**OS/device including version:**
Win10 x64

**Issue description:**
Pressing Ctrl+Tab cycles the layers and switches between the tabs Layers,History and Plugins. It should only do the former and not the latter.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/7b26bc2884b4fada39d27530111812d5fc3c8ab2.
