### ISSUE TITLE
Shift Tab material switch only works if the viewport has the focus

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#925]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-10) - fde16d8

**OS/device including version:**
Win 10 x64

**Issue description:**
Materials can be switched by Shift+Number. This only works if the viewport has the focus. If the mouse is outside of the viewport the shortcut does not work. I'm unsure whether this is intentional or not. I understand that Shift+Number interferes with secondary key assignment and that this might be the case to limit it to the edit control free viewport.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/edc0f7568d60542379e147f6ddc3fc6985878c40.
