### ISSUE TITLE
Particle tool recolors existing particle paintings on other layers than first one

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#926]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-10) - fde16d8

**OS/device including version:**
Win10 x64

**Steps to reproduce:**
1. Create two materials, e.g. a red and a green one.
2. On the first layer use the particle tool with the first and then with the second material. After doing so both colors are sprinkled all over the painted areas as expected.
3. Now switch to the second layer and repeat the steps from step 2. After switching to the second material and starting to sprinkle particles, the already painted ones switch their material to the second one (all textures, not just base color)

**Comment by MathemanFlo** [comment]
I'd like to add that except on the first layer the behavior for the other textures (roughness, metallic, ...) is also incorrect. It instantly fills whole faces?? with some incorrect value 
![ap1](https://user-images.githubusercontent.com/28649121/117658102-a2d6d400-b19a-11eb-8c37-a2f792005d7e.png)

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/ec7485ea6c5296eee0e9ad89a1fa12f14d371ffd, thanks for report! Still more work needed on handling the opacity / hardness, should get better soon.

**Comment by MathemanFlo** [comment]
Yes I agree! Please. please, please improve the whole brush system. In my opinion this is the single most annoying issue of Armorpaint. Especially the bug that brush hardness is only taken into account for the first layer and not for masks makes hand-painting almost impossible.
