### ISSUE TITLE
Math atan operation is broken

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#929]
The math node's atan (the one with one argument, not atan2) function is broken. The reason for it is
`s += '#define atan(x, y) atan2(y, x)\n';` in line 204 (DirectX) and 389 (Metal) in NodeShader.hx. Because it also replaces the one argument atan with the two argument atan resulting in an error. 
A quick solution would be to replace line 1455 in MaterialParser.hx by out_val = 'atan(1.0, $val1)';

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorbase/commit/9a59acf0d2821f12ac79ae60fbc21e54997addaf + https://github.com/armory3d/armorpaint/wiki/Plugins/_compare/f2c25f18e65ba522a0e75bd0150d7e9ff4ad9832, thanks!
