### ISSUE TITLE
. FBX and. OBJ import error

### ISSUE THREAD

**Issue by JameGTI14** [armory3d/armorpaint#93]
Hi there,
 I purchased this as an alternative to substance painter. I'm trying to import a. FBX model (not too Complicated at all and pretty simple) I get an error "failed to read mesh data" I have tried exporting from 3ds max as a .OBJ too but when this imports the UV map isn't visible until parts are painted and then those parts are visible. Also OBJ format ruins the definition of the model. Any help would be most appreciated. Many thanks!

**Comment by luboslenco** [comment]
Hello @JameGTI14, are you able to share the .obj and .fbx file? Will get it fixed.

**Comment by JameGTI14** [comment]
hi there,

 Attatches is my FBX and OBJ that wont import into Armorpaint, I have
discovered that now nothing imports. I Have tried deleting the armorpaint
folder and re extracting it from the archive I downloaded but its still not
working

many thanks,

James

**Comment by qwertychouskie** [comment]
@JameGTI14 GitHub doesn't support adding attachments from email, please upload your attachment using the web interface, thanks.

**Comment by luboslenco** [comment]
Sorry to bother, if you are still around and don't mind attaching the files directly on GitHub that would be awesome.
