### ISSUE TITLE
Mesh Deletion

### ISSUE THREAD

**Issue by LunarBitz** [armory3d/armorpaint#930]
*ArmorPaint 0.8-4b662d3, Windows*

**Feature description:**
Reimporting the same mesh (blend file) from any other folder gets rid of all layers. So to work around this, appending the new mesh and retargeting the layers has to be done. Except it leaves a trail of old meshes behind with no way to delete them, making the list pretty cluttered with larger models.

So a feature that I think would be cool? Being able to delete any mesh from the list so long as there are at least 2 or more meshes present.

**Comment by luboslenco** [comment]
Meshes from the list can be deleted now, thanks for suggestion! https://github.com/armory3d/armorpaint/commit/0895fa512af27bb3cb202280c6ceb0a771d04c43
