### ISSUE TITLE
Troubles with mixing materials

### ISSUE THREAD

**Issue by AlexeySergeich** [armory3d/armorpaint#931]
Hello, I have few questions about mixing materials.
I have two materials and I wanna to mix them by mask on layer 2
But it shows not good result. I'm using paint brush with png image for mask 
So, how to mix materials correctly?
Result
![image](https://user-images.githubusercontent.com/78400738/118103542-b4aab800-b3e2-11eb-8d8f-572815ad01e7.png)
Mask
![image](https://user-images.githubusercontent.com/78400738/118103631-cd1ad280-b3e2-11eb-988f-5a866504dbf7.png)

Paint brush image
![12](https://user-images.githubusercontent.com/78400738/118103712-defc7580-b3e2-11eb-98e5-d19f1b9f93d3.png)

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/armory3d/armorpaint/issues/312, many thanks for report!
