### ISSUE TITLE
Object Fill fills whole project, not selected object

### ISSUE THREAD

**Issue by ssnd292** [armory3d/armorpaint#934]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-11) - 4b662d3

**OS/device including version:**
Windows - Direct3D11
NVIDIA GeForce GTX 1080 Ti  

**Issue description:**
When wanting to Fill masks with a material to only have that material displayed on a certain object, it fills the entire UV and not just the object I clicked on.

The mesh is fully seperated - forgot to mention this.

https://user-images.githubusercontent.com/3914410/118365158-d4391080-b59b-11eb-8bc4-11155e1dae00.mp4

**Comment by luboslenco** [comment]
Check here to see how to set object mask for layer:
https://www.youtube.com/watch?v=9LJY2y6JyKg&list=PLsoJIZPOq9_r2aciBXDB0VBo3Z0lTI2En&index=19

It will also be possible to just 'click on object' eventually via https://github.com/armory3d/armorpaint/issues/381.

**Comment by ssnd292** [comment]
I did not find that ticket you linked, thank you. The way you have shown might work for simple models, but not complex one where you quickly want to mask something.

**Comment by ItsCubeTime** [comment]
I must say that I agree with op that you should be able to fill certain objects individually without having to hide the rest.

I also think it would be nice if it wouldnt just work for each separated body, but for each piece of connected geometry (Like anything that would get selected when pressing L hovering a mesh in blender).

Perhaps it would make more sense to add some geometry selection tools & allow for filling by selection?

**Comment by ssnd292** [comment]
I honestly believe the way Substance Painter did it is the best way. Click - or rectangle-select.
