### ISSUE TITLE
Baked maps should be put in a seperate category

### ISSUE THREAD

**Issue by ssnd292** [armory3d/armorpaint#935]
Instead of creating a layer for every baked map, they should automatically appear in their own category. I create a Photoshop Mockup here:
<img width="227" alt="2021-05-17 08_00_50-" src="https://user-images.githubusercontent.com/3914410/118439676-b926e780-b6e6-11eb-9562-10ff036c19a9.png">

Instead of them being their own layer, a new cateory called "Baked Textures" is used to store all baked maps which are also automatically updated once I bake that map again.

**Comment by luboslenco** [comment]
There is no separate category but one can export baked textures from layer into textures tab now via `layer - export - destination - packed`. The layer can be deleted afterwards.
