### ISSUE TITLE
ArmorPaint randomly distorts UV's at value 1.00 for imported meshes

### ISSUE THREAD

**Issue by FeJe** [armory3d/armorpaint#936]
**ArmorPaint version:**

ArmorPaint.org - v0.8 (2021-05-18) - 811b5fc

**OS/device including version:**

Windows 10

**Issue description:**

ArmorPaint randomly distorts UV's at value 1.00 for imported meshes

**Steps to reproduce:**

Create a default UV-Sphere in blender. Save and import the sphere via the .blend or the fbx file.

![grafik](https://user-images.githubusercontent.com/10330228/118675958-507d5f00-b7fb-11eb-9732-00db2bcddac5.png)
![grafik](https://user-images.githubusercontent.com/10330228/118676101-6a1ea680-b7fb-11eb-97a5-cf9c1a66d640.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/bbae892bc54af5bb9a63ef68fb47516f7e724f15 + https://github.com/armory3d/armorbase/commit/30064fe93c092db37a7c194a09530da62e2fb3ce. Thanks for report!
