### ISSUE TITLE
Brush image node alpha is broken

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#938]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-15) - 0895fa5

**OS/device including version:**
Win 10 x64

The alpha channel for the brush image node seems to be broken. Please consider the following alpha map. It is completely black for RGB and contains all its information in the alpha channel. By creating a brush with Opacity as alpha channel of this image, the brush is completely transparent (i.e. does not paint)

[Brush_alpha.zip](https://github.com/armory3d/armorpaint/files/6503059/Brush_alpha.zip)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/c24047688cd1b17b39d0b3ec32955af12c2ad6c5, will need a proper parser eventually.
