### ISSUE TITLE
Unable to paste Hex colors in swatch color selector

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#939]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-18) - 32a582d

**OS/device including version:**
Win10 x64

Swatches can not be changed by pasting or changing the hex value because the picker disappears on first mouse click

1. Open the color picker
2. Switch to Hex
3. Click on the edit to give it the focus to type/paste -> the picker closes

![ap](https://user-images.githubusercontent.com/28649121/118702052-b88c6f00-b814-11eb-8e1a-5feba1f5e324.jpg)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/7e5de6e0dc2e7bbf3f954bf287189ad778f17eaa, thanks for report!

**Comment by ronh991** [comment]
This happens on the RGB material input node also.  I cannot type in a backspace to edit a hex value.
