### ISSUE TITLE
file explorer in armorpaint

### ISSUE THREAD

**Issue by xtvjxk123456** [armory3d/armorpaint#94]
first ,i don't like the file explorer ,although i am a blender user. blender file explorer is convenient.
i prefer windows native file explorer or blender file explorer  in armor paint

second, when "2dview" or "node editor" is visible, file explorer can't display normally every time.
if i hide  "2dview" or "node editor" ,it show again.

I hope armorpaint is convenient to use.

**Comment by luboslenco** [comment]
Sorry about the file explorer, it is still an abomination. Hoping to push improvements soon!

**Comment by zphr** [comment]
Hi,
thanks for this promising software but I have to agree the custom file explorer should go because the native explorers are much better integrated (quick access, bookmarks, etc). Also having a decent custom one distracts from the real features that are needed.

**Comment by luboslenco** [comment]
Testing native file explorer integration in the latest 06dev builds. If anyone spots issues please let me know. 🙂

**Comment by zphr** [comment]
Thank you! :)
