### ISSUE TITLE
Baking AO produces "ringing artifacts"

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#940]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-18) - 32a582d

**OS/device including version:**
Win 10x64 Directx 11

**Issue description:**
Baking the AO gives sometimes unexpected results.

**Steps to reproduce:**
1. Use for instance this mesh [FassMP.zip](https://github.com/armory3d/armorpaint/files/6503409/FassMP.zip)
2. Bake AO and get this result
![grafik](https://user-images.githubusercontent.com/28649121/118702977-dc9c8000-b815-11eb-9913-9de9dd201414.png)

The center of the rings are excatly the coordinate axes x and y

**Comment by luboslenco** [comment]
It's because the non-dxr version only uses voxels, sorry. It should work properly in the ArmorPaintDXR / ArmorPaintVKRT versions which do use raytracing. In the future those versions will become the default, once the hardware adoption is there.

**Comment by MathemanFlo** [comment]
Awsome, thank you!

Am Di., 18. Mai 2021 um 20:25 Uhr schrieb Lubos Lenco <
***@***.***>:
