### ISSUE TITLE
Cloud Materials do not allow for 'open containing folder'

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#942]
![ap1](https://user-images.githubusercontent.com/28649121/118809563-123f7880-b8ab-11eb-8427-bbcf6bab9608.png)

**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-19) - 32a582d

**OS/device including version:**
Win 10 x64

**Issue description:**
If 'Open containing folder' is used for cloud imported materials it does not work because the path is the wrong one.

**Steps to reproduce:**
1. Import cloud material
2. Click on open containing folder
![ap1](https://user-images.githubusercontent.com/28649121/118809712-41ee8080-b8ab-11eb-9448-edc5974253ea.png)

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/a42fdbd182467b1d766a0822ee056d5385911975.
