### ISSUE TITLE
Cube template shares UV for all 6 sides

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#944]
I do not know whether it is intentional or not (it really could be) but the cube template shares UV for all 6 sides.
![grafik](https://user-images.githubusercontent.com/28649121/118859552-a70d9a80-b8da-11eb-905a-6ff1bdea85fd.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/2d12c490e115b5ca115128606fab5117a17e6c65.
