### ISSUE TITLE
Prevent creating recursive node groups

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#946]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-19) - a42fdbd

**Issue description:**
Copying the node of a node group and pasting it into itself freezes ArmorPaint

**Steps to reproduce:**

1. Create a node group
2. Copy the node by ctrl+c
3. Edit the nodes of the node group by clicking onto nodes.
4. Paste the copied node. -> ArmorPaint freezes.

Expected behavior: Do not allow pasting into itself (probably not feasible because one could build a "cycle" with two node groups. A contains B, B contains A) or do not output a material similar to recursive shader graphs.

**Comment by luboslenco** [comment]
Super cool, thanks for the reports! 👍

**Comment by MathemanFlo** [comment]
You are welcome! And thank you for the awsome work. You develop one of the coolest open source programs ever.
