### ISSUE TITLE
Decal Layer and Fill layer issues if material is deleted

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#947]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-19) - a42fdbd

**Issue description:**
1. Create a decal layer and an ordinary layer on top filled with a different material.
2. Now delete the material used by the decal layer.
3. The decal layer starts to behaves strange now.
4. After having deleted the material edit the decal layer by moving the decal layer with the gizmo. The layer changes its color to the second material (in case the first one was the material for the decal layer) but the layer preview does not update. 
![grafik](https://user-images.githubusercontent.com/28649121/118870500-e6da7f00-b8e6-11eb-9d01-b7b8e25e4fe4.png)
5. Now click on the + to access the layer's option. Switch from Project to UV map. The gizmo does not disappear immediately (it does if the material exists) but only after rotating the model (to force redraw). The same holds for switching back from UV map to project. Also switching has now no effect anymore. 

The very same happens if you start with a fill layer.

I think Decal layers and Fill layers are one of the most hidden features of ArmorPaint. I think the first one is mentioned nowhere. Maybe you want to consider to add it to the context menu the same way you did for fill layers? Clearly this is not optimal because you would have to place the decal layer at some position but I think this nice feature should not be hidden.

Finally one question: Decal layers and fill layers are the same right? They only differ in Tex coord mode, right?

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/1310ebcee28da1ef79f1f09bcc7457641e81163e. Added decal layers to the context menu when pressing the `New` button for better visibility.

**Comment by MathemanFlo** [comment]
Already saw it. It is a very nice solution.
