### ISSUE TITLE
Decal layers get border if the resolution is reduced

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#948]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-19) - a42fdbd

**Issue description:**
Reducing a decal layer's resolution blurs the whole layer and produces a "black border".

**Steps to reproduce:**
1. Create a decal layer.
2. Reduce its resolution
![grafik](https://user-images.githubusercontent.com/28649121/118872718-2a35ed00-b8e9-11eb-9fb8-1862f1e31ce7.png)

This makes the option to reduce the resolution more or less useless (it also happens for 1K and so on). If you export the decal layer to a file you see that it is actually not blurred at all. This is only due to the low resolution and the fact that it is painted on black background. Therefore it might be hard to solve this issue. Feel free to close it.

**Comment by luboslenco** [comment]
Should get resolved via https://github.com/armory3d/armorpaint/issues/274.
