### ISSUE TITLE
About Dialog is only half non-editable

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#949]
**Issue description:**
ArmorPaint's About dialog is only half non-editable. The user is not allowed to remove the text by pressing Del but can do so by pressing Esc

**Steps to reproduce:**
1. Open the About dialog.
2. Click on the first edit and press Esc. Repeat that for all others.
3. Copy some text in a text editor and paste it to the dialog by Ctrl+V
![grafik](https://user-images.githubusercontent.com/28649121/118874268-01165c00-b8eb-11eb-9b63-2a69938aedb3.png)

Again it is just some not so important UI glitch I detected by chance but maybe it is a zui related issue that could be harmful on other places?

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/zui/commit/fbb1d3d48dfdcfe2544405f7a93b563020397acc. 👍

**Comment by MathemanFlo** [comment]
Sorry but not completely. You did not update the submodules such that it takes effect in ArmorPaint.
And even if you did, it is still possible to paste stuff to the edit via Ctrl+V.
I don't know whether it is easily possible but I also think it might be nice to be able to select the text like it is possible for editable edits. 

Finally a context menu similar to the one you created for nodes would be amazing. Other edit controls in ArmorPaint's UI would benefit for sure.

**Comment by MathemanFlo** [comment]
I can still reproduce it. Ctrl+X to cut the content works, too.
