### ISSUE TITLE
Height paint leaves brush marks

### ISSUE THREAD

**Issue by Lexpartizan** [armory3d/armorpaint#95]
In 0.6 dev version remain brush marks. Screen attached. Material attached.

in 0.5 OK, but brush draws not in a circle.
when open file Manager - emerges and disappears window.

![brushmarks](https://user-images.githubusercontent.com/48552343/56600887-74f9b380-6602-11e9-818a-d7247c64494e.png)
[1.zip](https://github.com/armory3d/armorpaint/files/3108744/1.zip)

And height-maps dont work properly, imho.
In free program Materialize heightmap in previously attached material looks roundles, as it should be.
Only heightmap without another maps looks good in Materialize.

in 05 ArmorPaint heightmaps not working at all.
in 06 ArmorPaint looks like square strip with randomly bump.

Screenshots do not show it, so you better check for yourself.
Maybe problems with old drivers for my nvidia 1050. But in Materialize this feature looks very nice.

Reinstall driver.
Brush marks still here.
About heightmap - dificultly said. In some angles looks normal. Maybe different scale material.
This is quite subjective.

**Comment by Lexpartizan** [comment]
And height-maps dont work properly, imho.
In free program Materialize heightmap in previously attached material looks roundles, as it should be.
Only heightmap without another maps looks good in Materialize.

in 05 ArmorPaint heightmaps not working at all.
in 06 ArmorPaint looks like square strip with randomly bump.

Screenshots do not show it, so you better check for yourself.
Maybe problems with old drivers for my nvidia 1050. But in Materialize this feature looks very nice.

> In 0.6 dev version remain brush marks. Screen attached. Material attached.
> 
> in 0.5 OK, but brush draws not in a circle.
> when open file Manager - emerges and disappears window.
> 
> ![brushmarks](https://user-images.githubusercontent.com/48552343/56600887-74f9b380-6602-11e9-818a-d7247c64494e.png)
> [1.zip](https://github.com/armory3d/armorpaint/files/3108744/1.zip)

**Comment by brunomrsn** [comment]
I didn't find out a way to paint a height map, even a (already painted externally) height map loading seems not work.

**Comment by luboslenco** [comment]
Heightmap should take effect and marks should get cleared now.
Height paint is still tacky, will dedicate one of the upcoming updates to it.
