### ISSUE TITLE
Node groups produces undeselectable connections if input or output slot is deleted

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#950]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-19) - a42fdbd

**Steps to reproduce:**
Build something like this or similar
![grafik](https://user-images.githubusercontent.com/28649121/118875091-ed1f2a00-b8eb-11eb-9348-96c9d45094f2.png)

Deleting the input slot give a result like this
![grafik](https://user-images.githubusercontent.com/28649121/118875145-fc05dc80-b8eb-11eb-912d-8d59ead2e001.png)

By closing the node group you get a good old friend, the undeselectable connection
![grafik](https://user-images.githubusercontent.com/28649121/118875351-3d968780-b8ec-11eb-9665-99b790f9cca2.png)

You also get one if the deleted slot was connected outside
![grafik](https://user-images.githubusercontent.com/28649121/118876259-5489a980-b8ed-11eb-8437-f0cb8cdc1a47.png)

If you play the same game on the output node you get similar results:
![grafik](https://user-images.githubusercontent.com/28649121/118876431-8733a200-b8ed-11eb-82c2-7bd27c3ecfaf.png)

![grafik](https://user-images.githubusercontent.com/28649121/118876477-93b7fa80-b8ed-11eb-8f3b-37491fad44fd.png)

Doing further actions sometimes freezes ArmorPaint but unfortunately I could not find out a deterministic simple way to achieve this but hopefully it is either fixed by disconnecting slots on delete or by #882.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/cd154330f14257e47b234e87af6dbb5a67ca3a96.
