### ISSUE TITLE
Rotate by angle in Project and Triplanar mode

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#951]
I'm unsure about this. Currently ArmorPaint does not support angle rotation for triplanar and projection. Is it a bug, a missing feature or does it really make no sense? Because I thought it would make sense after all. Rotate the texture first, then project...
If it does not make sense or is not possible it might be a good idea to disable to angle functionality if these modes are chosen?

**Comment by ikonnow** [comment]
I agree with this question and confirm that I also miss this feature. 
In addition, I have collected here [https://github.com/armory3d/armorpaint/issues/955] a few more extensions to the texture projection, which of course also apply to the triplanar mode.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/13ea79240f8683ed579bbca7ee97a698705c2296, thanks for report.
