### ISSUE TITLE
Scrolling folders in the cloud zooms the node editor

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#952]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-19) - 32a582d

**OS/device including version:**
Win 10 x64

**Issue description:**
Scrolling folders in the cloud zooms the node editor

**Steps to reproduce:**
1. Open the cloud in the browser on the bottom
2. Open the node editor for an arbitrary material
3. Go to cloud\materials\cc0 or cloud\materials\scanned
4. Scroll up and down (if necessary resize the browser in order to be able to to so.)

Now the nodes are zoomed as well.

**Comment by MathemanFlo** [comment]
Wohoo just realized this is my 100th ArmorPaint issue :satisfied:

**Comment by luboslenco** [comment]
Hopefully all good after https://github.com/armory3d/armorpaint/commit/ac2ae33ee9894f9ada818fff12019e51476375f0.

**Comment by MathemanFlo** [comment]
yes, seems to be the case

Am Fr., 21. Mai 2021 um 11:44 Uhr schrieb Lubos Lenco <
***@***.***>:
