### ISSUE TITLE
Browser file and directory recognition problem

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#954]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-05-21) - 2d12c49

**OS/device including version:**
Win 10 x64

The browser has several problems to detect files and directories correctly

1. If a directory has a "." in its name. It is not recognized as directory. E.g. wood_3.1
2. If there is a file with multiple "." in it, like abc_10.3.png then it is also not recognized
2. If there is a file that contains spaces in its names, it is not recognized and and even worse subsequent files are not recognized anymore. It does not play any role whether the file type is a supported one or not.
3. Also cobblestone_floor_04_2k.zip is evil for some reason. The problem seems to be the "2k" in it. In this case again all subsequent files are not recognized.
4. The same holds for directory names like rough_wood_4k_jpg, aerial_grass_rock_1k_jpg and so on
5. The Browser has issues with showing file names containing non ASCII characters like ÄÖÜß€ and so on

I do not know whether the list is complete or not. But I realized ArmorPaint has serious issues to show me all files and some folders with lots of sub folders and suitable files (like images) where almost completely empty.

Also I can not understand the sorting. It is somehow alphabetically but not really 
![ap1](https://user-images.githubusercontent.com/28649121/119106387-97976a00-ba1e-11eb-9a57-30ec59c68af6.png)

**Comment by luboslenco** [comment]
👍 👍 linking together with https://github.com/armory3d/armorpaint/issues/814

**Comment by MathemanFlo** [comment]
Thanks a lot. Added a few suggestions for improvement in #814.
