### ISSUE TITLE
Smear Tool Request

### ISSUE THREAD

**Issue by Gravnn** [armory3d/armorpaint#958]
*ArmorPaint 0.8-2ffe9c7, Windows*

**Feature description:**

The tool that is missing, and any other 3D Painting have is the smear/smudge (blender/substance painter) tool.
It is very useful, and the blur tool can't do the job.

**Comment by luboslenco** [comment]
Blur tool has a `Directional` option now to perform smudge, quality will improve. Thanks for report!
