### ISSUE TITLE
UV-scale in material properties.

### ISSUE THREAD

**Issue by Lexpartizan** [armory3d/armorpaint#96]
When painting i need set UV-scale material to realistic for model.
For example, the size of bricks for a wall.

I set scale for first material. OK. 
I set scale for second material another scale.OK.
If i want paint first material, i will have scale for second material, not first.
If i forgot value of UV-scale for first material, I have to repaint all the places, where used this material.
Add UV-scale and UV-rotate to output material node.

And synchronize changes in the nodes and in the material.
Maybe you should automatically create a color-id card to apply the modified material to the entire model already painted.
PS Sorry for my english. Hope, you can understand.

**Comment by Lexpartizan** [comment]
Add UV-scale  and UV-rotate to output material node.

And synchronize changes in the nodes and in the material.
Maybe you should automatically create a color-id card to apply the modified material to the entire model already painted.

**Comment by Lexpartizan** [comment]
By the way, deleting nodes with press "x" in 06 not working in 06. It is so familiar to work with a blender.
in 05 working.

**Comment by luboslenco** [comment]
There is a way to set UV scale using the `Mapping` material node nowadays. Still not super happy with the control, will improve it further as we go.

![sc](https://user-images.githubusercontent.com/3685704/60420189-640f8480-9be7-11e9-9c5f-2b3de37caab4.PNG)

> Maybe you should automatically create a color-id card to apply the modified material to the entire model already painted.

It's possible now with the `Picker` tool, working on better UI for it to expose it properly. 🙂

**Comment by Lexpartizan** [comment]
Thanks for your work.
