### ISSUE TITLE
Several plugins fail to load with "TypeError: Cannot read property 'bind' of undefined"

### ISSUE THREAD

**Issue by belzecue** [armory3d/armorpaint#961]
*ArmorPaint 0.8-2454ddd, Linux*

I built for Linux (Ubuntu 20.04.2) and everything's working, but when I try to add some of the default plugins via the plugins manager, e.g. uv_unwrap and import_gltf_glb, the console reports:

```
TypeError: Cannot read property 'bind' of undefined
Failed to load plugin 'uv_unwrap.js'

```
However, I can add the hello_world plugin and see it appear in the plugin manager list.

**Steps to reproduce:**
Simply try to add either of those two plugins via the plugins manager.  (I'm guessing this issue is just affecting me, though.)

![Screenshot at 2021-05-26 19-13-56](https://user-images.githubusercontent.com/1931303/119650568-8dc69a00-be56-11eb-9da6-8785d29d2c4d.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/6b7860d488b269918d614269e253ab645cd443d0, thanks for report!
