### ISSUE TITLE
software not working well

### ISSUE THREAD

**Issue by wongsalvai** [armory3d/armorpaint#962]
**ArmorPaint version:**
the newest

**OS/device including version:**
macbook pro 2017 /big sur

**Issue description:**
hello, i just bought armorpaint and program is closing every moment, and the app seems a lot laggy. Have no idea what to do:(

**Comment by luboslenco** [comment]
Sent you a refund, windows & linux is recommended for now, sorry. Right now I build and test on mac mini m1.
