### ISSUE TITLE
I just started using ArmorPaint. after installation, I have the built file at C:\Users\XXXXX\Desktop\Applications\APp\armorpaint\armorcore\build\x64\Release . but can't run it

### ISSUE THREAD

**Issue by saeed-barari** [armory3d/armorpaint#963]
Hello everyone. I did all the steps mentioned in the readme as well as in the GamesFromScratch tutorial. however, after doing everything, the built file cant run. 

-- I cloned the repo, didnt download it as zip.
-- windows 10 , most recent versions
-- visual studio gave no errors 
-- i tried the workaround in the other issue ( copying the exe to desktop ) and did not work
-- i can run the program through ctrl+f5 in visual studio with no bugs or anything

thanks very much

**Comment by luboslenco** [comment]
Hello, check the issue at https://github.com/armory3d/armorpaint/issues/833.

**Comment by saeed-barari** [comment]
> Hello, check the issue at #833.

![out](https://user-images.githubusercontent.com/79690923/120102629-2b74de80-c161-11eb-9c78-f4babe2b9c39.jpg)

already done that , as instructed in the GamesFromScratch tutorial and in the readme file. thanks for reply , but this didnt solve my problem , man

**Comment by saeed-barari** [comment]
FIXED! 

So, what i did was copying the executable to C:\Users\XXXX\Desktop\Applications\armorpaint-master\armorpaint\build\krom and it solved my problem . I think this should've been more clear on the README file.

thanks again
