### ISSUE TITLE
HUGE ISSUE: Changing Texture Resolution 

### ISSUE THREAD

**Issue by JareDamn** [armory3d/armorpaint#965]
**ArmorPaint version:** 0.8

**OS/device including version:** Windows

**Issue description:** Not able to change texture resolution without crashing, whenever go to export and try to change the texture resolution it crashes, and once it crashed my entire OS and broke it so i had to hard reset it. Also changing a layer resolution has the same issues.  

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Hello, up to 8K should be fine on most machines (dedicate gpu, 6GB+ video ram). Unfortunately "crashed my entire OS" sounds like it runs out of the video memory on your machine. If you got the gumroad version please [email me](https://armorpaint.org/community.html) co I can send you a refund, sorry for trouble.
