### ISSUE TITLE
Issues with new Layer system

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#966]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-03) - 1310ebc

**OS/device including version:**
Win10 x64

I tried the new layer system and it is a huge improvement! But I experienced a few minor issues. I think some of them are inherited from layer groups.

1. Create two layers. Give the lower one a mask. 
![grafik](https://user-images.githubusercontent.com/28649121/120618465-6590f980-c45b-11eb-87cc-d7a65c193ebe.png) Now drag Layer 2 in Layer 1 by dragging it between Layer 1 and Mask 3. ArmorPaint's UI gets stuck.
2. Build this setting 
![grafik](https://user-images.githubusercontent.com/28649121/120624388-f0282780-c460-11eb-8a97-623430b2cd3b.png) Rearange it this way 
![grafik](https://user-images.githubusercontent.com/28649121/120624430-fcac8000-c460-11eb-873b-7083b6aec44c.png) Now press Ctrl+z as often as you can. ArmorPaint's UI will get stuck. Maybe this is related to #792

**Comment by luboslenco** [comment]
https://github.com/armory3d/armorpaint/issues/1013
