### ISSUE TITLE
Magic first layer in new Layer system

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#967]
ArmorPaint.org - v0.8 (2021-06-03) - 1310ebc
Win 10 64 bit

Hello Lubos! This concerns the hardness for the brush on the mask layer. For some reason, this function only works if you create a layer with a mask for the first layer. Brush hardness does not work on new layers.
Here is such a magical first layer)
Mask with brush hardness (0,24) for the second layer
![image](https://user-images.githubusercontent.com/65244629/120637804-02619000-c478-11eb-87d8-71e3fcf674f9.png)
Mask with brush hardness (0,24) for the first layer
![image](https://user-images.githubusercontent.com/65244629/120638005-42c10e00-c478-11eb-98a4-472c3bbce529.png)
But thanks a lot for this addition anyway. This is really great.
Have a nice day)

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/armory3d/armorpaint/issues/312 https://github.com/armory3d/armorpaint/issues/595, many thanks for report!

**Comment by AlexKiryanov** [comment]
Woow super fast) many thanks)

**Comment by AlexKiryanov** [comment]
Good day! hmmm.
Strange but still the same. For the first layer mask, mouse hardness works. (I can paint with a brush with blurred borders)
And for the next layers, this function does not work (
![image](https://user-images.githubusercontent.com/65244629/120777716-41521d00-c52e-11eb-84f7-eb96f24feeb0.png)
![image](https://user-images.githubusercontent.com/65244629/120777819-5dee5500-c52e-11eb-8ca4-c2041a952f51.png)
