### ISSUE TITLE
Color id + fill layer issue

### ISSUE THREAD

**Issue by shubhampatilart** [armory3d/armorpaint#969]
**ArmorPaint version:**8.0Dev

**OS/device including version:** windows 64x
 Non DXR

**Issue description:**
 when picking color in color ID mode having issue while selecting 2nd color
also after clear color can't select any color not even previews selected color

**Steps [to](url) reproduce:**
 Did Record a video  - https://youtu.be/ZYw_MZFWX7M

**Comment by MathemanFlo** [comment]
I think the key problem here is that you use a fill layer instead of a normal layer. This is a fill layer:
![Screenshot 2021-06-05 144424](https://user-images.githubusercontent.com/28649121/120892053-89477180-c60c-11eb-8b3a-56f3401fbe54.jpg) By dragging and dropping a material on the viewport you create this fill layer.
If you use the Fill tool instead (shortcut G) then it works as expected.

**Comment by shubhampatilart** [comment]
![Armor Paint Color ID work](https://user-images.githubusercontent.com/57253638/120892231-e18d6c00-c62a-11eb-9874-387524da544c.jpg)

I just experimenting And drag the Color ID map In layers And than all working. Is this is the right way to do it?

**Comment by shubhampatilart** [comment]
> 
> 
> I think the key problem here is that you use a fill layer instead of a normal layer. This is a fill layer:
> ![Screenshot 2021-06-05 144424](https://user-images.githubusercontent.com/28649121/120892053-89477180-c60c-11eb-8b3a-56f3401fbe54.jpg) By dragging and dropping a material on the viewport you create this fill layer.
> If you use the Fill tool instead (shortcut G) then it works as expected.

Thankyou for quickly replay

**Comment by shubhampatilart** [comment]
> 
> 
> ![Armor Paint Color ID work](https://user-images.githubusercontent.com/57253638/120892231-e18d6c00-c62a-11eb-9874-387524da544c.jpg)
> 
> I just experimenting And drag the Color ID map In layers And than all working. Is this is the right way to do it?

After this direct dragging material work Perfect.

**Comment by MathemanFlo** [comment]
You are welcome. Now it should be easier for @luboslenco to fix it.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/af868f16124fe4aab0a6397b7dec78e47b22fdf9, thanks for report.
