### ISSUE TITLE
Roughness with EnvMap not correct.

### ISSUE THREAD

**Issue by Lexpartizan** [armory3d/armorpaint#97]
Without Enviroment Map fingerprints looks normal.
With Enviroment fingerprints looks like painted diffusemap.
Screen attached.
And heightmap bad works. like bump. No volume.
Sorry for my english.

![Rough+Env](https://user-images.githubusercontent.com/48552343/56688573-bc0aa600-66e1-11e9-8a64-34a962e238ca.png)
![without Env](https://user-images.githubusercontent.com/48552343/56688766-2facb300-66e2-11e9-9986-26bd657fd501.png)

**Comment by luboslenco** [comment]
Thanks for report! Fixing envmap import in upcoming build, linking with issue at https://github.com/armory3d/armorpaint/issues/180.
