### ISSUE TITLE
Layer node with mask as layer produces a red color

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#973]
---- Sorry for polluting the bug tracker but I think you overlooked a commit in a already closed bug #949. I think it is still not completely correct but should be a quick fix -----

**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**OS/device including version:**
Win 10x64

**Issue description:**
Thanks to ArmorPaint's awsome new layer system it is now possible to use Masks as a layer in Layer node. By doing so you get red color in the easiest case
![Screenshot 2021-06-11 071823](https://user-images.githubusercontent.com/28649121/121634665-46125600-ca85-11eb-9739-7c84d1c61c67.jpg)
From a technical point of view it is clear that the result looks like that because mask layers have only one channel and this one is mapped to the R channel. However it is inconsistent to other one-channel cases like plugging in a layer's roughness in the base color which produces a grey-scale result instead of a "red-scale" result. Additionally the layer node's base slot gives a RGB result and therefore it should visually match the mask layer appearance as the users sees it in the UI.

Additionally the behavior is inconsistent with the "layer mask" node (I also proposed a change for this node in #974)

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/974.
