### ISSUE TITLE
Layer group 2d view is incorrect

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#975]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**OS/device including version:**
Win 10x64

**Issue description:**
The layer group 2d view only shows the bottom most layer in the group and not the others. The viewport shows the correct result.

1. Create two layers
2. Paint some stuff on them
3. Group them
4. Compare the layer group result with the viewport

![Screenshot 2021-06-11 075552](https://user-images.githubusercontent.com/28649121/121638225-e7e87180-ca8a-11eb-80fe-f9e2d72e26cb.jpg)

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/414e988a370101c6a507fc64e3393de06d3ad393.
