### ISSUE TITLE
Deleting a layer with a mask crashes ArmorPaint

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#977]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**OS/device including version:**
Win10 x64

- Create a layer/fill layer
- Add a mask to it
- Delete the layer/fill layer
- Now the UI gets inreponsive and by clicking somewhere ArmorPaint crashes 

I'm not sure whether this is the same bug or not. 

- ArmorPaint does not allow you to delete the last layer (which makes sense)
- By adding a layer mask to a layer, there is still only one layer
- I have the impression ArmorPaint allows to delete that layer because it "counts" the mask layer, too...

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/4ef088065dc8926e739cd455789cd28f03d17c5b.
