### ISSUE TITLE
Fill layer does not always respect mask

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#979]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Steps to reproduce:**
This bug is a bit tough, you have to follow the steps exactly in the described way.

1. Create a fill layer. The first material has to be selected
2. Create a mask for the fill layer. 
3. Paint on the mask using the first material
3. Now change the color of the first material

Now the fill layer icon color on the layer stack changes but is is not done in the viewport.

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/1ad67a2eb664ca24c826142dcc54bd32df4a5770.
