### ISSUE TITLE
Drag and drop layers replaces layers and freezes ArmorPaint on undo

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#980]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

Build this situation:
![Screenshot 2021-06-11 084910](https://user-images.githubusercontent.com/28649121/121643260-e79fa480-ca91-11eb-8e50-945b5edf6d55.jpg)
i.e.

1. Create a second layer and fill it with some color
2. Import some texture to create a interesting fill layer.
3. Attatch a fill layer with the material from step 2 to the second layer.
4. Fill the first layer with a different material.
5. Drag and drop Layer 1 between the fill mask and Layer 2.
6. Layer 2 disappears and is replaced by Layer 1, but the mask is not taken into account.
7. By clicking Ctrl+Z to revert the operation, ArmorPaint's UI gets stuck.

![Screenshot 2021-06-11 085138](https://user-images.githubusercontent.com/28649121/121643594-47964b00-ca92-11eb-9d60-5499435a28da.jpg)

I think this bug is a variant of #966, so I'd like to link it to this one.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/792.
