### ISSUE TITLE
Undo apply mask is broken

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#981]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Issue description:**

1. Add a mask to the first layer.
2. Paint something on the mask
3. Fill the first layer with some color
4. Apply the mask
5. Undo it

The layer and the mask are restored but their "content" is not.

Before applying
![Screenshot 2021-06-11 090251](https://user-images.githubusercontent.com/28649121/121645003-ff782800-ca93-11eb-963b-0b611ed0162f.jpg)

After applying and undo
![Screenshot 2021-06-11 090503](https://user-images.githubusercontent.com/28649121/121645135-233b6e00-ca94-11eb-9352-ceb2c729b92c.jpg)

**Steps to reproduce:**

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/792.
