### ISSUE TITLE
Layer icon is not updated after applying a mask

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#982]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Issue description:**

1. Fill the first layer with some color
2. Add a mask and paint on itsuch that it looks like this

![Screenshot 2021-06-11 090652](https://user-images.githubusercontent.com/28649121/121645564-9fce4c80-ca94-11eb-8cce-3c2fc5f7bdf8.jpg)

3. Apply the mask and realize that the layer icon is not updated.

![grafik](https://user-images.githubusercontent.com/28649121/121645698-c8564680-ca94-11eb-92d4-e2c58df964ec.png)

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/c73900d746baba71f10b0e37d460d31b3dbf180a.
