### ISSUE TITLE
Merge down the first layer on a mask freezes ArmorPaint

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#983]
I hope I do not demotivate you by my last bug report flood. It might look different but actually the new layer system is working great in most situations and a huge improvement of ArmorPaint.

**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Issue description:**

1. Create a mask for the first layer
2. Right click on the first layer and merge it down to the mask

Now ArmorPaint freezes. Clearly it makes no sense to merge it down on a mask (at least in my opinion). I think the problem is again that ArmorPaint does not correctly detect that the bottom most layer is the bottom most layer if it has a mask.

For other layers it works as expected.

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/e998e20f13bb31efe85b767338753284254c0132.
