### ISSUE TITLE
Duplicating a layer with mask should duplicate the mask, too

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#984]
Currently if ArmorPaint has a layer with mask and the layer is duplicated, its mask is not. In my opinion this should not be the case. The mask should be duplicated as well.

The same holds for groups containing a layer with a mask. If the group is duplicated, the masks of the layers should be as well. If #797 is implemented the same should hold for the group masks.

**Comment by lassiiter** [comment]
@MathemanFlo Im trying to work on this feature, im new to haxe. Can you help me understand how I can log / print while opening the project in Microsoft visual studio. I tried using trace but wasnt able to find where the output was stored

**Comment by MathemanFlo** [comment]
Hey,
If you only want to log out some info, you can use the ArmorPaint console. It is on the buttom of ArmorPaint'UI (browser, console, script).
You can print out info by arm.Console.log("test"); and  arrm.Console.error("..."); and so on.

@luboslenco Maybe it would be a good idea to have a best practise guid to choose an IDE for ArmorPaint and how to contribute? Maybe an additional section similar to how to compile.

**Comment by lassiiter** [comment]
@MathemanFlo Thanks for the help :) do you have  a twitter or discord where I can poke you if I have questions?

**Comment by lassiiter** [comment]
@luboslenco Should this be implemented in the TabLayer class under the duplication logic or under the LayerSlot class duplicate()? Current solution is doing logic in the TabLayers, seems like it would make more sense to move it under the LayerSlot class in duplicate(). That way you can just call "duplicate()" on anything

**Comment by luboslenco** [comment]
https://github.com/armory3d/armorpaint/pull/1022
