### ISSUE TITLE
Redo duplicate groups is not done in one step

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#985]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

Create a layer group like this
![grafik](https://user-images.githubusercontent.com/28649121/121649835-3d2b7f80-ca99-11eb-85a7-7103c92a406c.png)
Duplicating the whole group and pressing ctrl+z yields this result
![grafik](https://user-images.githubusercontent.com/28649121/121650190-9a273580-ca99-11eb-9c32-f6461f65fe99.png)
One has to redo multiple times to be at the initial state.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/792.
