### ISSUE TITLE
Undo group merge does not restore the group

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#986]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Issue description:**
Undo merging a group does not restore the group itsef but only its layers.

1. Create a group with two or more layers.
2. Merge the group
3. Undo merging, the layers are restored but not the group itself

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/792.
