### ISSUE TITLE
Undo merge group with masks in layers freezes ArmorPaint

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#987]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Steps to reproduce:**
1. Build the following situation
![grafik](https://user-images.githubusercontent.com/28649121/121651959-77961c00-ca9b-11eb-8ee3-dec6d8d284bc.png)
2. Merge the group (it works as expected)
3. Undo merging freezes ArmorPaint

Maybe it is related to  #981

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/792.
