### ISSUE TITLE
A group containg all layers can be deleted

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#988]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Issue description:**
A group containg all layers can be deleted and therefore also remove the last layer.

**Steps to reproduce:**
Build something like this
![grafik](https://user-images.githubusercontent.com/28649121/121652881-68639e00-ca9c-11eb-95d1-9263b1990334.png)
Delete the group and get this one:
![grafik](https://user-images.githubusercontent.com/28649121/121652936-76b1ba00-ca9c-11eb-833f-d243018075ca.png)
Being in this state does not make ArmorPaint unusable because a new Layer can be created but ArmorPaint is not built for having no Layer at all. For instance trying to open the 2d view freezes ArmorPaint. 

I can imagine two meaningful ways to prevent this:

1. Allow to delete all Layers. Most of the features seem to work without any layers. It is not so easy to crash ArmorPaint in this state. This would also simplify the case distinctions you have to make for allowed layer operations.
2. Prevent deleting the last group if all remaining layers are in it.

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/6671854e1bf6f904c4483900c6929b22e0a40536.
