### ISSUE TITLE
mesh is broken when importing

### ISSUE THREAD

**Issue by BananaCake2Day** [armory3d/armorpaint#99]
![image](https://user-images.githubusercontent.com/13282174/57183792-29f06380-6e80-11e9-88e8-0f3f1767815d.png)
Here's an image of this rock for a platforming segment.
![image](https://user-images.githubusercontent.com/13282174/57183804-3bd20680-6e80-11e9-809c-a025d06dba9c.png)
Here's the same rock mutilated in ArmorPaint. I have no idea what happens between exporting and importing but this seemed like the place to ask. Why is the mesh so broken up?
![image](https://user-images.githubusercontent.com/13282174/57183827-818ecf00-6e80-11e9-95cc-f12b14534624.png)
This triangle seems like the one issue with the mesh. Everything else works as expected except for this one triangle and the vertex captured in it's area of effect. I don't know why it's there.

**Comment by luboslenco** [comment]
Hi, are you able to paste the `.obj` file? Will take a look and fix asap, thanks!
