### ISSUE TITLE
Clearing a group is not idempotent

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#990]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**OS/device including version:**

**Issue description:**
In my understanding Clear is an idempotent operation. If clear is called multiple times on a layer group, it changes in subsequent calls of clear.

**Steps to reproduce:**
Build this one
![grafik](https://user-images.githubusercontent.com/28649121/121655914-43bcf580-ca9f-11eb-8e2b-124b179ff20d.png)
Now click on Clear in the group context menu.
Then I get this result:
![grafik](https://user-images.githubusercontent.com/28649121/121656006-5800f280-ca9f-11eb-8f3f-10f71329d139.png)
Clicking again yields
![grafik](https://user-images.githubusercontent.com/28649121/121656090-68b16880-ca9f-11eb-9ddb-7e913d8d36ca.png)
Again yields
![grafik](https://user-images.githubusercontent.com/28649121/121656134-76ff8480-ca9f-11eb-8848-1d75fe395bf3.png)

You can repeat this game as often as you want to.

Edit: This has actually nothing to do with the mask shown in the images. It can be skipped and the problem still remains.

**Comment by MathemanFlo** [comment]
And I have a question: Is it intentional that clearing a group does not clear the masks? I think it is not a bad idea after all because clearing a layer does also not clear its mask.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/eba4ad60dcf88135f8ec070e1e5cea3eeb9bbc74.
