### ISSUE TITLE
Export for layer groups does not work

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#991]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**OS/device including version:**
Win10 x64

**Issue description:**
Exporting a layer group gives a blank export result.

**Steps to reproduce:**
Build something like this
![grafik](https://user-images.githubusercontent.com/28649121/121657464-b7133700-caa0-11eb-873c-9674ea0b5ec5.png)
Export the group and get 
![grafik](https://user-images.githubusercontent.com/28649121/121657526-c4c8bc80-caa0-11eb-96b7-cdf3118ec889.png)

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/229498a7ba11bee46f2b4aa880798e6b757916a2.
