### ISSUE TITLE
Export mask does not work

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#992]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Issue description:**
Exporting a _non_ empty mask results in a empty exported texture. 

1. Create a non empty mask
2. Export it
3. The mask is correctly exported in terms of files. I.e. no roughness and so on is created but only the mask itself but the file is empty (black) for me.

**Comment by MathemanFlo** [comment]
The same holds for fill masks but this is probably the very same issue.

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/8c849fd981555e21f1a0b7f2455493b17f4918a1.
