### ISSUE TITLE
What is the purpose of "to fill layer"?

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#993]
A mask can be converted to a fill layer. At the moment this operation seems to be equivalent to:

1. Remove the current mask (and therefore loose the mask content)
2. Create a fill layer with the currently selected material
I have the impression this does not really make sense. Because the opposite operation (to paint layer) actually behaves differently. It takes the current fill layer and converts it to a paint layer. The visual appearance is not immediately affected but one can paint on the mask now. (which makes sense in my opinion) Inuitively the two operations are opponents and should neutralize each others but they can not for the reasons described above.

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/4afb8bfdbc739ca5ae723cf7a6b323554b0dedaa.
