### ISSUE TITLE
Duplicate a layer mask puts the mask on top

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#995]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Issue description:**
Duplicate a layer mask puts the mask on top

**Steps to reproduce:**
1. Create a layer and fill it with a color
2. Create a mask for the layer and add some pattern
3. Duplicate the mask
The duplicated mask is now on top (It should not be there). By painting on it one can see that the mask gives unexpected results.
Here is a image of the final result
![grafik](https://user-images.githubusercontent.com/28649121/121667280-67396d80-caaa-11eb-8f58-034c1572177b.png)

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/e72478bef0d1f57cecfedfc032a0ffac5b3f76d4.
