### ISSUE TITLE
Layer mask node has a red color as preview

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#996]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Issue description:**
Layer mask node has a red color as preview

**Steps to reproduce:**
1. Create a mask with some pattern for Layer 1
2. Create a new material and add a Layer Mask node for the mask. It produces a grey scale result on the textures as expected but the preview is red.
![grafik](https://user-images.githubusercontent.com/28649121/121669283-74eff280-caac-11eb-9bb2-6f5c8a72025d.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorpaint/commit/f3c045d51f9a0576f9d5573acddbe67f2f64b587.
