### ISSUE TITLE
UX issue: Can not drag and drop Layer (mask) of fill mask/layer on material

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#997]
**ArmorPaint version:**
ArmorPaint.org - v0.8 (2021-06-11) - 7e5de6e

**Issue description:**
Fill masks and fill layers have the nice property that selecting them automatically selects their corresponding material. In most cases this is the best behavior but it complicates creating a Layer node or a Layer mask node by drag and drop because merly clicking on these layers to drag them in the node editor selects a different material. 
To be honest I have no good solution for this issue and maybe the resolution is to simply change nothing at all....

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armorpaint/commit/238ac27f6a5e3fabd46be9e78008cd3ca412fdb5.
