### ISSUE TITLE
Imported mesh has artifacts and invisible faces

### ISSUE THREAD

**Issue by bhibb** [armory3d/armorpaint#998]
**ArmorPaint version:**

ArmorPaint.org - v0.8 (2021-05-01) - 7679640
Linux - OpenGL

**OS/device including version:**

Linux Solus 4.2 Budgie. Kernel 5.12.10-182.current. Nvidia GeForce GTX TITAN X with proprietary Nvidia drivers (up to date).

**Issue description:**

An imported mesh (.blend or .fbx) has artifacts and some invisible faces from certain angles when panning in armorpaint viewport.

**Steps to reproduce:**

1. Save .blend project with a single (or all) pieces of a mesh.
2. Import the mesh into ArmorPaint via Files -> Import Mesh and select the blend file.
3. Observe object issues where some faces are invisible from certain angles, also, the bottom face becomes noisy.
4. Export the selected mesh from Blender into a .fbx file
5. Import the .fbx file into ArmorPaint
6. Observe the same issue exists with the imported mesh.

In ArmorPaint:
![image](https://user-images.githubusercontent.com/33728168/121786430-3c850d00-cbaf-11eb-9d67-4042e3301da8.png)
In Blender:
![image](https://user-images.githubusercontent.com/33728168/121786441-4d358300-cbaf-11eb-84d1-ef7b1aa34a23.png)

Note: There are no modifiers on the mesh, just a simple plane extruded and beveled.
![image](https://user-images.githubusercontent.com/33728168/121786504-bb7a4580-cbaf-11eb-919f-9423767af759.png)

**Comment by luboslenco** [comment]
Hello, thanks for report. Check out https://github.com/armory3d/armorpaint/issues/807 and [FAQ](https://github.com/armory3d/armorpaint_docs/blob/master/faq.md) for a fix. If that does not help please share the test file if possible and I will investigate. Also make sure to use the latest ArmorPaint version.

**Comment by bhibb** [comment]
Thank you the normal recalculation did the trick.
