### ISSUE TITLE
can WinTab api be supported in ArmorPaint

### ISSUE THREAD

**Issue by ABugNamedBeetle** [armory3d/armorpaint#999]
https://user-images.githubusercontent.com/62416701/121814452-d53e8a00-cc8e-11eb-887c-1d22b5ea618d.mp4

My issues are following (though I might be doing something wrong):
1> Sometime tablet input won't be registers (to visualize i have turn on the Visual Effects for pen)
2> Sometime dragging through slider the slider and text field are both selected. 

Both of these disappear, when i turn off the windows ink check box. But then pen pressure won't work.
Is there a possibility the WinTab api be supported.

**Comment by luboslenco** [comment]
Should be able to fix that, thanks for report. Investigating together with https://github.com/armory3d/armorpaint/issues/853.
